# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TFRPlotDialogUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TFRPlotDialog(object):
    def setupUi(self, TFRPlotDialog):
        TFRPlotDialog.setObjectName("TFRPlotDialog")
        TFRPlotDialog.resize(546, 524)
        self.gridLayout_2 = QtWidgets.QGridLayout(TFRPlotDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(TFRPlotDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(TFRPlotDialog)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 528, 474))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBoxBaseline = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxBaseline.setObjectName("groupBoxBaseline")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBoxBaseline)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.labelBaselineCorrection = QtWidgets.QLabel(self.groupBoxBaseline)
        self.labelBaselineCorrection.setObjectName("labelBaselineCorrection")
        self.gridLayout_9.addWidget(self.labelBaselineCorrection, 0, 0, 1, 1)
        self.doubleSpinBoxBaselineStart = QtWidgets.QDoubleSpinBox(self.groupBoxBaseline)
        self.doubleSpinBoxBaselineStart.setObjectName("doubleSpinBoxBaselineStart")
        self.gridLayout_9.addWidget(self.doubleSpinBoxBaselineStart, 2, 1, 1, 1)
        self.doubleSpinBoxBaselineEnd = QtWidgets.QDoubleSpinBox(self.groupBoxBaseline)
        self.doubleSpinBoxBaselineEnd.setObjectName("doubleSpinBoxBaselineEnd")
        self.gridLayout_9.addWidget(self.doubleSpinBoxBaselineEnd, 3, 1, 1, 1)
        self.comboBoxBaselineMode = QtWidgets.QComboBox(self.groupBoxBaseline)
        self.comboBoxBaselineMode.setObjectName("comboBoxBaselineMode")
        self.comboBoxBaselineMode.addItem("")
        self.comboBoxBaselineMode.addItem("")
        self.comboBoxBaselineMode.addItem("")
        self.comboBoxBaselineMode.addItem("")
        self.comboBoxBaselineMode.addItem("")
        self.gridLayout_9.addWidget(self.comboBoxBaselineMode, 1, 1, 1, 1)
        self.labelBaselineStart = QtWidgets.QLabel(self.groupBoxBaseline)
        self.labelBaselineStart.setObjectName("labelBaselineStart")
        self.gridLayout_9.addWidget(self.labelBaselineStart, 2, 0, 1, 1)
        self.labelBaselineEnd = QtWidgets.QLabel(self.groupBoxBaseline)
        self.labelBaselineEnd.setObjectName("labelBaselineEnd")
        self.gridLayout_9.addWidget(self.labelBaselineEnd, 3, 0, 1, 1)
        self.labelBaselineMode = QtWidgets.QLabel(self.groupBoxBaseline)
        self.labelBaselineMode.setObjectName("labelBaselineMode")
        self.gridLayout_9.addWidget(self.labelBaselineMode, 1, 0, 1, 1)
        self.checkBoxBaselineCorrection = QtWidgets.QCheckBox(self.groupBoxBaseline)
        self.checkBoxBaselineCorrection.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBoxBaselineCorrection.setText("")
        self.checkBoxBaselineCorrection.setChecked(True)
        self.checkBoxBaselineCorrection.setObjectName("checkBoxBaselineCorrection")
        self.gridLayout_9.addWidget(self.checkBoxBaselineCorrection, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxBaseline, 2, 0, 1, 1)
        self.groupBoxOutputOptions = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxOutputOptions.setObjectName("groupBoxOutputOptions")
        self.formLayout = QtWidgets.QFormLayout(self.groupBoxOutputOptions)
        self.formLayout.setObjectName("formLayout")
        self.labelChannels = QtWidgets.QLabel(self.groupBoxOutputOptions)
        self.labelChannels.setObjectName("labelChannels")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelChannels)
        self.radioButtonAllChannels = QtWidgets.QRadioButton(self.groupBoxOutputOptions)
        self.radioButtonAllChannels.setChecked(True)
        self.radioButtonAllChannels.setObjectName("radioButtonAllChannels")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.radioButtonAllChannels)
        self.radioButtonChannelAverages = QtWidgets.QRadioButton(self.groupBoxOutputOptions)
        self.radioButtonChannelAverages.setObjectName("radioButtonChannelAverages")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.radioButtonChannelAverages)
        self.labelCondition = QtWidgets.QLabel(self.groupBoxOutputOptions)
        self.labelCondition.setObjectName("labelCondition")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelCondition)
        self.comboBoxCondition = QtWidgets.QComboBox(self.groupBoxOutputOptions)
        self.comboBoxCondition.setObjectName("comboBoxCondition")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBoxCondition)
        self.gridLayout_4.addWidget(self.groupBoxOutputOptions, 4, 0, 1, 1)
        self.groupBoxCrop = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxCrop.setObjectName("groupBoxCrop")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxCrop)
        self.gridLayout.setObjectName("gridLayout")
        self.labelCropMaxFreq = QtWidgets.QLabel(self.groupBoxCrop)
        self.labelCropMaxFreq.setObjectName("labelCropMaxFreq")
        self.gridLayout.addWidget(self.labelCropMaxFreq, 1, 0, 1, 1)
        self.labelCropMinFreq = QtWidgets.QLabel(self.groupBoxCrop)
        self.labelCropMinFreq.setObjectName("labelCropMinFreq")
        self.gridLayout.addWidget(self.labelCropMinFreq, 0, 0, 1, 1)
        self.doubleSpinBoxCropMinFreq = QtWidgets.QDoubleSpinBox(self.groupBoxCrop)
        self.doubleSpinBoxCropMinFreq.setSingleStep(0.1)
        self.doubleSpinBoxCropMinFreq.setObjectName("doubleSpinBoxCropMinFreq")
        self.gridLayout.addWidget(self.doubleSpinBoxCropMinFreq, 0, 1, 1, 1)
        self.doubleSpinBoxCropMaxFreq = QtWidgets.QDoubleSpinBox(self.groupBoxCrop)
        self.doubleSpinBoxCropMaxFreq.setSingleStep(0.1)
        self.doubleSpinBoxCropMaxFreq.setObjectName("doubleSpinBoxCropMaxFreq")
        self.gridLayout.addWidget(self.doubleSpinBoxCropMaxFreq, 1, 1, 1, 1)
        self.labelCropStart = QtWidgets.QLabel(self.groupBoxCrop)
        self.labelCropStart.setObjectName("labelCropStart")
        self.gridLayout.addWidget(self.labelCropStart, 2, 0, 1, 1)
        self.doubleSpinBoxCropStart = QtWidgets.QDoubleSpinBox(self.groupBoxCrop)
        self.doubleSpinBoxCropStart.setSingleStep(0.1)
        self.doubleSpinBoxCropStart.setObjectName("doubleSpinBoxCropStart")
        self.gridLayout.addWidget(self.doubleSpinBoxCropStart, 2, 1, 1, 1)
        self.labelCropEnd = QtWidgets.QLabel(self.groupBoxCrop)
        self.labelCropEnd.setObjectName("labelCropEnd")
        self.gridLayout.addWidget(self.labelCropEnd, 3, 0, 1, 1)
        self.doubleSpinBoxCropEnd = QtWidgets.QDoubleSpinBox(self.groupBoxCrop)
        self.doubleSpinBoxCropEnd.setMinimum(0.0)
        self.doubleSpinBoxCropEnd.setSingleStep(0.1)
        self.doubleSpinBoxCropEnd.setProperty("value", 0.0)
        self.doubleSpinBoxCropEnd.setObjectName("doubleSpinBoxCropEnd")
        self.gridLayout.addWidget(self.doubleSpinBoxCropEnd, 3, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxCrop, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 5, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(TFRPlotDialog)
        self.buttonBox.accepted.connect(TFRPlotDialog.accept)
        self.buttonBox.rejected.connect(TFRPlotDialog.reject)
        self.checkBoxBaselineCorrection.toggled['bool'].connect(self.comboBoxBaselineMode.setEnabled)
        self.checkBoxBaselineCorrection.toggled['bool'].connect(self.doubleSpinBoxBaselineStart.setEnabled)
        self.checkBoxBaselineCorrection.toggled['bool'].connect(self.doubleSpinBoxBaselineEnd.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(TFRPlotDialog)
        TFRPlotDialog.setTabOrder(self.scrollArea, self.buttonBox)

    def retranslateUi(self, TFRPlotDialog):
        _translate = QtCore.QCoreApplication.translate
        TFRPlotDialog.setWindowTitle(_translate("TFRPlotDialog", "Meggie - Plot TFR"))
        self.groupBoxBaseline.setTitle(_translate("TFRPlotDialog", "Baseline"))
        self.labelBaselineCorrection.setText(_translate("TFRPlotDialog", "Baseline correction:"))
        self.comboBoxBaselineMode.setItemText(0, _translate("TFRPlotDialog", "mean"))
        self.comboBoxBaselineMode.setItemText(1, _translate("TFRPlotDialog", "ratio"))
        self.comboBoxBaselineMode.setItemText(2, _translate("TFRPlotDialog", "logratio"))
        self.comboBoxBaselineMode.setItemText(3, _translate("TFRPlotDialog", "percent"))
        self.comboBoxBaselineMode.setItemText(4, _translate("TFRPlotDialog", "zscore"))
        self.labelBaselineStart.setText(_translate("TFRPlotDialog", "Baseline start (s):"))
        self.labelBaselineEnd.setText(_translate("TFRPlotDialog", "Baseline end (s):"))
        self.labelBaselineMode.setText(_translate("TFRPlotDialog", "Baseline mode:"))
        self.groupBoxOutputOptions.setTitle(_translate("TFRPlotDialog", "Output options"))
        self.labelChannels.setText(_translate("TFRPlotDialog", "Type:"))
        self.radioButtonAllChannels.setText(_translate("TFRPlotDialog", "All channels"))
        self.radioButtonChannelAverages.setText(_translate("TFRPlotDialog", "Channel averages"))
        self.labelCondition.setText(_translate("TFRPlotDialog", "Condition:"))
        self.groupBoxCrop.setTitle(_translate("TFRPlotDialog", "Crop"))
        self.labelCropMaxFreq.setText(_translate("TFRPlotDialog", "Maximum frequency (Hz):"))
        self.labelCropMinFreq.setText(_translate("TFRPlotDialog", "Minimum frequency (Hz):"))
        self.labelCropStart.setText(_translate("TFRPlotDialog", "Start (s):"))
        self.labelCropEnd.setText(_translate("TFRPlotDialog", "End (s):"))

