# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TSEPlotDialogUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TSEPlotDialog(object):
    def setupUi(self, TSEPlotDialog):
        TSEPlotDialog.setObjectName("TSEPlotDialog")
        TSEPlotDialog.resize(556, 478)
        self.gridLayout_2 = QtWidgets.QGridLayout(TSEPlotDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(TSEPlotDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(TSEPlotDialog)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 538, 428))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBoxCrop = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxCrop.setObjectName("groupBoxCrop")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxCrop)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelCropStart = QtWidgets.QLabel(self.groupBoxCrop)
        self.labelCropStart.setObjectName("labelCropStart")
        self.gridLayout_3.addWidget(self.labelCropStart, 0, 0, 1, 1)
        self.doubleSpinBoxCropStart = QtWidgets.QDoubleSpinBox(self.groupBoxCrop)
        self.doubleSpinBoxCropStart.setObjectName("doubleSpinBoxCropStart")
        self.gridLayout_3.addWidget(self.doubleSpinBoxCropStart, 0, 1, 1, 1)
        self.labelCropEnd = QtWidgets.QLabel(self.groupBoxCrop)
        self.labelCropEnd.setObjectName("labelCropEnd")
        self.gridLayout_3.addWidget(self.labelCropEnd, 1, 0, 1, 1)
        self.doubleSpinBoxCropEnd = QtWidgets.QDoubleSpinBox(self.groupBoxCrop)
        self.doubleSpinBoxCropEnd.setObjectName("doubleSpinBoxCropEnd")
        self.gridLayout_3.addWidget(self.doubleSpinBoxCropEnd, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxCrop, 3, 0, 1, 1)
        self.groupBoxBaseline = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxBaseline.setObjectName("groupBoxBaseline")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBoxBaseline)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.labelBaselineStart = QtWidgets.QLabel(self.groupBoxBaseline)
        self.labelBaselineStart.setObjectName("labelBaselineStart")
        self.gridLayout_9.addWidget(self.labelBaselineStart, 0, 0, 1, 1)
        self.labelBaselineEnd = QtWidgets.QLabel(self.groupBoxBaseline)
        self.labelBaselineEnd.setObjectName("labelBaselineEnd")
        self.gridLayout_9.addWidget(self.labelBaselineEnd, 1, 0, 1, 1)
        self.doubleSpinBoxBaselineEnd = QtWidgets.QDoubleSpinBox(self.groupBoxBaseline)
        self.doubleSpinBoxBaselineEnd.setMinimum(-99.0)
        self.doubleSpinBoxBaselineEnd.setSingleStep(0.1)
        self.doubleSpinBoxBaselineEnd.setObjectName("doubleSpinBoxBaselineEnd")
        self.gridLayout_9.addWidget(self.doubleSpinBoxBaselineEnd, 1, 1, 1, 1)
        self.doubleSpinBoxBaselineStart = QtWidgets.QDoubleSpinBox(self.groupBoxBaseline)
        self.doubleSpinBoxBaselineStart.setMinimum(-99.99)
        self.doubleSpinBoxBaselineStart.setSingleStep(0.1)
        self.doubleSpinBoxBaselineStart.setObjectName("doubleSpinBoxBaselineStart")
        self.gridLayout_9.addWidget(self.doubleSpinBoxBaselineStart, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxBaseline, 2, 0, 1, 1)
        self.groupBoxAveraging = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxAveraging.setObjectName("groupBoxAveraging")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxAveraging)
        self.gridLayout.setObjectName("gridLayout")
        self.labelAveMinFreq = QtWidgets.QLabel(self.groupBoxAveraging)
        self.labelAveMinFreq.setObjectName("labelAveMinFreq")
        self.gridLayout.addWidget(self.labelAveMinFreq, 0, 0, 1, 1)
        self.doubleSpinBoxAveMinFreq = QtWidgets.QDoubleSpinBox(self.groupBoxAveraging)
        self.doubleSpinBoxAveMinFreq.setMaximum(999.99)
        self.doubleSpinBoxAveMinFreq.setObjectName("doubleSpinBoxAveMinFreq")
        self.gridLayout.addWidget(self.doubleSpinBoxAveMinFreq, 0, 1, 1, 1)
        self.labelAveMaxFreq = QtWidgets.QLabel(self.groupBoxAveraging)
        self.labelAveMaxFreq.setObjectName("labelAveMaxFreq")
        self.gridLayout.addWidget(self.labelAveMaxFreq, 1, 0, 1, 1)
        self.doubleSpinBoxAveMaxFreq = QtWidgets.QDoubleSpinBox(self.groupBoxAveraging)
        self.doubleSpinBoxAveMaxFreq.setMaximum(999.99)
        self.doubleSpinBoxAveMaxFreq.setObjectName("doubleSpinBoxAveMaxFreq")
        self.gridLayout.addWidget(self.doubleSpinBoxAveMaxFreq, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxAveraging, 4, 0, 1, 1)
        self.groupBoxOutputOptions = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxOutputOptions.setObjectName("groupBoxOutputOptions")
        self.formLayout = QtWidgets.QFormLayout(self.groupBoxOutputOptions)
        self.formLayout.setObjectName("formLayout")
        self.labelChannels = QtWidgets.QLabel(self.groupBoxOutputOptions)
        self.labelChannels.setObjectName("labelChannels")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelChannels)
        self.radioButtonAllChannels = QtWidgets.QRadioButton(self.groupBoxOutputOptions)
        self.radioButtonAllChannels.setChecked(True)
        self.radioButtonAllChannels.setObjectName("radioButtonAllChannels")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.radioButtonAllChannels)
        self.radioButtonChannelAverages = QtWidgets.QRadioButton(self.groupBoxOutputOptions)
        self.radioButtonChannelAverages.setObjectName("radioButtonChannelAverages")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.radioButtonChannelAverages)
        self.gridLayout_4.addWidget(self.groupBoxOutputOptions, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 6, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(TSEPlotDialog)
        self.buttonBox.accepted.connect(TSEPlotDialog.accept)
        self.buttonBox.rejected.connect(TSEPlotDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(TSEPlotDialog)
        TSEPlotDialog.setTabOrder(self.scrollArea, self.buttonBox)

    def retranslateUi(self, TSEPlotDialog):
        _translate = QtCore.QCoreApplication.translate
        TSEPlotDialog.setWindowTitle(_translate("TSEPlotDialog", "Meggie - Plot TSE"))
        self.groupBoxCrop.setTitle(_translate("TSEPlotDialog", "Crop"))
        self.labelCropStart.setText(_translate("TSEPlotDialog", "Start (s):"))
        self.labelCropEnd.setText(_translate("TSEPlotDialog", "End (s):"))
        self.groupBoxBaseline.setTitle(_translate("TSEPlotDialog", "Baseline"))
        self.labelBaselineStart.setText(_translate("TSEPlotDialog", "Baseline start (s):"))
        self.labelBaselineEnd.setText(_translate("TSEPlotDialog", "Baseline end (s):"))
        self.groupBoxAveraging.setTitle(_translate("TSEPlotDialog", "Averaging"))
        self.labelAveMinFreq.setText(_translate("TSEPlotDialog", "Minimum frequency (Hz):"))
        self.labelAveMaxFreq.setText(_translate("TSEPlotDialog", "Maximum frequency (Hz):"))
        self.groupBoxOutputOptions.setTitle(_translate("TSEPlotDialog", "Output options"))
        self.labelChannels.setText(_translate("TSEPlotDialog", "Type:"))
        self.radioButtonAllChannels.setText(_translate("TSEPlotDialog", "All channels"))
        self.radioButtonChannelAverages.setText(_translate("TSEPlotDialog", "Channel averages"))

