# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'powerSpectrumDialogUi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PowerSpectrumDialog(object):
    def setupUi(self, PowerSpectrumDialog):
        PowerSpectrumDialog.setObjectName(_fromUtf8("PowerSpectrumDialog"))
        PowerSpectrumDialog.resize(888, 377)
        self.gridLayout = QtGui.QGridLayout(PowerSpectrumDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBoxConditions = QtGui.QGroupBox(PowerSpectrumDialog)
        self.groupBoxConditions.setObjectName(_fromUtf8("groupBoxConditions"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxConditions)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelFmin = QtGui.QLabel(self.groupBoxConditions)
        self.labelFmin.setObjectName(_fromUtf8("labelFmin"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelFmin)
        self.spinBoxFmin = QtGui.QSpinBox(self.groupBoxConditions)
        self.spinBoxFmin.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBoxFmin.setObjectName(_fromUtf8("spinBoxFmin"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBoxFmin)
        self.labelFmax = QtGui.QLabel(self.groupBoxConditions)
        self.labelFmax.setObjectName(_fromUtf8("labelFmax"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelFmax)
        self.spinBoxFmax = QtGui.QSpinBox(self.groupBoxConditions)
        self.spinBoxFmax.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBoxFmax.setMaximum(150)
        self.spinBoxFmax.setProperty("value", 40)
        self.spinBoxFmax.setObjectName(_fromUtf8("spinBoxFmax"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.spinBoxFmax)
        self.labelChannels = QtGui.QLabel(self.groupBoxConditions)
        self.labelChannels.setObjectName(_fromUtf8("labelChannels"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelChannels)
        self.comboBoxChannels = QtGui.QComboBox(self.groupBoxConditions)
        self.comboBoxChannels.setObjectName(_fromUtf8("comboBoxChannels"))
        self.comboBoxChannels.addItem(_fromUtf8(""))
        self.comboBoxChannels.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.comboBoxChannels)
        self.horizontalLayout_5.addLayout(self.formLayout_2)
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.labelNfft = QtGui.QLabel(self.groupBoxConditions)
        self.labelNfft.setObjectName(_fromUtf8("labelNfft"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelNfft)
        self.spinBoxNfft = QtGui.QSpinBox(self.groupBoxConditions)
        self.spinBoxNfft.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBoxNfft.setMaximum(10000)
        self.spinBoxNfft.setProperty("value", 2048)
        self.spinBoxNfft.setObjectName(_fromUtf8("spinBoxNfft"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBoxNfft)
        self.labelOverlap = QtGui.QLabel(self.groupBoxConditions)
        self.labelOverlap.setObjectName(_fromUtf8("labelOverlap"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelOverlap)
        self.spinBoxOverlap = QtGui.QSpinBox(self.groupBoxConditions)
        self.spinBoxOverlap.setMaximum(10000)
        self.spinBoxOverlap.setProperty("value", 1024)
        self.spinBoxOverlap.setObjectName(_fromUtf8("spinBoxOverlap"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBoxOverlap)
        self.checkBoxLogarithm = QtGui.QCheckBox(self.groupBoxConditions)
        self.checkBoxLogarithm.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxLogarithm.setAutoFillBackground(False)
        self.checkBoxLogarithm.setChecked(True)
        self.checkBoxLogarithm.setObjectName(_fromUtf8("checkBoxLogarithm"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.checkBoxLogarithm)
        self.checkBoxSaveData = QtGui.QCheckBox(self.groupBoxConditions)
        self.checkBoxSaveData.setObjectName(_fromUtf8("checkBoxSaveData"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.checkBoxSaveData)
        self.horizontalLayout_5.addLayout(self.formLayout_6)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_27 = QtGui.QVBoxLayout()
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.radioButtonSelectLayout = QtGui.QRadioButton(self.groupBoxConditions)
        self.radioButtonSelectLayout.setChecked(True)
        self.radioButtonSelectLayout.setObjectName(_fromUtf8("radioButtonSelectLayout"))
        self.horizontalLayout_35.addWidget(self.radioButtonSelectLayout)
        self.comboBoxLayout = QtGui.QComboBox(self.groupBoxConditions)
        self.comboBoxLayout.setObjectName(_fromUtf8("comboBoxLayout"))
        self.comboBoxLayout.addItem(_fromUtf8(""))
        self.horizontalLayout_35.addWidget(self.comboBoxLayout)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.radioButtonLayoutFromFile = QtGui.QRadioButton(self.groupBoxConditions)
        self.radioButtonLayoutFromFile.setObjectName(_fromUtf8("radioButtonLayoutFromFile"))
        self.horizontalLayout_36.addWidget(self.radioButtonLayoutFromFile)
        self.pushButtonBrowseLayout = QtGui.QPushButton(self.groupBoxConditions)
        self.pushButtonBrowseLayout.setEnabled(False)
        self.pushButtonBrowseLayout.setObjectName(_fromUtf8("pushButtonBrowseLayout"))
        self.horizontalLayout_36.addWidget(self.pushButtonBrowseLayout)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_36)
        self.verticalLayout_27.addLayout(self.horizontalLayout_35)
        self.labelLayout = QtGui.QLabel(self.groupBoxConditions)
        self.labelLayout.setEnabled(False)
        self.labelLayout.setObjectName(_fromUtf8("labelLayout"))
        self.verticalLayout_27.addWidget(self.labelLayout)
        self.horizontalLayout_6.addLayout(self.verticalLayout_27)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.line = QtGui.QFrame(self.groupBoxConditions)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 2, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.groupBoxConditions)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 7, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelTmin = QtGui.QLabel(self.groupBoxConditions)
        self.labelTmin.setObjectName(_fromUtf8("labelTmin"))
        self.horizontalLayout.addWidget(self.labelTmin)
        self.spinBoxTmin = QtGui.QSpinBox(self.groupBoxConditions)
        self.spinBoxTmin.setObjectName(_fromUtf8("spinBoxTmin"))
        self.horizontalLayout.addWidget(self.spinBoxTmin)
        self.labelTmax = QtGui.QLabel(self.groupBoxConditions)
        self.labelTmax.setObjectName(_fromUtf8("labelTmax"))
        self.horizontalLayout.addWidget(self.labelTmax)
        self.spinBoxTmax = QtGui.QSpinBox(self.groupBoxConditions)
        self.spinBoxTmax.setObjectName(_fromUtf8("spinBoxTmax"))
        self.horizontalLayout.addWidget(self.spinBoxTmax)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxConditions, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(PowerSpectrumDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.NoButton)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButtonReject = QtGui.QPushButton(PowerSpectrumDialog)
        self.pushButtonReject.setObjectName(_fromUtf8("pushButtonReject"))
        self.horizontalLayout_2.addWidget(self.pushButtonReject)
        self.pushButtonAccept = QtGui.QPushButton(PowerSpectrumDialog)
        self.pushButtonAccept.setObjectName(_fromUtf8("pushButtonAccept"))
        self.horizontalLayout_2.addWidget(self.pushButtonAccept)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)

        self.retranslateUi(PowerSpectrumDialog)
        QtCore.QObject.connect(self.radioButtonLayoutFromFile, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pushButtonBrowseLayout.setEnabled)
        QtCore.QObject.connect(self.radioButtonLayoutFromFile, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.labelLayout.setEnabled)
        QtCore.QObject.connect(self.pushButtonAccept, QtCore.SIGNAL(_fromUtf8("clicked()")), PowerSpectrumDialog.accept)
        QtCore.QObject.connect(self.pushButtonReject, QtCore.SIGNAL(_fromUtf8("clicked()")), PowerSpectrumDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PowerSpectrumDialog)
        PowerSpectrumDialog.setTabOrder(self.spinBoxFmin, self.spinBoxFmax)
        PowerSpectrumDialog.setTabOrder(self.spinBoxFmax, self.comboBoxChannels)
        PowerSpectrumDialog.setTabOrder(self.comboBoxChannels, self.spinBoxNfft)
        PowerSpectrumDialog.setTabOrder(self.spinBoxNfft, self.checkBoxLogarithm)
        PowerSpectrumDialog.setTabOrder(self.checkBoxLogarithm, self.radioButtonSelectLayout)
        PowerSpectrumDialog.setTabOrder(self.radioButtonSelectLayout, self.comboBoxLayout)
        PowerSpectrumDialog.setTabOrder(self.comboBoxLayout, self.radioButtonLayoutFromFile)
        PowerSpectrumDialog.setTabOrder(self.radioButtonLayoutFromFile, self.pushButtonBrowseLayout)
        PowerSpectrumDialog.setTabOrder(self.pushButtonBrowseLayout, self.buttonBox)

    def retranslateUi(self, PowerSpectrumDialog):
        PowerSpectrumDialog.setWindowTitle(_translate("PowerSpectrumDialog", "Power spectrum", None))
        self.groupBoxConditions.setTitle(_translate("PowerSpectrumDialog", "Conditions", None))
        self.labelFmin.setToolTip(_translate("PowerSpectrumDialog", "Set the lower limit for the frequencies.", None))
        self.labelFmin.setText(_translate("PowerSpectrumDialog", "Min frequency of interest:", None))
        self.spinBoxFmin.setToolTip(_translate("PowerSpectrumDialog", "Set the lower limit for the frequencies.", None))
        self.spinBoxFmin.setSuffix(_translate("PowerSpectrumDialog", "Hz", None))
        self.labelFmax.setToolTip(_translate("PowerSpectrumDialog", "Set the upper limit for the frequencies.", None))
        self.labelFmax.setText(_translate("PowerSpectrumDialog", "Max frequency of interest:", None))
        self.spinBoxFmax.setToolTip(_translate("PowerSpectrumDialog", "Set the upper limit for the frequencies.", None))
        self.spinBoxFmax.setSuffix(_translate("PowerSpectrumDialog", "Hz", None))
        self.labelChannels.setText(_translate("PowerSpectrumDialog", "Channels", None))
        self.comboBoxChannels.setItemText(0, _translate("PowerSpectrumDialog", "MEG", None))
        self.comboBoxChannels.setItemText(1, _translate("PowerSpectrumDialog", "EEG", None))
        self.labelNfft.setToolTip(_translate("PowerSpectrumDialog", "<html><head/><body><p>The length of the tapers ie. the windows (hanning). The smaller it is the smoother are the PSDs.</p></body></html>", None))
        self.labelNfft.setText(_translate("PowerSpectrumDialog", "Length of the tapers (ie. the windows):", None))
        self.spinBoxNfft.setToolTip(_translate("PowerSpectrumDialog", "<html><head/><body><p>The length of the tapers ie. the windows (hanning). The smaller it is the smoother are the PSDs.</p></body></html>", None))
        self.labelOverlap.setToolTip(_translate("PowerSpectrumDialog", "<html><head/><body><p>Number of overlapping points between the blocks.</p></body></html>", None))
        self.labelOverlap.setText(_translate("PowerSpectrumDialog", "Overlap", None))
        self.spinBoxOverlap.setToolTip(_translate("PowerSpectrumDialog", "<html><head/><body><p>Number of overlapping points between the blocks.</p></body></html>", None))
        self.checkBoxLogarithm.setToolTip(_translate("PowerSpectrumDialog", "Use logarithmic scale.", None))
        self.checkBoxLogarithm.setText(_translate("PowerSpectrumDialog", "Use logarithmic scale", None))
        self.checkBoxSaveData.setText(_translate("PowerSpectrumDialog", "Save data to file", None))
        self.radioButtonSelectLayout.setText(_translate("PowerSpectrumDialog", "Select layout", None))
        self.comboBoxLayout.setItemText(0, _translate("PowerSpectrumDialog", "Infer from data", None))
        self.radioButtonLayoutFromFile.setText(_translate("PowerSpectrumDialog", "Layout from file", None))
        self.pushButtonBrowseLayout.setText(_translate("PowerSpectrumDialog", "Browse...", None))
        self.labelLayout.setText(_translate("PowerSpectrumDialog", "No layout selected", None))
        self.labelTmin.setText(_translate("PowerSpectrumDialog", "Start time:", None))
        self.labelTmax.setText(_translate("PowerSpectrumDialog", "End time:", None))
        self.pushButtonReject.setText(_translate("PowerSpectrumDialog", "Start", None))
        self.pushButtonAccept.setText(_translate("PowerSpectrumDialog", "Cancel", None))

