# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TFRfromRawDialogUi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogRawTFR(object):
    def setupUi(self, DialogRawTFR):
        DialogRawTFR.setObjectName(_fromUtf8("DialogRawTFR"))
        DialogRawTFR.resize(495, 431)
        self.gridLayout = QtGui.QGridLayout(DialogRawTFR)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(DialogRawTFR)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.comboBoxChannel = QtGui.QComboBox(DialogRawTFR)
        self.comboBoxChannel.setObjectName(_fromUtf8("comboBoxChannel"))
        self.horizontalLayout_5.addWidget(self.comboBoxChannel)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.line_3 = QtGui.QFrame(DialogRawTFR)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(DialogRawTFR)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.spinBoxWsize = QtGui.QSpinBox(DialogRawTFR)
        self.spinBoxWsize.setMaximum(1000000000)
        self.spinBoxWsize.setSingleStep(1)
        self.spinBoxWsize.setProperty("value", 1024)
        self.spinBoxWsize.setObjectName(_fromUtf8("spinBoxWsize"))
        self.horizontalLayout.addWidget(self.spinBoxWsize)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(DialogRawTFR)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.checkBoxTstep = QtGui.QCheckBox(DialogRawTFR)
        self.checkBoxTstep.setChecked(True)
        self.checkBoxTstep.setObjectName(_fromUtf8("checkBoxTstep"))
        self.verticalLayout.addWidget(self.checkBoxTstep)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(DialogRawTFR)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.spinBoxTstep = QtGui.QSpinBox(DialogRawTFR)
        self.spinBoxTstep.setEnabled(False)
        self.spinBoxTstep.setMaximum(1000000000)
        self.spinBoxTstep.setSingleStep(1)
        self.spinBoxTstep.setProperty("value", 512)
        self.spinBoxTstep.setObjectName(_fromUtf8("spinBoxTstep"))
        self.horizontalLayout_2.addWidget(self.spinBoxTstep)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtGui.QFrame(DialogRawTFR)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(DialogRawTFR)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBoxFmin = QtGui.QSpinBox(DialogRawTFR)
        self.spinBoxFmin.setEnabled(True)
        self.spinBoxFmin.setMinimum(0)
        self.spinBoxFmin.setMaximum(1000)
        self.spinBoxFmin.setProperty("value", 1)
        self.spinBoxFmin.setObjectName(_fromUtf8("spinBoxFmin"))
        self.horizontalLayout_3.addWidget(self.spinBoxFmin)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(DialogRawTFR)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.spinBoxFmax = QtGui.QSpinBox(DialogRawTFR)
        self.spinBoxFmax.setEnabled(True)
        self.spinBoxFmax.setMinimum(0)
        self.spinBoxFmax.setMaximum(1000)
        self.spinBoxFmax.setProperty("value", 40)
        self.spinBoxFmax.setObjectName(_fromUtf8("spinBoxFmax"))
        self.horizontalLayout_4.addWidget(self.spinBoxFmax)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line_5 = QtGui.QFrame(DialogRawTFR)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout.addWidget(self.line_5)
        self.checkBoxLogaritmicScale = QtGui.QCheckBox(DialogRawTFR)
        self.checkBoxLogaritmicScale.setChecked(False)
        self.checkBoxLogaritmicScale.setObjectName(_fromUtf8("checkBoxLogaritmicScale"))
        self.verticalLayout.addWidget(self.checkBoxLogaritmicScale)
        self.line_4 = QtGui.QFrame(DialogRawTFR)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout.addWidget(self.line_4)
        self.checkBoxSaveData = QtGui.QCheckBox(DialogRawTFR)
        self.checkBoxSaveData.setObjectName(_fromUtf8("checkBoxSaveData"))
        self.verticalLayout.addWidget(self.checkBoxSaveData)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(DialogRawTFR)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(DialogRawTFR)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DialogRawTFR.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DialogRawTFR.reject)
        QtCore.QObject.connect(self.checkBoxTstep, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spinBoxTstep.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(DialogRawTFR)

    def retranslateUi(self, DialogRawTFR):
        DialogRawTFR.setWindowTitle(_translate("DialogRawTFR", "Meggie - TFR from raw", None))
        self.label_5.setText(_translate("DialogRawTFR", "Select channel:", None))
        self.label.setText(_translate("DialogRawTFR", "Length of the STFT window in samples:", None))
        self.checkBoxTstep.setText(_translate("DialogRawTFR", "Use default step (=window length / 2)", None))
        self.label_2.setText(_translate("DialogRawTFR", "Step between successive windows in samples:", None))
        self.label_3.setText(_translate("DialogRawTFR", "Min frequency:", None))
        self.label_4.setText(_translate("DialogRawTFR", "Max frequency:", None))
        self.checkBoxLogaritmicScale.setText(_translate("DialogRawTFR", "Use logarithmic scale", None))
        self.checkBoxSaveData.setText(_translate("DialogRawTFR", "Save data", None))

