# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TFRfromEpochsUi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogEpochsTFR(object):
    def setupUi(self, DialogEpochsTFR):
        DialogEpochsTFR.setObjectName(_fromUtf8("DialogEpochsTFR"))
        DialogEpochsTFR.resize(484, 687)
        self.gridLayout = QtGui.QGridLayout(DialogEpochsTFR)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(DialogEpochsTFR)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 466, 630))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_4 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBoxBaseline = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxBaseline.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBoxBaseline.sizePolicy().hasHeightForWidth())
        self.groupBoxBaseline.setSizePolicy(sizePolicy)
        self.groupBoxBaseline.setCheckable(True)
        self.groupBoxBaseline.setChecked(True)
        self.groupBoxBaseline.setObjectName(_fromUtf8("groupBoxBaseline"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxBaseline)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.labelRescaling = QtGui.QLabel(self.groupBoxBaseline)
        self.labelRescaling.setObjectName(_fromUtf8("labelRescaling"))
        self.gridLayout_7.addWidget(self.labelRescaling, 0, 0, 1, 1)
        self.labelBaselineStart = QtGui.QLabel(self.groupBoxBaseline)
        self.labelBaselineStart.setEnabled(True)
        self.labelBaselineStart.setObjectName(_fromUtf8("labelBaselineStart"))
        self.gridLayout_7.addWidget(self.labelBaselineStart, 1, 0, 1, 1)
        self.comboBoxMode = QtGui.QComboBox(self.groupBoxBaseline)
        self.comboBoxMode.setObjectName(_fromUtf8("comboBoxMode"))
        self.comboBoxMode.addItem(_fromUtf8(""))
        self.comboBoxMode.addItem(_fromUtf8(""))
        self.comboBoxMode.addItem(_fromUtf8(""))
        self.comboBoxMode.addItem(_fromUtf8(""))
        self.comboBoxMode.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.comboBoxMode, 0, 1, 1, 1)
        self.doubleSpinBoxBaselineStart = QtGui.QDoubleSpinBox(self.groupBoxBaseline)
        self.doubleSpinBoxBaselineStart.setEnabled(True)
        self.doubleSpinBoxBaselineStart.setDecimals(3)
        self.doubleSpinBoxBaselineStart.setSingleStep(0.05)
        self.doubleSpinBoxBaselineStart.setObjectName(_fromUtf8("doubleSpinBoxBaselineStart"))
        self.gridLayout_7.addWidget(self.doubleSpinBoxBaselineStart, 1, 1, 1, 1)
        self.labelBaselineEnd = QtGui.QLabel(self.groupBoxBaseline)
        self.labelBaselineEnd.setEnabled(True)
        self.labelBaselineEnd.setObjectName(_fromUtf8("labelBaselineEnd"))
        self.gridLayout_7.addWidget(self.labelBaselineEnd, 2, 0, 1, 1)
        self.doubleSpinBoxBaselineEnd = QtGui.QDoubleSpinBox(self.groupBoxBaseline)
        self.doubleSpinBoxBaselineEnd.setEnabled(True)
        self.doubleSpinBoxBaselineEnd.setDecimals(3)
        self.doubleSpinBoxBaselineEnd.setSingleStep(0.05)
        self.doubleSpinBoxBaselineEnd.setObjectName(_fromUtf8("doubleSpinBoxBaselineEnd"))
        self.gridLayout_7.addWidget(self.doubleSpinBoxBaselineEnd, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_7, 0, 0, 1, 2)
        self.gridLayout_4.addWidget(self.groupBoxBaseline, 3, 0, 1, 1)
        self.groupBoxFrequencies = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxFrequencies.setObjectName(_fromUtf8("groupBoxFrequencies"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxFrequencies)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.labelMinFreq = QtGui.QLabel(self.groupBoxFrequencies)
        self.labelMinFreq.setObjectName(_fromUtf8("labelMinFreq"))
        self.horizontalLayout_13.addWidget(self.labelMinFreq)
        self.doubleSpinBoxMinFreq = QtGui.QDoubleSpinBox(self.groupBoxFrequencies)
        self.doubleSpinBoxMinFreq.setMinimum(0.1)
        self.doubleSpinBoxMinFreq.setMaximum(200.0)
        self.doubleSpinBoxMinFreq.setProperty("value", 7.0)
        self.doubleSpinBoxMinFreq.setObjectName(_fromUtf8("doubleSpinBoxMinFreq"))
        self.horizontalLayout_13.addWidget(self.doubleSpinBoxMinFreq)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.labelMaxFreq = QtGui.QLabel(self.groupBoxFrequencies)
        self.labelMaxFreq.setObjectName(_fromUtf8("labelMaxFreq"))
        self.horizontalLayout_12.addWidget(self.labelMaxFreq)
        self.doubleSpinBoxMaxFreq = QtGui.QDoubleSpinBox(self.groupBoxFrequencies)
        self.doubleSpinBoxMaxFreq.setMinimum(7.0)
        self.doubleSpinBoxMaxFreq.setMaximum(600.0)
        self.doubleSpinBoxMaxFreq.setProperty("value", 30.0)
        self.doubleSpinBoxMaxFreq.setObjectName(_fromUtf8("doubleSpinBoxMaxFreq"))
        self.horizontalLayout_12.addWidget(self.doubleSpinBoxMaxFreq)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelFrequencyInterval = QtGui.QLabel(self.groupBoxFrequencies)
        self.labelFrequencyInterval.setObjectName(_fromUtf8("labelFrequencyInterval"))
        self.horizontalLayout.addWidget(self.labelFrequencyInterval)
        self.doubleSpinBoxFreqInterval = QtGui.QDoubleSpinBox(self.groupBoxFrequencies)
        self.doubleSpinBoxFreqInterval.setMinimum(0.1)
        self.doubleSpinBoxFreqInterval.setMaximum(99.99)
        self.doubleSpinBoxFreqInterval.setProperty("value", 3.0)
        self.doubleSpinBoxFreqInterval.setObjectName(_fromUtf8("doubleSpinBoxFreqInterval"))
        self.horizontalLayout.addWidget(self.doubleSpinBoxFreqInterval)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.label = QtGui.QLabel(self.groupBoxFrequencies)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_6.addWidget(self.label)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radioButtonFixed = QtGui.QRadioButton(self.groupBoxFrequencies)
        self.radioButtonFixed.setObjectName(_fromUtf8("radioButtonFixed"))
        self.horizontalLayout_4.addWidget(self.radioButtonFixed)
        self.doubleSpinBoxNcycles = QtGui.QDoubleSpinBox(self.groupBoxFrequencies)
        self.doubleSpinBoxNcycles.setEnabled(False)
        self.doubleSpinBoxNcycles.setProperty("value", 3.0)
        self.doubleSpinBoxNcycles.setObjectName(_fromUtf8("doubleSpinBoxNcycles"))
        self.horizontalLayout_4.addWidget(self.doubleSpinBoxNcycles)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.radioButtonAdapted = QtGui.QRadioButton(self.groupBoxFrequencies)
        self.radioButtonAdapted.setChecked(True)
        self.radioButtonAdapted.setObjectName(_fromUtf8("radioButtonAdapted"))
        self.horizontalLayout_5.addWidget(self.radioButtonAdapted)
        self.doubleSpinBoxCycleFactor = QtGui.QDoubleSpinBox(self.groupBoxFrequencies)
        self.doubleSpinBoxCycleFactor.setMinimum(1.0)
        self.doubleSpinBoxCycleFactor.setMaximum(10.0)
        self.doubleSpinBoxCycleFactor.setProperty("value", 3.0)
        self.doubleSpinBoxCycleFactor.setObjectName(_fromUtf8("doubleSpinBoxCycleFactor"))
        self.horizontalLayout_5.addWidget(self.doubleSpinBoxCycleFactor)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxFrequencies, 1, 0, 1, 1)
        self.groupBoxMisc = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxMisc.setObjectName(_fromUtf8("groupBoxMisc"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBoxMisc)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.spinBoxDecim = QtGui.QSpinBox(self.groupBoxMisc)
        self.spinBoxDecim.setProperty("value", 2)
        self.spinBoxDecim.setObjectName(_fromUtf8("spinBoxDecim"))
        self.gridLayout_10.addWidget(self.spinBoxDecim, 1, 1, 1, 1)
        self.labelCmap = QtGui.QLabel(self.groupBoxMisc)
        self.labelCmap.setObjectName(_fromUtf8("labelCmap"))
        self.gridLayout_10.addWidget(self.labelCmap, 0, 0, 1, 1)
        self.comboBoxCmap = QtGui.QComboBox(self.groupBoxMisc)
        self.comboBoxCmap.setObjectName(_fromUtf8("comboBoxCmap"))
        self.comboBoxCmap.addItem(_fromUtf8(""))
        self.comboBoxCmap.addItem(_fromUtf8(""))
        self.comboBoxCmap.addItem(_fromUtf8(""))
        self.comboBoxCmap.addItem(_fromUtf8(""))
        self.comboBoxCmap.addItem(_fromUtf8(""))
        self.comboBoxCmap.addItem(_fromUtf8(""))
        self.gridLayout_10.addWidget(self.comboBoxCmap, 0, 1, 1, 1)
        self.labelDecim = QtGui.QLabel(self.groupBoxMisc)
        self.labelDecim.setObjectName(_fromUtf8("labelDecim"))
        self.gridLayout_10.addWidget(self.labelDecim, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_10, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxMisc, 4, 0, 1, 1)
        self.comboBoxChannels = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.comboBoxChannels.setObjectName(_fromUtf8("comboBoxChannels"))
        self.gridLayout_4.addWidget(self.comboBoxChannels, 0, 0, 1, 1)
        self.checkBoxSaveData = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBoxSaveData.setObjectName(_fromUtf8("checkBoxSaveData"))
        self.gridLayout_4.addWidget(self.checkBoxSaveData, 6, 0, 1, 1)
        self.line = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_4.addWidget(self.line, 5, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(DialogEpochsTFR)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)

        self.retranslateUi(DialogEpochsTFR)
        self.comboBoxMode.setCurrentIndex(0)
        self.comboBoxCmap.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DialogEpochsTFR.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DialogEpochsTFR.reject)
        QtCore.QObject.connect(self.radioButtonAdapted, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBoxCycleFactor.setEnabled)
        QtCore.QObject.connect(self.radioButtonFixed, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBoxNcycles.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(DialogEpochsTFR)
        DialogEpochsTFR.setTabOrder(self.scrollArea, self.doubleSpinBoxMinFreq)
        DialogEpochsTFR.setTabOrder(self.doubleSpinBoxMinFreq, self.doubleSpinBoxMaxFreq)
        DialogEpochsTFR.setTabOrder(self.doubleSpinBoxMaxFreq, self.doubleSpinBoxFreqInterval)
        DialogEpochsTFR.setTabOrder(self.doubleSpinBoxFreqInterval, self.buttonBox)

    def retranslateUi(self, DialogEpochsTFR):
        DialogEpochsTFR.setWindowTitle(_translate("DialogEpochsTFR", "Meggie - TFR from epochs", None))
        self.groupBoxBaseline.setTitle(_translate("DialogEpochsTFR", "Baseline rescaling and correction", None))
        self.labelRescaling.setText(_translate("DialogEpochsTFR", "Rescaling mode:", None))
        self.labelBaselineStart.setText(_translate("DialogEpochsTFR", "Baseline start:", None))
        self.comboBoxMode.setItemText(0, _translate("DialogEpochsTFR", "ratio", None))
        self.comboBoxMode.setItemText(1, _translate("DialogEpochsTFR", "logratio", None))
        self.comboBoxMode.setItemText(2, _translate("DialogEpochsTFR", "mean", None))
        self.comboBoxMode.setItemText(3, _translate("DialogEpochsTFR", "zscore", None))
        self.comboBoxMode.setItemText(4, _translate("DialogEpochsTFR", "percent", None))
        self.doubleSpinBoxBaselineStart.setSuffix(_translate("DialogEpochsTFR", "s", None))
        self.labelBaselineEnd.setText(_translate("DialogEpochsTFR", "Baseline end:", None))
        self.doubleSpinBoxBaselineEnd.setSuffix(_translate("DialogEpochsTFR", "s", None))
        self.groupBoxFrequencies.setTitle(_translate("DialogEpochsTFR", "Frequency window", None))
        self.labelMinFreq.setText(_translate("DialogEpochsTFR", "Minimum frequency:", None))
        self.doubleSpinBoxMinFreq.setSuffix(_translate("DialogEpochsTFR", " Hz", None))
        self.labelMaxFreq.setText(_translate("DialogEpochsTFR", "Maximum frequency:", None))
        self.doubleSpinBoxMaxFreq.setSuffix(_translate("DialogEpochsTFR", " Hz", None))
        self.labelFrequencyInterval.setText(_translate("DialogEpochsTFR", "Frequency interval:", None))
        self.doubleSpinBoxFreqInterval.setSuffix(_translate("DialogEpochsTFR", " Hz", None))
        self.label.setText(_translate("DialogEpochsTFR", "Number of cycles", None))
        self.radioButtonFixed.setText(_translate("DialogEpochsTFR", "Fixed", None))
        self.radioButtonAdapted.setText(_translate("DialogEpochsTFR", "Freqs divided by", None))
        self.groupBoxMisc.setTitle(_translate("DialogEpochsTFR", "Miscellaneous", None))
        self.labelCmap.setText(_translate("DialogEpochsTFR", "Color map:", None))
        self.comboBoxCmap.setItemText(0, _translate("DialogEpochsTFR", "auto", None))
        self.comboBoxCmap.setItemText(1, _translate("DialogEpochsTFR", "RdBu_r", None))
        self.comboBoxCmap.setItemText(2, _translate("DialogEpochsTFR", "Reds", None))
        self.comboBoxCmap.setItemText(3, _translate("DialogEpochsTFR", "YlOrRd", None))
        self.comboBoxCmap.setItemText(4, _translate("DialogEpochsTFR", "seismic", None))
        self.comboBoxCmap.setItemText(5, _translate("DialogEpochsTFR", "bwr", None))
        self.labelDecim.setText(_translate("DialogEpochsTFR", "Decimation factor:", None))
        self.checkBoxSaveData.setText(_translate("DialogEpochsTFR", "Save data", None))

