# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TFRtopologyUi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogTFRTopology(object):
    def setupUi(self, DialogTFRTopology):
        DialogTFRTopology.setObjectName(_fromUtf8("DialogTFRTopology"))
        DialogTFRTopology.resize(544, 735)
        self.gridLayout_2 = QtGui.QGridLayout(DialogTFRTopology)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(DialogTFRTopology)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(DialogTFRTopology)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 526, 639))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(197, 134))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_4 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBoxTopogpraphyType = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBoxTopogpraphyType.sizePolicy().hasHeightForWidth())
        self.groupBoxTopogpraphyType.setSizePolicy(sizePolicy)
        self.groupBoxTopogpraphyType.setObjectName(_fromUtf8("groupBoxTopogpraphyType"))
        self.gridLayout = QtGui.QGridLayout(self.groupBoxTopogpraphyType)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.radioButtonInduced = QtGui.QRadioButton(self.groupBoxTopogpraphyType)
        self.radioButtonInduced.setEnabled(True)
        self.radioButtonInduced.setChecked(True)
        self.radioButtonInduced.setObjectName(_fromUtf8("radioButtonInduced"))
        self.gridLayout.addWidget(self.radioButtonInduced, 1, 0, 1, 1)
        self.radioButtonPhase = QtGui.QRadioButton(self.groupBoxTopogpraphyType)
        self.radioButtonPhase.setEnabled(True)
        self.radioButtonPhase.setObjectName(_fromUtf8("radioButtonPhase"))
        self.gridLayout.addWidget(self.radioButtonPhase, 2, 0, 1, 1)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.labelCmap = QtGui.QLabel(self.groupBoxTopogpraphyType)
        self.labelCmap.setObjectName(_fromUtf8("labelCmap"))
        self.horizontalLayout_17.addWidget(self.labelCmap)
        self.comboBoxCmap = QtGui.QComboBox(self.groupBoxTopogpraphyType)
        self.comboBoxCmap.setObjectName(_fromUtf8("comboBoxCmap"))
        self.comboBoxCmap.addItem(_fromUtf8(""))
        self.comboBoxCmap.addItem(_fromUtf8(""))
        self.comboBoxCmap.addItem(_fromUtf8(""))
        self.comboBoxCmap.addItem(_fromUtf8(""))
        self.comboBoxCmap.addItem(_fromUtf8(""))
        self.comboBoxCmap.addItem(_fromUtf8(""))
        self.horizontalLayout_17.addWidget(self.comboBoxCmap)
        self.gridLayout.addLayout(self.horizontalLayout_17, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxTopogpraphyType, 1, 0, 1, 2)
        self.labelEpochName = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.labelEpochName.setText(_fromUtf8(""))
        self.labelEpochName.setObjectName(_fromUtf8("labelEpochName"))
        self.gridLayout_4.addWidget(self.labelEpochName, 0, 0, 1, 1)
        self.groupBoxFrequencies = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBoxFrequencies.sizePolicy().hasHeightForWidth())
        self.groupBoxFrequencies.setSizePolicy(sizePolicy)
        self.groupBoxFrequencies.setObjectName(_fromUtf8("groupBoxFrequencies"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBoxFrequencies)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.labelMinFreq = QtGui.QLabel(self.groupBoxFrequencies)
        self.labelMinFreq.setObjectName(_fromUtf8("labelMinFreq"))
        self.horizontalLayout_13.addWidget(self.labelMinFreq)
        self.doubleSpinBoxMinFreq = QtGui.QDoubleSpinBox(self.groupBoxFrequencies)
        self.doubleSpinBoxMinFreq.setMinimum(0.1)
        self.doubleSpinBoxMinFreq.setMaximum(200.0)
        self.doubleSpinBoxMinFreq.setProperty("value", 7.0)
        self.doubleSpinBoxMinFreq.setObjectName(_fromUtf8("doubleSpinBoxMinFreq"))
        self.horizontalLayout_13.addWidget(self.doubleSpinBoxMinFreq)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.labelMaxFreq = QtGui.QLabel(self.groupBoxFrequencies)
        self.labelMaxFreq.setObjectName(_fromUtf8("labelMaxFreq"))
        self.horizontalLayout_12.addWidget(self.labelMaxFreq)
        self.doubleSpinBoxMaxFreq = QtGui.QDoubleSpinBox(self.groupBoxFrequencies)
        self.doubleSpinBoxMaxFreq.setMinimum(7.0)
        self.doubleSpinBoxMaxFreq.setMaximum(600.0)
        self.doubleSpinBoxMaxFreq.setProperty("value", 30.0)
        self.doubleSpinBoxMaxFreq.setObjectName(_fromUtf8("doubleSpinBoxMaxFreq"))
        self.horizontalLayout_12.addWidget(self.doubleSpinBoxMaxFreq)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelFrequencyInterval = QtGui.QLabel(self.groupBoxFrequencies)
        self.labelFrequencyInterval.setObjectName(_fromUtf8("labelFrequencyInterval"))
        self.horizontalLayout.addWidget(self.labelFrequencyInterval)
        self.doubleSpinBoxFreqInterval = QtGui.QDoubleSpinBox(self.groupBoxFrequencies)
        self.doubleSpinBoxFreqInterval.setMinimum(0.1)
        self.doubleSpinBoxFreqInterval.setMaximum(99.99)
        self.doubleSpinBoxFreqInterval.setProperty("value", 3.0)
        self.doubleSpinBoxFreqInterval.setObjectName(_fromUtf8("doubleSpinBoxFreqInterval"))
        self.horizontalLayout.addWidget(self.doubleSpinBoxFreqInterval)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_2 = QtGui.QLabel(self.groupBoxFrequencies)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_8.addWidget(self.label_2)
        self.spinBoxDecim = QtGui.QSpinBox(self.groupBoxFrequencies)
        self.spinBoxDecim.setProperty("value", 3)
        self.spinBoxDecim.setObjectName(_fromUtf8("spinBoxDecim"))
        self.horizontalLayout_8.addWidget(self.spinBoxDecim)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.gridLayout_5.addLayout(self.verticalLayout_6, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 3, 1, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.radioButtonFixed = QtGui.QRadioButton(self.groupBoxFrequencies)
        self.radioButtonFixed.setChecked(True)
        self.radioButtonFixed.setObjectName(_fromUtf8("radioButtonFixed"))
        self.horizontalLayout_18.addWidget(self.radioButtonFixed)
        self.ncyclesLabel = QtGui.QLabel(self.groupBoxFrequencies)
        self.ncyclesLabel.setObjectName(_fromUtf8("ncyclesLabel"))
        self.horizontalLayout_18.addWidget(self.ncyclesLabel)
        self.doubleSpinBoxNcycles = QtGui.QDoubleSpinBox(self.groupBoxFrequencies)
        self.doubleSpinBoxNcycles.setMinimum(1.0)
        self.doubleSpinBoxNcycles.setMaximum(100.0)
        self.doubleSpinBoxNcycles.setProperty("value", 3.0)
        self.doubleSpinBoxNcycles.setObjectName(_fromUtf8("doubleSpinBoxNcycles"))
        self.horizontalLayout_18.addWidget(self.doubleSpinBoxNcycles)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.radioButtonAdapted = QtGui.QRadioButton(self.groupBoxFrequencies)
        self.radioButtonAdapted.setObjectName(_fromUtf8("radioButtonAdapted"))
        self.horizontalLayout_19.addWidget(self.radioButtonAdapted)
        self.label_7 = QtGui.QLabel(self.groupBoxFrequencies)
        self.label_7.setEnabled(False)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_19.addWidget(self.label_7)
        self.doubleSpinBoxCycleFactor = QtGui.QDoubleSpinBox(self.groupBoxFrequencies)
        self.doubleSpinBoxCycleFactor.setEnabled(False)
        self.doubleSpinBoxCycleFactor.setMinimum(0.01)
        self.doubleSpinBoxCycleFactor.setMaximum(2.0)
        self.doubleSpinBoxCycleFactor.setSingleStep(0.1)
        self.doubleSpinBoxCycleFactor.setProperty("value", 0.5)
        self.doubleSpinBoxCycleFactor.setObjectName(_fromUtf8("doubleSpinBoxCycleFactor"))
        self.horizontalLayout_19.addWidget(self.doubleSpinBoxCycleFactor)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 2, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxFrequencies, 2, 0, 1, 1)
        self.groupBoxScalp = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxScalp.setCheckable(True)
        self.groupBoxScalp.setChecked(False)
        self.groupBoxScalp.setObjectName(_fromUtf8("groupBoxScalp"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBoxScalp)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_6 = QtGui.QLabel(self.groupBoxScalp)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_16.addWidget(self.label_6)
        self.comboBoxChannels = QtGui.QComboBox(self.groupBoxScalp)
        self.comboBoxChannels.setObjectName(_fromUtf8("comboBoxChannels"))
        self.comboBoxChannels.addItem(_fromUtf8(""))
        self.comboBoxChannels.addItem(_fromUtf8(""))
        self.comboBoxChannels.addItem(_fromUtf8(""))
        self.horizontalLayout_16.addWidget(self.comboBoxChannels)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_5 = QtGui.QLabel(self.groupBoxScalp)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_15.addWidget(self.label_5)
        self.doubleSpinBoxScalpFmin = QtGui.QDoubleSpinBox(self.groupBoxScalp)
        self.doubleSpinBoxScalpFmin.setProperty("value", 7.0)
        self.doubleSpinBoxScalpFmin.setObjectName(_fromUtf8("doubleSpinBoxScalpFmin"))
        self.horizontalLayout_15.addWidget(self.doubleSpinBoxScalpFmin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_4 = QtGui.QLabel(self.groupBoxScalp)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_14.addWidget(self.label_4)
        self.doubleSpinBoxScalpFmax = QtGui.QDoubleSpinBox(self.groupBoxScalp)
        self.doubleSpinBoxScalpFmax.setProperty("value", 30.0)
        self.doubleSpinBoxScalpFmax.setObjectName(_fromUtf8("doubleSpinBoxScalpFmax"))
        self.horizontalLayout_14.addWidget(self.doubleSpinBoxScalpFmax)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label = QtGui.QLabel(self.groupBoxScalp)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_10.addWidget(self.label)
        self.doubleSpinBoxScalpTmin = QtGui.QDoubleSpinBox(self.groupBoxScalp)
        self.doubleSpinBoxScalpTmin.setMinimum(-10.0)
        self.doubleSpinBoxScalpTmin.setSingleStep(0.1)
        self.doubleSpinBoxScalpTmin.setObjectName(_fromUtf8("doubleSpinBoxScalpTmin"))
        self.horizontalLayout_10.addWidget(self.doubleSpinBoxScalpTmin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_3 = QtGui.QLabel(self.groupBoxScalp)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_11.addWidget(self.label_3)
        self.doubleSpinBoxScalpTmax = QtGui.QDoubleSpinBox(self.groupBoxScalp)
        self.doubleSpinBoxScalpTmax.setMinimum(-10.0)
        self.doubleSpinBoxScalpTmax.setSingleStep(0.1)
        self.doubleSpinBoxScalpTmax.setObjectName(_fromUtf8("doubleSpinBoxScalpTmax"))
        self.horizontalLayout_11.addWidget(self.doubleSpinBoxScalpTmax)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem2, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxScalp, 2, 1, 1, 1)
        self.groupBoxBaseline = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxBaseline.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBoxBaseline.sizePolicy().hasHeightForWidth())
        self.groupBoxBaseline.setSizePolicy(sizePolicy)
        self.groupBoxBaseline.setCheckable(True)
        self.groupBoxBaseline.setChecked(True)
        self.groupBoxBaseline.setObjectName(_fromUtf8("groupBoxBaseline"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxBaseline)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.labelRescaling = QtGui.QLabel(self.groupBoxBaseline)
        self.labelRescaling.setObjectName(_fromUtf8("labelRescaling"))
        self.horizontalLayout_7.addWidget(self.labelRescaling)
        self.comboBoxMode = QtGui.QComboBox(self.groupBoxBaseline)
        self.comboBoxMode.setObjectName(_fromUtf8("comboBoxMode"))
        self.comboBoxMode.addItem(_fromUtf8(""))
        self.comboBoxMode.addItem(_fromUtf8(""))
        self.comboBoxMode.addItem(_fromUtf8(""))
        self.comboBoxMode.addItem(_fromUtf8(""))
        self.comboBoxMode.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.comboBoxMode)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelBaselineStart = QtGui.QLabel(self.groupBoxBaseline)
        self.labelBaselineStart.setEnabled(True)
        self.labelBaselineStart.setObjectName(_fromUtf8("labelBaselineStart"))
        self.horizontalLayout_3.addWidget(self.labelBaselineStart)
        self.doubleSpinBoxBaselineStart = QtGui.QDoubleSpinBox(self.groupBoxBaseline)
        self.doubleSpinBoxBaselineStart.setEnabled(True)
        self.doubleSpinBoxBaselineStart.setDecimals(3)
        self.doubleSpinBoxBaselineStart.setSingleStep(0.05)
        self.doubleSpinBoxBaselineStart.setObjectName(_fromUtf8("doubleSpinBoxBaselineStart"))
        self.horizontalLayout_3.addWidget(self.doubleSpinBoxBaselineStart)
        self.checkBoxBaselineStartNone = QtGui.QCheckBox(self.groupBoxBaseline)
        self.checkBoxBaselineStartNone.setChecked(False)
        self.checkBoxBaselineStartNone.setObjectName(_fromUtf8("checkBoxBaselineStartNone"))
        self.horizontalLayout_3.addWidget(self.checkBoxBaselineStartNone)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.labelBaselineEnd = QtGui.QLabel(self.groupBoxBaseline)
        self.labelBaselineEnd.setEnabled(True)
        self.labelBaselineEnd.setObjectName(_fromUtf8("labelBaselineEnd"))
        self.horizontalLayout_4.addWidget(self.labelBaselineEnd)
        self.doubleSpinBoxBaselineEnd = QtGui.QDoubleSpinBox(self.groupBoxBaseline)
        self.doubleSpinBoxBaselineEnd.setEnabled(True)
        self.doubleSpinBoxBaselineEnd.setDecimals(3)
        self.doubleSpinBoxBaselineEnd.setSingleStep(0.05)
        self.doubleSpinBoxBaselineEnd.setObjectName(_fromUtf8("doubleSpinBoxBaselineEnd"))
        self.horizontalLayout_4.addWidget(self.doubleSpinBoxBaselineEnd)
        self.checkBoxBaselineEndNone = QtGui.QCheckBox(self.groupBoxBaseline)
        self.checkBoxBaselineEndNone.setChecked(False)
        self.checkBoxBaselineEndNone.setObjectName(_fromUtf8("checkBoxBaselineEndNone"))
        self.horizontalLayout_4.addWidget(self.checkBoxBaselineEndNone)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxBaseline, 3, 0, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.pushButtonGroupAverage = QtGui.QPushButton(DialogTFRTopology)
        self.pushButtonGroupAverage.setObjectName(_fromUtf8("pushButtonGroupAverage"))
        self.horizontalLayout_9.addWidget(self.pushButtonGroupAverage)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)

        self.retranslateUi(DialogTFRTopology)
        self.comboBoxCmap.setCurrentIndex(0)
        self.comboBoxChannels.setCurrentIndex(1)
        self.comboBoxMode.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DialogTFRTopology.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DialogTFRTopology.reject)
        QtCore.QObject.connect(self.checkBoxBaselineStartNone, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.labelBaselineStart.setDisabled)
        QtCore.QObject.connect(self.checkBoxBaselineStartNone, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBoxBaselineStart.setDisabled)
        QtCore.QObject.connect(self.checkBoxBaselineEndNone, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBoxBaselineEnd.setDisabled)
        QtCore.QObject.connect(self.checkBoxBaselineEndNone, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.labelBaselineEnd.setDisabled)
        QtCore.QObject.connect(self.radioButtonFixed, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ncyclesLabel.setEnabled)
        QtCore.QObject.connect(self.radioButtonFixed, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBoxNcycles.setEnabled)
        QtCore.QObject.connect(self.radioButtonAdapted, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_7.setEnabled)
        QtCore.QObject.connect(self.radioButtonAdapted, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBoxCycleFactor.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(DialogTFRTopology)
        DialogTFRTopology.setTabOrder(self.scrollArea, self.radioButtonInduced)
        DialogTFRTopology.setTabOrder(self.radioButtonInduced, self.radioButtonPhase)
        DialogTFRTopology.setTabOrder(self.radioButtonPhase, self.comboBoxCmap)
        DialogTFRTopology.setTabOrder(self.comboBoxCmap, self.doubleSpinBoxMinFreq)
        DialogTFRTopology.setTabOrder(self.doubleSpinBoxMinFreq, self.doubleSpinBoxMaxFreq)
        DialogTFRTopology.setTabOrder(self.doubleSpinBoxMaxFreq, self.doubleSpinBoxFreqInterval)
        DialogTFRTopology.setTabOrder(self.doubleSpinBoxFreqInterval, self.spinBoxDecim)
        DialogTFRTopology.setTabOrder(self.spinBoxDecim, self.radioButtonFixed)
        DialogTFRTopology.setTabOrder(self.radioButtonFixed, self.doubleSpinBoxNcycles)
        DialogTFRTopology.setTabOrder(self.doubleSpinBoxNcycles, self.radioButtonAdapted)
        DialogTFRTopology.setTabOrder(self.radioButtonAdapted, self.doubleSpinBoxCycleFactor)
        DialogTFRTopology.setTabOrder(self.doubleSpinBoxCycleFactor, self.groupBoxScalp)
        DialogTFRTopology.setTabOrder(self.groupBoxScalp, self.comboBoxChannels)
        DialogTFRTopology.setTabOrder(self.comboBoxChannels, self.doubleSpinBoxScalpFmin)
        DialogTFRTopology.setTabOrder(self.doubleSpinBoxScalpFmin, self.doubleSpinBoxScalpFmax)
        DialogTFRTopology.setTabOrder(self.doubleSpinBoxScalpFmax, self.doubleSpinBoxScalpTmin)
        DialogTFRTopology.setTabOrder(self.doubleSpinBoxScalpTmin, self.doubleSpinBoxScalpTmax)
        DialogTFRTopology.setTabOrder(self.doubleSpinBoxScalpTmax, self.groupBoxBaseline)
        DialogTFRTopology.setTabOrder(self.groupBoxBaseline, self.comboBoxMode)
        DialogTFRTopology.setTabOrder(self.comboBoxMode, self.doubleSpinBoxBaselineStart)
        DialogTFRTopology.setTabOrder(self.doubleSpinBoxBaselineStart, self.checkBoxBaselineStartNone)
        DialogTFRTopology.setTabOrder(self.checkBoxBaselineStartNone, self.doubleSpinBoxBaselineEnd)
        DialogTFRTopology.setTabOrder(self.doubleSpinBoxBaselineEnd, self.checkBoxBaselineEndNone)
        DialogTFRTopology.setTabOrder(self.checkBoxBaselineEndNone, self.pushButtonGroupAverage)
        DialogTFRTopology.setTabOrder(self.pushButtonGroupAverage, self.buttonBox)

    def retranslateUi(self, DialogTFRTopology):
        DialogTFRTopology.setWindowTitle(_translate("DialogTFRTopology", "Meggie - Show TFR topologies ", None))
        self.groupBoxTopogpraphyType.setTitle(_translate("DialogTFRTopology", "Topography type", None))
        self.radioButtonInduced.setText(_translate("DialogTFRTopology", "Induced power", None))
        self.radioButtonPhase.setText(_translate("DialogTFRTopology", "Phase locking value", None))
        self.labelCmap.setText(_translate("DialogTFRTopology", "Color map:", None))
        self.comboBoxCmap.setItemText(0, _translate("DialogTFRTopology", "auto", None))
        self.comboBoxCmap.setItemText(1, _translate("DialogTFRTopology", "RdBu_r", None))
        self.comboBoxCmap.setItemText(2, _translate("DialogTFRTopology", "Reds", None))
        self.comboBoxCmap.setItemText(3, _translate("DialogTFRTopology", "YlOrRd", None))
        self.comboBoxCmap.setItemText(4, _translate("DialogTFRTopology", "seismic", None))
        self.comboBoxCmap.setItemText(5, _translate("DialogTFRTopology", "bwr", None))
        self.groupBoxFrequencies.setTitle(_translate("DialogTFRTopology", "Frequency window", None))
        self.labelMinFreq.setText(_translate("DialogTFRTopology", "Minimum frequency:", None))
        self.doubleSpinBoxMinFreq.setSuffix(_translate("DialogTFRTopology", "Hz", None))
        self.labelMaxFreq.setText(_translate("DialogTFRTopology", "Maximum frequency:", None))
        self.doubleSpinBoxMaxFreq.setSuffix(_translate("DialogTFRTopology", "Hz", None))
        self.labelFrequencyInterval.setText(_translate("DialogTFRTopology", "Frequency interval:", None))
        self.doubleSpinBoxFreqInterval.setSuffix(_translate("DialogTFRTopology", "Hz", None))
        self.label_2.setText(_translate("DialogTFRTopology", "Temporal decim factor:", None))
        self.radioButtonFixed.setText(_translate("DialogTFRTopology", "Fixed", None))
        self.ncyclesLabel.setText(_translate("DialogTFRTopology", "ncycles", None))
        self.radioButtonAdapted.setToolTip(_translate("DialogTFRTopology", "<html><head/><body><p>You can define different number of cycles for each frequency of interest. The defined factor is multiplied by the frequency in hertz to get the number of cycles (ncycles = freq * factor). For instance, with a factor of 0.5, frequencies of 2, 4 and 6 tranlslate to morlet wavelets with cycles of 1, 2 and 3.</p></body></html>", None))
        self.radioButtonAdapted.setText(_translate("DialogTFRTopology", "Adapted", None))
        self.label_7.setToolTip(_translate("DialogTFRTopology", "<html><head/><body><p>You can define different number of cycles for each frequency of interest. The defined factor is multiplied by the frequency in hertz to get the number of cycles (ncycles = freq * factor). For instance, with a factor of 0.5, frequencies of 2, 4 and 6 tranlslate to morlet wavelets with cycles of 1, 2 and 3.</p></body></html>", None))
        self.label_7.setText(_translate("DialogTFRTopology", "cycles / freq", None))
        self.doubleSpinBoxCycleFactor.setToolTip(_translate("DialogTFRTopology", "<html><head/><body><p>You can define different number of cycles for each frequency of interest. The defined factor is multiplied by the frequency in hertz to get the number of cycles (ncycles = freq * factor). For instance, with a factor of 0.5, frequencies of 2, 4 and 6 tranlslate to morlet wavelets with cycles of 1, 2 and 3.</p></body></html>", None))
        self.groupBoxScalp.setToolTip(_translate("DialogTFRTopology", "If checked, a scalp plot will be displayed.", None))
        self.groupBoxScalp.setTitle(_translate("DialogTFRTopology", "Scalp plot", None))
        self.label_6.setText(_translate("DialogTFRTopology", "Channels:", None))
        self.comboBoxChannels.setItemText(0, _translate("DialogTFRTopology", "mag", None))
        self.comboBoxChannels.setItemText(1, _translate("DialogTFRTopology", "grad", None))
        self.comboBoxChannels.setItemText(2, _translate("DialogTFRTopology", "eeg", None))
        self.label_5.setText(_translate("DialogTFRTopology", "Minimum frequency:", None))
        self.doubleSpinBoxScalpFmin.setSuffix(_translate("DialogTFRTopology", "Hz", None))
        self.label_4.setText(_translate("DialogTFRTopology", "Maximum frequency:", None))
        self.doubleSpinBoxScalpFmax.setSuffix(_translate("DialogTFRTopology", "Hz", None))
        self.label.setText(_translate("DialogTFRTopology", "Start time:", None))
        self.label_3.setText(_translate("DialogTFRTopology", "End time:", None))
        self.groupBoxBaseline.setTitle(_translate("DialogTFRTopology", "Baseline rescaling and correction", None))
        self.labelRescaling.setText(_translate("DialogTFRTopology", "Rescaling mode:", None))
        self.comboBoxMode.setItemText(0, _translate("DialogTFRTopology", "ratio", None))
        self.comboBoxMode.setItemText(1, _translate("DialogTFRTopology", "logratio", None))
        self.comboBoxMode.setItemText(2, _translate("DialogTFRTopology", "mean", None))
        self.comboBoxMode.setItemText(3, _translate("DialogTFRTopology", "zscore", None))
        self.comboBoxMode.setItemText(4, _translate("DialogTFRTopology", "percent", None))
        self.labelBaselineStart.setText(_translate("DialogTFRTopology", "Baseline start:", None))
        self.doubleSpinBoxBaselineStart.setSuffix(_translate("DialogTFRTopology", "s", None))
        self.checkBoxBaselineStartNone.setText(_translate("DialogTFRTopology", "None", None))
        self.labelBaselineEnd.setText(_translate("DialogTFRTopology", "Baseline end:", None))
        self.doubleSpinBoxBaselineEnd.setSuffix(_translate("DialogTFRTopology", "s", None))
        self.checkBoxBaselineEndNone.setText(_translate("DialogTFRTopology", "None", None))
        self.pushButtonGroupAverage.setText(_translate("DialogTFRTopology", "Group average for all subjects", None))

