# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'covarianceRawDialogUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_covarianceRawDialog(object):
    def setupUi(self, covarianceRawDialog):
        covarianceRawDialog.setObjectName("covarianceRawDialog")
        covarianceRawDialog.resize(496, 337)
        self.gridLayout_7 = QtWidgets.QGridLayout(covarianceRawDialog)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.buttonBox = QtWidgets.QDialogButtonBox(covarianceRawDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_7.addWidget(self.buttonBox, 3, 0, 1, 1)
        self.groupBoxName = QtWidgets.QGroupBox(covarianceRawDialog)
        self.groupBoxName.setObjectName("groupBoxName")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxName)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelName = QtWidgets.QLabel(self.groupBoxName)
        self.labelName.setObjectName("labelName")
        self.horizontalLayout_4.addWidget(self.labelName)
        self.lineEditName = QtWidgets.QLineEdit(self.groupBoxName)
        self.lineEditName.setObjectName("lineEditName")
        self.horizontalLayout_4.addWidget(self.lineEditName)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBoxName, 0, 0, 1, 1)
        self.groupBoxSource = QtWidgets.QGroupBox(covarianceRawDialog)
        self.groupBoxSource.setObjectName("groupBoxSource")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBoxSource)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButtonCurrentSubject = QtWidgets.QRadioButton(self.groupBoxSource)
        self.radioButtonCurrentSubject.setChecked(True)
        self.radioButtonCurrentSubject.setObjectName("radioButtonCurrentSubject")
        self.horizontalLayout_5.addWidget(self.radioButtonCurrentSubject)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButtonElsewhere = QtWidgets.QRadioButton(self.groupBoxSource)
        self.radioButtonElsewhere.setObjectName("radioButtonElsewhere")
        self.horizontalLayout.addWidget(self.radioButtonElsewhere)
        self.lineEditRawFile = QtWidgets.QLineEdit(self.groupBoxSource)
        self.lineEditRawFile.setEnabled(False)
        self.lineEditRawFile.setObjectName("lineEditRawFile")
        self.horizontalLayout.addWidget(self.lineEditRawFile)
        self.pushButtonBrowse = QtWidgets.QPushButton(self.groupBoxSource)
        self.pushButtonBrowse.setEnabled(False)
        self.pushButtonBrowse.setObjectName("pushButtonBrowse")
        self.horizontalLayout.addWidget(self.pushButtonBrowse)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBoxSource, 1, 0, 1, 1)
        self.groupBoxStartEnd = QtWidgets.QGroupBox(covarianceRawDialog)
        self.groupBoxStartEnd.setObjectName("groupBoxStartEnd")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxStartEnd)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelBeginTime = QtWidgets.QLabel(self.groupBoxStartEnd)
        self.labelBeginTime.setObjectName("labelBeginTime")
        self.horizontalLayout_3.addWidget(self.labelBeginTime)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.doubleSpinBoxStartTime = QtWidgets.QDoubleSpinBox(self.groupBoxStartEnd)
        self.doubleSpinBoxStartTime.setPrefix("")
        self.doubleSpinBoxStartTime.setMaximum(9999.99)
        self.doubleSpinBoxStartTime.setObjectName("doubleSpinBoxStartTime")
        self.horizontalLayout_3.addWidget(self.doubleSpinBoxStartTime)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelEndTime = QtWidgets.QLabel(self.groupBoxStartEnd)
        self.labelEndTime.setObjectName("labelEndTime")
        self.horizontalLayout_2.addWidget(self.labelEndTime)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.doubleSpinBoxEndTime = QtWidgets.QDoubleSpinBox(self.groupBoxStartEnd)
        self.doubleSpinBoxEndTime.setMaximum(9999.99)
        self.doubleSpinBoxEndTime.setObjectName("doubleSpinBoxEndTime")
        self.horizontalLayout_2.addWidget(self.doubleSpinBoxEndTime)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBoxStartEnd, 2, 0, 1, 1)

        self.retranslateUi(covarianceRawDialog)
        self.buttonBox.accepted.connect(covarianceRawDialog.accept)
        self.buttonBox.rejected.connect(covarianceRawDialog.reject)
        self.radioButtonElsewhere.toggled['bool'].connect(self.lineEditRawFile.setEnabled)
        self.radioButtonElsewhere.toggled['bool'].connect(self.pushButtonBrowse.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(covarianceRawDialog)

    def retranslateUi(self, covarianceRawDialog):
        _translate = QtCore.QCoreApplication.translate
        covarianceRawDialog.setWindowTitle(_translate("covarianceRawDialog", "Meggie - Covariance from raw"))
        self.groupBoxName.setTitle(_translate("covarianceRawDialog", "General:"))
        self.labelName.setText(_translate("covarianceRawDialog", "Name:"))
        self.groupBoxSource.setTitle(_translate("covarianceRawDialog", "Use raw file from:"))
        self.radioButtonCurrentSubject.setText(_translate("covarianceRawDialog", "Current subject"))
        self.radioButtonElsewhere.setText(_translate("covarianceRawDialog", "Elsewhere:"))
        self.pushButtonBrowse.setText(_translate("covarianceRawDialog", "Browse..."))
        self.groupBoxStartEnd.setTitle(_translate("covarianceRawDialog", "Time interval:"))
        self.labelBeginTime.setText(_translate("covarianceRawDialog", "Beginning of time interval (seconds from start):"))
        self.doubleSpinBoxStartTime.setSuffix(_translate("covarianceRawDialog", " s"))
        self.labelEndTime.setText(_translate("covarianceRawDialog", "End of time interval (seconds from start):"))
        self.doubleSpinBoxEndTime.setSuffix(_translate("covarianceRawDialog", " s"))

