# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'covarianceEpochDialogUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_covarianceEpochDialog(object):
    def setupUi(self, covarianceEpochDialog):
        covarianceEpochDialog.setObjectName("covarianceEpochDialog")
        covarianceEpochDialog.resize(397, 345)
        self.gridLayout = QtWidgets.QGridLayout(covarianceEpochDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(covarianceEpochDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBoxName = QtWidgets.QGroupBox(covarianceEpochDialog)
        self.groupBoxName.setObjectName("groupBoxName")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxName)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelName = QtWidgets.QLabel(self.groupBoxName)
        self.labelName.setObjectName("labelName")
        self.horizontalLayout_3.addWidget(self.labelName)
        self.lineEditName = QtWidgets.QLineEdit(self.groupBoxName)
        self.lineEditName.setObjectName("lineEditName")
        self.horizontalLayout_3.addWidget(self.lineEditName)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBoxName)
        self.groupBoxEpochs = QtWidgets.QGroupBox(covarianceEpochDialog)
        self.groupBoxEpochs.setObjectName("groupBoxEpochs")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxEpochs)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidgetEpochs = QtWidgets.QListWidget(self.groupBoxEpochs)
        self.listWidgetEpochs.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listWidgetEpochs.setObjectName("listWidgetEpochs")
        self.gridLayout_2.addWidget(self.listWidgetEpochs, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBoxEpochs)
        self.groupBoxParams = QtWidgets.QGroupBox(covarianceEpochDialog)
        self.groupBoxParams.setObjectName("groupBoxParams")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxParams)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelTmin = QtWidgets.QLabel(self.groupBoxParams)
        self.labelTmin.setObjectName("labelTmin")
        self.horizontalLayout.addWidget(self.labelTmin)
        self.doubleSpinBoxTmin = QtWidgets.QDoubleSpinBox(self.groupBoxParams)
        self.doubleSpinBoxTmin.setMinimum(-1000000000.0)
        self.doubleSpinBoxTmin.setMaximum(1000000000.0)
        self.doubleSpinBoxTmin.setSingleStep(0.1)
        self.doubleSpinBoxTmin.setObjectName("doubleSpinBoxTmin")
        self.horizontalLayout.addWidget(self.doubleSpinBoxTmin)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelTmax = QtWidgets.QLabel(self.groupBoxParams)
        self.labelTmax.setObjectName("labelTmax")
        self.horizontalLayout_2.addWidget(self.labelTmax)
        self.doubleSpinBoxTmax = QtWidgets.QDoubleSpinBox(self.groupBoxParams)
        self.doubleSpinBoxTmax.setMinimum(-1000000000.0)
        self.doubleSpinBoxTmax.setMaximum(1000000000.0)
        self.doubleSpinBoxTmax.setSingleStep(0.1)
        self.doubleSpinBoxTmax.setObjectName("doubleSpinBoxTmax")
        self.horizontalLayout_2.addWidget(self.doubleSpinBoxTmax)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBoxParams)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(covarianceEpochDialog)
        self.buttonBox.accepted.connect(covarianceEpochDialog.accept)
        self.buttonBox.rejected.connect(covarianceEpochDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(covarianceEpochDialog)

    def retranslateUi(self, covarianceEpochDialog):
        _translate = QtCore.QCoreApplication.translate
        covarianceEpochDialog.setWindowTitle(_translate("covarianceEpochDialog", "Meggie - Covariance from epochs"))
        self.groupBoxName.setTitle(_translate("covarianceEpochDialog", "General:"))
        self.labelName.setText(_translate("covarianceEpochDialog", "Name:"))
        self.groupBoxEpochs.setTitle(_translate("covarianceEpochDialog", "Select epochs for computation:"))
        self.groupBoxParams.setTitle(_translate("covarianceEpochDialog", "Set parameters:"))
        self.labelTmin.setText(_translate("covarianceEpochDialog", "Start time:"))
        self.doubleSpinBoxTmin.setSuffix(_translate("covarianceEpochDialog", " s"))
        self.labelTmax.setText(_translate("covarianceEpochDialog", "End time:"))
        self.doubleSpinBoxTmax.setSuffix(_translate("covarianceEpochDialog", " s"))

