# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forwardSolutionDialogUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_forwardSolutionDialog(object):
    def setupUi(self, forwardSolutionDialog):
        forwardSolutionDialog.setObjectName("forwardSolutionDialog")
        forwardSolutionDialog.resize(572, 272)
        forwardSolutionDialog.setModal(True)
        self.formLayout_3 = QtWidgets.QFormLayout(forwardSolutionDialog)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelForwardSolutionName = QtWidgets.QLabel(forwardSolutionDialog)
        self.labelForwardSolutionName.setObjectName("labelForwardSolutionName")
        self.horizontalLayout_6.addWidget(self.labelForwardSolutionName)
        self.lineEditForwardSolutionName = QtWidgets.QLineEdit(forwardSolutionDialog)
        self.lineEditForwardSolutionName.setObjectName("lineEditForwardSolutionName")
        self.horizontalLayout_6.addWidget(self.lineEditForwardSolutionName)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_6)
        self.groupBoxSourceSpaceSetup = QtWidgets.QGroupBox(forwardSolutionDialog)
        self.groupBoxSourceSpaceSetup.setObjectName("groupBoxSourceSpaceSetup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxSourceSpaceSetup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelIco = QtWidgets.QLabel(self.groupBoxSourceSpaceSetup)
        self.labelIco.setObjectName("labelIco")
        self.gridLayout_3.addWidget(self.labelIco, 0, 0, 1, 1)
        self.comboBoxSurfaceDecimMethod = QtWidgets.QComboBox(self.groupBoxSourceSpaceSetup)
        self.comboBoxSurfaceDecimMethod.setObjectName("comboBoxSurfaceDecimMethod")
        self.comboBoxSurfaceDecimMethod.addItem("")
        self.comboBoxSurfaceDecimMethod.addItem("")
        self.comboBoxSurfaceDecimMethod.addItem("")
        self.comboBoxSurfaceDecimMethod.addItem("")
        self.gridLayout_3.addWidget(self.comboBoxSurfaceDecimMethod, 0, 1, 1, 2)
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.groupBoxSourceSpaceSetup)
        self.groupBoxSetupBem = QtWidgets.QGroupBox(forwardSolutionDialog)
        self.groupBoxSetupBem.setObjectName("groupBoxSetupBem")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxSetupBem)
        self.gridLayout.setObjectName("gridLayout")
        self.labelConductivity = QtWidgets.QLabel(self.groupBoxSetupBem)
        self.labelConductivity.setObjectName("labelConductivity")
        self.gridLayout.addWidget(self.labelConductivity, 1, 0, 1, 1)
        self.labelTriangIco = QtWidgets.QLabel(self.groupBoxSetupBem)
        self.labelTriangIco.setObjectName("labelTriangIco")
        self.gridLayout.addWidget(self.labelTriangIco, 0, 0, 1, 1)
        self.spinBoxTriangFilesIco = QtWidgets.QSpinBox(self.groupBoxSetupBem)
        self.spinBoxTriangFilesIco.setEnabled(True)
        self.spinBoxTriangFilesIco.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxTriangFilesIco.setProperty("value", 4)
        self.spinBoxTriangFilesIco.setObjectName("spinBoxTriangFilesIco")
        self.gridLayout.addWidget(self.spinBoxTriangFilesIco, 0, 1, 1, 1)
        self.doubleSpinBoxBrainConductivity = QtWidgets.QDoubleSpinBox(self.groupBoxSetupBem)
        self.doubleSpinBoxBrainConductivity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBrainConductivity.setDecimals(2)
        self.doubleSpinBoxBrainConductivity.setProperty("value", 0.3)
        self.doubleSpinBoxBrainConductivity.setObjectName("doubleSpinBoxBrainConductivity")
        self.gridLayout.addWidget(self.doubleSpinBoxBrainConductivity, 1, 1, 1, 1)
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.groupBoxSetupBem)
        self.buttonBox = QtWidgets.QDialogButtonBox(forwardSolutionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)

        self.retranslateUi(forwardSolutionDialog)
        self.buttonBox.accepted.connect(forwardSolutionDialog.accept)
        self.buttonBox.rejected.connect(forwardSolutionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(forwardSolutionDialog)

    def retranslateUi(self, forwardSolutionDialog):
        _translate = QtCore.QCoreApplication.translate
        forwardSolutionDialog.setWindowTitle(_translate("forwardSolutionDialog", "Create new forward solution"))
        self.labelForwardSolutionName.setText(_translate("forwardSolutionDialog", "Forward solution name:"))
        self.groupBoxSourceSpaceSetup.setTitle(_translate("forwardSolutionDialog", "Source space setup parameters:"))
        self.labelIco.setText(_translate("forwardSolutionDialog", "Cortical surface decimation method:"))
        self.comboBoxSurfaceDecimMethod.setItemText(0, _translate("forwardSolutionDialog", "ico4"))
        self.comboBoxSurfaceDecimMethod.setItemText(1, _translate("forwardSolutionDialog", "oct5"))
        self.comboBoxSurfaceDecimMethod.setItemText(2, _translate("forwardSolutionDialog", "ico5"))
        self.comboBoxSurfaceDecimMethod.setItemText(3, _translate("forwardSolutionDialog", "oct6"))
        self.groupBoxSetupBem.setTitle(_translate("forwardSolutionDialog", "BEM model setup parameters:"))
        self.labelConductivity.setText(_translate("forwardSolutionDialog", "Single-layer conductivity:"))
        self.labelTriangIco.setText(_translate("forwardSolutionDialog", "Triangulation files ico-number:"))
        self.doubleSpinBoxBrainConductivity.setSuffix(_translate("forwardSolutionDialog", " S/m"))

