# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "MarkupSafe" = super.buildPythonPackage rec {
    pname = "MarkupSafe";
    version = "2.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1d/97/2288fe498044284f39ab8950703e88abbac2abbdf65524d576157af70556/MarkupSafe-2.1.1.tar.gz";
      sha256 = "0jqxp5sfrc0byp6bk0gwdmildi4mck2gprp42afri3z4r5y1k4bz";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "appdirs" = super.buildPythonPackage rec {
    pname = "appdirs";
    version = "1.4.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3b/00/2344469e2084fb287c2e0b57b72910309874c3245463acd6cf5e3db69324/appdirs-1.4.4-py2.py3-none-any.whl";
      sha256 = "0a5ib82s2335nhvq5rjh8hkimrwyw43xnshn3ds8lccrdg6xlhd8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2022.9.24";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1d/38/fa96a426e0c0e68aabc68e896584b83ad1eec779265a028e156ce509630e/certifi-2022.9.24-py3-none-any.whl";
      sha256 = "10pkhgnxd22ca8c9bc3d207rza6cyrq67qslhd441yb83lps7hch";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "charset-normalizer" = super.buildPythonPackage rec {
    pname = "charset-normalizer";
    version = "2.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/db/51/a507c856293ab05cdc1db77ff4bc1268ddd39f29e7dc4919aa497f0adbec/charset_normalizer-2.1.1-py3-none-any.whl";
      sha256 = "17z2zvkvalb66i5hasshq0grsma8afs6hb1mi7yrl9qi35fsgsc3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "colorspacious" = super.buildPythonPackage rec {
    pname = "colorspacious";
    version = "1.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ab/a1/318b9aeca7b9856410ededa4f52d6f82174d1a41e64bdd70d951e532675a/colorspacious-1.1.2-py2.py3-none-any.whl";
      sha256 = "0vzxwdliwg8m54q17mbcpzp6jr7957fyfr146g5xr9ff0fkfz2y7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."numpy"
    ];
  };
  "contourpy" = super.buildPythonPackage rec {
    pname = "contourpy";
    version = "1.0.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8f/4f/8a5789867f2a928fd9b32e7e8d4bc0f27a765aa7056989e7427f2c2a1966/contourpy-1.0.6.tar.gz";
      sha256 = "0hm1jz56mpyx2wgf2g53f4crhnc09wbh1h4wq4i4rvmmifxrwibf";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."numpy"
    ];
  };
  "cycler" = super.buildPythonPackage rec {
    pname = "cycler";
    version = "0.11.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5c/f9/695d6bedebd747e5eb0fe8fad57b72fdf25411273a39791cde838d5a8f51/cycler-0.11.0-py3-none-any.whl";
      sha256 = "18v5s7585w6mqhw4qz6168m92k29lygrgp9akmrqlhisfrgyj9rs";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "darkdetect" = super.buildPythonPackage rec {
    pname = "darkdetect";
    version = "0.7.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/63/bd/b31abc8fcaab163e0b9501020309dd9094b47d609035a23e6ec0a0a8ba10/darkdetect-0.7.1-py2.py3-none-any.whl";
      sha256 = "0rn8rclsbqpzh0ij4jfc8ly4j3kbclzxkldhzgsbgwfmxkw6kziy";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "decorator" = super.buildPythonPackage rec {
    pname = "decorator";
    version = "5.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d5/50/83c593b07763e1161326b3b8c6686f0f4b0f24d5526546bee538c89837d6/decorator-5.1.1-py3-none-any.whl";
      sha256 = "11kisc16y8lmka9khfvnm4gzwaa7x6n5lg4i4lr45p5r01czihxq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "fonttools" = super.buildPythonPackage rec {
    pname = "fonttools";
    version = "4.38.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e3/d9/e9bae85e84737e76ebbcbea13607236da0c0699baed0ae4f1151b728a608/fonttools-4.38.0-py3-none-any.whl";
      sha256 = "1yslmr1vdvz4d724xrhdix836h81hpkqg2zgk80c7s4b7ks6c142";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "h5io" = super.buildPythonPackage rec {
    pname = "h5io";
    version = "0.1.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/07/da/9a458c143ee79d7b340e2ac1301de14a9558336bdb07bfbd97f8e9252637/h5io-0.1.7-py3-none-any.whl";
      sha256 = "0zkkpcjpygqy7151q5zwy76m3h924lhsda1rr80rk89dx9n85bx6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."h5py"
      self."numpy"
    ];
  };
  "h5py" = super.buildPythonPackage rec {
    pname = "h5py";
    version = "3.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c5/40/7cf58e6230f0e76699f011c6d293dd47755997709a303a4e644823f3a753/h5py-3.7.0.tar.gz";
      sha256 = "1wybwpdmkdnwv16z7pk80z57s0i00wci1dbahijdmic38f43gkrz";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."numpy"
    ];
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "3.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/34/3030de6f1370931b9dbb4dad48f6ab1015ab1d32447850b9fc94e60097be/idna-3.4-py3-none-any.whl";
      sha256 = "1hn54ps4kgv2fmyvfaks38sgrvjc1cn4834sh7gadsx3x9wpxdwh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jinja2" = super.buildPythonPackage rec {
    pname = "jinja2";
    version = "3.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bc/c3/f068337a370801f372f2f8f6bad74a5c140f6fda3d9de154052708dd3c65/Jinja2-3.1.2-py3-none-any.whl";
      sha256 = "0q9a30x046p3wvbgx598g4lmxwwykk0vjsjl21khx7r3zq5r7230";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
  };
  "joblib" = super.buildPythonPackage rec {
    pname = "joblib";
    version = "1.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/91/d4/3b4c8e5a30604df4c7518c562d4bf0502f2fa29221459226e140cf846512/joblib-1.2.0-py3-none-any.whl";
      sha256 = "11fkqv1q7ax2zsh11fclhmdk0ykyjkgbs8y5d0lk807qg3nkh489";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "kiwisolver" = super.buildPythonPackage rec {
    pname = "kiwisolver";
    version = "1.4.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5f/5c/272a7dd49a1914f35cd8d6d9f386defa8b047f6fbd06badd6b77b3ba24e7/kiwisolver-1.4.4.tar.gz";
      sha256 = "0mg96grl8ixjip1bm09bgfazzw0jphqzx8mldvja396bkx8rf6fl";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "matplotlib" = super.buildPythonPackage rec {
    pname = "matplotlib";
    version = "3.6.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/91/1c/a48fd779287df3425c289cc2ff728980a5b355f15f4c3c40e1822770ba44/matplotlib-3.6.2.tar.gz";
      sha256 = "1429jq2z16km301niqjiyxsfkif4yx8bb0s80lf11l092w5d2gxh";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."contourpy"
      self."cycler"
      self."fonttools"
      self."kiwisolver"
      self."numpy"
      self."packaging"
      self."pillow"
      self."pyparsing"
      self."python-dateutil"
    ];
  };
  "mne" = super.buildPythonPackage rec {
    pname = "mne";
    version = "1.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8c/45/3ad20a14109c302ddbe6b630280bf05953d9fa2404c3a5365715e475f658/mne-1.2.2-py3-none-any.whl";
      sha256 = "1dhpb1jikd783hcak8k13pkzksdsh3i2mw1321qzw7l3grbmba01";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."decorator"
      self."jinja2"
      self."matplotlib"
      self."numpy"
      self."packaging"
      self."pooch"
      self."scipy"
      self."tqdm"
    ];
  };
  "mne-qt-browser" = super.buildPythonPackage rec {
    pname = "mne-qt-browser";
    version = "0.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ff/07/22d60a159e2a14076f478cd1c3202f79f7f86fe88ceecfa96258818ca0c1/mne_qt_browser-0.4.0-py3-none-any.whl";
      sha256 = "1k773jph0xg7bq21xwkqhpc4x4k4hln81jrxf2mbcybz42acmqbx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."colorspacious"
      self."darkdetect"
      self."matplotlib"
      self."mne"
      self."numpy"
      self."pyqtgraph"
      self."qdarkstyle"
      self."qtpy"
      self."scipy"
      self."scooby"
    ];
  };
  "numpy" = super.buildPythonPackage rec {
    pname = "numpy";
    version = "1.23.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/42/38/775b43da55fa7473015eddc9a819571517d9a271a9f8134f68fb9be2f212/numpy-1.23.5.tar.gz";
      sha256 = "06pd9nyairfl539d416wpb51bdyxg7yds580si9q3hcpygb6c5qv";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "packaging" = super.buildPythonPackage rec {
    pname = "packaging";
    version = "21.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/8e/8de486cbd03baba4deef4142bd643a3e7bbe954a784dc1bb17142572d127/packaging-21.3-py3-none-any.whl";
      sha256 = "08nmbgmf38nnxr99d5nlnacrr2jh1wp4xsi4ms1wgk8ryl2kw47g";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pyparsing"
    ];
  };
  "pillow" = super.buildPythonPackage rec {
    pname = "pillow";
    version = "9.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/16/11/da8d395299ca166aa56d9436e26fe8440e5443471de16ccd9a1d06f5993a/Pillow-9.3.0.tar.gz";
      sha256 = "03vn7s6rq943knjglm6w82clbmvd8bya1yc0sw402mksalma4df9";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pooch" = super.buildPythonPackage rec {
    pname = "pooch";
    version = "1.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8d/64/8e1bfeda3ba0f267b2d9a918e8ca51db8652d0e1a3412a5b3dbce85d90b6/pooch-1.6.0-py3-none-any.whl";
      sha256 = "171wwbqmy9yx9gmih5k2xfmnk8l5nzdm40ffvfw3cs094w0f5w1v";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."appdirs"
      self."packaging"
      self."requests"
    ];
  };
  "pyparsing" = super.buildPythonPackage rec {
    pname = "pyparsing";
    version = "3.0.9";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6c/10/a7d0fa5baea8fe7b50f448ab742f26f52b80bfca85ac2be9d35cdd9a3246/pyparsing-3.0.9-py3-none-any.whl";
      sha256 = "1g3b426kswh9ndjdlkpf9ba0fhwz5c2hjbxb3nvfzshfl7lvl9jh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyqtgraph" = super.buildPythonPackage rec {
    pname = "pyqtgraph";
    version = "0.13.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a2/88/8f2e85c0e171b7b08357f61551614ff39c4cab644a242bc80907e2275e47/pyqtgraph-0.13.1-py3-none-any.whl";
      sha256 = "0v1dxa9vjzvld0s6gfaai7p226gzbrky6hyzl7r0p28kqa22fswh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."numpy"
    ];
  };
  "python-dateutil" = super.buildPythonPackage rec {
    pname = "python-dateutil";
    version = "2.8.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl";
      sha256 = "1aaxjfp4lrz8c6qls3vdhw554lan3khy9afyvdcvrssk6kf067cn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "python-json-logger" = super.buildPythonPackage rec {
    pname = "python-json-logger";
    version = "2.0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cd/c7/beaf6614f94fcaf02f7f2e6dd29c15a4d4da863ee13b7a791964be24e87b/python_json_logger-2.0.4-py3-none-any.whl";
      sha256 = "0vwcgpasx6r5hrawzkl9zn14nfdmb0rh4apwwivlz7pb2ixlh0rv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "qdarkstyle" = super.buildPythonPackage rec {
    pname = "qdarkstyle";
    version = "3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/48/59/01f454d0eacb6670c77add68611b7a572455ae69ba902d270ed761869f87/QDarkStyle-3.1-py2.py3-none-any.whl";
      sha256 = "1cm9fi4wa7f4959884nrr09dnbrh20rliblcifn9zpj0s3y3i6k7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."qtpy"
    ];
  };
  "qtpy" = super.buildPythonPackage rec {
    pname = "qtpy";
    version = "2.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ca/56/3dfbcf8a6808d2b3566b75759c48a281bcdc2b9547760e5d044e6ec7e33b/QtPy-2.3.0-py3-none-any.whl";
      sha256 = "025lpvk9sa43y2sc1pphhm3n2p0kws99a67ac1rx5b0gq97m8vcd";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."packaging"
    ];
  };
  "requests" = super.buildPythonPackage rec {
    pname = "requests";
    version = "2.28.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ca/91/6d9b8ccacd0412c08820f72cebaa4f0c0441b5cda699c90f618b6f8a1b42/requests-2.28.1-py3-none-any.whl";
      sha256 = "0jakwryf077k46wbs525hrkxlyg4prpq6hdc199ganrnl6hs5vwg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."charset-normalizer"
      self."idna"
      self."urllib3"
    ];
  };
  "scikit-learn" = super.buildPythonPackage rec {
    pname = "scikit-learn";
    version = "1.1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/38/bc/319f789ce0988d9bf1379d6e40498dc119b30bec133bf76cd82ca549b69a/scikit-learn-1.1.3.tar.gz";
      sha256 = "0dafpd9b38vlddsi2f2gi0jwhjgaximbirqgf1vrkh8ylmw1kxdy";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."joblib"
      self."numpy"
      self."scipy"
      self."threadpoolctl"
    ];
  };
  "scipy" = super.buildPythonPackage rec {
    pname = "scipy";
    version = "1.9.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0a/2e/44795c6398e24e45fa0bb61c3e98de1cfea567b1b51efd3751e2f7ff9720/scipy-1.9.3.tar.gz";
      sha256 = "09x0w6jlxdlbg7xxjavdkibl9g43gh493x8zggkjp861hmfc1igv";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."numpy"
    ];
  };
  "scooby" = super.buildPythonPackage rec {
    pname = "scooby";
    version = "0.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/58/8c/3dcb004ff7e287855510e4b3586127c7bf834d5be0d0f25a663aa05973cb/scooby-0.7.0-py3-none-any.whl";
      sha256 = "04sx8vdrjfjh1v2xk1aq4h8vlnvrdlmp61y3jwrjwd9m3hp63xs2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.16.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl";
      sha256 = "0m02dsi8lvrjf4bi20ab6lm7rr6krz7pg6lzk3xjs2l9hqfjzfwa";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "threadpoolctl" = super.buildPythonPackage rec {
    pname = "threadpoolctl";
    version = "3.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/61/cf/6e354304bcb9c6413c4e02a747b600061c21d38ba51e7e544ac7bc66aecc/threadpoolctl-3.1.0-py3-none-any.whl";
      sha256 = "0ywh4j89jbrp5vazy89dfwdmdrmjwzn1xx0d51rngssz4vdav6cb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tqdm" = super.buildPythonPackage rec {
    pname = "tqdm";
    version = "4.64.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/47/bb/849011636c4da2e44f1253cd927cfb20ada4374d8b3a4e425416e84900cc/tqdm-4.64.1-py2.py3-none-any.whl";
      sha256 = "18d68ickjbf5jb73aqvj0722p0r2kj14rwb5ik3b3lgwdw6idvkg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "urllib3" = super.buildPythonPackage rec {
    pname = "urllib3";
    version = "1.26.12";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6f/de/5be2e3eed8426f871b170663333a0f627fc2924cc386cd41be065e7ea870/urllib3-1.26.12-py2.py3-none-any.whl";
      sha256 = "15z9xsfhxg94ypa1r7907cg91rsg2hsvnzv3d83gp2jsin3xsc5r";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
