# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projectMainScreenWidgetEpochs.ui'
#
# Created: Tue Mar 19 14:21:17 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(902, 842)
        self.dockWidget = QtGui.QDockWidget(Form)
        self.dockWidget.setGeometry(QtCore.QRect(0, 10, 400, 761))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(400, 41))
        self.dockWidget.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.LeftDockWidgetArea)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.treeWidget_2 = QtGui.QTreeWidget(self.dockWidgetContents_2)
        self.treeWidget_2.setGeometry(QtCore.QRect(2, 5, 256, 192))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_2.sizePolicy().hasHeightForWidth())
        self.treeWidget_2.setSizePolicy(sizePolicy)
        self.treeWidget_2.setMaximumSize(QtCore.QSize(3000, 2000))
        self.treeWidget_2.setBaseSize(QtCore.QSize(0, 0))
        self.treeWidget_2.setObjectName(_fromUtf8("treeWidget_2"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_2)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.tabWidget_2 = QtGui.QTabWidget(self.dockWidgetContents_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(2, 203, 351, 501))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tabRecommended_2 = QtGui.QWidget()
        self.tabRecommended_2.setAccessibleName(_fromUtf8(""))
        self.tabRecommended_2.setObjectName(_fromUtf8("tabRecommended_2"))
        self.layoutWidget_6 = QtGui.QWidget(self.tabRecommended_2)
        self.layoutWidget_6.setGeometry(QtCore.QRect(20, 30, 97, 107))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButtonEpoch_2 = QtGui.QPushButton(self.layoutWidget_6)
        self.pushButtonEpoch_2.setObjectName(_fromUtf8("pushButtonEpoch_2"))
        self.verticalLayout_2.addWidget(self.pushButtonEpoch_2)
        self.pushButtonSSS_2 = QtGui.QPushButton(self.layoutWidget_6)
        self.pushButtonSSS_2.setObjectName(_fromUtf8("pushButtonSSS_2"))
        self.verticalLayout_2.addWidget(self.pushButtonSSS_2)
        self.pushButtonMC_2 = QtGui.QPushButton(self.layoutWidget_6)
        self.pushButtonMC_2.setObjectName(_fromUtf8("pushButtonMC_2"))
        self.verticalLayout_2.addWidget(self.pushButtonMC_2)
        self.tabWidget_2.addTab(self.tabRecommended_2, _fromUtf8(""))
        self.tabInfo_2 = QtGui.QWidget()
        self.tabInfo_2.setObjectName(_fromUtf8("tabInfo_2"))
        self.layoutWidget_7 = QtGui.QWidget(self.tabInfo_2)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 10, 301, 391))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.metaBox_2 = QtGui.QGroupBox(self.layoutWidget_7)
        self.metaBox_2.setObjectName(_fromUtf8("metaBox_2"))
        self.layoutWidget_8 = QtGui.QWidget(self.metaBox_2)
        self.layoutWidget_8.setGeometry(QtCore.QRect(26, 35, 113, 23))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget_8)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.labelDate_2 = QtGui.QLabel(self.layoutWidget_8)
        self.labelDate_2.setObjectName(_fromUtf8("labelDate_2"))
        self.gridLayout_5.addWidget(self.labelDate_2, 0, 0, 1, 1)
        self.labelDateValue_2 = QtGui.QLabel(self.layoutWidget_8)
        self.labelDateValue_2.setObjectName(_fromUtf8("labelDateValue_2"))
        self.gridLayout_5.addWidget(self.labelDateValue_2, 0, 1, 1, 1)
        self.filtersBox_2 = QtGui.QGroupBox(self.metaBox_2)
        self.filtersBox_2.setGeometry(QtCore.QRect(0, 70, 299, 125))
        self.filtersBox_2.setObjectName(_fromUtf8("filtersBox_2"))
        self.layoutWidget_9 = QtGui.QWidget(self.filtersBox_2)
        self.layoutWidget_9.setGeometry(QtCore.QRect(23, 31, 181, 77))
        self.layoutWidget_9.setObjectName(_fromUtf8("layoutWidget_9"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget_9)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.labelLow_2 = QtGui.QLabel(self.layoutWidget_9)
        self.labelLow_2.setLineWidth(1)
        self.labelLow_2.setScaledContents(True)
        self.labelLow_2.setObjectName(_fromUtf8("labelLow_2"))
        self.gridLayout_6.addWidget(self.labelLow_2, 0, 0, 1, 1)
        self.labelLowValue_2 = QtGui.QLabel(self.layoutWidget_9)
        self.labelLowValue_2.setObjectName(_fromUtf8("labelLowValue_2"))
        self.gridLayout_6.addWidget(self.labelLowValue_2, 0, 1, 1, 1)
        self.labelHigh_2 = QtGui.QLabel(self.layoutWidget_9)
        self.labelHigh_2.setObjectName(_fromUtf8("labelHigh_2"))
        self.gridLayout_6.addWidget(self.labelHigh_2, 1, 0, 1, 1)
        self.labelHighValue_2 = QtGui.QLabel(self.layoutWidget_9)
        self.labelHighValue_2.setObjectName(_fromUtf8("labelHighValue_2"))
        self.gridLayout_6.addWidget(self.labelHighValue_2, 1, 1, 1, 1)
        self.labelSfreq_2 = QtGui.QLabel(self.layoutWidget_9)
        self.labelSfreq_2.setObjectName(_fromUtf8("labelSfreq_2"))
        self.gridLayout_6.addWidget(self.labelSfreq_2, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget_9)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_6.addWidget(self.label_6, 2, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.metaBox_2)
        self.channelsBox_2 = QtGui.QGroupBox(self.layoutWidget_7)
        self.channelsBox_2.setObjectName(_fromUtf8("channelsBox_2"))
        self.layoutWidget_10 = QtGui.QWidget(self.channelsBox_2)
        self.layoutWidget_10.setGeometry(QtCore.QRect(20, 23, 194, 104))
        self.layoutWidget_10.setObjectName(_fromUtf8("layoutWidget_10"))
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget_10)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.labelEEG_2 = QtGui.QLabel(self.layoutWidget_10)
        self.labelEEG_2.setObjectName(_fromUtf8("labelEEG_2"))
        self.gridLayout_7.addWidget(self.labelEEG_2, 0, 0, 1, 1)
        self.labelEEGValue_2 = QtGui.QLabel(self.layoutWidget_10)
        self.labelEEGValue_2.setObjectName(_fromUtf8("labelEEGValue_2"))
        self.gridLayout_7.addWidget(self.labelEEGValue_2, 0, 1, 1, 1)
        self.labelGradMEG_2 = QtGui.QLabel(self.layoutWidget_10)
        self.labelGradMEG_2.setObjectName(_fromUtf8("labelGradMEG_2"))
        self.gridLayout_7.addWidget(self.labelGradMEG_2, 1, 0, 1, 1)
        self.labelGradMEGValue_2 = QtGui.QLabel(self.layoutWidget_10)
        self.labelGradMEGValue_2.setObjectName(_fromUtf8("labelGradMEGValue_2"))
        self.gridLayout_7.addWidget(self.labelGradMEGValue_2, 1, 1, 1, 1)
        self.labelMagMEG_2 = QtGui.QLabel(self.layoutWidget_10)
        self.labelMagMEG_2.setObjectName(_fromUtf8("labelMagMEG_2"))
        self.gridLayout_7.addWidget(self.labelMagMEG_2, 2, 0, 1, 1)
        self.labelMagMEGValue_2 = QtGui.QLabel(self.layoutWidget_10)
        self.labelMagMEGValue_2.setObjectName(_fromUtf8("labelMagMEGValue_2"))
        self.gridLayout_7.addWidget(self.labelMagMEGValue_2, 2, 1, 1, 1)
        self.labelSamples_2 = QtGui.QLabel(self.layoutWidget_10)
        self.labelSamples_2.setObjectName(_fromUtf8("labelSamples_2"))
        self.gridLayout_7.addWidget(self.labelSamples_2, 3, 0, 1, 1)
        self.labelSamplesValue_2 = QtGui.QLabel(self.layoutWidget_10)
        self.labelSamplesValue_2.setObjectName(_fromUtf8("labelSamplesValue_2"))
        self.gridLayout_7.addWidget(self.labelSamplesValue_2, 3, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.channelsBox_2)
        self.tabWidget_2.addTab(self.tabInfo_2, _fromUtf8(""))
        self.dockWidget.setWidget(self.dockWidgetContents_2)
        self.frame = QtGui.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(450, 20, 421, 751))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))

        self.retranslateUi(Form)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.treeWidget_2.headerItem().setText(0, _translate("Form", "1", None))
        __sortingEnabled = self.treeWidget_2.isSortingEnabled()
        self.treeWidget_2.setSortingEnabled(False)
        self.treeWidget_2.topLevelItem(0).setText(0, _translate("Form", "Original raw", None))
        self.treeWidget_2.topLevelItem(0).child(0).setText(0, _translate("Form", "sss", None))
        self.treeWidget_2.topLevelItem(0).child(1).setText(0, _translate("Form", "tsss", None))
        self.treeWidget_2.topLevelItem(0).child(1).child(0).setText(0, _translate("Form", "high-pass(parameters)", None))
        self.treeWidget_2.setSortingEnabled(__sortingEnabled)
        self.pushButtonEpoch_2.setText(_translate("Form", "Epoch", None))
        self.pushButtonSSS_2.setText(_translate("Form", "SSS", None))
        self.pushButtonMC_2.setText(_translate("Form", "MC", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabRecommended_2), _translate("Form", "Recommended actions", None))
        self.metaBox_2.setTitle(_translate("Form", "Background", None))
        self.labelDate_2.setText(_translate("Form", "Date:", None))
        self.labelDateValue_2.setText(_translate("Form", "DateValue", None))
        self.filtersBox_2.setTitle(_translate("Form", "Filters", None))
        self.labelLow_2.setText(_translate("Form", "Low-pass:", None))
        self.labelLowValue_2.setText(_translate("Form", "Low-pass value", None))
        self.labelHigh_2.setText(_translate("Form", "High-pass:", None))
        self.labelHighValue_2.setText(_translate("Form", "High-pass value", None))
        self.labelSfreq_2.setText(_translate("Form", "TextLabel:", None))
        self.label_6.setText(_translate("Form", "TextLabel", None))
        self.channelsBox_2.setTitle(_translate("Form", "Channels", None))
        self.labelEEG_2.setText(_translate("Form", "EEG:", None))
        self.labelEEGValue_2.setText(_translate("Form", "EEG value", None))
        self.labelGradMEG_2.setText(_translate("Form", "Grad. MEG:", None))
        self.labelGradMEGValue_2.setText(_translate("Form", "Grad. MEG value", None))
        self.labelMagMEG_2.setText(_translate("Form", "Mag. MEG:", None))
        self.labelMagMEGValue_2.setText(_translate("Form", "Mag. MEG value", None))
        self.labelSamples_2.setText(_translate("Form", "Samples:", None))
        self.labelSamplesValue_2.setText(_translate("Form", "SamplesValue", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabInfo_2), _translate("Form", "Info", None))

