# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../layoutDialogUi.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Layout(object):
    def setupUi(self, Layout):
        Layout.setObjectName("Layout")
        Layout.resize(532, 171)
        self.gridLayout = QtWidgets.QGridLayout(Layout)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButtonSelectLayout = QtWidgets.QRadioButton(Layout)
        self.radioButtonSelectLayout.setChecked(True)
        self.radioButtonSelectLayout.setObjectName("radioButtonSelectLayout")
        self.gridLayout_2.addWidget(self.radioButtonSelectLayout, 0, 0, 1, 1)
        self.pushButtonBrowseLayout = QtWidgets.QPushButton(Layout)
        self.pushButtonBrowseLayout.setEnabled(False)
        self.pushButtonBrowseLayout.setObjectName("pushButtonBrowseLayout")
        self.gridLayout_2.addWidget(self.pushButtonBrowseLayout, 1, 1, 1, 1)
        self.radioButtonLayoutFromFile = QtWidgets.QRadioButton(Layout)
        self.radioButtonLayoutFromFile.setObjectName("radioButtonLayoutFromFile")
        self.gridLayout_2.addWidget(self.radioButtonLayoutFromFile, 1, 0, 1, 1)
        self.comboBoxLayout = QtWidgets.QComboBox(Layout)
        self.comboBoxLayout.setObjectName("comboBoxLayout")
        self.comboBoxLayout.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxLayout, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Layout)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.labelLayout = QtWidgets.QLabel(Layout)
        self.labelLayout.setObjectName("labelLayout")
        self.gridLayout_2.addWidget(self.labelLayout, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.line = QtWidgets.QFrame(Layout)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(Layout)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.labelLayoutActive = QtWidgets.QLabel(Layout)
        self.labelLayoutActive.setObjectName("labelLayoutActive")
        self.horizontalLayout_3.addWidget(self.labelLayoutActive)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButtonReject_2 = QtWidgets.QPushButton(Layout)
        self.pushButtonReject_2.setObjectName("pushButtonReject_2")
        self.horizontalLayout.addWidget(self.pushButtonReject_2)
        self.pushButtonAccept = QtWidgets.QPushButton(Layout)
        self.pushButtonAccept.setObjectName("pushButtonAccept")
        self.horizontalLayout.addWidget(self.pushButtonAccept)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Layout)
        self.radioButtonLayoutFromFile.toggled['bool'].connect(self.pushButtonBrowseLayout.setEnabled)
        self.pushButtonReject_2.clicked.connect(Layout.reject)
        self.pushButtonAccept.clicked.connect(Layout.accept)
        QtCore.QMetaObject.connectSlotsByName(Layout)

    def retranslateUi(self, Layout):
        _translate = QtCore.QCoreApplication.translate
        Layout.setWindowTitle(_translate("Layout", "Meggie - Select layout"))
        self.radioButtonSelectLayout.setText(_translate("Layout", "Select layout"))
        self.pushButtonBrowseLayout.setText(_translate("Layout", "Browse..."))
        self.radioButtonLayoutFromFile.setText(_translate("Layout", "Layout from file"))
        self.comboBoxLayout.setItemText(0, _translate("Layout", "Infer from data"))
        self.label_2.setText(_translate("Layout", "Change layout to:"))
        self.labelLayout.setText(_translate("Layout", "Infer from data"))
        self.label.setText(_translate("Layout", "Layout currently:"))
        self.labelLayoutActive.setText(_translate("Layout", "Infer from data"))
        self.pushButtonReject_2.setText(_translate("Layout", "Cancel"))
        self.pushButtonAccept.setText(_translate("Layout", "Ok"))

