# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../forwardSolutionDialogUi.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_forwardSolutionDialog(object):
    def setupUi(self, forwardSolutionDialog):
        forwardSolutionDialog.setObjectName("forwardSolutionDialog")
        forwardSolutionDialog.resize(572, 372)
        forwardSolutionDialog.setModal(True)
        self.formLayout_3 = QtWidgets.QFormLayout(forwardSolutionDialog)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelForwardSolutionName = QtWidgets.QLabel(forwardSolutionDialog)
        self.labelForwardSolutionName.setObjectName("labelForwardSolutionName")
        self.horizontalLayout_6.addWidget(self.labelForwardSolutionName)
        self.lineEditForwardSolutionName = QtWidgets.QLineEdit(forwardSolutionDialog)
        self.lineEditForwardSolutionName.setObjectName("lineEditForwardSolutionName")
        self.horizontalLayout_6.addWidget(self.lineEditForwardSolutionName)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_6)
        self.groupBoxSourceSpaceSetup = QtWidgets.QGroupBox(forwardSolutionDialog)
        self.groupBoxSourceSpaceSetup.setObjectName("groupBoxSourceSpaceSetup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxSourceSpaceSetup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelIco = QtWidgets.QLabel(self.groupBoxSourceSpaceSetup)
        self.labelIco.setObjectName("labelIco")
        self.gridLayout_3.addWidget(self.labelIco, 0, 0, 1, 1)
        self.comboBoxSurfaceDecimMethod = QtWidgets.QComboBox(self.groupBoxSourceSpaceSetup)
        self.comboBoxSurfaceDecimMethod.setObjectName("comboBoxSurfaceDecimMethod")
        self.comboBoxSurfaceDecimMethod.addItem("")
        self.comboBoxSurfaceDecimMethod.addItem("")
        self.comboBoxSurfaceDecimMethod.addItem("")
        self.comboBoxSurfaceDecimMethod.addItem("")
        self.gridLayout_3.addWidget(self.comboBoxSurfaceDecimMethod, 0, 1, 1, 2)
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.groupBoxSourceSpaceSetup)
        self.groupBoxSetupBem = QtWidgets.QGroupBox(forwardSolutionDialog)
        self.groupBoxSetupBem.setObjectName("groupBoxSetupBem")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxSetupBem)
        self.gridLayout.setObjectName("gridLayout")
        self.labelHomog = QtWidgets.QLabel(self.groupBoxSetupBem)
        self.labelHomog.setObjectName("labelHomog")
        self.gridLayout.addWidget(self.labelHomog, 3, 0, 1, 1)
        self.comboBoxCompartmentModel = QtWidgets.QComboBox(self.groupBoxSetupBem)
        self.comboBoxCompartmentModel.setObjectName("comboBoxCompartmentModel")
        self.comboBoxCompartmentModel.addItem("")
        self.comboBoxCompartmentModel.addItem("")
        self.gridLayout.addWidget(self.comboBoxCompartmentModel, 3, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.groupBoxSetupBem)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.labelConductivity = QtWidgets.QLabel(self.frame_2)
        self.labelConductivity.setObjectName("labelConductivity")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.labelConductivity)
        self.labelBrainComp = QtWidgets.QLabel(self.frame_2)
        self.labelBrainComp.setObjectName("labelBrainComp")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelBrainComp)
        self.doubleSpinBoxBrainConductivity = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBoxBrainConductivity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBrainConductivity.setDecimals(2)
        self.doubleSpinBoxBrainConductivity.setProperty("value", 0.3)
        self.doubleSpinBoxBrainConductivity.setObjectName("doubleSpinBoxBrainConductivity")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxBrainConductivity)
        self.labelSkullComp = QtWidgets.QLabel(self.frame_2)
        self.labelSkullComp.setObjectName("labelSkullComp")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelSkullComp)
        self.doubleSpinBoxSkullConductivity = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBoxSkullConductivity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxSkullConductivity.setPrefix("")
        self.doubleSpinBoxSkullConductivity.setDecimals(3)
        self.doubleSpinBoxSkullConductivity.setProperty("value", 0.006)
        self.doubleSpinBoxSkullConductivity.setObjectName("doubleSpinBoxSkullConductivity")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxSkullConductivity)
        self.labelScalpComp = QtWidgets.QLabel(self.frame_2)
        self.labelScalpComp.setObjectName("labelScalpComp")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelScalpComp)
        self.doubleSpinBoxScalpConductivity = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBoxScalpConductivity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxScalpConductivity.setProperty("value", 0.03)
        self.doubleSpinBoxScalpConductivity.setObjectName("doubleSpinBoxScalpConductivity")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxScalpConductivity)
        self.gridLayout.addWidget(self.frame_2, 4, 1, 1, 1)
        self.labelTriangIco = QtWidgets.QLabel(self.groupBoxSetupBem)
        self.labelTriangIco.setObjectName("labelTriangIco")
        self.gridLayout.addWidget(self.labelTriangIco, 2, 0, 1, 1)
        self.spinBoxTriangFilesIco = QtWidgets.QSpinBox(self.groupBoxSetupBem)
        self.spinBoxTriangFilesIco.setEnabled(True)
        self.spinBoxTriangFilesIco.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxTriangFilesIco.setProperty("value", 4)
        self.spinBoxTriangFilesIco.setObjectName("spinBoxTriangFilesIco")
        self.gridLayout.addWidget(self.spinBoxTriangFilesIco, 2, 1, 1, 1)
        self.labelIncludeMEG = QtWidgets.QLabel(self.groupBoxSetupBem)
        self.labelIncludeMEG.setObjectName("labelIncludeMEG")
        self.gridLayout.addWidget(self.labelIncludeMEG, 0, 0, 1, 1)
        self.checkBoxIncludeMEG = QtWidgets.QCheckBox(self.groupBoxSetupBem)
        self.checkBoxIncludeMEG.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBoxIncludeMEG.setText("")
        self.checkBoxIncludeMEG.setChecked(True)
        self.checkBoxIncludeMEG.setObjectName("checkBoxIncludeMEG")
        self.gridLayout.addWidget(self.checkBoxIncludeMEG, 0, 1, 1, 1)
        self.labelIncludeEEG = QtWidgets.QLabel(self.groupBoxSetupBem)
        self.labelIncludeEEG.setObjectName("labelIncludeEEG")
        self.gridLayout.addWidget(self.labelIncludeEEG, 1, 0, 1, 1)
        self.checkBoxIncludeEEG = QtWidgets.QCheckBox(self.groupBoxSetupBem)
        self.checkBoxIncludeEEG.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBoxIncludeEEG.setText("")
        self.checkBoxIncludeEEG.setObjectName("checkBoxIncludeEEG")
        self.gridLayout.addWidget(self.checkBoxIncludeEEG, 1, 1, 1, 1)
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.groupBoxSetupBem)
        self.buttonBox = QtWidgets.QDialogButtonBox(forwardSolutionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)
        self.labelHomog.setBuddy(self.comboBoxCompartmentModel)
        self.labelBrainComp.setBuddy(self.doubleSpinBoxBrainConductivity)
        self.labelSkullComp.setBuddy(self.doubleSpinBoxSkullConductivity)
        self.labelScalpComp.setBuddy(self.doubleSpinBoxScalpConductivity)

        self.retranslateUi(forwardSolutionDialog)
        self.buttonBox.accepted.connect(forwardSolutionDialog.accept)
        self.buttonBox.rejected.connect(forwardSolutionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(forwardSolutionDialog)

    def retranslateUi(self, forwardSolutionDialog):
        _translate = QtCore.QCoreApplication.translate
        forwardSolutionDialog.setWindowTitle(_translate("forwardSolutionDialog", "Create new forward solution"))
        self.labelForwardSolutionName.setText(_translate("forwardSolutionDialog", "Forward solution name:"))
        self.groupBoxSourceSpaceSetup.setTitle(_translate("forwardSolutionDialog", "Source space setup parameters:"))
        self.labelIco.setText(_translate("forwardSolutionDialog", "Cortical surface decimation method:"))
        self.comboBoxSurfaceDecimMethod.setItemText(0, _translate("forwardSolutionDialog", "ico4"))
        self.comboBoxSurfaceDecimMethod.setItemText(1, _translate("forwardSolutionDialog", "oct5"))
        self.comboBoxSurfaceDecimMethod.setItemText(2, _translate("forwardSolutionDialog", "ico5"))
        self.comboBoxSurfaceDecimMethod.setItemText(3, _translate("forwardSolutionDialog", "oct6"))
        self.groupBoxSetupBem.setTitle(_translate("forwardSolutionDialog", "BEM model setup parameters:"))
        self.labelHomog.setText(_translate("forwardSolutionDialog", "Compartment model (homog) :"))
        self.comboBoxCompartmentModel.setItemText(0, _translate("forwardSolutionDialog", "single (usually used with MEG)"))
        self.comboBoxCompartmentModel.setItemText(1, _translate("forwardSolutionDialog", "three layer"))
        self.labelConductivity.setText(_translate("forwardSolutionDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Conductivity:</span></p></body></html>"))
        self.labelBrainComp.setText(_translate("forwardSolutionDialog", "inner skull:"))
        self.doubleSpinBoxBrainConductivity.setSuffix(_translate("forwardSolutionDialog", " S/m"))
        self.labelSkullComp.setText(_translate("forwardSolutionDialog", "outer skull:"))
        self.doubleSpinBoxSkullConductivity.setSuffix(_translate("forwardSolutionDialog", " S/m"))
        self.labelScalpComp.setText(_translate("forwardSolutionDialog", "outer skin:"))
        self.doubleSpinBoxScalpConductivity.setSuffix(_translate("forwardSolutionDialog", " S/m"))
        self.labelTriangIco.setText(_translate("forwardSolutionDialog", "Triangulation files ico-number:"))
        self.labelIncludeMEG.setText(_translate("forwardSolutionDialog", "Include MEG:"))
        self.labelIncludeEEG.setText(_translate("forwardSolutionDialog", "Include EEG:"))

