# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lcmvDialogUi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_lcmvDialog(object):
    def setupUi(self, lcmvDialog):
        lcmvDialog.setObjectName(_fromUtf8("lcmvDialog"))
        lcmvDialog.resize(587, 529)
        lcmvDialog.setModal(True)
        self.formLayout_3 = QtGui.QFormLayout(lcmvDialog)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.labelSourceEstimateName = QtGui.QLabel(lcmvDialog)
        self.labelSourceEstimateName.setObjectName(_fromUtf8("labelSourceEstimateName"))
        self.horizontalLayout_6.addWidget(self.labelSourceEstimateName)
        self.lineEditSourceEstimateName = QtGui.QLineEdit(lcmvDialog)
        self.lineEditSourceEstimateName.setObjectName(_fromUtf8("lineEditSourceEstimateName"))
        self.horizontalLayout_6.addWidget(self.lineEditSourceEstimateName)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelBasedOn = QtGui.QLabel(lcmvDialog)
        self.labelBasedOn.setObjectName(_fromUtf8("labelBasedOn"))
        self.horizontalLayout.addWidget(self.labelBasedOn)
        self.lineEditBasedOn = QtGui.QLineEdit(lcmvDialog)
        self.lineEditBasedOn.setEnabled(False)
        self.lineEditBasedOn.setObjectName(_fromUtf8("lineEditBasedOn"))
        self.horizontalLayout.addWidget(self.lineEditBasedOn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.labelData = QtGui.QLabel(lcmvDialog)
        self.labelData.setObjectName(_fromUtf8("labelData"))
        self.horizontalLayout_8.addWidget(self.labelData)
        self.lineEditData = QtGui.QLineEdit(lcmvDialog)
        self.lineEditData.setEnabled(False)
        self.lineEditData.setObjectName(_fromUtf8("lineEditData"))
        self.horizontalLayout_8.addWidget(self.lineEditData)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.formLayout_3.setLayout(0, QtGui.QFormLayout.SpanningRole, self.verticalLayout)
        self.covarianceParameters = QtGui.QGroupBox(lcmvDialog)
        self.covarianceParameters.setObjectName(_fromUtf8("covarianceParameters"))
        self.gridLayout_3 = QtGui.QGridLayout(self.covarianceParameters)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.labelNoiseCovariance = QtGui.QLabel(self.covarianceParameters)
        self.labelNoiseCovariance.setObjectName(_fromUtf8("labelNoiseCovariance"))
        self.horizontalLayout_9.addWidget(self.labelNoiseCovariance)
        self.comboBoxNoiseCovariance = QtGui.QComboBox(self.covarianceParameters)
        self.comboBoxNoiseCovariance.setObjectName(_fromUtf8("comboBoxNoiseCovariance"))
        self.horizontalLayout_9.addWidget(self.comboBoxNoiseCovariance)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelDataCovariance = QtGui.QLabel(self.covarianceParameters)
        self.labelDataCovariance.setObjectName(_fromUtf8("labelDataCovariance"))
        self.horizontalLayout_2.addWidget(self.labelDataCovariance)
        self.comboBoxDataCovariance = QtGui.QComboBox(self.covarianceParameters)
        self.comboBoxDataCovariance.setObjectName(_fromUtf8("comboBoxDataCovariance"))
        self.horizontalLayout_2.addWidget(self.comboBoxDataCovariance)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.SpanningRole, self.covarianceParameters)
        self.buttonBox = QtGui.QDialogButtonBox(lcmvDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.FieldRole, self.buttonBox)
        self.groupBoxStcParameters = QtGui.QGroupBox(lcmvDialog)
        self.groupBoxStcParameters.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBoxStcParameters.setObjectName(_fromUtf8("groupBoxStcParameters"))
        self.gridLayout = QtGui.QGridLayout(self.groupBoxStcParameters)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.labelLabel = QtGui.QLabel(self.groupBoxStcParameters)
        self.labelLabel.setObjectName(_fromUtf8("labelLabel"))
        self.horizontalLayout_7.addWidget(self.labelLabel)
        self.comboBoxLabel = QtGui.QComboBox(self.groupBoxStcParameters)
        self.comboBoxLabel.setObjectName(_fromUtf8("comboBoxLabel"))
        self.horizontalLayout_7.addWidget(self.comboBoxLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.labelReg = QtGui.QLabel(self.groupBoxStcParameters)
        self.labelReg.setObjectName(_fromUtf8("labelReg"))
        self.horizontalLayout_4.addWidget(self.labelReg)
        self.doubleSpinBoxReg = QtGui.QDoubleSpinBox(self.groupBoxStcParameters)
        self.doubleSpinBoxReg.setSingleStep(0.05)
        self.doubleSpinBoxReg.setProperty("value", 0.05)
        self.doubleSpinBoxReg.setObjectName(_fromUtf8("doubleSpinBoxReg"))
        self.horizontalLayout_4.addWidget(self.doubleSpinBoxReg)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.SpanningRole, self.groupBoxStcParameters)
        self.groupBoxTimeParameters = QtGui.QGroupBox(lcmvDialog)
        self.groupBoxTimeParameters.setEnabled(False)
        self.groupBoxTimeParameters.setObjectName(_fromUtf8("groupBoxTimeParameters"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxTimeParameters)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.labelStart = QtGui.QLabel(self.groupBoxTimeParameters)
        self.labelStart.setObjectName(_fromUtf8("labelStart"))
        self.horizontalLayout_11.addWidget(self.labelStart)
        self.doubleSpinBoxStart = QtGui.QDoubleSpinBox(self.groupBoxTimeParameters)
        self.doubleSpinBoxStart.setEnabled(False)
        self.doubleSpinBoxStart.setMaximum(9999.0)
        self.doubleSpinBoxStart.setObjectName(_fromUtf8("doubleSpinBoxStart"))
        self.horizontalLayout_11.addWidget(self.doubleSpinBoxStart)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.labelEnd = QtGui.QLabel(self.groupBoxTimeParameters)
        self.labelEnd.setObjectName(_fromUtf8("labelEnd"))
        self.horizontalLayout_10.addWidget(self.labelEnd)
        self.doubleSpinBoxEnd = QtGui.QDoubleSpinBox(self.groupBoxTimeParameters)
        self.doubleSpinBoxEnd.setEnabled(False)
        self.doubleSpinBoxEnd.setMaximum(9999.0)
        self.doubleSpinBoxEnd.setObjectName(_fromUtf8("doubleSpinBoxEnd"))
        self.horizontalLayout_10.addWidget(self.doubleSpinBoxEnd)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.SpanningRole, self.groupBoxTimeParameters)

        self.retranslateUi(lcmvDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), lcmvDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), lcmvDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(lcmvDialog)

    def retranslateUi(self, lcmvDialog):
        lcmvDialog.setWindowTitle(_translate("lcmvDialog", "Create new beamformer estimate", None))
        self.labelSourceEstimateName.setText(_translate("lcmvDialog", "Source estimate name:", None))
        self.labelBasedOn.setText(_translate("lcmvDialog", "Based on forward solution:", None))
        self.labelData.setText(_translate("lcmvDialog", "Based on dataset:", None))
        self.covarianceParameters.setTitle(_translate("lcmvDialog", "Covariance parameters", None))
        self.labelNoiseCovariance.setText(_translate("lcmvDialog", "Noise covariance:", None))
        self.labelDataCovariance.setText(_translate("lcmvDialog", "Data covariance:", None))
        self.groupBoxStcParameters.setTitle(_translate("lcmvDialog", "Source estimate parameters:", None))
        self.labelLabel.setText(_translate("lcmvDialog", "Label:", None))
        self.labelReg.setText(_translate("lcmvDialog", "Regularization parameter:", None))
        self.groupBoxTimeParameters.setTitle(_translate("lcmvDialog", "Time parameters (only for raw data)", None))
        self.labelStart.setText(_translate("lcmvDialog", "Start:", None))
        self.labelEnd.setText(_translate("lcmvDialog", "End:", None))

