# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eogParametersDialog.ui'
#
# Created: Fri Apr 12 10:02:44 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(627, 658)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.tabWidgetEOGSettings = QtGui.QTabWidget(Dialog)
        self.tabWidgetEOGSettings.setObjectName(_fromUtf8("tabWidgetEOGSettings"))
        self.tabEOG1 = QtGui.QWidget()
        self.tabEOG1.setObjectName(_fromUtf8("tabEOG1"))
        self.groupBoxEpoch = QtGui.QGroupBox(self.tabEOG1)
        self.groupBoxEpoch.setGeometry(QtCore.QRect(10, 450, 561, 101))
        self.groupBoxEpoch.setObjectName(_fromUtf8("groupBoxEpoch"))
        self.frame_4 = QtGui.QFrame(self.groupBoxEpoch)
        self.frame_4.setGeometry(QtCore.QRect(10, 30, 261, 61))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayoutWidget_13 = QtGui.QWidget(self.frame_4)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(10, 10, 241, 41))
        self.horizontalLayoutWidget_13.setObjectName(_fromUtf8("horizontalLayoutWidget_13"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.labelRejection = QtGui.QLabel(self.horizontalLayoutWidget_13)
        self.labelRejection.setObjectName(_fromUtf8("labelRejection"))
        self.horizontalLayout_14.addWidget(self.labelRejection)
        self.lineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_13)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_14.addWidget(self.lineEdit)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.labelFlat = QtGui.QLabel(self.horizontalLayoutWidget_13)
        self.labelFlat.setObjectName(_fromUtf8("labelFlat"))
        self.horizontalLayout_15.addWidget(self.labelFlat)
        self.lineEdit_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_13)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_15.addWidget(self.lineEdit_2)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_15)
        self.groupBoxFilter = QtGui.QGroupBox(self.tabEOG1)
        self.groupBoxFilter.setGeometry(QtCore.QRect(10, 340, 311, 101))
        self.groupBoxFilter.setObjectName(_fromUtf8("groupBoxFilter"))
        self.frame_7 = QtGui.QFrame(self.groupBoxFilter)
        self.frame_7.setGeometry(QtCore.QRect(10, 30, 291, 61))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.horizontalLayoutWidget_19 = QtGui.QWidget(self.frame_7)
        self.horizontalLayoutWidget_19.setGeometry(QtCore.QRect(10, 10, 271, 41))
        self.horizontalLayoutWidget_19.setObjectName(_fromUtf8("horizontalLayoutWidget_19"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_19)
        self.horizontalLayout_25.setMargin(0)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.labelLow = QtGui.QLabel(self.horizontalLayoutWidget_19)
        self.labelLow.setObjectName(_fromUtf8("labelLow"))
        self.horizontalLayout_26.addWidget(self.labelLow)
        self.spinBoxLow = QtGui.QSpinBox(self.horizontalLayoutWidget_19)
        self.spinBoxLow.setObjectName(_fromUtf8("spinBoxLow"))
        self.horizontalLayout_26.addWidget(self.spinBoxLow)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.labelHigh = QtGui.QLabel(self.horizontalLayoutWidget_19)
        self.labelHigh.setObjectName(_fromUtf8("labelHigh"))
        self.horizontalLayout_27.addWidget(self.labelHigh)
        self.spinBoxHigh = QtGui.QSpinBox(self.horizontalLayoutWidget_19)
        self.spinBoxHigh.setObjectName(_fromUtf8("spinBoxHigh"))
        self.horizontalLayout_27.addWidget(self.spinBoxHigh)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_27)
        self.groupBoxFilteringEOG = QtGui.QGroupBox(self.tabEOG1)
        self.groupBoxFilteringEOG.setGeometry(QtCore.QRect(10, 120, 471, 101))
        self.groupBoxFilteringEOG.setObjectName(_fromUtf8("groupBoxFilteringEOG"))
        self.frame_6 = QtGui.QFrame(self.groupBoxFilteringEOG)
        self.frame_6.setGeometry(QtCore.QRect(10, 30, 451, 61))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayoutWidget_20 = QtGui.QWidget(self.frame_6)
        self.horizontalLayoutWidget_20.setGeometry(QtCore.QRect(10, 10, 431, 41))
        self.horizontalLayoutWidget_20.setObjectName(_fromUtf8("horizontalLayoutWidget_20"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_20)
        self.horizontalLayout_18.setMargin(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.labelLowPass = QtGui.QLabel(self.horizontalLayoutWidget_20)
        self.labelLowPass.setObjectName(_fromUtf8("labelLowPass"))
        self.horizontalLayout_23.addWidget(self.labelLowPass)
        self.spinBoxLowPass = QtGui.QSpinBox(self.horizontalLayoutWidget_20)
        self.spinBoxLowPass.setObjectName(_fromUtf8("spinBoxLowPass"))
        self.horizontalLayout_23.addWidget(self.spinBoxLowPass)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.labelHighPass = QtGui.QLabel(self.horizontalLayoutWidget_20)
        self.labelHighPass.setObjectName(_fromUtf8("labelHighPass"))
        self.horizontalLayout_24.addWidget(self.labelHighPass)
        self.spinBoxHighPass = QtGui.QSpinBox(self.horizontalLayoutWidget_20)
        self.spinBoxHighPass.setObjectName(_fromUtf8("spinBoxHighPass"))
        self.horizontalLayout_24.addWidget(self.spinBoxHighPass)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_24)
        self.groupBoxSSP = QtGui.QGroupBox(self.tabEOG1)
        self.groupBoxSSP.setGeometry(QtCore.QRect(10, 230, 561, 101))
        self.groupBoxSSP.setObjectName(_fromUtf8("groupBoxSSP"))
        self.frame_2 = QtGui.QFrame(self.groupBoxSSP)
        self.frame_2.setGeometry(QtCore.QRect(10, 30, 321, 61))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayoutWidget_9 = QtGui.QWidget(self.frame_2)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(10, 10, 301, 41))
        self.horizontalLayoutWidget_9.setObjectName(_fromUtf8("horizontalLayoutWidget_9"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelGrad = QtGui.QLabel(self.horizontalLayoutWidget_9)
        self.labelGrad.setObjectName(_fromUtf8("labelGrad"))
        self.horizontalLayout_3.addWidget(self.labelGrad)
        self.spinBoxGrad = QtGui.QSpinBox(self.horizontalLayoutWidget_9)
        self.spinBoxGrad.setObjectName(_fromUtf8("spinBoxGrad"))
        self.horizontalLayout_3.addWidget(self.spinBoxGrad)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.labelMag = QtGui.QLabel(self.horizontalLayoutWidget_9)
        self.labelMag.setObjectName(_fromUtf8("labelMag"))
        self.horizontalLayout_4.addWidget(self.labelMag)
        self.spinBoxMag = QtGui.QSpinBox(self.horizontalLayoutWidget_9)
        self.spinBoxMag.setObjectName(_fromUtf8("spinBoxMag"))
        self.horizontalLayout_4.addWidget(self.spinBoxMag)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.labelEeg = QtGui.QLabel(self.horizontalLayoutWidget_9)
        self.labelEeg.setObjectName(_fromUtf8("labelEeg"))
        self.horizontalLayout_5.addWidget(self.labelEeg)
        self.spinBoxEeg = QtGui.QSpinBox(self.horizontalLayoutWidget_9)
        self.spinBoxEeg.setObjectName(_fromUtf8("spinBoxEeg"))
        self.horizontalLayout_5.addWidget(self.spinBoxEeg)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_5)
        self.groupBoxEvent = QtGui.QGroupBox(self.tabEOG1)
        self.groupBoxEvent.setGeometry(QtCore.QRect(10, 10, 529, 99))
        self.groupBoxEvent.setObjectName(_fromUtf8("groupBoxEvent"))
        self.frame = QtGui.QFrame(self.groupBoxEvent)
        self.frame.setGeometry(QtCore.QRect(10, 30, 491, 61))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayoutWidget_8 = QtGui.QWidget(self.frame)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 10, 471, 41))
        self.horizontalLayoutWidget_8.setObjectName(_fromUtf8("horizontalLayoutWidget_8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelTmin = QtGui.QLabel(self.horizontalLayoutWidget_8)
        self.labelTmin.setObjectName(_fromUtf8("labelTmin"))
        self.horizontalLayout.addWidget(self.labelTmin)
        self.spinBoxTmin = QtGui.QSpinBox(self.horizontalLayoutWidget_8)
        self.spinBoxTmin.setObjectName(_fromUtf8("spinBoxTmin"))
        self.horizontalLayout.addWidget(self.spinBoxTmin)
        self.horizontalLayout_8.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelTmax = QtGui.QLabel(self.horizontalLayoutWidget_8)
        self.labelTmax.setObjectName(_fromUtf8("labelTmax"))
        self.horizontalLayout_2.addWidget(self.labelTmax)
        self.spinBoxTmax = QtGui.QSpinBox(self.horizontalLayoutWidget_8)
        self.spinBoxTmax.setObjectName(_fromUtf8("spinBoxTmax"))
        self.horizontalLayout_2.addWidget(self.spinBoxTmax)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.labelEventID = QtGui.QLabel(self.horizontalLayoutWidget_8)
        self.labelEventID.setObjectName(_fromUtf8("labelEventID"))
        self.horizontalLayout_6.addWidget(self.labelEventID)
        self.lineEditEventID = QtGui.QLineEdit(self.horizontalLayoutWidget_8)
        self.lineEditEventID.setObjectName(_fromUtf8("lineEditEventID"))
        self.horizontalLayout_6.addWidget(self.lineEditEventID)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_6)
        self.tabWidgetEOGSettings.addTab(self.tabEOG1, _fromUtf8(""))
        self.tabEOG2 = QtGui.QWidget()
        self.tabEOG2.setObjectName(_fromUtf8("tabEOG2"))
        self.horizontalLayoutWidget_17 = QtGui.QWidget(self.tabEOG2)
        self.horizontalLayoutWidget_17.setGeometry(QtCore.QRect(10, 80, 351, 41))
        self.horizontalLayoutWidget_17.setObjectName(_fromUtf8("horizontalLayoutWidget_17"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_17)
        self.horizontalLayout_21.setMargin(0)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.labelStart1 = QtGui.QLabel(self.horizontalLayoutWidget_17)
        self.labelStart1.setObjectName(_fromUtf8("labelStart1"))
        self.horizontalLayout_21.addWidget(self.labelStart1)
        self.spinBoxStart = QtGui.QSpinBox(self.horizontalLayoutWidget_17)
        self.spinBoxStart.setObjectName(_fromUtf8("spinBoxStart"))
        self.horizontalLayout_21.addWidget(self.spinBoxStart)
        self.labelStart2 = QtGui.QLabel(self.horizontalLayoutWidget_17)
        self.labelStart2.setObjectName(_fromUtf8("labelStart2"))
        self.horizontalLayout_21.addWidget(self.labelStart2)
        self.horizontalLayoutWidget = QtGui.QWidget(self.tabEOG2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 180, 281, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.labelJobs = QtGui.QLabel(self.horizontalLayoutWidget)
        self.labelJobs.setObjectName(_fromUtf8("labelJobs"))
        self.horizontalLayout_7.addWidget(self.labelJobs)
        self.spinBoxJobs = QtGui.QSpinBox(self.horizontalLayoutWidget)
        self.spinBoxJobs.setObjectName(_fromUtf8("spinBoxJobs"))
        self.horizontalLayout_7.addWidget(self.spinBoxJobs)
        self.layoutWidget = QtGui.QWidget(self.tabEOG2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 401, 61))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_28.setMargin(0)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.labelBad = QtGui.QLabel(self.layoutWidget)
        self.labelBad.setObjectName(_fromUtf8("labelBad"))
        self.horizontalLayout_28.addWidget(self.labelBad)
        self.lineEditBad = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditBad.setObjectName(_fromUtf8("lineEditBad"))
        self.horizontalLayout_28.addWidget(self.lineEditBad)
        self.layoutWidget1 = QtGui.QWidget(self.tabEOG2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 130, 291, 41))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_22.setMargin(0)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.labelTaps = QtGui.QLabel(self.layoutWidget1)
        self.labelTaps.setObjectName(_fromUtf8("labelTaps"))
        self.horizontalLayout_22.addWidget(self.labelTaps)
        self.spinBoxTaps = QtGui.QSpinBox(self.layoutWidget1)
        self.spinBoxTaps.setObjectName(_fromUtf8("spinBoxTaps"))
        self.horizontalLayout_22.addWidget(self.spinBoxTaps)
        self.verticalLayoutWidget = QtGui.QWidget(self.tabEOG2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 240, 371, 111))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.checkBoxEEGProj = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxEEGProj.setObjectName(_fromUtf8("checkBoxEEGProj"))
        self.verticalLayout.addWidget(self.checkBoxEEGProj)
        self.checkBoxSSPProj = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxSSPProj.setObjectName(_fromUtf8("checkBoxSSPProj"))
        self.verticalLayout.addWidget(self.checkBoxSSPProj)
        self.checkBoxSSPCompute = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxSSPCompute.setObjectName(_fromUtf8("checkBoxSSPCompute"))
        self.verticalLayout.addWidget(self.checkBoxSSPCompute)
        self.tabWidgetEOGSettings.addTab(self.tabEOG2, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidgetEOGSettings, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidgetEOGSettings.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBoxEpoch.setTitle(_translate("Dialog", "Epoch configuration", None))
        self.labelRejection.setText(_translate("Dialog", "Rejection", None))
        self.labelFlat.setText(_translate("Dialog", "Flat", None))
        self.groupBoxFilter.setTitle(_translate("Dialog", "Filtering cut-off frequency", None))
        self.labelLow.setText(_translate("Dialog", "Low (Hz)", None))
        self.labelHigh.setText(_translate("Dialog", "High (Hz)", None))
        self.groupBoxFilteringEOG.setTitle(_translate("Dialog", "Filtering EOG channel", None))
        self.labelLowPass.setText(_translate("Dialog", "Low pass frequency", None))
        self.labelHighPass.setText(_translate("Dialog", "High pass frequency", None))
        self.groupBoxSSP.setTitle(_translate("Dialog", "Number of SSP vectors", None))
        self.labelGrad.setText(_translate("Dialog", "Grad", None))
        self.labelMag.setText(_translate("Dialog", "Mag", None))
        self.labelEeg.setText(_translate("Dialog", "Eeg", None))
        self.groupBoxEvent.setTitle(_translate("Dialog", "Events", None))
        self.labelTmin.setText(_translate("Dialog", "Start time", None))
        self.labelTmax.setText(_translate("Dialog", "End time", None))
        self.labelEventID.setText(_translate("Dialog", "Events ID", None))
        self.tabWidgetEOGSettings.setTabText(self.tabWidgetEOGSettings.indexOf(self.tabEOG1), _translate("Dialog", "EOG settings", None))
        self.labelStart1.setText(_translate("Dialog", "Start artifact detection after", None))
        self.labelStart2.setText(_translate("Dialog", "seconds.", None))
        self.labelJobs.setText(_translate("Dialog", "Number of jobs to run in parallel", None))
        self.labelBad.setText(_translate("Dialog", "Bad channels (e.g. 0323 1042 2631) :", None))
        self.labelTaps.setText(_translate("Dialog", "Number of taps to use for filtering", None))
        self.checkBoxEEGProj.setText(_translate("Dialog", "Add EEG average reference proj.", None))
        self.checkBoxSSPProj.setText(_translate("Dialog", "Exclude the SSP projectors currently in the fiff file", None))
        self.checkBoxSSPCompute.setText(_translate("Dialog", "Compute SSP after averaging", None))
        self.tabWidgetEOGSettings.setTabText(self.tabWidgetEOGSettings.indexOf(self.tabEOG2), _translate("Dialog", "Bads etc.", None))

