# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maxFilterDialog.ui'
#
# Created: Mon Apr  1 12:16:30 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setEnabled(True)
        Dialog.resize(546, 670)
        self.gridLayout_11 = QtGui.QGridLayout(Dialog)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_11.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.tabWidgetMaxFilterSettings = QtGui.QTabWidget(Dialog)
        self.tabWidgetMaxFilterSettings.setObjectName(_fromUtf8("tabWidgetMaxFilterSettings"))
        self.tabGeneral = QtGui.QWidget()
        self.tabGeneral.setObjectName(_fromUtf8("tabGeneral"))
        self.formLayout_2 = QtGui.QFormLayout(self.tabGeneral)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.labelOrderIn = QtGui.QLabel(self.tabGeneral)
        self.labelOrderIn.setObjectName(_fromUtf8("labelOrderIn"))
        self.horizontalLayout_8.addWidget(self.labelOrderIn)
        self.lineEditOrderIn = QtGui.QLineEdit(self.tabGeneral)
        self.lineEditOrderIn.setObjectName(_fromUtf8("lineEditOrderIn"))
        self.horizontalLayout_8.addWidget(self.lineEditOrderIn)
        self.labelOrderOut = QtGui.QLabel(self.tabGeneral)
        self.labelOrderOut.setObjectName(_fromUtf8("labelOrderOut"))
        self.horizontalLayout_8.addWidget(self.labelOrderOut)
        self.lineEditOrderOut = QtGui.QLineEdit(self.tabGeneral)
        self.lineEditOrderOut.setObjectName(_fromUtf8("lineEditOrderOut"))
        self.horizontalLayout_8.addWidget(self.lineEditOrderOut)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.LabelRole, self.horizontalLayout_8)
        self.groupBoxBadChannel = QtGui.QGroupBox(self.tabGeneral)
        self.groupBoxBadChannel.setObjectName(_fromUtf8("groupBoxBadChannel"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBoxBadChannel)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.frame_3 = QtGui.QFrame(self.groupBoxBadChannel)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.labelBadLimit = QtGui.QLabel(self.frame_3)
        self.labelBadLimit.setObjectName(_fromUtf8("labelBadLimit"))
        self.horizontalLayout_6.addWidget(self.labelBadLimit)
        self.lineEditBadLimit = QtGui.QLineEdit(self.frame_3)
        self.lineEditBadLimit.setObjectName(_fromUtf8("lineEditBadLimit"))
        self.horizontalLayout_6.addWidget(self.lineEditBadLimit)
        self.gridLayout_7.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.labelBad = QtGui.QLabel(self.frame_3)
        self.labelBad.setObjectName(_fromUtf8("labelBad"))
        self.horizontalLayout_5.addWidget(self.labelBad)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.lineEditBad = QtGui.QLineEdit(self.frame_3)
        self.lineEditBad.setObjectName(_fromUtf8("lineEditBad"))
        self.horizontalLayout_5.addWidget(self.lineEditBad)
        self.gridLayout_7.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.checkBoxAutobad = QtGui.QCheckBox(self.frame_3)
        self.checkBoxAutobad.setObjectName(_fromUtf8("checkBoxAutobad"))
        self.gridLayout_7.addWidget(self.checkBoxAutobad, 3, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_3, 0, 1, 1, 1)
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.groupBoxBadChannel)
        self.groupBoxDataSkips = QtGui.QGroupBox(self.tabGeneral)
        self.groupBoxDataSkips.setObjectName(_fromUtf8("groupBoxDataSkips"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBoxDataSkips)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.frame_5 = QtGui.QFrame(self.groupBoxDataSkips)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBoxSkip_3 = QtGui.QCheckBox(self.frame_5)
        self.checkBoxSkip_3.setObjectName(_fromUtf8("checkBoxSkip_3"))
        self.gridLayout.addWidget(self.checkBoxSkip_3, 3, 0, 1, 1)
        self.lineEditSkipStart_3 = QtGui.QLineEdit(self.frame_5)
        self.lineEditSkipStart_3.setEnabled(False)
        self.lineEditSkipStart_3.setObjectName(_fromUtf8("lineEditSkipStart_3"))
        self.gridLayout.addWidget(self.lineEditSkipStart_3, 3, 1, 1, 2)
        self.lineEditSkipEnd_1 = QtGui.QLineEdit(self.frame_5)
        self.lineEditSkipEnd_1.setEnabled(False)
        self.lineEditSkipEnd_1.setObjectName(_fromUtf8("lineEditSkipEnd_1"))
        self.gridLayout.addWidget(self.lineEditSkipEnd_1, 1, 3, 1, 1)
        self.lineEditSkipEnd_2 = QtGui.QLineEdit(self.frame_5)
        self.lineEditSkipEnd_2.setEnabled(False)
        self.lineEditSkipEnd_2.setObjectName(_fromUtf8("lineEditSkipEnd_2"))
        self.gridLayout.addWidget(self.lineEditSkipEnd_2, 2, 3, 1, 1)
        self.lineEditSkipEnd_3 = QtGui.QLineEdit(self.frame_5)
        self.lineEditSkipEnd_3.setEnabled(False)
        self.lineEditSkipEnd_3.setObjectName(_fromUtf8("lineEditSkipEnd_3"))
        self.gridLayout.addWidget(self.lineEditSkipEnd_3, 3, 3, 1, 1)
        self.checkBoxSkip_1 = QtGui.QCheckBox(self.frame_5)
        self.checkBoxSkip_1.setObjectName(_fromUtf8("checkBoxSkip_1"))
        self.gridLayout.addWidget(self.checkBoxSkip_1, 1, 0, 1, 1)
        self.checkBoxSkip_2 = QtGui.QCheckBox(self.frame_5)
        self.checkBoxSkip_2.setObjectName(_fromUtf8("checkBoxSkip_2"))
        self.gridLayout.addWidget(self.checkBoxSkip_2, 2, 0, 1, 1)
        self.lineEditSkipStart_1 = QtGui.QLineEdit(self.frame_5)
        self.lineEditSkipStart_1.setEnabled(False)
        self.lineEditSkipStart_1.setObjectName(_fromUtf8("lineEditSkipStart_1"))
        self.gridLayout.addWidget(self.lineEditSkipStart_1, 1, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.lineEditSkipStart_2 = QtGui.QLineEdit(self.frame_5)
        self.lineEditSkipStart_2.setEnabled(False)
        self.lineEditSkipStart_2.setObjectName(_fromUtf8("lineEditSkipStart_2"))
        self.gridLayout.addWidget(self.lineEditSkipStart_2, 2, 1, 1, 2)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.gridLayout_5.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame_5, 0, 0, 1, 1)
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.groupBoxDataSkips)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.groupBoxOrigin = QtGui.QGroupBox(self.tabGeneral)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxOrigin.sizePolicy().hasHeightForWidth())
        self.groupBoxOrigin.setSizePolicy(sizePolicy)
        self.groupBoxOrigin.setObjectName(_fromUtf8("groupBoxOrigin"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBoxOrigin)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.frame_6 = QtGui.QFrame(self.groupBoxOrigin)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.checkBoxFit = QtGui.QCheckBox(self.frame_6)
        self.checkBoxFit.setObjectName(_fromUtf8("checkBoxFit"))
        self.gridLayout_2.addWidget(self.checkBoxFit, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelX0 = QtGui.QLabel(self.frame_6)
        self.labelX0.setObjectName(_fromUtf8("labelX0"))
        self.horizontalLayout_3.addWidget(self.labelX0)
        self.lineEditX0 = QtGui.QLineEdit(self.frame_6)
        self.lineEditX0.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEditX0.setObjectName(_fromUtf8("lineEditX0"))
        self.horizontalLayout_3.addWidget(self.lineEditX0)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelZ0 = QtGui.QLabel(self.frame_6)
        self.labelZ0.setObjectName(_fromUtf8("labelZ0"))
        self.horizontalLayout.addWidget(self.labelZ0)
        self.lineEditZ0 = QtGui.QLineEdit(self.frame_6)
        self.lineEditZ0.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEditZ0.setObjectName(_fromUtf8("lineEditZ0"))
        self.horizontalLayout.addWidget(self.lineEditZ0)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.labelY0 = QtGui.QLabel(self.frame_6)
        self.labelY0.setObjectName(_fromUtf8("labelY0"))
        self.horizontalLayout_4.addWidget(self.labelY0)
        self.lineEditY0 = QtGui.QLineEdit(self.frame_6)
        self.lineEditY0.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEditY0.setObjectName(_fromUtf8("lineEditY0"))
        self.horizontalLayout_4.addWidget(self.lineEditY0)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_6, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.groupBoxOrigin)
        self.groupBoxOutputFormat = QtGui.QGroupBox(self.tabGeneral)
        self.groupBoxOutputFormat.setObjectName(_fromUtf8("groupBoxOutputFormat"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxOutputFormat)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.frame_4 = QtGui.QFrame(self.groupBoxOutputFormat)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.formLayout_6 = QtGui.QFormLayout(self.frame_4)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.radioButtonFloat = QtGui.QRadioButton(self.frame_4)
        self.radioButtonFloat.setChecked(True)
        self.radioButtonFloat.setObjectName(_fromUtf8("radioButtonFloat"))
        self.buttonGroup = QtGui.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButtonFloat)
        self.verticalLayout_5.addWidget(self.radioButtonFloat)
        self.radioButtonLong = QtGui.QRadioButton(self.frame_4)
        self.radioButtonLong.setObjectName(_fromUtf8("radioButtonLong"))
        self.buttonGroup.addButton(self.radioButtonLong)
        self.verticalLayout_5.addWidget(self.radioButtonLong)
        self.radioButtonShort = QtGui.QRadioButton(self.frame_4)
        self.radioButtonShort.setObjectName(_fromUtf8("radioButtonShort"))
        self.buttonGroup.addButton(self.radioButtonShort)
        self.verticalLayout_5.addWidget(self.radioButtonShort)
        self.formLayout_6.setLayout(0, QtGui.QFormLayout.LabelRole, self.verticalLayout_5)
        self.gridLayout_3.addWidget(self.frame_4, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.groupBoxOutputFormat)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.LabelRole, self.horizontalLayout_7)
        self.tabWidgetMaxFilterSettings.addTab(self.tabGeneral, _fromUtf8(""))
        self.tabTSSS = QtGui.QWidget()
        self.tabTSSS.setObjectName(_fromUtf8("tabTSSS"))
        self.widget = QtGui.QWidget(self.tabTSSS)
        self.widget.setGeometry(QtCore.QRect(0, 10, 353, 139))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.checkBoxtSSS = QtGui.QCheckBox(self.widget)
        self.checkBoxtSSS.setEnabled(True)
        self.checkBoxtSSS.setChecked(False)
        self.checkBoxtSSS.setObjectName(_fromUtf8("checkBoxtSSS"))
        self.verticalLayout_2.addWidget(self.checkBoxtSSS)
        self.frame = QtGui.QFrame(self.widget)
        self.frame.setEnabled(False)
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayoutWidget = QtGui.QWidget(self.frame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 10, 341, 81))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelDataBufferLength = QtGui.QLabel(self.formLayoutWidget)
        self.labelDataBufferLength.setObjectName(_fromUtf8("labelDataBufferLength"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelDataBufferLength)
        self.lineEditDataBufferLength = QtGui.QLineEdit(self.formLayoutWidget)
        self.lineEditDataBufferLength.setObjectName(_fromUtf8("lineEditDataBufferLength"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditDataBufferLength)
        self.labelSubspaceCorrelationLimit = QtGui.QLabel(self.formLayoutWidget)
        self.labelSubspaceCorrelationLimit.setObjectName(_fromUtf8("labelSubspaceCorrelationLimit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelSubspaceCorrelationLimit)
        self.lineEditSubspaceCorrelationLimit = QtGui.QLineEdit(self.formLayoutWidget)
        self.lineEditSubspaceCorrelationLimit.setObjectName(_fromUtf8("lineEditSubspaceCorrelationLimit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditSubspaceCorrelationLimit)
        self.verticalLayout_2.addWidget(self.frame)
        self.label = QtGui.QLabel(self.tabTSSS)
        self.label.setGeometry(QtCore.QRect(10, 180, 181, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.tabWidgetMaxFilterSettings.addTab(self.tabTSSS, _fromUtf8(""))
        self.tabMC = QtGui.QWidget()
        self.tabMC.setObjectName(_fromUtf8("tabMC"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tabMC)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.checkBoxMaxMove = QtGui.QCheckBox(self.tabMC)
        self.checkBoxMaxMove.setEnabled(True)
        self.checkBoxMaxMove.setChecked(False)
        self.checkBoxMaxMove.setObjectName(_fromUtf8("checkBoxMaxMove"))
        self.verticalLayout_4.addWidget(self.checkBoxMaxMove)
        self.frame_2 = QtGui.QFrame(self.tabMC)
        self.frame_2.setEnabled(False)
        self.frame_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.formLayoutWidget_3 = QtGui.QWidget(self.frame_2)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(9, 10, 331, 80))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.formLayout_3.setLayout(2, QtGui.QFormLayout.LabelRole, self.formLayout_4)
        self.labelHPI = QtGui.QLabel(self.formLayoutWidget_3)
        self.labelHPI.setObjectName(_fromUtf8("labelHPI"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelHPI)
        self.lineEditHPI = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.lineEditHPI.setObjectName(_fromUtf8("lineEditHPI"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditHPI)
        self.labelHPIStep = QtGui.QLabel(self.formLayoutWidget_3)
        self.labelHPIStep.setObjectName(_fromUtf8("labelHPIStep"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelHPIStep)
        self.lineEditHPIStep = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.lineEditHPIStep.setObjectName(_fromUtf8("lineEditHPIStep"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditHPIStep)
        self.groupBoxTransform = QtGui.QGroupBox(self.frame_2)
        self.groupBoxTransform.setGeometry(QtCore.QRect(70, 100, 221, 191))
        self.groupBoxTransform.setObjectName(_fromUtf8("groupBoxTransform"))
        self.frame_7 = QtGui.QFrame(self.groupBoxTransform)
        self.frame_7.setGeometry(QtCore.QRect(20, 40, 120, 80))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.widget1 = QtGui.QWidget(self.frame_2)
        self.widget1.setGeometry(QtCore.QRect(110, 310, 291, 67))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioButton = QtGui.QRadioButton(self.widget1)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.verticalLayout.addWidget(self.radioButton)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.lineEdit = QtGui.QLineEdit(self.widget1)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_9.addWidget(self.lineEdit)
        self.pushButton = QtGui.QPushButton(self.widget1)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_9.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.gridLayout_10.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.tabWidgetMaxFilterSettings.addTab(self.tabMC, _fromUtf8(""))
        self.gridLayout_11.addWidget(self.tabWidgetMaxFilterSettings, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidgetMaxFilterSettings.setCurrentIndex(2)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.checkBoxSkip_1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEditSkipStart_1.setEnabled)
        QtCore.QObject.connect(self.checkBoxSkip_1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEditSkipEnd_1.setEnabled)
        QtCore.QObject.connect(self.checkBoxSkip_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEditSkipStart_2.setEnabled)
        QtCore.QObject.connect(self.checkBoxSkip_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEditSkipEnd_2.setEnabled)
        QtCore.QObject.connect(self.checkBoxSkip_3, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEditSkipStart_3.setEnabled)
        QtCore.QObject.connect(self.checkBoxSkip_3, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEditSkipEnd_3.setEnabled)
        QtCore.QObject.connect(self.checkBoxMaxMove, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame_2.setEnabled)
        QtCore.QObject.connect(self.checkBoxtSSS, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame.setEnabled)
        QtCore.QObject.connect(self.checkBoxAutobad, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEditBad.setDisabled)
        QtCore.QObject.connect(self.checkBoxAutobad, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.labelBad.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.labelOrderIn.setText(_translate("Dialog", "Order in:", None))
        self.labelOrderOut.setText(_translate("Dialog", "Order out:", None))
        self.groupBoxBadChannel.setTitle(_translate("Dialog", "Bad channel selection", None))
        self.labelBadLimit.setText(_translate("Dialog", "Threshold for bads:", None))
        self.labelBad.setText(_translate("Dialog", "Bad channels (manual) :", None))
        self.checkBoxAutobad.setText(_translate("Dialog", "Autobad", None))
        self.groupBoxDataSkips.setTitle(_translate("Dialog", "Data skips", None))
        self.checkBoxSkip_3.setText(_translate("Dialog", "S3", None))
        self.checkBoxSkip_1.setText(_translate("Dialog", "S1", None))
        self.checkBoxSkip_2.setText(_translate("Dialog", "S2", None))
        self.label_5.setText(_translate("Dialog", "Start (sec)", None))
        self.label_6.setText(_translate("Dialog", "End (sec)", None))
        self.groupBoxOrigin.setTitle(_translate("Dialog", "Origin (in mm)", None))
        self.checkBoxFit.setText(_translate("Dialog", "Fit to isotrak points", None))
        self.labelX0.setText(_translate("Dialog", "x0", None))
        self.labelZ0.setText(_translate("Dialog", "z0", None))
        self.labelY0.setText(_translate("Dialog", "y0", None))
        self.groupBoxOutputFormat.setTitle(_translate("Dialog", "Output format", None))
        self.radioButtonFloat.setText(_translate("Dialog", "Float (32 bits)", None))
        self.radioButtonLong.setText(_translate("Dialog", "Long (32 bits)", None))
        self.radioButtonShort.setText(_translate("Dialog", "Short (16 bits)", None))
        self.tabWidgetMaxFilterSettings.setTabText(self.tabWidgetMaxFilterSettings.indexOf(self.tabGeneral), _translate("Dialog", "General and SSS", None))
        self.checkBoxtSSS.setText(_translate("Dialog", "tSSS filtering enabled", None))
        self.labelDataBufferLength.setText(_translate("Dialog", "Data buffer length (s):", None))
        self.lineEditDataBufferLength.setText(_translate("Dialog", "10", None))
        self.labelSubspaceCorrelationLimit.setText(_translate("Dialog", "Subspace correlation limit:", None))
        self.lineEditSubspaceCorrelationLimit.setText(_translate("Dialog", "0.98", None))
        self.label.setText(_translate("Dialog", "***waves vielä tänne?", None))
        self.tabWidgetMaxFilterSettings.setTabText(self.tabWidgetMaxFilterSettings.indexOf(self.tabTSSS), _translate("Dialog", "TSSS", None))
        self.checkBoxMaxMove.setText(_translate("Dialog", "Motion compensation (MaxMove) enabled", None))
        self.labelHPI.setText(_translate("Dialog", "HPI signal amp extraction window (ms):", None))
        self.lineEditHPI.setText(_translate("Dialog", "200", None))
        self.labelHPIStep.setText(_translate("Dialog", "Step to move HPI window (ms):", None))
        self.lineEditHPIStep.setText(_translate("Dialog", "10", None))
        self.groupBoxTransform.setTitle(_translate("Dialog", "Transform", None))
        self.radioButton.setText(_translate("Dialog", "Transform data to head position in a file:", None))
        self.pushButton.setText(_translate("Dialog", "Browse...", None))
        self.tabWidgetMaxFilterSettings.setTabText(self.tabWidgetMaxFilterSettings.indexOf(self.tabMC), _translate("Dialog", "Motion compensation", None))

