# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIehdotus7.ui'
#
# Created: Wed Mar 27 12:25:56 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(599, 858)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 599, 29))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(575, 115))
        self.dockWidget.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.LeftDockWidgetArea)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setGeometry(QtCore.QRect(0, 150, 391, 611))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabRaw = QtGui.QWidget()
        self.tabRaw.setMaximumSize(QtCore.QSize(360, 16777215))
        self.tabRaw.setAccessibleName(_fromUtf8(""))
        self.tabRaw.setObjectName(_fromUtf8("tabRaw"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.tabRaw)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 341, 481))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.metaBox = QtGui.QGroupBox(self.horizontalLayoutWidget)
        self.metaBox.setObjectName(_fromUtf8("metaBox"))
        self.layoutWidget_2 = QtGui.QWidget(self.metaBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(26, 35, 271, 54))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.labelDate = QtGui.QLabel(self.layoutWidget_2)
        self.labelDate.setObjectName(_fromUtf8("labelDate"))
        self.gridLayout_5.addWidget(self.labelDate, 0, 0, 1, 1)
        self.labelDateValue = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDateValue.sizePolicy().hasHeightForWidth())
        self.labelDateValue.setSizePolicy(sizePolicy)
        self.labelDateValue.setObjectName(_fromUtf8("labelDateValue"))
        self.gridLayout_5.addWidget(self.labelDateValue, 0, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelSubject = QtGui.QLabel(self.layoutWidget_2)
        self.labelSubject.setObjectName(_fromUtf8("labelSubject"))
        self.horizontalLayout.addWidget(self.labelSubject)
        self.labelSubjectValue = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSubjectValue.sizePolicy().hasHeightForWidth())
        self.labelSubjectValue.setSizePolicy(sizePolicy)
        self.labelSubjectValue.setObjectName(_fromUtf8("labelSubjectValue"))
        self.horizontalLayout.addWidget(self.labelSubjectValue)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.metaBox)
        self.filtersBox = QtGui.QGroupBox(self.horizontalLayoutWidget)
        self.filtersBox.setObjectName(_fromUtf8("filtersBox"))
        self.layoutWidget_6 = QtGui.QWidget(self.filtersBox)
        self.layoutWidget_6.setGeometry(QtCore.QRect(24, 32, 272, 65))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.labelLow = QtGui.QLabel(self.layoutWidget_6)
        self.labelLow.setLineWidth(1)
        self.labelLow.setScaledContents(True)
        self.labelLow.setObjectName(_fromUtf8("labelLow"))
        self.horizontalLayout_4.addWidget(self.labelLow)
        self.labelLowValue = QtGui.QLabel(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLowValue.sizePolicy().hasHeightForWidth())
        self.labelLowValue.setSizePolicy(sizePolicy)
        self.labelLowValue.setObjectName(_fromUtf8("labelLowValue"))
        self.horizontalLayout_4.addWidget(self.labelLowValue)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.labelHigh = QtGui.QLabel(self.layoutWidget_6)
        self.labelHigh.setObjectName(_fromUtf8("labelHigh"))
        self.horizontalLayout_5.addWidget(self.labelHigh)
        self.labelHighValue = QtGui.QLabel(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHighValue.sizePolicy().hasHeightForWidth())
        self.labelHighValue.setSizePolicy(sizePolicy)
        self.labelHighValue.setObjectName(_fromUtf8("labelHighValue"))
        self.horizontalLayout_5.addWidget(self.labelHighValue)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addWidget(self.filtersBox)
        self.channelsBox = QtGui.QGroupBox(self.horizontalLayoutWidget)
        self.channelsBox.setObjectName(_fromUtf8("channelsBox"))
        self.layoutWidget_7 = QtGui.QWidget(self.channelsBox)
        self.layoutWidget_7.setGeometry(QtCore.QRect(30, 30, 306, 112))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.labelEEG = QtGui.QLabel(self.layoutWidget_7)
        self.labelEEG.setObjectName(_fromUtf8("labelEEG"))
        self.horizontalLayout_6.addWidget(self.labelEEG)
        self.labelEEGValue = QtGui.QLabel(self.layoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelEEGValue.sizePolicy().hasHeightForWidth())
        self.labelEEGValue.setSizePolicy(sizePolicy)
        self.labelEEGValue.setObjectName(_fromUtf8("labelEEGValue"))
        self.horizontalLayout_6.addWidget(self.labelEEGValue)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.labelGradMEG = QtGui.QLabel(self.layoutWidget_7)
        self.labelGradMEG.setObjectName(_fromUtf8("labelGradMEG"))
        self.horizontalLayout_7.addWidget(self.labelGradMEG)
        self.labelGradMEGValue = QtGui.QLabel(self.layoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelGradMEGValue.sizePolicy().hasHeightForWidth())
        self.labelGradMEGValue.setSizePolicy(sizePolicy)
        self.labelGradMEGValue.setObjectName(_fromUtf8("labelGradMEGValue"))
        self.horizontalLayout_7.addWidget(self.labelGradMEGValue)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.labelMagMEG = QtGui.QLabel(self.layoutWidget_7)
        self.labelMagMEG.setObjectName(_fromUtf8("labelMagMEG"))
        self.horizontalLayout_8.addWidget(self.labelMagMEG)
        self.labelMagMEGValue = QtGui.QLabel(self.layoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMagMEGValue.sizePolicy().hasHeightForWidth())
        self.labelMagMEGValue.setSizePolicy(sizePolicy)
        self.labelMagMEGValue.setObjectName(_fromUtf8("labelMagMEGValue"))
        self.horizontalLayout_8.addWidget(self.labelMagMEGValue)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.labelSamples = QtGui.QLabel(self.layoutWidget_7)
        self.labelSamples.setObjectName(_fromUtf8("labelSamples"))
        self.horizontalLayout_9.addWidget(self.labelSamples)
        self.labelSamplesValue = QtGui.QLabel(self.layoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSamplesValue.sizePolicy().hasHeightForWidth())
        self.labelSamplesValue.setSizePolicy(sizePolicy)
        self.labelSamplesValue.setObjectName(_fromUtf8("labelSamplesValue"))
        self.horizontalLayout_9.addWidget(self.labelSamplesValue)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.verticalLayout_4.addWidget(self.channelsBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.labelRawData = QtGui.QLabel(self.tabRaw)
        self.labelRawData.setGeometry(QtCore.QRect(10, 30, 341, 21))
        self.labelRawData.setObjectName(_fromUtf8("labelRawData"))
        self.tabWidget.addTab(self.tabRaw, _fromUtf8(""))
        self.layoutWidget = QtGui.QWidget(self.dockWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 50, 146, 70))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButtonMNE_Browse_Raw = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonMNE_Browse_Raw.setObjectName(_fromUtf8("pushButtonMNE_Browse_Raw"))
        self.verticalLayout.addWidget(self.pushButtonMNE_Browse_Raw)
        self.pushButtonMaxFilter = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonMaxFilter.setObjectName(_fromUtf8("pushButtonMaxFilter"))
        self.verticalLayout.addWidget(self.pushButtonMaxFilter)
        self.layoutWidget1 = QtGui.QWidget(self.dockWidgetContents)
        self.layoutWidget1.setGeometry(QtCore.QRect(210, 30, 87, 107))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButtonEpoch = QtGui.QPushButton(self.layoutWidget1)
        self.pushButtonEpoch.setObjectName(_fromUtf8("pushButtonEpoch"))
        self.verticalLayout_2.addWidget(self.pushButtonEpoch)
        self.pushButtonAverage = QtGui.QPushButton(self.layoutWidget1)
        self.pushButtonAverage.setObjectName(_fromUtf8("pushButtonAverage"))
        self.verticalLayout_2.addWidget(self.pushButtonAverage)
        self.pushButtonVisualize = QtGui.QPushButton(self.layoutWidget1)
        self.pushButtonVisualize.setObjectName(_fromUtf8("pushButtonVisualize"))
        self.verticalLayout_2.addWidget(self.pushButtonVisualize)
        self.widget = QtGui.QWidget(self.dockWidgetContents)
        self.widget.setGeometry(QtCore.QRect(20, 0, 100, 36))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.pushButtonBack = QtGui.QPushButton(self.widget)
        self.pushButtonBack.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("image1.xpm")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonBack.setIcon(icon)
        self.pushButtonBack.setObjectName(_fromUtf8("pushButtonBack"))
        self.horizontalLayout_10.addWidget(self.pushButtonBack)
        self.pushButtonForward = QtGui.QPushButton(self.widget)
        self.pushButtonForward.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("image2.xpm")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonForward.setIcon(icon1)
        self.pushButtonForward.setObjectName(_fromUtf8("pushButtonForward"))
        self.horizontalLayout_10.addWidget(self.pushButtonForward)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actionLoad_file = QtGui.QAction(MainWindow)
        self.actionLoad_file.setObjectName(_fromUtf8("actionLoad_file"))
        self.actionSave_file = QtGui.QAction(MainWindow)
        self.actionSave_file.setObjectName(_fromUtf8("actionSave_file"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.menuFile.addAction(self.actionLoad_file)
        self.menuFile.addAction(self.actionSave_file)
        self.menuTools.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.metaBox.setTitle(_translate("MainWindow", "Background", None))
        self.labelDate.setText(_translate("MainWindow", "Date:", None))
        self.labelDateValue.setText(_translate("MainWindow", "DateValue", None))
        self.labelSubject.setText(_translate("MainWindow", "Subject:", None))
        self.labelSubjectValue.setText(_translate("MainWindow", "TextLabel", None))
        self.filtersBox.setTitle(_translate("MainWindow", "Filters", None))
        self.labelLow.setText(_translate("MainWindow", "Low-pass:", None))
        self.labelLowValue.setText(_translate("MainWindow", "Low-pass value", None))
        self.labelHigh.setText(_translate("MainWindow", "High-pass:", None))
        self.labelHighValue.setText(_translate("MainWindow", "High-pass value", None))
        self.channelsBox.setTitle(_translate("MainWindow", "Channels", None))
        self.labelEEG.setText(_translate("MainWindow", "EEG:", None))
        self.labelEEGValue.setText(_translate("MainWindow", "EEG value", None))
        self.labelGradMEG.setText(_translate("MainWindow", "Grad. MEG:", None))
        self.labelGradMEGValue.setText(_translate("MainWindow", "Grad. MEG value", None))
        self.labelMagMEG.setText(_translate("MainWindow", "Mag. MEG:", None))
        self.labelMagMEGValue.setText(_translate("MainWindow", "Mag. MEG value", None))
        self.labelSamples.setText(_translate("MainWindow", "Samples:", None))
        self.labelSamplesValue.setText(_translate("MainWindow", "SamplesValue", None))
        self.labelRawData.setText(_translate("MainWindow", "TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRaw), _translate("MainWindow", "Raw", None))
        self.pushButtonMNE_Browse_Raw.setText(_translate("MainWindow", "MNE_Browse_Raw", None))
        self.pushButtonMaxFilter.setText(_translate("MainWindow", "MaxFilter", None))
        self.pushButtonEpoch.setText(_translate("MainWindow", "Epoch", None))
        self.pushButtonAverage.setText(_translate("MainWindow", "Average", None))
        self.pushButtonVisualize.setText(_translate("MainWindow", "Visualize", None))
        self.actionLoad_file.setText(_translate("MainWindow", "Load file", None))
        self.actionSave_file.setText(_translate("MainWindow", "Save file", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))

