# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filterDialog.ui'
#
# Created: Mon Sep  2 12:21:53 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogFilter(object):
    def setupUi(self, DialogFilter):
        DialogFilter.setObjectName(_fromUtf8("DialogFilter"))
        DialogFilter.resize(1280, 961)
        self.gridLayout_2 = QtGui.QGridLayout(DialogFilter)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButtonPreview = QtGui.QPushButton(DialogFilter)
        self.pushButtonPreview.setObjectName(_fromUtf8("pushButtonPreview"))
        self.gridLayout_2.addWidget(self.pushButtonPreview, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(DialogFilter)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 1, 1, 1, 1)
        self.groupBoxPreview = QtGui.QGroupBox(DialogFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPreview.sizePolicy().hasHeightForWidth())
        self.groupBoxPreview.setSizePolicy(sizePolicy)
        self.groupBoxPreview.setObjectName(_fromUtf8("groupBoxPreview"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBoxPreview)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.widgetMpl = MplWidget(self.groupBoxPreview)
        self.widgetMpl.setObjectName(_fromUtf8("widgetMpl"))
        self.gridLayout_6.addWidget(self.widgetMpl, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxPreview, 0, 1, 1, 1)
        self.frameFilterSelection = QtGui.QFrame(DialogFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameFilterSelection.sizePolicy().hasHeightForWidth())
        self.frameFilterSelection.setSizePolicy(sizePolicy)
        self.frameFilterSelection.setMinimumSize(QtCore.QSize(350, 0))
        self.frameFilterSelection.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameFilterSelection.setFrameShadow(QtGui.QFrame.Raised)
        self.frameFilterSelection.setLineWidth(0)
        self.frameFilterSelection.setObjectName(_fromUtf8("frameFilterSelection"))
        self.formLayout_6 = QtGui.QFormLayout(self.frameFilterSelection)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.frameLowpass = QtGui.QFrame(self.frameFilterSelection)
        self.frameLowpass.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameLowpass.setFrameShadow(QtGui.QFrame.Raised)
        self.frameLowpass.setObjectName(_fromUtf8("frameLowpass"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frameLowpass)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.frame = QtGui.QFrame(self.frameLowpass)
        self.frame.setEnabled(False)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayout = QtGui.QFormLayout(self.frame)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelLowpassCutoff = QtGui.QLabel(self.frame)
        self.labelLowpassCutoff.setObjectName(_fromUtf8("labelLowpassCutoff"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelLowpassCutoff)
        self.doubleSpinBoxLowpassCutoff = QtGui.QDoubleSpinBox(self.frame)
        self.doubleSpinBoxLowpassCutoff.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxLowpassCutoff.setDecimals(3)
        self.doubleSpinBoxLowpassCutoff.setMaximum(10000.0)
        self.doubleSpinBoxLowpassCutoff.setSingleStep(10.0)
        self.doubleSpinBoxLowpassCutoff.setProperty("value", 50.0)
        self.doubleSpinBoxLowpassCutoff.setObjectName(_fromUtf8("doubleSpinBoxLowpassCutoff"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxLowpassCutoff)
        self.labelLowpassTransitionWidth = QtGui.QLabel(self.frame)
        self.labelLowpassTransitionWidth.setObjectName(_fromUtf8("labelLowpassTransitionWidth"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelLowpassTransitionWidth)
        self.doubleSpinBoxLowpassTransBandwidth = QtGui.QDoubleSpinBox(self.frame)
        self.doubleSpinBoxLowpassTransBandwidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxLowpassTransBandwidth.setDecimals(3)
        self.doubleSpinBoxLowpassTransBandwidth.setMaximum(10000.0)
        self.doubleSpinBoxLowpassTransBandwidth.setSingleStep(10.0)
        self.doubleSpinBoxLowpassTransBandwidth.setProperty("value", 10.0)
        self.doubleSpinBoxLowpassTransBandwidth.setObjectName(_fromUtf8("doubleSpinBoxLowpassTransBandwidth"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxLowpassTransBandwidth)
        self.labelLowpassFilterLength = QtGui.QLabel(self.frame)
        self.labelLowpassFilterLength.setObjectName(_fromUtf8("labelLowpassFilterLength"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelLowpassFilterLength)
        self.doubleSpinBoxLowpassFilterLength = QtGui.QDoubleSpinBox(self.frame)
        self.doubleSpinBoxLowpassFilterLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxLowpassFilterLength.setDecimals(3)
        self.doubleSpinBoxLowpassFilterLength.setProperty("value", 10.0)
        self.doubleSpinBoxLowpassFilterLength.setObjectName(_fromUtf8("doubleSpinBoxLowpassFilterLength"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxLowpassFilterLength)
        self.gridLayout_3.addWidget(self.frame, 1, 0, 1, 1)
        self.checkBoxLowpass = QtGui.QCheckBox(self.frameLowpass)
        self.checkBoxLowpass.setChecked(False)
        self.checkBoxLowpass.setObjectName(_fromUtf8("checkBoxLowpass"))
        self.gridLayout_3.addWidget(self.checkBoxLowpass, 0, 0, 1, 1)
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.SpanningRole, self.frameLowpass)
        self.line = QtGui.QFrame(self.frameFilterSelection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.SpanningRole, self.line)
        self.frameHighpass = QtGui.QFrame(self.frameFilterSelection)
        self.frameHighpass.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameHighpass.setFrameShadow(QtGui.QFrame.Raised)
        self.frameHighpass.setObjectName(_fromUtf8("frameHighpass"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frameHighpass)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.frame_2 = QtGui.QFrame(self.frameHighpass)
        self.frame_2.setEnabled(False)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.frame_2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelHighpassCutoff = QtGui.QLabel(self.frame_2)
        self.labelHighpassCutoff.setObjectName(_fromUtf8("labelHighpassCutoff"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelHighpassCutoff)
        self.doubleSpinBoxHighpassCutoff = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBoxHighpassCutoff.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxHighpassCutoff.setDecimals(3)
        self.doubleSpinBoxHighpassCutoff.setMaximum(10000.0)
        self.doubleSpinBoxHighpassCutoff.setSingleStep(10.0)
        self.doubleSpinBoxHighpassCutoff.setProperty("value", 600.0)
        self.doubleSpinBoxHighpassCutoff.setObjectName(_fromUtf8("doubleSpinBoxHighpassCutoff"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxHighpassCutoff)
        self.labelHighpassTransitionWidth = QtGui.QLabel(self.frame_2)
        self.labelHighpassTransitionWidth.setObjectName(_fromUtf8("labelHighpassTransitionWidth"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelHighpassTransitionWidth)
        self.doubleSpinBoxHighpassTransBandwidth = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBoxHighpassTransBandwidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxHighpassTransBandwidth.setDecimals(3)
        self.doubleSpinBoxHighpassTransBandwidth.setMaximum(10000.0)
        self.doubleSpinBoxHighpassTransBandwidth.setSingleStep(10.0)
        self.doubleSpinBoxHighpassTransBandwidth.setProperty("value", 10.0)
        self.doubleSpinBoxHighpassTransBandwidth.setObjectName(_fromUtf8("doubleSpinBoxHighpassTransBandwidth"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxHighpassTransBandwidth)
        self.labelHighpassFilterLength = QtGui.QLabel(self.frame_2)
        self.labelHighpassFilterLength.setObjectName(_fromUtf8("labelHighpassFilterLength"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelHighpassFilterLength)
        self.doubleSpinBoxHighpassFilterLength = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBoxHighpassFilterLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxHighpassFilterLength.setDecimals(3)
        self.doubleSpinBoxHighpassFilterLength.setProperty("value", 10.0)
        self.doubleSpinBoxHighpassFilterLength.setObjectName(_fromUtf8("doubleSpinBoxHighpassFilterLength"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxHighpassFilterLength)
        self.gridLayout_4.addWidget(self.frame_2, 1, 0, 1, 1)
        self.checkBoxHighpass = QtGui.QCheckBox(self.frameHighpass)
        self.checkBoxHighpass.setObjectName(_fromUtf8("checkBoxHighpass"))
        self.gridLayout_4.addWidget(self.checkBoxHighpass, 0, 0, 1, 1)
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.SpanningRole, self.frameHighpass)
        self.line_2 = QtGui.QFrame(self.frameFilterSelection)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.SpanningRole, self.line_2)
        self.frameBandPass = QtGui.QFrame(self.frameFilterSelection)
        self.frameBandPass.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameBandPass.setFrameShadow(QtGui.QFrame.Raised)
        self.frameBandPass.setObjectName(_fromUtf8("frameBandPass"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frameBandPass)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frame_3 = QtGui.QFrame(self.frameBandPass)
        self.frame_3.setEnabled(False)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.frame_3)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.labelBandStopFreq = QtGui.QLabel(self.frame_3)
        self.labelBandStopFreq.setObjectName(_fromUtf8("labelBandStopFreq"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelBandStopFreq)
        self.doubleSpinBoxBandstopFreq1 = QtGui.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBoxBandstopFreq1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandstopFreq1.setDecimals(3)
        self.doubleSpinBoxBandstopFreq1.setMaximum(10000.0)
        self.doubleSpinBoxBandstopFreq1.setSingleStep(10.0)
        self.doubleSpinBoxBandstopFreq1.setProperty("value", 50.0)
        self.doubleSpinBoxBandstopFreq1.setObjectName(_fromUtf8("doubleSpinBoxBandstopFreq1"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxBandstopFreq1)
        self.labelBandpassTransitionWidthLow = QtGui.QLabel(self.frame_3)
        self.labelBandpassTransitionWidthLow.setObjectName(_fromUtf8("labelBandpassTransitionWidthLow"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelBandpassTransitionWidthLow)
        self.doubleSpinBoxBandstopWidth1 = QtGui.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBoxBandstopWidth1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandstopWidth1.setDecimals(3)
        self.doubleSpinBoxBandstopWidth1.setMaximum(10000.0)
        self.doubleSpinBoxBandstopWidth1.setSingleStep(1.0)
        self.doubleSpinBoxBandstopWidth1.setProperty("value", 1.0)
        self.doubleSpinBoxBandstopWidth1.setObjectName(_fromUtf8("doubleSpinBoxBandstopWidth1"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxBandstopWidth1)
        self.labelBandstopFilterLength1 = QtGui.QLabel(self.frame_3)
        self.labelBandstopFilterLength1.setObjectName(_fromUtf8("labelBandstopFilterLength1"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelBandstopFilterLength1)
        self.doubleSpinBoxBandstopFilterLength1 = QtGui.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBoxBandstopFilterLength1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandstopFilterLength1.setDecimals(3)
        self.doubleSpinBoxBandstopFilterLength1.setProperty("value", 10.0)
        self.doubleSpinBoxBandstopFilterLength1.setObjectName(_fromUtf8("doubleSpinBoxBandstopFilterLength1"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxBandstopFilterLength1)
        self.gridLayout_5.addWidget(self.frame_3, 1, 0, 1, 1)
        self.checkBoxBandstop1 = QtGui.QCheckBox(self.frameBandPass)
        self.checkBoxBandstop1.setObjectName(_fromUtf8("checkBoxBandstop1"))
        self.gridLayout_5.addWidget(self.checkBoxBandstop1, 0, 0, 1, 1)
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.SpanningRole, self.frameBandPass)
        self.frameBandPass_3 = QtGui.QFrame(self.frameFilterSelection)
        self.frameBandPass_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameBandPass_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frameBandPass_3.setObjectName(_fromUtf8("frameBandPass_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frameBandPass_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.frame_5 = QtGui.QFrame(self.frameBandPass_3)
        self.frame_5.setEnabled(False)
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.formLayout_5 = QtGui.QFormLayout(self.frame_5)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.labelBandStopFreq_3 = QtGui.QLabel(self.frame_5)
        self.labelBandStopFreq_3.setObjectName(_fromUtf8("labelBandStopFreq_3"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelBandStopFreq_3)
        self.doubleSpinBoxBandstopFreq2 = QtGui.QDoubleSpinBox(self.frame_5)
        self.doubleSpinBoxBandstopFreq2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandstopFreq2.setDecimals(3)
        self.doubleSpinBoxBandstopFreq2.setMaximum(10000.0)
        self.doubleSpinBoxBandstopFreq2.setSingleStep(10.0)
        self.doubleSpinBoxBandstopFreq2.setProperty("value", 50.0)
        self.doubleSpinBoxBandstopFreq2.setObjectName(_fromUtf8("doubleSpinBoxBandstopFreq2"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxBandstopFreq2)
        self.labelBandpassTransitionWidthLow_3 = QtGui.QLabel(self.frame_5)
        self.labelBandpassTransitionWidthLow_3.setObjectName(_fromUtf8("labelBandpassTransitionWidthLow_3"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelBandpassTransitionWidthLow_3)
        self.doubleSpinBoxBandstopwidth2 = QtGui.QDoubleSpinBox(self.frame_5)
        self.doubleSpinBoxBandstopwidth2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandstopwidth2.setDecimals(3)
        self.doubleSpinBoxBandstopwidth2.setMaximum(10000.0)
        self.doubleSpinBoxBandstopwidth2.setSingleStep(1.0)
        self.doubleSpinBoxBandstopwidth2.setProperty("value", 1.0)
        self.doubleSpinBoxBandstopwidth2.setObjectName(_fromUtf8("doubleSpinBoxBandstopwidth2"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxBandstopwidth2)
        self.labelBandstopFilterLength2 = QtGui.QLabel(self.frame_5)
        self.labelBandstopFilterLength2.setObjectName(_fromUtf8("labelBandstopFilterLength2"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelBandstopFilterLength2)
        self.doubleSpinBoxBandstopFilterLength2 = QtGui.QDoubleSpinBox(self.frame_5)
        self.doubleSpinBoxBandstopFilterLength2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandstopFilterLength2.setDecimals(3)
        self.doubleSpinBoxBandstopFilterLength2.setProperty("value", 10.0)
        self.doubleSpinBoxBandstopFilterLength2.setObjectName(_fromUtf8("doubleSpinBoxBandstopFilterLength2"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxBandstopFilterLength2)
        self.gridLayout_8.addWidget(self.frame_5, 1, 0, 1, 1)
        self.checkBoxBandstop2 = QtGui.QCheckBox(self.frameBandPass_3)
        self.checkBoxBandstop2.setObjectName(_fromUtf8("checkBoxBandstop2"))
        self.gridLayout_8.addWidget(self.checkBoxBandstop2, 0, 0, 1, 1)
        self.formLayout_6.setWidget(5, QtGui.QFormLayout.SpanningRole, self.frameBandPass_3)
        self.frameBandPass_2 = QtGui.QFrame(self.frameFilterSelection)
        self.frameBandPass_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameBandPass_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frameBandPass_2.setObjectName(_fromUtf8("frameBandPass_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frameBandPass_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.frame_4 = QtGui.QFrame(self.frameBandPass_2)
        self.frame_4.setEnabled(False)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.frame_4)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.labelBandStopFreq_2 = QtGui.QLabel(self.frame_4)
        self.labelBandStopFreq_2.setObjectName(_fromUtf8("labelBandStopFreq_2"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelBandStopFreq_2)
        self.doubleSpinBoxBandstopFreq3 = QtGui.QDoubleSpinBox(self.frame_4)
        self.doubleSpinBoxBandstopFreq3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandstopFreq3.setDecimals(3)
        self.doubleSpinBoxBandstopFreq3.setMaximum(10000.0)
        self.doubleSpinBoxBandstopFreq3.setSingleStep(10.0)
        self.doubleSpinBoxBandstopFreq3.setProperty("value", 50.0)
        self.doubleSpinBoxBandstopFreq3.setObjectName(_fromUtf8("doubleSpinBoxBandstopFreq3"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxBandstopFreq3)
        self.labelBandpassTransitionWidthLow_2 = QtGui.QLabel(self.frame_4)
        self.labelBandpassTransitionWidthLow_2.setObjectName(_fromUtf8("labelBandpassTransitionWidthLow_2"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelBandpassTransitionWidthLow_2)
        self.doubleSpinBoxBandstopWidth3 = QtGui.QDoubleSpinBox(self.frame_4)
        self.doubleSpinBoxBandstopWidth3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandstopWidth3.setDecimals(3)
        self.doubleSpinBoxBandstopWidth3.setMaximum(10000.0)
        self.doubleSpinBoxBandstopWidth3.setSingleStep(1.0)
        self.doubleSpinBoxBandstopWidth3.setProperty("value", 1.0)
        self.doubleSpinBoxBandstopWidth3.setObjectName(_fromUtf8("doubleSpinBoxBandstopWidth3"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxBandstopWidth3)
        self.labelBandstopFilterLength3 = QtGui.QLabel(self.frame_4)
        self.labelBandstopFilterLength3.setObjectName(_fromUtf8("labelBandstopFilterLength3"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelBandstopFilterLength3)
        self.doubleSpinBoxBandstopFilterLength3 = QtGui.QDoubleSpinBox(self.frame_4)
        self.doubleSpinBoxBandstopFilterLength3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandstopFilterLength3.setDecimals(3)
        self.doubleSpinBoxBandstopFilterLength3.setProperty("value", 10.0)
        self.doubleSpinBoxBandstopFilterLength3.setObjectName(_fromUtf8("doubleSpinBoxBandstopFilterLength3"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxBandstopFilterLength3)
        self.gridLayout_7.addWidget(self.frame_4, 1, 0, 1, 1)
        self.checkBoxBandstop3 = QtGui.QCheckBox(self.frameBandPass_2)
        self.checkBoxBandstop3.setObjectName(_fromUtf8("checkBoxBandstop3"))
        self.gridLayout_7.addWidget(self.checkBoxBandstop3, 0, 0, 1, 1)
        self.formLayout_6.setWidget(6, QtGui.QFormLayout.FieldRole, self.frameBandPass_2)
        self.gridLayout_2.addWidget(self.frameFilterSelection, 0, 0, 1, 1)

        self.retranslateUi(DialogFilter)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DialogFilter.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DialogFilter.reject)
        QtCore.QObject.connect(self.checkBoxLowpass, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame.setEnabled)
        QtCore.QObject.connect(self.checkBoxHighpass, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame_2.setEnabled)
        QtCore.QObject.connect(self.checkBoxBandstop1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame_3.setEnabled)
        QtCore.QObject.connect(self.checkBoxBandstop2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame_5.setEnabled)
        QtCore.QObject.connect(self.checkBoxBandstop3, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame_4.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(DialogFilter)

    def retranslateUi(self, DialogFilter):
        DialogFilter.setWindowTitle(_translate("DialogFilter", "Filtering", None))
        self.pushButtonPreview.setText(_translate("DialogFilter", "Preview", None))
        self.groupBoxPreview.setTitle(_translate("DialogFilter", "Preview", None))
        self.labelLowpassCutoff.setText(_translate("DialogFilter", "Cutoff frequency:", None))
        self.doubleSpinBoxLowpassCutoff.setSuffix(_translate("DialogFilter", " Hz", None))
        self.labelLowpassTransitionWidth.setText(_translate("DialogFilter", "Transition band width:", None))
        self.doubleSpinBoxLowpassTransBandwidth.setSuffix(_translate("DialogFilter", " Hz", None))
        self.labelLowpassFilterLength.setText(_translate("DialogFilter", "Filter length:", None))
        self.doubleSpinBoxLowpassFilterLength.setSuffix(_translate("DialogFilter", " s", None))
        self.checkBoxLowpass.setText(_translate("DialogFilter", "Lowpass filter", None))
        self.labelHighpassCutoff.setText(_translate("DialogFilter", "Cutoff frequency:", None))
        self.doubleSpinBoxHighpassCutoff.setSuffix(_translate("DialogFilter", " Hz", None))
        self.labelHighpassTransitionWidth.setText(_translate("DialogFilter", "Transition band width:", None))
        self.doubleSpinBoxHighpassTransBandwidth.setSuffix(_translate("DialogFilter", " Hz", None))
        self.labelHighpassFilterLength.setText(_translate("DialogFilter", "Filter length:", None))
        self.doubleSpinBoxHighpassFilterLength.setSuffix(_translate("DialogFilter", " s", None))
        self.checkBoxHighpass.setText(_translate("DialogFilter", "Highpass filter", None))
        self.labelBandStopFreq.setText(_translate("DialogFilter", "Notch frequency:", None))
        self.doubleSpinBoxBandstopFreq1.setSuffix(_translate("DialogFilter", " Hz", None))
        self.labelBandpassTransitionWidthLow.setText(_translate("DialogFilter", "Band width:", None))
        self.doubleSpinBoxBandstopWidth1.setSuffix(_translate("DialogFilter", " Hz", None))
        self.labelBandstopFilterLength1.setText(_translate("DialogFilter", "Filter length:", None))
        self.doubleSpinBoxBandstopFilterLength1.setSuffix(_translate("DialogFilter", " s", None))
        self.checkBoxBandstop1.setText(_translate("DialogFilter", "BandStop filter (notch)", None))
        self.labelBandStopFreq_3.setText(_translate("DialogFilter", "Notch frequency:", None))
        self.doubleSpinBoxBandstopFreq2.setSuffix(_translate("DialogFilter", " Hz", None))
        self.labelBandpassTransitionWidthLow_3.setText(_translate("DialogFilter", "Band width:", None))
        self.doubleSpinBoxBandstopwidth2.setSuffix(_translate("DialogFilter", " Hz", None))
        self.labelBandstopFilterLength2.setText(_translate("DialogFilter", "Filter length:", None))
        self.doubleSpinBoxBandstopFilterLength2.setSuffix(_translate("DialogFilter", " s", None))
        self.checkBoxBandstop2.setText(_translate("DialogFilter", "BandStop filter (notch)", None))
        self.labelBandStopFreq_2.setText(_translate("DialogFilter", "Notch frequency:", None))
        self.doubleSpinBoxBandstopFreq3.setSuffix(_translate("DialogFilter", " Hz", None))
        self.labelBandpassTransitionWidthLow_2.setText(_translate("DialogFilter", "Band width:", None))
        self.doubleSpinBoxBandstopWidth3.setSuffix(_translate("DialogFilter", " Hz", None))
        self.labelBandstopFilterLength3.setText(_translate("DialogFilter", "Filter length:", None))
        self.doubleSpinBoxBandstopFilterLength3.setSuffix(_translate("DialogFilter", " s", None))
        self.checkBoxBandstop3.setText(_translate("DialogFilter", "BandStop filter (notch)", None))

from mplWidget import MplWidget
