# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt4Designer_ui_files/eegParametersDialogUi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(525, 613)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem)
        self.pushButtonCancel = QtGui.QPushButton(Dialog)
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))
        self.horizontalLayout_19.addWidget(self.pushButtonCancel)
        self.pushButtonCompute = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCompute.sizePolicy().hasHeightForWidth())
        self.pushButtonCompute.setSizePolicy(sizePolicy)
        self.pushButtonCompute.setObjectName(_fromUtf8("pushButtonCompute"))
        self.horizontalLayout_19.addWidget(self.pushButtonCompute)
        self.gridLayout.addLayout(self.horizontalLayout_19, 1, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(Dialog)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 507, 554))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_5 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.pushButtonShowEvents = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonShowEvents.sizePolicy().hasHeightForWidth())
        self.pushButtonShowEvents.setSizePolicy(sizePolicy)
        self.pushButtonShowEvents.setObjectName(_fromUtf8("pushButtonShowEvents"))
        self.gridLayout_6.addWidget(self.pushButtonShowEvents, 0, 0, 1, 1)
        self.pushButtonPlotEpochs = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPlotEpochs.sizePolicy().hasHeightForWidth())
        self.pushButtonPlotEpochs.setSizePolicy(sizePolicy)
        self.pushButtonPlotEpochs.setObjectName(_fromUtf8("pushButtonPlotEpochs"))
        self.gridLayout_6.addWidget(self.pushButtonPlotEpochs, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 2, 0, 1, 1)
        self.groupBoxProjection = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxProjection.setObjectName(_fromUtf8("groupBoxProjection"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBoxProjection)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelTmin = QtGui.QLabel(self.groupBoxProjection)
        self.labelTmin.setObjectName(_fromUtf8("labelTmin"))
        self.gridLayout_2.addWidget(self.labelTmin, 0, 0, 1, 1)
        self.spinBoxVectors = QtGui.QSpinBox(self.groupBoxProjection)
        self.spinBoxVectors.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBoxVectors.setMinimum(1)
        self.spinBoxVectors.setProperty("value", 2)
        self.spinBoxVectors.setObjectName(_fromUtf8("spinBoxVectors"))
        self.gridLayout_2.addWidget(self.spinBoxVectors, 2, 1, 1, 1)
        self.labelTmax = QtGui.QLabel(self.groupBoxProjection)
        self.labelTmax.setObjectName(_fromUtf8("labelTmax"))
        self.gridLayout_2.addWidget(self.labelTmax, 1, 0, 1, 1)
        self.doubleSpinBoxTmax = QtGui.QDoubleSpinBox(self.groupBoxProjection)
        self.doubleSpinBoxTmax.setDecimals(3)
        self.doubleSpinBoxTmax.setMaximum(9.9)
        self.doubleSpinBoxTmax.setSingleStep(0.1)
        self.doubleSpinBoxTmax.setProperty("value", 0.2)
        self.doubleSpinBoxTmax.setObjectName(_fromUtf8("doubleSpinBoxTmax"))
        self.gridLayout_2.addWidget(self.doubleSpinBoxTmax, 1, 1, 1, 1)
        self.doubleSpinBoxTmin = QtGui.QDoubleSpinBox(self.groupBoxProjection)
        self.doubleSpinBoxTmin.setDecimals(3)
        self.doubleSpinBoxTmin.setMinimum(-10.0)
        self.doubleSpinBoxTmin.setSingleStep(0.1)
        self.doubleSpinBoxTmin.setProperty("value", -0.2)
        self.doubleSpinBoxTmin.setObjectName(_fromUtf8("doubleSpinBoxTmin"))
        self.gridLayout_2.addWidget(self.doubleSpinBoxTmin, 0, 1, 1, 1)
        self.labelVectors = QtGui.QLabel(self.groupBoxProjection)
        self.labelVectors.setScaledContents(False)
        self.labelVectors.setObjectName(_fromUtf8("labelVectors"))
        self.gridLayout_2.addWidget(self.labelVectors, 2, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBoxProjection, 1, 0, 1, 1)
        self.groupBoxEvents = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxEvents.setObjectName(_fromUtf8("groupBoxEvents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxEvents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelChannel = QtGui.QLabel(self.groupBoxEvents)
        self.labelChannel.setObjectName(_fromUtf8("labelChannel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelChannel)
        self.comboBoxChannelSelect = QtGui.QComboBox(self.groupBoxEvents)
        self.comboBoxChannelSelect.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.comboBoxChannelSelect.setObjectName(_fromUtf8("comboBoxChannelSelect"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBoxChannelSelect)
        self.labelLowPass = QtGui.QLabel(self.groupBoxEvents)
        self.labelLowPass.setObjectName(_fromUtf8("labelLowPass"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelLowPass)
        self.doubleSpinBoxLowPass = QtGui.QDoubleSpinBox(self.groupBoxEvents)
        self.doubleSpinBoxLowPass.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleSpinBoxLowPass.setProperty("value", 1.0)
        self.doubleSpinBoxLowPass.setObjectName(_fromUtf8("doubleSpinBoxLowPass"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxLowPass)
        self.labelHighPass = QtGui.QLabel(self.groupBoxEvents)
        self.labelHighPass.setObjectName(_fromUtf8("labelHighPass"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelHighPass)
        self.doubleSpinBoxHighPass = QtGui.QDoubleSpinBox(self.groupBoxEvents)
        self.doubleSpinBoxHighPass.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleSpinBoxHighPass.setSingleStep(1.0)
        self.doubleSpinBoxHighPass.setProperty("value", 10.0)
        self.doubleSpinBoxHighPass.setObjectName(_fromUtf8("doubleSpinBoxHighPass"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxHighPass)
        self.labelFilterLength = QtGui.QLabel(self.groupBoxEvents)
        self.labelFilterLength.setObjectName(_fromUtf8("labelFilterLength"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.labelFilterLength)
        self.spinBoxFilterLength = QtGui.QSpinBox(self.groupBoxEvents)
        self.spinBoxFilterLength.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBoxFilterLength.setProperty("value", 10)
        self.spinBoxFilterLength.setObjectName(_fromUtf8("spinBoxFilterLength"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.spinBoxFilterLength)
        self.labelStart = QtGui.QLabel(self.groupBoxEvents)
        self.labelStart.setObjectName(_fromUtf8("labelStart"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.labelStart)
        self.doubleSpinBoxStart = QtGui.QDoubleSpinBox(self.groupBoxEvents)
        self.doubleSpinBoxStart.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleSpinBoxStart.setProperty("value", 5.0)
        self.doubleSpinBoxStart.setObjectName(_fromUtf8("doubleSpinBoxStart"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxStart)
        self.labelInvertPolarity = QtGui.QLabel(self.groupBoxEvents)
        self.labelInvertPolarity.setObjectName(_fromUtf8("labelInvertPolarity"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.labelInvertPolarity)
        self.checkBoxInvertPolarity = QtGui.QCheckBox(self.groupBoxEvents)
        self.checkBoxInvertPolarity.setText(_fromUtf8(""))
        self.checkBoxInvertPolarity.setObjectName(_fromUtf8("checkBoxInvertPolarity"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.checkBoxInvertPolarity)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tableWidgetEvents = QtGui.QTableWidget(self.groupBoxEvents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetEvents.sizePolicy().hasHeightForWidth())
        self.tableWidgetEvents.setSizePolicy(sizePolicy)
        self.tableWidgetEvents.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetEvents.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidgetEvents.setObjectName(_fromUtf8("tableWidgetEvents"))
        self.tableWidgetEvents.setColumnCount(0)
        self.tableWidgetEvents.setRowCount(0)
        self.gridLayout_3.addWidget(self.tableWidgetEvents, 0, 1, 2, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButtonAdd = QtGui.QPushButton(self.groupBoxEvents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAdd.sizePolicy().hasHeightForWidth())
        self.pushButtonAdd.setSizePolicy(sizePolicy)
        self.pushButtonAdd.setObjectName(_fromUtf8("pushButtonAdd"))
        self.verticalLayout.addWidget(self.pushButtonAdd)
        self.pushButtonRemove = QtGui.QPushButton(self.groupBoxEvents)
        self.pushButtonRemove.setObjectName(_fromUtf8("pushButtonRemove"))
        self.verticalLayout.addWidget(self.pushButtonRemove)
        self.gridLayout_3.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBoxEvents, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.pushButtonCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.reject)
        QtCore.QObject.connect(self.pushButtonCompute, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Compute ocular projections", None))
        self.pushButtonCancel.setText(_translate("Dialog", "Cancel", None))
        self.pushButtonCompute.setText(_translate("Dialog", "Compute", None))
        self.pushButtonShowEvents.setText(_translate("Dialog", "Show event locations", None))
        self.pushButtonPlotEpochs.setText(_translate("Dialog", "Plot average epochs", None))
        self.groupBoxProjection.setTitle(_translate("Dialog", "Projection parameters", None))
        self.labelTmin.setText(_translate("Dialog", "Start time:", None))
        self.spinBoxVectors.setToolTip(_translate("Dialog", "Number of projections calculated for events. Try increasing this if the artefact is not completely removed.", None))
        self.labelTmax.setText(_translate("Dialog", "End time:", None))
        self.doubleSpinBoxTmax.setSuffix(_translate("Dialog", " s", None))
        self.doubleSpinBoxTmin.setSuffix(_translate("Dialog", " s", None))
        self.labelVectors.setToolTip(_translate("Dialog", "Number of projections calculated for events. Try increasing this if the artefact is not completely removed.", None))
        self.labelVectors.setText(_translate("Dialog", "Number of projection vectors for EEG channels:", None))
        self.groupBoxEvents.setTitle(_translate("Dialog", "Find EOG events", None))
        self.labelChannel.setToolTip(_translate("Dialog", "Select specified channel for finding EOG artefacts. Preferably a channel with clear blinks.", None))
        self.labelChannel.setText(_translate("Dialog", "Event channel:", None))
        self.comboBoxChannelSelect.setToolTip(_translate("Dialog", "Select specified channel for finding EOG artefacts. Preferably a channel with clear blinks.", None))
        self.labelLowPass.setToolTip(_translate("Dialog", "Low pass filter frequency.", None))
        self.labelLowPass.setText(_translate("Dialog", "Low pass:", None))
        self.doubleSpinBoxLowPass.setToolTip(_translate("Dialog", "Low pass filter frequency.", None))
        self.doubleSpinBoxLowPass.setSuffix(_translate("Dialog", "Hz", None))
        self.labelHighPass.setToolTip(_translate("Dialog", "High pass filter frequency.", None))
        self.labelHighPass.setText(_translate("Dialog", "High pass:", None))
        self.doubleSpinBoxHighPass.setToolTip(_translate("Dialog", "High pass filter frequency.", None))
        self.doubleSpinBoxHighPass.setSuffix(_translate("Dialog", "Hz", None))
        self.labelFilterLength.setToolTip(_translate("Dialog", "Sets the number of taps used for filtering.", None))
        self.labelFilterLength.setText(_translate("Dialog", "Filter length:", None))
        self.spinBoxFilterLength.setToolTip(_translate("Dialog", "Sets the number of taps used for filtering.", None))
        self.spinBoxFilterLength.setSuffix(_translate("Dialog", "s", None))
        self.labelStart.setToolTip(_translate("Dialog", "Set starting time for blink detection.", None))
        self.labelStart.setText(_translate("Dialog", "Start time:", None))
        self.doubleSpinBoxStart.setToolTip(_translate("Dialog", "Set starting time for blink detection.", None))
        self.doubleSpinBoxStart.setSuffix(_translate("Dialog", "s", None))
        self.labelInvertPolarity.setText(_translate("Dialog", "Invert polarity:", None))
        self.tableWidgetEvents.setToolTip(_translate("Dialog", "Found events.", None))
        self.pushButtonAdd.setToolTip(_translate("Dialog", "Start blink detection. The previous event list will be deleted!", None))
        self.pushButtonAdd.setText(_translate("Dialog", "Add to list >>", None))
        self.pushButtonRemove.setText(_translate("Dialog", "Remove <<", None))

