# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../eegParametersDialogUi.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(543, 683)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem)
        self.pushButtonCancel = QtWidgets.QPushButton(Dialog)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_19.addWidget(self.pushButtonCancel)
        self.pushButtonCompute = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCompute.sizePolicy().hasHeightForWidth())
        self.pushButtonCompute.setSizePolicy(sizePolicy)
        self.pushButtonCompute.setObjectName("pushButtonCompute")
        self.horizontalLayout_19.addWidget(self.pushButtonCompute)
        self.gridLayout.addLayout(self.horizontalLayout_19, 1, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 525, 626))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBoxEvents = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxEvents.setObjectName("groupBoxEvents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxEvents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.labelChannel = QtWidgets.QLabel(self.groupBoxEvents)
        self.labelChannel.setObjectName("labelChannel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelChannel)
        self.comboBoxChannelSelect = QtWidgets.QComboBox(self.groupBoxEvents)
        self.comboBoxChannelSelect.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.comboBoxChannelSelect.setObjectName("comboBoxChannelSelect")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBoxChannelSelect)
        self.labelLowPass = QtWidgets.QLabel(self.groupBoxEvents)
        self.labelLowPass.setObjectName("labelLowPass")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelLowPass)
        self.doubleSpinBoxLowPass = QtWidgets.QDoubleSpinBox(self.groupBoxEvents)
        self.doubleSpinBoxLowPass.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleSpinBoxLowPass.setProperty("value", 1.0)
        self.doubleSpinBoxLowPass.setObjectName("doubleSpinBoxLowPass")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxLowPass)
        self.labelHighPass = QtWidgets.QLabel(self.groupBoxEvents)
        self.labelHighPass.setObjectName("labelHighPass")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelHighPass)
        self.doubleSpinBoxHighPass = QtWidgets.QDoubleSpinBox(self.groupBoxEvents)
        self.doubleSpinBoxHighPass.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleSpinBoxHighPass.setSingleStep(1.0)
        self.doubleSpinBoxHighPass.setProperty("value", 10.0)
        self.doubleSpinBoxHighPass.setObjectName("doubleSpinBoxHighPass")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxHighPass)
        self.labelFilterLength = QtWidgets.QLabel(self.groupBoxEvents)
        self.labelFilterLength.setObjectName("labelFilterLength")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelFilterLength)
        self.spinBoxFilterLength = QtWidgets.QSpinBox(self.groupBoxEvents)
        self.spinBoxFilterLength.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBoxFilterLength.setProperty("value", 10)
        self.spinBoxFilterLength.setObjectName("spinBoxFilterLength")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBoxFilterLength)
        self.labelStart = QtWidgets.QLabel(self.groupBoxEvents)
        self.labelStart.setObjectName("labelStart")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelStart)
        self.doubleSpinBoxStart = QtWidgets.QDoubleSpinBox(self.groupBoxEvents)
        self.doubleSpinBoxStart.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleSpinBoxStart.setProperty("value", 5.0)
        self.doubleSpinBoxStart.setObjectName("doubleSpinBoxStart")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxStart)
        self.labelInvertPolarity = QtWidgets.QLabel(self.groupBoxEvents)
        self.labelInvertPolarity.setObjectName("labelInvertPolarity")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelInvertPolarity)
        self.checkBoxInvertPolarity = QtWidgets.QCheckBox(self.groupBoxEvents)
        self.checkBoxInvertPolarity.setText("")
        self.checkBoxInvertPolarity.setObjectName("checkBoxInvertPolarity")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.checkBoxInvertPolarity)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tableWidgetEvents = QtWidgets.QTableWidget(self.groupBoxEvents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetEvents.sizePolicy().hasHeightForWidth())
        self.tableWidgetEvents.setSizePolicy(sizePolicy)
        self.tableWidgetEvents.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetEvents.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidgetEvents.setObjectName("tableWidgetEvents")
        self.tableWidgetEvents.setColumnCount(0)
        self.tableWidgetEvents.setRowCount(0)
        self.gridLayout_3.addWidget(self.tableWidgetEvents, 0, 1, 2, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonAdd = QtWidgets.QPushButton(self.groupBoxEvents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAdd.sizePolicy().hasHeightForWidth())
        self.pushButtonAdd.setSizePolicy(sizePolicy)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.verticalLayout.addWidget(self.pushButtonAdd)
        self.pushButtonRemove = QtWidgets.QPushButton(self.groupBoxEvents)
        self.pushButtonRemove.setObjectName("pushButtonRemove")
        self.verticalLayout.addWidget(self.pushButtonRemove)
        self.gridLayout_3.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBoxEvents, 0, 0, 1, 1)
        self.groupBoxVisualize = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxVisualize.setObjectName("groupBoxVisualize")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBoxVisualize)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButtonShowEvents = QtWidgets.QPushButton(self.groupBoxVisualize)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonShowEvents.sizePolicy().hasHeightForWidth())
        self.pushButtonShowEvents.setSizePolicy(sizePolicy)
        self.pushButtonShowEvents.setObjectName("pushButtonShowEvents")
        self.gridLayout_6.addWidget(self.pushButtonShowEvents, 0, 0, 1, 1)
        self.pushButtonPlotEpochs = QtWidgets.QPushButton(self.groupBoxVisualize)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPlotEpochs.sizePolicy().hasHeightForWidth())
        self.pushButtonPlotEpochs.setSizePolicy(sizePolicy)
        self.pushButtonPlotEpochs.setObjectName("pushButtonPlotEpochs")
        self.gridLayout_6.addWidget(self.pushButtonPlotEpochs, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 1, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBoxVisualize, 2, 0, 1, 1)
        self.groupBoxProjection = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxProjection.setObjectName("groupBoxProjection")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxProjection)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelTmin = QtWidgets.QLabel(self.groupBoxProjection)
        self.labelTmin.setObjectName("labelTmin")
        self.gridLayout_2.addWidget(self.labelTmin, 0, 0, 1, 1)
        self.spinBoxVectors = QtWidgets.QSpinBox(self.groupBoxProjection)
        self.spinBoxVectors.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBoxVectors.setMinimum(1)
        self.spinBoxVectors.setProperty("value", 2)
        self.spinBoxVectors.setObjectName("spinBoxVectors")
        self.gridLayout_2.addWidget(self.spinBoxVectors, 2, 1, 1, 1)
        self.labelTmax = QtWidgets.QLabel(self.groupBoxProjection)
        self.labelTmax.setObjectName("labelTmax")
        self.gridLayout_2.addWidget(self.labelTmax, 1, 0, 1, 1)
        self.doubleSpinBoxTmax = QtWidgets.QDoubleSpinBox(self.groupBoxProjection)
        self.doubleSpinBoxTmax.setDecimals(3)
        self.doubleSpinBoxTmax.setMaximum(9.9)
        self.doubleSpinBoxTmax.setSingleStep(0.1)
        self.doubleSpinBoxTmax.setProperty("value", 0.2)
        self.doubleSpinBoxTmax.setObjectName("doubleSpinBoxTmax")
        self.gridLayout_2.addWidget(self.doubleSpinBoxTmax, 1, 1, 1, 1)
        self.doubleSpinBoxTmin = QtWidgets.QDoubleSpinBox(self.groupBoxProjection)
        self.doubleSpinBoxTmin.setDecimals(3)
        self.doubleSpinBoxTmin.setMinimum(-10.0)
        self.doubleSpinBoxTmin.setSingleStep(0.1)
        self.doubleSpinBoxTmin.setProperty("value", -0.2)
        self.doubleSpinBoxTmin.setObjectName("doubleSpinBoxTmin")
        self.gridLayout_2.addWidget(self.doubleSpinBoxTmin, 0, 1, 1, 1)
        self.labelVectors = QtWidgets.QLabel(self.groupBoxProjection)
        self.labelVectors.setScaledContents(False)
        self.labelVectors.setObjectName("labelVectors")
        self.gridLayout_2.addWidget(self.labelVectors, 2, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBoxProjection, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.pushButtonCancel.clicked.connect(Dialog.reject)
        self.pushButtonCompute.clicked.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Compute ocular projections"))
        self.pushButtonCancel.setText(_translate("Dialog", "Cancel"))
        self.pushButtonCompute.setText(_translate("Dialog", "Compute"))
        self.groupBoxEvents.setTitle(_translate("Dialog", "Find EOG events"))
        self.labelChannel.setToolTip(_translate("Dialog", "Select specified channel for finding EOG artefacts. Preferably a channel with clear blinks."))
        self.labelChannel.setText(_translate("Dialog", "Event channel:"))
        self.comboBoxChannelSelect.setToolTip(_translate("Dialog", "Select specified channel for finding EOG artefacts. Preferably a channel with clear blinks."))
        self.labelLowPass.setToolTip(_translate("Dialog", "Low pass filter frequency."))
        self.labelLowPass.setText(_translate("Dialog", "Low pass:"))
        self.doubleSpinBoxLowPass.setToolTip(_translate("Dialog", "Low pass filter frequency."))
        self.doubleSpinBoxLowPass.setSuffix(_translate("Dialog", "Hz"))
        self.labelHighPass.setToolTip(_translate("Dialog", "High pass filter frequency."))
        self.labelHighPass.setText(_translate("Dialog", "High pass:"))
        self.doubleSpinBoxHighPass.setToolTip(_translate("Dialog", "High pass filter frequency."))
        self.doubleSpinBoxHighPass.setSuffix(_translate("Dialog", "Hz"))
        self.labelFilterLength.setToolTip(_translate("Dialog", "Sets the number of taps used for filtering."))
        self.labelFilterLength.setText(_translate("Dialog", "Filter length:"))
        self.spinBoxFilterLength.setToolTip(_translate("Dialog", "Sets the number of taps used for filtering."))
        self.spinBoxFilterLength.setSuffix(_translate("Dialog", "s"))
        self.labelStart.setToolTip(_translate("Dialog", "Set starting time for blink detection."))
        self.labelStart.setText(_translate("Dialog", "Start time:"))
        self.doubleSpinBoxStart.setToolTip(_translate("Dialog", "Set starting time for blink detection."))
        self.doubleSpinBoxStart.setSuffix(_translate("Dialog", "s"))
        self.labelInvertPolarity.setText(_translate("Dialog", "Invert polarity:"))
        self.tableWidgetEvents.setToolTip(_translate("Dialog", "Found events."))
        self.pushButtonAdd.setToolTip(_translate("Dialog", "Start blink detection. The previous event list will be deleted!"))
        self.pushButtonAdd.setText(_translate("Dialog", "Add to list >>"))
        self.pushButtonRemove.setText(_translate("Dialog", "Remove <<"))
        self.groupBoxVisualize.setTitle(_translate("Dialog", "Visualize"))
        self.pushButtonShowEvents.setText(_translate("Dialog", "Show event locations"))
        self.pushButtonPlotEpochs.setText(_translate("Dialog", "Plot average epochs"))
        self.groupBoxProjection.setTitle(_translate("Dialog", "Projection parameters"))
        self.labelTmin.setText(_translate("Dialog", "Start time:"))
        self.spinBoxVectors.setToolTip(_translate("Dialog", "Number of projections calculated for events. Try increasing this if the artefact is not completely removed."))
        self.labelTmax.setText(_translate("Dialog", "End time:"))
        self.doubleSpinBoxTmax.setSuffix(_translate("Dialog", " s"))
        self.doubleSpinBoxTmin.setSuffix(_translate("Dialog", " s"))
        self.labelVectors.setToolTip(_translate("Dialog", "Number of projections calculated for events. Try increasing this if the artefact is not completely removed."))
        self.labelVectors.setText(_translate("Dialog", "Number of projection vectors for EEG channels:"))

