# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../eogParametersDialogUi.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(528, 879)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButtonPlotEvents = QtWidgets.QPushButton(Dialog)
        self.pushButtonPlotEvents.setObjectName("pushButtonPlotEvents")
        self.horizontalLayout_13.addWidget(self.pushButtonPlotEvents)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.pushButtonCancel = QtWidgets.QPushButton(Dialog)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_13.addWidget(self.pushButtonCancel)
        self.pushButtonComputeBatch = QtWidgets.QPushButton(Dialog)
        self.pushButtonComputeBatch.setObjectName("pushButtonComputeBatch")
        self.horizontalLayout_13.addWidget(self.pushButtonComputeBatch)
        self.pushButtonCompute = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCompute.sizePolicy().hasHeightForWidth())
        self.pushButtonCompute.setSizePolicy(sizePolicy)
        self.pushButtonCompute.setObjectName("pushButtonCompute")
        self.horizontalLayout_13.addWidget(self.pushButtonCompute)
        self.gridLayout.addLayout(self.horizontalLayout_13, 1, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 510, 822))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(500, 800))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tabWidgetEOGSettings = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidgetEOGSettings.setGeometry(QtCore.QRect(0, 0, 501, 421))
        self.tabWidgetEOGSettings.setObjectName("tabWidgetEOGSettings")
        self.tabEOG1 = QtWidgets.QWidget()
        self.tabEOG1.setObjectName("tabEOG1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabEOG1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBoxEvent = QtWidgets.QGroupBox(self.tabEOG1)
        self.groupBoxEvent.setObjectName("groupBoxEvent")
        self.frame = QtWidgets.QFrame(self.groupBoxEvent)
        self.frame.setGeometry(QtCore.QRect(10, 30, 361, 61))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 10, 341, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelTmin = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.labelTmin.setObjectName("labelTmin")
        self.horizontalLayout.addWidget(self.labelTmin)
        self.doubleSpinBoxTmin = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_8)
        self.doubleSpinBoxTmin.setDecimals(3)
        self.doubleSpinBoxTmin.setMinimum(-99.99)
        self.doubleSpinBoxTmin.setSingleStep(0.05)
        self.doubleSpinBoxTmin.setProperty("value", -0.2)
        self.doubleSpinBoxTmin.setObjectName("doubleSpinBoxTmin")
        self.horizontalLayout.addWidget(self.doubleSpinBoxTmin)
        self.horizontalLayout_8.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelTmax = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.labelTmax.setObjectName("labelTmax")
        self.horizontalLayout_2.addWidget(self.labelTmax)
        self.doubleSpinBoxTmax = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_8)
        self.doubleSpinBoxTmax.setDecimals(3)
        self.doubleSpinBoxTmax.setMinimum(-99.99)
        self.doubleSpinBoxTmax.setSingleStep(0.05)
        self.doubleSpinBoxTmax.setProperty("value", 0.2)
        self.doubleSpinBoxTmax.setObjectName("doubleSpinBoxTmax")
        self.horizontalLayout_2.addWidget(self.doubleSpinBoxTmax)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addWidget(self.groupBoxEvent, 0, 0, 1, 1)
        self.groupBoxFilteringEOG = QtWidgets.QGroupBox(self.tabEOG1)
        self.groupBoxFilteringEOG.setObjectName("groupBoxFilteringEOG")
        self.frame_6 = QtWidgets.QFrame(self.groupBoxFilteringEOG)
        self.frame_6.setGeometry(QtCore.QRect(10, 30, 391, 61))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayoutWidget_20 = QtWidgets.QWidget(self.frame_6)
        self.horizontalLayoutWidget_20.setGeometry(QtCore.QRect(10, 10, 371, 41))
        self.horizontalLayoutWidget_20.setObjectName("horizontalLayoutWidget_20")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_20)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.labelLowPass = QtWidgets.QLabel(self.horizontalLayoutWidget_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLowPass.sizePolicy().hasHeightForWidth())
        self.labelLowPass.setSizePolicy(sizePolicy)
        self.labelLowPass.setObjectName("labelLowPass")
        self.horizontalLayout_23.addWidget(self.labelLowPass)
        self.spinBoxLowPass = QtWidgets.QSpinBox(self.horizontalLayoutWidget_20)
        self.spinBoxLowPass.setProperty("value", 1)
        self.spinBoxLowPass.setObjectName("spinBoxLowPass")
        self.horizontalLayout_23.addWidget(self.spinBoxLowPass)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.labelHighPass = QtWidgets.QLabel(self.horizontalLayoutWidget_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHighPass.sizePolicy().hasHeightForWidth())
        self.labelHighPass.setSizePolicy(sizePolicy)
        self.labelHighPass.setObjectName("labelHighPass")
        self.horizontalLayout_24.addWidget(self.labelHighPass)
        self.spinBoxHighPass = QtWidgets.QSpinBox(self.horizontalLayoutWidget_20)
        self.spinBoxHighPass.setMaximum(1000)
        self.spinBoxHighPass.setProperty("value", 10)
        self.spinBoxHighPass.setObjectName("spinBoxHighPass")
        self.horizontalLayout_24.addWidget(self.spinBoxHighPass)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_24)
        self.gridLayout_3.addWidget(self.groupBoxFilteringEOG, 1, 0, 1, 1)
        self.groupBoxSSP = QtWidgets.QGroupBox(self.tabEOG1)
        self.groupBoxSSP.setObjectName("groupBoxSSP")
        self.frame_2 = QtWidgets.QFrame(self.groupBoxSSP)
        self.frame_2.setGeometry(QtCore.QRect(10, 30, 341, 61))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.frame_2)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(10, 10, 325, 41))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelGrad = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.labelGrad.setObjectName("labelGrad")
        self.horizontalLayout_3.addWidget(self.labelGrad)
        self.spinBoxGrad = QtWidgets.QSpinBox(self.horizontalLayoutWidget_9)
        self.spinBoxGrad.setProperty("value", 2)
        self.spinBoxGrad.setObjectName("spinBoxGrad")
        self.horizontalLayout_3.addWidget(self.spinBoxGrad)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelMag = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.labelMag.setObjectName("labelMag")
        self.horizontalLayout_4.addWidget(self.labelMag)
        self.spinBoxMag = QtWidgets.QSpinBox(self.horizontalLayoutWidget_9)
        self.spinBoxMag.setProperty("value", 2)
        self.spinBoxMag.setObjectName("spinBoxMag")
        self.horizontalLayout_4.addWidget(self.spinBoxMag)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelEeg = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.labelEeg.setObjectName("labelEeg")
        self.horizontalLayout_5.addWidget(self.labelEeg)
        self.spinBoxEeg = QtWidgets.QSpinBox(self.horizontalLayoutWidget_9)
        self.spinBoxEeg.setProperty("value", 2)
        self.spinBoxEeg.setObjectName("spinBoxEeg")
        self.horizontalLayout_5.addWidget(self.spinBoxEeg)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_5)
        self.gridLayout_3.addWidget(self.groupBoxSSP, 2, 0, 1, 1)
        self.tabWidgetEOGSettings.addTab(self.tabEOG1, "")
        self.tabEOG2 = QtWidgets.QWidget()
        self.tabEOG2.setObjectName("tabEOG2")
        self.groupBox = QtWidgets.QGroupBox(self.tabEOG2)
        self.groupBox.setGeometry(QtCore.QRect(10, 150, 491, 131))
        self.groupBox.setObjectName("groupBox")
        self.frameEpochRejection = QtWidgets.QFrame(self.groupBox)
        self.frameEpochRejection.setEnabled(True)
        self.frameEpochRejection.setGeometry(QtCore.QRect(10, 30, 461, 91))
        self.frameEpochRejection.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameEpochRejection.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameEpochRejection.setObjectName("frameEpochRejection")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.frameEpochRejection)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 441, 80))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.labelGradReject = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.labelGradReject.setObjectName("labelGradReject")
        self.horizontalLayout_14.addWidget(self.labelGradReject)
        self.doubleSpinBoxGradReject = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_4)
        self.doubleSpinBoxGradReject.setPrefix("")
        self.doubleSpinBoxGradReject.setMaximum(1000000000.0)
        self.doubleSpinBoxGradReject.setProperty("value", 3000.0)
        self.doubleSpinBoxGradReject.setObjectName("doubleSpinBoxGradReject")
        self.horizontalLayout_14.addWidget(self.doubleSpinBoxGradReject)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.labelEegReject = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.labelEegReject.setObjectName("labelEegReject")
        self.horizontalLayout_11.addWidget(self.labelEegReject)
        self.doubleSpinBoxEEGReject = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_4)
        self.doubleSpinBoxEEGReject.setMaximum(1000000000.0)
        self.doubleSpinBoxEEGReject.setProperty("value", 100.0)
        self.doubleSpinBoxEEGReject.setObjectName("doubleSpinBoxEEGReject")
        self.horizontalLayout_11.addWidget(self.doubleSpinBoxEEGReject)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.labelMagReject = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.labelMagReject.setObjectName("labelMagReject")
        self.horizontalLayout_10.addWidget(self.labelMagReject)
        self.doubleSpinBoxMagReject = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_4)
        self.doubleSpinBoxMagReject.setMaximum(1000000000.0)
        self.doubleSpinBoxMagReject.setProperty("value", 4000.0)
        self.doubleSpinBoxMagReject.setObjectName("doubleSpinBoxMagReject")
        self.horizontalLayout_10.addWidget(self.doubleSpinBoxMagReject)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.labelEogReject = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.labelEogReject.setObjectName("labelEogReject")
        self.horizontalLayout_15.addWidget(self.labelEogReject)
        self.doubleSpinBoxEOGReject = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_4)
        self.doubleSpinBoxEOGReject.setMaximum(1000000000.0)
        self.doubleSpinBoxEOGReject.setProperty("value", 1000000000.0)
        self.doubleSpinBoxEOGReject.setObjectName("doubleSpinBoxEOGReject")
        self.horizontalLayout_15.addWidget(self.doubleSpinBoxEOGReject)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_12.addLayout(self.verticalLayout_3)
        self.gridLayoutWidget = QtWidgets.QWidget(self.tabEOG2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 138))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spinBoxStart = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBoxStart.setObjectName("spinBoxStart")
        self.gridLayout_2.addWidget(self.spinBoxStart, 0, 1, 1, 1)
        self.checkBoxSSPCompute = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxSSPCompute.setObjectName("checkBoxSSPCompute")
        self.gridLayout_2.addWidget(self.checkBoxSSPCompute, 3, 0, 1, 1)
        self.labelTaps = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelTaps.setObjectName("labelTaps")
        self.gridLayout_2.addWidget(self.labelTaps, 1, 0, 1, 1)
        self.labelStart2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelStart2.setObjectName("labelStart2")
        self.gridLayout_2.addWidget(self.labelStart2, 0, 2, 1, 1)
        self.spinBoxTaps = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBoxTaps.setMaximum(10000)
        self.spinBoxTaps.setProperty("value", 2048)
        self.spinBoxTaps.setObjectName("spinBoxTaps")
        self.gridLayout_2.addWidget(self.spinBoxTaps, 1, 1, 1, 1)
        self.labelStart1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelStart1.setObjectName("labelStart1")
        self.gridLayout_2.addWidget(self.labelStart1, 0, 0, 1, 1)
        self.checkBoxSSPProj = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxSSPProj.setEnabled(True)
        self.checkBoxSSPProj.setChecked(True)
        self.checkBoxSSPProj.setObjectName("checkBoxSSPProj")
        self.gridLayout_2.addWidget(self.checkBoxSSPProj, 2, 0, 1, 1)
        self.groupBoxFilter = QtWidgets.QGroupBox(self.tabEOG2)
        self.groupBoxFilter.setGeometry(QtCore.QRect(10, 280, 351, 101))
        self.groupBoxFilter.setObjectName("groupBoxFilter")
        self.frame_7 = QtWidgets.QFrame(self.groupBoxFilter)
        self.frame_7.setGeometry(QtCore.QRect(10, 30, 271, 61))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayoutWidget_19 = QtWidgets.QWidget(self.frame_7)
        self.horizontalLayoutWidget_19.setGeometry(QtCore.QRect(10, 10, 251, 41))
        self.horizontalLayoutWidget_19.setObjectName("horizontalLayoutWidget_19")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_19)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.labelLow = QtWidgets.QLabel(self.horizontalLayoutWidget_19)
        self.labelLow.setObjectName("labelLow")
        self.horizontalLayout_26.addWidget(self.labelLow)
        self.spinBoxLow = QtWidgets.QSpinBox(self.horizontalLayoutWidget_19)
        self.spinBoxLow.setProperty("value", 1)
        self.spinBoxLow.setObjectName("spinBoxLow")
        self.horizontalLayout_26.addWidget(self.spinBoxLow)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.labelHigh = QtWidgets.QLabel(self.horizontalLayoutWidget_19)
        self.labelHigh.setObjectName("labelHigh")
        self.horizontalLayout_27.addWidget(self.labelHigh)
        self.spinBoxHigh = QtWidgets.QSpinBox(self.horizontalLayoutWidget_19)
        self.spinBoxHigh.setMaximum(1000)
        self.spinBoxHigh.setProperty("value", 35)
        self.spinBoxHigh.setObjectName("spinBoxHigh")
        self.horizontalLayout_27.addWidget(self.spinBoxHigh)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_27)
        self.tabWidgetEOGSettings.addTab(self.tabEOG2, "")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(0, 430, 301, 371))
        self.widget.setObjectName("widget")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidgetEOGSettings.setCurrentIndex(0)
        self.pushButtonCompute.clicked.connect(Dialog.accept)
        self.pushButtonComputeBatch.clicked.connect(Dialog.acceptBatch)
        self.pushButtonCancel.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.scrollArea, self.doubleSpinBoxTmin)
        Dialog.setTabOrder(self.doubleSpinBoxTmin, self.doubleSpinBoxTmax)
        Dialog.setTabOrder(self.doubleSpinBoxTmax, self.spinBoxLowPass)
        Dialog.setTabOrder(self.spinBoxLowPass, self.spinBoxHighPass)
        Dialog.setTabOrder(self.spinBoxHighPass, self.spinBoxGrad)
        Dialog.setTabOrder(self.spinBoxGrad, self.spinBoxMag)
        Dialog.setTabOrder(self.spinBoxMag, self.spinBoxEeg)
        Dialog.setTabOrder(self.spinBoxEeg, self.spinBoxLow)
        Dialog.setTabOrder(self.spinBoxLow, self.spinBoxHigh)
        Dialog.setTabOrder(self.spinBoxHigh, self.pushButtonCancel)
        Dialog.setTabOrder(self.pushButtonCancel, self.pushButtonCompute)
        Dialog.setTabOrder(self.pushButtonCompute, self.tabWidgetEOGSettings)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Meggie - Compute EOG projections"))
        self.pushButtonPlotEvents.setText(_translate("Dialog", "Plot events"))
        self.pushButtonCancel.setText(_translate("Dialog", "Cancel"))
        self.pushButtonComputeBatch.setText(_translate("Dialog", "Compute Batch"))
        self.pushButtonCompute.setText(_translate("Dialog", "Compute"))
        self.groupBoxEvent.setTitle(_translate("Dialog", "Events"))
        self.labelTmin.setText(_translate("Dialog", "Start time:"))
        self.doubleSpinBoxTmin.setSuffix(_translate("Dialog", " s"))
        self.labelTmax.setText(_translate("Dialog", "End time:"))
        self.doubleSpinBoxTmax.setSuffix(_translate("Dialog", " s"))
        self.groupBoxFilteringEOG.setTitle(_translate("Dialog", "Filter cut-off frequencies for EOG channel"))
        self.labelLowPass.setText(_translate("Dialog", "Low:"))
        self.spinBoxLowPass.setSuffix(_translate("Dialog", " Hz"))
        self.labelHighPass.setText(_translate("Dialog", "High:"))
        self.spinBoxHighPass.setSuffix(_translate("Dialog", " Hz"))
        self.groupBoxSSP.setTitle(_translate("Dialog", "Number of SSP vectors"))
        self.labelGrad.setText(_translate("Dialog", "Grad:"))
        self.labelMag.setText(_translate("Dialog", "Mag:"))
        self.labelEeg.setText(_translate("Dialog", "EEG:"))
        self.tabWidgetEOGSettings.setTabText(self.tabWidgetEOGSettings.indexOf(self.tabEOG1), _translate("Dialog", "EOG settings"))
        self.groupBox.setTitle(_translate("Dialog", "Epoch rejection"))
        self.labelGradReject.setText(_translate("Dialog", "Grad:"))
        self.doubleSpinBoxGradReject.setSuffix(_translate("Dialog", " fT/cm"))
        self.labelEegReject.setText(_translate("Dialog", "EEG:"))
        self.doubleSpinBoxEEGReject.setSuffix(_translate("Dialog", " uV"))
        self.labelMagReject.setText(_translate("Dialog", "Mag:"))
        self.doubleSpinBoxMagReject.setSuffix(_translate("Dialog", " fT"))
        self.labelEogReject.setText(_translate("Dialog", "EOG:"))
        self.doubleSpinBoxEOGReject.setSuffix(_translate("Dialog", " uV"))
        self.checkBoxSSPCompute.setText(_translate("Dialog", "Compute SSP after averaging"))
        self.labelTaps.setText(_translate("Dialog", "Number of taps to use for filtering:"))
        self.labelStart2.setText(_translate("Dialog", "seconds."))
        self.labelStart1.setText(_translate("Dialog", "Start artifact detection after"))
        self.checkBoxSSPProj.setText(_translate("Dialog", "Exclude SSP projections currently in the file"))
        self.groupBoxFilter.setTitle(_translate("Dialog", "Filtering cut-off frequencies for the data"))
        self.labelLow.setText(_translate("Dialog", "Low:"))
        self.spinBoxLow.setSuffix(_translate("Dialog", " Hz"))
        self.labelHigh.setText(_translate("Dialog", "High:"))
        self.spinBoxHigh.setSuffix(_translate("Dialog", " Hz"))
        self.tabWidgetEOGSettings.setTabText(self.tabWidgetEOGSettings.indexOf(self.tabEOG2), _translate("Dialog", "Advanced"))

