# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'icaDialogUi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(470, 647)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.bottomLayout = QtGui.QHBoxLayout()
        self.bottomLayout.setObjectName(_fromUtf8("bottomLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.bottomLayout.addItem(spacerItem)
        self.pushButtonCancel = QtGui.QPushButton(Dialog)
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))
        self.bottomLayout.addWidget(self.pushButtonCancel)
        self.pushButtonApply = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonApply.sizePolicy().hasHeightForWidth())
        self.pushButtonApply.setSizePolicy(sizePolicy)
        self.pushButtonApply.setObjectName(_fromUtf8("pushButtonApply"))
        self.bottomLayout.addWidget(self.pushButtonApply)
        self.gridLayout.addLayout(self.bottomLayout, 1, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(Dialog)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 452, 587))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_5 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupBoxComputation = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxComputation.setObjectName(_fromUtf8("groupBoxComputation"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBoxComputation)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.parametersLayout = QtGui.QGridLayout()
        self.parametersLayout.setObjectName(_fromUtf8("parametersLayout"))
        self.spinBoxMaxIter = QtGui.QSpinBox(self.groupBoxComputation)
        self.spinBoxMaxIter.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBoxMaxIter.setMinimum(1)
        self.spinBoxMaxIter.setMaximum(10000000)
        self.spinBoxMaxIter.setProperty("value", 2000)
        self.spinBoxMaxIter.setObjectName(_fromUtf8("spinBoxMaxIter"))
        self.parametersLayout.addWidget(self.spinBoxMaxIter, 1, 1, 1, 1)
        self.labelNComponents = QtGui.QLabel(self.groupBoxComputation)
        self.labelNComponents.setObjectName(_fromUtf8("labelNComponents"))
        self.parametersLayout.addWidget(self.labelNComponents, 0, 0, 1, 1)
        self.doubleSpinBoxNComponents = QtGui.QDoubleSpinBox(self.groupBoxComputation)
        self.doubleSpinBoxNComponents.setSuffix(_fromUtf8(""))
        self.doubleSpinBoxNComponents.setDecimals(3)
        self.doubleSpinBoxNComponents.setMaximum(1000.0)
        self.doubleSpinBoxNComponents.setSingleStep(0.1)
        self.doubleSpinBoxNComponents.setProperty("value", 0.95)
        self.doubleSpinBoxNComponents.setObjectName(_fromUtf8("doubleSpinBoxNComponents"))
        self.parametersLayout.addWidget(self.doubleSpinBoxNComponents, 0, 1, 1, 1)
        self.labelMaxIter = QtGui.QLabel(self.groupBoxComputation)
        self.labelMaxIter.setScaledContents(False)
        self.labelMaxIter.setObjectName(_fromUtf8("labelMaxIter"))
        self.parametersLayout.addWidget(self.labelMaxIter, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.parametersLayout, 0, 0, 1, 1)
        self.pushButtonCompute = QtGui.QPushButton(self.groupBoxComputation)
        self.pushButtonCompute.setObjectName(_fromUtf8("pushButtonCompute"))
        self.gridLayout_4.addWidget(self.pushButtonCompute, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBoxComputation, 0, 0, 1, 1)
        self.groupBoxComponents = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxComponents.setObjectName(_fromUtf8("groupBoxComponents"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBoxComponents)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelNotRemoved = QtGui.QLabel(self.groupBoxComponents)
        self.labelNotRemoved.setObjectName(_fromUtf8("labelNotRemoved"))
        self.gridLayout_2.addWidget(self.labelNotRemoved, 0, 0, 1, 1)
        self.listWidgetNotRemoved = QtGui.QListWidget(self.groupBoxComponents)
        self.listWidgetNotRemoved.setObjectName(_fromUtf8("listWidgetNotRemoved"))
        self.gridLayout_2.addWidget(self.listWidgetNotRemoved, 1, 0, 1, 1)
        self.listWidgetRemoved = QtGui.QListWidget(self.groupBoxComponents)
        self.listWidgetRemoved.setObjectName(_fromUtf8("listWidgetRemoved"))
        self.gridLayout_2.addWidget(self.listWidgetRemoved, 4, 0, 1, 1)
        self.labelRemoved = QtGui.QLabel(self.groupBoxComponents)
        self.labelRemoved.setObjectName(_fromUtf8("labelRemoved"))
        self.gridLayout_2.addWidget(self.labelRemoved, 3, 0, 1, 1)
        self.pushButtonTransfer = QtGui.QPushButton(self.groupBoxComponents)
        self.pushButtonTransfer.setObjectName(_fromUtf8("pushButtonTransfer"))
        self.gridLayout_2.addWidget(self.pushButtonTransfer, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButtonPlotProperties = QtGui.QPushButton(self.groupBoxComponents)
        self.pushButtonPlotProperties.setObjectName(_fromUtf8("pushButtonPlotProperties"))
        self.gridLayout_3.addWidget(self.pushButtonPlotProperties, 2, 0, 1, 1)
        self.pushButtonPlotOverlay = QtGui.QPushButton(self.groupBoxComponents)
        self.pushButtonPlotOverlay.setObjectName(_fromUtf8("pushButtonPlotOverlay"))
        self.gridLayout_3.addWidget(self.pushButtonPlotOverlay, 3, 0, 1, 1)
        self.pushButtonPlotSources = QtGui.QPushButton(self.groupBoxComponents)
        self.pushButtonPlotSources.setObjectName(_fromUtf8("pushButtonPlotSources"))
        self.gridLayout_3.addWidget(self.pushButtonPlotSources, 0, 0, 1, 1)
        self.pushButtonPlotTopographies = QtGui.QPushButton(self.groupBoxComponents)
        self.pushButtonPlotTopographies.setObjectName(_fromUtf8("pushButtonPlotTopographies"))
        self.gridLayout_3.addWidget(self.pushButtonPlotTopographies, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_7.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBoxComponents, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.pushButtonCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.reject)
        QtCore.QObject.connect(self.pushButtonApply, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "ICA", None))
        self.pushButtonCancel.setText(_translate("Dialog", "Cancel", None))
        self.pushButtonApply.setText(_translate("Dialog", "Apply", None))
        self.groupBoxComputation.setTitle(_translate("Dialog", "ICA computation", None))
        self.spinBoxMaxIter.setToolTip(_translate("Dialog", "Number of projections calculated for events. Try increasing this if the artefact is not completely removed.", None))
        self.labelNComponents.setText(_translate("Dialog", "Number of components:", None))
        self.labelMaxIter.setToolTip(_translate("Dialog", "Number of projections calculated for events. Try increasing this if the artefact is not completely removed.", None))
        self.labelMaxIter.setText(_translate("Dialog", "Maximum number of iterations: ", None))
        self.pushButtonCompute.setText(_translate("Dialog", "Compute", None))
        self.groupBoxComponents.setTitle(_translate("Dialog", "ICA components", None))
        self.labelNotRemoved.setText(_translate("Dialog", "Not removed", None))
        self.labelRemoved.setText(_translate("Dialog", "Removed", None))
        self.pushButtonTransfer.setText(_translate("Dialog", "Transfer", None))
        self.pushButtonPlotProperties.setText(_translate("Dialog", "Plot properties", None))
        self.pushButtonPlotOverlay.setText(_translate("Dialog", "Plot overlay", None))
        self.pushButtonPlotSources.setText(_translate("Dialog", "Plot sources", None))
        self.pushButtonPlotTopographies.setText(_translate("Dialog", "Plot topographies", None))

