# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kari/Opinnot/gradu/lahdekoodit/lahdekoodit/meggie_batch/ui/qt4Designer_ui_files/forwardModelDialog.ui'
#
# Created: Thu Jan  1 22:04:13 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_forwardModelDialog(object):
    def setupUi(self, forwardModelDialog):
        forwardModelDialog.setObjectName(_fromUtf8("forwardModelDialog"))
        forwardModelDialog.resize(579, 564)
        forwardModelDialog.setModal(True)
        self.formLayout_3 = QtGui.QFormLayout(forwardModelDialog)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.buttonBox = QtGui.QDialogButtonBox(forwardModelDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.SpanningRole, self.buttonBox)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.labelFModelName = QtGui.QLabel(forwardModelDialog)
        self.labelFModelName.setObjectName(_fromUtf8("labelFModelName"))
        self.horizontalLayout_6.addWidget(self.labelFModelName)
        self.lineEditFModelName = QtGui.QLineEdit(forwardModelDialog)
        self.lineEditFModelName.setObjectName(_fromUtf8("lineEditFModelName"))
        self.horizontalLayout_6.addWidget(self.lineEditFModelName)
        self.formLayout_3.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_6)
        self.groupBoxSetupBem = QtGui.QGroupBox(forwardModelDialog)
        self.groupBoxSetupBem.setObjectName(_fromUtf8("groupBoxSetupBem"))
        self.gridLayout = QtGui.QGridLayout(self.groupBoxSetupBem)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelHomog = QtGui.QLabel(self.groupBoxSetupBem)
        self.labelHomog.setObjectName(_fromUtf8("labelHomog"))
        self.gridLayout.addWidget(self.labelHomog, 1, 0, 1, 1)
        self.comboBoxCompartmentModel = QtGui.QComboBox(self.groupBoxSetupBem)
        self.comboBoxCompartmentModel.setObjectName(_fromUtf8("comboBoxCompartmentModel"))
        self.comboBoxCompartmentModel.addItem(_fromUtf8(""))
        self.comboBoxCompartmentModel.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxCompartmentModel, 1, 1, 1, 1)
        self.frame = QtGui.QFrame(self.groupBoxSetupBem)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayout = QtGui.QFormLayout(self.frame)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelShifts = QtGui.QLabel(self.frame)
        self.labelShifts.setObjectName(_fromUtf8("labelShifts"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.labelShifts)
        self.labelInnerShift = QtGui.QLabel(self.frame)
        self.labelInnerShift.setObjectName(_fromUtf8("labelInnerShift"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelInnerShift)
        self.spinBoxInnerShift = QtGui.QSpinBox(self.frame)
        self.spinBoxInnerShift.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxInnerShift.setPrefix(_fromUtf8(""))
        self.spinBoxInnerShift.setObjectName(_fromUtf8("spinBoxInnerShift"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBoxInnerShift)
        self.labelOuterShift = QtGui.QLabel(self.frame)
        self.labelOuterShift.setObjectName(_fromUtf8("labelOuterShift"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelOuterShift)
        self.spinBoxOuterShift = QtGui.QSpinBox(self.frame)
        self.spinBoxOuterShift.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxOuterShift.setObjectName(_fromUtf8("spinBoxOuterShift"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.spinBoxOuterShift)
        self.labelSkullShift = QtGui.QLabel(self.frame)
        self.labelSkullShift.setObjectName(_fromUtf8("labelSkullShift"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelSkullShift)
        self.spinBoxSkullShift = QtGui.QSpinBox(self.frame)
        self.spinBoxSkullShift.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxSkullShift.setObjectName(_fromUtf8("spinBoxSkullShift"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.spinBoxSkullShift)
        self.gridLayout.addWidget(self.frame, 3, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.groupBoxSetupBem)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.frame_2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelConductivity = QtGui.QLabel(self.frame_2)
        self.labelConductivity.setObjectName(_fromUtf8("labelConductivity"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.SpanningRole, self.labelConductivity)
        self.labelBrainComp = QtGui.QLabel(self.frame_2)
        self.labelBrainComp.setObjectName(_fromUtf8("labelBrainComp"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelBrainComp)
        self.doubleSpinBoxBrainConductivity = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBoxBrainConductivity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBrainConductivity.setDecimals(2)
        self.doubleSpinBoxBrainConductivity.setProperty("value", 0.3)
        self.doubleSpinBoxBrainConductivity.setObjectName(_fromUtf8("doubleSpinBoxBrainConductivity"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxBrainConductivity)
        self.labelSkullComp = QtGui.QLabel(self.frame_2)
        self.labelSkullComp.setObjectName(_fromUtf8("labelSkullComp"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelSkullComp)
        self.doubleSpinBoxSkullConductivity = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBoxSkullConductivity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxSkullConductivity.setPrefix(_fromUtf8(""))
        self.doubleSpinBoxSkullConductivity.setDecimals(3)
        self.doubleSpinBoxSkullConductivity.setProperty("value", 0.006)
        self.doubleSpinBoxSkullConductivity.setObjectName(_fromUtf8("doubleSpinBoxSkullConductivity"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxSkullConductivity)
        self.labelScalpComp = QtGui.QLabel(self.frame_2)
        self.labelScalpComp.setObjectName(_fromUtf8("labelScalpComp"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelScalpComp)
        self.doubleSpinBoxScalpConductivity = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBoxScalpConductivity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxScalpConductivity.setProperty("value", 0.03)
        self.doubleSpinBoxScalpConductivity.setObjectName(_fromUtf8("doubleSpinBoxScalpConductivity"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxScalpConductivity)
        self.gridLayout.addWidget(self.frame_2, 3, 1, 1, 1)
        self.labelTriangIco = QtGui.QLabel(self.groupBoxSetupBem)
        self.labelTriangIco.setObjectName(_fromUtf8("labelTriangIco"))
        self.gridLayout.addWidget(self.labelTriangIco, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radioButtonNosolNo = QtGui.QRadioButton(self.groupBoxSetupBem)
        self.radioButtonNosolNo.setChecked(True)
        self.radioButtonNosolNo.setObjectName(_fromUtf8("radioButtonNosolNo"))
        self.buttonGroupNosol = QtGui.QButtonGroup(forwardModelDialog)
        self.buttonGroupNosol.setObjectName(_fromUtf8("buttonGroupNosol"))
        self.buttonGroupNosol.addButton(self.radioButtonNosolNo)
        self.horizontalLayout_4.addWidget(self.radioButtonNosolNo)
        self.radioButtonNoSolYes = QtGui.QRadioButton(self.groupBoxSetupBem)
        self.radioButtonNoSolYes.setObjectName(_fromUtf8("radioButtonNoSolYes"))
        self.buttonGroupNosol.addButton(self.radioButtonNoSolYes)
        self.horizontalLayout_4.addWidget(self.radioButtonNoSolYes)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.labelNoSol = QtGui.QLabel(self.groupBoxSetupBem)
        self.labelNoSol.setObjectName(_fromUtf8("labelNoSol"))
        self.gridLayout.addWidget(self.labelNoSol, 2, 0, 1, 1)
        self.spinBoxTriangFilesIco = QtGui.QSpinBox(self.groupBoxSetupBem)
        self.spinBoxTriangFilesIco.setEnabled(True)
        self.spinBoxTriangFilesIco.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxTriangFilesIco.setProperty("value", 4)
        self.spinBoxTriangFilesIco.setObjectName(_fromUtf8("spinBoxTriangFilesIco"))
        self.gridLayout.addWidget(self.spinBoxTriangFilesIco, 0, 1, 1, 1)
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.SpanningRole, self.groupBoxSetupBem)
        self.groupBoxSourceSpaceSetup = QtGui.QGroupBox(forwardModelDialog)
        self.groupBoxSourceSpaceSetup.setObjectName(_fromUtf8("groupBoxSourceSpaceSetup"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxSourceSpaceSetup)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.labelSurface = QtGui.QLabel(self.groupBoxSourceSpaceSetup)
        self.labelSurface.setObjectName(_fromUtf8("labelSurface"))
        self.gridLayout_3.addWidget(self.labelSurface, 4, 0, 1, 1)
        self.spinBoxSpacing = QtGui.QSpinBox(self.groupBoxSourceSpaceSetup)
        self.spinBoxSpacing.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxSpacing.setProperty("value", 7)
        self.spinBoxSpacing.setObjectName(_fromUtf8("spinBoxSpacing"))
        self.gridLayout_3.addWidget(self.spinBoxSpacing, 2, 1, 1, 2)
        self.comboBoxSurfaceName = QtGui.QComboBox(self.groupBoxSourceSpaceSetup)
        self.comboBoxSurfaceName.setObjectName(_fromUtf8("comboBoxSurfaceName"))
        self.gridLayout_3.addWidget(self.comboBoxSurfaceName, 4, 1, 1, 2)
        self.labelIco = QtGui.QLabel(self.groupBoxSourceSpaceSetup)
        self.labelIco.setObjectName(_fromUtf8("labelIco"))
        self.gridLayout_3.addWidget(self.labelIco, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.radioButtonPatchStatNo = QtGui.QRadioButton(self.groupBoxSourceSpaceSetup)
        self.radioButtonPatchStatNo.setChecked(True)
        self.radioButtonPatchStatNo.setObjectName(_fromUtf8("radioButtonPatchStatNo"))
        self.buttonGroupCorticalPatchStats = QtGui.QButtonGroup(forwardModelDialog)
        self.buttonGroupCorticalPatchStats.setObjectName(_fromUtf8("buttonGroupCorticalPatchStats"))
        self.buttonGroupCorticalPatchStats.addButton(self.radioButtonPatchStatNo)
        self.horizontalLayout_3.addWidget(self.radioButtonPatchStatNo)
        self.radioButtonPatchStatYes = QtGui.QRadioButton(self.groupBoxSourceSpaceSetup)
        self.radioButtonPatchStatYes.setObjectName(_fromUtf8("radioButtonPatchStatYes"))
        self.buttonGroupCorticalPatchStats.addButton(self.radioButtonPatchStatYes)
        self.horizontalLayout_3.addWidget(self.radioButtonPatchStatYes)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 6, 1, 1, 2)
        self.labelSpacing = QtGui.QLabel(self.groupBoxSourceSpaceSetup)
        self.labelSpacing.setObjectName(_fromUtf8("labelSpacing"))
        self.gridLayout_3.addWidget(self.labelSpacing, 2, 0, 1, 1)
        self.labelCPS = QtGui.QLabel(self.groupBoxSourceSpaceSetup)
        self.labelCPS.setObjectName(_fromUtf8("labelCPS"))
        self.gridLayout_3.addWidget(self.labelCPS, 6, 0, 1, 1)
        self.spinBoxSurfaceDecimValue = QtGui.QSpinBox(self.groupBoxSourceSpaceSetup)
        self.spinBoxSurfaceDecimValue.setEnabled(False)
        self.spinBoxSurfaceDecimValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxSurfaceDecimValue.setObjectName(_fromUtf8("spinBoxSurfaceDecimValue"))
        self.gridLayout_3.addWidget(self.spinBoxSurfaceDecimValue, 1, 1, 1, 2)
        self.comboBoxSurfaceDecimMethod = QtGui.QComboBox(self.groupBoxSourceSpaceSetup)
        self.comboBoxSurfaceDecimMethod.setObjectName(_fromUtf8("comboBoxSurfaceDecimMethod"))
        self.comboBoxSurfaceDecimMethod.addItem(_fromUtf8(""))
        self.comboBoxSurfaceDecimMethod.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBoxSurfaceDecimMethod, 0, 1, 1, 2)
        self.labelIcoValue = QtGui.QLabel(self.groupBoxSourceSpaceSetup)
        self.labelIcoValue.setEnabled(False)
        self.labelIcoValue.setObjectName(_fromUtf8("labelIcoValue"))
        self.gridLayout_3.addWidget(self.labelIcoValue, 1, 0, 1, 1)
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.SpanningRole, self.groupBoxSourceSpaceSetup)
        self.groupBoxBemModelMeshes = QtGui.QGroupBox(forwardModelDialog)
        self.groupBoxBemModelMeshes.setObjectName(_fromUtf8("groupBoxBemModelMeshes"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxBemModelMeshes)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelAtlas = QtGui.QLabel(self.groupBoxBemModelMeshes)
        self.labelAtlas.setObjectName(_fromUtf8("labelAtlas"))
        self.gridLayout_2.addWidget(self.labelAtlas, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.radioButtonAtlasNo = QtGui.QRadioButton(self.groupBoxBemModelMeshes)
        self.radioButtonAtlasNo.setChecked(True)
        self.radioButtonAtlasNo.setObjectName(_fromUtf8("radioButtonAtlasNo"))
        self.buttonGroupAtlas = QtGui.QButtonGroup(forwardModelDialog)
        self.buttonGroupAtlas.setObjectName(_fromUtf8("buttonGroupAtlas"))
        self.buttonGroupAtlas.addButton(self.radioButtonAtlasNo)
        self.horizontalLayout_5.addWidget(self.radioButtonAtlasNo)
        self.radioButtonAtlasYes = QtGui.QRadioButton(self.groupBoxBemModelMeshes)
        self.radioButtonAtlasYes.setObjectName(_fromUtf8("radioButtonAtlasYes"))
        self.buttonGroupAtlas.addButton(self.radioButtonAtlasYes)
        self.horizontalLayout_5.addWidget(self.radioButtonAtlasYes)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 1, 1, 1)
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.SpanningRole, self.groupBoxBemModelMeshes)
        self.labelHomog.setBuddy(self.comboBoxCompartmentModel)
        self.labelInnerShift.setBuddy(self.spinBoxInnerShift)
        self.labelOuterShift.setBuddy(self.spinBoxOuterShift)
        self.labelSkullShift.setBuddy(self.spinBoxSkullShift)
        self.labelBrainComp.setBuddy(self.doubleSpinBoxBrainConductivity)
        self.labelSkullComp.setBuddy(self.doubleSpinBoxSkullConductivity)
        self.labelScalpComp.setBuddy(self.doubleSpinBoxScalpConductivity)
        self.labelSurface.setBuddy(self.comboBoxSurfaceName)
        self.labelSpacing.setBuddy(self.spinBoxSpacing)

        self.retranslateUi(forwardModelDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), forwardModelDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), forwardModelDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(forwardModelDialog)

    def retranslateUi(self, forwardModelDialog):
        forwardModelDialog.setWindowTitle(_translate("forwardModelDialog", "Create new forward model", None))
        self.labelFModelName.setText(_translate("forwardModelDialog", "Forward model name:", None))
        self.groupBoxSetupBem.setTitle(_translate("forwardModelDialog", "BEM model setup parameters:", None))
        self.labelHomog.setText(_translate("forwardModelDialog", "Compartment model (homog) :", None))
        self.comboBoxCompartmentModel.setItemText(0, _translate("forwardModelDialog", "single (usually used with MEG)", None))
        self.comboBoxCompartmentModel.setItemText(1, _translate("forwardModelDialog", "three layer", None))
        self.labelShifts.setText(_translate("forwardModelDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Shifts:</span></p></body></html>", None))
        self.labelInnerShift.setText(_translate("forwardModelDialog", "inner:", None))
        self.spinBoxInnerShift.setSuffix(_translate("forwardModelDialog", " mm", None))
        self.labelOuterShift.setText(_translate("forwardModelDialog", "outer:", None))
        self.spinBoxOuterShift.setSuffix(_translate("forwardModelDialog", " mm", None))
        self.labelSkullShift.setText(_translate("forwardModelDialog", "skull:", None))
        self.spinBoxSkullShift.setSuffix(_translate("forwardModelDialog", " mm", None))
        self.labelConductivity.setText(_translate("forwardModelDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Conductivity:</span></p></body></html>", None))
        self.labelBrainComp.setText(_translate("forwardModelDialog", "brainc:", None))
        self.doubleSpinBoxBrainConductivity.setSuffix(_translate("forwardModelDialog", " S/m", None))
        self.labelSkullComp.setText(_translate("forwardModelDialog", "skullc:", None))
        self.doubleSpinBoxSkullConductivity.setSuffix(_translate("forwardModelDialog", " S/m", None))
        self.labelScalpComp.setText(_translate("forwardModelDialog", "scalpc:", None))
        self.doubleSpinBoxScalpConductivity.setSuffix(_translate("forwardModelDialog", " S/m", None))
        self.labelTriangIco.setText(_translate("forwardModelDialog", "Triangulation files ico-number:", None))
        self.radioButtonNosolNo.setText(_translate("forwardModelDialog", "no (default)", None))
        self.radioButtonNoSolYes.setText(_translate("forwardModelDialog", "yes", None))
        self.labelNoSol.setText(_translate("forwardModelDialog", "Nosol:", None))
        self.groupBoxSourceSpaceSetup.setTitle(_translate("forwardModelDialog", "Source space setup parameters:", None))
        self.labelSurface.setText(_translate("forwardModelDialog", "Surface name (default is \"white\"):", None))
        self.spinBoxSpacing.setSuffix(_translate("forwardModelDialog", " mm", None))
        self.labelIco.setText(_translate("forwardModelDialog", "Cortical surface decimation method (ico):", None))
        self.radioButtonPatchStatNo.setText(_translate("forwardModelDialog", "no (default)", None))
        self.radioButtonPatchStatYes.setText(_translate("forwardModelDialog", "yes", None))
        self.labelSpacing.setText(_translate("forwardModelDialog", "Spacing (default is 7 mm):", None))
        self.labelCPS.setText(_translate("forwardModelDialog", "Compute cortical patch statistics:", None))
        self.comboBoxSurfaceDecimMethod.setItemText(0, _translate("forwardModelDialog", "traditional (default)", None))
        self.comboBoxSurfaceDecimMethod.setItemText(1, _translate("forwardModelDialog", "icosahedron or octahedron", None))
        self.labelIcoValue.setText(_translate("forwardModelDialog", "Ico value:", None))
        self.groupBoxBemModelMeshes.setTitle(_translate("forwardModelDialog", "BEM model meshes (watershed) creation parameters:", None))
        self.labelAtlas.setText(_translate("forwardModelDialog", "Use atlas:", None))
        self.radioButtonAtlasNo.setText(_translate("forwardModelDialog", "no (default)", None))
        self.radioButtonAtlasYes.setText(_translate("forwardModelDialog", "yes", None))

