# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kari/Opinnot/gradu/lahdekoodit/lahdekoodit/meggie_batch/ui/qt4Designer_ui_files/forwardModelDialog.ui'
#
# Created: Sun Oct 12 22:24:32 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_forwardModelDialog(object):
    def setupUi(self, forwardModelDialog):
        forwardModelDialog.setObjectName(_fromUtf8("forwardModelDialog"))
        forwardModelDialog.resize(613, 566)
        forwardModelDialog.setModal(True)
        self.formLayout_3 = QtGui.QFormLayout(forwardModelDialog)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.groupBoxSourceSpaceSetup = QtGui.QGroupBox(forwardModelDialog)
        self.groupBoxSourceSpaceSetup.setObjectName(_fromUtf8("groupBoxSourceSpaceSetup"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxSourceSpaceSetup)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(self.groupBoxSourceSpaceSetup)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.comboBoxSurfaceName = QtGui.QComboBox(self.groupBoxSourceSpaceSetup)
        self.comboBoxSurfaceName.setObjectName(_fromUtf8("comboBoxSurfaceName"))
        self.gridLayout_3.addWidget(self.comboBoxSurfaceName, 3, 1, 1, 1)
        self.spinBoxSpacing = QtGui.QSpinBox(self.groupBoxSourceSpaceSetup)
        self.spinBoxSpacing.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxSpacing.setObjectName(_fromUtf8("spinBoxSpacing"))
        self.gridLayout_3.addWidget(self.spinBoxSpacing, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBoxSourceSpaceSetup)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBoxSourceSpaceSetup)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBoxSourceSpaceSetup)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.comboBoxSurfaceDecimMethod = QtGui.QComboBox(self.groupBoxSourceSpaceSetup)
        self.comboBoxSurfaceDecimMethod.setObjectName(_fromUtf8("comboBoxSurfaceDecimMethod"))
        self.comboBoxSurfaceDecimMethod.addItem(_fromUtf8(""))
        self.comboBoxSurfaceDecimMethod.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.comboBoxSurfaceDecimMethod)
        self.spinBoxSurfaceDecimValue = QtGui.QSpinBox(self.groupBoxSourceSpaceSetup)
        self.spinBoxSurfaceDecimValue.setEnabled(False)
        self.spinBoxSurfaceDecimValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxSurfaceDecimValue.setObjectName(_fromUtf8("spinBoxSurfaceDecimValue"))
        self.horizontalLayout_2.addWidget(self.spinBoxSurfaceDecimValue)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.radioButtonPatchStatNo = QtGui.QRadioButton(self.groupBoxSourceSpaceSetup)
        self.radioButtonPatchStatNo.setChecked(True)
        self.radioButtonPatchStatNo.setObjectName(_fromUtf8("radioButtonPatchStatNo"))
        self.buttonGroupCorticalPatchStats = QtGui.QButtonGroup(forwardModelDialog)
        self.buttonGroupCorticalPatchStats.setObjectName(_fromUtf8("buttonGroupCorticalPatchStats"))
        self.buttonGroupCorticalPatchStats.addButton(self.radioButtonPatchStatNo)
        self.horizontalLayout_3.addWidget(self.radioButtonPatchStatNo)
        self.radioButtonPatchStatYes = QtGui.QRadioButton(self.groupBoxSourceSpaceSetup)
        self.radioButtonPatchStatYes.setObjectName(_fromUtf8("radioButtonPatchStatYes"))
        self.buttonGroupCorticalPatchStats.addButton(self.radioButtonPatchStatYes)
        self.horizontalLayout_3.addWidget(self.radioButtonPatchStatYes)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 5, 1, 1, 1)
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.groupBoxSourceSpaceSetup)
        self.groupBoxBemModelMeshes = QtGui.QGroupBox(forwardModelDialog)
        self.groupBoxBemModelMeshes.setObjectName(_fromUtf8("groupBoxBemModelMeshes"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxBemModelMeshes)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_5 = QtGui.QLabel(self.groupBoxBemModelMeshes)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.radioButtonAtlasNo = QtGui.QRadioButton(self.groupBoxBemModelMeshes)
        self.radioButtonAtlasNo.setChecked(True)
        self.radioButtonAtlasNo.setObjectName(_fromUtf8("radioButtonAtlasNo"))
        self.buttonGroupAtlas = QtGui.QButtonGroup(forwardModelDialog)
        self.buttonGroupAtlas.setObjectName(_fromUtf8("buttonGroupAtlas"))
        self.buttonGroupAtlas.addButton(self.radioButtonAtlasNo)
        self.horizontalLayout_5.addWidget(self.radioButtonAtlasNo)
        self.radioButtonAtlasYes = QtGui.QRadioButton(self.groupBoxBemModelMeshes)
        self.radioButtonAtlasYes.setObjectName(_fromUtf8("radioButtonAtlasYes"))
        self.buttonGroupAtlas.addButton(self.radioButtonAtlasYes)
        self.horizontalLayout_5.addWidget(self.radioButtonAtlasYes)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 1, 1, 1)
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.groupBoxBemModelMeshes)
        self.buttonBox = QtGui.QDialogButtonBox(forwardModelDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.SpanningRole, self.buttonBox)
        self.groupBoxSetupBem = QtGui.QGroupBox(forwardModelDialog)
        self.groupBoxSetupBem.setObjectName(_fromUtf8("groupBoxSetupBem"))
        self.gridLayout = QtGui.QGridLayout(self.groupBoxSetupBem)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_8 = QtGui.QLabel(self.groupBoxSetupBem)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.comboBoxCompartmentModel = QtGui.QComboBox(self.groupBoxSetupBem)
        self.comboBoxCompartmentModel.setObjectName(_fromUtf8("comboBoxCompartmentModel"))
        self.comboBoxCompartmentModel.addItem(_fromUtf8(""))
        self.comboBoxCompartmentModel.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxCompartmentModel, 1, 1, 1, 1)
        self.frame = QtGui.QFrame(self.groupBoxSetupBem)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayout = QtGui.QFormLayout(self.frame)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_14 = QtGui.QLabel(self.frame)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_14)
        self.label_13 = QtGui.QLabel(self.frame)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_13)
        self.spinBoxInnerShift = QtGui.QSpinBox(self.frame)
        self.spinBoxInnerShift.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxInnerShift.setPrefix(_fromUtf8(""))
        self.spinBoxInnerShift.setObjectName(_fromUtf8("spinBoxInnerShift"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBoxInnerShift)
        self.label_15 = QtGui.QLabel(self.frame)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_15)
        self.spinBoxOuterShift = QtGui.QSpinBox(self.frame)
        self.spinBoxOuterShift.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxOuterShift.setObjectName(_fromUtf8("spinBoxOuterShift"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.spinBoxOuterShift)
        self.label_16 = QtGui.QLabel(self.frame)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_16)
        self.spinBoxSkullShift = QtGui.QSpinBox(self.frame)
        self.spinBoxSkullShift.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxSkullShift.setObjectName(_fromUtf8("spinBoxSkullShift"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.spinBoxSkullShift)
        self.gridLayout.addWidget(self.frame, 3, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.comboBoxTriangFiles = QtGui.QComboBox(self.groupBoxSetupBem)
        self.comboBoxTriangFiles.setObjectName(_fromUtf8("comboBoxTriangFiles"))
        self.comboBoxTriangFiles.addItem(_fromUtf8(""))
        self.comboBoxTriangFiles.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBoxTriangFiles)
        self.label_7 = QtGui.QLabel(self.groupBoxSetupBem)
        self.label_7.setEnabled(False)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.spinBoxTriangFilesIco = QtGui.QSpinBox(self.groupBoxSetupBem)
        self.spinBoxTriangFilesIco.setEnabled(False)
        self.spinBoxTriangFilesIco.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxTriangFilesIco.setObjectName(_fromUtf8("spinBoxTriangFilesIco"))
        self.horizontalLayout.addWidget(self.spinBoxTriangFilesIco)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.frame_2 = QtGui.QFrame(self.groupBoxSetupBem)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.frame_2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_9 = QtGui.QLabel(self.frame_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.doubleSpinBoxBrainConductivity = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBoxBrainConductivity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBrainConductivity.setDecimals(2)
        self.doubleSpinBoxBrainConductivity.setProperty("value", 0.3)
        self.doubleSpinBoxBrainConductivity.setObjectName(_fromUtf8("doubleSpinBoxBrainConductivity"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxBrainConductivity)
        self.label_11 = QtGui.QLabel(self.frame_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_11)
        self.doubleSpinBoxSkullConductivity = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBoxSkullConductivity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxSkullConductivity.setPrefix(_fromUtf8(""))
        self.doubleSpinBoxSkullConductivity.setDecimals(3)
        self.doubleSpinBoxSkullConductivity.setProperty("value", 0.006)
        self.doubleSpinBoxSkullConductivity.setObjectName(_fromUtf8("doubleSpinBoxSkullConductivity"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxSkullConductivity)
        self.label_12 = QtGui.QLabel(self.frame_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_12)
        self.doubleSpinBoxScalpConductivity = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBoxScalpConductivity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxScalpConductivity.setProperty("value", 0.03)
        self.doubleSpinBoxScalpConductivity.setObjectName(_fromUtf8("doubleSpinBoxScalpConductivity"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxScalpConductivity)
        self.gridLayout.addWidget(self.frame_2, 3, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBoxSetupBem)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radioButtonNosolNo = QtGui.QRadioButton(self.groupBoxSetupBem)
        self.radioButtonNosolNo.setChecked(True)
        self.radioButtonNosolNo.setObjectName(_fromUtf8("radioButtonNosolNo"))
        self.buttonGroupNosol = QtGui.QButtonGroup(forwardModelDialog)
        self.buttonGroupNosol.setObjectName(_fromUtf8("buttonGroupNosol"))
        self.buttonGroupNosol.addButton(self.radioButtonNosolNo)
        self.horizontalLayout_4.addWidget(self.radioButtonNosolNo)
        self.radioButtonNoSolYes = QtGui.QRadioButton(self.groupBoxSetupBem)
        self.radioButtonNoSolYes.setObjectName(_fromUtf8("radioButtonNoSolYes"))
        self.buttonGroupNosol.addButton(self.radioButtonNoSolYes)
        self.horizontalLayout_4.addWidget(self.radioButtonNoSolYes)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBoxSetupBem)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 2, 0, 1, 1)
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.groupBoxSetupBem)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_17 = QtGui.QLabel(forwardModelDialog)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_6.addWidget(self.label_17)
        self.lineEditFModelName = QtGui.QLineEdit(forwardModelDialog)
        self.lineEditFModelName.setObjectName(_fromUtf8("lineEditFModelName"))
        self.horizontalLayout_6.addWidget(self.lineEditFModelName)
        self.formLayout_3.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_6)
        self.label.setBuddy(self.spinBoxSpacing)
        self.label_3.setBuddy(self.comboBoxSurfaceName)
        self.label_8.setBuddy(self.comboBoxCompartmentModel)
        self.label_13.setBuddy(self.spinBoxInnerShift)
        self.label_15.setBuddy(self.spinBoxOuterShift)
        self.label_16.setBuddy(self.spinBoxSkullShift)
        self.label_10.setBuddy(self.doubleSpinBoxBrainConductivity)
        self.label_11.setBuddy(self.doubleSpinBoxSkullConductivity)
        self.label_12.setBuddy(self.doubleSpinBoxScalpConductivity)
        self.label_6.setBuddy(self.comboBoxTriangFiles)

        self.retranslateUi(forwardModelDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), forwardModelDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), forwardModelDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(forwardModelDialog)

    def retranslateUi(self, forwardModelDialog):
        forwardModelDialog.setWindowTitle(_translate("forwardModelDialog", "Create new forward model", None))
        self.groupBoxSourceSpaceSetup.setTitle(_translate("forwardModelDialog", "Source space setup parameters:", None))
        self.label.setText(_translate("forwardModelDialog", "Spacing:", None))
        self.spinBoxSpacing.setSuffix(_translate("forwardModelDialog", " mm", None))
        self.label_4.setText(_translate("forwardModelDialog", "Compute cortical patch statistics:", None))
        self.label_3.setText(_translate("forwardModelDialog", "Surface name (defaut is \"white\"):", None))
        self.label_2.setText(_translate("forwardModelDialog", "Cortical surface decimation method (ico):", None))
        self.comboBoxSurfaceDecimMethod.setItemText(0, _translate("forwardModelDialog", "traditional (default)", None))
        self.comboBoxSurfaceDecimMethod.setItemText(1, _translate("forwardModelDialog", "icosahedron or octahedron", None))
        self.radioButtonPatchStatNo.setText(_translate("forwardModelDialog", "no (default)", None))
        self.radioButtonPatchStatYes.setText(_translate("forwardModelDialog", "yes", None))
        self.groupBoxBemModelMeshes.setTitle(_translate("forwardModelDialog", "BEM model meshes (watershed) creation parameters:", None))
        self.label_5.setText(_translate("forwardModelDialog", "Use atlas:", None))
        self.radioButtonAtlasNo.setText(_translate("forwardModelDialog", "no (default)", None))
        self.radioButtonAtlasYes.setText(_translate("forwardModelDialog", "yes", None))
        self.groupBoxSetupBem.setTitle(_translate("forwardModelDialog", "BEM model setup parameters:", None))
        self.label_8.setText(_translate("forwardModelDialog", "Compartment model (homog) :", None))
        self.comboBoxCompartmentModel.setItemText(0, _translate("forwardModelDialog", "three layer (default)", None))
        self.comboBoxCompartmentModel.setItemText(1, _translate("forwardModelDialog", "single", None))
        self.label_14.setText(_translate("forwardModelDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Shifts:</span></p></body></html>", None))
        self.label_13.setText(_translate("forwardModelDialog", "inner:", None))
        self.spinBoxInnerShift.setSuffix(_translate("forwardModelDialog", " mm", None))
        self.label_15.setText(_translate("forwardModelDialog", "outer:", None))
        self.spinBoxOuterShift.setSuffix(_translate("forwardModelDialog", " mm", None))
        self.label_16.setText(_translate("forwardModelDialog", "skull:", None))
        self.spinBoxSkullShift.setSuffix(_translate("forwardModelDialog", " mm", None))
        self.comboBoxTriangFiles.setItemText(0, _translate("forwardModelDialog", "standard ASCII (default)", None))
        self.comboBoxTriangFiles.setItemText(1, _translate("forwardModelDialog", "FreeSurfer triangulation files", None))
        self.label_7.setText(_translate("forwardModelDialog", "ico-number:", None))
        self.label_9.setText(_translate("forwardModelDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Conductivity:</span></p></body></html>", None))
        self.label_10.setText(_translate("forwardModelDialog", "brainc:", None))
        self.doubleSpinBoxBrainConductivity.setSuffix(_translate("forwardModelDialog", " S/m", None))
        self.label_11.setText(_translate("forwardModelDialog", "skullc:", None))
        self.doubleSpinBoxSkullConductivity.setSuffix(_translate("forwardModelDialog", " S/m", None))
        self.label_12.setText(_translate("forwardModelDialog", "scalpc:", None))
        self.doubleSpinBoxScalpConductivity.setSuffix(_translate("forwardModelDialog", " S/m", None))
        self.label_6.setText(_translate("forwardModelDialog", "Triangulation files:", None))
        self.radioButtonNosolNo.setText(_translate("forwardModelDialog", "no (default)", None))
        self.radioButtonNoSolYes.setText(_translate("forwardModelDialog", "yes", None))
        self.label_18.setText(_translate("forwardModelDialog", "Nosol:", None))
        self.label_17.setText(_translate("forwardModelDialog", "Forward model name:", None))

