# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filterDialogUi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogFilter(object):
    def setupUi(self, DialogFilter):
        DialogFilter.setObjectName(_fromUtf8("DialogFilter"))
        DialogFilter.resize(622, 979)
        self.gridLayout = QtGui.QGridLayout(DialogFilter)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonCancel = QtGui.QPushButton(DialogFilter)
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.pushButtonComputeBatch = QtGui.QPushButton(DialogFilter)
        self.pushButtonComputeBatch.setObjectName(_fromUtf8("pushButtonComputeBatch"))
        self.horizontalLayout.addWidget(self.pushButtonComputeBatch)
        self.pushButtonCompute = QtGui.QPushButton(DialogFilter)
        self.pushButtonCompute.setObjectName(_fromUtf8("pushButtonCompute"))
        self.horizontalLayout.addWidget(self.pushButtonCompute)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(DialogFilter)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 604, 922))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(604, 922))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.frameFilterSelection = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frameFilterSelection.setGeometry(QtCore.QRect(0, 10, 596, 491))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameFilterSelection.sizePolicy().hasHeightForWidth())
        self.frameFilterSelection.setSizePolicy(sizePolicy)
        self.frameFilterSelection.setMinimumSize(QtCore.QSize(350, 0))
        self.frameFilterSelection.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameFilterSelection.setFrameShadow(QtGui.QFrame.Raised)
        self.frameFilterSelection.setLineWidth(0)
        self.frameFilterSelection.setObjectName(_fromUtf8("frameFilterSelection"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frameFilterSelection)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frameBandPass = QtGui.QFrame(self.frameFilterSelection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameBandPass.sizePolicy().hasHeightForWidth())
        self.frameBandPass.setSizePolicy(sizePolicy)
        self.frameBandPass.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameBandPass.setFrameShadow(QtGui.QFrame.Raised)
        self.frameBandPass.setObjectName(_fromUtf8("frameBandPass"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frameBandPass)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frame_3 = QtGui.QFrame(self.frameBandPass)
        self.frame_3.setEnabled(True)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.frame_3)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.doubleSpinBoxBandstopFreq = QtGui.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBoxBandstopFreq.setEnabled(False)
        self.doubleSpinBoxBandstopFreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandstopFreq.setDecimals(3)
        self.doubleSpinBoxBandstopFreq.setMaximum(10000.0)
        self.doubleSpinBoxBandstopFreq.setSingleStep(1.0)
        self.doubleSpinBoxBandstopFreq.setProperty("value", 50.0)
        self.doubleSpinBoxBandstopFreq.setObjectName(_fromUtf8("doubleSpinBoxBandstopFreq"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxBandstopFreq)
        self.gridLayout_5.addWidget(self.frame_3, 1, 0, 1, 1)
        self.checkBoxBandstop = QtGui.QCheckBox(self.frameBandPass)
        self.checkBoxBandstop.setChecked(False)
        self.checkBoxBandstop.setObjectName(_fromUtf8("checkBoxBandstop"))
        self.gridLayout_5.addWidget(self.checkBoxBandstop, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frameBandPass, 2, 0, 1, 1)
        self.frameBandStop_3 = QtGui.QFrame(self.frameFilterSelection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameBandStop_3.sizePolicy().hasHeightForWidth())
        self.frameBandStop_3.setSizePolicy(sizePolicy)
        self.frameBandStop_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameBandStop_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frameBandStop_3.setObjectName(_fromUtf8("frameBandStop_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frameBandStop_3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.frame_4 = QtGui.QFrame(self.frameBandStop_3)
        self.frame_4.setEnabled(False)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.frame_4)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.doubleSpinBoxBandstopFreq2 = QtGui.QDoubleSpinBox(self.frame_4)
        self.doubleSpinBoxBandstopFreq2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandstopFreq2.setDecimals(3)
        self.doubleSpinBoxBandstopFreq2.setMaximum(10000.0)
        self.doubleSpinBoxBandstopFreq2.setSingleStep(1.0)
        self.doubleSpinBoxBandstopFreq2.setProperty("value", 100.0)
        self.doubleSpinBoxBandstopFreq2.setObjectName(_fromUtf8("doubleSpinBoxBandstopFreq2"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxBandstopFreq2)
        self.gridLayout_7.addWidget(self.frame_4, 1, 0, 1, 1)
        self.checkBoxBandstop2 = QtGui.QCheckBox(self.frameBandStop_3)
        self.checkBoxBandstop2.setObjectName(_fromUtf8("checkBoxBandstop2"))
        self.gridLayout_7.addWidget(self.checkBoxBandstop2, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frameBandStop_3, 2, 1, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.pushButtonPreview = QtGui.QPushButton(self.frameFilterSelection)
        self.pushButtonPreview.setEnabled(True)
        self.pushButtonPreview.setObjectName(_fromUtf8("pushButtonPreview"))
        self.horizontalLayout_8.addWidget(self.pushButtonPreview)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 6, 0, 1, 1)
        self.line = QtGui.QFrame(self.frameFilterSelection)
        self.line.setLineWidth(2)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.labelBandStopNotchWidth = QtGui.QLabel(self.frameFilterSelection)
        self.labelBandStopNotchWidth.setObjectName(_fromUtf8("labelBandStopNotchWidth"))
        self.horizontalLayout_5.addWidget(self.labelBandStopNotchWidth)
        self.doubleSpinBoxBandstopWidth = QtGui.QDoubleSpinBox(self.frameFilterSelection)
        self.doubleSpinBoxBandstopWidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandstopWidth.setDecimals(3)
        self.doubleSpinBoxBandstopWidth.setMaximum(10000.0)
        self.doubleSpinBoxBandstopWidth.setSingleStep(1.0)
        self.doubleSpinBoxBandstopWidth.setProperty("value", 1.0)
        self.doubleSpinBoxBandstopWidth.setObjectName(_fromUtf8("doubleSpinBoxBandstopWidth"))
        self.horizontalLayout_5.addWidget(self.doubleSpinBoxBandstopWidth)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 3, 0, 1, 2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.labelTransBw = QtGui.QLabel(self.frameFilterSelection)
        self.labelTransBw.setObjectName(_fromUtf8("labelTransBw"))
        self.horizontalLayout_7.addWidget(self.labelTransBw)
        self.doubleSpinBoxNotchTransBw = QtGui.QDoubleSpinBox(self.frameFilterSelection)
        self.doubleSpinBoxNotchTransBw.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxNotchTransBw.setDecimals(3)
        self.doubleSpinBoxNotchTransBw.setMinimum(0.1)
        self.doubleSpinBoxNotchTransBw.setSingleStep(0.1)
        self.doubleSpinBoxNotchTransBw.setProperty("value", 0.5)
        self.doubleSpinBoxNotchTransBw.setObjectName(_fromUtf8("doubleSpinBoxNotchTransBw"))
        self.horizontalLayout_7.addWidget(self.doubleSpinBoxNotchTransBw)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 4, 0, 1, 2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.labelBandstopFilterLength = QtGui.QLabel(self.frameFilterSelection)
        self.labelBandstopFilterLength.setObjectName(_fromUtf8("labelBandstopFilterLength"))
        self.horizontalLayout_6.addWidget(self.labelBandstopFilterLength)
        self.doubleSpinBoxBandStopLength = QtGui.QDoubleSpinBox(self.frameFilterSelection)
        self.doubleSpinBoxBandStopLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandStopLength.setSingleStep(0.1)
        self.doubleSpinBoxBandStopLength.setProperty("value", 10.0)
        self.doubleSpinBoxBandStopLength.setObjectName(_fromUtf8("doubleSpinBoxBandStopLength"))
        self.horizontalLayout_6.addWidget(self.doubleSpinBoxBandStopLength)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 5, 0, 1, 2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frameHighpass = QtGui.QFrame(self.frameFilterSelection)
        self.frameHighpass.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameHighpass.setFrameShadow(QtGui.QFrame.Raised)
        self.frameHighpass.setObjectName(_fromUtf8("frameHighpass"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frameHighpass)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.frame_2 = QtGui.QFrame(self.frameHighpass)
        self.frame_2.setEnabled(True)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.frame_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.doubleSpinBoxHighpassCutoff = QtGui.QDoubleSpinBox(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxHighpassCutoff.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxHighpassCutoff.setSizePolicy(sizePolicy)
        self.doubleSpinBoxHighpassCutoff.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxHighpassCutoff.setDecimals(3)
        self.doubleSpinBoxHighpassCutoff.setMaximum(1000000000.0)
        self.doubleSpinBoxHighpassCutoff.setSingleStep(1.0)
        self.doubleSpinBoxHighpassCutoff.setProperty("value", 1.0)
        self.doubleSpinBoxHighpassCutoff.setObjectName(_fromUtf8("doubleSpinBoxHighpassCutoff"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxHighpassCutoff)
        self.gridLayout_4.addWidget(self.frame_2, 1, 0, 1, 1)
        self.checkBoxHighpass = QtGui.QCheckBox(self.frameHighpass)
        self.checkBoxHighpass.setChecked(True)
        self.checkBoxHighpass.setObjectName(_fromUtf8("checkBoxHighpass"))
        self.gridLayout_4.addWidget(self.checkBoxHighpass, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frameHighpass)
        self.frameLowpass = QtGui.QFrame(self.frameFilterSelection)
        self.frameLowpass.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameLowpass.setFrameShadow(QtGui.QFrame.Raised)
        self.frameLowpass.setObjectName(_fromUtf8("frameLowpass"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frameLowpass)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.frame = QtGui.QFrame(self.frameLowpass)
        self.frame.setEnabled(True)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayout = QtGui.QFormLayout(self.frame)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.doubleSpinBoxLowpassCutoff = QtGui.QDoubleSpinBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxLowpassCutoff.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxLowpassCutoff.setSizePolicy(sizePolicy)
        self.doubleSpinBoxLowpassCutoff.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxLowpassCutoff.setDecimals(3)
        self.doubleSpinBoxLowpassCutoff.setMaximum(10000.0)
        self.doubleSpinBoxLowpassCutoff.setSingleStep(1.0)
        self.doubleSpinBoxLowpassCutoff.setProperty("value", 40.0)
        self.doubleSpinBoxLowpassCutoff.setObjectName(_fromUtf8("doubleSpinBoxLowpassCutoff"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxLowpassCutoff)
        self.gridLayout_3.addWidget(self.frame, 1, 0, 1, 1)
        self.checkBoxLowpass = QtGui.QCheckBox(self.frameLowpass)
        self.checkBoxLowpass.setChecked(True)
        self.checkBoxLowpass.setObjectName(_fromUtf8("checkBoxLowpass"))
        self.gridLayout_3.addWidget(self.checkBoxLowpass, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frameLowpass)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.labelTransitionWidth = QtGui.QLabel(self.frameFilterSelection)
        self.labelTransitionWidth.setObjectName(_fromUtf8("labelTransitionWidth"))
        self.horizontalLayout_4.addWidget(self.labelTransitionWidth)
        self.doubleSpinBoxTransBandwidth = QtGui.QDoubleSpinBox(self.frameFilterSelection)
        self.doubleSpinBoxTransBandwidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxTransBandwidth.setDecimals(3)
        self.doubleSpinBoxTransBandwidth.setMaximum(10000.0)
        self.doubleSpinBoxTransBandwidth.setSingleStep(0.1)
        self.doubleSpinBoxTransBandwidth.setProperty("value", 0.5)
        self.doubleSpinBoxTransBandwidth.setObjectName(_fromUtf8("doubleSpinBoxTransBandwidth"))
        self.horizontalLayout_4.addWidget(self.doubleSpinBoxTransBandwidth)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelFilterLength = QtGui.QLabel(self.frameFilterSelection)
        self.labelFilterLength.setObjectName(_fromUtf8("labelFilterLength"))
        self.horizontalLayout_3.addWidget(self.labelFilterLength)
        self.doubleSpinBoxLength = QtGui.QDoubleSpinBox(self.frameFilterSelection)
        self.doubleSpinBoxLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxLength.setSingleStep(0.1)
        self.doubleSpinBoxLength.setProperty("value", 10.0)
        self.doubleSpinBoxLength.setObjectName(_fromUtf8("doubleSpinBoxLength"))
        self.horizontalLayout_3.addWidget(self.doubleSpinBoxLength)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 2)
        self.widget = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(9, 510, 301, 371))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(DialogFilter)
        QtCore.QObject.connect(self.checkBoxBandstop2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame_4.setEnabled)
        QtCore.QObject.connect(self.checkBoxHighpass, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame_2.setEnabled)
        QtCore.QObject.connect(self.checkBoxLowpass, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame.setEnabled)
        QtCore.QObject.connect(self.pushButtonCompute, QtCore.SIGNAL(_fromUtf8("clicked()")), DialogFilter.accept)
        QtCore.QObject.connect(self.pushButtonCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), DialogFilter.reject)
        QtCore.QObject.connect(self.pushButtonComputeBatch, QtCore.SIGNAL(_fromUtf8("clicked()")), DialogFilter.acceptBatch)
        QtCore.QObject.connect(self.checkBoxBandstop, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBoxBandstopFreq.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(DialogFilter)
        DialogFilter.setTabOrder(self.checkBoxLowpass, self.doubleSpinBoxLowpassCutoff)
        DialogFilter.setTabOrder(self.doubleSpinBoxLowpassCutoff, self.checkBoxHighpass)
        DialogFilter.setTabOrder(self.checkBoxHighpass, self.doubleSpinBoxHighpassCutoff)
        DialogFilter.setTabOrder(self.doubleSpinBoxHighpassCutoff, self.checkBoxBandstop)
        DialogFilter.setTabOrder(self.checkBoxBandstop, self.doubleSpinBoxBandstopFreq)
        DialogFilter.setTabOrder(self.doubleSpinBoxBandstopFreq, self.checkBoxBandstop2)
        DialogFilter.setTabOrder(self.checkBoxBandstop2, self.doubleSpinBoxBandstopFreq2)

    def retranslateUi(self, DialogFilter):
        DialogFilter.setWindowTitle(_translate("DialogFilter", "Filtering", None))
        self.pushButtonCancel.setText(_translate("DialogFilter", "Cancel", None))
        self.pushButtonComputeBatch.setText(_translate("DialogFilter", "Compute Batch", None))
        self.pushButtonCompute.setText(_translate("DialogFilter", "Compute", None))
        self.doubleSpinBoxBandstopFreq.setSuffix(_translate("DialogFilter", " Hz", None))
        self.checkBoxBandstop.setText(_translate("DialogFilter", "BandStop filter (notch)", None))
        self.doubleSpinBoxBandstopFreq2.setSuffix(_translate("DialogFilter", " Hz", None))
        self.checkBoxBandstop2.setText(_translate("DialogFilter", "BandStop filter (notch)", None))
        self.pushButtonPreview.setText(_translate("DialogFilter", "Preview with given filters", None))
        self.labelBandStopNotchWidth.setText(_translate("DialogFilter", "Notch band width:", None))
        self.doubleSpinBoxBandstopWidth.setSuffix(_translate("DialogFilter", " Hz", None))
        self.labelTransBw.setText(_translate("DialogFilter", "Transition band width:", None))
        self.doubleSpinBoxNotchTransBw.setSuffix(_translate("DialogFilter", " Hz", None))
        self.labelBandstopFilterLength.setText(_translate("DialogFilter", "Filter length:", None))
        self.doubleSpinBoxBandStopLength.setSuffix(_translate("DialogFilter", "s", None))
        self.doubleSpinBoxHighpassCutoff.setSuffix(_translate("DialogFilter", " Hz", None))
        self.checkBoxHighpass.setText(_translate("DialogFilter", "Highpass filter", None))
        self.doubleSpinBoxLowpassCutoff.setSuffix(_translate("DialogFilter", " Hz", None))
        self.checkBoxLowpass.setText(_translate("DialogFilter", "Lowpass filter", None))
        self.labelTransitionWidth.setText(_translate("DialogFilter", "Transition band width:", None))
        self.doubleSpinBoxTransBandwidth.setSuffix(_translate("DialogFilter", " Hz", None))
        self.labelFilterLength.setText(_translate("DialogFilter", "Filter length:", None))
        self.doubleSpinBoxLength.setSuffix(_translate("DialogFilter", "s", None))

