# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filterDialog.ui'
#
# Created: Tue Aug 27 18:50:02 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogFilter(object):
    def setupUi(self, DialogFilter):
        DialogFilter.setObjectName(_fromUtf8("DialogFilter"))
        DialogFilter.resize(848, 865)
        self.gridLayout_2 = QtGui.QGridLayout(DialogFilter)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButtonPreview = QtGui.QPushButton(DialogFilter)
        self.pushButtonPreview.setObjectName(_fromUtf8("pushButtonPreview"))
        self.gridLayout_2.addWidget(self.pushButtonPreview, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(DialogFilter)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 1, 1, 1, 1)
        self.groupBoxPreview = QtGui.QGroupBox(DialogFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPreview.sizePolicy().hasHeightForWidth())
        self.groupBoxPreview.setSizePolicy(sizePolicy)
        self.groupBoxPreview.setObjectName(_fromUtf8("groupBoxPreview"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBoxPreview)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.widgetMpl = MplWidget(self.groupBoxPreview)
        self.widgetMpl.setObjectName(_fromUtf8("widgetMpl"))
        self.gridLayout_6.addWidget(self.widgetMpl, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxPreview, 0, 1, 1, 1)
        self.frameFilterSelection = QtGui.QFrame(DialogFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameFilterSelection.sizePolicy().hasHeightForWidth())
        self.frameFilterSelection.setSizePolicy(sizePolicy)
        self.frameFilterSelection.setMinimumSize(QtCore.QSize(350, 0))
        self.frameFilterSelection.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameFilterSelection.setFrameShadow(QtGui.QFrame.Raised)
        self.frameFilterSelection.setLineWidth(0)
        self.frameFilterSelection.setObjectName(_fromUtf8("frameFilterSelection"))
        self.gridLayout = QtGui.QGridLayout(self.frameFilterSelection)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frameLowpass = QtGui.QFrame(self.frameFilterSelection)
        self.frameLowpass.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameLowpass.setFrameShadow(QtGui.QFrame.Raised)
        self.frameLowpass.setObjectName(_fromUtf8("frameLowpass"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frameLowpass)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.frame = QtGui.QFrame(self.frameLowpass)
        self.frame.setEnabled(True)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayout = QtGui.QFormLayout(self.frame)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelLowpassCutoff = QtGui.QLabel(self.frame)
        self.labelLowpassCutoff.setObjectName(_fromUtf8("labelLowpassCutoff"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelLowpassCutoff)
        self.doubleSpinBoxLowpassCutoff = QtGui.QDoubleSpinBox(self.frame)
        self.doubleSpinBoxLowpassCutoff.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxLowpassCutoff.setObjectName(_fromUtf8("doubleSpinBoxLowpassCutoff"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxLowpassCutoff)
        self.labelLowpassTransitionWidth = QtGui.QLabel(self.frame)
        self.labelLowpassTransitionWidth.setObjectName(_fromUtf8("labelLowpassTransitionWidth"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelLowpassTransitionWidth)
        self.doubleSpinBoxLowpassTransBandwidth = QtGui.QDoubleSpinBox(self.frame)
        self.doubleSpinBoxLowpassTransBandwidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxLowpassTransBandwidth.setObjectName(_fromUtf8("doubleSpinBoxLowpassTransBandwidth"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxLowpassTransBandwidth)
        self.labelLowpassMethod = QtGui.QLabel(self.frame)
        self.labelLowpassMethod.setObjectName(_fromUtf8("labelLowpassMethod"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelLowpassMethod)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.radioButtonLowPassFft = QtGui.QRadioButton(self.frame)
        self.radioButtonLowPassFft.setObjectName(_fromUtf8("radioButtonLowPassFft"))
        self.buttonGroupLowpassMethod = QtGui.QButtonGroup(DialogFilter)
        self.buttonGroupLowpassMethod.setObjectName(_fromUtf8("buttonGroupLowpassMethod"))
        self.buttonGroupLowpassMethod.addButton(self.radioButtonLowPassFft)
        self.horizontalLayout_2.addWidget(self.radioButtonLowPassFft)
        self.radioButtonLowPassIir = QtGui.QRadioButton(self.frame)
        self.radioButtonLowPassIir.setObjectName(_fromUtf8("radioButtonLowPassIir"))
        self.buttonGroupLowpassMethod.addButton(self.radioButtonLowPassIir)
        self.horizontalLayout_2.addWidget(self.radioButtonLowPassIir)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.gridLayout_3.addWidget(self.frame, 1, 0, 1, 1)
        self.radioButtonLowpass = QtGui.QRadioButton(self.frameLowpass)
        self.radioButtonLowpass.setChecked(True)
        self.radioButtonLowpass.setObjectName(_fromUtf8("radioButtonLowpass"))
        self.buttonGroupFilterTypes = QtGui.QButtonGroup(DialogFilter)
        self.buttonGroupFilterTypes.setObjectName(_fromUtf8("buttonGroupFilterTypes"))
        self.buttonGroupFilterTypes.addButton(self.radioButtonLowpass)
        self.gridLayout_3.addWidget(self.radioButtonLowpass, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frameLowpass, 0, 0, 1, 1)
        self.line = QtGui.QFrame(self.frameFilterSelection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.frameHighpass = QtGui.QFrame(self.frameFilterSelection)
        self.frameHighpass.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameHighpass.setFrameShadow(QtGui.QFrame.Raised)
        self.frameHighpass.setObjectName(_fromUtf8("frameHighpass"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frameHighpass)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.frame_2 = QtGui.QFrame(self.frameHighpass)
        self.frame_2.setEnabled(False)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.frame_2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelHighpassCutoff = QtGui.QLabel(self.frame_2)
        self.labelHighpassCutoff.setObjectName(_fromUtf8("labelHighpassCutoff"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelHighpassCutoff)
        self.doubleSpinBoxHighpassCutoff = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBoxHighpassCutoff.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxHighpassCutoff.setObjectName(_fromUtf8("doubleSpinBoxHighpassCutoff"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxHighpassCutoff)
        self.labelHighpassTransitionWidth = QtGui.QLabel(self.frame_2)
        self.labelHighpassTransitionWidth.setObjectName(_fromUtf8("labelHighpassTransitionWidth"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelHighpassTransitionWidth)
        self.doubleSpinBoxHighpassTransBandwidth = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBoxHighpassTransBandwidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxHighpassTransBandwidth.setObjectName(_fromUtf8("doubleSpinBoxHighpassTransBandwidth"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxHighpassTransBandwidth)
        self.labelHighpassMethod = QtGui.QLabel(self.frame_2)
        self.labelHighpassMethod.setObjectName(_fromUtf8("labelHighpassMethod"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelHighpassMethod)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.radioButtonHighpassFft = QtGui.QRadioButton(self.frame_2)
        self.radioButtonHighpassFft.setObjectName(_fromUtf8("radioButtonHighpassFft"))
        self.buttonGroupHighpassMethod = QtGui.QButtonGroup(DialogFilter)
        self.buttonGroupHighpassMethod.setObjectName(_fromUtf8("buttonGroupHighpassMethod"))
        self.buttonGroupHighpassMethod.addButton(self.radioButtonHighpassFft)
        self.horizontalLayout_3.addWidget(self.radioButtonHighpassFft)
        self.radioButtonHighpassIir = QtGui.QRadioButton(self.frame_2)
        self.radioButtonHighpassIir.setObjectName(_fromUtf8("radioButtonHighpassIir"))
        self.buttonGroupHighpassMethod.addButton(self.radioButtonHighpassIir)
        self.horizontalLayout_3.addWidget(self.radioButtonHighpassIir)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.gridLayout_4.addWidget(self.frame_2, 1, 0, 1, 1)
        self.radioButtonHighpass = QtGui.QRadioButton(self.frameHighpass)
        self.radioButtonHighpass.setObjectName(_fromUtf8("radioButtonHighpass"))
        self.buttonGroupFilterTypes.addButton(self.radioButtonHighpass)
        self.gridLayout_4.addWidget(self.radioButtonHighpass, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frameHighpass, 2, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.frameFilterSelection)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 3, 0, 1, 1)
        self.frameBandPass = QtGui.QFrame(self.frameFilterSelection)
        self.frameBandPass.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameBandPass.setFrameShadow(QtGui.QFrame.Raised)
        self.frameBandPass.setObjectName(_fromUtf8("frameBandPass"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frameBandPass)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frame_3 = QtGui.QFrame(self.frameBandPass)
        self.frame_3.setEnabled(False)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.frame_3)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.labelBandpassCutoffLow = QtGui.QLabel(self.frame_3)
        self.labelBandpassCutoffLow.setObjectName(_fromUtf8("labelBandpassCutoffLow"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelBandpassCutoffLow)
        self.doubleSpinBoxBandLowpassCutoff = QtGui.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBoxBandLowpassCutoff.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandLowpassCutoff.setObjectName(_fromUtf8("doubleSpinBoxBandLowpassCutoff"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxBandLowpassCutoff)
        self.labelBandpassTransitionWidthLow = QtGui.QLabel(self.frame_3)
        self.labelBandpassTransitionWidthLow.setObjectName(_fromUtf8("labelBandpassTransitionWidthLow"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelBandpassTransitionWidthLow)
        self.doubleSpinBoxBandTransBandwidthLow = QtGui.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBoxBandTransBandwidthLow.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandTransBandwidthLow.setObjectName(_fromUtf8("doubleSpinBoxBandTransBandwidthLow"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxBandTransBandwidthLow)
        self.labelBandpassCutoffHigh = QtGui.QLabel(self.frame_3)
        self.labelBandpassCutoffHigh.setObjectName(_fromUtf8("labelBandpassCutoffHigh"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelBandpassCutoffHigh)
        self.doubleSpinBoxBandHighpassCutoff = QtGui.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBoxBandHighpassCutoff.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandHighpassCutoff.setObjectName(_fromUtf8("doubleSpinBoxBandHighpassCutoff"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxBandHighpassCutoff)
        self.labelBandpassTransitionWidthHigh = QtGui.QLabel(self.frame_3)
        self.labelBandpassTransitionWidthHigh.setObjectName(_fromUtf8("labelBandpassTransitionWidthHigh"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelBandpassTransitionWidthHigh)
        self.doubleSpinBoxBandTransBandwidthHigh = QtGui.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBoxBandTransBandwidthHigh.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandTransBandwidthHigh.setObjectName(_fromUtf8("doubleSpinBoxBandTransBandwidthHigh"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxBandTransBandwidthHigh)
        self.labelBandpassMethod = QtGui.QLabel(self.frame_3)
        self.labelBandpassMethod.setObjectName(_fromUtf8("labelBandpassMethod"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.labelBandpassMethod)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radioButtonBandpassFft = QtGui.QRadioButton(self.frame_3)
        self.radioButtonBandpassFft.setObjectName(_fromUtf8("radioButtonBandpassFft"))
        self.buttonGroupBandpassMethod = QtGui.QButtonGroup(DialogFilter)
        self.buttonGroupBandpassMethod.setObjectName(_fromUtf8("buttonGroupBandpassMethod"))
        self.buttonGroupBandpassMethod.addButton(self.radioButtonBandpassFft)
        self.horizontalLayout_4.addWidget(self.radioButtonBandpassFft)
        self.radioButtonBandpassIir = QtGui.QRadioButton(self.frame_3)
        self.radioButtonBandpassIir.setObjectName(_fromUtf8("radioButtonBandpassIir"))
        self.buttonGroupBandpassMethod.addButton(self.radioButtonBandpassIir)
        self.horizontalLayout_4.addWidget(self.radioButtonBandpassIir)
        self.formLayout_3.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.gridLayout_5.addWidget(self.frame_3, 1, 0, 1, 1)
        self.radioButtonBandpass = QtGui.QRadioButton(self.frameBandPass)
        self.radioButtonBandpass.setObjectName(_fromUtf8("radioButtonBandpass"))
        self.buttonGroupFilterTypes.addButton(self.radioButtonBandpass)
        self.gridLayout_5.addWidget(self.radioButtonBandpass, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frameBandPass, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frameFilterSelection, 0, 0, 1, 1)

        self.retranslateUi(DialogFilter)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DialogFilter.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DialogFilter.reject)
        QtCore.QObject.connect(self.radioButtonLowpass, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame.setEnabled)
        QtCore.QObject.connect(self.radioButtonHighpass, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame_2.setEnabled)
        QtCore.QObject.connect(self.radioButtonBandpass, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame_3.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(DialogFilter)

    def retranslateUi(self, DialogFilter):
        DialogFilter.setWindowTitle(_translate("DialogFilter", "Filtering", None))
        self.pushButtonPreview.setText(_translate("DialogFilter", "Preview", None))
        self.groupBoxPreview.setTitle(_translate("DialogFilter", "Preview", None))
        self.labelLowpassCutoff.setText(_translate("DialogFilter", "Cutoff frequency:", None))
        self.labelLowpassTransitionWidth.setText(_translate("DialogFilter", "Transition band width:", None))
        self.labelLowpassMethod.setText(_translate("DialogFilter", "Filtering method:", None))
        self.radioButtonLowPassFft.setText(_translate("DialogFilter", "fft", None))
        self.radioButtonLowPassIir.setText(_translate("DialogFilter", "iir", None))
        self.radioButtonLowpass.setText(_translate("DialogFilter", "Lowpass filter", None))
        self.labelHighpassCutoff.setText(_translate("DialogFilter", "Cutoff frequency:", None))
        self.labelHighpassTransitionWidth.setText(_translate("DialogFilter", "Transition band width:", None))
        self.labelHighpassMethod.setText(_translate("DialogFilter", "Filtering method:", None))
        self.radioButtonHighpassFft.setText(_translate("DialogFilter", "fft", None))
        self.radioButtonHighpassIir.setText(_translate("DialogFilter", "iir", None))
        self.radioButtonHighpass.setText(_translate("DialogFilter", "Highpass filter", None))
        self.labelBandpassCutoffLow.setText(_translate("DialogFilter", "Low cutoff frequency:", None))
        self.labelBandpassTransitionWidthLow.setText(_translate("DialogFilter", "Low cut-off transition band width:", None))
        self.labelBandpassCutoffHigh.setText(_translate("DialogFilter", "High cut-off frequency:", None))
        self.labelBandpassTransitionWidthHigh.setText(_translate("DialogFilter", "High cut-off transition band width:", None))
        self.labelBandpassMethod.setText(_translate("DialogFilter", "Filtering method:", None))
        self.radioButtonBandpassFft.setText(_translate("DialogFilter", "fft", None))
        self.radioButtonBandpassIir.setText(_translate("DialogFilter", "iir", None))
        self.radioButtonBandpass.setText(_translate("DialogFilter", "Bandpass filter", None))

from mplwidget import MplWidget
