# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt4Designer_ui_files/bitSelectionDialogUi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(919, 175)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label = QtGui.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.labelID = QtGui.QLabel(Dialog)
        self.labelID.setText(_fromUtf8(""))
        self.labelID.setObjectName(_fromUtf8("labelID"))
        self.horizontalLayout_3.addWidget(self.labelID)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.labelMask = QtGui.QLabel(Dialog)
        self.labelMask.setText(_fromUtf8(""))
        self.labelMask.setObjectName(_fromUtf8("labelMask"))
        self.horizontalLayout_3.addWidget(self.labelMask)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout16 = QtGui.QVBoxLayout()
        self.verticalLayout16.setObjectName(_fromUtf8("verticalLayout16"))
        self.pushButton16 = QtGui.QPushButton(Dialog)
        self.pushButton16.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton16.setText(_fromUtf8(""))
        self.pushButton16.setObjectName(_fromUtf8("pushButton16"))
        self.verticalLayout16.addWidget(self.pushButton16)
        self.bitLabel16 = QtGui.QLabel(Dialog)
        self.bitLabel16.setMaximumSize(QtCore.QSize(40, 16777215))
        self.bitLabel16.setAlignment(QtCore.Qt.AlignCenter)
        self.bitLabel16.setObjectName(_fromUtf8("bitLabel16"))
        self.verticalLayout16.addWidget(self.bitLabel16)
        self.horizontalLayout.addLayout(self.verticalLayout16)
        self.line16 = QtGui.QFrame(Dialog)
        self.line16.setFrameShape(QtGui.QFrame.VLine)
        self.line16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line16.setObjectName(_fromUtf8("line16"))
        self.horizontalLayout.addWidget(self.line16)
        self.verticalLayout15 = QtGui.QVBoxLayout()
        self.verticalLayout15.setObjectName(_fromUtf8("verticalLayout15"))
        self.pushButton15 = QtGui.QPushButton(Dialog)
        self.pushButton15.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton15.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton15.setText(_fromUtf8(""))
        self.pushButton15.setObjectName(_fromUtf8("pushButton15"))
        self.verticalLayout15.addWidget(self.pushButton15)
        self.bitLabel15 = QtGui.QLabel(Dialog)
        self.bitLabel15.setAlignment(QtCore.Qt.AlignCenter)
        self.bitLabel15.setObjectName(_fromUtf8("bitLabel15"))
        self.verticalLayout15.addWidget(self.bitLabel15)
        self.horizontalLayout.addLayout(self.verticalLayout15)
        self.line15 = QtGui.QFrame(Dialog)
        self.line15.setFrameShape(QtGui.QFrame.VLine)
        self.line15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line15.setObjectName(_fromUtf8("line15"))
        self.horizontalLayout.addWidget(self.line15)
        self.verticalLayout14 = QtGui.QVBoxLayout()
        self.verticalLayout14.setObjectName(_fromUtf8("verticalLayout14"))
        self.pushButton14 = QtGui.QPushButton(Dialog)
        self.pushButton14.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton14.setText(_fromUtf8(""))
        self.pushButton14.setObjectName(_fromUtf8("pushButton14"))
        self.verticalLayout14.addWidget(self.pushButton14)
        self.bitLabel14 = QtGui.QLabel(Dialog)
        self.bitLabel14.setAlignment(QtCore.Qt.AlignCenter)
        self.bitLabel14.setObjectName(_fromUtf8("bitLabel14"))
        self.verticalLayout14.addWidget(self.bitLabel14)
        self.horizontalLayout.addLayout(self.verticalLayout14)
        self.line14 = QtGui.QFrame(Dialog)
        self.line14.setFrameShape(QtGui.QFrame.VLine)
        self.line14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line14.setObjectName(_fromUtf8("line14"))
        self.horizontalLayout.addWidget(self.line14)
        self.verticalLayout13 = QtGui.QVBoxLayout()
        self.verticalLayout13.setObjectName(_fromUtf8("verticalLayout13"))
        self.pushButton13 = QtGui.QPushButton(Dialog)
        self.pushButton13.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton13.setText(_fromUtf8(""))
        self.pushButton13.setObjectName(_fromUtf8("pushButton13"))
        self.verticalLayout13.addWidget(self.pushButton13)
        self.bitLabel13 = QtGui.QLabel(Dialog)
        self.bitLabel13.setAlignment(QtCore.Qt.AlignCenter)
        self.bitLabel13.setObjectName(_fromUtf8("bitLabel13"))
        self.verticalLayout13.addWidget(self.bitLabel13)
        self.horizontalLayout.addLayout(self.verticalLayout13)
        self.line13 = QtGui.QFrame(Dialog)
        self.line13.setFrameShape(QtGui.QFrame.VLine)
        self.line13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line13.setObjectName(_fromUtf8("line13"))
        self.horizontalLayout.addWidget(self.line13)
        self.verticalLayout12 = QtGui.QVBoxLayout()
        self.verticalLayout12.setObjectName(_fromUtf8("verticalLayout12"))
        self.pushButton12 = QtGui.QPushButton(Dialog)
        self.pushButton12.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton12.setText(_fromUtf8(""))
        self.pushButton12.setObjectName(_fromUtf8("pushButton12"))
        self.verticalLayout12.addWidget(self.pushButton12)
        self.bitLabel12 = QtGui.QLabel(Dialog)
        self.bitLabel12.setAlignment(QtCore.Qt.AlignCenter)
        self.bitLabel12.setObjectName(_fromUtf8("bitLabel12"))
        self.verticalLayout12.addWidget(self.bitLabel12)
        self.horizontalLayout.addLayout(self.verticalLayout12)
        self.line12 = QtGui.QFrame(Dialog)
        self.line12.setFrameShape(QtGui.QFrame.VLine)
        self.line12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line12.setObjectName(_fromUtf8("line12"))
        self.horizontalLayout.addWidget(self.line12)
        self.verticalLayout11 = QtGui.QVBoxLayout()
        self.verticalLayout11.setObjectName(_fromUtf8("verticalLayout11"))
        self.pushButton11 = QtGui.QPushButton(Dialog)
        self.pushButton11.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton11.setText(_fromUtf8(""))
        self.pushButton11.setObjectName(_fromUtf8("pushButton11"))
        self.verticalLayout11.addWidget(self.pushButton11)
        self.bitLabel11 = QtGui.QLabel(Dialog)
        self.bitLabel11.setAlignment(QtCore.Qt.AlignCenter)
        self.bitLabel11.setObjectName(_fromUtf8("bitLabel11"))
        self.verticalLayout11.addWidget(self.bitLabel11)
        self.horizontalLayout.addLayout(self.verticalLayout11)
        self.line11 = QtGui.QFrame(Dialog)
        self.line11.setFrameShape(QtGui.QFrame.VLine)
        self.line11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line11.setObjectName(_fromUtf8("line11"))
        self.horizontalLayout.addWidget(self.line11)
        self.verticalLayout10 = QtGui.QVBoxLayout()
        self.verticalLayout10.setObjectName(_fromUtf8("verticalLayout10"))
        self.pushButton10 = QtGui.QPushButton(Dialog)
        self.pushButton10.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton10.setText(_fromUtf8(""))
        self.pushButton10.setObjectName(_fromUtf8("pushButton10"))
        self.verticalLayout10.addWidget(self.pushButton10)
        self.bitLabel10 = QtGui.QLabel(Dialog)
        self.bitLabel10.setAlignment(QtCore.Qt.AlignCenter)
        self.bitLabel10.setObjectName(_fromUtf8("bitLabel10"))
        self.verticalLayout10.addWidget(self.bitLabel10)
        self.horizontalLayout.addLayout(self.verticalLayout10)
        self.line10 = QtGui.QFrame(Dialog)
        self.line10.setFrameShape(QtGui.QFrame.VLine)
        self.line10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line10.setObjectName(_fromUtf8("line10"))
        self.horizontalLayout.addWidget(self.line10)
        self.verticalLayout9 = QtGui.QVBoxLayout()
        self.verticalLayout9.setObjectName(_fromUtf8("verticalLayout9"))
        self.pushButton9 = QtGui.QPushButton(Dialog)
        self.pushButton9.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton9.setText(_fromUtf8(""))
        self.pushButton9.setObjectName(_fromUtf8("pushButton9"))
        self.verticalLayout9.addWidget(self.pushButton9)
        self.bitLabel9 = QtGui.QLabel(Dialog)
        self.bitLabel9.setAlignment(QtCore.Qt.AlignCenter)
        self.bitLabel9.setObjectName(_fromUtf8("bitLabel9"))
        self.verticalLayout9.addWidget(self.bitLabel9)
        self.horizontalLayout.addLayout(self.verticalLayout9)
        self.line9 = QtGui.QFrame(Dialog)
        self.line9.setFrameShape(QtGui.QFrame.VLine)
        self.line9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line9.setObjectName(_fromUtf8("line9"))
        self.horizontalLayout.addWidget(self.line9)
        self.verticalLayout8 = QtGui.QVBoxLayout()
        self.verticalLayout8.setObjectName(_fromUtf8("verticalLayout8"))
        self.pushButton8 = QtGui.QPushButton(Dialog)
        self.pushButton8.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton8.setText(_fromUtf8(""))
        self.pushButton8.setObjectName(_fromUtf8("pushButton8"))
        self.verticalLayout8.addWidget(self.pushButton8)
        self.bitLabel8 = QtGui.QLabel(Dialog)
        self.bitLabel8.setAlignment(QtCore.Qt.AlignCenter)
        self.bitLabel8.setObjectName(_fromUtf8("bitLabel8"))
        self.verticalLayout8.addWidget(self.bitLabel8)
        self.horizontalLayout.addLayout(self.verticalLayout8)
        self.line8 = QtGui.QFrame(Dialog)
        self.line8.setFrameShape(QtGui.QFrame.VLine)
        self.line8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line8.setObjectName(_fromUtf8("line8"))
        self.horizontalLayout.addWidget(self.line8)
        self.verticalLayout7 = QtGui.QVBoxLayout()
        self.verticalLayout7.setObjectName(_fromUtf8("verticalLayout7"))
        self.pushButton7 = QtGui.QPushButton(Dialog)
        self.pushButton7.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton7.setText(_fromUtf8(""))
        self.pushButton7.setObjectName(_fromUtf8("pushButton7"))
        self.verticalLayout7.addWidget(self.pushButton7)
        self.bitLabel7 = QtGui.QLabel(Dialog)
        self.bitLabel7.setAlignment(QtCore.Qt.AlignCenter)
        self.bitLabel7.setObjectName(_fromUtf8("bitLabel7"))
        self.verticalLayout7.addWidget(self.bitLabel7)
        self.horizontalLayout.addLayout(self.verticalLayout7)
        self.line7 = QtGui.QFrame(Dialog)
        self.line7.setFrameShape(QtGui.QFrame.VLine)
        self.line7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line7.setObjectName(_fromUtf8("line7"))
        self.horizontalLayout.addWidget(self.line7)
        self.verticalLayout6 = QtGui.QVBoxLayout()
        self.verticalLayout6.setObjectName(_fromUtf8("verticalLayout6"))
        self.pushButton6 = QtGui.QPushButton(Dialog)
        self.pushButton6.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton6.setText(_fromUtf8(""))
        self.pushButton6.setObjectName(_fromUtf8("pushButton6"))
        self.verticalLayout6.addWidget(self.pushButton6)
        self.bitLabel6 = QtGui.QLabel(Dialog)
        self.bitLabel6.setAlignment(QtCore.Qt.AlignCenter)
        self.bitLabel6.setObjectName(_fromUtf8("bitLabel6"))
        self.verticalLayout6.addWidget(self.bitLabel6)
        self.horizontalLayout.addLayout(self.verticalLayout6)
        self.line6 = QtGui.QFrame(Dialog)
        self.line6.setFrameShape(QtGui.QFrame.VLine)
        self.line6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line6.setObjectName(_fromUtf8("line6"))
        self.horizontalLayout.addWidget(self.line6)
        self.verticalLayout5 = QtGui.QVBoxLayout()
        self.verticalLayout5.setObjectName(_fromUtf8("verticalLayout5"))
        self.pushButton5 = QtGui.QPushButton(Dialog)
        self.pushButton5.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton5.setText(_fromUtf8(""))
        self.pushButton5.setObjectName(_fromUtf8("pushButton5"))
        self.verticalLayout5.addWidget(self.pushButton5)
        self.bitLabel5 = QtGui.QLabel(Dialog)
        self.bitLabel5.setAlignment(QtCore.Qt.AlignCenter)
        self.bitLabel5.setObjectName(_fromUtf8("bitLabel5"))
        self.verticalLayout5.addWidget(self.bitLabel5)
        self.horizontalLayout.addLayout(self.verticalLayout5)
        self.line5 = QtGui.QFrame(Dialog)
        self.line5.setFrameShape(QtGui.QFrame.VLine)
        self.line5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line5.setObjectName(_fromUtf8("line5"))
        self.horizontalLayout.addWidget(self.line5)
        self.verticalLayout4 = QtGui.QVBoxLayout()
        self.verticalLayout4.setObjectName(_fromUtf8("verticalLayout4"))
        self.pushButton4 = QtGui.QPushButton(Dialog)
        self.pushButton4.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton4.setText(_fromUtf8(""))
        self.pushButton4.setObjectName(_fromUtf8("pushButton4"))
        self.verticalLayout4.addWidget(self.pushButton4)
        self.bitLabel4 = QtGui.QLabel(Dialog)
        self.bitLabel4.setAlignment(QtCore.Qt.AlignCenter)
        self.bitLabel4.setObjectName(_fromUtf8("bitLabel4"))
        self.verticalLayout4.addWidget(self.bitLabel4)
        self.horizontalLayout.addLayout(self.verticalLayout4)
        self.line4 = QtGui.QFrame(Dialog)
        self.line4.setFrameShape(QtGui.QFrame.VLine)
        self.line4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line4.setObjectName(_fromUtf8("line4"))
        self.horizontalLayout.addWidget(self.line4)
        self.verticalLayout3 = QtGui.QVBoxLayout()
        self.verticalLayout3.setObjectName(_fromUtf8("verticalLayout3"))
        self.pushButton3 = QtGui.QPushButton(Dialog)
        self.pushButton3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton3.setText(_fromUtf8(""))
        self.pushButton3.setObjectName(_fromUtf8("pushButton3"))
        self.verticalLayout3.addWidget(self.pushButton3)
        self.bitLabel3 = QtGui.QLabel(Dialog)
        self.bitLabel3.setAlignment(QtCore.Qt.AlignCenter)
        self.bitLabel3.setObjectName(_fromUtf8("bitLabel3"))
        self.verticalLayout3.addWidget(self.bitLabel3)
        self.horizontalLayout.addLayout(self.verticalLayout3)
        self.line3 = QtGui.QFrame(Dialog)
        self.line3.setFrameShape(QtGui.QFrame.VLine)
        self.line3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line3.setObjectName(_fromUtf8("line3"))
        self.horizontalLayout.addWidget(self.line3)
        self.verticalLayout2 = QtGui.QVBoxLayout()
        self.verticalLayout2.setObjectName(_fromUtf8("verticalLayout2"))
        self.pushButton2 = QtGui.QPushButton(Dialog)
        self.pushButton2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton2.setText(_fromUtf8(""))
        self.pushButton2.setObjectName(_fromUtf8("pushButton2"))
        self.verticalLayout2.addWidget(self.pushButton2)
        self.bitLabel2 = QtGui.QLabel(Dialog)
        self.bitLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.bitLabel2.setObjectName(_fromUtf8("bitLabel2"))
        self.verticalLayout2.addWidget(self.bitLabel2)
        self.horizontalLayout.addLayout(self.verticalLayout2)
        self.line2 = QtGui.QFrame(Dialog)
        self.line2.setFrameShape(QtGui.QFrame.VLine)
        self.line2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line2.setObjectName(_fromUtf8("line2"))
        self.horizontalLayout.addWidget(self.line2)
        self.verticalLayout1 = QtGui.QVBoxLayout()
        self.verticalLayout1.setObjectName(_fromUtf8("verticalLayout1"))
        self.pushButton1 = QtGui.QPushButton(Dialog)
        self.pushButton1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton1.setText(_fromUtf8(""))
        self.pushButton1.setObjectName(_fromUtf8("pushButton1"))
        self.verticalLayout1.addWidget(self.pushButton1)
        self.bitLabel1 = QtGui.QLabel(Dialog)
        self.bitLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.bitLabel1.setObjectName(_fromUtf8("bitLabel1"))
        self.verticalLayout1.addWidget(self.bitLabel1)
        self.horizontalLayout.addLayout(self.verticalLayout1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButtonReject = QtGui.QPushButton(Dialog)
        self.pushButtonReject.setObjectName(_fromUtf8("pushButtonReject"))
        self.horizontalLayout_2.addWidget(self.pushButtonReject)
        self.pushButtonAccept = QtGui.QPushButton(Dialog)
        self.pushButtonAccept.setObjectName(_fromUtf8("pushButtonAccept"))
        self.horizontalLayout_2.addWidget(self.pushButtonAccept)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.pushButtonReject, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.reject)
        QtCore.QObject.connect(self.pushButtonAccept, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Edit", None))
        self.label.setText(_translate("Dialog", "ID:", None))
        self.label_3.setText(_translate("Dialog", "Mask:", None))
        self.bitLabel16.setText(_translate("Dialog", "16", None))
        self.bitLabel15.setText(_translate("Dialog", "15", None))
        self.bitLabel14.setText(_translate("Dialog", "14", None))
        self.bitLabel13.setText(_translate("Dialog", "13", None))
        self.bitLabel12.setText(_translate("Dialog", "12", None))
        self.bitLabel11.setText(_translate("Dialog", "11", None))
        self.bitLabel10.setText(_translate("Dialog", "10", None))
        self.bitLabel9.setText(_translate("Dialog", "9", None))
        self.bitLabel8.setText(_translate("Dialog", "8", None))
        self.bitLabel7.setText(_translate("Dialog", "7", None))
        self.bitLabel6.setText(_translate("Dialog", "6", None))
        self.bitLabel5.setText(_translate("Dialog", "5", None))
        self.bitLabel4.setText(_translate("Dialog", "4", None))
        self.bitLabel3.setText(_translate("Dialog", "3", None))
        self.bitLabel2.setText(_translate("Dialog", "2", None))
        self.bitLabel1.setText(_translate("Dialog", "1", None))
        self.pushButtonReject.setText(_translate("Dialog", "Cancel", None))
        self.pushButtonAccept.setText(_translate("Dialog", "Ok", None))

