# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eogParametersDialogBatch.ui'
#
# Created: Tue Sep 22 02:30:15 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setEnabled(True)
        Dialog.resize(661, 891)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.pushButtonCancel = QtGui.QPushButton(Dialog)
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))
        self.horizontalLayout_13.addWidget(self.pushButtonCancel)
        self.pushButtonCompute = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCompute.sizePolicy().hasHeightForWidth())
        self.pushButtonCompute.setSizePolicy(sizePolicy)
        self.pushButtonCompute.setObjectName(_fromUtf8("pushButtonCompute"))
        self.horizontalLayout_13.addWidget(self.pushButtonCompute)
        self.gridLayout.addLayout(self.horizontalLayout_13, 1, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(Dialog)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 643, 834))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(540, 690))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.tabWidgetEOGSettings = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidgetEOGSettings.setGeometry(QtCore.QRect(0, 0, 553, 571))
        self.tabWidgetEOGSettings.setObjectName(_fromUtf8("tabWidgetEOGSettings"))
        self.tabEOG1 = QtGui.QWidget()
        self.tabEOG1.setObjectName(_fromUtf8("tabEOG1"))
        self.groupBoxFilter = QtGui.QGroupBox(self.tabEOG1)
        self.groupBoxFilter.setGeometry(QtCore.QRect(10, 340, 351, 101))
        self.groupBoxFilter.setObjectName(_fromUtf8("groupBoxFilter"))
        self.frame_7 = QtGui.QFrame(self.groupBoxFilter)
        self.frame_7.setGeometry(QtCore.QRect(10, 30, 261, 61))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.horizontalLayoutWidget_19 = QtGui.QWidget(self.frame_7)
        self.horizontalLayoutWidget_19.setGeometry(QtCore.QRect(10, 10, 246, 41))
        self.horizontalLayoutWidget_19.setObjectName(_fromUtf8("horizontalLayoutWidget_19"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_19)
        self.horizontalLayout_25.setMargin(0)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.labelLow = QtGui.QLabel(self.horizontalLayoutWidget_19)
        self.labelLow.setObjectName(_fromUtf8("labelLow"))
        self.horizontalLayout_26.addWidget(self.labelLow)
        self.spinBoxLow = QtGui.QSpinBox(self.horizontalLayoutWidget_19)
        self.spinBoxLow.setProperty("value", 1)
        self.spinBoxLow.setObjectName(_fromUtf8("spinBoxLow"))
        self.horizontalLayout_26.addWidget(self.spinBoxLow)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.labelHigh = QtGui.QLabel(self.horizontalLayoutWidget_19)
        self.labelHigh.setObjectName(_fromUtf8("labelHigh"))
        self.horizontalLayout_27.addWidget(self.labelHigh)
        self.spinBoxHigh = QtGui.QSpinBox(self.horizontalLayoutWidget_19)
        self.spinBoxHigh.setMaximum(1000)
        self.spinBoxHigh.setProperty("value", 35)
        self.spinBoxHigh.setObjectName(_fromUtf8("spinBoxHigh"))
        self.horizontalLayout_27.addWidget(self.spinBoxHigh)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_27)
        self.groupBoxFilteringEOG = QtGui.QGroupBox(self.tabEOG1)
        self.groupBoxFilteringEOG.setGeometry(QtCore.QRect(10, 120, 491, 101))
        self.groupBoxFilteringEOG.setObjectName(_fromUtf8("groupBoxFilteringEOG"))
        self.frame_6 = QtGui.QFrame(self.groupBoxFilteringEOG)
        self.frame_6.setGeometry(QtCore.QRect(10, 30, 471, 61))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayoutWidget_20 = QtGui.QWidget(self.frame_6)
        self.horizontalLayoutWidget_20.setGeometry(QtCore.QRect(10, 10, 451, 41))
        self.horizontalLayoutWidget_20.setObjectName(_fromUtf8("horizontalLayoutWidget_20"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_20)
        self.horizontalLayout_18.setMargin(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.labelLowPass = QtGui.QLabel(self.horizontalLayoutWidget_20)
        self.labelLowPass.setObjectName(_fromUtf8("labelLowPass"))
        self.horizontalLayout_23.addWidget(self.labelLowPass)
        self.spinBoxLowPass = QtGui.QSpinBox(self.horizontalLayoutWidget_20)
        self.spinBoxLowPass.setProperty("value", 1)
        self.spinBoxLowPass.setObjectName(_fromUtf8("spinBoxLowPass"))
        self.horizontalLayout_23.addWidget(self.spinBoxLowPass)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.labelHighPass = QtGui.QLabel(self.horizontalLayoutWidget_20)
        self.labelHighPass.setObjectName(_fromUtf8("labelHighPass"))
        self.horizontalLayout_24.addWidget(self.labelHighPass)
        self.spinBoxHighPass = QtGui.QSpinBox(self.horizontalLayoutWidget_20)
        self.spinBoxHighPass.setMaximum(1000)
        self.spinBoxHighPass.setProperty("value", 10)
        self.spinBoxHighPass.setObjectName(_fromUtf8("spinBoxHighPass"))
        self.horizontalLayout_24.addWidget(self.spinBoxHighPass)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_24)
        self.groupBoxSSP = QtGui.QGroupBox(self.tabEOG1)
        self.groupBoxSSP.setGeometry(QtCore.QRect(10, 230, 351, 101))
        self.groupBoxSSP.setObjectName(_fromUtf8("groupBoxSSP"))
        self.frame_2 = QtGui.QFrame(self.groupBoxSSP)
        self.frame_2.setGeometry(QtCore.QRect(10, 30, 331, 61))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayoutWidget_9 = QtGui.QWidget(self.frame_2)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(10, 10, 316, 41))
        self.horizontalLayoutWidget_9.setObjectName(_fromUtf8("horizontalLayoutWidget_9"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelGrad = QtGui.QLabel(self.horizontalLayoutWidget_9)
        self.labelGrad.setObjectName(_fromUtf8("labelGrad"))
        self.horizontalLayout_3.addWidget(self.labelGrad)
        self.spinBoxGrad = QtGui.QSpinBox(self.horizontalLayoutWidget_9)
        self.spinBoxGrad.setProperty("value", 2)
        self.spinBoxGrad.setObjectName(_fromUtf8("spinBoxGrad"))
        self.horizontalLayout_3.addWidget(self.spinBoxGrad)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.labelMag = QtGui.QLabel(self.horizontalLayoutWidget_9)
        self.labelMag.setObjectName(_fromUtf8("labelMag"))
        self.horizontalLayout_4.addWidget(self.labelMag)
        self.spinBoxMag = QtGui.QSpinBox(self.horizontalLayoutWidget_9)
        self.spinBoxMag.setProperty("value", 2)
        self.spinBoxMag.setObjectName(_fromUtf8("spinBoxMag"))
        self.horizontalLayout_4.addWidget(self.spinBoxMag)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.labelEeg = QtGui.QLabel(self.horizontalLayoutWidget_9)
        self.labelEeg.setObjectName(_fromUtf8("labelEeg"))
        self.horizontalLayout_5.addWidget(self.labelEeg)
        self.spinBoxEeg = QtGui.QSpinBox(self.horizontalLayoutWidget_9)
        self.spinBoxEeg.setProperty("value", 2)
        self.spinBoxEeg.setObjectName(_fromUtf8("spinBoxEeg"))
        self.horizontalLayout_5.addWidget(self.spinBoxEeg)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_5)
        self.groupBoxEvent = QtGui.QGroupBox(self.tabEOG1)
        self.groupBoxEvent.setGeometry(QtCore.QRect(10, 10, 541, 99))
        self.groupBoxEvent.setObjectName(_fromUtf8("groupBoxEvent"))
        self.frame = QtGui.QFrame(self.groupBoxEvent)
        self.frame.setGeometry(QtCore.QRect(10, 30, 511, 61))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayoutWidget_8 = QtGui.QWidget(self.frame)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 10, 495, 41))
        self.horizontalLayoutWidget_8.setObjectName(_fromUtf8("horizontalLayoutWidget_8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelTmin = QtGui.QLabel(self.horizontalLayoutWidget_8)
        self.labelTmin.setObjectName(_fromUtf8("labelTmin"))
        self.horizontalLayout.addWidget(self.labelTmin)
        self.doubleSpinBoxTmin = QtGui.QDoubleSpinBox(self.horizontalLayoutWidget_8)
        self.doubleSpinBoxTmin.setDecimals(3)
        self.doubleSpinBoxTmin.setMinimum(-99.99)
        self.doubleSpinBoxTmin.setSingleStep(0.05)
        self.doubleSpinBoxTmin.setProperty("value", -0.2)
        self.doubleSpinBoxTmin.setObjectName(_fromUtf8("doubleSpinBoxTmin"))
        self.horizontalLayout.addWidget(self.doubleSpinBoxTmin)
        self.horizontalLayout_8.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelTmax = QtGui.QLabel(self.horizontalLayoutWidget_8)
        self.labelTmax.setObjectName(_fromUtf8("labelTmax"))
        self.horizontalLayout_2.addWidget(self.labelTmax)
        self.doubleSpinBoxTmax = QtGui.QDoubleSpinBox(self.horizontalLayoutWidget_8)
        self.doubleSpinBoxTmax.setDecimals(3)
        self.doubleSpinBoxTmax.setMinimum(-99.99)
        self.doubleSpinBoxTmax.setSingleStep(0.05)
        self.doubleSpinBoxTmax.setProperty("value", 0.2)
        self.doubleSpinBoxTmax.setObjectName(_fromUtf8("doubleSpinBoxTmax"))
        self.horizontalLayout_2.addWidget(self.doubleSpinBoxTmax)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.labelEventID = QtGui.QLabel(self.horizontalLayoutWidget_8)
        self.labelEventID.setObjectName(_fromUtf8("labelEventID"))
        self.horizontalLayout_6.addWidget(self.labelEventID)
        self.spinBoxEventsID = QtGui.QSpinBox(self.horizontalLayoutWidget_8)
        self.spinBoxEventsID.setMaximum(10000)
        self.spinBoxEventsID.setProperty("value", 998)
        self.spinBoxEventsID.setObjectName(_fromUtf8("spinBoxEventsID"))
        self.horizontalLayout_6.addWidget(self.spinBoxEventsID)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_6)
        self.tabWidgetEOGSettings.addTab(self.tabEOG1, _fromUtf8(""))
        self.tabEOG2 = QtGui.QWidget()
        self.tabEOG2.setObjectName(_fromUtf8("tabEOG2"))
        self.horizontalLayoutWidget_17 = QtGui.QWidget(self.tabEOG2)
        self.horizontalLayoutWidget_17.setGeometry(QtCore.QRect(10, 60, 351, 41))
        self.horizontalLayoutWidget_17.setObjectName(_fromUtf8("horizontalLayoutWidget_17"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_17)
        self.horizontalLayout_21.setMargin(0)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.labelStart1 = QtGui.QLabel(self.horizontalLayoutWidget_17)
        self.labelStart1.setObjectName(_fromUtf8("labelStart1"))
        self.horizontalLayout_21.addWidget(self.labelStart1)
        self.spinBoxStart = QtGui.QSpinBox(self.horizontalLayoutWidget_17)
        self.spinBoxStart.setObjectName(_fromUtf8("spinBoxStart"))
        self.horizontalLayout_21.addWidget(self.spinBoxStart)
        self.labelStart2 = QtGui.QLabel(self.horizontalLayoutWidget_17)
        self.labelStart2.setObjectName(_fromUtf8("labelStart2"))
        self.horizontalLayout_21.addWidget(self.labelStart2)
        self.horizontalLayoutWidget = QtGui.QWidget(self.tabEOG2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 160, 285, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.labelJobs = QtGui.QLabel(self.horizontalLayoutWidget)
        self.labelJobs.setObjectName(_fromUtf8("labelJobs"))
        self.horizontalLayout_7.addWidget(self.labelJobs)
        self.spinBoxJobs = QtGui.QSpinBox(self.horizontalLayoutWidget)
        self.spinBoxJobs.setProperty("value", 1)
        self.spinBoxJobs.setObjectName(_fromUtf8("spinBoxJobs"))
        self.horizontalLayout_7.addWidget(self.spinBoxJobs)
        self.layoutWidget = QtGui.QWidget(self.tabEOG2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 531, 41))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_28.setMargin(0)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.labelBad = QtGui.QLabel(self.layoutWidget)
        self.labelBad.setObjectName(_fromUtf8("labelBad"))
        self.horizontalLayout_28.addWidget(self.labelBad)
        self.lineEditBad = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditBad.setObjectName(_fromUtf8("lineEditBad"))
        self.horizontalLayout_28.addWidget(self.lineEditBad)
        self.layoutWidget_2 = QtGui.QWidget(self.tabEOG2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 110, 309, 41))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_22.setMargin(0)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.labelTaps = QtGui.QLabel(self.layoutWidget_2)
        self.labelTaps.setObjectName(_fromUtf8("labelTaps"))
        self.horizontalLayout_22.addWidget(self.labelTaps)
        self.spinBoxTaps = QtGui.QSpinBox(self.layoutWidget_2)
        self.spinBoxTaps.setMaximum(10000)
        self.spinBoxTaps.setProperty("value", 2048)
        self.spinBoxTaps.setObjectName(_fromUtf8("spinBoxTaps"))
        self.horizontalLayout_22.addWidget(self.spinBoxTaps)
        self.verticalLayoutWidget = QtGui.QWidget(self.tabEOG2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 250, 371, 111))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.checkBoxEEGProj = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxEEGProj.setObjectName(_fromUtf8("checkBoxEEGProj"))
        self.verticalLayout.addWidget(self.checkBoxEEGProj)
        self.checkBoxSSPProj = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxSSPProj.setChecked(True)
        self.checkBoxSSPProj.setObjectName(_fromUtf8("checkBoxSSPProj"))
        self.verticalLayout.addWidget(self.checkBoxSSPProj)
        self.checkBoxSSPCompute = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxSSPCompute.setObjectName(_fromUtf8("checkBoxSSPCompute"))
        self.verticalLayout.addWidget(self.checkBoxSSPCompute)
        self.groupBox = QtGui.QGroupBox(self.tabEOG2)
        self.groupBox.setGeometry(QtCore.QRect(10, 400, 491, 151))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.frameEpochRejection = QtGui.QFrame(self.groupBox)
        self.frameEpochRejection.setEnabled(True)
        self.frameEpochRejection.setGeometry(QtCore.QRect(10, 30, 461, 91))
        self.frameEpochRejection.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameEpochRejection.setFrameShadow(QtGui.QFrame.Raised)
        self.frameEpochRejection.setObjectName(_fromUtf8("frameEpochRejection"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.frameEpochRejection)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 441, 80))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.labelGradReject = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.labelGradReject.setObjectName(_fromUtf8("labelGradReject"))
        self.horizontalLayout_14.addWidget(self.labelGradReject)
        self.doubleSpinBoxGradReject = QtGui.QDoubleSpinBox(self.horizontalLayoutWidget_4)
        self.doubleSpinBoxGradReject.setPrefix(_fromUtf8(""))
        self.doubleSpinBoxGradReject.setMaximum(1000000000.0)
        self.doubleSpinBoxGradReject.setProperty("value", 3000.0)
        self.doubleSpinBoxGradReject.setObjectName(_fromUtf8("doubleSpinBoxGradReject"))
        self.horizontalLayout_14.addWidget(self.doubleSpinBoxGradReject)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.labelEegReject = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.labelEegReject.setObjectName(_fromUtf8("labelEegReject"))
        self.horizontalLayout_11.addWidget(self.labelEegReject)
        self.doubleSpinBoxEEGReject = QtGui.QDoubleSpinBox(self.horizontalLayoutWidget_4)
        self.doubleSpinBoxEEGReject.setMaximum(1000000000.0)
        self.doubleSpinBoxEEGReject.setProperty("value", 100.0)
        self.doubleSpinBoxEEGReject.setObjectName(_fromUtf8("doubleSpinBoxEEGReject"))
        self.horizontalLayout_11.addWidget(self.doubleSpinBoxEEGReject)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.labelMagReject = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.labelMagReject.setObjectName(_fromUtf8("labelMagReject"))
        self.horizontalLayout_10.addWidget(self.labelMagReject)
        self.doubleSpinBoxMagReject = QtGui.QDoubleSpinBox(self.horizontalLayoutWidget_4)
        self.doubleSpinBoxMagReject.setMaximum(1000000000.0)
        self.doubleSpinBoxMagReject.setProperty("value", 4000.0)
        self.doubleSpinBoxMagReject.setObjectName(_fromUtf8("doubleSpinBoxMagReject"))
        self.horizontalLayout_10.addWidget(self.doubleSpinBoxMagReject)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.labelEogReject = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.labelEogReject.setObjectName(_fromUtf8("labelEogReject"))
        self.horizontalLayout_15.addWidget(self.labelEogReject)
        self.doubleSpinBoxEOGReject = QtGui.QDoubleSpinBox(self.horizontalLayoutWidget_4)
        self.doubleSpinBoxEOGReject.setMaximum(1000000000.0)
        self.doubleSpinBoxEOGReject.setProperty("value", 1000000000.0)
        self.doubleSpinBoxEOGReject.setObjectName(_fromUtf8("doubleSpinBoxEOGReject"))
        self.horizontalLayout_15.addWidget(self.doubleSpinBoxEOGReject)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_12.addLayout(self.verticalLayout_3)
        self.tabWidgetEOGSettings.addTab(self.tabEOG2, _fromUtf8(""))
        self.groupBoxBatch = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxBatch.setGeometry(QtCore.QRect(0, 580, 631, 240))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxBatch.sizePolicy().hasHeightForWidth())
        self.groupBoxBatch.setSizePolicy(sizePolicy)
        self.groupBoxBatch.setMinimumSize(QtCore.QSize(0, 240))
        self.groupBoxBatch.setObjectName(_fromUtf8("groupBoxBatch"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.groupBoxBatch)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 471, 209))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.checkBoxBatch = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxBatch.sizePolicy().hasHeightForWidth())
        self.checkBoxBatch.setSizePolicy(sizePolicy)
        self.checkBoxBatch.setObjectName(_fromUtf8("checkBoxBatch"))
        self.verticalLayout_9.addWidget(self.checkBoxBatch)
        self.labelSubjects = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.labelSubjects.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSubjects.sizePolicy().hasHeightForWidth())
        self.labelSubjects.setSizePolicy(sizePolicy)
        self.labelSubjects.setObjectName(_fromUtf8("labelSubjects"))
        self.verticalLayout_9.addWidget(self.labelSubjects)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.listWidgetSubjects = QtGui.QListWidget(self.verticalLayoutWidget_4)
        self.listWidgetSubjects.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetSubjects.sizePolicy().hasHeightForWidth())
        self.listWidgetSubjects.setSizePolicy(sizePolicy)
        self.listWidgetSubjects.setObjectName(_fromUtf8("listWidgetSubjects"))
        self.horizontalLayout_17.addWidget(self.listWidgetSubjects)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem1)
        self.label = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label.setEnabled(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_11.addWidget(self.label)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.pushButtonApply = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButtonApply.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonApply.sizePolicy().hasHeightForWidth())
        self.pushButtonApply.setSizePolicy(sizePolicy)
        self.pushButtonApply.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButtonApply.setMaximumSize(QtCore.QSize(90, 16777215))
        self.pushButtonApply.setObjectName(_fromUtf8("pushButtonApply"))
        self.horizontalLayout_30.addWidget(self.pushButtonApply)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_6.setEnabled(False)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_30.addWidget(self.label_6)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.pushButtonApplyAll = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButtonApplyAll.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonApplyAll.sizePolicy().hasHeightForWidth())
        self.pushButtonApplyAll.setSizePolicy(sizePolicy)
        self.pushButtonApplyAll.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButtonApplyAll.setMaximumSize(QtCore.QSize(90, 16777215))
        self.pushButtonApplyAll.setObjectName(_fromUtf8("pushButtonApplyAll"))
        self.horizontalLayout_31.addWidget(self.pushButtonApplyAll)
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_7.setEnabled(False)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_31.addWidget(self.label_7)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_31)
        self.verticalLayout_10.addLayout(self.verticalLayout_11)
        self.horizontalLayout_17.addLayout(self.verticalLayout_10)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.pushButtonRemove = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButtonRemove.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRemove.sizePolicy().hasHeightForWidth())
        self.pushButtonRemove.setSizePolicy(sizePolicy)
        self.pushButtonRemove.setObjectName(_fromUtf8("pushButtonRemove"))
        self.verticalLayout_9.addWidget(self.pushButtonRemove)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidgetEOGSettings.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButtonCompute, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.accept)
        QtCore.QObject.connect(self.pushButtonCancel, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), Dialog.reject)
        QtCore.QObject.connect(self.checkBoxBatch, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.labelSubjects.setEnabled)
        QtCore.QObject.connect(self.checkBoxBatch, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.listWidgetSubjects.setEnabled)
        QtCore.QObject.connect(self.checkBoxBatch, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label.setEnabled)
        QtCore.QObject.connect(self.checkBoxBatch, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pushButtonApply.setEnabled)
        QtCore.QObject.connect(self.checkBoxBatch, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_6.setEnabled)
        QtCore.QObject.connect(self.checkBoxBatch, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pushButtonApplyAll.setEnabled)
        QtCore.QObject.connect(self.checkBoxBatch, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_7.setEnabled)
        QtCore.QObject.connect(self.checkBoxBatch, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pushButtonRemove.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.scrollArea, self.doubleSpinBoxTmin)
        Dialog.setTabOrder(self.doubleSpinBoxTmin, self.doubleSpinBoxTmax)
        Dialog.setTabOrder(self.doubleSpinBoxTmax, self.spinBoxEventsID)
        Dialog.setTabOrder(self.spinBoxEventsID, self.spinBoxLowPass)
        Dialog.setTabOrder(self.spinBoxLowPass, self.spinBoxHighPass)
        Dialog.setTabOrder(self.spinBoxHighPass, self.spinBoxGrad)
        Dialog.setTabOrder(self.spinBoxGrad, self.spinBoxMag)
        Dialog.setTabOrder(self.spinBoxMag, self.spinBoxEeg)
        Dialog.setTabOrder(self.spinBoxEeg, self.spinBoxLow)
        Dialog.setTabOrder(self.spinBoxLow, self.spinBoxHigh)
        Dialog.setTabOrder(self.spinBoxHigh, self.lineEditBad)
        Dialog.setTabOrder(self.lineEditBad, self.spinBoxStart)
        Dialog.setTabOrder(self.spinBoxStart, self.spinBoxTaps)
        Dialog.setTabOrder(self.spinBoxTaps, self.spinBoxJobs)
        Dialog.setTabOrder(self.spinBoxJobs, self.checkBoxEEGProj)
        Dialog.setTabOrder(self.checkBoxEEGProj, self.checkBoxSSPProj)
        Dialog.setTabOrder(self.checkBoxSSPProj, self.checkBoxSSPCompute)
        Dialog.setTabOrder(self.checkBoxSSPCompute, self.pushButtonCancel)
        Dialog.setTabOrder(self.pushButtonCancel, self.pushButtonCompute)
        Dialog.setTabOrder(self.pushButtonCompute, self.tabWidgetEOGSettings)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Meggie - Compute EOG projections", None))
        self.pushButtonCancel.setText(_translate("Dialog", "Cancel", None))
        self.pushButtonCompute.setText(_translate("Dialog", "Compute", None))
        self.groupBoxFilter.setTitle(_translate("Dialog", "Filtering cut-off frequency", None))
        self.labelLow.setText(_translate("Dialog", "Low:", None))
        self.spinBoxLow.setSuffix(_translate("Dialog", " Hz", None))
        self.labelHigh.setText(_translate("Dialog", "High:", None))
        self.spinBoxHigh.setSuffix(_translate("Dialog", " Hz", None))
        self.groupBoxFilteringEOG.setTitle(_translate("Dialog", "Filtering EOG channel", None))
        self.labelLowPass.setText(_translate("Dialog", "Low pass frequency:", None))
        self.spinBoxLowPass.setSuffix(_translate("Dialog", " Hz", None))
        self.labelHighPass.setText(_translate("Dialog", "High pass frequency:", None))
        self.spinBoxHighPass.setSuffix(_translate("Dialog", " Hz", None))
        self.groupBoxSSP.setTitle(_translate("Dialog", "Number of SSP vectors", None))
        self.labelGrad.setText(_translate("Dialog", "Grad:", None))
        self.labelMag.setText(_translate("Dialog", "Mag:", None))
        self.labelEeg.setText(_translate("Dialog", "EEG:", None))
        self.groupBoxEvent.setTitle(_translate("Dialog", "Events", None))
        self.labelTmin.setText(_translate("Dialog", "Start time:", None))
        self.doubleSpinBoxTmin.setSuffix(_translate("Dialog", " s", None))
        self.labelTmax.setText(_translate("Dialog", "End time:", None))
        self.doubleSpinBoxTmax.setSuffix(_translate("Dialog", " s", None))
        self.labelEventID.setText(_translate("Dialog", "Events ID:", None))
        self.tabWidgetEOGSettings.setTabText(self.tabWidgetEOGSettings.indexOf(self.tabEOG1), _translate("Dialog", "EOG settings", None))
        self.labelStart1.setText(_translate("Dialog", "Start artifact detection after", None))
        self.labelStart2.setText(_translate("Dialog", "seconds.", None))
        self.labelJobs.setText(_translate("Dialog", "Number of jobs to run in parallel:", None))
        self.labelBad.setText(_translate("Dialog", "Bad channels (eg. MEG 2443, MEG 1531):", None))
        self.labelTaps.setText(_translate("Dialog", "Number of taps to use for filtering:", None))
        self.checkBoxEEGProj.setText(_translate("Dialog", "Add EEG average reference proj.", None))
        self.checkBoxSSPProj.setText(_translate("Dialog", "Exclude the SSP projectors currently in the fiff file", None))
        self.checkBoxSSPCompute.setText(_translate("Dialog", "Compute SSP after averaging", None))
        self.groupBox.setTitle(_translate("Dialog", "Epoch rejection", None))
        self.labelGradReject.setText(_translate("Dialog", "Grad:", None))
        self.doubleSpinBoxGradReject.setSuffix(_translate("Dialog", " fT/cm", None))
        self.labelEegReject.setText(_translate("Dialog", "EEG:", None))
        self.doubleSpinBoxEEGReject.setSuffix(_translate("Dialog", " uV", None))
        self.labelMagReject.setText(_translate("Dialog", "Mag:", None))
        self.doubleSpinBoxMagReject.setSuffix(_translate("Dialog", " fT", None))
        self.labelEogReject.setText(_translate("Dialog", "EOG:", None))
        self.doubleSpinBoxEOGReject.setSuffix(_translate("Dialog", " uV", None))
        self.tabWidgetEOGSettings.setTabText(self.tabWidgetEOGSettings.indexOf(self.tabEOG2), _translate("Dialog", "Bads etc.", None))
        self.groupBoxBatch.setTitle(_translate("Dialog", "Batch processing", None))
        self.checkBoxBatch.setText(_translate("Dialog", "Enable", None))
        self.labelSubjects.setText(_translate("Dialog", "Select subject to modify its parameters", None))
        self.label.setText(_translate("Dialog", "Apply parameters:", None))
        self.pushButtonApply.setText(_translate("Dialog", "Apply", None))
        self.label_6.setText(_translate("Dialog", "to selected subject", None))
        self.pushButtonApplyAll.setText(_translate("Dialog", "Apply to all", None))
        self.label_7.setText(_translate("Dialog", "subjects on the list", None))
        self.pushButtonRemove.setText(_translate("Dialog", "Remove subject from this process", None))

