# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(928, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollAreaLeft = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollAreaLeft.setMaximumSize(QtCore.QSize(300, 16777215))
        self.scrollAreaLeft.setWidgetResizable(True)
        self.scrollAreaLeft.setObjectName("scrollAreaLeft")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 284, 600))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(200, 600))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBoxSubjects = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxSubjects.setObjectName("groupBoxSubjects")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBoxSubjects)
        self.gridLayout_12.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButtonActivateSubject = QtWidgets.QPushButton(self.groupBoxSubjects)
        self.pushButtonActivateSubject.setObjectName("pushButtonActivateSubject")
        self.gridLayout_5.addWidget(self.pushButtonActivateSubject, 0, 0, 1, 1)
        self.pushButtonAddSubjects = QtWidgets.QPushButton(self.groupBoxSubjects)
        self.pushButtonAddSubjects.setObjectName("pushButtonAddSubjects")
        self.gridLayout_5.addWidget(self.pushButtonAddSubjects, 0, 1, 1, 1)
        self.pushButtonRemoveSubject = QtWidgets.QPushButton(self.groupBoxSubjects)
        self.pushButtonRemoveSubject.setObjectName("pushButtonRemoveSubject")
        self.gridLayout_5.addWidget(self.pushButtonRemoveSubject, 1, 0, 1, 1)
        self.pushButtonLayout = QtWidgets.QPushButton(self.groupBoxSubjects)
        self.pushButtonLayout.setObjectName("pushButtonLayout")
        self.gridLayout_5.addWidget(self.pushButtonLayout, 1, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.listWidgetSubjects = QtWidgets.QListWidget(self.groupBoxSubjects)
        self.listWidgetSubjects.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidgetSubjects.setObjectName("listWidgetSubjects")
        self.gridLayout_12.addWidget(self.listWidgetSubjects, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxSubjects, 2, 0, 1, 1)
        self.groupBoxInfo = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxInfo.setObjectName("groupBoxInfo")
        self.formLayout = QtWidgets.QFormLayout(self.groupBoxInfo)
        self.formLayout.setObjectName("formLayout")
        self.labelSubject = QtWidgets.QLabel(self.groupBoxInfo)
        self.labelSubject.setWordWrap(False)
        self.labelSubject.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelSubject.setObjectName("labelSubject")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelSubject)
        self.labelSubjectValue = QtWidgets.QLabel(self.groupBoxInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSubjectValue.sizePolicy().hasHeightForWidth())
        self.labelSubjectValue.setSizePolicy(sizePolicy)
        self.labelSubjectValue.setText("")
        self.labelSubjectValue.setWordWrap(True)
        self.labelSubjectValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelSubjectValue.setObjectName("labelSubjectValue")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelSubjectValue)
        self.labelDate = QtWidgets.QLabel(self.groupBoxInfo)
        self.labelDate.setWordWrap(False)
        self.labelDate.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelDate.setObjectName("labelDate")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelDate)
        self.labelDateValue = QtWidgets.QLabel(self.groupBoxInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDateValue.sizePolicy().hasHeightForWidth())
        self.labelDateValue.setSizePolicy(sizePolicy)
        self.labelDateValue.setText("")
        self.labelDateValue.setWordWrap(True)
        self.labelDateValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelDateValue.setObjectName("labelDateValue")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.labelDateValue)
        self.labelLength = QtWidgets.QLabel(self.groupBoxInfo)
        self.labelLength.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelLength.setObjectName("labelLength")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelLength)
        self.labelLengthValue = QtWidgets.QLabel(self.groupBoxInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLengthValue.sizePolicy().hasHeightForWidth())
        self.labelLengthValue.setSizePolicy(sizePolicy)
        self.labelLengthValue.setText("")
        self.labelLengthValue.setObjectName("labelLengthValue")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.labelLengthValue)
        self.labelSamples = QtWidgets.QLabel(self.groupBoxInfo)
        self.labelSamples.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelSamples.setObjectName("labelSamples")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelSamples)
        self.labelSamplesValue = QtWidgets.QLabel(self.groupBoxInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSamplesValue.sizePolicy().hasHeightForWidth())
        self.labelSamplesValue.setSizePolicy(sizePolicy)
        self.labelSamplesValue.setText("")
        self.labelSamplesValue.setWordWrap(True)
        self.labelSamplesValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelSamplesValue.setObjectName("labelSamplesValue")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.labelSamplesValue)
        self.labelLow = QtWidgets.QLabel(self.groupBoxInfo)
        self.labelLow.setLineWidth(1)
        self.labelLow.setScaledContents(True)
        self.labelLow.setWordWrap(False)
        self.labelLow.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelLow.setObjectName("labelLow")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelLow)
        self.labelLowValue = QtWidgets.QLabel(self.groupBoxInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLowValue.sizePolicy().hasHeightForWidth())
        self.labelLowValue.setSizePolicy(sizePolicy)
        self.labelLowValue.setText("")
        self.labelLowValue.setWordWrap(True)
        self.labelLowValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelLowValue.setObjectName("labelLowValue")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.labelLowValue)
        self.labelHigh = QtWidgets.QLabel(self.groupBoxInfo)
        self.labelHigh.setWordWrap(False)
        self.labelHigh.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelHigh.setObjectName("labelHigh")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelHigh)
        self.labelHighValue = QtWidgets.QLabel(self.groupBoxInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHighValue.sizePolicy().hasHeightForWidth())
        self.labelHighValue.setSizePolicy(sizePolicy)
        self.labelHighValue.setText("")
        self.labelHighValue.setWordWrap(True)
        self.labelHighValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelHighValue.setObjectName("labelHighValue")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.labelHighValue)
        self.labelICAApplied = QtWidgets.QLabel(self.groupBoxInfo)
        self.labelICAApplied.setObjectName("labelICAApplied")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelICAApplied)
        self.checkBoxICAApplied = QtWidgets.QCheckBox(self.groupBoxInfo)
        self.checkBoxICAApplied.setEnabled(False)
        self.checkBoxICAApplied.setText("")
        self.checkBoxICAApplied.setObjectName("checkBoxICAApplied")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.checkBoxICAApplied)
        self.labelRereferenced = QtWidgets.QLabel(self.groupBoxInfo)
        self.labelRereferenced.setObjectName("labelRereferenced")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.labelRereferenced)
        self.checkBoxRereferenced = QtWidgets.QCheckBox(self.groupBoxInfo)
        self.checkBoxRereferenced.setEnabled(False)
        self.checkBoxRereferenced.setText("")
        self.checkBoxRereferenced.setObjectName("checkBoxRereferenced")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.checkBoxRereferenced)
        self.labelMaxfiltered = QtWidgets.QLabel(self.groupBoxInfo)
        self.labelMaxfiltered.setObjectName("labelMaxfiltered")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.labelMaxfiltered)
        self.checkBoxMaxfiltered = QtWidgets.QCheckBox(self.groupBoxInfo)
        self.checkBoxMaxfiltered.setEnabled(False)
        self.checkBoxMaxfiltered.setText("")
        self.checkBoxMaxfiltered.setObjectName("checkBoxMaxfiltered")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.checkBoxMaxfiltered)
        self.gridLayout_2.addWidget(self.groupBoxInfo, 3, 0, 1, 1)
        self.groupBoxEvents = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxEvents.setObjectName("groupBoxEvents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxEvents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textBrowserEvents = QtWidgets.QTextBrowser(self.groupBoxEvents)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserEvents.setPalette(palette)
        self.textBrowserEvents.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowserEvents.setObjectName("textBrowserEvents")
        self.gridLayout_4.addWidget(self.textBrowserEvents, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxEvents, 4, 0, 1, 1)
        self.scrollAreaLeft.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollAreaLeft, 0, 0, 3, 1)
        self.scrollAreaRight = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollAreaRight.setWidgetResizable(True)
        self.scrollAreaRight.setObjectName("scrollAreaRight")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 800, 700))
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(800, 700))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(200, 400))
        self.tabWidget.setMaximumSize(QtCore.QSize(20000, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.scrollAreaRight.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollAreaRight, 0, 1, 1, 1)
        self.textEditConsole = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditConsole.setMinimumSize(QtCore.QSize(0, 100))
        self.textEditConsole.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textEditConsole.setObjectName("textEditConsole")
        self.gridLayout.addWidget(self.textEditConsole, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 928, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCreateExperiment = QtWidgets.QAction(MainWindow)
        self.actionCreateExperiment.setObjectName("actionCreateExperiment")
        self.actionOpenExperiment = QtWidgets.QAction(MainWindow)
        self.actionOpenExperiment.setObjectName("actionOpenExperiment")
        self.actionShowExperimentInfo = QtWidgets.QAction(MainWindow)
        self.actionShowExperimentInfo.setObjectName("actionShowExperimentInfo")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionShowLog = QtWidgets.QAction(MainWindow)
        self.actionShowLog.setObjectName("actionShowLog")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionCreateExperiment)
        self.menuFile.addAction(self.actionOpenExperiment)
        self.menuFile.addAction(self.actionShowExperimentInfo)
        self.menuFile.addAction(self.actionQuit)
        self.menuTools.addAction(self.actionShowLog)
        self.menuTools.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBoxSubjects.setTitle(_translate("MainWindow", "Subjects (active in bold):"))
        self.pushButtonActivateSubject.setText(_translate("MainWindow", "Activate selected"))
        self.pushButtonAddSubjects.setText(_translate("MainWindow", "Add new..."))
        self.pushButtonRemoveSubject.setText(_translate("MainWindow", "Remove selected"))
        self.pushButtonLayout.setText(_translate("MainWindow", "Change layout..."))
        self.groupBoxInfo.setTitle(_translate("MainWindow", "Info"))
        self.labelSubject.setText(_translate("MainWindow", "Name:"))
        self.labelDate.setText(_translate("MainWindow", "Date:"))
        self.labelLength.setText(_translate("MainWindow", "Length:"))
        self.labelSamples.setText(_translate("MainWindow", "Sampling frequency:"))
        self.labelLow.setText(_translate("MainWindow", "Low-pass:"))
        self.labelHigh.setText(_translate("MainWindow", "High-pass:"))
        self.labelICAApplied.setText(_translate("MainWindow", "ICA applied:"))
        self.labelRereferenced.setText(_translate("MainWindow", "Rereferenced:"))
        self.labelMaxfiltered.setText(_translate("MainWindow", "Maxfiltered:"))
        self.groupBoxEvents.setTitle(_translate("MainWindow", "Events"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionCreateExperiment.setText(_translate("MainWindow", "Create new experiment..."))
        self.actionOpenExperiment.setText(_translate("MainWindow", "Open experiment..."))
        self.actionShowExperimentInfo.setText(_translate("MainWindow", "Show experiment info..."))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionShowLog.setText(_translate("MainWindow", "Show log..."))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences..."))
        self.actionAbout.setText(_translate("MainWindow", "About..."))

