# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stcFreqDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_stcFreqDialog(object):
    def setupUi(self, stcFreqDialog):
        stcFreqDialog.setObjectName(_fromUtf8("stcFreqDialog"))
        stcFreqDialog.resize(625, 404)
        self.gridLayout = QtGui.QGridLayout(stcFreqDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.listWidgetStcs = QtGui.QListWidget(stcFreqDialog)
        self.listWidgetStcs.setObjectName(_fromUtf8("listWidgetStcs"))
        self.gridLayout.addWidget(self.listWidgetStcs, 0, 0, 1, 1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.fminLabel = QtGui.QLabel(stcFreqDialog)
        self.fminLabel.setObjectName(_fromUtf8("fminLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.fminLabel)
        self.doubleSpinBoxFmin = QtGui.QDoubleSpinBox(stcFreqDialog)
        self.doubleSpinBoxFmin.setProperty("value", 5.0)
        self.doubleSpinBoxFmin.setObjectName(_fromUtf8("doubleSpinBoxFmin"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxFmin)
        self.fmaxLabel = QtGui.QLabel(stcFreqDialog)
        self.fmaxLabel.setObjectName(_fromUtf8("fmaxLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.fmaxLabel)
        self.doubleSpinBoxFmax = QtGui.QDoubleSpinBox(stcFreqDialog)
        self.doubleSpinBoxFmax.setProperty("value", 30.0)
        self.doubleSpinBoxFmax.setObjectName(_fromUtf8("doubleSpinBoxFmax"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxFmax)
        self.freqIntervalLabel = QtGui.QLabel(stcFreqDialog)
        self.freqIntervalLabel.setObjectName(_fromUtf8("freqIntervalLabel"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.freqIntervalLabel)
        self.doubleSpinBoxInterval = QtGui.QDoubleSpinBox(stcFreqDialog)
        self.doubleSpinBoxInterval.setMinimum(1.0)
        self.doubleSpinBoxInterval.setProperty("value", 3.0)
        self.doubleSpinBoxInterval.setObjectName(_fromUtf8("doubleSpinBoxInterval"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxInterval)
        self.tminLabel = QtGui.QLabel(stcFreqDialog)
        self.tminLabel.setObjectName(_fromUtf8("tminLabel"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.tminLabel)
        self.doubleSpinBoxTmin = QtGui.QDoubleSpinBox(stcFreqDialog)
        self.doubleSpinBoxTmin.setMinimum(-2.0)
        self.doubleSpinBoxTmin.setSingleStep(0.1)
        self.doubleSpinBoxTmin.setObjectName(_fromUtf8("doubleSpinBoxTmin"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxTmin)
        self.tmaxLabel = QtGui.QLabel(stcFreqDialog)
        self.tmaxLabel.setObjectName(_fromUtf8("tmaxLabel"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.tmaxLabel)
        self.doubleSpinBoxTmax = QtGui.QDoubleSpinBox(stcFreqDialog)
        self.doubleSpinBoxTmax.setSingleStep(0.1)
        self.doubleSpinBoxTmax.setProperty("value", 0.5)
        self.doubleSpinBoxTmax.setObjectName(_fromUtf8("doubleSpinBoxTmax"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxTmax)
        self.hemisphereLabel = QtGui.QLabel(stcFreqDialog)
        self.hemisphereLabel.setObjectName(_fromUtf8("hemisphereLabel"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.hemisphereLabel)
        self.comboBoxHemisphere = QtGui.QComboBox(stcFreqDialog)
        self.comboBoxHemisphere.setObjectName(_fromUtf8("comboBoxHemisphere"))
        self.comboBoxHemisphere.addItem(_fromUtf8(""))
        self.comboBoxHemisphere.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.comboBoxHemisphere)
        self.gridLayout.addLayout(self.formLayout_2, 0, 1, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radioButtonFixed = QtGui.QRadioButton(stcFreqDialog)
        self.radioButtonFixed.setChecked(True)
        self.radioButtonFixed.setObjectName(_fromUtf8("radioButtonFixed"))
        self.buttonGroup = QtGui.QButtonGroup(stcFreqDialog)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButtonFixed)
        self.horizontalLayout.addWidget(self.radioButtonFixed)
        self.ncyclesLabel = QtGui.QLabel(stcFreqDialog)
        self.ncyclesLabel.setObjectName(_fromUtf8("ncyclesLabel"))
        self.horizontalLayout.addWidget(self.ncyclesLabel)
        self.doubleSpinBoxNcycles = QtGui.QDoubleSpinBox(stcFreqDialog)
        self.doubleSpinBoxNcycles.setMinimum(1.0)
        self.doubleSpinBoxNcycles.setMaximum(100.0)
        self.doubleSpinBoxNcycles.setProperty("value", 7.0)
        self.doubleSpinBoxNcycles.setObjectName(_fromUtf8("doubleSpinBoxNcycles"))
        self.horizontalLayout.addWidget(self.doubleSpinBoxNcycles)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.radioButtonAdapted = QtGui.QRadioButton(stcFreqDialog)
        self.radioButtonAdapted.setObjectName(_fromUtf8("radioButtonAdapted"))
        self.buttonGroup.addButton(self.radioButtonAdapted)
        self.horizontalLayout_2.addWidget(self.radioButtonAdapted)
        self.label = QtGui.QLabel(stcFreqDialog)
        self.label.setEnabled(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.doubleSpinBoxCycleFactor = QtGui.QDoubleSpinBox(stcFreqDialog)
        self.doubleSpinBoxCycleFactor.setEnabled(False)
        self.doubleSpinBoxCycleFactor.setMinimum(0.01)
        self.doubleSpinBoxCycleFactor.setMaximum(2.0)
        self.doubleSpinBoxCycleFactor.setSingleStep(0.1)
        self.doubleSpinBoxCycleFactor.setProperty("value", 0.5)
        self.doubleSpinBoxCycleFactor.setObjectName(_fromUtf8("doubleSpinBoxCycleFactor"))
        self.horizontalLayout_2.addWidget(self.doubleSpinBoxCycleFactor)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(stcFreqDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(stcFreqDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)

        self.retranslateUi(stcFreqDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), stcFreqDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), stcFreqDialog.reject)
        QtCore.QObject.connect(self.radioButtonFixed, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ncyclesLabel.setEnabled)
        QtCore.QObject.connect(self.radioButtonFixed, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBoxNcycles.setEnabled)
        QtCore.QObject.connect(self.radioButtonAdapted, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label.setEnabled)
        QtCore.QObject.connect(self.radioButtonAdapted, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBoxCycleFactor.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(stcFreqDialog)
        stcFreqDialog.setTabOrder(self.listWidgetStcs, self.doubleSpinBoxFmin)
        stcFreqDialog.setTabOrder(self.doubleSpinBoxFmin, self.doubleSpinBoxFmax)
        stcFreqDialog.setTabOrder(self.doubleSpinBoxFmax, self.doubleSpinBoxInterval)
        stcFreqDialog.setTabOrder(self.doubleSpinBoxInterval, self.doubleSpinBoxTmin)
        stcFreqDialog.setTabOrder(self.doubleSpinBoxTmin, self.doubleSpinBoxTmax)
        stcFreqDialog.setTabOrder(self.doubleSpinBoxTmax, self.comboBoxHemisphere)
        stcFreqDialog.setTabOrder(self.comboBoxHemisphere, self.radioButtonFixed)
        stcFreqDialog.setTabOrder(self.radioButtonFixed, self.doubleSpinBoxNcycles)
        stcFreqDialog.setTabOrder(self.doubleSpinBoxNcycles, self.radioButtonAdapted)
        stcFreqDialog.setTabOrder(self.radioButtonAdapted, self.doubleSpinBoxCycleFactor)
        stcFreqDialog.setTabOrder(self.doubleSpinBoxCycleFactor, self.buttonBox)

    def retranslateUi(self, stcFreqDialog):
        stcFreqDialog.setWindowTitle(_translate("stcFreqDialog", "Frequency analysis", None))
        self.fminLabel.setText(_translate("stcFreqDialog", "fmin", None))
        self.doubleSpinBoxFmin.setSuffix(_translate("stcFreqDialog", "Hz", None))
        self.fmaxLabel.setText(_translate("stcFreqDialog", "fmax", None))
        self.doubleSpinBoxFmax.setSuffix(_translate("stcFreqDialog", "Hz", None))
        self.freqIntervalLabel.setText(_translate("stcFreqDialog", "freq interval", None))
        self.tminLabel.setText(_translate("stcFreqDialog", "tmin", None))
        self.doubleSpinBoxTmin.setSuffix(_translate("stcFreqDialog", "s", None))
        self.tmaxLabel.setText(_translate("stcFreqDialog", "tmax", None))
        self.doubleSpinBoxTmax.setSuffix(_translate("stcFreqDialog", "s", None))
        self.hemisphereLabel.setText(_translate("stcFreqDialog", "hemisphere", None))
        self.comboBoxHemisphere.setItemText(0, _translate("stcFreqDialog", "left", None))
        self.comboBoxHemisphere.setItemText(1, _translate("stcFreqDialog", "right", None))
        self.radioButtonFixed.setText(_translate("stcFreqDialog", "Fixed", None))
        self.ncyclesLabel.setText(_translate("stcFreqDialog", "ncycles", None))
        self.radioButtonAdapted.setToolTip(_translate("stcFreqDialog", "<html><head/><body><p>You can define different number of cycles for each frequency of interest. The defined factor is multiplied by the frequency in hertz to get the number of cycles (ncycles = freq * factor). For instance, with a factor of 0.5, frequencies of 2, 4 and 6 tranlslate to morlet wavelets with cycles of 1, 2 and 3.</p></body></html>", None))
        self.radioButtonAdapted.setText(_translate("stcFreqDialog", "Adapted", None))
        self.label.setToolTip(_translate("stcFreqDialog", "<html><head/><body><p>You can define different number of cycles for each frequency of interest. The defined factor is multiplied by the frequency in hertz to get the number of cycles (ncycles = freq * factor). For instance, with a factor of 0.5, frequencies of 2, 4 and 6 tranlslate to morlet wavelets with cycles of 1, 2 and 3.</p></body></html>", None))
        self.label.setText(_translate("stcFreqDialog", "cycles / freq", None))
        self.doubleSpinBoxCycleFactor.setToolTip(_translate("stcFreqDialog", "<html><head/><body><p>You can define different number of cycles for each frequency of interest. The defined factor is multiplied by the frequency in hertz to get the number of cycles (ncycles = freq * factor). For instance, with a factor of 0.5, frequencies of 2, 4 and 6 tranlslate to morlet wavelets with cycles of 1, 2 and 3.</p></body></html>", None))
        self.label_2.setText(_translate("stcFreqDialog", "Clicking \'OK\' will plot the average TFR over all epoch \n"
"source estimates. Click on the desired frequency \n"
"in the plot to show the power on the surfaces.", None))

