# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer_ui_files/lcmvDialogUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_lcmvDialog(object):
    def setupUi(self, lcmvDialog):
        lcmvDialog.setObjectName("lcmvDialog")
        lcmvDialog.resize(587, 529)
        lcmvDialog.setModal(True)
        self.formLayout_3 = QtWidgets.QFormLayout(lcmvDialog)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelSourceEstimateName = QtWidgets.QLabel(lcmvDialog)
        self.labelSourceEstimateName.setObjectName("labelSourceEstimateName")
        self.horizontalLayout_6.addWidget(self.labelSourceEstimateName)
        self.lineEditSourceEstimateName = QtWidgets.QLineEdit(lcmvDialog)
        self.lineEditSourceEstimateName.setObjectName("lineEditSourceEstimateName")
        self.horizontalLayout_6.addWidget(self.lineEditSourceEstimateName)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelBasedOn = QtWidgets.QLabel(lcmvDialog)
        self.labelBasedOn.setObjectName("labelBasedOn")
        self.horizontalLayout.addWidget(self.labelBasedOn)
        self.lineEditBasedOn = QtWidgets.QLineEdit(lcmvDialog)
        self.lineEditBasedOn.setEnabled(False)
        self.lineEditBasedOn.setObjectName("lineEditBasedOn")
        self.horizontalLayout.addWidget(self.lineEditBasedOn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelData = QtWidgets.QLabel(lcmvDialog)
        self.labelData.setObjectName("labelData")
        self.horizontalLayout_8.addWidget(self.labelData)
        self.lineEditData = QtWidgets.QLineEdit(lcmvDialog)
        self.lineEditData.setEnabled(False)
        self.lineEditData.setObjectName("lineEditData")
        self.horizontalLayout_8.addWidget(self.lineEditData)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout)
        self.covarianceParameters = QtWidgets.QGroupBox(lcmvDialog)
        self.covarianceParameters.setObjectName("covarianceParameters")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.covarianceParameters)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.labelNoiseCovariance = QtWidgets.QLabel(self.covarianceParameters)
        self.labelNoiseCovariance.setObjectName("labelNoiseCovariance")
        self.horizontalLayout_9.addWidget(self.labelNoiseCovariance)
        self.comboBoxNoiseCovariance = QtWidgets.QComboBox(self.covarianceParameters)
        self.comboBoxNoiseCovariance.setObjectName("comboBoxNoiseCovariance")
        self.horizontalLayout_9.addWidget(self.comboBoxNoiseCovariance)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelDataCovariance = QtWidgets.QLabel(self.covarianceParameters)
        self.labelDataCovariance.setObjectName("labelDataCovariance")
        self.horizontalLayout_2.addWidget(self.labelDataCovariance)
        self.comboBoxDataCovariance = QtWidgets.QComboBox(self.covarianceParameters)
        self.comboBoxDataCovariance.setObjectName("comboBoxDataCovariance")
        self.horizontalLayout_2.addWidget(self.comboBoxDataCovariance)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.covarianceParameters)
        self.buttonBox = QtWidgets.QDialogButtonBox(lcmvDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.buttonBox)
        self.groupBoxStcParameters = QtWidgets.QGroupBox(lcmvDialog)
        self.groupBoxStcParameters.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBoxStcParameters.setObjectName("groupBoxStcParameters")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxStcParameters)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelReg = QtWidgets.QLabel(self.groupBoxStcParameters)
        self.labelReg.setObjectName("labelReg")
        self.horizontalLayout_4.addWidget(self.labelReg)
        self.doubleSpinBoxReg = QtWidgets.QDoubleSpinBox(self.groupBoxStcParameters)
        self.doubleSpinBoxReg.setSingleStep(0.05)
        self.doubleSpinBoxReg.setProperty("value", 0.05)
        self.doubleSpinBoxReg.setObjectName("doubleSpinBoxReg")
        self.horizontalLayout_4.addWidget(self.doubleSpinBoxReg)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.groupBoxStcParameters)
        self.groupBoxTimeParameters = QtWidgets.QGroupBox(lcmvDialog)
        self.groupBoxTimeParameters.setEnabled(False)
        self.groupBoxTimeParameters.setObjectName("groupBoxTimeParameters")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxTimeParameters)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.labelStart = QtWidgets.QLabel(self.groupBoxTimeParameters)
        self.labelStart.setObjectName("labelStart")
        self.horizontalLayout_11.addWidget(self.labelStart)
        self.doubleSpinBoxStart = QtWidgets.QDoubleSpinBox(self.groupBoxTimeParameters)
        self.doubleSpinBoxStart.setEnabled(False)
        self.doubleSpinBoxStart.setMaximum(9999.0)
        self.doubleSpinBoxStart.setObjectName("doubleSpinBoxStart")
        self.horizontalLayout_11.addWidget(self.doubleSpinBoxStart)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.labelEnd = QtWidgets.QLabel(self.groupBoxTimeParameters)
        self.labelEnd.setObjectName("labelEnd")
        self.horizontalLayout_10.addWidget(self.labelEnd)
        self.doubleSpinBoxEnd = QtWidgets.QDoubleSpinBox(self.groupBoxTimeParameters)
        self.doubleSpinBoxEnd.setEnabled(False)
        self.doubleSpinBoxEnd.setMaximum(9999.0)
        self.doubleSpinBoxEnd.setObjectName("doubleSpinBoxEnd")
        self.horizontalLayout_10.addWidget(self.doubleSpinBoxEnd)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.groupBoxTimeParameters)

        self.retranslateUi(lcmvDialog)
        self.buttonBox.accepted.connect(lcmvDialog.accept)
        self.buttonBox.rejected.connect(lcmvDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(lcmvDialog)

    def retranslateUi(self, lcmvDialog):
        _translate = QtCore.QCoreApplication.translate
        lcmvDialog.setWindowTitle(_translate("lcmvDialog", "Create new beamformer estimate"))
        self.labelSourceEstimateName.setText(_translate("lcmvDialog", "Source estimate name:"))
        self.labelBasedOn.setText(_translate("lcmvDialog", "Based on forward solution:"))
        self.labelData.setText(_translate("lcmvDialog", "Based on dataset:"))
        self.covarianceParameters.setTitle(_translate("lcmvDialog", "Covariance parameters"))
        self.labelNoiseCovariance.setText(_translate("lcmvDialog", "Noise covariance:"))
        self.labelDataCovariance.setText(_translate("lcmvDialog", "Data covariance:"))
        self.groupBoxStcParameters.setTitle(_translate("lcmvDialog", "Source estimate parameters:"))
        self.labelReg.setText(_translate("lcmvDialog", "Regularization parameter:"))
        self.groupBoxTimeParameters.setTitle(_translate("lcmvDialog", "Time parameters (only for raw data)"))
        self.labelStart.setText(_translate("lcmvDialog", "Start:"))
        self.labelEnd.setText(_translate("lcmvDialog", "End:"))

