# Form implementation generated from reading ui file './meggie/mainwindow/dialogs/activePluginsDialogUi.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_activePluginsDialog(object):
    def setupUi(self, activePluginsDialog):
        activePluginsDialog.setObjectName("activePluginsDialog")
        activePluginsDialog.resize(414, 176)
        self.gridLayout = QtWidgets.QGridLayout(activePluginsDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidgetPlugins = QtWidgets.QListWidget(parent=activePluginsDialog)
        self.listWidgetPlugins.setDragDropMode(
            QtWidgets.QAbstractItemView.DragDropMode.InternalMove
        )
        self.listWidgetPlugins.setDefaultDropAction(QtCore.Qt.DropAction.IgnoreAction)
        self.listWidgetPlugins.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.MultiSelection
        )
        self.listWidgetPlugins.setObjectName("listWidgetPlugins")
        self.gridLayout.addWidget(self.listWidgetPlugins, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonCancel = QtWidgets.QPushButton(parent=activePluginsDialog)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.pushButtonAccept = QtWidgets.QPushButton(parent=activePluginsDialog)
        self.pushButtonAccept.setObjectName("pushButtonAccept")
        self.horizontalLayout.addWidget(self.pushButtonAccept)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(activePluginsDialog)
        self.pushButtonAccept.clicked.connect(activePluginsDialog.accept)  # type: ignore
        self.pushButtonCancel.clicked.connect(activePluginsDialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(activePluginsDialog)
        activePluginsDialog.setTabOrder(self.listWidgetPlugins, self.pushButtonCancel)
        activePluginsDialog.setTabOrder(self.pushButtonCancel, self.pushButtonAccept)

    def retranslateUi(self, activePluginsDialog):
        _translate = QtCore.QCoreApplication.translate
        activePluginsDialog.setWindowTitle(
            _translate("activePluginsDialog", "Meggie - Active plugins")
        )
        self.pushButtonCancel.setText(_translate("activePluginsDialog", "Cancel"))
        self.pushButtonAccept.setText(_translate("activePluginsDialog", "Accept"))
