# Form implementation generated from reading ui file './meggie/mainwindow/dialogs/preferencesDialogUi.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_DialogPreferences(object):
    def setupUi(self, DialogPreferences):
        DialogPreferences.setObjectName("DialogPreferences")
        DialogPreferences.resize(507, 482)
        self.gridLayout_3 = QtWidgets.QGridLayout(DialogPreferences)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButtonCancel = QtWidgets.QPushButton(parent=DialogPreferences)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_2.addWidget(self.pushButtonCancel)
        self.pushButtonAccept = QtWidgets.QPushButton(parent=DialogPreferences)
        self.pushButtonAccept.setObjectName("pushButtonAccept")
        self.horizontalLayout_2.addWidget(self.pushButtonAccept)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(parent=DialogPreferences)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 487, 431))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBoxMisc = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBoxMisc.setObjectName("groupBoxMisc")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxMisc)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBoxAutomaticOpenPreviousExperiment = QtWidgets.QCheckBox(
            parent=self.groupBoxMisc
        )
        self.checkBoxAutomaticOpenPreviousExperiment.setObjectName(
            "checkBoxAutomaticOpenPreviousExperiment"
        )
        self.gridLayout_4.addWidget(
            self.checkBoxAutomaticOpenPreviousExperiment, 0, 0, 1, 1
        )
        self.gridLayout_5.addWidget(self.groupBoxMisc, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.gridLayout_5.addItem(spacerItem1, 3, 0, 1, 1)
        self.groupBoxWorkspace = QtWidgets.QGroupBox(
            parent=self.scrollAreaWidgetContents
        )
        self.groupBoxWorkspace.setObjectName("groupBoxWorkspace")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxWorkspace)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LineEditFilePath = QtWidgets.QLineEdit(parent=self.groupBoxWorkspace)
        self.LineEditFilePath.setObjectName("LineEditFilePath")
        self.gridLayout_2.addWidget(self.LineEditFilePath, 0, 0, 1, 1)
        self.ButtonBrowseWorkingDir = QtWidgets.QPushButton(
            parent=self.groupBoxWorkspace
        )
        self.ButtonBrowseWorkingDir.setObjectName("ButtonBrowseWorkingDir")
        self.gridLayout_2.addWidget(self.ButtonBrowseWorkingDir, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBoxWorkspace, 0, 0, 1, 1)
        self.groupBoxPlugins = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBoxPlugins.setObjectName("groupBoxPlugins")
        self.formLayout = QtWidgets.QFormLayout(self.groupBoxPlugins)
        self.formLayout.setObjectName("formLayout")
        self.pushButtonPlugins = QtWidgets.QPushButton(parent=self.groupBoxPlugins)
        self.pushButtonPlugins.setObjectName("pushButtonPlugins")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.pushButtonPlugins
        )
        self.gridLayout_5.addWidget(self.groupBoxPlugins, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(DialogPreferences)
        self.pushButtonCancel.clicked.connect(DialogPreferences.reject)  # type: ignore
        self.pushButtonAccept.clicked.connect(DialogPreferences.accept)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogPreferences)

    def retranslateUi(self, DialogPreferences):
        _translate = QtCore.QCoreApplication.translate
        DialogPreferences.setWindowTitle(
            _translate("DialogPreferences", "Meggie - Preferences")
        )
        self.pushButtonCancel.setText(_translate("DialogPreferences", "Cancel"))
        self.pushButtonAccept.setText(_translate("DialogPreferences", "Ok"))
        self.groupBoxMisc.setTitle(_translate("DialogPreferences", "Miscellaneous:"))
        self.checkBoxAutomaticOpenPreviousExperiment.setText(
            _translate(
                "DialogPreferences",
                "Automatically open previous experiment upon application startup",
            )
        )
        self.groupBoxWorkspace.setTitle(_translate("DialogPreferences", "Workspace:"))
        self.ButtonBrowseWorkingDir.setText(
            _translate("DialogPreferences", "Browse...")
        )
        self.groupBoxPlugins.setTitle(_translate("DialogPreferences", "Plugins:"))
        self.pushButtonPlugins.setText(
            _translate("DialogPreferences", "Select active plugins...")
        )
