# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kari/Opinnot/gradu/lahdekoodit/lahdekoodit/meggie_batch/ui/qt4Designer_ui_files/covarianceWidgetRaw.ui'
#
# Created: Fri Jan 30 16:18:42 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_covarianceRawWidget(object):
    def setupUi(self, covarianceRawWidget):
        covarianceRawWidget.setObjectName(_fromUtf8("covarianceRawWidget"))
        covarianceRawWidget.resize(600, 587)
        covarianceRawWidget.setMaximumSize(QtCore.QSize(600, 800))
        self.gridLayout_2 = QtGui.QGridLayout(covarianceRawWidget)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(covarianceRawWidget)
        self.groupBox_3.setMaximumSize(QtCore.QSize(600, 800))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.groupBoxEpochTimes_2 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBoxEpochTimes_2.setObjectName(_fromUtf8("groupBoxEpochTimes_2"))
        self.formLayout_16 = QtGui.QFormLayout(self.groupBoxEpochTimes_2)
        self.formLayout_16.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_16.setObjectName(_fromUtf8("formLayout_16"))
        self.labelTminCovariance = QtGui.QLabel(self.groupBoxEpochTimes_2)
        self.labelTminCovariance.setMinimumSize(QtCore.QSize(80, 0))
        self.labelTminCovariance.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelTminCovariance.setObjectName(_fromUtf8("labelTminCovariance"))
        self.formLayout_16.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelTminCovariance)
        self.textBrowserTmin = QtGui.QTextBrowser(self.groupBoxEpochTimes_2)
        self.textBrowserTmin.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserTmin.sizePolicy().hasHeightForWidth())
        self.textBrowserTmin.setSizePolicy(sizePolicy)
        self.textBrowserTmin.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowserTmin.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textBrowserTmin.setSizeIncrement(QtCore.QSize(0, 31))
        self.textBrowserTmin.setBaseSize(QtCore.QSize(0, 0))
        self.textBrowserTmin.setFrameShape(QtGui.QFrame.StyledPanel)
        self.textBrowserTmin.setObjectName(_fromUtf8("textBrowserTmin"))
        self.formLayout_16.setWidget(1, QtGui.QFormLayout.FieldRole, self.textBrowserTmin)
        self.labelTmaxCovariance = QtGui.QLabel(self.groupBoxEpochTimes_2)
        self.labelTmaxCovariance.setMinimumSize(QtCore.QSize(80, 0))
        self.labelTmaxCovariance.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelTmaxCovariance.setObjectName(_fromUtf8("labelTmaxCovariance"))
        self.formLayout_16.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelTmaxCovariance)
        self.textBrowserTmax = QtGui.QTextBrowser(self.groupBoxEpochTimes_2)
        self.textBrowserTmax.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserTmax.sizePolicy().hasHeightForWidth())
        self.textBrowserTmax.setSizePolicy(sizePolicy)
        self.textBrowserTmax.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowserTmax.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textBrowserTmax.setSizeIncrement(QtCore.QSize(0, 31))
        self.textBrowserTmax.setObjectName(_fromUtf8("textBrowserTmax"))
        self.formLayout_16.setWidget(2, QtGui.QFormLayout.FieldRole, self.textBrowserTmax)
        self.labelTimeStep = QtGui.QLabel(self.groupBoxEpochTimes_2)
        self.labelTimeStep.setObjectName(_fromUtf8("labelTimeStep"))
        self.formLayout_16.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelTimeStep)
        self.textBrowserTstep = QtGui.QTextBrowser(self.groupBoxEpochTimes_2)
        self.textBrowserTstep.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textBrowserTstep.setObjectName(_fromUtf8("textBrowserTstep"))
        self.formLayout_16.setWidget(3, QtGui.QFormLayout.FieldRole, self.textBrowserTstep)
        self.formLayout.setWidget(1, QtGui.QFormLayout.SpanningRole, self.groupBoxEpochTimes_2)
        self.groupBoxRejections_2 = QtGui.QGroupBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxRejections_2.sizePolicy().hasHeightForWidth())
        self.groupBoxRejections_2.setSizePolicy(sizePolicy)
        self.groupBoxRejections_2.setMaximumSize(QtCore.QSize(1000, 231))
        self.groupBoxRejections_2.setObjectName(_fromUtf8("groupBoxRejections_2"))
        self.gridLayout_26 = QtGui.QGridLayout(self.groupBoxRejections_2)
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.labelEogRejectCovariance = QtGui.QLabel(self.groupBoxRejections_2)
        self.labelEogRejectCovariance.setMinimumSize(QtCore.QSize(75, 0))
        self.labelEogRejectCovariance.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelEogRejectCovariance.setObjectName(_fromUtf8("labelEogRejectCovariance"))
        self.gridLayout_26.addWidget(self.labelEogRejectCovariance, 4, 1, 1, 1)
        self.textBrowserFlatEOG = QtGui.QTextBrowser(self.groupBoxRejections_2)
        self.textBrowserFlatEOG.setObjectName(_fromUtf8("textBrowserFlatEOG"))
        self.gridLayout_26.addWidget(self.textBrowserFlatEOG, 4, 3, 1, 1)
        self.textBrowserFlatEEG = QtGui.QTextBrowser(self.groupBoxRejections_2)
        self.textBrowserFlatEEG.setObjectName(_fromUtf8("textBrowserFlatEEG"))
        self.gridLayout_26.addWidget(self.textBrowserFlatEEG, 3, 3, 1, 1)
        self.textBrowserEEGPeakCovariance = QtGui.QTextBrowser(self.groupBoxRejections_2)
        self.textBrowserEEGPeakCovariance.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textBrowserEEGPeakCovariance.setObjectName(_fromUtf8("textBrowserEEGPeakCovariance"))
        self.gridLayout_26.addWidget(self.textBrowserEEGPeakCovariance, 3, 2, 1, 1)
        self.labelStimReject_2 = QtGui.QLabel(self.groupBoxRejections_2)
        self.labelStimReject_2.setMinimumSize(QtCore.QSize(75, 0))
        self.labelStimReject_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelStimReject_2.setObjectName(_fromUtf8("labelStimReject_2"))
        self.gridLayout_26.addWidget(self.labelStimReject_2, 5, 1, 1, 1)
        self.textBrowserEOGPeakCovariance = QtGui.QTextBrowser(self.groupBoxRejections_2)
        self.textBrowserEOGPeakCovariance.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textBrowserEOGPeakCovariance.setObjectName(_fromUtf8("textBrowserEOGPeakCovariance"))
        self.gridLayout_26.addWidget(self.textBrowserEOGPeakCovariance, 4, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBoxRejections_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_26.addWidget(self.label_8, 0, 2, 1, 1)
        self.textBrowserFlatECG = QtGui.QTextBrowser(self.groupBoxRejections_2)
        self.textBrowserFlatECG.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textBrowserFlatECG.setObjectName(_fromUtf8("textBrowserFlatECG"))
        self.gridLayout_26.addWidget(self.textBrowserFlatECG, 5, 3, 1, 1)
        self.labelMagRejectCovariance = QtGui.QLabel(self.groupBoxRejections_2)
        self.labelMagRejectCovariance.setMinimumSize(QtCore.QSize(80, 0))
        self.labelMagRejectCovariance.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelMagRejectCovariance.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelMagRejectCovariance.setObjectName(_fromUtf8("labelMagRejectCovariance"))
        self.gridLayout_26.addWidget(self.labelMagRejectCovariance, 1, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBoxRejections_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_26.addWidget(self.label_15, 0, 3, 1, 1)
        self.labelEegRejectCovariance = QtGui.QLabel(self.groupBoxRejections_2)
        self.labelEegRejectCovariance.setMinimumSize(QtCore.QSize(75, 0))
        self.labelEegRejectCovariance.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelEegRejectCovariance.setObjectName(_fromUtf8("labelEegRejectCovariance"))
        self.gridLayout_26.addWidget(self.labelEegRejectCovariance, 3, 1, 1, 1)
        self.labelGradRejectCovariance = QtGui.QLabel(self.groupBoxRejections_2)
        self.labelGradRejectCovariance.setMinimumSize(QtCore.QSize(75, 0))
        self.labelGradRejectCovariance.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelGradRejectCovariance.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelGradRejectCovariance.setObjectName(_fromUtf8("labelGradRejectCovariance"))
        self.gridLayout_26.addWidget(self.labelGradRejectCovariance, 2, 1, 1, 1)
        self.textBrowserFlatGrad = QtGui.QTextBrowser(self.groupBoxRejections_2)
        self.textBrowserFlatGrad.setObjectName(_fromUtf8("textBrowserFlatGrad"))
        self.gridLayout_26.addWidget(self.textBrowserFlatGrad, 2, 3, 1, 1)
        self.textBrowserFlatMag = QtGui.QTextBrowser(self.groupBoxRejections_2)
        self.textBrowserFlatMag.setObjectName(_fromUtf8("textBrowserFlatMag"))
        self.gridLayout_26.addWidget(self.textBrowserFlatMag, 1, 3, 1, 1)
        self.textBrowserMagPeakCovariance = QtGui.QTextBrowser(self.groupBoxRejections_2)
        self.textBrowserMagPeakCovariance.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserMagPeakCovariance.sizePolicy().hasHeightForWidth())
        self.textBrowserMagPeakCovariance.setSizePolicy(sizePolicy)
        self.textBrowserMagPeakCovariance.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowserMagPeakCovariance.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textBrowserMagPeakCovariance.setSizeIncrement(QtCore.QSize(0, 31))
        self.textBrowserMagPeakCovariance.setFrameShadow(QtGui.QFrame.Sunken)
        self.textBrowserMagPeakCovariance.setObjectName(_fromUtf8("textBrowserMagPeakCovariance"))
        self.gridLayout_26.addWidget(self.textBrowserMagPeakCovariance, 1, 2, 1, 1)
        self.textBrowserGradPeakCovariance = QtGui.QTextBrowser(self.groupBoxRejections_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserGradPeakCovariance.sizePolicy().hasHeightForWidth())
        self.textBrowserGradPeakCovariance.setSizePolicy(sizePolicy)
        self.textBrowserGradPeakCovariance.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowserGradPeakCovariance.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textBrowserGradPeakCovariance.setObjectName(_fromUtf8("textBrowserGradPeakCovariance"))
        self.gridLayout_26.addWidget(self.textBrowserGradPeakCovariance, 2, 2, 1, 1)
        self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.groupBoxRejections_2)
        self.groupBoxPicks = QtGui.QGroupBox(self.groupBox_3)
        self.groupBoxPicks.setObjectName(_fromUtf8("groupBoxPicks"))
        self.gridLayout_30 = QtGui.QGridLayout(self.groupBoxPicks)
        self.gridLayout_30.setObjectName(_fromUtf8("gridLayout_30"))
        self.textBrowserPicks = QtGui.QTextBrowser(self.groupBoxPicks)
        self.textBrowserPicks.setObjectName(_fromUtf8("textBrowserPicks"))
        self.gridLayout_30.addWidget(self.textBrowserPicks, 0, 0, 1, 1)
        self.formLayout.setWidget(3, QtGui.QFormLayout.SpanningRole, self.groupBoxPicks)
        self.textBrowserBasedOn = QtGui.QTextBrowser(self.groupBox_3)
        self.textBrowserBasedOn.setMaximumSize(QtCore.QSize(10000, 29))
        self.textBrowserBasedOn.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowserBasedOn.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowserBasedOn.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textBrowserBasedOn.setLineWrapColumnOrWidth(0)
        self.textBrowserBasedOn.setObjectName(_fromUtf8("textBrowserBasedOn"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.textBrowserBasedOn)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)

        self.retranslateUi(covarianceRawWidget)
        QtCore.QMetaObject.connectSlotsByName(covarianceRawWidget)

    def retranslateUi(self, covarianceRawWidget):
        covarianceRawWidget.setWindowTitle(_translate("covarianceRawWidget", "Form", None))
        self.groupBox_3.setTitle(_translate("covarianceRawWidget", "Current covariance matrix info:", None))
        self.label_7.setText(_translate("covarianceRawWidget", "Based on:", None))
        self.groupBoxEpochTimes_2.setTitle(_translate("covarianceRawWidget", "Time limits:", None))
        self.labelTminCovariance.setText(_translate("covarianceRawWidget", "Start time:", None))
        self.labelTmaxCovariance.setText(_translate("covarianceRawWidget", "End time:", None))
        self.labelTimeStep.setText(_translate("covarianceRawWidget", "Time step (for rejection):", None))
        self.groupBoxRejections_2.setTitle(_translate("covarianceRawWidget", "Rejection parameters:", None))
        self.labelEogRejectCovariance.setText(_translate("covarianceRawWidget", "EOG:", None))
        self.labelStimReject_2.setText(_translate("covarianceRawWidget", "ECG:", None))
        self.label_8.setText(_translate("covarianceRawWidget", "Peak to peak amplitude:", None))
        self.labelMagRejectCovariance.setText(_translate("covarianceRawWidget", "Mag:", None))
        self.label_15.setText(_translate("covarianceRawWidget", "Signal flatness:", None))
        self.labelEegRejectCovariance.setText(_translate("covarianceRawWidget", "EEG:", None))
        self.labelGradRejectCovariance.setText(_translate("covarianceRawWidget", "Grad:", None))
        self.groupBoxPicks.setTitle(_translate("covarianceRawWidget", "Picks:", None))

