# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'powerSpectrumWidget.ui'
#
# Created: Fri Feb  6 07:14:51 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PowerSpectrumWidget(object):
    def setupUi(self, PowerSpectrumWidget):
        PowerSpectrumWidget.setObjectName(_fromUtf8("PowerSpectrumWidget"))
        PowerSpectrumWidget.resize(826, 102)
        self.gridLayout = QtGui.QGridLayout(PowerSpectrumWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelTmin = QtGui.QLabel(PowerSpectrumWidget)
        self.labelTmin.setObjectName(_fromUtf8("labelTmin"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelTmin)
        self.spinBoxTmin = QtGui.QSpinBox(PowerSpectrumWidget)
        self.spinBoxTmin.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBoxTmin.setMaximum(1000)
        self.spinBoxTmin.setObjectName(_fromUtf8("spinBoxTmin"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBoxTmin)
        self.labelTmax = QtGui.QLabel(PowerSpectrumWidget)
        self.labelTmax.setObjectName(_fromUtf8("labelTmax"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelTmax)
        self.spinBoxTmax = QtGui.QSpinBox(PowerSpectrumWidget)
        self.spinBoxTmax.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBoxTmax.setMaximum(1000)
        self.spinBoxTmax.setObjectName(_fromUtf8("spinBoxTmax"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBoxTmax)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 3, 1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelColor = QtGui.QLabel(PowerSpectrumWidget)
        self.labelColor.setObjectName(_fromUtf8("labelColor"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelColor)
        self.comboBoxColor = QtGui.QComboBox(PowerSpectrumWidget)
        self.comboBoxColor.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.comboBoxColor.setObjectName(_fromUtf8("comboBoxColor"))
        self.comboBoxColor.addItem(_fromUtf8(""))
        self.comboBoxColor.addItem(_fromUtf8(""))
        self.comboBoxColor.addItem(_fromUtf8(""))
        self.comboBoxColor.addItem(_fromUtf8(""))
        self.comboBoxColor.addItem(_fromUtf8(""))
        self.comboBoxColor.addItem(_fromUtf8(""))
        self.comboBoxColor.addItem(_fromUtf8(""))
        self.comboBoxColor.addItem(_fromUtf8(""))
        self.comboBoxColor.addItem(_fromUtf8(""))
        self.comboBoxColor.addItem(_fromUtf8(""))
        self.comboBoxColor.addItem(_fromUtf8(""))
        self.comboBoxColor.addItem(_fromUtf8(""))
        self.comboBoxColor.addItem(_fromUtf8(""))
        self.comboBoxColor.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxColor)
        self.gridLayout.addLayout(self.formLayout_2, 0, 1, 2, 1)
        self.line_2 = QtGui.QFrame(PowerSpectrumWidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 0, 2, 3, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.labelChannelColors = QtGui.QLabel(PowerSpectrumWidget)
        self.labelChannelColors.setObjectName(_fromUtf8("labelChannelColors"))
        self.verticalLayout.addWidget(self.labelChannelColors)
        self.listWidgetChannels = QtGui.QListWidget(PowerSpectrumWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetChannels.sizePolicy().hasHeightForWidth())
        self.listWidgetChannels.setSizePolicy(sizePolicy)
        self.listWidgetChannels.setMaximumSize(QtCore.QSize(16777215, 50))
        self.listWidgetChannels.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.listWidgetChannels.setFlow(QtGui.QListView.LeftToRight)
        self.listWidgetChannels.setObjectName(_fromUtf8("listWidgetChannels"))
        self.verticalLayout.addWidget(self.listWidgetChannels)
        self.gridLayout.addLayout(self.verticalLayout, 0, 3, 3, 1)
        self.comboBoxChannelColor = QtGui.QComboBox(PowerSpectrumWidget)
        self.comboBoxChannelColor.setEnabled(False)
        self.comboBoxChannelColor.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.comboBoxChannelColor.setObjectName(_fromUtf8("comboBoxChannelColor"))
        self.comboBoxChannelColor.addItem(_fromUtf8(""))
        self.comboBoxChannelColor.addItem(_fromUtf8(""))
        self.comboBoxChannelColor.addItem(_fromUtf8(""))
        self.comboBoxChannelColor.addItem(_fromUtf8(""))
        self.comboBoxChannelColor.addItem(_fromUtf8(""))
        self.comboBoxChannelColor.addItem(_fromUtf8(""))
        self.comboBoxChannelColor.addItem(_fromUtf8(""))
        self.comboBoxChannelColor.addItem(_fromUtf8(""))
        self.comboBoxChannelColor.addItem(_fromUtf8(""))
        self.comboBoxChannelColor.addItem(_fromUtf8(""))
        self.comboBoxChannelColor.addItem(_fromUtf8(""))
        self.comboBoxChannelColor.addItem(_fromUtf8(""))
        self.comboBoxChannelColor.addItem(_fromUtf8(""))
        self.comboBoxChannelColor.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxChannelColor, 0, 4, 2, 1)
        self.line_3 = QtGui.QFrame(PowerSpectrumWidget)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 0, 5, 3, 2)
        self.pushButtonRemove = QtGui.QPushButton(PowerSpectrumWidget)
        self.pushButtonRemove.setObjectName(_fromUtf8("pushButtonRemove"))
        self.gridLayout.addWidget(self.pushButtonRemove, 1, 6, 2, 1)
        self.pushButtonModify = QtGui.QPushButton(PowerSpectrumWidget)
        self.pushButtonModify.setObjectName(_fromUtf8("pushButtonModify"))
        self.gridLayout.addWidget(self.pushButtonModify, 2, 4, 1, 1)
        self.line = QtGui.QFrame(PowerSpectrumWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 3, 0, 1, 7)

        self.retranslateUi(PowerSpectrumWidget)
        self.comboBoxChannelColor.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PowerSpectrumWidget)
        PowerSpectrumWidget.setTabOrder(self.spinBoxTmin, self.spinBoxTmax)
        PowerSpectrumWidget.setTabOrder(self.spinBoxTmax, self.comboBoxColor)
        PowerSpectrumWidget.setTabOrder(self.comboBoxColor, self.listWidgetChannels)
        PowerSpectrumWidget.setTabOrder(self.listWidgetChannels, self.comboBoxChannelColor)
        PowerSpectrumWidget.setTabOrder(self.comboBoxChannelColor, self.pushButtonModify)
        PowerSpectrumWidget.setTabOrder(self.pushButtonModify, self.pushButtonRemove)

    def retranslateUi(self, PowerSpectrumWidget):
        PowerSpectrumWidget.setWindowTitle(_translate("PowerSpectrumWidget", "Form", None))
        self.labelTmin.setToolTip(_translate("PowerSpectrumWidget", "Set the starting time for this condition.", None))
        self.labelTmin.setText(_translate("PowerSpectrumWidget", "Start time:", None))
        self.spinBoxTmin.setToolTip(_translate("PowerSpectrumWidget", "Set the starting time for this condition.", None))
        self.spinBoxTmin.setSuffix(_translate("PowerSpectrumWidget", "s", None))
        self.labelTmax.setToolTip(_translate("PowerSpectrumWidget", "Set the ending time for this condition.", None))
        self.labelTmax.setText(_translate("PowerSpectrumWidget", "End time:", None))
        self.spinBoxTmax.setToolTip(_translate("PowerSpectrumWidget", "Set the ending time for this condition.", None))
        self.spinBoxTmax.setSuffix(_translate("PowerSpectrumWidget", "s", None))
        self.labelColor.setToolTip(_translate("PowerSpectrumWidget", "Set the color for this condition.", None))
        self.labelColor.setText(_translate("PowerSpectrumWidget", "Color:", None))
        self.comboBoxColor.setToolTip(_translate("PowerSpectrumWidget", "Set the color for this condition.", None))
        self.comboBoxColor.setItemText(0, _translate("PowerSpectrumWidget", "blue", None))
        self.comboBoxColor.setItemText(1, _translate("PowerSpectrumWidget", "green", None))
        self.comboBoxColor.setItemText(2, _translate("PowerSpectrumWidget", "red", None))
        self.comboBoxColor.setItemText(3, _translate("PowerSpectrumWidget", "cyan", None))
        self.comboBoxColor.setItemText(4, _translate("PowerSpectrumWidget", "magenta", None))
        self.comboBoxColor.setItemText(5, _translate("PowerSpectrumWidget", "yellow", None))
        self.comboBoxColor.setItemText(6, _translate("PowerSpectrumWidget", "black", None))
        self.comboBoxColor.setItemText(7, _translate("PowerSpectrumWidget", "white", None))
        self.comboBoxColor.setItemText(8, _translate("PowerSpectrumWidget", "grey", None))
        self.comboBoxColor.setItemText(9, _translate("PowerSpectrumWidget", "brown", None))
        self.comboBoxColor.setItemText(10, _translate("PowerSpectrumWidget", "orange", None))
        self.comboBoxColor.setItemText(11, _translate("PowerSpectrumWidget", "purple", None))
        self.comboBoxColor.setItemText(12, _translate("PowerSpectrumWidget", "magenta", None))
        self.comboBoxColor.setItemText(13, _translate("PowerSpectrumWidget", "pink", None))
        self.labelChannelColors.setToolTip(_translate("PowerSpectrumWidget", "Select specific channels to write to ASCII files. The channels can be shown in different color in the topology view.", None))
        self.labelChannelColors.setText(_translate("PowerSpectrumWidget", "Select channels of interest:", None))
        self.listWidgetChannels.setToolTip(_translate("PowerSpectrumWidget", "Select specific channels to write to ASCII files. The channels can be shown in different color in the topology view.", None))
        self.comboBoxChannelColor.setToolTip(_translate("PowerSpectrumWidget", "Color for the selected channels.", None))
        self.comboBoxChannelColor.setItemText(0, _translate("PowerSpectrumWidget", "blue", None))
        self.comboBoxChannelColor.setItemText(1, _translate("PowerSpectrumWidget", "green", None))
        self.comboBoxChannelColor.setItemText(2, _translate("PowerSpectrumWidget", "red", None))
        self.comboBoxChannelColor.setItemText(3, _translate("PowerSpectrumWidget", "cyan", None))
        self.comboBoxChannelColor.setItemText(4, _translate("PowerSpectrumWidget", "magenta", None))
        self.comboBoxChannelColor.setItemText(5, _translate("PowerSpectrumWidget", "yellow", None))
        self.comboBoxChannelColor.setItemText(6, _translate("PowerSpectrumWidget", "black", None))
        self.comboBoxChannelColor.setItemText(7, _translate("PowerSpectrumWidget", "white", None))
        self.comboBoxChannelColor.setItemText(8, _translate("PowerSpectrumWidget", "grey", None))
        self.comboBoxChannelColor.setItemText(9, _translate("PowerSpectrumWidget", "brown", None))
        self.comboBoxChannelColor.setItemText(10, _translate("PowerSpectrumWidget", "orange", None))
        self.comboBoxChannelColor.setItemText(11, _translate("PowerSpectrumWidget", "purple", None))
        self.comboBoxChannelColor.setItemText(12, _translate("PowerSpectrumWidget", "magenta", None))
        self.comboBoxChannelColor.setItemText(13, _translate("PowerSpectrumWidget", "pink", None))
        self.pushButtonRemove.setToolTip(_translate("PowerSpectrumWidget", "Remove this condition.", None))
        self.pushButtonRemove.setText(_translate("PowerSpectrumWidget", "Remove", None))
        self.pushButtonModify.setToolTip(_translate("PowerSpectrumWidget", "Add channels.", None))
        self.pushButtonModify.setText(_translate("PowerSpectrumWidget", "Modify...", None))

