# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bitSelectionDialogUi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(707, 127)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label = QtGui.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.labelID = QtGui.QLabel(Dialog)
        self.labelID.setText(_fromUtf8(""))
        self.labelID.setObjectName(_fromUtf8("labelID"))
        self.horizontalLayout_3.addWidget(self.labelID)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.labelMask = QtGui.QLabel(Dialog)
        self.labelMask.setText(_fromUtf8(""))
        self.labelMask.setObjectName(_fromUtf8("labelMask"))
        self.horizontalLayout_3.addWidget(self.labelMask)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton10 = QtGui.QPushButton(Dialog)
        self.pushButton10.setText(_fromUtf8(""))
        self.pushButton10.setObjectName(_fromUtf8("pushButton10"))
        self.horizontalLayout.addWidget(self.pushButton10)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.pushButton9 = QtGui.QPushButton(Dialog)
        self.pushButton9.setText(_fromUtf8(""))
        self.pushButton9.setObjectName(_fromUtf8("pushButton9"))
        self.horizontalLayout.addWidget(self.pushButton9)
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout.addWidget(self.line_2)
        self.pushButton8 = QtGui.QPushButton(Dialog)
        self.pushButton8.setText(_fromUtf8(""))
        self.pushButton8.setObjectName(_fromUtf8("pushButton8"))
        self.horizontalLayout.addWidget(self.pushButton8)
        self.line_3 = QtGui.QFrame(Dialog)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout.addWidget(self.line_3)
        self.pushButton7 = QtGui.QPushButton(Dialog)
        self.pushButton7.setText(_fromUtf8(""))
        self.pushButton7.setObjectName(_fromUtf8("pushButton7"))
        self.horizontalLayout.addWidget(self.pushButton7)
        self.line_4 = QtGui.QFrame(Dialog)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout.addWidget(self.line_4)
        self.pushButton6 = QtGui.QPushButton(Dialog)
        self.pushButton6.setText(_fromUtf8(""))
        self.pushButton6.setObjectName(_fromUtf8("pushButton6"))
        self.horizontalLayout.addWidget(self.pushButton6)
        self.line_5 = QtGui.QFrame(Dialog)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayout.addWidget(self.line_5)
        self.pushButton5 = QtGui.QPushButton(Dialog)
        self.pushButton5.setText(_fromUtf8(""))
        self.pushButton5.setObjectName(_fromUtf8("pushButton5"))
        self.horizontalLayout.addWidget(self.pushButton5)
        self.line_6 = QtGui.QFrame(Dialog)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.horizontalLayout.addWidget(self.line_6)
        self.pushButton4 = QtGui.QPushButton(Dialog)
        self.pushButton4.setText(_fromUtf8(""))
        self.pushButton4.setObjectName(_fromUtf8("pushButton4"))
        self.horizontalLayout.addWidget(self.pushButton4)
        self.line_7 = QtGui.QFrame(Dialog)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayout.addWidget(self.line_7)
        self.pushButton3 = QtGui.QPushButton(Dialog)
        self.pushButton3.setText(_fromUtf8(""))
        self.pushButton3.setObjectName(_fromUtf8("pushButton3"))
        self.horizontalLayout.addWidget(self.pushButton3)
        self.line_8 = QtGui.QFrame(Dialog)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.horizontalLayout.addWidget(self.line_8)
        self.pushButton2 = QtGui.QPushButton(Dialog)
        self.pushButton2.setText(_fromUtf8(""))
        self.pushButton2.setObjectName(_fromUtf8("pushButton2"))
        self.horizontalLayout.addWidget(self.pushButton2)
        self.line_9 = QtGui.QFrame(Dialog)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.horizontalLayout.addWidget(self.line_9)
        self.pushButton1 = QtGui.QPushButton(Dialog)
        self.pushButton1.setText(_fromUtf8(""))
        self.pushButton1.setObjectName(_fromUtf8("pushButton1"))
        self.horizontalLayout.addWidget(self.pushButton1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButtonReject = QtGui.QPushButton(Dialog)
        self.pushButtonReject.setObjectName(_fromUtf8("pushButtonReject"))
        self.horizontalLayout_2.addWidget(self.pushButtonReject)
        self.pushButtonAccept = QtGui.QPushButton(Dialog)
        self.pushButtonAccept.setObjectName(_fromUtf8("pushButtonAccept"))
        self.horizontalLayout_2.addWidget(self.pushButtonAccept)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.pushButtonReject, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.reject)
        QtCore.QObject.connect(self.pushButtonAccept, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Edit", None))
        self.label.setText(_translate("Dialog", "ID:", None))
        self.label_3.setText(_translate("Dialog", "Mask:", None))
        self.pushButtonReject.setText(_translate("Dialog", "Cancel", None))
        self.pushButtonAccept.setText(_translate("Dialog", "Ok", None))

