# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'infoDialog.ui'
#
# Created: Mon Aug 17 03:33:31 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_infoDialog(object):
    def setupUi(self, infoDialog):
        infoDialog.setObjectName(_fromUtf8("infoDialog"))
        infoDialog.resize(392, 580)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(infoDialog.sizePolicy().hasHeightForWidth())
        infoDialog.setSizePolicy(sizePolicy)
        self.verticalLayout_6 = QtGui.QVBoxLayout(infoDialog)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.scrollArea = QtGui.QScrollArea(infoDialog)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 374, 525))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(369, 504))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.layoutWidget = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 3, 371, 501))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.metaBox = QtGui.QGroupBox(self.layoutWidget)
        self.metaBox.setObjectName(_fromUtf8("metaBox"))
        self.layoutWidget1 = QtGui.QWidget(self.metaBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(26, 35, 271, 89))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.labelDate = QtGui.QLabel(self.layoutWidget1)
        self.labelDate.setObjectName(_fromUtf8("labelDate"))
        self.gridLayout_3.addWidget(self.labelDate, 0, 0, 1, 1)
        self.labelDateValue = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDateValue.sizePolicy().hasHeightForWidth())
        self.labelDateValue.setSizePolicy(sizePolicy)
        self.labelDateValue.setObjectName(_fromUtf8("labelDateValue"))
        self.gridLayout_3.addWidget(self.labelDateValue, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelSubject = QtGui.QLabel(self.layoutWidget1)
        self.labelSubject.setObjectName(_fromUtf8("labelSubject"))
        self.horizontalLayout.addWidget(self.labelSubject)
        self.labelSubjectValue = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSubjectValue.sizePolicy().hasHeightForWidth())
        self.labelSubjectValue.setSizePolicy(sizePolicy)
        self.labelSubjectValue.setObjectName(_fromUtf8("labelSubjectValue"))
        self.horizontalLayout.addWidget(self.labelSubjectValue)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.labelLength = QtGui.QLabel(self.layoutWidget1)
        self.labelLength.setObjectName(_fromUtf8("labelLength"))
        self.horizontalLayout_8.addWidget(self.labelLength)
        self.labelLengthValue = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLengthValue.sizePolicy().hasHeightForWidth())
        self.labelLengthValue.setSizePolicy(sizePolicy)
        self.labelLengthValue.setText(_fromUtf8(""))
        self.labelLengthValue.setObjectName(_fromUtf8("labelLengthValue"))
        self.horizontalLayout_8.addWidget(self.labelLengthValue)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addWidget(self.metaBox)
        self.filtersBox = QtGui.QGroupBox(self.layoutWidget)
        self.filtersBox.setObjectName(_fromUtf8("filtersBox"))
        self.layoutWidget2 = QtGui.QWidget(self.filtersBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(24, 32, 272, 65))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelLow = QtGui.QLabel(self.layoutWidget2)
        self.labelLow.setLineWidth(1)
        self.labelLow.setScaledContents(True)
        self.labelLow.setObjectName(_fromUtf8("labelLow"))
        self.horizontalLayout_3.addWidget(self.labelLow)
        self.labelLowValue = QtGui.QLabel(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLowValue.sizePolicy().hasHeightForWidth())
        self.labelLowValue.setSizePolicy(sizePolicy)
        self.labelLowValue.setObjectName(_fromUtf8("labelLowValue"))
        self.horizontalLayout_3.addWidget(self.labelLowValue)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelHigh = QtGui.QLabel(self.layoutWidget2)
        self.labelHigh.setObjectName(_fromUtf8("labelHigh"))
        self.horizontalLayout_2.addWidget(self.labelHigh)
        self.labelHighValue = QtGui.QLabel(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHighValue.sizePolicy().hasHeightForWidth())
        self.labelHighValue.setSizePolicy(sizePolicy)
        self.labelHighValue.setObjectName(_fromUtf8("labelHighValue"))
        self.horizontalLayout_2.addWidget(self.labelHighValue)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.filtersBox)
        self.channelsBox = QtGui.QGroupBox(self.layoutWidget)
        self.channelsBox.setObjectName(_fromUtf8("channelsBox"))
        self.layoutWidget3 = QtGui.QWidget(self.channelsBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(30, 30, 261, 112))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.labelEEG = QtGui.QLabel(self.layoutWidget3)
        self.labelEEG.setObjectName(_fromUtf8("labelEEG"))
        self.horizontalLayout_4.addWidget(self.labelEEG)
        self.labelEEGValue = QtGui.QLabel(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelEEGValue.sizePolicy().hasHeightForWidth())
        self.labelEEGValue.setSizePolicy(sizePolicy)
        self.labelEEGValue.setObjectName(_fromUtf8("labelEEGValue"))
        self.horizontalLayout_4.addWidget(self.labelEEGValue)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.labelGradMEG = QtGui.QLabel(self.layoutWidget3)
        self.labelGradMEG.setObjectName(_fromUtf8("labelGradMEG"))
        self.horizontalLayout_5.addWidget(self.labelGradMEG)
        self.labelGradMEGValue = QtGui.QLabel(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelGradMEGValue.sizePolicy().hasHeightForWidth())
        self.labelGradMEGValue.setSizePolicy(sizePolicy)
        self.labelGradMEGValue.setObjectName(_fromUtf8("labelGradMEGValue"))
        self.horizontalLayout_5.addWidget(self.labelGradMEGValue)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.labelMagMEG = QtGui.QLabel(self.layoutWidget3)
        self.labelMagMEG.setObjectName(_fromUtf8("labelMagMEG"))
        self.horizontalLayout_6.addWidget(self.labelMagMEG)
        self.labelMagMEGValue = QtGui.QLabel(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMagMEGValue.sizePolicy().hasHeightForWidth())
        self.labelMagMEGValue.setSizePolicy(sizePolicy)
        self.labelMagMEGValue.setObjectName(_fromUtf8("labelMagMEGValue"))
        self.horizontalLayout_6.addWidget(self.labelMagMEGValue)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.labelSamples = QtGui.QLabel(self.layoutWidget3)
        self.labelSamples.setObjectName(_fromUtf8("labelSamples"))
        self.horizontalLayout_7.addWidget(self.labelSamples)
        self.labelSamplesValue = QtGui.QLabel(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSamplesValue.sizePolicy().hasHeightForWidth())
        self.labelSamplesValue.setSizePolicy(sizePolicy)
        self.labelSamplesValue.setObjectName(_fromUtf8("labelSamplesValue"))
        self.horizontalLayout_7.addWidget(self.labelSamplesValue)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addWidget(self.channelsBox)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.ButtonClose = QtGui.QPushButton(infoDialog)
        self.ButtonClose.setObjectName(_fromUtf8("ButtonClose"))
        self.verticalLayout_6.addWidget(self.ButtonClose)

        self.retranslateUi(infoDialog)
        QtCore.QMetaObject.connectSlotsByName(infoDialog)

    def retranslateUi(self, infoDialog):
        infoDialog.setWindowTitle(_translate("infoDialog", "Measurement info", None))
        self.metaBox.setTitle(_translate("infoDialog", "Background", None))
        self.labelDate.setText(_translate("infoDialog", "Date:", None))
        self.labelDateValue.setText(_translate("infoDialog", "DateValue", None))
        self.labelSubject.setText(_translate("infoDialog", "Subject:", None))
        self.labelSubjectValue.setText(_translate("infoDialog", "TextLabel", None))
        self.labelLength.setText(_translate("infoDialog", "Length:", None))
        self.filtersBox.setTitle(_translate("infoDialog", "Filters", None))
        self.labelLow.setText(_translate("infoDialog", "Low-pass:", None))
        self.labelLowValue.setText(_translate("infoDialog", "Low-pass value", None))
        self.labelHigh.setText(_translate("infoDialog", "High-pass:", None))
        self.labelHighValue.setText(_translate("infoDialog", "High-pass value", None))
        self.channelsBox.setTitle(_translate("infoDialog", "Channels", None))
        self.labelEEG.setText(_translate("infoDialog", "EEG channels:", None))
        self.labelEEGValue.setText(_translate("infoDialog", "EEG value", None))
        self.labelGradMEG.setText(_translate("infoDialog", "Gradiometers:", None))
        self.labelGradMEGValue.setText(_translate("infoDialog", "Grad. MEG value", None))
        self.labelMagMEG.setText(_translate("infoDialog", "Magnetometers:", None))
        self.labelMagMEGValue.setText(_translate("infoDialog", "Mag. MEG value", None))
        self.labelSamples.setText(_translate("infoDialog", "Sampling frequency:", None))
        self.labelSamplesValue.setText(_translate("infoDialog", "SamplesValue", None))
        self.ButtonClose.setText(_translate("infoDialog", "Close", None))

