# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../infoDialogUi.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_infoDialog(object):
    def setupUi(self, infoDialog):
        infoDialog.setObjectName("infoDialog")
        infoDialog.resize(392, 580)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(infoDialog.sizePolicy().hasHeightForWidth())
        infoDialog.setSizePolicy(sizePolicy)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(infoDialog)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(infoDialog)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 374, 525))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(369, 504))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.layoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 3, 371, 501))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.metaBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.metaBox.setObjectName("metaBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.metaBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(26, 35, 271, 89))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelDate = QtWidgets.QLabel(self.layoutWidget1)
        self.labelDate.setObjectName("labelDate")
        self.gridLayout_3.addWidget(self.labelDate, 0, 0, 1, 1)
        self.labelDateValue = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDateValue.sizePolicy().hasHeightForWidth())
        self.labelDateValue.setSizePolicy(sizePolicy)
        self.labelDateValue.setObjectName("labelDateValue")
        self.gridLayout_3.addWidget(self.labelDateValue, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelSubject = QtWidgets.QLabel(self.layoutWidget1)
        self.labelSubject.setObjectName("labelSubject")
        self.horizontalLayout.addWidget(self.labelSubject)
        self.labelSubjectValue = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSubjectValue.sizePolicy().hasHeightForWidth())
        self.labelSubjectValue.setSizePolicy(sizePolicy)
        self.labelSubjectValue.setObjectName("labelSubjectValue")
        self.horizontalLayout.addWidget(self.labelSubjectValue)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelLength = QtWidgets.QLabel(self.layoutWidget1)
        self.labelLength.setObjectName("labelLength")
        self.horizontalLayout_8.addWidget(self.labelLength)
        self.labelLengthValue = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLengthValue.sizePolicy().hasHeightForWidth())
        self.labelLengthValue.setSizePolicy(sizePolicy)
        self.labelLengthValue.setText("")
        self.labelLengthValue.setObjectName("labelLengthValue")
        self.horizontalLayout_8.addWidget(self.labelLengthValue)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addWidget(self.metaBox)
        self.filtersBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.filtersBox.setObjectName("filtersBox")
        self.layoutWidget2 = QtWidgets.QWidget(self.filtersBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(24, 32, 272, 65))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelLow = QtWidgets.QLabel(self.layoutWidget2)
        self.labelLow.setLineWidth(1)
        self.labelLow.setScaledContents(True)
        self.labelLow.setObjectName("labelLow")
        self.horizontalLayout_3.addWidget(self.labelLow)
        self.labelLowValue = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLowValue.sizePolicy().hasHeightForWidth())
        self.labelLowValue.setSizePolicy(sizePolicy)
        self.labelLowValue.setObjectName("labelLowValue")
        self.horizontalLayout_3.addWidget(self.labelLowValue)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelHigh = QtWidgets.QLabel(self.layoutWidget2)
        self.labelHigh.setObjectName("labelHigh")
        self.horizontalLayout_2.addWidget(self.labelHigh)
        self.labelHighValue = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHighValue.sizePolicy().hasHeightForWidth())
        self.labelHighValue.setSizePolicy(sizePolicy)
        self.labelHighValue.setObjectName("labelHighValue")
        self.horizontalLayout_2.addWidget(self.labelHighValue)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.filtersBox)
        self.channelsBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.channelsBox.setObjectName("channelsBox")
        self.layoutWidget3 = QtWidgets.QWidget(self.channelsBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(30, 30, 261, 112))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelEEG = QtWidgets.QLabel(self.layoutWidget3)
        self.labelEEG.setObjectName("labelEEG")
        self.horizontalLayout_4.addWidget(self.labelEEG)
        self.labelEEGValue = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelEEGValue.sizePolicy().hasHeightForWidth())
        self.labelEEGValue.setSizePolicy(sizePolicy)
        self.labelEEGValue.setObjectName("labelEEGValue")
        self.horizontalLayout_4.addWidget(self.labelEEGValue)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelGradMEG = QtWidgets.QLabel(self.layoutWidget3)
        self.labelGradMEG.setObjectName("labelGradMEG")
        self.horizontalLayout_5.addWidget(self.labelGradMEG)
        self.labelGradMEGValue = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelGradMEGValue.sizePolicy().hasHeightForWidth())
        self.labelGradMEGValue.setSizePolicy(sizePolicy)
        self.labelGradMEGValue.setObjectName("labelGradMEGValue")
        self.horizontalLayout_5.addWidget(self.labelGradMEGValue)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelMagMEG = QtWidgets.QLabel(self.layoutWidget3)
        self.labelMagMEG.setObjectName("labelMagMEG")
        self.horizontalLayout_6.addWidget(self.labelMagMEG)
        self.labelMagMEGValue = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMagMEGValue.sizePolicy().hasHeightForWidth())
        self.labelMagMEGValue.setSizePolicy(sizePolicy)
        self.labelMagMEGValue.setObjectName("labelMagMEGValue")
        self.horizontalLayout_6.addWidget(self.labelMagMEGValue)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelSamples = QtWidgets.QLabel(self.layoutWidget3)
        self.labelSamples.setObjectName("labelSamples")
        self.horizontalLayout_7.addWidget(self.labelSamples)
        self.labelSamplesValue = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSamplesValue.sizePolicy().hasHeightForWidth())
        self.labelSamplesValue.setSizePolicy(sizePolicy)
        self.labelSamplesValue.setObjectName("labelSamplesValue")
        self.horizontalLayout_7.addWidget(self.labelSamplesValue)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addWidget(self.channelsBox)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.ButtonClose = QtWidgets.QPushButton(infoDialog)
        self.ButtonClose.setObjectName("ButtonClose")
        self.verticalLayout_6.addWidget(self.ButtonClose)

        self.retranslateUi(infoDialog)
        QtCore.QMetaObject.connectSlotsByName(infoDialog)

    def retranslateUi(self, infoDialog):
        _translate = QtCore.QCoreApplication.translate
        infoDialog.setWindowTitle(_translate("infoDialog", "Measurement info"))
        self.metaBox.setTitle(_translate("infoDialog", "Background"))
        self.labelDate.setText(_translate("infoDialog", "Date:"))
        self.labelDateValue.setText(_translate("infoDialog", "DateValue"))
        self.labelSubject.setText(_translate("infoDialog", "Subject:"))
        self.labelSubjectValue.setText(_translate("infoDialog", "TextLabel"))
        self.labelLength.setText(_translate("infoDialog", "Length:"))
        self.filtersBox.setTitle(_translate("infoDialog", "Filters"))
        self.labelLow.setText(_translate("infoDialog", "Low-pass:"))
        self.labelLowValue.setText(_translate("infoDialog", "Low-pass value"))
        self.labelHigh.setText(_translate("infoDialog", "High-pass:"))
        self.labelHighValue.setText(_translate("infoDialog", "High-pass value"))
        self.channelsBox.setTitle(_translate("infoDialog", "Channels"))
        self.labelEEG.setText(_translate("infoDialog", "EEG channels:"))
        self.labelEEGValue.setText(_translate("infoDialog", "EEG value"))
        self.labelGradMEG.setText(_translate("infoDialog", "Gradiometers:"))
        self.labelGradMEGValue.setText(_translate("infoDialog", "Grad. MEG value"))
        self.labelMagMEG.setText(_translate("infoDialog", "Magnetometers:"))
        self.labelMagMEGValue.setText(_translate("infoDialog", "Mag. MEG value"))
        self.labelSamples.setText(_translate("infoDialog", "Sampling frequency:"))
        self.labelSamplesValue.setText(_translate("infoDialog", "SamplesValue"))
        self.ButtonClose.setText(_translate("infoDialog", "Close"))

