# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Wed Aug 21 11:02:56 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(964, 829)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 944, 721))
        self.scrollAreaWidgetContents_3.setMinimumSize(QtCore.QSize(937, 638))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents_3)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabRaw = QtGui.QWidget()
        self.tabRaw.setObjectName(_fromUtf8("tabRaw"))
        self.groupBoxExperiment = QtGui.QGroupBox(self.tabRaw)
        self.groupBoxExperiment.setGeometry(QtCore.QRect(10, 10, 391, 241))
        self.groupBoxExperiment.setObjectName(_fromUtf8("groupBoxExperiment"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.groupBoxExperiment)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 40, 371, 71))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.labelExperiment = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.labelExperiment.setObjectName(_fromUtf8("labelExperiment"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelExperiment)
        self.labelExperimentName = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.labelExperimentName.setObjectName(_fromUtf8("labelExperimentName"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.labelExperimentName)
        self.verticalLayout_4.addLayout(self.formLayout_4)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.labelAuthor = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.labelAuthor.setObjectName(_fromUtf8("labelAuthor"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelAuthor)
        self.labelAuthorName = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.labelAuthorName.setObjectName(_fromUtf8("labelAuthorName"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.labelAuthorName)
        self.verticalLayout_4.addLayout(self.formLayout_5)
        self.labelDescription = QtGui.QLabel(self.groupBoxExperiment)
        self.labelDescription.setGeometry(QtCore.QRect(20, 110, 79, 21))
        self.labelDescription.setObjectName(_fromUtf8("labelDescription"))
        self.textBrowserExperimentDescription = QtGui.QTextBrowser(self.groupBoxExperiment)
        self.textBrowserExperimentDescription.setGeometry(QtCore.QRect(20, 130, 371, 111))
        self.textBrowserExperimentDescription.setObjectName(_fromUtf8("textBrowserExperimentDescription"))
        self.groupBoxSubject = QtGui.QGroupBox(self.tabRaw)
        self.groupBoxSubject.setGeometry(QtCore.QRect(10, 260, 901, 341))
        self.groupBoxSubject.setObjectName(_fromUtf8("groupBoxSubject"))
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBoxSubject)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 371, 71))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelSubject = QtGui.QLabel(self.verticalLayoutWidget)
        self.labelSubject.setObjectName(_fromUtf8("labelSubject"))
        self.horizontalLayout_3.addWidget(self.labelSubject)
        self.labelSubjectValue = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSubjectValue.sizePolicy().hasHeightForWidth())
        self.labelSubjectValue.setSizePolicy(sizePolicy)
        self.labelSubjectValue.setObjectName(_fromUtf8("labelSubjectValue"))
        self.horizontalLayout_3.addWidget(self.labelSubjectValue)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.labelDate = QtGui.QLabel(self.verticalLayoutWidget)
        self.labelDate.setObjectName(_fromUtf8("labelDate"))
        self.horizontalLayout_22.addWidget(self.labelDate)
        self.labelDateValue = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDateValue.sizePolicy().hasHeightForWidth())
        self.labelDateValue.setSizePolicy(sizePolicy)
        self.labelDateValue.setObjectName(_fromUtf8("labelDateValue"))
        self.horizontalLayout_22.addWidget(self.labelDateValue)
        self.verticalLayout_5.addLayout(self.horizontalLayout_22)
        self.layoutWidget_7 = QtGui.QWidget(self.groupBoxSubject)
        self.layoutWidget_7.setGeometry(QtCore.QRect(510, 150, 371, 151))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.labelEEG = QtGui.QLabel(self.layoutWidget_7)
        self.labelEEG.setObjectName(_fromUtf8("labelEEG"))
        self.horizontalLayout_6.addWidget(self.labelEEG)
        self.labelEEGValue = QtGui.QLabel(self.layoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelEEGValue.sizePolicy().hasHeightForWidth())
        self.labelEEGValue.setSizePolicy(sizePolicy)
        self.labelEEGValue.setObjectName(_fromUtf8("labelEEGValue"))
        self.horizontalLayout_6.addWidget(self.labelEEGValue)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.labelGradMEG = QtGui.QLabel(self.layoutWidget_7)
        self.labelGradMEG.setObjectName(_fromUtf8("labelGradMEG"))
        self.horizontalLayout_7.addWidget(self.labelGradMEG)
        self.labelGradMEGValue = QtGui.QLabel(self.layoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelGradMEGValue.sizePolicy().hasHeightForWidth())
        self.labelGradMEGValue.setSizePolicy(sizePolicy)
        self.labelGradMEGValue.setObjectName(_fromUtf8("labelGradMEGValue"))
        self.horizontalLayout_7.addWidget(self.labelGradMEGValue)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.labelMagMEG = QtGui.QLabel(self.layoutWidget_7)
        self.labelMagMEG.setObjectName(_fromUtf8("labelMagMEG"))
        self.horizontalLayout_8.addWidget(self.labelMagMEG)
        self.labelMagMEGValue = QtGui.QLabel(self.layoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMagMEGValue.sizePolicy().hasHeightForWidth())
        self.labelMagMEGValue.setSizePolicy(sizePolicy)
        self.labelMagMEGValue.setObjectName(_fromUtf8("labelMagMEGValue"))
        self.horizontalLayout_8.addWidget(self.labelMagMEGValue)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.labelSamples = QtGui.QLabel(self.layoutWidget_7)
        self.labelSamples.setObjectName(_fromUtf8("labelSamples"))
        self.horizontalLayout_9.addWidget(self.labelSamples)
        self.labelSamplesValue = QtGui.QLabel(self.layoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSamplesValue.sizePolicy().hasHeightForWidth())
        self.labelSamplesValue.setSizePolicy(sizePolicy)
        self.labelSamplesValue.setObjectName(_fromUtf8("labelSamplesValue"))
        self.horizontalLayout_9.addWidget(self.labelSamplesValue)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.layoutWidget_6 = QtGui.QWidget(self.groupBoxSubject)
        self.layoutWidget_6.setGeometry(QtCore.QRect(510, 40, 371, 71))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.labelLow = QtGui.QLabel(self.layoutWidget_6)
        self.labelLow.setLineWidth(1)
        self.labelLow.setScaledContents(True)
        self.labelLow.setObjectName(_fromUtf8("labelLow"))
        self.horizontalLayout_4.addWidget(self.labelLow)
        self.labelLowValue = QtGui.QLabel(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLowValue.sizePolicy().hasHeightForWidth())
        self.labelLowValue.setSizePolicy(sizePolicy)
        self.labelLowValue.setObjectName(_fromUtf8("labelLowValue"))
        self.horizontalLayout_4.addWidget(self.labelLowValue)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.labelHigh = QtGui.QLabel(self.layoutWidget_6)
        self.labelHigh.setObjectName(_fromUtf8("labelHigh"))
        self.horizontalLayout_5.addWidget(self.labelHigh)
        self.labelHighValue = QtGui.QLabel(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHighValue.sizePolicy().hasHeightForWidth())
        self.labelHighValue.setSizePolicy(sizePolicy)
        self.labelHighValue.setObjectName(_fromUtf8("labelHighValue"))
        self.horizontalLayout_5.addWidget(self.labelHighValue)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.labelChannels = QtGui.QLabel(self.groupBoxSubject)
        self.labelChannels.setGeometry(QtCore.QRect(430, 150, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelChannels.setFont(font)
        self.labelChannels.setObjectName(_fromUtf8("labelChannels"))
        self.labelFilters = QtGui.QLabel(self.groupBoxSubject)
        self.labelFilters.setGeometry(QtCore.QRect(450, 40, 61, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelFilters.setFont(font)
        self.labelFilters.setObjectName(_fromUtf8("labelFilters"))
        self.textBrowserEvents = QtGui.QTextBrowser(self.groupBoxSubject)
        self.textBrowserEvents.setGeometry(QtCore.QRect(20, 160, 371, 111))
        self.textBrowserEvents.setObjectName(_fromUtf8("textBrowserEvents"))
        self.labelEvents = QtGui.QLabel(self.groupBoxSubject)
        self.labelEvents.setGeometry(QtCore.QRect(20, 140, 66, 21))
        self.labelEvents.setObjectName(_fromUtf8("labelEvents"))
        self.pushButtonMNE_Browse_Raw = QtGui.QPushButton(self.tabRaw)
        self.pushButtonMNE_Browse_Raw.setGeometry(QtCore.QRect(0, 630, 214, 31))
        self.pushButtonMNE_Browse_Raw.setObjectName(_fromUtf8("pushButtonMNE_Browse_Raw"))
        self.tabWidget.addTab(self.tabRaw, _fromUtf8(""))
        self.tabPreprocessing = QtGui.QWidget()
        self.tabPreprocessing.setObjectName(_fromUtf8("tabPreprocessing"))
        self.formLayout = QtGui.QFormLayout(self.tabPreprocessing)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.groupBoxAvailablePreprocessing = QtGui.QGroupBox(self.tabPreprocessing)
        self.groupBoxAvailablePreprocessing.setMaximumSize(QtCore.QSize(400, 170))
        self.groupBoxAvailablePreprocessing.setObjectName(_fromUtf8("groupBoxAvailablePreprocessing"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxAvailablePreprocessing)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButtonMaxFilter = QtGui.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonMaxFilter.setObjectName(_fromUtf8("pushButtonMaxFilter"))
        self.gridLayout_3.addWidget(self.pushButtonMaxFilter, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonECG = QtGui.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonECG.setObjectName(_fromUtf8("pushButtonECG"))
        self.horizontalLayout.addWidget(self.pushButtonECG)
        self.pushButtonApplyECG = QtGui.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonApplyECG.setEnabled(False)
        self.pushButtonApplyECG.setObjectName(_fromUtf8("pushButtonApplyECG"))
        self.horizontalLayout.addWidget(self.pushButtonApplyECG)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.pushButtonEOG = QtGui.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonEOG.setObjectName(_fromUtf8("pushButtonEOG"))
        self.horizontalLayout_12.addWidget(self.pushButtonEOG)
        self.pushButtonApplyEOG = QtGui.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonApplyEOG.setEnabled(False)
        self.pushButtonApplyEOG.setObjectName(_fromUtf8("pushButtonApplyEOG"))
        self.horizontalLayout_12.addWidget(self.pushButtonApplyEOG)
        self.gridLayout_3.addLayout(self.horizontalLayout_12, 2, 0, 1, 1)
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.groupBoxAvailablePreprocessing)
        self.groupBoxPreprocessingCheckBoxes = QtGui.QGroupBox(self.tabPreprocessing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPreprocessingCheckBoxes.sizePolicy().hasHeightForWidth())
        self.groupBoxPreprocessingCheckBoxes.setSizePolicy(sizePolicy)
        self.groupBoxPreprocessingCheckBoxes.setMinimumSize(QtCore.QSize(60, 0))
        self.groupBoxPreprocessingCheckBoxes.setObjectName(_fromUtf8("groupBoxPreprocessingCheckBoxes"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBoxPreprocessingCheckBoxes)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.labelEOGApplied_2 = QtGui.QLabel(self.groupBoxPreprocessingCheckBoxes)
        self.labelEOGApplied_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEOGApplied_2.setObjectName(_fromUtf8("labelEOGApplied_2"))
        self.gridLayout_6.addWidget(self.labelEOGApplied_2, 0, 2, 1, 1)
        self.labelECGComputed_2 = QtGui.QLabel(self.groupBoxPreprocessingCheckBoxes)
        self.labelECGComputed_2.setObjectName(_fromUtf8("labelECGComputed_2"))
        self.gridLayout_6.addWidget(self.labelECGComputed_2, 2, 0, 1, 1)
        self.labelEOGComputed_2 = QtGui.QLabel(self.groupBoxPreprocessingCheckBoxes)
        self.labelEOGComputed_2.setObjectName(_fromUtf8("labelEOGComputed_2"))
        self.gridLayout_6.addWidget(self.labelEOGComputed_2, 3, 0, 1, 1)
        self.labelECGApplied_2 = QtGui.QLabel(self.groupBoxPreprocessingCheckBoxes)
        self.labelECGApplied_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelECGApplied_2.setObjectName(_fromUtf8("labelECGApplied_2"))
        self.gridLayout_6.addWidget(self.labelECGApplied_2, 0, 1, 1, 1)
        self.labelMaxFilter_2 = QtGui.QLabel(self.groupBoxPreprocessingCheckBoxes)
        self.labelMaxFilter_2.setObjectName(_fromUtf8("labelMaxFilter_2"))
        self.gridLayout_6.addWidget(self.labelMaxFilter_2, 1, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.checkBoxMaxFilterComputed = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxMaxFilterComputed.setEnabled(False)
        self.checkBoxMaxFilterComputed.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.checkBoxMaxFilterComputed.setText(_fromUtf8(""))
        self.checkBoxMaxFilterComputed.setObjectName(_fromUtf8("checkBoxMaxFilterComputed"))
        self.horizontalLayout_13.addWidget(self.checkBoxMaxFilterComputed)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.gridLayout_6.addLayout(self.horizontalLayout_13, 1, 1, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem2)
        self.checkBoxECGApplied = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxECGApplied.setEnabled(False)
        self.checkBoxECGApplied.setText(_fromUtf8(""))
        self.checkBoxECGApplied.setObjectName(_fromUtf8("checkBoxECGApplied"))
        self.horizontalLayout_16.addWidget(self.checkBoxECGApplied)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem3)
        self.gridLayout_6.addLayout(self.horizontalLayout_16, 2, 2, 1, 1)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem4)
        self.checkBoxECGComputed = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxECGComputed.setEnabled(False)
        self.checkBoxECGComputed.setText(_fromUtf8(""))
        self.checkBoxECGComputed.setObjectName(_fromUtf8("checkBoxECGComputed"))
        self.horizontalLayout_17.addWidget(self.checkBoxECGComputed)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem5)
        self.gridLayout_6.addLayout(self.horizontalLayout_17, 2, 1, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem6)
        self.checkBoxEOGComputed = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxEOGComputed.setEnabled(False)
        self.checkBoxEOGComputed.setText(_fromUtf8(""))
        self.checkBoxEOGComputed.setObjectName(_fromUtf8("checkBoxEOGComputed"))
        self.horizontalLayout_19.addWidget(self.checkBoxEOGComputed)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem7)
        self.gridLayout_6.addLayout(self.horizontalLayout_19, 3, 1, 1, 1)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem8)
        self.checkBoxEOGApplied = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxEOGApplied.setEnabled(False)
        self.checkBoxEOGApplied.setText(_fromUtf8(""))
        self.checkBoxEOGApplied.setObjectName(_fromUtf8("checkBoxEOGApplied"))
        self.horizontalLayout_20.addWidget(self.checkBoxEOGApplied)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem9)
        self.gridLayout_6.addLayout(self.horizontalLayout_20, 3, 2, 1, 1)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem10)
        self.checkBoxMaxFilterApplied = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxMaxFilterApplied.setEnabled(False)
        self.checkBoxMaxFilterApplied.setText(_fromUtf8(""))
        self.checkBoxMaxFilterApplied.setObjectName(_fromUtf8("checkBoxMaxFilterApplied"))
        self.horizontalLayout_21.addWidget(self.checkBoxMaxFilterApplied)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem11)
        self.gridLayout_6.addLayout(self.horizontalLayout_21, 1, 2, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_6)
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.groupBoxPreprocessingCheckBoxes)
        self.pushButtonSpectrum = QtGui.QPushButton(self.tabPreprocessing)
        self.pushButtonSpectrum.setObjectName(_fromUtf8("pushButtonSpectrum"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.pushButtonSpectrum)
        self.pushButtonMNE_Browse_Raw_2 = QtGui.QPushButton(self.tabPreprocessing)
        self.pushButtonMNE_Browse_Raw_2.setObjectName(_fromUtf8("pushButtonMNE_Browse_Raw_2"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.pushButtonMNE_Browse_Raw_2)
        self.pushButtonFilter = QtGui.QPushButton(self.tabPreprocessing)
        self.pushButtonFilter.setObjectName(_fromUtf8("pushButtonFilter"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.pushButtonFilter)
        self.tabWidget.addTab(self.tabPreprocessing, _fromUtf8(""))
        self.tabEpoching = QtGui.QWidget()
        self.tabEpoching.setObjectName(_fromUtf8("tabEpoching"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tabEpoching)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 901, 441))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.pushButtonModifyEpochs = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButtonModifyEpochs.setObjectName(_fromUtf8("pushButtonModifyEpochs"))
        self.horizontalLayout_18.addWidget(self.pushButtonModifyEpochs)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem12)
        self.gridLayout_5.addLayout(self.horizontalLayout_18, 1, 1, 1, 1)
        self.groupBoxEpochsEpoching = QtGui.QGroupBox(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxEpochsEpoching.sizePolicy().hasHeightForWidth())
        self.groupBoxEpochsEpoching.setSizePolicy(sizePolicy)
        self.groupBoxEpochsEpoching.setTitle(_fromUtf8(""))
        self.groupBoxEpochsEpoching.setObjectName(_fromUtf8("groupBoxEpochsEpoching"))
        self.gridLayout_5.addWidget(self.groupBoxEpochsEpoching, 0, 0, 1, 1)
        self.groupBoxAvailableEpoching = QtGui.QGroupBox(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxAvailableEpoching.sizePolicy().hasHeightForWidth())
        self.groupBoxAvailableEpoching.setSizePolicy(sizePolicy)
        self.groupBoxAvailableEpoching.setMaximumSize(QtCore.QSize(600, 90))
        self.groupBoxAvailableEpoching.setObjectName(_fromUtf8("groupBoxAvailableEpoching"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBoxAvailableEpoching)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.pushButtonCreateEpochs = QtGui.QPushButton(self.groupBoxAvailableEpoching)
        self.pushButtonCreateEpochs.setObjectName(_fromUtf8("pushButtonCreateEpochs"))
        self.horizontalLayout_10.addWidget(self.pushButtonCreateEpochs)
        self.pushButtonSaveEpochs = QtGui.QPushButton(self.groupBoxAvailableEpoching)
        self.pushButtonSaveEpochs.setObjectName(_fromUtf8("pushButtonSaveEpochs"))
        self.horizontalLayout_10.addWidget(self.pushButtonSaveEpochs)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButtonDeleteEpochs = QtGui.QPushButton(self.groupBoxAvailableEpoching)
        self.pushButtonDeleteEpochs.setObjectName(_fromUtf8("pushButtonDeleteEpochs"))
        self.horizontalLayout_2.addWidget(self.pushButtonDeleteEpochs)
        self.pushButtonLoadEpochs = QtGui.QPushButton(self.groupBoxAvailableEpoching)
        self.pushButtonLoadEpochs.setObjectName(_fromUtf8("pushButtonLoadEpochs"))
        self.horizontalLayout_2.addWidget(self.pushButtonLoadEpochs)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_5.addWidget(self.groupBoxAvailableEpoching, 1, 0, 1, 1)
        self.groupBoxEpochParamsEpoching = QtGui.QGroupBox(self.gridLayoutWidget_2)
        self.groupBoxEpochParamsEpoching.setTitle(_fromUtf8(""))
        self.groupBoxEpochParamsEpoching.setObjectName(_fromUtf8("groupBoxEpochParamsEpoching"))
        self.gridLayout_5.addWidget(self.groupBoxEpochParamsEpoching, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tabEpoching, _fromUtf8(""))
        self.tabAveraging = QtGui.QWidget()
        self.tabAveraging.setObjectName(_fromUtf8("tabAveraging"))
        self.gridLayoutWidget = QtGui.QWidget(self.tabAveraging)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 901, 591))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBoxAvailableAveraging = QtGui.QGroupBox(self.gridLayoutWidget)
        self.groupBoxAvailableAveraging.setMaximumSize(QtCore.QSize(500, 240))
        self.groupBoxAvailableAveraging.setObjectName(_fromUtf8("groupBoxAvailableAveraging"))
        self.groupBoxChannelAverages = QtGui.QGroupBox(self.groupBoxAvailableAveraging)
        self.groupBoxChannelAverages.setGeometry(QtCore.QRect(17, 62, 433, 167))
        self.groupBoxChannelAverages.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBoxChannelAverages.setObjectName(_fromUtf8("groupBoxChannelAverages"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBoxChannelAverages)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.pushButtonChannelAverages = QtGui.QPushButton(self.groupBoxChannelAverages)
        self.pushButtonChannelAverages.setObjectName(_fromUtf8("pushButtonChannelAverages"))
        self.gridLayout_11.addWidget(self.pushButtonChannelAverages, 4, 1, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.radioButtonLobe = QtGui.QRadioButton(self.groupBoxChannelAverages)
        self.radioButtonLobe.setChecked(True)
        self.radioButtonLobe.setObjectName(_fromUtf8("radioButtonLobe"))
        self.buttonGroupChannelAverage = QtGui.QButtonGroup(MainWindow)
        self.buttonGroupChannelAverage.setObjectName(_fromUtf8("buttonGroupChannelAverage"))
        self.buttonGroupChannelAverage.addButton(self.radioButtonLobe)
        self.horizontalLayout_14.addWidget(self.radioButtonLobe)
        self.comboBoxLobes = QtGui.QComboBox(self.groupBoxChannelAverages)
        self.comboBoxLobes.setObjectName(_fromUtf8("comboBoxLobes"))
        self.horizontalLayout_14.addWidget(self.comboBoxLobes)
        self.gridLayout_11.addLayout(self.horizontalLayout_14, 1, 1, 1, 1)
        self.labelChannelAverages = QtGui.QLabel(self.groupBoxChannelAverages)
        self.labelChannelAverages.setObjectName(_fromUtf8("labelChannelAverages"))
        self.gridLayout_11.addWidget(self.labelChannelAverages, 0, 1, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.radioButtonCustomChannels = QtGui.QRadioButton(self.groupBoxChannelAverages)
        self.radioButtonCustomChannels.setObjectName(_fromUtf8("radioButtonCustomChannels"))
        self.buttonGroupChannelAverage.addButton(self.radioButtonCustomChannels)
        self.horizontalLayout_15.addWidget(self.radioButtonCustomChannels)
        self.plainTextEditCustomChannelsToAverage = QtGui.QPlainTextEdit(self.groupBoxChannelAverages)
        self.plainTextEditCustomChannelsToAverage.setEnabled(False)
        self.plainTextEditCustomChannelsToAverage.setObjectName(_fromUtf8("plainTextEditCustomChannelsToAverage"))
        self.horizontalLayout_15.addWidget(self.plainTextEditCustomChannelsToAverage)
        self.gridLayout_11.addLayout(self.horizontalLayout_15, 3, 1, 1, 1)
        self.pushButtonAverage = QtGui.QPushButton(self.groupBoxAvailableAveraging)
        self.pushButtonAverage.setGeometry(QtCore.QRect(17, 25, 242, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAverage.sizePolicy().hasHeightForWidth())
        self.pushButtonAverage.setSizePolicy(sizePolicy)
        self.pushButtonAverage.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.pushButtonAverage.setObjectName(_fromUtf8("pushButtonAverage"))
        self.gridLayout_4.addWidget(self.groupBoxAvailableAveraging, 1, 0, 1, 1)
        self.groupBoxEpochsAveraging = QtGui.QGroupBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxEpochsAveraging.sizePolicy().hasHeightForWidth())
        self.groupBoxEpochsAveraging.setSizePolicy(sizePolicy)
        self.groupBoxEpochsAveraging.setTitle(_fromUtf8(""))
        self.groupBoxEpochsAveraging.setObjectName(_fromUtf8("groupBoxEpochsAveraging"))
        self.gridLayout_4.addWidget(self.groupBoxEpochsAveraging, 0, 0, 1, 1)
        self.groupBoxEpochParamsAveraging = QtGui.QGroupBox(self.gridLayoutWidget)
        self.groupBoxEpochParamsAveraging.setTitle(_fromUtf8(""))
        self.groupBoxEpochParamsAveraging.setObjectName(_fromUtf8("groupBoxEpochParamsAveraging"))
        self.gridLayout_4.addWidget(self.groupBoxEpochParamsAveraging, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tabAveraging, _fromUtf8(""))
        self.tabTFR = QtGui.QWidget()
        self.tabTFR.setObjectName(_fromUtf8("tabTFR"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tabTFR)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 901, 531))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.groupBoxEpochsTFR = QtGui.QGroupBox(self.gridLayoutWidget_3)
        self.groupBoxEpochsTFR.setTitle(_fromUtf8(""))
        self.groupBoxEpochsTFR.setObjectName(_fromUtf8("groupBoxEpochsTFR"))
        self.gridLayout_8.addWidget(self.groupBoxEpochsTFR, 0, 0, 1, 1)
        self.groupBoxEpochParamsTFR = QtGui.QGroupBox(self.gridLayoutWidget_3)
        self.groupBoxEpochParamsTFR.setTitle(_fromUtf8(""))
        self.groupBoxEpochParamsTFR.setObjectName(_fromUtf8("groupBoxEpochParamsTFR"))
        self.gridLayout_8.addWidget(self.groupBoxEpochParamsTFR, 0, 1, 1, 1)
        self.groupBoxAvailableTFR = QtGui.QGroupBox(self.gridLayoutWidget_3)
        self.groupBoxAvailableTFR.setMaximumSize(QtCore.QSize(500, 180))
        self.groupBoxAvailableTFR.setObjectName(_fromUtf8("groupBoxAvailableTFR"))
        self.pushButtonTFRTopology = QtGui.QPushButton(self.groupBoxAvailableTFR)
        self.pushButtonTFRTopology.setGeometry(QtCore.QRect(20, 80, 189, 31))
        self.pushButtonTFRTopology.setObjectName(_fromUtf8("pushButtonTFRTopology"))
        self.pushButtonTFR = QtGui.QPushButton(self.groupBoxAvailableTFR)
        self.pushButtonTFR.setGeometry(QtCore.QRect(20, 40, 191, 31))
        self.pushButtonTFR.setObjectName(_fromUtf8("pushButtonTFR"))
        self.gridLayout_8.addWidget(self.groupBoxAvailableTFR, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabTFR, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.gridLayout_7.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 964, 29))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionCreate_experiment = QtGui.QAction(MainWindow)
        self.actionCreate_experiment.setObjectName(_fromUtf8("actionCreate_experiment"))
        self.actionOpen_experiment = QtGui.QAction(MainWindow)
        self.actionOpen_experiment.setObjectName(_fromUtf8("actionOpen_experiment"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionSet_workspace = QtGui.QAction(MainWindow)
        self.actionSet_workspace.setObjectName(_fromUtf8("actionSet_workspace"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionCreate_experiment)
        self.menuFile.addAction(self.actionOpen_experiment)
        self.menuFile.addAction(self.actionSet_workspace)
        self.menuFile.addAction(self.actionAbout)
        self.menuTools.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.toolBar.addAction(self.actionCreate_experiment)
        self.toolBar.addAction(self.actionOpen_experiment)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.radioButtonLobe, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.comboBoxLobes.setEnabled)
        QtCore.QObject.connect(self.radioButtonCustomChannels, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.plainTextEditCustomChannelsToAverage.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Meggie", None))
        self.groupBoxExperiment.setTitle(_translate("MainWindow", "Experiment info", None))
        self.labelExperiment.setText(_translate("MainWindow", "Experiment:", None))
        self.labelExperimentName.setText(_translate("MainWindow", "TextLabel", None))
        self.labelAuthor.setText(_translate("MainWindow", "Author:", None))
        self.labelAuthorName.setText(_translate("MainWindow", "TextLabel", None))
        self.labelDescription.setText(_translate("MainWindow", "Description:", None))
        self.groupBoxSubject.setTitle(_translate("MainWindow", "Subject info", None))
        self.labelSubject.setText(_translate("MainWindow", "Subject:", None))
        self.labelSubjectValue.setText(_translate("MainWindow", "TextLabel", None))
        self.labelDate.setText(_translate("MainWindow", "Date:", None))
        self.labelDateValue.setText(_translate("MainWindow", "DateValue", None))
        self.labelEEG.setText(_translate("MainWindow", "EEG channels:", None))
        self.labelEEGValue.setText(_translate("MainWindow", "EEG value", None))
        self.labelGradMEG.setText(_translate("MainWindow", "Gradiometers:", None))
        self.labelGradMEGValue.setText(_translate("MainWindow", "Grad. MEG value", None))
        self.labelMagMEG.setText(_translate("MainWindow", "Magnetometers:", None))
        self.labelMagMEGValue.setText(_translate("MainWindow", "Mag. MEG value", None))
        self.labelSamples.setText(_translate("MainWindow", "Sampling frequency:", None))
        self.labelSamplesValue.setText(_translate("MainWindow", "SamplesValue", None))
        self.labelLow.setText(_translate("MainWindow", "Low-pass:", None))
        self.labelLowValue.setText(_translate("MainWindow", "Low-pass value", None))
        self.labelHigh.setText(_translate("MainWindow", "High-pass:", None))
        self.labelHighValue.setText(_translate("MainWindow", "High-pass value", None))
        self.labelChannels.setText(_translate("MainWindow", "Channels:", None))
        self.labelFilters.setText(_translate("MainWindow", "Filters:", None))
        self.labelEvents.setText(_translate("MainWindow", "Events:", None))
        self.pushButtonMNE_Browse_Raw.setText(_translate("MainWindow", "View with MNE_Browse_Raw", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRaw), _translate("MainWindow", "Info", None))
        self.groupBoxAvailablePreprocessing.setTitle(_translate("MainWindow", "Available actions:", None))
        self.pushButtonMaxFilter.setText(_translate("MainWindow", "MaxFilter", None))
        self.pushButtonECG.setText(_translate("MainWindow", "Calculate ECG projections", None))
        self.pushButtonApplyECG.setText(_translate("MainWindow", "Apply ECG projections", None))
        self.pushButtonEOG.setText(_translate("MainWindow", "Calculate EOG projections", None))
        self.pushButtonApplyEOG.setText(_translate("MainWindow", "Apply EOG projections", None))
        self.groupBoxPreprocessingCheckBoxes.setTitle(_translate("MainWindow", "Preprocessing steps completed:", None))
        self.labelEOGApplied_2.setText(_translate("MainWindow", "Applied", None))
        self.labelECGComputed_2.setText(_translate("MainWindow", "ECG projections", None))
        self.labelEOGComputed_2.setText(_translate("MainWindow", "EOG projections", None))
        self.labelECGApplied_2.setText(_translate("MainWindow", "Computed", None))
        self.labelMaxFilter_2.setText(_translate("MainWindow", "MaxFilter", None))
        self.pushButtonSpectrum.setText(_translate("MainWindow", "Magnitude spectrum", None))
        self.pushButtonMNE_Browse_Raw_2.setText(_translate("MainWindow", "View with MNE_Browse_Raw", None))
        self.pushButtonFilter.setText(_translate("MainWindow", "Filter", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPreprocessing), _translate("MainWindow", "Preprocessing", None))
        self.pushButtonModifyEpochs.setText(_translate("MainWindow", "Modify selected epochs", None))
        self.groupBoxAvailableEpoching.setTitle(_translate("MainWindow", "Available actions:", None))
        self.pushButtonCreateEpochs.setText(_translate("MainWindow", "Create epochs", None))
        self.pushButtonSaveEpochs.setText(_translate("MainWindow", "Save selected epochs", None))
        self.pushButtonDeleteEpochs.setText(_translate("MainWindow", "Delete selected epochs", None))
        self.pushButtonLoadEpochs.setText(_translate("MainWindow", "Load epochs", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEpoching), _translate("MainWindow", "Epoching", None))
        self.groupBoxAvailableAveraging.setTitle(_translate("MainWindow", "Available actions:", None))
        self.groupBoxChannelAverages.setTitle(_translate("MainWindow", "Channel Averages", None))
        self.pushButtonChannelAverages.setText(_translate("MainWindow", "Show channel averages", None))
        self.radioButtonLobe.setText(_translate("MainWindow", "Lobe:", None))
        self.labelChannelAverages.setText(_translate("MainWindow", "Show channel averages for:", None))
        self.radioButtonCustomChannels.setText(_translate("MainWindow", "Custom channels:", None))
        self.pushButtonAverage.setText(_translate("MainWindow", "Average selected epoch collection", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAveraging), _translate("MainWindow", "Averaging", None))
        self.groupBoxAvailableTFR.setTitle(_translate("MainWindow", "Available actions:", None))
        self.pushButtonTFRTopology.setText(_translate("MainWindow", "TFR topology vizualization", None))
        self.pushButtonTFR.setText(_translate("MainWindow", "TFR visualization", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTFR), _translate("MainWindow", "TFR", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionCreate_experiment.setText(_translate("MainWindow", "Create new experiment...", None))
        self.actionOpen_experiment.setText(_translate("MainWindow", "Open experiment...", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionSet_workspace.setText(_translate("MainWindow", "Set workspace...", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

