# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowUi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1683, 1014)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(700, 400))
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(600, 400))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.scrollArea = QtGui.QScrollArea(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(600, 600))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1327, 847))
        self.scrollAreaWidgetContents_3.setMinimumSize(QtCore.QSize(1250, 750))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout_22 = QtGui.QGridLayout()
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents_3)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(200, 400))
        self.tabWidget.setMaximumSize(QtCore.QSize(20000, 16777215))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabPreprocessing = QtGui.QWidget()
        self.tabPreprocessing.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tabPreprocessing.setFont(font)
        self.tabPreprocessing.setObjectName(_fromUtf8("tabPreprocessing"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tabPreprocessing)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 959, 531))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_19 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.groupBoxAvailablePreprocessing = QtGui.QGroupBox(self.gridLayoutWidget_3)
        self.groupBoxAvailablePreprocessing.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBoxAvailablePreprocessing.setObjectName(_fromUtf8("groupBoxAvailablePreprocessing"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBoxAvailablePreprocessing)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.pushButtonEOG = QtGui.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonEOG.setObjectName(_fromUtf8("pushButtonEOG"))
        self.gridLayout_14.addWidget(self.pushButtonEOG, 2, 0, 1, 1)
        self.pushButtonApplyEEG = QtGui.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonApplyEEG.setEnabled(False)
        self.pushButtonApplyEEG.setObjectName(_fromUtf8("pushButtonApplyEEG"))
        self.gridLayout_14.addWidget(self.pushButtonApplyEEG, 3, 1, 1, 1)
        self.pushButtonApplyEOG = QtGui.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonApplyEOG.setEnabled(False)
        self.pushButtonApplyEOG.setObjectName(_fromUtf8("pushButtonApplyEOG"))
        self.gridLayout_14.addWidget(self.pushButtonApplyEOG, 2, 1, 1, 1)
        self.pushButtonApplyECG = QtGui.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonApplyECG.setEnabled(False)
        self.pushButtonApplyECG.setObjectName(_fromUtf8("pushButtonApplyECG"))
        self.gridLayout_14.addWidget(self.pushButtonApplyECG, 1, 1, 1, 1)
        self.pushButtonEEG = QtGui.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonEEG.setObjectName(_fromUtf8("pushButtonEEG"))
        self.gridLayout_14.addWidget(self.pushButtonEEG, 3, 0, 1, 1)
        self.pushButtonECG = QtGui.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonECG.setObjectName(_fromUtf8("pushButtonECG"))
        self.gridLayout_14.addWidget(self.pushButtonECG, 1, 0, 1, 1)
        self.pushButtonFilter = QtGui.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonFilter.setObjectName(_fromUtf8("pushButtonFilter"))
        self.gridLayout_14.addWidget(self.pushButtonFilter, 0, 0, 1, 1)
        self.pushButtonICA = QtGui.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonICA.setObjectName(_fromUtf8("pushButtonICA"))
        self.gridLayout_14.addWidget(self.pushButtonICA, 0, 1, 1, 1)
        self.horizontalLayout_18.addLayout(self.gridLayout_14)
        self.gridLayout_13.addLayout(self.horizontalLayout_18, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBoxAvailablePreprocessing, 1, 0, 1, 1)
        self.groupBoxPreprocessingCheckBoxes = QtGui.QGroupBox(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPreprocessingCheckBoxes.sizePolicy().hasHeightForWidth())
        self.groupBoxPreprocessingCheckBoxes.setSizePolicy(sizePolicy)
        self.groupBoxPreprocessingCheckBoxes.setMinimumSize(QtCore.QSize(60, 0))
        self.groupBoxPreprocessingCheckBoxes.setObjectName(_fromUtf8("groupBoxPreprocessingCheckBoxes"))
        self.gridLayout_18 = QtGui.QGridLayout(self.groupBoxPreprocessingCheckBoxes)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem)
        self.checkBoxMaxFilterApplied = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxMaxFilterApplied.setEnabled(False)
        self.checkBoxMaxFilterApplied.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBoxMaxFilterApplied.setText(_fromUtf8(""))
        self.checkBoxMaxFilterApplied.setObjectName(_fromUtf8("checkBoxMaxFilterApplied"))
        self.horizontalLayout_21.addWidget(self.checkBoxMaxFilterApplied)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem1)
        self.gridLayout_6.addLayout(self.horizontalLayout_21, 1, 2, 1, 1)
        self.labelECGComputed_2 = QtGui.QLabel(self.groupBoxPreprocessingCheckBoxes)
        self.labelECGComputed_2.setObjectName(_fromUtf8("labelECGComputed_2"))
        self.gridLayout_6.addWidget(self.labelECGComputed_2, 2, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.checkBoxMaxFilterComputed = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxMaxFilterComputed.setEnabled(False)
        self.checkBoxMaxFilterComputed.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBoxMaxFilterComputed.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.checkBoxMaxFilterComputed.setText(_fromUtf8(""))
        self.checkBoxMaxFilterComputed.setObjectName(_fromUtf8("checkBoxMaxFilterComputed"))
        self.horizontalLayout_13.addWidget(self.checkBoxMaxFilterComputed)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.gridLayout_6.addLayout(self.horizontalLayout_13, 1, 1, 1, 1)
        self.labelMaxFilter_2 = QtGui.QLabel(self.groupBoxPreprocessingCheckBoxes)
        self.labelMaxFilter_2.setObjectName(_fromUtf8("labelMaxFilter_2"))
        self.gridLayout_6.addWidget(self.labelMaxFilter_2, 1, 0, 1, 1)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem4)
        self.checkBoxECGComputed = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxECGComputed.setEnabled(False)
        self.checkBoxECGComputed.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBoxECGComputed.setText(_fromUtf8(""))
        self.checkBoxECGComputed.setObjectName(_fromUtf8("checkBoxECGComputed"))
        self.horizontalLayout_17.addWidget(self.checkBoxECGComputed)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem5)
        self.gridLayout_6.addLayout(self.horizontalLayout_17, 2, 1, 1, 1)
        self.labelEOGComputed_2 = QtGui.QLabel(self.groupBoxPreprocessingCheckBoxes)
        self.labelEOGComputed_2.setObjectName(_fromUtf8("labelEOGComputed_2"))
        self.gridLayout_6.addWidget(self.labelEOGComputed_2, 3, 0, 1, 1)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem6)
        self.checkBoxEOGApplied = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxEOGApplied.setEnabled(False)
        self.checkBoxEOGApplied.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBoxEOGApplied.setText(_fromUtf8(""))
        self.checkBoxEOGApplied.setObjectName(_fromUtf8("checkBoxEOGApplied"))
        self.horizontalLayout_20.addWidget(self.checkBoxEOGApplied)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem7)
        self.gridLayout_6.addLayout(self.horizontalLayout_20, 3, 2, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem8)
        self.checkBoxECGApplied = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxECGApplied.setEnabled(False)
        self.checkBoxECGApplied.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBoxECGApplied.setText(_fromUtf8(""))
        self.checkBoxECGApplied.setObjectName(_fromUtf8("checkBoxECGApplied"))
        self.horizontalLayout_16.addWidget(self.checkBoxECGApplied)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem9)
        self.gridLayout_6.addLayout(self.horizontalLayout_16, 2, 2, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem10)
        self.checkBoxEOGComputed = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxEOGComputed.setEnabled(False)
        self.checkBoxEOGComputed.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBoxEOGComputed.setText(_fromUtf8(""))
        self.checkBoxEOGComputed.setObjectName(_fromUtf8("checkBoxEOGComputed"))
        self.horizontalLayout_19.addWidget(self.checkBoxEOGComputed)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem11)
        self.gridLayout_6.addLayout(self.horizontalLayout_19, 3, 1, 1, 1)
        self.labelEEGComputed = QtGui.QLabel(self.groupBoxPreprocessingCheckBoxes)
        self.labelEEGComputed.setObjectName(_fromUtf8("labelEEGComputed"))
        self.gridLayout_6.addWidget(self.labelEEGComputed, 4, 0, 1, 1)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem12)
        self.checkBoxEEGComputed = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxEEGComputed.setEnabled(False)
        self.checkBoxEEGComputed.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBoxEEGComputed.setText(_fromUtf8(""))
        self.checkBoxEEGComputed.setObjectName(_fromUtf8("checkBoxEEGComputed"))
        self.horizontalLayout_22.addWidget(self.checkBoxEEGComputed)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem13)
        self.gridLayout_6.addLayout(self.horizontalLayout_22, 4, 1, 1, 1)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem14)
        self.checkBoxEEGApplied = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxEEGApplied.setEnabled(False)
        self.checkBoxEEGApplied.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBoxEEGApplied.setText(_fromUtf8(""))
        self.checkBoxEEGApplied.setObjectName(_fromUtf8("checkBoxEEGApplied"))
        self.horizontalLayout_34.addWidget(self.checkBoxEEGApplied)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem15)
        self.gridLayout_6.addLayout(self.horizontalLayout_34, 4, 2, 1, 1)
        self.labelEOGApplied_2 = QtGui.QLabel(self.groupBoxPreprocessingCheckBoxes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelEOGApplied_2.sizePolicy().hasHeightForWidth())
        self.labelEOGApplied_2.setSizePolicy(sizePolicy)
        self.labelEOGApplied_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEOGApplied_2.setObjectName(_fromUtf8("labelEOGApplied_2"))
        self.gridLayout_6.addWidget(self.labelEOGApplied_2, 0, 2, 1, 1)
        self.labelECGApplied_2 = QtGui.QLabel(self.groupBoxPreprocessingCheckBoxes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelECGApplied_2.sizePolicy().hasHeightForWidth())
        self.labelECGApplied_2.setSizePolicy(sizePolicy)
        self.labelECGApplied_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelECGApplied_2.setObjectName(_fromUtf8("labelECGApplied_2"))
        self.gridLayout_6.addWidget(self.labelECGApplied_2, 0, 1, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBoxPreprocessingCheckBoxes, 0, 0, 1, 1)
        self.groupBoxVisualization_2 = QtGui.QGroupBox(self.gridLayoutWidget_3)
        self.groupBoxVisualization_2.setObjectName(_fromUtf8("groupBoxVisualization_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxVisualization_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.checkBoxShowEvents = QtGui.QCheckBox(self.groupBoxVisualization_2)
        self.checkBoxShowEvents.setObjectName(_fromUtf8("checkBoxShowEvents"))
        self.gridLayout_16.addWidget(self.checkBoxShowEvents, 0, 1, 1, 1)
        self.pushButtonTFRraw = QtGui.QPushButton(self.groupBoxVisualization_2)
        self.pushButtonTFRraw.setObjectName(_fromUtf8("pushButtonTFRraw"))
        self.gridLayout_16.addWidget(self.pushButtonTFRraw, 1, 1, 1, 1)
        self.pushButtonSpectrum = QtGui.QPushButton(self.groupBoxVisualization_2)
        self.pushButtonSpectrum.setObjectName(_fromUtf8("pushButtonSpectrum"))
        self.gridLayout_16.addWidget(self.pushButtonSpectrum, 1, 0, 1, 1)
        self.pushButtonRawPlot = QtGui.QPushButton(self.groupBoxVisualization_2)
        self.pushButtonRawPlot.setObjectName(_fromUtf8("pushButtonRawPlot"))
        self.gridLayout_16.addWidget(self.pushButtonRawPlot, 0, 0, 1, 1)
        self.pushButtonPlotProjections = QtGui.QPushButton(self.groupBoxVisualization_2)
        self.pushButtonPlotProjections.setObjectName(_fromUtf8("pushButtonPlotProjections"))
        self.gridLayout_16.addWidget(self.pushButtonPlotProjections, 1, 2, 1, 1)
        self.horizontalLayout_32.addLayout(self.gridLayout_16)
        self.gridLayout_3.addLayout(self.horizontalLayout_32, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBoxVisualization_2, 2, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.labelBads = QtGui.QLabel(self.gridLayoutWidget_3)
        self.labelBads.setObjectName(_fromUtf8("labelBads"))
        self.verticalLayout_5.addWidget(self.labelBads)
        self.listWidgetBads = QtGui.QListWidget(self.gridLayoutWidget_3)
        self.listWidgetBads.setEnabled(True)
        self.listWidgetBads.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listWidgetBads.setObjectName(_fromUtf8("listWidgetBads"))
        self.verticalLayout_5.addWidget(self.listWidgetBads)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonCustomChannels = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButtonCustomChannels.setObjectName(_fromUtf8("pushButtonCustomChannels"))
        self.horizontalLayout.addWidget(self.pushButtonCustomChannels)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem16)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem17)
        self.gridLayout_19.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.labelProjs = QtGui.QLabel(self.gridLayoutWidget_3)
        self.labelProjs.setObjectName(_fromUtf8("labelProjs"))
        self.verticalLayout_2.addWidget(self.labelProjs)
        self.listWidgetProjs = QtGui.QListWidget(self.gridLayoutWidget_3)
        self.listWidgetProjs.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetProjs.sizePolicy().hasHeightForWidth())
        self.listWidgetProjs.setSizePolicy(sizePolicy)
        self.listWidgetProjs.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidgetProjs.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.listWidgetProjs.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidgetProjs.setObjectName(_fromUtf8("listWidgetProjs"))
        self.verticalLayout_2.addWidget(self.listWidgetProjs)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButtonRemoveProj = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButtonRemoveProj.setObjectName(_fromUtf8("pushButtonRemoveProj"))
        self.horizontalLayout_4.addWidget(self.pushButtonRemoveProj)
        spacerItem18 = QtGui.QSpacerItem(78, 28, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem18)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_19.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tabPreprocessing, _fromUtf8(""))
        self.tabEpoching = QtGui.QWidget()
        self.tabEpoching.setObjectName(_fromUtf8("tabEpoching"))
        self.groupBoxAvailableAveraging_2 = QtGui.QGroupBox(self.tabEpoching)
        self.groupBoxAvailableAveraging_2.setGeometry(QtCore.QRect(10, 510, 500, 240))
        self.groupBoxAvailableAveraging_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBoxAvailableAveraging_2.setMaximumSize(QtCore.QSize(500, 240))
        self.groupBoxAvailableAveraging_2.setObjectName(_fromUtf8("groupBoxAvailableAveraging_2"))
        self.formLayout_12 = QtGui.QFormLayout(self.groupBoxAvailableAveraging_2)
        self.formLayout_12.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_12.setObjectName(_fromUtf8("formLayout_12"))
        self.groupBoxChannelAverages_4 = QtGui.QGroupBox(self.groupBoxAvailableAveraging_2)
        self.groupBoxChannelAverages_4.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBoxChannelAverages_4.setObjectName(_fromUtf8("groupBoxChannelAverages_4"))
        self.formLayout_21 = QtGui.QFormLayout(self.groupBoxChannelAverages_4)
        self.formLayout_21.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_21.setObjectName(_fromUtf8("formLayout_21"))
        self.verticalLayout_34 = QtGui.QVBoxLayout()
        self.verticalLayout_34.setObjectName(_fromUtf8("verticalLayout_34"))
        self.horizontalLayout_42 = QtGui.QHBoxLayout()
        self.horizontalLayout_42.setObjectName(_fromUtf8("horizontalLayout_42"))
        self.label = QtGui.QLabel(self.groupBoxChannelAverages_4)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_42.addWidget(self.label)
        self.comboBoxLobes = QtGui.QComboBox(self.groupBoxChannelAverages_4)
        self.comboBoxLobes.setObjectName(_fromUtf8("comboBoxLobes"))
        self.horizontalLayout_42.addWidget(self.comboBoxLobes)
        self.verticalLayout_34.addLayout(self.horizontalLayout_42)
        self.pushButtonChannelAverages = QtGui.QPushButton(self.groupBoxChannelAverages_4)
        self.pushButtonChannelAverages.setObjectName(_fromUtf8("pushButtonChannelAverages"))
        self.verticalLayout_34.addWidget(self.pushButtonChannelAverages)
        self.formLayout_21.setLayout(0, QtGui.QFormLayout.LabelRole, self.verticalLayout_34)
        self.formLayout_12.setWidget(2, QtGui.QFormLayout.LabelRole, self.groupBoxChannelAverages_4)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.pushButtonVisualizeEpochChannels = QtGui.QPushButton(self.groupBoxAvailableAveraging_2)
        self.pushButtonVisualizeEpochChannels.setObjectName(_fromUtf8("pushButtonVisualizeEpochChannels"))
        self.horizontalLayout_15.addWidget(self.pushButtonVisualizeEpochChannels)
        self.pushButtonEpochsPlot = QtGui.QPushButton(self.groupBoxAvailableAveraging_2)
        self.pushButtonEpochsPlot.setObjectName(_fromUtf8("pushButtonEpochsPlot"))
        self.horizontalLayout_15.addWidget(self.pushButtonEpochsPlot)
        self.formLayout_12.setLayout(1, QtGui.QFormLayout.LabelRole, self.horizontalLayout_15)
        self.frame_6 = QtGui.QFrame(self.tabEpoching)
        self.frame_6.setGeometry(QtCore.QRect(10, 10, 431, 501))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.groupBoxAvailableEpoching = QtGui.QGroupBox(self.frame_6)
        self.groupBoxAvailableEpoching.setGeometry(QtCore.QRect(10, 350, 391, 141))
        self.groupBoxAvailableEpoching.setObjectName(_fromUtf8("groupBoxAvailableEpoching"))
        self.pushButtonCreateEpochs = QtGui.QPushButton(self.groupBoxAvailableEpoching)
        self.pushButtonCreateEpochs.setGeometry(QtCore.QRect(10, 30, 241, 31))
        self.pushButtonCreateEpochs.setObjectName(_fromUtf8("pushButtonCreateEpochs"))
        self.pushButtonDeleteEpochs = QtGui.QPushButton(self.groupBoxAvailableEpoching)
        self.pushButtonDeleteEpochs.setGeometry(QtCore.QRect(10, 70, 241, 31))
        self.pushButtonDeleteEpochs.setObjectName(_fromUtf8("pushButtonDeleteEpochs"))
        self.pushButtonGroupDeleteEpochs = QtGui.QPushButton(self.groupBoxAvailableEpoching)
        self.pushButtonGroupDeleteEpochs.setGeometry(QtCore.QRect(10, 110, 241, 31))
        self.pushButtonGroupDeleteEpochs.setObjectName(_fromUtf8("pushButtonGroupDeleteEpochs"))
        self.layoutWidget = QtGui.QWidget(self.frame_6)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 411, 341))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.groupBoxEpochsEpoching = QtGui.QGroupBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBoxEpochsEpoching.sizePolicy().hasHeightForWidth())
        self.groupBoxEpochsEpoching.setSizePolicy(sizePolicy)
        self.groupBoxEpochsEpoching.setTitle(_fromUtf8(""))
        self.groupBoxEpochsEpoching.setFlat(False)
        self.groupBoxEpochsEpoching.setObjectName(_fromUtf8("groupBoxEpochsEpoching"))
        self.horizontalLayout_26.addWidget(self.groupBoxEpochsEpoching)
        self.frameEpochCollectionParameters = QtGui.QFrame(self.tabEpoching)
        self.frameEpochCollectionParameters.setGeometry(QtCore.QRect(450, 10, 396, 501))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameEpochCollectionParameters.sizePolicy().hasHeightForWidth())
        self.frameEpochCollectionParameters.setSizePolicy(sizePolicy)
        self.frameEpochCollectionParameters.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameEpochCollectionParameters.setFrameShadow(QtGui.QFrame.Raised)
        self.frameEpochCollectionParameters.setLineWidth(1)
        self.frameEpochCollectionParameters.setObjectName(_fromUtf8("frameEpochCollectionParameters"))
        self.formLayout_8 = QtGui.QFormLayout(self.frameEpochCollectionParameters)
        self.formLayout_8.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.label_3 = QtGui.QLabel(self.frameEpochCollectionParameters)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_20.addWidget(self.label_3)
        self.groupBoxEpochTimes = QtGui.QGroupBox(self.frameEpochCollectionParameters)
        self.groupBoxEpochTimes.setObjectName(_fromUtf8("groupBoxEpochTimes"))
        self.formLayout = QtGui.QFormLayout(self.groupBoxEpochTimes)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelTmin = QtGui.QLabel(self.groupBoxEpochTimes)
        self.labelTmin.setMinimumSize(QtCore.QSize(80, 0))
        self.labelTmin.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelTmin.setObjectName(_fromUtf8("labelTmin"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelTmin)
        self.textBrowserTmin = QtGui.QTextBrowser(self.groupBoxEpochTimes)
        self.textBrowserTmin.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserTmin.sizePolicy().hasHeightForWidth())
        self.textBrowserTmin.setSizePolicy(sizePolicy)
        self.textBrowserTmin.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowserTmin.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textBrowserTmin.setSizeIncrement(QtCore.QSize(0, 31))
        self.textBrowserTmin.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserTmin.setPalette(palette)
        self.textBrowserTmin.setFrameShape(QtGui.QFrame.StyledPanel)
        self.textBrowserTmin.setObjectName(_fromUtf8("textBrowserTmin"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.textBrowserTmin)
        self.labelTmax = QtGui.QLabel(self.groupBoxEpochTimes)
        self.labelTmax.setMinimumSize(QtCore.QSize(80, 0))
        self.labelTmax.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelTmax.setObjectName(_fromUtf8("labelTmax"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelTmax)
        self.textBrowserTmax = QtGui.QTextBrowser(self.groupBoxEpochTimes)
        self.textBrowserTmax.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserTmax.sizePolicy().hasHeightForWidth())
        self.textBrowserTmax.setSizePolicy(sizePolicy)
        self.textBrowserTmax.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowserTmax.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textBrowserTmax.setSizeIncrement(QtCore.QSize(0, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserTmax.setPalette(palette)
        self.textBrowserTmax.setObjectName(_fromUtf8("textBrowserTmax"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.textBrowserTmax)
        self.verticalLayout_20.addWidget(self.groupBoxEpochTimes)
        self.groupBoxRejections = QtGui.QGroupBox(self.frameEpochCollectionParameters)
        self.groupBoxRejections.setObjectName(_fromUtf8("groupBoxRejections"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBoxRejections)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelMagReject = QtGui.QLabel(self.groupBoxRejections)
        self.labelMagReject.setMinimumSize(QtCore.QSize(80, 0))
        self.labelMagReject.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelMagReject.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelMagReject.setObjectName(_fromUtf8("labelMagReject"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelMagReject)
        self.textBrowserMag = QtGui.QTextBrowser(self.groupBoxRejections)
        self.textBrowserMag.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserMag.sizePolicy().hasHeightForWidth())
        self.textBrowserMag.setSizePolicy(sizePolicy)
        self.textBrowserMag.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowserMag.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textBrowserMag.setSizeIncrement(QtCore.QSize(0, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserMag.setPalette(palette)
        self.textBrowserMag.setFrameShadow(QtGui.QFrame.Sunken)
        self.textBrowserMag.setObjectName(_fromUtf8("textBrowserMag"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.textBrowserMag)
        self.labelGradReject = QtGui.QLabel(self.groupBoxRejections)
        self.labelGradReject.setMinimumSize(QtCore.QSize(75, 0))
        self.labelGradReject.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelGradReject.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelGradReject.setObjectName(_fromUtf8("labelGradReject"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelGradReject)
        self.textBrowserGrad = QtGui.QTextBrowser(self.groupBoxRejections)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserGrad.sizePolicy().hasHeightForWidth())
        self.textBrowserGrad.setSizePolicy(sizePolicy)
        self.textBrowserGrad.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowserGrad.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserGrad.setPalette(palette)
        self.textBrowserGrad.setObjectName(_fromUtf8("textBrowserGrad"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.textBrowserGrad)
        self.labelEegReject = QtGui.QLabel(self.groupBoxRejections)
        self.labelEegReject.setMinimumSize(QtCore.QSize(75, 0))
        self.labelEegReject.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelEegReject.setObjectName(_fromUtf8("labelEegReject"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelEegReject)
        self.textBrowserEEG = QtGui.QTextBrowser(self.groupBoxRejections)
        self.textBrowserEEG.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserEEG.setPalette(palette)
        self.textBrowserEEG.setObjectName(_fromUtf8("textBrowserEEG"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.textBrowserEEG)
        self.labelEogReject = QtGui.QLabel(self.groupBoxRejections)
        self.labelEogReject.setMinimumSize(QtCore.QSize(75, 0))
        self.labelEogReject.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelEogReject.setObjectName(_fromUtf8("labelEogReject"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelEogReject)
        self.textBrowserEOG = QtGui.QTextBrowser(self.groupBoxRejections)
        self.textBrowserEOG.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserEOG.setPalette(palette)
        self.textBrowserEOG.setObjectName(_fromUtf8("textBrowserEOG"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.textBrowserEOG)
        self.labelStimReject = QtGui.QLabel(self.groupBoxRejections)
        self.labelStimReject.setMinimumSize(QtCore.QSize(75, 0))
        self.labelStimReject.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelStimReject.setObjectName(_fromUtf8("labelStimReject"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.labelStimReject)
        self.textBrowserStim = QtGui.QTextBrowser(self.groupBoxRejections)
        self.textBrowserStim.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserStim.setPalette(palette)
        self.textBrowserStim.setObjectName(_fromUtf8("textBrowserStim"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.textBrowserStim)
        self.verticalLayout_20.addWidget(self.groupBoxRejections)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.labelWorkingFile = QtGui.QLabel(self.frameEpochCollectionParameters)
        self.labelWorkingFile.setMinimumSize(QtCore.QSize(90, 0))
        self.labelWorkingFile.setMaximumSize(QtCore.QSize(16777215, 6000))
        self.labelWorkingFile.setObjectName(_fromUtf8("labelWorkingFile"))
        self.horizontalLayout_8.addWidget(self.labelWorkingFile)
        self.textBrowserWorkingFile = QtGui.QTextBrowser(self.frameEpochCollectionParameters)
        self.textBrowserWorkingFile.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserWorkingFile.setPalette(palette)
        self.textBrowserWorkingFile.setFrameShape(QtGui.QFrame.StyledPanel)
        self.textBrowserWorkingFile.setObjectName(_fromUtf8("textBrowserWorkingFile"))
        self.horizontalLayout_8.addWidget(self.textBrowserWorkingFile)
        self.verticalLayout_20.addLayout(self.horizontalLayout_8)
        self.formLayout_8.setLayout(0, QtGui.QFormLayout.LabelRole, self.verticalLayout_20)
        self.tabWidget.addTab(self.tabEpoching, _fromUtf8(""))
        self.tabAveraging = QtGui.QWidget()
        self.tabAveraging.setObjectName(_fromUtf8("tabAveraging"))
        self.layoutWidget1 = QtGui.QWidget(self.tabAveraging)
        self.layoutWidget1.setGeometry(QtCore.QRect(9, 9, 1191, 630))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_15 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.groupBoxEpochsAveraging = QtGui.QGroupBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxEpochsAveraging.sizePolicy().hasHeightForWidth())
        self.groupBoxEpochsAveraging.setSizePolicy(sizePolicy)
        self.groupBoxEpochsAveraging.setMinimumSize(QtCore.QSize(0, 380))
        self.groupBoxEpochsAveraging.setTitle(_fromUtf8(""))
        self.groupBoxEpochsAveraging.setObjectName(_fromUtf8("groupBoxEpochsAveraging"))
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBoxEpochsAveraging)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.verticalLayout_23.addWidget(self.groupBoxEpochsAveraging)
        self.gridLayout_15.addLayout(self.verticalLayout_23, 0, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_4.addItem(spacerItem19)
        self.pushButtonCreateEvoked = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCreateEvoked.sizePolicy().hasHeightForWidth())
        self.pushButtonCreateEvoked.setSizePolicy(sizePolicy)
        self.pushButtonCreateEvoked.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.pushButtonCreateEvoked.setObjectName(_fromUtf8("pushButtonCreateEvoked"))
        self.verticalLayout_4.addWidget(self.pushButtonCreateEvoked)
        self.pushButtonCreateEvokedBatch = QtGui.QPushButton(self.layoutWidget1)
        self.pushButtonCreateEvokedBatch.setObjectName(_fromUtf8("pushButtonCreateEvokedBatch"))
        self.verticalLayout_4.addWidget(self.pushButtonCreateEvokedBatch)
        self.widget = QtGui.QWidget(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_4.addWidget(self.widget)
        self.gridLayout_15.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBoxEvokeds2 = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBoxEvokeds2.setMinimumSize(QtCore.QSize(0, 300))
        self.groupBoxEvokeds2.setObjectName(_fromUtf8("groupBoxEvokeds2"))
        self.listWidgetEvoked = QtGui.QListWidget(self.groupBoxEvokeds2)
        self.listWidgetEvoked.setGeometry(QtCore.QRect(20, 30, 361, 111))
        self.listWidgetEvoked.setObjectName(_fromUtf8("listWidgetEvoked"))
        self.textBrowserEvokedInfo = QtGui.QTextBrowser(self.groupBoxEvokeds2)
        self.textBrowserEvokedInfo.setGeometry(QtCore.QRect(20, 180, 361, 111))
        self.textBrowserEvokedInfo.setObjectName(_fromUtf8("textBrowserEvokedInfo"))
        self.labelEvokedInfo = QtGui.QLabel(self.groupBoxEvokeds2)
        self.labelEvokedInfo.setGeometry(QtCore.QRect(0, 150, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelEvokedInfo.setFont(font)
        self.labelEvokedInfo.setObjectName(_fromUtf8("labelEvokedInfo"))
        self.verticalLayout_6.addWidget(self.groupBoxEvokeds2)
        self.groupBox = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_21 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButtonVisualizeEvokedDataset = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonVisualizeEvokedDataset.setObjectName(_fromUtf8("pushButtonVisualizeEvokedDataset"))
        self.horizontalLayout_2.addWidget(self.pushButtonVisualizeEvokedDataset)
        self.pushButtonEvokedTopomaps = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonEvokedTopomaps.setObjectName(_fromUtf8("pushButtonEvokedTopomaps"))
        self.horizontalLayout_2.addWidget(self.pushButtonEvokedTopomaps)
        self.gridLayout_21.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButtonDeleteEvoked = QtGui.QPushButton(self.groupBox)
        self.pushButtonDeleteEvoked.setObjectName(_fromUtf8("pushButtonDeleteEvoked"))
        self.gridLayout.addWidget(self.pushButtonDeleteEvoked, 1, 0, 1, 1)
        self.pushButtonGroupDeleteEvoked = QtGui.QPushButton(self.groupBox)
        self.pushButtonGroupDeleteEvoked.setObjectName(_fromUtf8("pushButtonGroupDeleteEvoked"))
        self.gridLayout.addWidget(self.pushButtonGroupDeleteEvoked, 2, 0, 1, 1)
        self.pushButtonGroupAverage = QtGui.QPushButton(self.groupBox)
        self.pushButtonGroupAverage.setObjectName(_fromUtf8("pushButtonGroupAverage"))
        self.gridLayout.addWidget(self.pushButtonGroupAverage, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_20 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButtonSaveEvoked = QtGui.QPushButton(self.groupBox_5)
        self.pushButtonSaveEvoked.setObjectName(_fromUtf8("pushButtonSaveEvoked"))
        self.horizontalLayout_3.addWidget(self.pushButtonSaveEvoked)
        self.pushButtonGroupSaveEvoked = QtGui.QPushButton(self.groupBox_5)
        self.pushButtonGroupSaveEvoked.setObjectName(_fromUtf8("pushButtonGroupSaveEvoked"))
        self.horizontalLayout_3.addWidget(self.pushButtonGroupSaveEvoked)
        self.gridLayout_20.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.gridLayout_15.addLayout(self.verticalLayout_6, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tabAveraging, _fromUtf8(""))
        self.tabSpectralAnalysis = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabSpectralAnalysis.sizePolicy().hasHeightForWidth())
        self.tabSpectralAnalysis.setSizePolicy(sizePolicy)
        self.tabSpectralAnalysis.setObjectName(_fromUtf8("tabSpectralAnalysis"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabSpectralAnalysis)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBoxEpochsTFR = QtGui.QGroupBox(self.tabSpectralAnalysis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxEpochsTFR.sizePolicy().hasHeightForWidth())
        self.groupBoxEpochsTFR.setSizePolicy(sizePolicy)
        self.groupBoxEpochsTFR.setTitle(_fromUtf8(""))
        self.groupBoxEpochsTFR.setObjectName(_fromUtf8("groupBoxEpochsTFR"))
        self.groupBoxAvailableTFR = QtGui.QGroupBox(self.groupBoxEpochsTFR)
        self.groupBoxAvailableTFR.setGeometry(QtCore.QRect(10, 310, 500, 180))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBoxAvailableTFR.sizePolicy().hasHeightForWidth())
        self.groupBoxAvailableTFR.setSizePolicy(sizePolicy)
        self.groupBoxAvailableTFR.setMaximumSize(QtCore.QSize(500, 180))
        self.groupBoxAvailableTFR.setObjectName(_fromUtf8("groupBoxAvailableTFR"))
        self.gridLayout_27 = QtGui.QGridLayout(self.groupBoxAvailableTFR)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.pushButtonTFRTopology = QtGui.QPushButton(self.groupBoxAvailableTFR)
        self.pushButtonTFRTopology.setObjectName(_fromUtf8("pushButtonTFRTopology"))
        self.gridLayout_27.addWidget(self.pushButtonTFRTopology, 2, 0, 1, 1)
        self.pushButtonTFR = QtGui.QPushButton(self.groupBoxAvailableTFR)
        self.pushButtonTFR.setObjectName(_fromUtf8("pushButtonTFR"))
        self.gridLayout_27.addWidget(self.pushButtonTFR, 1, 0, 1, 1)
        self.pushButtonSpectrumEpochs = QtGui.QPushButton(self.groupBoxAvailableTFR)
        self.pushButtonSpectrumEpochs.setObjectName(_fromUtf8("pushButtonSpectrumEpochs"))
        self.gridLayout_27.addWidget(self.pushButtonSpectrumEpochs, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBoxEpochsTFR)
        self.horizontalLayout_33.addLayout(self.verticalLayout)
        self.line = QtGui.QFrame(self.tabSpectralAnalysis)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_33.addWidget(self.line)
        self.groupBoxEpochParamsTFR = QtGui.QGroupBox(self.tabSpectralAnalysis)
        self.groupBoxEpochParamsTFR.setTitle(_fromUtf8(""))
        self.groupBoxEpochParamsTFR.setObjectName(_fromUtf8("groupBoxEpochParamsTFR"))
        self.horizontalLayout_33.addWidget(self.groupBoxEpochParamsTFR)
        self.gridLayout_8.addLayout(self.horizontalLayout_33, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabSpectralAnalysis, _fromUtf8(""))
        self.tabSourceAnalysis = QtGui.QWidget()
        self.tabSourceAnalysis.setObjectName(_fromUtf8("tabSourceAnalysis"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tabSourceAnalysis)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.tabWidget.addTab(self.tabSourceAnalysis, _fromUtf8(""))
        self.gridLayout_22.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_22, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.textEditConsole = QtGui.QTextEdit(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textEditConsole.sizePolicy().hasHeightForWidth())
        self.textEditConsole.setSizePolicy(sizePolicy)
        self.textEditConsole.setReadOnly(True)
        self.textEditConsole.setObjectName(_fromUtf8("textEditConsole"))
        self.gridLayout_7.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1683, 24))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidgetSubjects = QtGui.QDockWidget(MainWindow)
        self.dockWidgetSubjects.setMinimumSize(QtCore.QSize(330, 757))
        self.dockWidgetSubjects.setFloating(False)
        self.dockWidgetSubjects.setFeatures(QtGui.QDockWidget.DockWidgetFloatable)
        self.dockWidgetSubjects.setObjectName(_fromUtf8("dockWidgetSubjects"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_9 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.groupBoxSubjectInfo = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBoxSubjectInfo.setObjectName(_fromUtf8("groupBoxSubjectInfo"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBoxSubjectInfo)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.labelEvents = QtGui.QLabel(self.groupBoxSubjectInfo)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelEvents.setFont(font)
        self.labelEvents.setObjectName(_fromUtf8("labelEvents"))
        self.gridLayout_10.addWidget(self.labelEvents, 3, 0, 1, 1)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.labelFilters = QtGui.QLabel(self.groupBoxSubjectInfo)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelFilters.setFont(font)
        self.labelFilters.setObjectName(_fromUtf8("labelFilters"))
        self.verticalLayout_12.addWidget(self.labelFilters)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.labelLow = QtGui.QLabel(self.groupBoxSubjectInfo)
        self.labelLow.setLineWidth(1)
        self.labelLow.setScaledContents(True)
        self.labelLow.setWordWrap(False)
        self.labelLow.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelLow.setObjectName(_fromUtf8("labelLow"))
        self.horizontalLayout_30.addWidget(self.labelLow)
        self.labelLowValue = QtGui.QLabel(self.groupBoxSubjectInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLowValue.sizePolicy().hasHeightForWidth())
        self.labelLowValue.setSizePolicy(sizePolicy)
        self.labelLowValue.setText(_fromUtf8(""))
        self.labelLowValue.setWordWrap(True)
        self.labelLowValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelLowValue.setObjectName(_fromUtf8("labelLowValue"))
        self.horizontalLayout_30.addWidget(self.labelLowValue)
        self.verticalLayout_12.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.labelHigh = QtGui.QLabel(self.groupBoxSubjectInfo)
        self.labelHigh.setWordWrap(False)
        self.labelHigh.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelHigh.setObjectName(_fromUtf8("labelHigh"))
        self.horizontalLayout_31.addWidget(self.labelHigh)
        self.labelHighValue = QtGui.QLabel(self.groupBoxSubjectInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHighValue.sizePolicy().hasHeightForWidth())
        self.labelHighValue.setSizePolicy(sizePolicy)
        self.labelHighValue.setText(_fromUtf8(""))
        self.labelHighValue.setWordWrap(True)
        self.labelHighValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelHighValue.setObjectName(_fromUtf8("labelHighValue"))
        self.horizontalLayout_31.addWidget(self.labelHighValue)
        self.verticalLayout_12.addLayout(self.horizontalLayout_31)
        self.gridLayout_10.addLayout(self.verticalLayout_12, 1, 0, 1, 1)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.labelChannels = QtGui.QLabel(self.groupBoxSubjectInfo)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelChannels.setFont(font)
        self.labelChannels.setObjectName(_fromUtf8("labelChannels"))
        self.verticalLayout_11.addWidget(self.labelChannels)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.labelEEG = QtGui.QLabel(self.groupBoxSubjectInfo)
        self.labelEEG.setWordWrap(False)
        self.labelEEG.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelEEG.setObjectName(_fromUtf8("labelEEG"))
        self.horizontalLayout_25.addWidget(self.labelEEG)
        self.labelEEGValue = QtGui.QLabel(self.groupBoxSubjectInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelEEGValue.sizePolicy().hasHeightForWidth())
        self.labelEEGValue.setSizePolicy(sizePolicy)
        self.labelEEGValue.setText(_fromUtf8(""))
        self.labelEEGValue.setWordWrap(True)
        self.labelEEGValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelEEGValue.setObjectName(_fromUtf8("labelEEGValue"))
        self.horizontalLayout_25.addWidget(self.labelEEGValue)
        self.verticalLayout_11.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.labelGradMEG = QtGui.QLabel(self.groupBoxSubjectInfo)
        self.labelGradMEG.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelGradMEG.setObjectName(_fromUtf8("labelGradMEG"))
        self.horizontalLayout_27.addWidget(self.labelGradMEG)
        self.labelGradMEGValue = QtGui.QLabel(self.groupBoxSubjectInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelGradMEGValue.sizePolicy().hasHeightForWidth())
        self.labelGradMEGValue.setSizePolicy(sizePolicy)
        self.labelGradMEGValue.setText(_fromUtf8(""))
        self.labelGradMEGValue.setWordWrap(True)
        self.labelGradMEGValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelGradMEGValue.setObjectName(_fromUtf8("labelGradMEGValue"))
        self.horizontalLayout_27.addWidget(self.labelGradMEGValue)
        self.verticalLayout_11.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.labelMagMEG = QtGui.QLabel(self.groupBoxSubjectInfo)
        self.labelMagMEG.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelMagMEG.setObjectName(_fromUtf8("labelMagMEG"))
        self.horizontalLayout_28.addWidget(self.labelMagMEG)
        self.labelMagMEGValue = QtGui.QLabel(self.groupBoxSubjectInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMagMEGValue.sizePolicy().hasHeightForWidth())
        self.labelMagMEGValue.setSizePolicy(sizePolicy)
        self.labelMagMEGValue.setText(_fromUtf8(""))
        self.labelMagMEGValue.setWordWrap(True)
        self.labelMagMEGValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelMagMEGValue.setObjectName(_fromUtf8("labelMagMEGValue"))
        self.horizontalLayout_28.addWidget(self.labelMagMEGValue)
        self.verticalLayout_11.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.labelSamples = QtGui.QLabel(self.groupBoxSubjectInfo)
        self.labelSamples.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelSamples.setObjectName(_fromUtf8("labelSamples"))
        self.horizontalLayout_29.addWidget(self.labelSamples)
        self.labelSamplesValue = QtGui.QLabel(self.groupBoxSubjectInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSamplesValue.sizePolicy().hasHeightForWidth())
        self.labelSamplesValue.setSizePolicy(sizePolicy)
        self.labelSamplesValue.setText(_fromUtf8(""))
        self.labelSamplesValue.setWordWrap(True)
        self.labelSamplesValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelSamplesValue.setObjectName(_fromUtf8("labelSamplesValue"))
        self.horizontalLayout_29.addWidget(self.labelSamplesValue)
        self.verticalLayout_11.addLayout(self.horizontalLayout_29)
        self.gridLayout_10.addLayout(self.verticalLayout_11, 2, 0, 1, 1)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.labelSubjectGeneral = QtGui.QLabel(self.groupBoxSubjectInfo)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelSubjectGeneral.setFont(font)
        self.labelSubjectGeneral.setTextFormat(QtCore.Qt.AutoText)
        self.labelSubjectGeneral.setObjectName(_fromUtf8("labelSubjectGeneral"))
        self.verticalLayout_9.addWidget(self.labelSubjectGeneral)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.labelSubject = QtGui.QLabel(self.groupBoxSubjectInfo)
        self.labelSubject.setWordWrap(False)
        self.labelSubject.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelSubject.setObjectName(_fromUtf8("labelSubject"))
        self.horizontalLayout_23.addWidget(self.labelSubject)
        self.labelSubjectValue = QtGui.QLabel(self.groupBoxSubjectInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSubjectValue.sizePolicy().hasHeightForWidth())
        self.labelSubjectValue.setSizePolicy(sizePolicy)
        self.labelSubjectValue.setText(_fromUtf8(""))
        self.labelSubjectValue.setWordWrap(True)
        self.labelSubjectValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelSubjectValue.setObjectName(_fromUtf8("labelSubjectValue"))
        self.horizontalLayout_23.addWidget(self.labelSubjectValue)
        self.verticalLayout_9.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.labelDate = QtGui.QLabel(self.groupBoxSubjectInfo)
        self.labelDate.setWordWrap(False)
        self.labelDate.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelDate.setObjectName(_fromUtf8("labelDate"))
        self.horizontalLayout_24.addWidget(self.labelDate)
        self.labelDateValue = QtGui.QLabel(self.groupBoxSubjectInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDateValue.sizePolicy().hasHeightForWidth())
        self.labelDateValue.setSizePolicy(sizePolicy)
        self.labelDateValue.setText(_fromUtf8(""))
        self.labelDateValue.setWordWrap(True)
        self.labelDateValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelDateValue.setObjectName(_fromUtf8("labelDateValue"))
        self.horizontalLayout_24.addWidget(self.labelDateValue)
        self.verticalLayout_9.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        self.labelLength = QtGui.QLabel(self.groupBoxSubjectInfo)
        self.labelLength.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelLength.setObjectName(_fromUtf8("labelLength"))
        self.horizontalLayout_40.addWidget(self.labelLength)
        self.labelLengthValue = QtGui.QLabel(self.groupBoxSubjectInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLengthValue.sizePolicy().hasHeightForWidth())
        self.labelLengthValue.setSizePolicy(sizePolicy)
        self.labelLengthValue.setText(_fromUtf8(""))
        self.labelLengthValue.setObjectName(_fromUtf8("labelLengthValue"))
        self.horizontalLayout_40.addWidget(self.labelLengthValue)
        self.verticalLayout_9.addLayout(self.horizontalLayout_40)
        self.gridLayout_10.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.textBrowserEvents = QtGui.QTextBrowser(self.groupBoxSubjectInfo)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserEvents.setPalette(palette)
        self.textBrowserEvents.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowserEvents.setObjectName(_fromUtf8("textBrowserEvents"))
        self.gridLayout_10.addWidget(self.textBrowserEvents, 4, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBoxSubjectInfo, 1, 0, 1, 1)
        self.groupBoxSubject_2 = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBoxSubject_2.setObjectName(_fromUtf8("groupBoxSubject_2"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBoxSubject_2)
        self.gridLayout_12.setMargin(9)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pushButtonActivateSubject = QtGui.QPushButton(self.groupBoxSubject_2)
        self.pushButtonActivateSubject.setObjectName(_fromUtf8("pushButtonActivateSubject"))
        self.gridLayout_5.addWidget(self.pushButtonActivateSubject, 0, 0, 1, 1)
        self.pushButtonAddSubjects = QtGui.QPushButton(self.groupBoxSubject_2)
        self.pushButtonAddSubjects.setObjectName(_fromUtf8("pushButtonAddSubjects"))
        self.gridLayout_5.addWidget(self.pushButtonAddSubjects, 0, 1, 1, 1)
        self.pushButtonRemoveSubject = QtGui.QPushButton(self.groupBoxSubject_2)
        self.pushButtonRemoveSubject.setObjectName(_fromUtf8("pushButtonRemoveSubject"))
        self.gridLayout_5.addWidget(self.pushButtonRemoveSubject, 1, 0, 1, 1)
        self.pushButtonLayout = QtGui.QPushButton(self.groupBoxSubject_2)
        self.pushButtonLayout.setObjectName(_fromUtf8("pushButtonLayout"))
        self.gridLayout_5.addWidget(self.pushButtonLayout, 1, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.listWidgetSubjects = QtGui.QListWidget(self.groupBoxSubject_2)
        self.listWidgetSubjects.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidgetSubjects.setObjectName(_fromUtf8("listWidgetSubjects"))
        self.gridLayout_12.addWidget(self.listWidgetSubjects, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBoxSubject_2, 0, 0, 1, 1)
        self.dockWidgetSubjects.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidgetSubjects)
        self.actionCreate_experiment = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolBarIcons/images/createExperiment.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_experiment.setIcon(icon)
        self.actionCreate_experiment.setObjectName(_fromUtf8("actionCreate_experiment"))
        self.actionOpen_experiment = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolBarIcons/images/openExperiment.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_experiment.setIcon(icon1)
        self.actionOpen_experiment.setObjectName(_fromUtf8("actionOpen_experiment"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionSet_workspace = QtGui.QAction(MainWindow)
        self.actionSet_workspace.setObjectName(_fromUtf8("actionSet_workspace"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionShowExperimentInfo = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolBarIcons/images/showExperimentInfo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShowExperimentInfo.setIcon(icon2)
        self.actionShowExperimentInfo.setObjectName(_fromUtf8("actionShowExperimentInfo"))
        self.actionHide_Show_subject_list_and_info = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolBarIcons/images/subjectList.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHide_Show_subject_list_and_info.setIcon(icon3)
        self.actionHide_Show_subject_list_and_info.setObjectName(_fromUtf8("actionHide_Show_subject_list_and_info"))
        self.actionDirectToConsole = QtGui.QAction(MainWindow)
        self.actionDirectToConsole.setCheckable(True)
        self.actionDirectToConsole.setChecked(True)
        self.actionDirectToConsole.setObjectName(_fromUtf8("actionDirectToConsole"))
        self.actionShow_log = QtGui.QAction(MainWindow)
        self.actionShow_log.setObjectName(_fromUtf8("actionShow_log"))
        self.menuFile.addAction(self.actionCreate_experiment)
        self.menuFile.addAction(self.actionOpen_experiment)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionShowExperimentInfo)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuTools.addAction(self.actionDirectToConsole)
        self.menuTools.addAction(self.actionShow_log)
        self.menuTools.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionCreate_experiment)
        self.toolBar.addAction(self.actionOpen_experiment)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionShowExperimentInfo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHide_Show_subject_list_and_info)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.scrollArea, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.pushButtonCreateEpochs)
        MainWindow.setTabOrder(self.pushButtonCreateEpochs, self.pushButtonDeleteEpochs)
        MainWindow.setTabOrder(self.pushButtonDeleteEpochs, self.textBrowserTmin)
        MainWindow.setTabOrder(self.textBrowserTmin, self.textBrowserTmax)
        MainWindow.setTabOrder(self.textBrowserTmax, self.textBrowserMag)
        MainWindow.setTabOrder(self.textBrowserMag, self.textBrowserGrad)
        MainWindow.setTabOrder(self.textBrowserGrad, self.textBrowserEEG)
        MainWindow.setTabOrder(self.textBrowserEEG, self.textBrowserEOG)
        MainWindow.setTabOrder(self.textBrowserEOG, self.textBrowserStim)
        MainWindow.setTabOrder(self.textBrowserStim, self.textBrowserWorkingFile)
        MainWindow.setTabOrder(self.textBrowserWorkingFile, self.pushButtonVisualizeEpochChannels)
        MainWindow.setTabOrder(self.pushButtonVisualizeEpochChannels, self.pushButtonEpochsPlot)
        MainWindow.setTabOrder(self.pushButtonEpochsPlot, self.comboBoxLobes)
        MainWindow.setTabOrder(self.comboBoxLobes, self.pushButtonChannelAverages)
        MainWindow.setTabOrder(self.pushButtonChannelAverages, self.pushButtonCreateEvoked)
        MainWindow.setTabOrder(self.pushButtonCreateEvoked, self.pushButtonDeleteEvoked)
        MainWindow.setTabOrder(self.pushButtonDeleteEvoked, self.pushButtonTFR)
        MainWindow.setTabOrder(self.pushButtonTFR, self.pushButtonTFRTopology)
        MainWindow.setTabOrder(self.pushButtonTFRTopology, self.textEditConsole)
        MainWindow.setTabOrder(self.textEditConsole, self.textBrowserEvents)
        MainWindow.setTabOrder(self.textBrowserEvents, self.pushButtonActivateSubject)
        MainWindow.setTabOrder(self.pushButtonActivateSubject, self.pushButtonAddSubjects)
        MainWindow.setTabOrder(self.pushButtonAddSubjects, self.pushButtonRemoveSubject)
        MainWindow.setTabOrder(self.pushButtonRemoveSubject, self.listWidgetSubjects)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Meggie", None))
        self.groupBoxAvailablePreprocessing.setTitle(_translate("MainWindow", "Available actions:", None))
        self.pushButtonEOG.setText(_translate("MainWindow", "Calculate EOG projections...", None))
        self.pushButtonApplyEEG.setText(_translate("MainWindow", "Apply ocular projections...", None))
        self.pushButtonApplyEOG.setText(_translate("MainWindow", "Apply EOG projections...", None))
        self.pushButtonApplyECG.setText(_translate("MainWindow", "Apply ECG projections...", None))
        self.pushButtonEEG.setText(_translate("MainWindow", "Calculate ocular projections...", None))
        self.pushButtonECG.setText(_translate("MainWindow", "Calculate ECG projections...", None))
        self.pushButtonFilter.setText(_translate("MainWindow", "Filter...", None))
        self.pushButtonICA.setText(_translate("MainWindow", "ICA...", None))
        self.groupBoxPreprocessingCheckBoxes.setTitle(_translate("MainWindow", "Preprocessing steps completed:", None))
        self.labelECGComputed_2.setText(_translate("MainWindow", "ECG projections", None))
        self.labelMaxFilter_2.setText(_translate("MainWindow", "MaxFilter", None))
        self.labelEOGComputed_2.setText(_translate("MainWindow", "EOG projections", None))
        self.labelEEGComputed.setText(_translate("MainWindow", "Ocular projections", None))
        self.labelEOGApplied_2.setText(_translate("MainWindow", "Applied", None))
        self.labelECGApplied_2.setText(_translate("MainWindow", "Computed", None))
        self.groupBoxVisualization_2.setTitle(_translate("MainWindow", "Visualization:", None))
        self.checkBoxShowEvents.setText(_translate("MainWindow", "Show events", None))
        self.pushButtonTFRraw.setText(_translate("MainWindow", "TFR", None))
        self.pushButtonSpectrum.setText(_translate("MainWindow", "Power spectrum", None))
        self.pushButtonRawPlot.setText(_translate("MainWindow", "Raw plot", None))
        self.pushButtonPlotProjections.setText(_translate("MainWindow", "Plot projections", None))
        self.labelBads.setText(_translate("MainWindow", "Bad channels", None))
        self.listWidgetBads.setSortingEnabled(True)
        self.pushButtonCustomChannels.setText(_translate("MainWindow", "Customize channels...", None))
        self.labelProjs.setText(_translate("MainWindow", "Added projection items", None))
        self.listWidgetProjs.setSortingEnabled(False)
        self.pushButtonRemoveProj.setText(_translate("MainWindow", "Remove", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPreprocessing), _translate("MainWindow", "Preprocessing", None))
        self.groupBoxAvailableAveraging_2.setTitle(_translate("MainWindow", "Visualization for epoch collections:", None))
        self.groupBoxChannelAverages_4.setTitle(_translate("MainWindow", "Channel Averages", None))
        self.label.setText(_translate("MainWindow", "Lobe:", None))
        self.pushButtonChannelAverages.setText(_translate("MainWindow", "Show channel averages", None))
        self.pushButtonVisualizeEpochChannels.setText(_translate("MainWindow", "Visualize epochs in selected channels...", None))
        self.pushButtonEpochsPlot.setText(_translate("MainWindow", "Epochs plot", None))
        self.groupBoxAvailableEpoching.setTitle(_translate("MainWindow", "Available actions for epoch collections:", None))
        self.pushButtonCreateEpochs.setText(_translate("MainWindow", "Create new collection...", None))
        self.pushButtonDeleteEpochs.setText(_translate("MainWindow", "Delete selected collection", None))
        self.pushButtonGroupDeleteEpochs.setText(_translate("MainWindow", "Group delete selected collection", None))
        self.label_3.setText(_translate("MainWindow", "Parameters of the selected epoch collection:", None))
        self.groupBoxEpochTimes.setTitle(_translate("MainWindow", "Time limits:", None))
        self.labelTmin.setText(_translate("MainWindow", "Start time:", None))
        self.labelTmax.setText(_translate("MainWindow", "End time:", None))
        self.groupBoxRejections.setTitle(_translate("MainWindow", "Rejection parameters:", None))
        self.labelMagReject.setText(_translate("MainWindow", "Mag:", None))
        self.labelGradReject.setText(_translate("MainWindow", "Grad:", None))
        self.labelEegReject.setText(_translate("MainWindow", "EEG:", None))
        self.labelEogReject.setText(_translate("MainWindow", "EOG:", None))
        self.labelStimReject.setText(_translate("MainWindow", "Stim:", None))
        self.labelWorkingFile.setText(_translate("MainWindow", "Source file:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEpoching), _translate("MainWindow", "Epoching", None))
        self.pushButtonCreateEvoked.setText(_translate("MainWindow", "------ Create evoked dataset ----->", None))
        self.pushButtonCreateEvokedBatch.setText(_translate("MainWindow", "----------  Batch evokeds --------->", None))
        self.groupBoxEvokeds2.setTitle(_translate("MainWindow", "Evoked datasets (averaged epoch collections):", None))
        self.labelEvokedInfo.setText(_translate("MainWindow", "Evoked info", None))
        self.groupBox.setTitle(_translate("MainWindow", "Available actions for evoked datasets:", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Visualization:", None))
        self.pushButtonVisualizeEvokedDataset.setText(_translate("MainWindow", "Visualize selected dataset(s)", None))
        self.pushButtonEvokedTopomaps.setText(_translate("MainWindow", "Plot evoked topomaps", None))
        self.pushButtonDeleteEvoked.setText(_translate("MainWindow", "Delete selected dataset", None))
        self.pushButtonGroupDeleteEvoked.setText(_translate("MainWindow", "Group delete selected dataset", None))
        self.pushButtonGroupAverage.setText(_translate("MainWindow", "Group average for all subjects", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Saving:", None))
        self.pushButtonSaveEvoked.setText(_translate("MainWindow", "Save evoked data", None))
        self.pushButtonGroupSaveEvoked.setText(_translate("MainWindow", "Group save evoked data", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAveraging), _translate("MainWindow", "Averaging", None))
        self.groupBoxAvailableTFR.setTitle(_translate("MainWindow", "Available actions:", None))
        self.pushButtonTFRTopology.setText(_translate("MainWindow", "TFR topology", None))
        self.pushButtonTFR.setText(_translate("MainWindow", "One-channel TFR", None))
        self.pushButtonSpectrumEpochs.setText(_translate("MainWindow", "Power spectrum", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpectralAnalysis), _translate("MainWindow", "Spectral analysis", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSourceAnalysis), _translate("MainWindow", "Source analysis", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.groupBoxSubjectInfo.setTitle(_translate("MainWindow", "Subject info", None))
        self.labelEvents.setText(_translate("MainWindow", "Events:", None))
        self.labelFilters.setText(_translate("MainWindow", "Filters:", None))
        self.labelLow.setText(_translate("MainWindow", "Low-pass:", None))
        self.labelHigh.setText(_translate("MainWindow", "High-pass:", None))
        self.labelChannels.setText(_translate("MainWindow", "Channels:", None))
        self.labelEEG.setText(_translate("MainWindow", "EEG channels:", None))
        self.labelGradMEG.setText(_translate("MainWindow", "Gradiometers:", None))
        self.labelMagMEG.setText(_translate("MainWindow", "Magnetometers:", None))
        self.labelSamples.setText(_translate("MainWindow", "Sampling frequency:", None))
        self.labelSubjectGeneral.setText(_translate("MainWindow", "General:", None))
        self.labelSubject.setText(_translate("MainWindow", "Name:", None))
        self.labelDate.setText(_translate("MainWindow", "Date:", None))
        self.labelLength.setText(_translate("MainWindow", "Length:", None))
        self.groupBoxSubject_2.setTitle(_translate("MainWindow", "Subjects (active in bold):", None))
        self.pushButtonActivateSubject.setText(_translate("MainWindow", "Activate selected", None))
        self.pushButtonAddSubjects.setText(_translate("MainWindow", "Add new...", None))
        self.pushButtonRemoveSubject.setText(_translate("MainWindow", "Remove selected", None))
        self.pushButtonLayout.setText(_translate("MainWindow", "Change layout...", None))
        self.actionCreate_experiment.setText(_translate("MainWindow", "Create New Experiment...", None))
        self.actionOpen_experiment.setText(_translate("MainWindow", "Open Experiment...", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionSet_workspace.setText(_translate("MainWindow", "Set Workspace...", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionShowExperimentInfo.setText(_translate("MainWindow", "Show experiment info", None))
        self.actionShowExperimentInfo.setToolTip(_translate("MainWindow", "Show more info about experiment", None))
        self.actionHide_Show_subject_list_and_info.setText(_translate("MainWindow", "Hide/show subject list and info", None))
        self.actionHide_Show_subject_list_and_info.setToolTip(_translate("MainWindow", "Hide/show subject list and info", None))
        self.actionDirectToConsole.setText(_translate("MainWindow", "Direct output to console", None))
        self.actionShow_log.setText(_translate("MainWindow", "Show log", None))

