# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../preferencesDialogUi.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogPreferences(object):
    def setupUi(self, DialogPreferences):
        DialogPreferences.setObjectName("DialogPreferences")
        DialogPreferences.resize(494, 532)
        self.gridLayout_3 = QtWidgets.QGridLayout(DialogPreferences)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBoxWorkingDirectory = QtWidgets.QGroupBox(DialogPreferences)
        self.groupBoxWorkingDirectory.setObjectName("groupBoxWorkingDirectory")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxWorkingDirectory)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBoxWorkingDirectory)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LineEditFilePath = QtWidgets.QLineEdit(self.groupBoxWorkingDirectory)
        self.LineEditFilePath.setObjectName("LineEditFilePath")
        self.horizontalLayout.addWidget(self.LineEditFilePath)
        self.ButtonBrowseWorkingDir = QtWidgets.QPushButton(self.groupBoxWorkingDirectory)
        self.ButtonBrowseWorkingDir.setObjectName("ButtonBrowseWorkingDir")
        self.horizontalLayout.addWidget(self.ButtonBrowseWorkingDir)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBoxWorkingDirectory, 0, 0, 1, 1)
        self.groupBoxEnv = QtWidgets.QGroupBox(DialogPreferences)
        self.groupBoxEnv.setObjectName("groupBoxEnv")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxEnv)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelFreeSurferHome = QtWidgets.QLabel(self.groupBoxEnv)
        self.labelFreeSurferHome.setObjectName("labelFreeSurferHome")
        self.verticalLayout_6.addWidget(self.labelFreeSurferHome)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEditFreeSurferHome = QtWidgets.QLineEdit(self.groupBoxEnv)
        self.lineEditFreeSurferHome.setObjectName("lineEditFreeSurferHome")
        self.horizontalLayout_4.addWidget(self.lineEditFreeSurferHome)
        self.pushButtonBrowseFreeSurferHome = QtWidgets.QPushButton(self.groupBoxEnv)
        self.pushButtonBrowseFreeSurferHome.setObjectName("pushButtonBrowseFreeSurferHome")
        self.horizontalLayout_4.addWidget(self.pushButtonBrowseFreeSurferHome)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBoxEnv, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(DialogPreferences)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 6, 0, 1, 1)
        self.checkBoxConfirmQuit = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxConfirmQuit.setObjectName("checkBoxConfirmQuit")
        self.gridLayout_4.addWidget(self.checkBoxConfirmQuit, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelNJobs = QtWidgets.QLabel(self.groupBox)
        self.labelNJobs.setObjectName("labelNJobs")
        self.horizontalLayout_3.addWidget(self.labelNJobs)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.spinBoxNJobs = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxNJobs.setMinimum(1)
        self.spinBoxNJobs.setMaximum(1000000000)
        self.spinBoxNJobs.setProperty("value", 3)
        self.spinBoxNJobs.setObjectName("spinBoxNJobs")
        self.horizontalLayout_3.addWidget(self.spinBoxNJobs)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.checkBoxAutomaticOpenPreviousExperiment = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxAutomaticOpenPreviousExperiment.setObjectName("checkBoxAutomaticOpenPreviousExperiment")
        self.gridLayout_4.addWidget(self.checkBoxAutomaticOpenPreviousExperiment, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 2, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogPreferences)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 3, 0, 1, 1)

        self.retranslateUi(DialogPreferences)
        self.buttonBox.accepted.connect(DialogPreferences.accept)
        self.buttonBox.rejected.connect(DialogPreferences.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogPreferences)
        DialogPreferences.setTabOrder(self.LineEditFilePath, self.ButtonBrowseWorkingDir)

    def retranslateUi(self, DialogPreferences):
        _translate = QtCore.QCoreApplication.translate
        DialogPreferences.setWindowTitle(_translate("DialogPreferences", "Preferences"))
        self.groupBoxWorkingDirectory.setTitle(_translate("DialogPreferences", "Working directory:"))
        self.label.setText(_translate("DialogPreferences", "Select a working directory (compulsory):"))
        self.ButtonBrowseWorkingDir.setText(_translate("DialogPreferences", "Browse..."))
        self.groupBoxEnv.setTitle(_translate("DialogPreferences", "Environment variables:"))
        self.labelFreeSurferHome.setText(_translate("DialogPreferences", "Select FREESURFER_HOME directory (needed for source analysis):"))
        self.pushButtonBrowseFreeSurferHome.setText(_translate("DialogPreferences", "Browse..."))
        self.groupBox.setTitle(_translate("DialogPreferences", "Miscellaneous preferences:"))
        self.checkBoxConfirmQuit.setText(_translate("DialogPreferences", "Show confirmation dialog on Meggie quit"))
        self.labelNJobs.setText(_translate("DialogPreferences", "Number of jobs to run in parallel:"))
        self.checkBoxAutomaticOpenPreviousExperiment.setText(_translate("DialogPreferences", "Automatically open previous experiment upon application startup"))

