# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'singleChannelDialogUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_singleChannelDialog(object):
    def setupUi(self, singleChannelDialog):
        singleChannelDialog.setObjectName("singleChannelDialog")
        singleChannelDialog.resize(419, 523)
        self.gridLayout = QtWidgets.QGridLayout(singleChannelDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(singleChannelDialog)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 399, 472))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.groupBoxLegend = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxLegend.setObjectName("groupBoxLegend")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBoxLegend)
        self.formLayout_2.setObjectName("formLayout_2")
        self.labelLegendItem_1 = QtWidgets.QLabel(self.groupBoxLegend)
        self.labelLegendItem_1.setObjectName("labelLegendItem_1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelLegendItem_1)
        self.lineEditLegendItem_1 = QtWidgets.QLineEdit(self.groupBoxLegend)
        self.lineEditLegendItem_1.setObjectName("lineEditLegendItem_1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditLegendItem_1)
        self.labelLegenditem_2 = QtWidgets.QLabel(self.groupBoxLegend)
        self.labelLegenditem_2.setObjectName("labelLegenditem_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelLegenditem_2)
        self.lineEditLegendItem_2 = QtWidgets.QLineEdit(self.groupBoxLegend)
        self.lineEditLegendItem_2.setObjectName("lineEditLegendItem_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditLegendItem_2)
        self.gridLayout_2.addWidget(self.groupBoxLegend, 2, 0, 1, 1)
        self.groupBoxValueRange = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxValueRange.setObjectName("groupBoxValueRange")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBoxValueRange)
        self.formLayout_3.setObjectName("formLayout_3")
        self.labelMax = QtWidgets.QLabel(self.groupBoxValueRange)
        self.labelMax.setObjectName("labelMax")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelMax)
        self.doubleSpinBoxMax = QtWidgets.QDoubleSpinBox(self.groupBoxValueRange)
        self.doubleSpinBoxMax.setSuffix("")
        self.doubleSpinBoxMax.setDecimals(15)
        self.doubleSpinBoxMax.setMinimum(-1000.0)
        self.doubleSpinBoxMax.setMaximum(1000.0)
        self.doubleSpinBoxMax.setSingleStep(0.01)
        self.doubleSpinBoxMax.setProperty("value", 0.0)
        self.doubleSpinBoxMax.setObjectName("doubleSpinBoxMax")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxMax)
        self.labelMin = QtWidgets.QLabel(self.groupBoxValueRange)
        self.labelMin.setObjectName("labelMin")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelMin)
        self.doubleSpinBoxMin = QtWidgets.QDoubleSpinBox(self.groupBoxValueRange)
        self.doubleSpinBoxMin.setSuffix("")
        self.doubleSpinBoxMin.setDecimals(15)
        self.doubleSpinBoxMin.setMinimum(-1000.0)
        self.doubleSpinBoxMin.setMaximum(1000.0)
        self.doubleSpinBoxMin.setSingleStep(0.01)
        self.doubleSpinBoxMin.setProperty("value", 0.0)
        self.doubleSpinBoxMin.setObjectName("doubleSpinBoxMin")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxMin)
        self.gridLayout_2.addWidget(self.groupBoxValueRange, 1, 0, 1, 1)
        self.groupBoxGeneral = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxGeneral.setObjectName("groupBoxGeneral")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBoxGeneral)
        self.formLayout_4.setObjectName("formLayout_4")
        self.labelTitle = QtWidgets.QLabel(self.groupBoxGeneral)
        self.labelTitle.setObjectName("labelTitle")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelTitle)
        self.lineEditTitle = QtWidgets.QLineEdit(self.groupBoxGeneral)
        self.lineEditTitle.setObjectName("lineEditTitle")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditTitle)
        self.labelSmoothing = QtWidgets.QLabel(self.groupBoxGeneral)
        self.labelSmoothing.setObjectName("labelSmoothing")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelSmoothing)
        self.doubleSpinBoxSmoothing = QtWidgets.QDoubleSpinBox(self.groupBoxGeneral)
        self.doubleSpinBoxSmoothing.setDecimals(2)
        self.doubleSpinBoxSmoothing.setMinimum(1.0)
        self.doubleSpinBoxSmoothing.setMaximum(100.0)
        self.doubleSpinBoxSmoothing.setProperty("value", 1.0)
        self.doubleSpinBoxSmoothing.setObjectName("doubleSpinBoxSmoothing")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxSmoothing)
        self.labelChannel = QtWidgets.QLabel(self.groupBoxGeneral)
        self.labelChannel.setObjectName("labelChannel")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelChannel)
        self.comboBoxChannel = QtWidgets.QComboBox(self.groupBoxGeneral)
        self.comboBoxChannel.setObjectName("comboBoxChannel")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxChannel)
        self.gridLayout_2.addWidget(self.groupBoxGeneral, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButtonCancel = QtWidgets.QPushButton(singleChannelDialog)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.pushButtonApply = QtWidgets.QPushButton(singleChannelDialog)
        self.pushButtonApply.setObjectName("pushButtonApply")
        self.horizontalLayout.addWidget(self.pushButtonApply)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(singleChannelDialog)
        self.pushButtonCancel.clicked.connect(singleChannelDialog.reject)
        self.pushButtonApply.clicked.connect(singleChannelDialog.accept)
        QtCore.QMetaObject.connectSlotsByName(singleChannelDialog)

    def retranslateUi(self, singleChannelDialog):
        _translate = QtCore.QCoreApplication.translate
        singleChannelDialog.setWindowTitle(_translate("singleChannelDialog", "Meggie - Single channel"))
        self.groupBoxLegend.setTitle(_translate("singleChannelDialog", "Legend:"))
        self.labelLegendItem_1.setText(_translate("singleChannelDialog", "1_2"))
        self.lineEditLegendItem_1.setText(_translate("singleChannelDialog", "Control"))
        self.labelLegenditem_2.setText(_translate("singleChannelDialog", "2_2"))
        self.lineEditLegendItem_2.setText(_translate("singleChannelDialog", "Dep"))
        self.groupBoxValueRange.setTitle(_translate("singleChannelDialog", "Value range:"))
        self.labelMax.setText(_translate("singleChannelDialog", "Max value:"))
        self.labelMin.setText(_translate("singleChannelDialog", "Min value:"))
        self.groupBoxGeneral.setTitle(_translate("singleChannelDialog", "General:"))
        self.labelTitle.setText(_translate("singleChannelDialog", "Title:"))
        self.labelSmoothing.setText(_translate("singleChannelDialog", "Smoothing factor:"))
        self.labelChannel.setText(_translate("singleChannelDialog", "Channel:"))
        self.pushButtonCancel.setText(_translate("singleChannelDialog", "Cancel"))
        self.pushButtonApply.setText(_translate("singleChannelDialog", "Apply"))

