# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'batchingWidgetUi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BatchingWidget(object):
    def setupUi(self, BatchingWidget):
        BatchingWidget.setObjectName(_fromUtf8("BatchingWidget"))
        BatchingWidget.resize(291, 392)
        self.widget = QtGui.QWidget(BatchingWidget)
        self.widget.setGeometry(QtCore.QRect(0, 10, 289, 41))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.headingLayout = QtGui.QHBoxLayout(self.widget)
        self.headingLayout.setObjectName(_fromUtf8("headingLayout"))
        self.checkBoxBatch = QtGui.QCheckBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxBatch.sizePolicy().hasHeightForWidth())
        self.checkBoxBatch.setSizePolicy(sizePolicy)
        self.checkBoxBatch.setObjectName(_fromUtf8("checkBoxBatch"))
        self.headingLayout.addWidget(self.checkBoxBatch)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.headingLayout.addItem(spacerItem)
        self.functionalityWidget = QtGui.QWidget(BatchingWidget)
        self.functionalityWidget.setGeometry(QtCore.QRect(0, 48, 289, 341))
        self.functionalityWidget.setObjectName(_fromUtf8("functionalityWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.functionalityWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.functionalityLayout = QtGui.QGridLayout()
        self.functionalityLayout.setObjectName(_fromUtf8("functionalityLayout"))
        self.applyButtonsLayout = QtGui.QVBoxLayout()
        self.applyButtonsLayout.setObjectName(_fromUtf8("applyButtonsLayout"))
        self.label = QtGui.QLabel(self.functionalityWidget)
        self.label.setEnabled(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.applyButtonsLayout.addWidget(self.label)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.pushButtonApply = QtGui.QPushButton(self.functionalityWidget)
        self.pushButtonApply.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonApply.sizePolicy().hasHeightForWidth())
        self.pushButtonApply.setSizePolicy(sizePolicy)
        self.pushButtonApply.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButtonApply.setMaximumSize(QtCore.QSize(90, 16777215))
        self.pushButtonApply.setObjectName(_fromUtf8("pushButtonApply"))
        self.horizontalLayout_30.addWidget(self.pushButtonApply)
        self.label_6 = QtGui.QLabel(self.functionalityWidget)
        self.label_6.setEnabled(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_30.addWidget(self.label_6)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem1)
        self.applyButtonsLayout.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.pushButtonApplyAll = QtGui.QPushButton(self.functionalityWidget)
        self.pushButtonApplyAll.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonApplyAll.sizePolicy().hasHeightForWidth())
        self.pushButtonApplyAll.setSizePolicy(sizePolicy)
        self.pushButtonApplyAll.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButtonApplyAll.setMaximumSize(QtCore.QSize(90, 16777215))
        self.pushButtonApplyAll.setObjectName(_fromUtf8("pushButtonApplyAll"))
        self.horizontalLayout_31.addWidget(self.pushButtonApplyAll)
        self.label_7 = QtGui.QLabel(self.functionalityWidget)
        self.label_7.setEnabled(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_31.addWidget(self.label_7)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem2)
        self.applyButtonsLayout.addLayout(self.horizontalLayout_31)
        self.functionalityLayout.addLayout(self.applyButtonsLayout, 1, 0, 1, 1)
        self.subjectListLayout = QtGui.QVBoxLayout()
        self.subjectListLayout.setObjectName(_fromUtf8("subjectListLayout"))
        self.labelSubjects = QtGui.QLabel(self.functionalityWidget)
        self.labelSubjects.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSubjects.sizePolicy().hasHeightForWidth())
        self.labelSubjects.setSizePolicy(sizePolicy)
        self.labelSubjects.setObjectName(_fromUtf8("labelSubjects"))
        self.subjectListLayout.addWidget(self.labelSubjects)
        self.listWidgetSubjects = QtGui.QListWidget(self.functionalityWidget)
        self.listWidgetSubjects.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetSubjects.sizePolicy().hasHeightForWidth())
        self.listWidgetSubjects.setSizePolicy(sizePolicy)
        self.listWidgetSubjects.setObjectName(_fromUtf8("listWidgetSubjects"))
        self.subjectListLayout.addWidget(self.listWidgetSubjects)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.subjectListLayout.addLayout(self.horizontalLayout_17)
        self.pushButtonRemove = QtGui.QPushButton(self.functionalityWidget)
        self.pushButtonRemove.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRemove.sizePolicy().hasHeightForWidth())
        self.pushButtonRemove.setSizePolicy(sizePolicy)
        self.pushButtonRemove.setObjectName(_fromUtf8("pushButtonRemove"))
        self.subjectListLayout.addWidget(self.pushButtonRemove)
        self.functionalityLayout.addLayout(self.subjectListLayout, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.functionalityLayout)

        self.retranslateUi(BatchingWidget)
        QtCore.QObject.connect(self.checkBoxBatch, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), BatchingWidget.showWidget)
        QtCore.QMetaObject.connectSlotsByName(BatchingWidget)

    def retranslateUi(self, BatchingWidget):
        BatchingWidget.setWindowTitle(_translate("BatchingWidget", "Batch processing", None))
        self.checkBoxBatch.setText(_translate("BatchingWidget", "Batch processing", None))
        self.label.setText(_translate("BatchingWidget", "Apply parameters:", None))
        self.pushButtonApply.setText(_translate("BatchingWidget", "Apply", None))
        self.label_6.setText(_translate("BatchingWidget", "to selected subject", None))
        self.pushButtonApplyAll.setText(_translate("BatchingWidget", "Apply to all", None))
        self.label_7.setText(_translate("BatchingWidget", "subjects on the list", None))
        self.labelSubjects.setText(_translate("BatchingWidget", "Select subject to modify its parameters", None))
        self.pushButtonRemove.setText(_translate("BatchingWidget", "Remove subject from this process", None))

