# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'batchingWidget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BatchingWidget(object):
    def setupUi(self, BatchingWidget):
        BatchingWidget.setObjectName(_fromUtf8("BatchingWidget"))
        BatchingWidget.resize(510, 302)
        self.groupBoxBatch = QtGui.QGroupBox(BatchingWidget)
        self.groupBoxBatch.setGeometry(QtCore.QRect(10, 40, 491, 240))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxBatch.sizePolicy().hasHeightForWidth())
        self.groupBoxBatch.setSizePolicy(sizePolicy)
        self.groupBoxBatch.setMinimumSize(QtCore.QSize(0, 240))
        self.groupBoxBatch.setTitle(_fromUtf8(""))
        self.groupBoxBatch.setObjectName(_fromUtf8("groupBoxBatch"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.groupBoxBatch)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 471, 209))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.labelSubjects = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.labelSubjects.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSubjects.sizePolicy().hasHeightForWidth())
        self.labelSubjects.setSizePolicy(sizePolicy)
        self.labelSubjects.setObjectName(_fromUtf8("labelSubjects"))
        self.verticalLayout_9.addWidget(self.labelSubjects)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.listWidgetSubjects = QtGui.QListWidget(self.verticalLayoutWidget_4)
        self.listWidgetSubjects.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetSubjects.sizePolicy().hasHeightForWidth())
        self.listWidgetSubjects.setSizePolicy(sizePolicy)
        self.listWidgetSubjects.setObjectName(_fromUtf8("listWidgetSubjects"))
        self.horizontalLayout_17.addWidget(self.listWidgetSubjects)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem)
        self.label = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label.setEnabled(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_11.addWidget(self.label)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.pushButtonApply = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButtonApply.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonApply.sizePolicy().hasHeightForWidth())
        self.pushButtonApply.setSizePolicy(sizePolicy)
        self.pushButtonApply.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButtonApply.setMaximumSize(QtCore.QSize(90, 16777215))
        self.pushButtonApply.setObjectName(_fromUtf8("pushButtonApply"))
        self.horizontalLayout_30.addWidget(self.pushButtonApply)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_6.setEnabled(False)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_30.addWidget(self.label_6)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.pushButtonApplyAll = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButtonApplyAll.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonApplyAll.sizePolicy().hasHeightForWidth())
        self.pushButtonApplyAll.setSizePolicy(sizePolicy)
        self.pushButtonApplyAll.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButtonApplyAll.setMaximumSize(QtCore.QSize(90, 16777215))
        self.pushButtonApplyAll.setObjectName(_fromUtf8("pushButtonApplyAll"))
        self.horizontalLayout_31.addWidget(self.pushButtonApplyAll)
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_7.setEnabled(False)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_31.addWidget(self.label_7)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_31)
        self.verticalLayout_10.addLayout(self.verticalLayout_11)
        self.horizontalLayout_17.addLayout(self.verticalLayout_10)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.pushButtonRemove = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButtonRemove.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRemove.sizePolicy().hasHeightForWidth())
        self.pushButtonRemove.setSizePolicy(sizePolicy)
        self.pushButtonRemove.setObjectName(_fromUtf8("pushButtonRemove"))
        self.verticalLayout_9.addWidget(self.pushButtonRemove)
        self.horizontalLayoutWidget = QtGui.QWidget(BatchingWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 471, 51))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.checkBoxBatch = QtGui.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxBatch.sizePolicy().hasHeightForWidth())
        self.checkBoxBatch.setSizePolicy(sizePolicy)
        self.checkBoxBatch.setObjectName(_fromUtf8("checkBoxBatch"))
        self.horizontalLayout.addWidget(self.checkBoxBatch)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)

        self.retranslateUi(BatchingWidget)
        QtCore.QObject.connect(self.checkBoxBatch, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), BatchingWidget.showWidget)
        QtCore.QMetaObject.connectSlotsByName(BatchingWidget)

    def retranslateUi(self, BatchingWidget):
        BatchingWidget.setWindowTitle(_translate("BatchingWidget", "Batch processing", None))
        self.labelSubjects.setText(_translate("BatchingWidget", "Select subject to modify its parameters", None))
        self.label.setText(_translate("BatchingWidget", "Apply parameters:", None))
        self.pushButtonApply.setText(_translate("BatchingWidget", "Apply", None))
        self.label_6.setText(_translate("BatchingWidget", "to selected subject", None))
        self.pushButtonApplyAll.setText(_translate("BatchingWidget", "Apply to all", None))
        self.label_7.setText(_translate("BatchingWidget", "subjects on the list", None))
        self.pushButtonRemove.setText(_translate("BatchingWidget", "Remove subject from this process", None))
        self.checkBoxBatch.setText(_translate("BatchingWidget", "Batch processing", None))

