# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kpaliran/Hoksotin/lahdekoodit/lahdekoodit/meggie_batch/ui/qt4Designer_ui_files/mainWindowBatch.ui'
#
# Created: Fri May 23 20:31:26 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1114, 954)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 400))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1100, 830))
        self.scrollAreaWidgetContents_3.setMinimumSize(QtCore.QSize(1100, 750))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout_22 = QtGui.QGridLayout()
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents_3)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabPreprocessing = QtGui.QWidget()
        self.tabPreprocessing.setMinimumSize(QtCore.QSize(500, 0))
        self.tabPreprocessing.setObjectName(_fromUtf8("tabPreprocessing"))
        self.gridLayout_18 = QtGui.QGridLayout(self.tabPreprocessing)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.groupBoxPreprocessingCheckBoxes = QtGui.QGroupBox(self.tabPreprocessing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPreprocessingCheckBoxes.sizePolicy().hasHeightForWidth())
        self.groupBoxPreprocessingCheckBoxes.setSizePolicy(sizePolicy)
        self.groupBoxPreprocessingCheckBoxes.setMinimumSize(QtCore.QSize(60, 0))
        self.groupBoxPreprocessingCheckBoxes.setObjectName(_fromUtf8("groupBoxPreprocessingCheckBoxes"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBoxPreprocessingCheckBoxes)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem)
        self.checkBoxECGComputed = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxECGComputed.setEnabled(False)
        self.checkBoxECGComputed.setText(_fromUtf8(""))
        self.checkBoxECGComputed.setObjectName(_fromUtf8("checkBoxECGComputed"))
        self.horizontalLayout_17.addWidget(self.checkBoxECGComputed)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem1)
        self.gridLayout_6.addLayout(self.horizontalLayout_17, 2, 1, 1, 1)
        self.labelEOGComputed_2 = QtGui.QLabel(self.groupBoxPreprocessingCheckBoxes)
        self.labelEOGComputed_2.setObjectName(_fromUtf8("labelEOGComputed_2"))
        self.gridLayout_6.addWidget(self.labelEOGComputed_2, 3, 0, 1, 1)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem2)
        self.checkBoxEOGApplied = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxEOGApplied.setEnabled(False)
        self.checkBoxEOGApplied.setText(_fromUtf8(""))
        self.checkBoxEOGApplied.setObjectName(_fromUtf8("checkBoxEOGApplied"))
        self.horizontalLayout_20.addWidget(self.checkBoxEOGApplied)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem3)
        self.gridLayout_6.addLayout(self.horizontalLayout_20, 3, 2, 1, 1)
        self.labelECGApplied_2 = QtGui.QLabel(self.groupBoxPreprocessingCheckBoxes)
        self.labelECGApplied_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelECGApplied_2.setObjectName(_fromUtf8("labelECGApplied_2"))
        self.gridLayout_6.addWidget(self.labelECGApplied_2, 0, 1, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem4)
        self.checkBoxECGApplied = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxECGApplied.setEnabled(False)
        self.checkBoxECGApplied.setText(_fromUtf8(""))
        self.checkBoxECGApplied.setObjectName(_fromUtf8("checkBoxECGApplied"))
        self.horizontalLayout_16.addWidget(self.checkBoxECGApplied)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem5)
        self.gridLayout_6.addLayout(self.horizontalLayout_16, 2, 2, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem6)
        self.checkBoxEOGComputed = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxEOGComputed.setEnabled(False)
        self.checkBoxEOGComputed.setText(_fromUtf8(""))
        self.checkBoxEOGComputed.setObjectName(_fromUtf8("checkBoxEOGComputed"))
        self.horizontalLayout_19.addWidget(self.checkBoxEOGComputed)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem7)
        self.gridLayout_6.addLayout(self.horizontalLayout_19, 3, 1, 1, 1)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem8)
        self.checkBoxMaxFilterApplied = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxMaxFilterApplied.setEnabled(False)
        self.checkBoxMaxFilterApplied.setText(_fromUtf8(""))
        self.checkBoxMaxFilterApplied.setObjectName(_fromUtf8("checkBoxMaxFilterApplied"))
        self.horizontalLayout_21.addWidget(self.checkBoxMaxFilterApplied)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem9)
        self.gridLayout_6.addLayout(self.horizontalLayout_21, 1, 2, 1, 1)
        self.labelECGComputed_2 = QtGui.QLabel(self.groupBoxPreprocessingCheckBoxes)
        self.labelECGComputed_2.setObjectName(_fromUtf8("labelECGComputed_2"))
        self.gridLayout_6.addWidget(self.labelECGComputed_2, 2, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem10)
        self.checkBoxMaxFilterComputed = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxMaxFilterComputed.setEnabled(False)
        self.checkBoxMaxFilterComputed.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.checkBoxMaxFilterComputed.setText(_fromUtf8(""))
        self.checkBoxMaxFilterComputed.setObjectName(_fromUtf8("checkBoxMaxFilterComputed"))
        self.horizontalLayout_13.addWidget(self.checkBoxMaxFilterComputed)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem11)
        self.gridLayout_6.addLayout(self.horizontalLayout_13, 1, 1, 1, 1)
        self.labelEOGApplied_2 = QtGui.QLabel(self.groupBoxPreprocessingCheckBoxes)
        self.labelEOGApplied_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEOGApplied_2.setObjectName(_fromUtf8("labelEOGApplied_2"))
        self.gridLayout_6.addWidget(self.labelEOGApplied_2, 0, 2, 1, 1)
        self.labelMaxFilter_2 = QtGui.QLabel(self.groupBoxPreprocessingCheckBoxes)
        self.labelMaxFilter_2.setObjectName(_fromUtf8("labelMaxFilter_2"))
        self.gridLayout_6.addWidget(self.labelMaxFilter_2, 1, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.groupBoxPreprocessingCheckBoxes, 0, 0, 1, 1)
        self.groupBoxAvailablePreprocessing = QtGui.QGroupBox(self.tabPreprocessing)
        self.groupBoxAvailablePreprocessing.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBoxAvailablePreprocessing.setObjectName(_fromUtf8("groupBoxAvailablePreprocessing"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxAvailablePreprocessing)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.pushButtonMaxFilter = QtGui.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonMaxFilter.setObjectName(_fromUtf8("pushButtonMaxFilter"))
        self.horizontalLayout_18.addWidget(self.pushButtonMaxFilter)
        self.pushButtonFilter = QtGui.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonFilter.setObjectName(_fromUtf8("pushButtonFilter"))
        self.horizontalLayout_18.addWidget(self.pushButtonFilter)
        self.gridLayout_3.addLayout(self.horizontalLayout_18, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.groupBoxAvailablePreprocessing, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tabPreprocessing)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_18.addWidget(self.label_2, 2, 0, 1, 1)
        self.listWidgetSubjects_2 = QtGui.QListWidget(self.tabPreprocessing)
        self.listWidgetSubjects_2.setObjectName(_fromUtf8("listWidgetSubjects_2"))
        self.gridLayout_18.addWidget(self.listWidgetSubjects_2, 3, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonECG = QtGui.QPushButton(self.tabPreprocessing)
        self.pushButtonECG.setObjectName(_fromUtf8("pushButtonECG"))
        self.horizontalLayout.addWidget(self.pushButtonECG)
        self.pushButtonApplyECG = QtGui.QPushButton(self.tabPreprocessing)
        self.pushButtonApplyECG.setEnabled(False)
        self.pushButtonApplyECG.setObjectName(_fromUtf8("pushButtonApplyECG"))
        self.horizontalLayout.addWidget(self.pushButtonApplyECG)
        self.gridLayout_18.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.pushButtonEOG = QtGui.QPushButton(self.tabPreprocessing)
        self.pushButtonEOG.setObjectName(_fromUtf8("pushButtonEOG"))
        self.horizontalLayout_12.addWidget(self.pushButtonEOG)
        self.pushButtonApplyEOG = QtGui.QPushButton(self.tabPreprocessing)
        self.pushButtonApplyEOG.setEnabled(False)
        self.pushButtonApplyEOG.setObjectName(_fromUtf8("pushButtonApplyEOG"))
        self.horizontalLayout_12.addWidget(self.pushButtonApplyEOG)
        self.gridLayout_18.addLayout(self.horizontalLayout_12, 5, 0, 1, 1)
        self.groupBoxVisualization_2 = QtGui.QGroupBox(self.tabPreprocessing)
        self.groupBoxVisualization_2.setObjectName(_fromUtf8("groupBoxVisualization_2"))
        self.gridLayout_21 = QtGui.QGridLayout(self.groupBoxVisualization_2)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButtonSpectrum = QtGui.QPushButton(self.groupBoxVisualization_2)
        self.pushButtonSpectrum.setObjectName(_fromUtf8("pushButtonSpectrum"))
        self.verticalLayout.addWidget(self.pushButtonSpectrum)
        self.pushButtonMNE_Browse_Raw_2 = QtGui.QPushButton(self.groupBoxVisualization_2)
        self.pushButtonMNE_Browse_Raw_2.setObjectName(_fromUtf8("pushButtonMNE_Browse_Raw_2"))
        self.verticalLayout.addWidget(self.pushButtonMNE_Browse_Raw_2)
        self.gridLayout_21.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.groupBoxVisualization_2, 6, 0, 1, 1)
        self.tabWidget.addTab(self.tabPreprocessing, _fromUtf8(""))
        self.tabEpoching = QtGui.QWidget()
        self.tabEpoching.setObjectName(_fromUtf8("tabEpoching"))
        self.gridLayout_20 = QtGui.QGridLayout(self.tabEpoching)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.groupBoxAvailableEpoching = QtGui.QGroupBox(self.tabEpoching)
        self.groupBoxAvailableEpoching.setObjectName(_fromUtf8("groupBoxAvailableEpoching"))
        self.gridLayout_19 = QtGui.QGridLayout(self.groupBoxAvailableEpoching)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.pushButtonVisualizeEpochChannels = QtGui.QPushButton(self.groupBoxAvailableEpoching)
        self.pushButtonVisualizeEpochChannels.setObjectName(_fromUtf8("pushButtonVisualizeEpochChannels"))
        self.gridLayout_19.addWidget(self.pushButtonVisualizeEpochChannels, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.pushButtonCreateEpochs = QtGui.QPushButton(self.groupBoxAvailableEpoching)
        self.pushButtonCreateEpochs.setObjectName(_fromUtf8("pushButtonCreateEpochs"))
        self.verticalLayout_13.addWidget(self.pushButtonCreateEpochs)
        self.pushButtonModifyEpochs = QtGui.QPushButton(self.groupBoxAvailableEpoching)
        self.pushButtonModifyEpochs.setObjectName(_fromUtf8("pushButtonModifyEpochs"))
        self.verticalLayout_13.addWidget(self.pushButtonModifyEpochs)
        self.pushButtonDeleteEpochs = QtGui.QPushButton(self.groupBoxAvailableEpoching)
        self.pushButtonDeleteEpochs.setObjectName(_fromUtf8("pushButtonDeleteEpochs"))
        self.verticalLayout_13.addWidget(self.pushButtonDeleteEpochs)
        self.horizontalLayout_2.addLayout(self.verticalLayout_13)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButtonSaveEpochs = QtGui.QPushButton(self.groupBoxAvailableEpoching)
        self.pushButtonSaveEpochs.setObjectName(_fromUtf8("pushButtonSaveEpochs"))
        self.verticalLayout_2.addWidget(self.pushButtonSaveEpochs)
        self.pushButtonLoadEpochs = QtGui.QPushButton(self.groupBoxAvailableEpoching)
        self.pushButtonLoadEpochs.setObjectName(_fromUtf8("pushButtonLoadEpochs"))
        self.verticalLayout_2.addWidget(self.pushButtonLoadEpochs)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayout_19.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_20.addWidget(self.groupBoxAvailableEpoching, 1, 0, 1, 1)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.groupBoxEpochsEpoching = QtGui.QGroupBox(self.tabEpoching)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxEpochsEpoching.sizePolicy().hasHeightForWidth())
        self.groupBoxEpochsEpoching.setSizePolicy(sizePolicy)
        self.groupBoxEpochsEpoching.setTitle(_fromUtf8(""))
        self.groupBoxEpochsEpoching.setObjectName(_fromUtf8("groupBoxEpochsEpoching"))
        self.horizontalLayout_11.addWidget(self.groupBoxEpochsEpoching)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_11)
        self.gridLayout_20.addLayout(self.horizontalLayout_26, 0, 0, 1, 1)
        self.frameEpochCollectionParameters = QtGui.QFrame(self.tabEpoching)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameEpochCollectionParameters.sizePolicy().hasHeightForWidth())
        self.frameEpochCollectionParameters.setSizePolicy(sizePolicy)
        self.frameEpochCollectionParameters.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameEpochCollectionParameters.setLineWidth(1)
        self.frameEpochCollectionParameters.setObjectName(_fromUtf8("frameEpochCollectionParameters"))
        self.gridLayout_26 = QtGui.QGridLayout(self.frameEpochCollectionParameters)
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.labelWorkingFile = QtGui.QLabel(self.frameEpochCollectionParameters)
        self.labelWorkingFile.setMaximumSize(QtCore.QSize(16777215, 6000))
        self.labelWorkingFile.setObjectName(_fromUtf8("labelWorkingFile"))
        self.horizontalLayout_8.addWidget(self.labelWorkingFile)
        self.textBrowserWorkingFile = QtGui.QTextBrowser(self.frameEpochCollectionParameters)
        self.textBrowserWorkingFile.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserWorkingFile.setPalette(palette)
        self.textBrowserWorkingFile.setFrameShape(QtGui.QFrame.StyledPanel)
        self.textBrowserWorkingFile.setObjectName(_fromUtf8("textBrowserWorkingFile"))
        self.horizontalLayout_8.addWidget(self.textBrowserWorkingFile)
        self.gridLayout_26.addLayout(self.horizontalLayout_8, 3, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_26.addItem(spacerItem12, 4, 0, 1, 1)
        self.groupBoxRejections = QtGui.QGroupBox(self.frameEpochCollectionParameters)
        self.groupBoxRejections.setObjectName(_fromUtf8("groupBoxRejections"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBoxRejections)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelMagReject = QtGui.QLabel(self.groupBoxRejections)
        self.labelMagReject.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelMagReject.setObjectName(_fromUtf8("labelMagReject"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelMagReject)
        self.textBrowserMag = QtGui.QTextBrowser(self.groupBoxRejections)
        self.textBrowserMag.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserMag.sizePolicy().hasHeightForWidth())
        self.textBrowserMag.setSizePolicy(sizePolicy)
        self.textBrowserMag.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowserMag.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textBrowserMag.setSizeIncrement(QtCore.QSize(0, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserMag.setPalette(palette)
        self.textBrowserMag.setFrameShadow(QtGui.QFrame.Sunken)
        self.textBrowserMag.setObjectName(_fromUtf8("textBrowserMag"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.textBrowserMag)
        self.labelGradReject = QtGui.QLabel(self.groupBoxRejections)
        self.labelGradReject.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelGradReject.setObjectName(_fromUtf8("labelGradReject"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelGradReject)
        self.textBrowserGrad = QtGui.QTextBrowser(self.groupBoxRejections)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserGrad.sizePolicy().hasHeightForWidth())
        self.textBrowserGrad.setSizePolicy(sizePolicy)
        self.textBrowserGrad.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowserGrad.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserGrad.setPalette(palette)
        self.textBrowserGrad.setObjectName(_fromUtf8("textBrowserGrad"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.textBrowserGrad)
        self.labelEegReject = QtGui.QLabel(self.groupBoxRejections)
        self.labelEegReject.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelEegReject.setObjectName(_fromUtf8("labelEegReject"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelEegReject)
        self.textBrowserEEG = QtGui.QTextBrowser(self.groupBoxRejections)
        self.textBrowserEEG.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserEEG.setPalette(palette)
        self.textBrowserEEG.setObjectName(_fromUtf8("textBrowserEEG"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.textBrowserEEG)
        self.labelEogReject = QtGui.QLabel(self.groupBoxRejections)
        self.labelEogReject.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelEogReject.setObjectName(_fromUtf8("labelEogReject"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelEogReject)
        self.textBrowserEOG = QtGui.QTextBrowser(self.groupBoxRejections)
        self.textBrowserEOG.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserEOG.setPalette(palette)
        self.textBrowserEOG.setObjectName(_fromUtf8("textBrowserEOG"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.textBrowserEOG)
        self.labelStimReject = QtGui.QLabel(self.groupBoxRejections)
        self.labelStimReject.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelStimReject.setObjectName(_fromUtf8("labelStimReject"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.labelStimReject)
        self.textBrowserStim = QtGui.QTextBrowser(self.groupBoxRejections)
        self.textBrowserStim.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserStim.setPalette(palette)
        self.textBrowserStim.setObjectName(_fromUtf8("textBrowserStim"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.textBrowserStim)
        self.gridLayout_26.addWidget(self.groupBoxRejections, 2, 0, 1, 1)
        self.groupBoxEpochTimes = QtGui.QGroupBox(self.frameEpochCollectionParameters)
        self.groupBoxEpochTimes.setObjectName(_fromUtf8("groupBoxEpochTimes"))
        self.formLayout = QtGui.QFormLayout(self.groupBoxEpochTimes)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelTmin = QtGui.QLabel(self.groupBoxEpochTimes)
        self.labelTmin.setObjectName(_fromUtf8("labelTmin"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelTmin)
        self.textBrowserTmin = QtGui.QTextBrowser(self.groupBoxEpochTimes)
        self.textBrowserTmin.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserTmin.sizePolicy().hasHeightForWidth())
        self.textBrowserTmin.setSizePolicy(sizePolicy)
        self.textBrowserTmin.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowserTmin.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textBrowserTmin.setSizeIncrement(QtCore.QSize(0, 31))
        self.textBrowserTmin.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserTmin.setPalette(palette)
        self.textBrowserTmin.setFrameShape(QtGui.QFrame.StyledPanel)
        self.textBrowserTmin.setObjectName(_fromUtf8("textBrowserTmin"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.textBrowserTmin)
        self.labelTmax = QtGui.QLabel(self.groupBoxEpochTimes)
        self.labelTmax.setObjectName(_fromUtf8("labelTmax"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelTmax)
        self.textBrowserTmax = QtGui.QTextBrowser(self.groupBoxEpochTimes)
        self.textBrowserTmax.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserTmax.sizePolicy().hasHeightForWidth())
        self.textBrowserTmax.setSizePolicy(sizePolicy)
        self.textBrowserTmax.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowserTmax.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textBrowserTmax.setSizeIncrement(QtCore.QSize(0, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserTmax.setPalette(palette)
        self.textBrowserTmax.setObjectName(_fromUtf8("textBrowserTmax"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.textBrowserTmax)
        self.gridLayout_26.addWidget(self.groupBoxEpochTimes, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.frameEpochCollectionParameters)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_26.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_20.addWidget(self.frameEpochCollectionParameters, 0, 1, 3, 1)
        self.tabWidget.addTab(self.tabEpoching, _fromUtf8(""))
        self.tabTFR = QtGui.QWidget()
        self.tabTFR.setObjectName(_fromUtf8("tabTFR"))
        self.gridLayout_25 = QtGui.QGridLayout(self.tabTFR)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.groupBoxEpochsTFR = QtGui.QGroupBox(self.tabTFR)
        self.groupBoxEpochsTFR.setTitle(_fromUtf8(""))
        self.groupBoxEpochsTFR.setObjectName(_fromUtf8("groupBoxEpochsTFR"))
        self.gridLayout_8.addWidget(self.groupBoxEpochsTFR, 0, 0, 1, 1)
        self.groupBoxEpochParamsTFR = QtGui.QGroupBox(self.tabTFR)
        self.groupBoxEpochParamsTFR.setTitle(_fromUtf8(""))
        self.groupBoxEpochParamsTFR.setObjectName(_fromUtf8("groupBoxEpochParamsTFR"))
        self.gridLayout_8.addWidget(self.groupBoxEpochParamsTFR, 0, 1, 1, 1)
        self.groupBoxAvailableTFR = QtGui.QGroupBox(self.tabTFR)
        self.groupBoxAvailableTFR.setMaximumSize(QtCore.QSize(500, 180))
        self.groupBoxAvailableTFR.setObjectName(_fromUtf8("groupBoxAvailableTFR"))
        self.gridLayout_27 = QtGui.QGridLayout(self.groupBoxAvailableTFR)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.pushButtonTFRTopology = QtGui.QPushButton(self.groupBoxAvailableTFR)
        self.pushButtonTFRTopology.setObjectName(_fromUtf8("pushButtonTFRTopology"))
        self.gridLayout_27.addWidget(self.pushButtonTFRTopology, 1, 0, 1, 1)
        self.pushButtonTFR = QtGui.QPushButton(self.groupBoxAvailableTFR)
        self.pushButtonTFR.setObjectName(_fromUtf8("pushButtonTFR"))
        self.gridLayout_27.addWidget(self.pushButtonTFR, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBoxAvailableTFR, 1, 0, 1, 1)
        self.gridLayout_25.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabTFR, _fromUtf8(""))
        self.tabAveraging = QtGui.QWidget()
        self.tabAveraging.setObjectName(_fromUtf8("tabAveraging"))
        self.gridLayout_24 = QtGui.QGridLayout(self.tabAveraging)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBoxAvailableAveraging = QtGui.QGroupBox(self.tabAveraging)
        self.groupBoxAvailableAveraging.setMinimumSize(QtCore.QSize(0, 260))
        self.groupBoxAvailableAveraging.setMaximumSize(QtCore.QSize(500, 240))
        self.groupBoxAvailableAveraging.setObjectName(_fromUtf8("groupBoxAvailableAveraging"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBoxAvailableAveraging)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.groupBoxChannelAverages = QtGui.QGroupBox(self.groupBoxAvailableAveraging)
        self.groupBoxChannelAverages.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBoxChannelAverages.setObjectName(_fromUtf8("groupBoxChannelAverages"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBoxChannelAverages)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.pushButtonChannelAverages = QtGui.QPushButton(self.groupBoxChannelAverages)
        self.pushButtonChannelAverages.setObjectName(_fromUtf8("pushButtonChannelAverages"))
        self.gridLayout_11.addWidget(self.pushButtonChannelAverages, 4, 1, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.radioButtonLobe = QtGui.QRadioButton(self.groupBoxChannelAverages)
        self.radioButtonLobe.setChecked(True)
        self.radioButtonLobe.setObjectName(_fromUtf8("radioButtonLobe"))
        self.buttonGroupChannelAverage = QtGui.QButtonGroup(MainWindow)
        self.buttonGroupChannelAverage.setObjectName(_fromUtf8("buttonGroupChannelAverage"))
        self.buttonGroupChannelAverage.addButton(self.radioButtonLobe)
        self.horizontalLayout_14.addWidget(self.radioButtonLobe)
        self.comboBoxLobes = QtGui.QComboBox(self.groupBoxChannelAverages)
        self.comboBoxLobes.setObjectName(_fromUtf8("comboBoxLobes"))
        self.horizontalLayout_14.addWidget(self.comboBoxLobes)
        self.gridLayout_11.addLayout(self.horizontalLayout_14, 1, 1, 1, 1)
        self.labelChannelAverages = QtGui.QLabel(self.groupBoxChannelAverages)
        self.labelChannelAverages.setObjectName(_fromUtf8("labelChannelAverages"))
        self.gridLayout_11.addWidget(self.labelChannelAverages, 0, 1, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.radioButtonCustomChannels = QtGui.QRadioButton(self.groupBoxChannelAverages)
        self.radioButtonCustomChannels.setObjectName(_fromUtf8("radioButtonCustomChannels"))
        self.buttonGroupChannelAverage.addButton(self.radioButtonCustomChannels)
        self.horizontalLayout_15.addWidget(self.radioButtonCustomChannels)
        self.plainTextEditCustomChannelsToAverage = QtGui.QPlainTextEdit(self.groupBoxChannelAverages)
        self.plainTextEditCustomChannelsToAverage.setEnabled(False)
        self.plainTextEditCustomChannelsToAverage.setObjectName(_fromUtf8("plainTextEditCustomChannelsToAverage"))
        self.horizontalLayout_15.addWidget(self.plainTextEditCustomChannelsToAverage)
        self.gridLayout_11.addLayout(self.horizontalLayout_15, 3, 1, 1, 1)
        self.gridLayout_15.addWidget(self.groupBoxChannelAverages, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxAvailableAveraging, 1, 0, 1, 1)
        self.groupBoxEpochsAveraging = QtGui.QGroupBox(self.tabAveraging)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxEpochsAveraging.sizePolicy().hasHeightForWidth())
        self.groupBoxEpochsAveraging.setSizePolicy(sizePolicy)
        self.groupBoxEpochsAveraging.setMinimumSize(QtCore.QSize(0, 400))
        self.groupBoxEpochsAveraging.setTitle(_fromUtf8(""))
        self.groupBoxEpochsAveraging.setObjectName(_fromUtf8("groupBoxEpochsAveraging"))
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBoxEpochsAveraging)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.gridLayout_4.addWidget(self.groupBoxEpochsAveraging, 0, 0, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pushButtonCreateEvoked = QtGui.QPushButton(self.tabAveraging)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCreateEvoked.sizePolicy().hasHeightForWidth())
        self.pushButtonCreateEvoked.setSizePolicy(sizePolicy)
        self.pushButtonCreateEvoked.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.pushButtonCreateEvoked.setObjectName(_fromUtf8("pushButtonCreateEvoked"))
        self.verticalLayout_4.addWidget(self.pushButtonCreateEvoked)
        self.label = QtGui.QLabel(self.tabAveraging)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.gridLayout_24.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.groupBoxEvokeds = QtGui.QGroupBox(self.tabAveraging)
        self.groupBoxEvokeds.setMinimumSize(QtCore.QSize(0, 300))
        self.groupBoxEvokeds.setObjectName(_fromUtf8("groupBoxEvokeds"))
        self.gridLayout_16 = QtGui.QGridLayout(self.groupBoxEvokeds)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.widgetEvokeds = QtGui.QWidget(self.groupBoxEvokeds)
        self.widgetEvokeds.setObjectName(_fromUtf8("widgetEvokeds"))
        self.gridLayout_16.addWidget(self.widgetEvokeds, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupBoxEvokeds, 0, 0, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButtonSaveEvoked = QtGui.QPushButton(self.tabAveraging)
        self.pushButtonSaveEvoked.setObjectName(_fromUtf8("pushButtonSaveEvoked"))
        self.gridLayout.addWidget(self.pushButtonSaveEvoked, 0, 0, 1, 1)
        self.pushButtonDeleteEvoked = QtGui.QPushButton(self.tabAveraging)
        self.pushButtonDeleteEvoked.setObjectName(_fromUtf8("pushButtonDeleteEvoked"))
        self.gridLayout.addWidget(self.pushButtonDeleteEvoked, 1, 0, 1, 1)
        self.pushButtonLoadEvoked = QtGui.QPushButton(self.tabAveraging)
        self.pushButtonLoadEvoked.setObjectName(_fromUtf8("pushButtonLoadEvoked"))
        self.gridLayout.addWidget(self.pushButtonLoadEvoked, 0, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem13)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.pushButtonVisualizeEvokedDataset = QtGui.QPushButton(self.tabAveraging)
        self.pushButtonVisualizeEvokedDataset.setObjectName(_fromUtf8("pushButtonVisualizeEvokedDataset"))
        self.horizontalLayout_10.addWidget(self.pushButtonVisualizeEvokedDataset)
        self.pushButtonOpenEvokedStatsDialog = QtGui.QPushButton(self.tabAveraging)
        self.pushButtonOpenEvokedStatsDialog.setObjectName(_fromUtf8("pushButtonOpenEvokedStatsDialog"))
        self.horizontalLayout_10.addWidget(self.pushButtonOpenEvokedStatsDialog)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.gridLayout_14.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_14, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tabAveraging, _fromUtf8(""))
        self.tabSourcePreparation = QtGui.QWidget()
        self.tabSourcePreparation.setObjectName(_fromUtf8("tabSourcePreparation"))
        self.gridLayout_23 = QtGui.QGridLayout(self.tabSourcePreparation)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.groupBoxConvertMRI = QtGui.QGroupBox(self.tabSourcePreparation)
        self.groupBoxConvertMRI.setObjectName(_fromUtf8("groupBoxConvertMRI"))
        self.gridLayout_23.addWidget(self.groupBoxConvertMRI, 1, 0, 1, 1)
        self.groupBoxCreateBEMMeshes = QtGui.QGroupBox(self.tabSourcePreparation)
        self.groupBoxCreateBEMMeshes.setObjectName(_fromUtf8("groupBoxCreateBEMMeshes"))
        self.gridLayout_23.addWidget(self.groupBoxCreateBEMMeshes, 2, 0, 1, 1)
        self.groupBoxReconstruction = QtGui.QGroupBox(self.tabSourcePreparation)
        self.groupBoxReconstruction.setFlat(False)
        self.groupBoxReconstruction.setCheckable(False)
        self.groupBoxReconstruction.setObjectName(_fromUtf8("groupBoxReconstruction"))
        self.widget = QtGui.QWidget(self.groupBoxReconstruction)
        self.widget.setGeometry(QtCore.QRect(10, 20, 398, 57))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_4 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setToolTip(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lineEditRecon = QtGui.QLineEdit(self.widget)
        self.lineEditRecon.setObjectName(_fromUtf8("lineEditRecon"))
        self.horizontalLayout_3.addWidget(self.lineEditRecon)
        self.pushButtonBrowseRecon = QtGui.QPushButton(self.widget)
        self.pushButtonBrowseRecon.setObjectName(_fromUtf8("pushButtonBrowseRecon"))
        self.horizontalLayout_3.addWidget(self.pushButtonBrowseRecon)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.widget1 = QtGui.QWidget(self.groupBoxReconstruction)
        self.widget1.setGeometry(QtCore.QRect(10, 80, 630, 57))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_6 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_5.addWidget(self.label_6)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButtonCheckTalairach = QtGui.QPushButton(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCheckTalairach.sizePolicy().hasHeightForWidth())
        self.pushButtonCheckTalairach.setSizePolicy(sizePolicy)
        self.pushButtonCheckTalairach.setObjectName(_fromUtf8("pushButtonCheckTalairach"))
        self.horizontalLayout_4.addWidget(self.pushButtonCheckTalairach)
        self.pushButtonSkullStrip = QtGui.QPushButton(self.widget1)
        self.pushButtonSkullStrip.setObjectName(_fromUtf8("pushButtonSkullStrip"))
        self.horizontalLayout_4.addWidget(self.pushButtonSkullStrip)
        self.pushButtonCheckSurfaces = QtGui.QPushButton(self.widget1)
        self.pushButtonCheckSurfaces.setObjectName(_fromUtf8("pushButtonCheckSurfaces"))
        self.horizontalLayout_4.addWidget(self.pushButtonCheckSurfaces)
        self.pushButtonCheckSegmentations = QtGui.QPushButton(self.widget1)
        self.pushButtonCheckSegmentations.setObjectName(_fromUtf8("pushButtonCheckSegmentations"))
        self.horizontalLayout_4.addWidget(self.pushButtonCheckSegmentations)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.gridLayout_23.addWidget(self.groupBoxReconstruction, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabSourcePreparation, _fromUtf8(""))
        self.gridLayout_22.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_22, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_7.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1114, 26))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidgetSubjects = QtGui.QDockWidget(MainWindow)
        self.dockWidgetSubjects.setMinimumSize(QtCore.QSize(330, 690))
        self.dockWidgetSubjects.setFloating(False)
        self.dockWidgetSubjects.setFeatures(QtGui.QDockWidget.DockWidgetFloatable)
        self.dockWidgetSubjects.setObjectName(_fromUtf8("dockWidgetSubjects"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_9 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.groupBoxSubjectInfo = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBoxSubjectInfo.setObjectName(_fromUtf8("groupBoxSubjectInfo"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBoxSubjectInfo)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.labelEvents = QtGui.QLabel(self.groupBoxSubjectInfo)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelEvents.setFont(font)
        self.labelEvents.setObjectName(_fromUtf8("labelEvents"))
        self.gridLayout_10.addWidget(self.labelEvents, 3, 0, 1, 1)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.labelFilters = QtGui.QLabel(self.groupBoxSubjectInfo)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelFilters.setFont(font)
        self.labelFilters.setObjectName(_fromUtf8("labelFilters"))
        self.verticalLayout_12.addWidget(self.labelFilters)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.labelLow = QtGui.QLabel(self.groupBoxSubjectInfo)
        self.labelLow.setLineWidth(1)
        self.labelLow.setScaledContents(True)
        self.labelLow.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelLow.setObjectName(_fromUtf8("labelLow"))
        self.horizontalLayout_30.addWidget(self.labelLow)
        self.labelLowValue = QtGui.QLabel(self.groupBoxSubjectInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLowValue.sizePolicy().hasHeightForWidth())
        self.labelLowValue.setSizePolicy(sizePolicy)
        self.labelLowValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelLowValue.setObjectName(_fromUtf8("labelLowValue"))
        self.horizontalLayout_30.addWidget(self.labelLowValue)
        self.verticalLayout_12.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.labelHigh = QtGui.QLabel(self.groupBoxSubjectInfo)
        self.labelHigh.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelHigh.setObjectName(_fromUtf8("labelHigh"))
        self.horizontalLayout_31.addWidget(self.labelHigh)
        self.labelHighValue = QtGui.QLabel(self.groupBoxSubjectInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHighValue.sizePolicy().hasHeightForWidth())
        self.labelHighValue.setSizePolicy(sizePolicy)
        self.labelHighValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelHighValue.setObjectName(_fromUtf8("labelHighValue"))
        self.horizontalLayout_31.addWidget(self.labelHighValue)
        self.verticalLayout_12.addLayout(self.horizontalLayout_31)
        self.gridLayout_10.addLayout(self.verticalLayout_12, 1, 0, 1, 1)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.labelChannels = QtGui.QLabel(self.groupBoxSubjectInfo)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelChannels.setFont(font)
        self.labelChannels.setObjectName(_fromUtf8("labelChannels"))
        self.verticalLayout_11.addWidget(self.labelChannels)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.labelEEG = QtGui.QLabel(self.groupBoxSubjectInfo)
        self.labelEEG.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelEEG.setObjectName(_fromUtf8("labelEEG"))
        self.horizontalLayout_25.addWidget(self.labelEEG)
        self.labelEEGValue = QtGui.QLabel(self.groupBoxSubjectInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelEEGValue.sizePolicy().hasHeightForWidth())
        self.labelEEGValue.setSizePolicy(sizePolicy)
        self.labelEEGValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelEEGValue.setObjectName(_fromUtf8("labelEEGValue"))
        self.horizontalLayout_25.addWidget(self.labelEEGValue)
        self.verticalLayout_11.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.labelGradMEG = QtGui.QLabel(self.groupBoxSubjectInfo)
        self.labelGradMEG.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelGradMEG.setObjectName(_fromUtf8("labelGradMEG"))
        self.horizontalLayout_27.addWidget(self.labelGradMEG)
        self.labelGradMEGValue = QtGui.QLabel(self.groupBoxSubjectInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelGradMEGValue.sizePolicy().hasHeightForWidth())
        self.labelGradMEGValue.setSizePolicy(sizePolicy)
        self.labelGradMEGValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelGradMEGValue.setObjectName(_fromUtf8("labelGradMEGValue"))
        self.horizontalLayout_27.addWidget(self.labelGradMEGValue)
        self.verticalLayout_11.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.labelMagMEG = QtGui.QLabel(self.groupBoxSubjectInfo)
        self.labelMagMEG.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelMagMEG.setObjectName(_fromUtf8("labelMagMEG"))
        self.horizontalLayout_28.addWidget(self.labelMagMEG)
        self.labelMagMEGValue = QtGui.QLabel(self.groupBoxSubjectInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMagMEGValue.sizePolicy().hasHeightForWidth())
        self.labelMagMEGValue.setSizePolicy(sizePolicy)
        self.labelMagMEGValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelMagMEGValue.setObjectName(_fromUtf8("labelMagMEGValue"))
        self.horizontalLayout_28.addWidget(self.labelMagMEGValue)
        self.verticalLayout_11.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.labelSamples = QtGui.QLabel(self.groupBoxSubjectInfo)
        self.labelSamples.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelSamples.setObjectName(_fromUtf8("labelSamples"))
        self.horizontalLayout_29.addWidget(self.labelSamples)
        self.labelSamplesValue = QtGui.QLabel(self.groupBoxSubjectInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSamplesValue.sizePolicy().hasHeightForWidth())
        self.labelSamplesValue.setSizePolicy(sizePolicy)
        self.labelSamplesValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelSamplesValue.setObjectName(_fromUtf8("labelSamplesValue"))
        self.horizontalLayout_29.addWidget(self.labelSamplesValue)
        self.verticalLayout_11.addLayout(self.horizontalLayout_29)
        self.gridLayout_10.addLayout(self.verticalLayout_11, 2, 0, 1, 1)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.labelSubjectGeneral = QtGui.QLabel(self.groupBoxSubjectInfo)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelSubjectGeneral.setFont(font)
        self.labelSubjectGeneral.setTextFormat(QtCore.Qt.AutoText)
        self.labelSubjectGeneral.setObjectName(_fromUtf8("labelSubjectGeneral"))
        self.verticalLayout_9.addWidget(self.labelSubjectGeneral)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.labelSubject = QtGui.QLabel(self.groupBoxSubjectInfo)
        self.labelSubject.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelSubject.setObjectName(_fromUtf8("labelSubject"))
        self.horizontalLayout_23.addWidget(self.labelSubject)
        self.labelSubjectValue = QtGui.QLabel(self.groupBoxSubjectInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSubjectValue.sizePolicy().hasHeightForWidth())
        self.labelSubjectValue.setSizePolicy(sizePolicy)
        self.labelSubjectValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelSubjectValue.setObjectName(_fromUtf8("labelSubjectValue"))
        self.horizontalLayout_23.addWidget(self.labelSubjectValue)
        self.verticalLayout_9.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.labelDate = QtGui.QLabel(self.groupBoxSubjectInfo)
        self.labelDate.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelDate.setObjectName(_fromUtf8("labelDate"))
        self.horizontalLayout_24.addWidget(self.labelDate)
        self.labelDateValue = QtGui.QLabel(self.groupBoxSubjectInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDateValue.sizePolicy().hasHeightForWidth())
        self.labelDateValue.setSizePolicy(sizePolicy)
        self.labelDateValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelDateValue.setObjectName(_fromUtf8("labelDateValue"))
        self.horizontalLayout_24.addWidget(self.labelDateValue)
        self.verticalLayout_9.addLayout(self.horizontalLayout_24)
        self.gridLayout_10.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.textBrowserEvents = QtGui.QTextBrowser(self.groupBoxSubjectInfo)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserEvents.setPalette(palette)
        self.textBrowserEvents.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowserEvents.setObjectName(_fromUtf8("textBrowserEvents"))
        self.gridLayout_10.addWidget(self.textBrowserEvents, 4, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBoxSubjectInfo, 1, 0, 1, 1)
        self.groupBoxSubject_2 = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBoxSubject_2.setObjectName(_fromUtf8("groupBoxSubject_2"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBoxSubject_2)
        self.gridLayout_12.setMargin(9)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.listWidgetSubjects = QtGui.QListWidget(self.groupBoxSubject_2)
        self.listWidgetSubjects.setObjectName(_fromUtf8("listWidgetSubjects"))
        self.gridLayout_12.addWidget(self.listWidgetSubjects, 0, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pushButtonActivateSubject = QtGui.QPushButton(self.groupBoxSubject_2)
        self.pushButtonActivateSubject.setObjectName(_fromUtf8("pushButtonActivateSubject"))
        self.gridLayout_5.addWidget(self.pushButtonActivateSubject, 0, 0, 1, 1)
        self.pushButtonAddSubjects = QtGui.QPushButton(self.groupBoxSubject_2)
        self.pushButtonAddSubjects.setObjectName(_fromUtf8("pushButtonAddSubjects"))
        self.gridLayout_5.addWidget(self.pushButtonAddSubjects, 0, 1, 1, 1)
        self.pushButtonRemoveSubject = QtGui.QPushButton(self.groupBoxSubject_2)
        self.pushButtonRemoveSubject.setObjectName(_fromUtf8("pushButtonRemoveSubject"))
        self.gridLayout_5.addWidget(self.pushButtonRemoveSubject, 1, 0, 1, 1)
        self.pushButtonMNE_Browse_Raw = QtGui.QPushButton(self.groupBoxSubject_2)
        self.pushButtonMNE_Browse_Raw.setObjectName(_fromUtf8("pushButtonMNE_Browse_Raw"))
        self.gridLayout_5.addWidget(self.pushButtonMNE_Browse_Raw, 1, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBoxSubject_2, 0, 0, 1, 1)
        self.dockWidgetSubjects.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidgetSubjects)
        self.actionCreate_experiment = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolBarIcons/images/createExperiment.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_experiment.setIcon(icon)
        self.actionCreate_experiment.setObjectName(_fromUtf8("actionCreate_experiment"))
        self.actionOpen_experiment = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolBarIcons/images/openExperiment.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_experiment.setIcon(icon1)
        self.actionOpen_experiment.setObjectName(_fromUtf8("actionOpen_experiment"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionSet_workspace = QtGui.QAction(MainWindow)
        self.actionSet_workspace.setObjectName(_fromUtf8("actionSet_workspace"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionShowExperimentInfo = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolBarIcons/images/showExperimentInfo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShowExperimentInfo.setIcon(icon2)
        self.actionShowExperimentInfo.setObjectName(_fromUtf8("actionShowExperimentInfo"))
        self.actionHide_Show_subject_list_and_info = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolBarIcons/images/subjectList.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHide_Show_subject_list_and_info.setIcon(icon3)
        self.actionHide_Show_subject_list_and_info.setObjectName(_fromUtf8("actionHide_Show_subject_list_and_info"))
        self.actionToggle_whatsthis_mode = QtGui.QAction(MainWindow)
        self.actionToggle_whatsthis_mode.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/toolBarIcons/images/whatsThisMode.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionToggle_whatsthis_mode.setIcon(icon4)
        self.actionToggle_whatsthis_mode.setObjectName(_fromUtf8("actionToggle_whatsthis_mode"))
        self.menuFile.addAction(self.actionCreate_experiment)
        self.menuFile.addAction(self.actionOpen_experiment)
        self.menuFile.addAction(self.actionSet_workspace)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionShowExperimentInfo)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuTools.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionCreate_experiment)
        self.toolBar.addAction(self.actionOpen_experiment)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionShowExperimentInfo)
        self.toolBar.addAction(self.actionToggle_whatsthis_mode)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHide_Show_subject_list_and_info)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QObject.connect(self.radioButtonLobe, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.comboBoxLobes.setEnabled)
        QtCore.QObject.connect(self.radioButtonCustomChannels, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.plainTextEditCustomChannelsToAverage.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Meggie", None))
        self.groupBoxPreprocessingCheckBoxes.setTitle(_translate("MainWindow", "Preprocessing steps completed:", None))
        self.labelEOGComputed_2.setText(_translate("MainWindow", "EOG projections", None))
        self.labelECGApplied_2.setText(_translate("MainWindow", "Computed", None))
        self.labelECGComputed_2.setText(_translate("MainWindow", "ECG projections", None))
        self.labelEOGApplied_2.setText(_translate("MainWindow", "Applied", None))
        self.labelMaxFilter_2.setText(_translate("MainWindow", "MaxFilter", None))
        self.groupBoxAvailablePreprocessing.setTitle(_translate("MainWindow", "Available actions:", None))
        self.pushButtonMaxFilter.setText(_translate("MainWindow", "MaxFilter...", None))
        self.pushButtonFilter.setText(_translate("MainWindow", "Filter...", None))
        self.label_2.setText(_translate("MainWindow", "Choose subjects to use in EOG/ECG calculation:", None))
        self.pushButtonECG.setText(_translate("MainWindow", "Calculate ECG projections...", None))
        self.pushButtonApplyECG.setText(_translate("MainWindow", "Apply ECG projections...", None))
        self.pushButtonEOG.setText(_translate("MainWindow", "Calculate EOG projections...", None))
        self.pushButtonApplyEOG.setText(_translate("MainWindow", "Apply EOG projections...", None))
        self.groupBoxVisualization_2.setTitle(_translate("MainWindow", "Visualization:", None))
        self.pushButtonSpectrum.setText(_translate("MainWindow", "Magnitude spectrum", None))
        self.pushButtonMNE_Browse_Raw_2.setText(_translate("MainWindow", "MNE_Browse_Raw", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPreprocessing), _translate("MainWindow", "Preprocessing", None))
        self.groupBoxAvailableEpoching.setTitle(_translate("MainWindow", "Available actions for selected collection:", None))
        self.pushButtonVisualizeEpochChannels.setText(_translate("MainWindow", "Visualize epochs in selected channels...", None))
        self.pushButtonCreateEpochs.setText(_translate("MainWindow", "Create epochs...", None))
        self.pushButtonModifyEpochs.setText(_translate("MainWindow", "Modify selected epochs...", None))
        self.pushButtonDeleteEpochs.setText(_translate("MainWindow", "Delete selected epochs", None))
        self.pushButtonSaveEpochs.setText(_translate("MainWindow", "Save selected epochs", None))
        self.pushButtonLoadEpochs.setText(_translate("MainWindow", "Load epochs", None))
        self.labelWorkingFile.setText(_translate("MainWindow", "Epoch collection source file:", None))
        self.groupBoxRejections.setTitle(_translate("MainWindow", "Rejection parameters", None))
        self.labelMagReject.setText(_translate("MainWindow", "Mag:", None))
        self.labelGradReject.setText(_translate("MainWindow", "Grad:", None))
        self.labelEegReject.setText(_translate("MainWindow", "EEG:", None))
        self.labelEogReject.setText(_translate("MainWindow", "EOG:", None))
        self.labelStimReject.setText(_translate("MainWindow", "Stim:", None))
        self.groupBoxEpochTimes.setTitle(_translate("MainWindow", "Time limits", None))
        self.labelTmin.setText(_translate("MainWindow", "Start time:", None))
        self.labelTmax.setText(_translate("MainWindow", "End time:", None))
        self.label_3.setText(_translate("MainWindow", "Epoch collection parameters:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEpoching), _translate("MainWindow", "Epoching", None))
        self.groupBoxAvailableTFR.setTitle(_translate("MainWindow", "Available actions:", None))
        self.pushButtonTFRTopology.setText(_translate("MainWindow", "TFR topology vizualization", None))
        self.pushButtonTFR.setText(_translate("MainWindow", "TFR visualization", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTFR), _translate("MainWindow", "TFR", None))
        self.groupBoxAvailableAveraging.setTitle(_translate("MainWindow", "Available actions:", None))
        self.groupBoxChannelAverages.setTitle(_translate("MainWindow", "Channel Averages", None))
        self.pushButtonChannelAverages.setText(_translate("MainWindow", "Show channel averages", None))
        self.radioButtonLobe.setText(_translate("MainWindow", "Lobe:", None))
        self.labelChannelAverages.setText(_translate("MainWindow", "Show channel averages for:", None))
        self.radioButtonCustomChannels.setText(_translate("MainWindow", "Custom channels:", None))
        self.pushButtonCreateEvoked.setText(_translate("MainWindow", "Create evoked dataset", None))
        self.label.setText(_translate("MainWindow", "Creates an evoked dataset from the currently chosen epoch collection if no events are selected. Otherwise creates an evoked dataset from the selected events of the currently chosen epoch collection.", None))
        self.groupBoxEvokeds.setTitle(_translate("MainWindow", "Evoked datasets (averaged epoch collections):", None))
        self.pushButtonSaveEvoked.setText(_translate("MainWindow", "Save evoked", None))
        self.pushButtonDeleteEvoked.setText(_translate("MainWindow", "Delete evoked", None))
        self.pushButtonLoadEvoked.setText(_translate("MainWindow", "Load evoked", None))
        self.pushButtonVisualizeEvokedDataset.setText(_translate("MainWindow", "Visualize evoked dataset", None))
        self.pushButtonOpenEvokedStatsDialog.setText(_translate("MainWindow", "Show evoked stats", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAveraging), _translate("MainWindow", "Averaging", None))
        self.groupBoxConvertMRI.setTitle(_translate("MainWindow", "2. Convert MRI image data to an MNE-friendly format", None))
        self.groupBoxCreateBEMMeshes.setTitle(_translate("MainWindow", "3. Create BEM model meshes", None))
        self.groupBoxReconstruction.setTitle(_translate("MainWindow", "1. MRI image reconstruction", None))
        self.label_4.setWhatsThis(_translate("MainWindow", "MRI-image reconstruction can take a day, therefore Meggie only allows importing the pre-reconstructed image. You can, however, examine the reconstructed image with provided tools.", None))
        self.label_4.setText(_translate("MainWindow", "1. Select directory of the reconstructed MRI file:", None))
        self.lineEditRecon.setWhatsThis(_translate("MainWindow", "MRI-image reconstruction can take a day, therefore Meggie only allows importing the pre-reconstructed image. You can, however, examine the reconstructed image with provided tools.", None))
        self.pushButtonBrowseRecon.setWhatsThis(_translate("MainWindow", "MRI-image reconstruction can take a day, therefore Meggie only allows importing the pre-reconstructed image. You can, however, examine the reconstructed image with provided tools.", None))
        self.pushButtonBrowseRecon.setText(_translate("MainWindow", "Browse...", None))
        self.label_6.setText(_translate("MainWindow", "2. Examine the reconstructed image:", None))
        self.pushButtonCheckTalairach.setText(_translate("MainWindow", "Check Talairach transform", None))
        self.pushButtonSkullStrip.setText(_translate("MainWindow", "Check skull strip", None))
        self.pushButtonCheckSurfaces.setText(_translate("MainWindow", "Check surfaces", None))
        self.pushButtonCheckSegmentations.setText(_translate("MainWindow", "Check segmentation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSourcePreparation), _translate("MainWindow", "Source modelling preparation", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.groupBoxSubjectInfo.setTitle(_translate("MainWindow", "Subject info", None))
        self.labelEvents.setText(_translate("MainWindow", "Events:", None))
        self.labelFilters.setText(_translate("MainWindow", "Filters:", None))
        self.labelLow.setText(_translate("MainWindow", "Low-pass:", None))
        self.labelLowValue.setText(_translate("MainWindow", "Low-pass value", None))
        self.labelHigh.setText(_translate("MainWindow", "High-pass:", None))
        self.labelHighValue.setText(_translate("MainWindow", "High-pass value", None))
        self.labelChannels.setText(_translate("MainWindow", "Channels:", None))
        self.labelEEG.setText(_translate("MainWindow", "EEG channels:", None))
        self.labelEEGValue.setText(_translate("MainWindow", "EEG value", None))
        self.labelGradMEG.setText(_translate("MainWindow", "Gradiometers:", None))
        self.labelGradMEGValue.setText(_translate("MainWindow", "Grad. MEG value", None))
        self.labelMagMEG.setText(_translate("MainWindow", "Magnetometers:", None))
        self.labelMagMEGValue.setText(_translate("MainWindow", "Mag. MEG value", None))
        self.labelSamples.setText(_translate("MainWindow", "Sampling frequency:", None))
        self.labelSamplesValue.setText(_translate("MainWindow", "SamplesValue", None))
        self.labelSubjectGeneral.setText(_translate("MainWindow", "General:", None))
        self.labelSubject.setText(_translate("MainWindow", "Name:", None))
        self.labelSubjectValue.setText(_translate("MainWindow", "TextLabel", None))
        self.labelDate.setText(_translate("MainWindow", "Date:", None))
        self.labelDateValue.setText(_translate("MainWindow", "DateValue", None))
        self.groupBoxSubject_2.setTitle(_translate("MainWindow", "Subjects", None))
        self.pushButtonActivateSubject.setText(_translate("MainWindow", "Activate selected", None))
        self.pushButtonAddSubjects.setText(_translate("MainWindow", "Add new...", None))
        self.pushButtonRemoveSubject.setText(_translate("MainWindow", "Remove selected", None))
        self.pushButtonMNE_Browse_Raw.setText(_translate("MainWindow", "View raw file", None))
        self.actionCreate_experiment.setText(_translate("MainWindow", "Create New Experiment...", None))
        self.actionOpen_experiment.setText(_translate("MainWindow", "Open Experiment...", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionSet_workspace.setText(_translate("MainWindow", "Set Workspace...", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionShowExperimentInfo.setText(_translate("MainWindow", "Show experiment info", None))
        self.actionShowExperimentInfo.setToolTip(_translate("MainWindow", "Show more info about experiment", None))
        self.actionHide_Show_subject_list_and_info.setText(_translate("MainWindow", "Hide/show subject list and info", None))
        self.actionHide_Show_subject_list_and_info.setToolTip(_translate("MainWindow", "Hide/show subject list and info", None))
        self.actionToggle_whatsthis_mode.setText(_translate("MainWindow", "Toggle whatsthis mode", None))
        self.actionToggle_whatsthis_mode.setToolTip(_translate("MainWindow", "Toggle mouseover help mode on/off", None))

import mainWindowIcons_rc
