# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eventSelectionDialog.ui'
#
# Created: Wed Apr  8 08:19:33 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EventSelectionDialog(object):
    def setupUi(self, EventSelectionDialog):
        EventSelectionDialog.setObjectName(_fromUtf8("EventSelectionDialog"))
        EventSelectionDialog.setWindowModality(QtCore.Qt.WindowModal)
        EventSelectionDialog.resize(942, 687)
        self.gridLayout = QtGui.QGridLayout(EventSelectionDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(600, 0, -1, -1)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.pushButtonCancel = QtGui.QPushButton(EventSelectionDialog)
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))
        self.horizontalLayout_10.addWidget(self.pushButtonCancel)
        self.pushButtonCreateEpochs = QtGui.QPushButton(EventSelectionDialog)
        self.pushButtonCreateEpochs.setObjectName(_fromUtf8("pushButtonCreateEpochs"))
        self.horizontalLayout_10.addWidget(self.pushButtonCreateEpochs)
        self.gridLayout.addLayout(self.horizontalLayout_10, 4, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(EventSelectionDialog)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 924, 634))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(741, 400))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 911, 561))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBoxEvent = QtGui.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBoxEvent.setObjectName(_fromUtf8("groupBoxEvent"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.groupBoxEvent)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 421, 151))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.labelEventID = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.labelEventID.setObjectName(_fromUtf8("labelEventID"))
        self.horizontalLayout_7.addWidget(self.labelEventID)
        self.comboBoxEventID = QtGui.QComboBox(self.verticalLayoutWidget_4)
        self.comboBoxEventID.setObjectName(_fromUtf8("comboBoxEventID"))
        self.horizontalLayout_7.addWidget(self.comboBoxEventID)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.labelName = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.labelName.setObjectName(_fromUtf8("labelName"))
        self.horizontalLayout_5.addWidget(self.labelName)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.lineEditName = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEditName.setObjectName(_fromUtf8("lineEditName"))
        self.horizontalLayout_5.addWidget(self.lineEditName)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pushButtonAdd = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButtonAdd.setObjectName(_fromUtf8("pushButtonAdd"))
        self.verticalLayout_3.addWidget(self.pushButtonAdd)
        self.pushButtonRemove = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButtonRemove.setEnabled(False)
        self.pushButtonRemove.setObjectName(_fromUtf8("pushButtonRemove"))
        self.verticalLayout_3.addWidget(self.pushButtonRemove)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.gridLayout_2.addWidget(self.groupBoxEvent, 1, 0, 1, 1)
        self.groupBoxRejection = QtGui.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBoxRejection.setObjectName(_fromUtf8("groupBoxRejection"))
        self.layoutWidget = QtGui.QWidget(self.groupBoxRejection)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 421, 141))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.checkBoxGrad = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxGrad.setChecked(True)
        self.checkBoxGrad.setObjectName(_fromUtf8("checkBoxGrad"))
        self.horizontalLayout_31.addWidget(self.checkBoxGrad)
        self.doubleSpinBoxGradReject_3 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBoxGradReject_3.setPrefix(_fromUtf8(""))
        self.doubleSpinBoxGradReject_3.setMaximum(1000000000.0)
        self.doubleSpinBoxGradReject_3.setProperty("value", 3000.0)
        self.doubleSpinBoxGradReject_3.setObjectName(_fromUtf8("doubleSpinBoxGradReject_3"))
        self.horizontalLayout_31.addWidget(self.doubleSpinBoxGradReject_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.checkBoxMag = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxMag.setChecked(True)
        self.checkBoxMag.setObjectName(_fromUtf8("checkBoxMag"))
        self.horizontalLayout_33.addWidget(self.checkBoxMag)
        self.doubleSpinBoxMagReject_3 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBoxMagReject_3.setMaximum(1000000000.0)
        self.doubleSpinBoxMagReject_3.setProperty("value", 4000.0)
        self.doubleSpinBoxMagReject_3.setObjectName(_fromUtf8("doubleSpinBoxMagReject_3"))
        self.horizontalLayout_33.addWidget(self.doubleSpinBoxMagReject_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.checkBoxEeg = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxEeg.setChecked(False)
        self.checkBoxEeg.setObjectName(_fromUtf8("checkBoxEeg"))
        self.horizontalLayout_32.addWidget(self.checkBoxEeg)
        self.doubleSpinBoxEEGReject_3 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBoxEEGReject_3.setEnabled(False)
        self.doubleSpinBoxEEGReject_3.setMaximum(1000000000.0)
        self.doubleSpinBoxEEGReject_3.setProperty("value", 40.0)
        self.doubleSpinBoxEEGReject_3.setObjectName(_fromUtf8("doubleSpinBoxEEGReject_3"))
        self.horizontalLayout_32.addWidget(self.doubleSpinBoxEEGReject_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.checkBoxEog = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxEog.setChecked(False)
        self.checkBoxEog.setObjectName(_fromUtf8("checkBoxEog"))
        self.horizontalLayout_34.addWidget(self.checkBoxEog)
        self.doubleSpinBoxEOGReject_3 = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBoxEOGReject_3.setEnabled(False)
        self.doubleSpinBoxEOGReject_3.setMaximum(1000000000.0)
        self.doubleSpinBoxEOGReject_3.setProperty("value", 250.0)
        self.doubleSpinBoxEOGReject_3.setObjectName(_fromUtf8("doubleSpinBoxEOGReject_3"))
        self.horizontalLayout_34.addWidget(self.doubleSpinBoxEOGReject_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_34)
        self.gridLayout_2.addWidget(self.groupBoxRejection, 2, 0, 1, 1)
        self.groupBoxEpoch = QtGui.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBoxEpoch.setObjectName(_fromUtf8("groupBoxEpoch"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBoxEpoch)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 421, 151))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelCollectionName = QtGui.QLabel(self.layoutWidget1)
        self.labelCollectionName.setObjectName(_fromUtf8("labelCollectionName"))
        self.horizontalLayout.addWidget(self.labelCollectionName)
        self.lineEditCollectionName = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEditCollectionName.setObjectName(_fromUtf8("lineEditCollectionName"))
        self.horizontalLayout.addWidget(self.lineEditCollectionName)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelTmin = QtGui.QLabel(self.layoutWidget1)
        self.labelTmin.setObjectName(_fromUtf8("labelTmin"))
        self.horizontalLayout_2.addWidget(self.labelTmin)
        self.doubleSpinBoxTmin = QtGui.QDoubleSpinBox(self.layoutWidget1)
        self.doubleSpinBoxTmin.setDecimals(3)
        self.doubleSpinBoxTmin.setMinimum(-10.0)
        self.doubleSpinBoxTmin.setSingleStep(0.1)
        self.doubleSpinBoxTmin.setProperty("value", -0.2)
        self.doubleSpinBoxTmin.setObjectName(_fromUtf8("doubleSpinBoxTmin"))
        self.horizontalLayout_2.addWidget(self.doubleSpinBoxTmin)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelTmax = QtGui.QLabel(self.layoutWidget1)
        self.labelTmax.setObjectName(_fromUtf8("labelTmax"))
        self.horizontalLayout_3.addWidget(self.labelTmax)
        self.doubleSpinBoxTmax = QtGui.QDoubleSpinBox(self.layoutWidget1)
        self.doubleSpinBoxTmax.setDecimals(3)
        self.doubleSpinBoxTmax.setMaximum(9.9)
        self.doubleSpinBoxTmax.setSingleStep(0.1)
        self.doubleSpinBoxTmax.setProperty("value", 0.5)
        self.doubleSpinBoxTmax.setObjectName(_fromUtf8("doubleSpinBoxTmax"))
        self.horizontalLayout_3.addWidget(self.doubleSpinBoxTmax)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.checkBoxStim = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBoxStim.setChecked(False)
        self.checkBoxStim.setObjectName(_fromUtf8("checkBoxStim"))
        self.verticalLayout_6.addWidget(self.checkBoxStim)
        self.gridLayout_2.addWidget(self.groupBoxEpoch, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBoxEventList = QtGui.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBoxEventList.setObjectName(_fromUtf8("groupBoxEventList"))
        self.listWidgetEvents = QtGui.QListWidget(self.groupBoxEventList)
        self.listWidgetEvents.setGeometry(QtCore.QRect(10, 30, 431, 461))
        self.listWidgetEvents.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidgetEvents.setObjectName(_fromUtf8("listWidgetEvents"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.groupBoxEventList)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 490, 431, 61))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButtonSaveEvents = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonSaveEvents.setObjectName(_fromUtf8("pushButtonSaveEvents"))
        self.horizontalLayout_4.addWidget(self.pushButtonSaveEvents)
        self.pushButtonReadEvents = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonReadEvents.setObjectName(_fromUtf8("pushButtonReadEvents"))
        self.horizontalLayout_4.addWidget(self.pushButtonReadEvents)
        self.verticalLayout_2.addWidget(self.groupBoxEventList)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)

        self.retranslateUi(EventSelectionDialog)
        QtCore.QObject.connect(self.pushButtonCreateEpochs, QtCore.SIGNAL(_fromUtf8("clicked()")), EventSelectionDialog.accept)
        QtCore.QObject.connect(self.pushButtonCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), EventSelectionDialog.reject)
        QtCore.QObject.connect(self.checkBoxGrad, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBoxGradReject_3.setEnabled)
        QtCore.QObject.connect(self.checkBoxMag, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBoxMagReject_3.setEnabled)
        QtCore.QObject.connect(self.checkBoxEeg, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBoxEEGReject_3.setEnabled)
        QtCore.QObject.connect(self.checkBoxEog, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBoxEOGReject_3.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(EventSelectionDialog)
        EventSelectionDialog.setTabOrder(self.scrollArea, self.lineEditCollectionName)
        EventSelectionDialog.setTabOrder(self.lineEditCollectionName, self.doubleSpinBoxTmin)
        EventSelectionDialog.setTabOrder(self.doubleSpinBoxTmin, self.doubleSpinBoxTmax)
        EventSelectionDialog.setTabOrder(self.doubleSpinBoxTmax, self.checkBoxStim)
        EventSelectionDialog.setTabOrder(self.checkBoxStim, self.comboBoxEventID)
        EventSelectionDialog.setTabOrder(self.comboBoxEventID, self.lineEditName)
        EventSelectionDialog.setTabOrder(self.lineEditName, self.pushButtonAdd)
        EventSelectionDialog.setTabOrder(self.pushButtonAdd, self.pushButtonRemove)
        EventSelectionDialog.setTabOrder(self.pushButtonRemove, self.checkBoxGrad)
        EventSelectionDialog.setTabOrder(self.checkBoxGrad, self.doubleSpinBoxGradReject_3)
        EventSelectionDialog.setTabOrder(self.doubleSpinBoxGradReject_3, self.checkBoxMag)
        EventSelectionDialog.setTabOrder(self.checkBoxMag, self.doubleSpinBoxMagReject_3)
        EventSelectionDialog.setTabOrder(self.doubleSpinBoxMagReject_3, self.checkBoxEeg)
        EventSelectionDialog.setTabOrder(self.checkBoxEeg, self.doubleSpinBoxEEGReject_3)
        EventSelectionDialog.setTabOrder(self.doubleSpinBoxEEGReject_3, self.checkBoxEog)
        EventSelectionDialog.setTabOrder(self.checkBoxEog, self.doubleSpinBoxEOGReject_3)
        EventSelectionDialog.setTabOrder(self.doubleSpinBoxEOGReject_3, self.listWidgetEvents)
        EventSelectionDialog.setTabOrder(self.listWidgetEvents, self.pushButtonSaveEvents)
        EventSelectionDialog.setTabOrder(self.pushButtonSaveEvents, self.pushButtonReadEvents)
        EventSelectionDialog.setTabOrder(self.pushButtonReadEvents, self.pushButtonCancel)
        EventSelectionDialog.setTabOrder(self.pushButtonCancel, self.pushButtonCreateEpochs)

    def retranslateUi(self, EventSelectionDialog):
        EventSelectionDialog.setWindowTitle(_translate("EventSelectionDialog", "Meggie - Epoch Creation", None))
        self.pushButtonCancel.setText(_translate("EventSelectionDialog", "Cancel", None))
        self.pushButtonCreateEpochs.setText(_translate("EventSelectionDialog", "Create epochs", None))
        self.groupBoxEvent.setTitle(_translate("EventSelectionDialog", "Select events to include in epoch collection", None))
        self.labelEventID.setText(_translate("EventSelectionDialog", "Event ID:", None))
        self.labelName.setText(_translate("EventSelectionDialog", "Event name:      ", None))
        self.pushButtonAdd.setText(_translate("EventSelectionDialog", "Add to list >>", None))
        self.pushButtonRemove.setText(_translate("EventSelectionDialog", "<< Remove", None))
        self.groupBoxRejection.setTitle(_translate("EventSelectionDialog", "Rejection parameters", None))
        self.checkBoxGrad.setToolTip(_translate("EventSelectionDialog", "Include or exclude grad channels", None))
        self.checkBoxGrad.setText(_translate("EventSelectionDialog", "Grad", None))
        self.doubleSpinBoxGradReject_3.setSuffix(_translate("EventSelectionDialog", " fT/cm", None))
        self.checkBoxMag.setToolTip(_translate("EventSelectionDialog", "Include or exclude mag channels", None))
        self.checkBoxMag.setText(_translate("EventSelectionDialog", "Mag", None))
        self.doubleSpinBoxMagReject_3.setSuffix(_translate("EventSelectionDialog", " fT", None))
        self.checkBoxEeg.setToolTip(_translate("EventSelectionDialog", "Include or exclude eeg channels", None))
        self.checkBoxEeg.setText(_translate("EventSelectionDialog", "EEG", None))
        self.doubleSpinBoxEEGReject_3.setSuffix(_translate("EventSelectionDialog", " uV", None))
        self.checkBoxEog.setToolTip(_translate("EventSelectionDialog", "Include or exclude eog channels", None))
        self.checkBoxEog.setText(_translate("EventSelectionDialog", "EOG", None))
        self.doubleSpinBoxEOGReject_3.setSuffix(_translate("EventSelectionDialog", " uV", None))
        self.groupBoxEpoch.setTitle(_translate("EventSelectionDialog", "Epoch collection", None))
        self.labelCollectionName.setText(_translate("EventSelectionDialog", "Collection name:", None))
        self.lineEditCollectionName.setText(_translate("EventSelectionDialog", "Epochs", None))
        self.labelTmin.setText(_translate("EventSelectionDialog", "Start time:", None))
        self.doubleSpinBoxTmin.setSuffix(_translate("EventSelectionDialog", " s", None))
        self.labelTmax.setText(_translate("EventSelectionDialog", "End time:", None))
        self.doubleSpinBoxTmax.setSuffix(_translate("EventSelectionDialog", " s", None))
        self.checkBoxStim.setToolTip(_translate("EventSelectionDialog", "Include or exclude stim channels", None))
        self.checkBoxStim.setText(_translate("EventSelectionDialog", "Include stim channel in collection", None))
        self.groupBoxEventList.setTitle(_translate("EventSelectionDialog", "List of events with given event ID", None))
        self.pushButtonSaveEvents.setText(_translate("EventSelectionDialog", "Save events to file...", None))
        self.pushButtonReadEvents.setText(_translate("EventSelectionDialog", "Read events from xls file...", None))

