# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'groupEpochingDialog.ui'
#
# Created: Fri Aug 28 05:43:45 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GroupEpochDialog(object):
    def setupUi(self, GroupEpochDialog):
        GroupEpochDialog.setObjectName(_fromUtf8("GroupEpochDialog"))
        GroupEpochDialog.resize(627, 628)
        self.gridLayout = QtGui.QGridLayout(GroupEpochDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBoxEpoch = QtGui.QGroupBox(GroupEpochDialog)
        self.groupBoxEpoch.setObjectName(_fromUtf8("groupBoxEpoch"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBoxEpoch)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelCollectionName = QtGui.QLabel(self.groupBoxEpoch)
        self.labelCollectionName.setObjectName(_fromUtf8("labelCollectionName"))
        self.horizontalLayout.addWidget(self.labelCollectionName)
        self.lineEditCollectionName = QtGui.QLineEdit(self.groupBoxEpoch)
        self.lineEditCollectionName.setObjectName(_fromUtf8("lineEditCollectionName"))
        self.horizontalLayout.addWidget(self.lineEditCollectionName)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelTmin = QtGui.QLabel(self.groupBoxEpoch)
        self.labelTmin.setObjectName(_fromUtf8("labelTmin"))
        self.horizontalLayout_2.addWidget(self.labelTmin)
        self.doubleSpinBoxTmin = QtGui.QDoubleSpinBox(self.groupBoxEpoch)
        self.doubleSpinBoxTmin.setDecimals(3)
        self.doubleSpinBoxTmin.setMinimum(-10.0)
        self.doubleSpinBoxTmin.setSingleStep(0.1)
        self.doubleSpinBoxTmin.setProperty("value", -0.2)
        self.doubleSpinBoxTmin.setObjectName(_fromUtf8("doubleSpinBoxTmin"))
        self.horizontalLayout_2.addWidget(self.doubleSpinBoxTmin)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelTmax = QtGui.QLabel(self.groupBoxEpoch)
        self.labelTmax.setObjectName(_fromUtf8("labelTmax"))
        self.horizontalLayout_3.addWidget(self.labelTmax)
        self.doubleSpinBoxTmax = QtGui.QDoubleSpinBox(self.groupBoxEpoch)
        self.doubleSpinBoxTmax.setDecimals(3)
        self.doubleSpinBoxTmax.setMaximum(9.9)
        self.doubleSpinBoxTmax.setSingleStep(0.1)
        self.doubleSpinBoxTmax.setProperty("value", 0.5)
        self.doubleSpinBoxTmax.setObjectName(_fromUtf8("doubleSpinBoxTmax"))
        self.horizontalLayout_3.addWidget(self.doubleSpinBoxTmax)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.checkBoxStim = QtGui.QCheckBox(self.groupBoxEpoch)
        self.checkBoxStim.setChecked(True)
        self.checkBoxStim.setObjectName(_fromUtf8("checkBoxStim"))
        self.verticalLayout_6.addWidget(self.checkBoxStim)
        self.gridLayout_6.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.labelEventID = QtGui.QLabel(self.groupBoxEpoch)
        self.labelEventID.setObjectName(_fromUtf8("labelEventID"))
        self.horizontalLayout_7.addWidget(self.labelEventID)
        self.spinBoxEventId = QtGui.QSpinBox(self.groupBoxEpoch)
        self.spinBoxEventId.setMinimum(1)
        self.spinBoxEventId.setMaximum(100000)
        self.spinBoxEventId.setProperty("value", 1)
        self.spinBoxEventId.setObjectName(_fromUtf8("spinBoxEventId"))
        self.horizontalLayout_7.addWidget(self.spinBoxEventId)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.labelMask = QtGui.QLabel(self.groupBoxEpoch)
        self.labelMask.setObjectName(_fromUtf8("labelMask"))
        self.horizontalLayout_6.addWidget(self.labelMask)
        self.spinBoxMask = QtGui.QSpinBox(self.groupBoxEpoch)
        self.spinBoxMask.setEnabled(True)
        self.spinBoxMask.setMinimum(0)
        self.spinBoxMask.setMaximum(9999)
        self.spinBoxMask.setProperty("value", 0)
        self.spinBoxMask.setObjectName(_fromUtf8("spinBoxMask"))
        self.horizontalLayout_6.addWidget(self.spinBoxMask)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.labelName = QtGui.QLabel(self.groupBoxEpoch)
        self.labelName.setObjectName(_fromUtf8("labelName"))
        self.horizontalLayout_5.addWidget(self.labelName)
        self.lineEditName = QtGui.QLineEdit(self.groupBoxEpoch)
        self.lineEditName.setObjectName(_fromUtf8("lineEditName"))
        self.horizontalLayout_5.addWidget(self.lineEditName)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.gridLayout_6.addLayout(self.verticalLayout_4, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxEpoch, 0, 0, 2, 1)
        self.groupBoxRejection = QtGui.QGroupBox(GroupEpochDialog)
        self.groupBoxRejection.setObjectName(_fromUtf8("groupBoxRejection"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBoxRejection)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.checkBoxGrad = QtGui.QCheckBox(self.groupBoxRejection)
        self.checkBoxGrad.setChecked(True)
        self.checkBoxGrad.setObjectName(_fromUtf8("checkBoxGrad"))
        self.horizontalLayout_31.addWidget(self.checkBoxGrad)
        self.doubleSpinBoxGradReject_3 = QtGui.QDoubleSpinBox(self.groupBoxRejection)
        self.doubleSpinBoxGradReject_3.setPrefix(_fromUtf8(""))
        self.doubleSpinBoxGradReject_3.setMaximum(1000000000.0)
        self.doubleSpinBoxGradReject_3.setSingleStep(100.0)
        self.doubleSpinBoxGradReject_3.setProperty("value", 3000.0)
        self.doubleSpinBoxGradReject_3.setObjectName(_fromUtf8("doubleSpinBoxGradReject_3"))
        self.horizontalLayout_31.addWidget(self.doubleSpinBoxGradReject_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.checkBoxMag = QtGui.QCheckBox(self.groupBoxRejection)
        self.checkBoxMag.setChecked(True)
        self.checkBoxMag.setObjectName(_fromUtf8("checkBoxMag"))
        self.horizontalLayout_33.addWidget(self.checkBoxMag)
        self.doubleSpinBoxMagReject_3 = QtGui.QDoubleSpinBox(self.groupBoxRejection)
        self.doubleSpinBoxMagReject_3.setMaximum(1000000000.0)
        self.doubleSpinBoxMagReject_3.setSingleStep(100.0)
        self.doubleSpinBoxMagReject_3.setProperty("value", 4000.0)
        self.doubleSpinBoxMagReject_3.setObjectName(_fromUtf8("doubleSpinBoxMagReject_3"))
        self.horizontalLayout_33.addWidget(self.doubleSpinBoxMagReject_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.checkBoxEeg = QtGui.QCheckBox(self.groupBoxRejection)
        self.checkBoxEeg.setChecked(False)
        self.checkBoxEeg.setObjectName(_fromUtf8("checkBoxEeg"))
        self.horizontalLayout_32.addWidget(self.checkBoxEeg)
        self.doubleSpinBoxEEGReject_3 = QtGui.QDoubleSpinBox(self.groupBoxRejection)
        self.doubleSpinBoxEEGReject_3.setEnabled(False)
        self.doubleSpinBoxEEGReject_3.setMaximum(1000000000.0)
        self.doubleSpinBoxEEGReject_3.setProperty("value", 40.0)
        self.doubleSpinBoxEEGReject_3.setObjectName(_fromUtf8("doubleSpinBoxEEGReject_3"))
        self.horizontalLayout_32.addWidget(self.doubleSpinBoxEEGReject_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.checkBoxEog = QtGui.QCheckBox(self.groupBoxRejection)
        self.checkBoxEog.setChecked(False)
        self.checkBoxEog.setObjectName(_fromUtf8("checkBoxEog"))
        self.horizontalLayout_34.addWidget(self.checkBoxEog)
        self.doubleSpinBoxEOGReject_3 = QtGui.QDoubleSpinBox(self.groupBoxRejection)
        self.doubleSpinBoxEOGReject_3.setEnabled(False)
        self.doubleSpinBoxEOGReject_3.setMaximum(1000000000.0)
        self.doubleSpinBoxEOGReject_3.setProperty("value", 250.0)
        self.doubleSpinBoxEOGReject_3.setObjectName(_fromUtf8("doubleSpinBoxEOGReject_3"))
        self.horizontalLayout_34.addWidget(self.doubleSpinBoxEOGReject_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_34)
        self.gridLayout_4.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxRejection, 2, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(GroupEpochDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 2)
        self.listWidgetSubjects = QtGui.QListWidget(GroupEpochDialog)
        self.listWidgetSubjects.setObjectName(_fromUtf8("listWidgetSubjects"))
        self.gridLayout.addWidget(self.listWidgetSubjects, 0, 1, 3, 1)

        self.retranslateUi(GroupEpochDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), GroupEpochDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), GroupEpochDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(GroupEpochDialog)

    def retranslateUi(self, GroupEpochDialog):
        GroupEpochDialog.setWindowTitle(_translate("GroupEpochDialog", "Group epoching", None))
        self.groupBoxEpoch.setTitle(_translate("GroupEpochDialog", "Epoch collection", None))
        self.labelCollectionName.setText(_translate("GroupEpochDialog", "Collection name:", None))
        self.lineEditCollectionName.setText(_translate("GroupEpochDialog", "Epochs", None))
        self.labelTmin.setText(_translate("GroupEpochDialog", "Start time:", None))
        self.doubleSpinBoxTmin.setSuffix(_translate("GroupEpochDialog", " s", None))
        self.labelTmax.setText(_translate("GroupEpochDialog", "End time:", None))
        self.doubleSpinBoxTmax.setSuffix(_translate("GroupEpochDialog", " s", None))
        self.checkBoxStim.setToolTip(_translate("GroupEpochDialog", "Include or exclude stim channels", None))
        self.checkBoxStim.setText(_translate("GroupEpochDialog", "Include stim channel in collection", None))
        self.labelEventID.setText(_translate("GroupEpochDialog", "Event ID:", None))
        self.labelMask.setText(_translate("GroupEpochDialog", "Mask", None))
        self.spinBoxMask.setToolTip(_translate("GroupEpochDialog", "<html><head/><body><p>Mask bit used for finding events. For example, if mask is set to 1, first bit is ignored.</p></body></html>", None))
        self.labelName.setText(_translate("GroupEpochDialog", "Event name:      ", None))
        self.lineEditName.setText(_translate("GroupEpochDialog", "Event", None))
        self.groupBoxRejection.setTitle(_translate("GroupEpochDialog", "Rejection parameters", None))
        self.checkBoxGrad.setToolTip(_translate("GroupEpochDialog", "<html><head/><body><p>Include grad channels</p></body></html>", None))
        self.checkBoxGrad.setText(_translate("GroupEpochDialog", "Grad", None))
        self.doubleSpinBoxGradReject_3.setToolTip(_translate("GroupEpochDialog", "<html><head/><body><p>Peak-to-peak rejection threshold for gradiometer channels.</p></body></html>", None))
        self.doubleSpinBoxGradReject_3.setSuffix(_translate("GroupEpochDialog", " fT/cm", None))
        self.checkBoxMag.setToolTip(_translate("GroupEpochDialog", "<html><head/><body><p>Include mag channels</p></body></html>", None))
        self.checkBoxMag.setText(_translate("GroupEpochDialog", "Mag", None))
        self.doubleSpinBoxMagReject_3.setToolTip(_translate("GroupEpochDialog", "<html><head/><body><p>Peak-to-peak rejection threshold for magnetometer channels.</p></body></html>", None))
        self.doubleSpinBoxMagReject_3.setSuffix(_translate("GroupEpochDialog", " fT", None))
        self.checkBoxEeg.setToolTip(_translate("GroupEpochDialog", "<html><head/><body><p>Include eeg channels</p></body></html>", None))
        self.checkBoxEeg.setText(_translate("GroupEpochDialog", "EEG", None))
        self.doubleSpinBoxEEGReject_3.setToolTip(_translate("GroupEpochDialog", "<html><head/><body><p>Peak-to-peak rejection threshold for EEG channels.</p></body></html>", None))
        self.doubleSpinBoxEEGReject_3.setSuffix(_translate("GroupEpochDialog", " uV", None))
        self.checkBoxEog.setToolTip(_translate("GroupEpochDialog", "<html><head/><body><p>Include eog channels</p></body></html>", None))
        self.checkBoxEog.setText(_translate("GroupEpochDialog", "EOG", None))
        self.doubleSpinBoxEOGReject_3.setToolTip(_translate("GroupEpochDialog", "<html><head/><body><p>Peak-to-peak rejection threshold for EOG channels.</p></body></html>", None))
        self.doubleSpinBoxEOGReject_3.setSuffix(_translate("GroupEpochDialog", " uV", None))
        self.listWidgetSubjects.setToolTip(_translate("GroupEpochDialog", "<html><head/><body><p>Select the subjects for epoch creation.</p></body></html>", None))

