# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../mainWindowTabSourceAnalysisUi.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindowTabSourceAnalysis(object):
    def setupUi(self, mainWindowTabSourceAnalysis):
        mainWindowTabSourceAnalysis.setObjectName("mainWindowTabSourceAnalysis")
        mainWindowTabSourceAnalysis.resize(918, 648)
        self.tabWidgetSourceAnalysis = QtWidgets.QTabWidget(mainWindowTabSourceAnalysis)
        self.tabWidgetSourceAnalysis.setEnabled(True)
        self.tabWidgetSourceAnalysis.setGeometry(QtCore.QRect(0, 10, 1001, 601))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidgetSourceAnalysis.sizePolicy().hasHeightForWidth())
        self.tabWidgetSourceAnalysis.setSizePolicy(sizePolicy)
        self.tabWidgetSourceAnalysis.setMinimumSize(QtCore.QSize(200, 400))
        self.tabWidgetSourceAnalysis.setMaximumSize(QtCore.QSize(20000, 16777215))
        self.tabWidgetSourceAnalysis.setObjectName("tabWidgetSourceAnalysis")
        self.tabSourcePreparation = QtWidgets.QWidget()
        self.tabSourcePreparation.setObjectName("tabSourcePreparation")
        self.formLayout_6 = QtWidgets.QFormLayout(self.tabSourcePreparation)
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBoxReconstruction = QtWidgets.QGroupBox(self.tabSourcePreparation)
        self.groupBoxReconstruction.setFlat(False)
        self.groupBoxReconstruction.setCheckable(False)
        self.groupBoxReconstruction.setObjectName("groupBoxReconstruction")
        self.formLayout_5 = QtWidgets.QFormLayout(self.groupBoxReconstruction)
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frameCopyRecon = QtWidgets.QFrame(self.groupBoxReconstruction)
        self.frameCopyRecon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCopyRecon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCopyRecon.setObjectName("frameCopyRecon")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.frameCopyRecon)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelCopyMRI = QtWidgets.QLabel(self.frameCopyRecon)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelCopyMRI.setFont(font)
        self.labelCopyMRI.setToolTip("")
        self.labelCopyMRI.setObjectName("labelCopyMRI")
        self.horizontalLayout_6.addWidget(self.labelCopyMRI)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEditRecon = QtWidgets.QLineEdit(self.frameCopyRecon)
        self.lineEditRecon.setEnabled(False)
        self.lineEditRecon.setObjectName("lineEditRecon")
        self.horizontalLayout_5.addWidget(self.lineEditRecon)
        self.pushButtonBrowseRecon = QtWidgets.QPushButton(self.frameCopyRecon)
        self.pushButtonBrowseRecon.setObjectName("pushButtonBrowseRecon")
        self.horizontalLayout_5.addWidget(self.pushButtonBrowseRecon)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.gridLayout_29.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.frameCopyRecon)
        self.frameExamine = QtWidgets.QFrame(self.groupBoxReconstruction)
        self.frameExamine.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameExamine.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameExamine.setObjectName("frameExamine")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.frameExamine)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelExamine = QtWidgets.QLabel(self.frameExamine)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelExamine.setFont(font)
        self.labelExamine.setIndent(-1)
        self.labelExamine.setObjectName("labelExamine")
        self.horizontalLayout_7.addWidget(self.labelExamine)
        self.verticalLayout_13.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.pushButtonCheckTalairach = QtWidgets.QPushButton(self.frameExamine)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCheckTalairach.sizePolicy().hasHeightForWidth())
        self.pushButtonCheckTalairach.setSizePolicy(sizePolicy)
        self.pushButtonCheckTalairach.setObjectName("pushButtonCheckTalairach")
        self.horizontalLayout_57.addWidget(self.pushButtonCheckTalairach)
        self.pushButtonSkullStrip = QtWidgets.QPushButton(self.frameExamine)
        self.pushButtonSkullStrip.setObjectName("pushButtonSkullStrip")
        self.horizontalLayout_57.addWidget(self.pushButtonSkullStrip)
        self.pushButtonCheckSurfaces = QtWidgets.QPushButton(self.frameExamine)
        self.pushButtonCheckSurfaces.setObjectName("pushButtonCheckSurfaces")
        self.horizontalLayout_57.addWidget(self.pushButtonCheckSurfaces)
        self.pushButtonCheckSegmentations = QtWidgets.QPushButton(self.frameExamine)
        self.pushButtonCheckSegmentations.setObjectName("pushButtonCheckSegmentations")
        self.horizontalLayout_57.addWidget(self.pushButtonCheckSegmentations)
        self.verticalLayout_13.addLayout(self.horizontalLayout_57)
        self.gridLayout_30.addLayout(self.verticalLayout_13, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.frameExamine)
        self.frameCopyUnderSubject = QtWidgets.QFrame(self.groupBoxReconstruction)
        self.frameCopyUnderSubject.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCopyUnderSubject.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCopyUnderSubject.setObjectName("frameCopyUnderSubject")
        self.layoutCopyUnderSubject = QtWidgets.QGridLayout(self.frameCopyUnderSubject)
        self.layoutCopyUnderSubject.setObjectName("layoutCopyUnderSubject")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelCopied = QtWidgets.QLabel(self.frameCopyUnderSubject)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelCopied.setFont(font)
        self.labelCopied.setObjectName("labelCopied")
        self.horizontalLayout.addWidget(self.labelCopied)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonCopyUnderSubject = QtWidgets.QPushButton(self.frameCopyUnderSubject)
        self.pushButtonCopyUnderSubject.setEnabled(True)
        self.pushButtonCopyUnderSubject.setObjectName("pushButtonCopyUnderSubject")
        self.horizontalLayout_2.addWidget(self.pushButtonCopyUnderSubject)
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.checkBoxCopyUnderSubject = QtWidgets.QCheckBox(self.frameCopyUnderSubject)
        self.checkBoxCopyUnderSubject.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxCopyUnderSubject.sizePolicy().hasHeightForWidth())
        self.checkBoxCopyUnderSubject.setSizePolicy(sizePolicy)
        self.checkBoxCopyUnderSubject.setText("")
        self.checkBoxCopyUnderSubject.setCheckable(True)
        self.checkBoxCopyUnderSubject.setObjectName("checkBoxCopyUnderSubject")
        self.horizontalLayout_2.addWidget(self.checkBoxCopyUnderSubject)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layoutCopyUnderSubject.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.frameCopyUnderSubject)
        self.frameBem = QtWidgets.QFrame(self.groupBoxReconstruction)
        self.frameBem.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBem.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBem.setObjectName("frameBem")
        self.layoutCopyUnderSubject_2 = QtWidgets.QGridLayout(self.frameBem)
        self.layoutCopyUnderSubject_2.setObjectName("layoutCopyUnderSubject_2")
        self.verticalLayoutBem = QtWidgets.QVBoxLayout()
        self.verticalLayoutBem.setContentsMargins(0, 0, -1, -1)
        self.verticalLayoutBem.setObjectName("verticalLayoutBem")
        self.horizontalLayoutBem_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayoutBem_1.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayoutBem_1.setObjectName("horizontalLayoutBem_1")
        self.labelBem = QtWidgets.QLabel(self.frameBem)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelBem.setFont(font)
        self.labelBem.setObjectName("labelBem")
        self.horizontalLayoutBem_1.addWidget(self.labelBem)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutBem_1.addItem(spacerItem2)
        self.labelAtlas = QtWidgets.QLabel(self.frameBem)
        self.labelAtlas.setObjectName("labelAtlas")
        self.horizontalLayoutBem_1.addWidget(self.labelAtlas)
        self.checkBoxAtlas = QtWidgets.QCheckBox(self.frameBem)
        self.checkBoxAtlas.setEnabled(True)
        self.checkBoxAtlas.setText("")
        self.checkBoxAtlas.setChecked(True)
        self.checkBoxAtlas.setObjectName("checkBoxAtlas")
        self.horizontalLayoutBem_1.addWidget(self.checkBoxAtlas)
        self.verticalLayoutBem.addLayout(self.horizontalLayoutBem_1)
        self.horizontalLayoutBem_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayoutBem_2.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayoutBem_2.setObjectName("horizontalLayoutBem_2")
        self.pushButtonBem = QtWidgets.QPushButton(self.frameBem)
        self.pushButtonBem.setEnabled(True)
        self.pushButtonBem.setObjectName("pushButtonBem")
        self.horizontalLayoutBem_2.addWidget(self.pushButtonBem)
        spacerItem3 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutBem_2.addItem(spacerItem3)
        self.checkBoxBem = QtWidgets.QCheckBox(self.frameBem)
        self.checkBoxBem.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxBem.sizePolicy().hasHeightForWidth())
        self.checkBoxBem.setSizePolicy(sizePolicy)
        self.checkBoxBem.setText("")
        self.checkBoxBem.setCheckable(True)
        self.checkBoxBem.setObjectName("checkBoxBem")
        self.horizontalLayoutBem_2.addWidget(self.checkBoxBem)
        self.verticalLayoutBem.addLayout(self.horizontalLayoutBem_2)
        self.layoutCopyUnderSubject_2.addLayout(self.verticalLayoutBem, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.frameBem)
        self.formLayout_5.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_10)
        self.verticalLayout_8.addWidget(self.groupBoxReconstruction)
        self.formLayout_6.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_8)
        self.label_7 = QtWidgets.QLabel(self.tabSourcePreparation)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_7)
        self.tabWidgetSourceAnalysis.addTab(self.tabSourcePreparation, "")
        self.tabCoregistration = QtWidgets.QWidget()
        self.tabCoregistration.setObjectName("tabCoregistration")
        self.formLayout_10 = QtWidgets.QFormLayout(self.tabCoregistration)
        self.formLayout_10.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_10.setContentsMargins(0, 0, 0, 0)
        self.formLayout_10.setObjectName("formLayout_10")
        self.groupBoxCoregistration = QtWidgets.QGroupBox(self.tabCoregistration)
        self.groupBoxCoregistration.setFlat(False)
        self.groupBoxCoregistration.setCheckable(False)
        self.groupBoxCoregistration.setObjectName("groupBoxCoregistration")
        self.formLayout_7 = QtWidgets.QFormLayout(self.groupBoxCoregistration)
        self.formLayout_7.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setObjectName("formLayout_7")
        self.verticalLayoutCoregistration = QtWidgets.QVBoxLayout()
        self.verticalLayoutCoregistration.setObjectName("verticalLayoutCoregistration")
        self.frameCoregistrationGUI = QtWidgets.QFrame(self.groupBoxCoregistration)
        self.frameCoregistrationGUI.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCoregistrationGUI.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCoregistrationGUI.setObjectName("frameCoregistrationGUI")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.frameCoregistrationGUI)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelCoregistrationGUI = QtWidgets.QLabel(self.frameCoregistrationGUI)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelCoregistrationGUI.setFont(font)
        self.labelCoregistrationGUI.setToolTip("")
        self.labelCoregistrationGUI.setObjectName("labelCoregistrationGUI")
        self.horizontalLayout_8.addWidget(self.labelCoregistrationGUI)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButtonCoregistrationGUI = QtWidgets.QPushButton(self.frameCoregistrationGUI)
        self.pushButtonCoregistrationGUI.setObjectName("pushButtonCoregistrationGUI")
        self.horizontalLayout_9.addWidget(self.pushButtonCoregistrationGUI)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.gridLayout_32.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayoutCoregistration.addWidget(self.frameCoregistrationGUI)
        self.frameCoregistrationBrowse = QtWidgets.QFrame(self.groupBoxCoregistration)
        self.frameCoregistrationBrowse.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCoregistrationBrowse.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCoregistrationBrowse.setObjectName("frameCoregistrationBrowse")
        self.gridLayout_42 = QtWidgets.QGridLayout(self.frameCoregistrationBrowse)
        self.gridLayout_42.setObjectName("gridLayout_42")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.labelCoregistrationBrowse = QtWidgets.QLabel(self.frameCoregistrationBrowse)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelCoregistrationBrowse.setFont(font)
        self.labelCoregistrationBrowse.setIndent(-1)
        self.labelCoregistrationBrowse.setObjectName("labelCoregistrationBrowse")
        self.horizontalLayout_10.addWidget(self.labelCoregistrationBrowse)
        self.verticalLayout_14.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        self.lineEditCoregistrationBrowse = QtWidgets.QLineEdit(self.frameCoregistrationBrowse)
        self.lineEditCoregistrationBrowse.setEnabled(False)
        self.lineEditCoregistrationBrowse.setObjectName("lineEditCoregistrationBrowse")
        self.horizontalLayout_63.addWidget(self.lineEditCoregistrationBrowse)
        self.pushButtonCoregistrationBrowse = QtWidgets.QPushButton(self.frameCoregistrationBrowse)
        self.pushButtonCoregistrationBrowse.setObjectName("pushButtonCoregistrationBrowse")
        self.horizontalLayout_63.addWidget(self.pushButtonCoregistrationBrowse)
        self.verticalLayout_14.addLayout(self.horizontalLayout_63)
        self.gridLayout_42.addLayout(self.verticalLayout_14, 0, 0, 1, 1)
        self.verticalLayoutCoregistration.addWidget(self.frameCoregistrationBrowse)
        self.frameCoregistrationCurrent = QtWidgets.QFrame(self.groupBoxCoregistration)
        self.frameCoregistrationCurrent.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCoregistrationCurrent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCoregistrationCurrent.setObjectName("frameCoregistrationCurrent")
        self.gridLayout_44 = QtWidgets.QGridLayout(self.frameCoregistrationCurrent)
        self.gridLayout_44.setObjectName("gridLayout_44")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.labelCoregistrationStatus = QtWidgets.QLabel(self.frameCoregistrationCurrent)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelCoregistrationStatus.setFont(font)
        self.labelCoregistrationStatus.setIndent(-1)
        self.labelCoregistrationStatus.setObjectName("labelCoregistrationStatus")
        self.horizontalLayout_16.addWidget(self.labelCoregistrationStatus)
        self.verticalLayout_16.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        self.labelCoregistrationSelected = QtWidgets.QLabel(self.frameCoregistrationCurrent)
        self.labelCoregistrationSelected.setObjectName("labelCoregistrationSelected")
        self.horizontalLayout_65.addWidget(self.labelCoregistrationSelected)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_65.addItem(spacerItem5)
        self.checkBoxCoregistrationSelected = QtWidgets.QCheckBox(self.frameCoregistrationCurrent)
        self.checkBoxCoregistrationSelected.setEnabled(False)
        self.checkBoxCoregistrationSelected.setText("")
        self.checkBoxCoregistrationSelected.setObjectName("checkBoxCoregistrationSelected")
        self.horizontalLayout_65.addWidget(self.checkBoxCoregistrationSelected)
        self.verticalLayout_16.addLayout(self.horizontalLayout_65)
        self.gridLayout_44.addLayout(self.verticalLayout_16, 0, 0, 1, 1)
        self.verticalLayoutCoregistration.addWidget(self.frameCoregistrationCurrent)
        self.formLayout_7.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayoutCoregistration)
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.groupBoxCoregistration)
        self.tabWidgetSourceAnalysis.addTab(self.tabCoregistration, "")
        self.tabForwardSolution = QtWidgets.QWidget()
        self.tabForwardSolution.setObjectName("tabForwardSolution")
        self.formLayout_11 = QtWidgets.QFormLayout(self.tabForwardSolution)
        self.formLayout_11.setContentsMargins(0, 0, 0, 0)
        self.formLayout_11.setObjectName("formLayout_11")
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabForwardSolution)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.pushButtonCreateForwardSolution = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButtonCreateForwardSolution.setObjectName("pushButtonCreateForwardSolution")
        self.gridLayout_35.addWidget(self.pushButtonCreateForwardSolution, 2, 0, 1, 1)
        self.pushButtonRemoveForwardSolution = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButtonRemoveForwardSolution.setObjectName("pushButtonRemoveForwardSolution")
        self.gridLayout_35.addWidget(self.pushButtonRemoveForwardSolution, 4, 0, 1, 1)
        self.pushButtonImportForwardSolution = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButtonImportForwardSolution.setObjectName("pushButtonImportForwardSolution")
        self.gridLayout_35.addWidget(self.pushButtonImportForwardSolution, 3, 0, 1, 1)
        self.listWidgetForwardSolutionsFwd = QtWidgets.QListWidget(self.groupBox_4)
        self.listWidgetForwardSolutionsFwd.setObjectName("listWidgetForwardSolutionsFwd")
        self.gridLayout_35.addWidget(self.listWidgetForwardSolutionsFwd, 1, 0, 1, 1)
        self.horizontalLayout_60.addWidget(self.groupBox_4)
        self.formLayout_11.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_60)
        self.tabWidgetSourceAnalysis.addTab(self.tabForwardSolution, "")
        self.tabNoiseCovariance = QtWidgets.QWidget()
        self.tabNoiseCovariance.setObjectName("tabNoiseCovariance")
        self.formLayout_16 = QtWidgets.QFormLayout(self.tabNoiseCovariance)
        self.formLayout_16.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_16.setContentsMargins(0, 0, 0, 0)
        self.formLayout_16.setObjectName("formLayout_16")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.groupBoxCovarianceComputing = QtWidgets.QGroupBox(self.tabNoiseCovariance)
        self.groupBoxCovarianceComputing.setFlat(False)
        self.groupBoxCovarianceComputing.setCheckable(False)
        self.groupBoxCovarianceComputing.setObjectName("groupBoxCovarianceComputing")
        self.formLayout_8 = QtWidgets.QFormLayout(self.groupBoxCovarianceComputing)
        self.formLayout_8.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_8.setObjectName("formLayout_8")
        self.verticalLayoutCovariance = QtWidgets.QVBoxLayout()
        self.verticalLayoutCovariance.setObjectName("verticalLayoutCovariance")
        self.frameCovarianceRaw = QtWidgets.QFrame(self.groupBoxCovarianceComputing)
        self.frameCovarianceRaw.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCovarianceRaw.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCovarianceRaw.setObjectName("frameCovarianceRaw")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.frameCovarianceRaw)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.labelCovarianceRaw = QtWidgets.QLabel(self.frameCovarianceRaw)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelCovarianceRaw.setFont(font)
        self.labelCovarianceRaw.setToolTip("")
        self.labelCovarianceRaw.setObjectName("labelCovarianceRaw")
        self.horizontalLayout_11.addWidget(self.labelCovarianceRaw)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButtonCovarianceRaw = QtWidgets.QPushButton(self.frameCovarianceRaw)
        self.pushButtonCovarianceRaw.setObjectName("pushButtonCovarianceRaw")
        self.horizontalLayout_12.addWidget(self.pushButtonCovarianceRaw)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.gridLayout_33.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayoutCovariance.addWidget(self.frameCovarianceRaw)
        self.frameCovarianceEpochs = QtWidgets.QFrame(self.groupBoxCovarianceComputing)
        self.frameCovarianceEpochs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCovarianceEpochs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCovarianceEpochs.setObjectName("frameCovarianceEpochs")
        self.gridLayout_43 = QtWidgets.QGridLayout(self.frameCovarianceEpochs)
        self.gridLayout_43.setObjectName("gridLayout_43")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.labelCovarianceEpochs = QtWidgets.QLabel(self.frameCovarianceEpochs)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelCovarianceEpochs.setFont(font)
        self.labelCovarianceEpochs.setIndent(-1)
        self.labelCovarianceEpochs.setObjectName("labelCovarianceEpochs")
        self.horizontalLayout_13.addWidget(self.labelCovarianceEpochs)
        self.verticalLayout_15.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_64.setObjectName("horizontalLayout_64")
        self.pushButtonCovarianceEpochs = QtWidgets.QPushButton(self.frameCovarianceEpochs)
        self.pushButtonCovarianceEpochs.setObjectName("pushButtonCovarianceEpochs")
        self.horizontalLayout_64.addWidget(self.pushButtonCovarianceEpochs)
        self.verticalLayout_15.addLayout(self.horizontalLayout_64)
        self.gridLayout_43.addLayout(self.verticalLayout_15, 0, 0, 1, 1)
        self.verticalLayoutCovariance.addWidget(self.frameCovarianceEpochs)
        self.formLayout_8.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayoutCovariance)
        self.horizontalLayout_18.addWidget(self.groupBoxCovarianceComputing)
        self.groupBoxCovarianceList = QtWidgets.QGroupBox(self.tabNoiseCovariance)
        self.groupBoxCovarianceList.setObjectName("groupBoxCovarianceList")
        self.formLayout = QtWidgets.QFormLayout(self.groupBoxCovarianceList)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.listWidgetCovariances = QtWidgets.QListWidget(self.groupBoxCovarianceList)
        self.listWidgetCovariances.setObjectName("listWidgetCovariances")
        self.verticalLayout_9.addWidget(self.listWidgetCovariances)
        self.pushButtonCovarianceRemove = QtWidgets.QPushButton(self.groupBoxCovarianceList)
        self.pushButtonCovarianceRemove.setObjectName("pushButtonCovarianceRemove")
        self.verticalLayout_9.addWidget(self.pushButtonCovarianceRemove)
        self.pushButtonCovariancePlot = QtWidgets.QPushButton(self.groupBoxCovarianceList)
        self.pushButtonCovariancePlot.setObjectName("pushButtonCovariancePlot")
        self.verticalLayout_9.addWidget(self.pushButtonCovariancePlot)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_9)
        self.horizontalLayout_18.addWidget(self.groupBoxCovarianceList)
        self.formLayout_16.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_18)
        self.tabWidgetSourceAnalysis.addTab(self.tabNoiseCovariance, "")
        self.tabSourceEstimate = QtWidgets.QWidget()
        self.tabSourceEstimate.setObjectName("tabSourceEstimate")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tabSourceEstimate)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 745, 408))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBoxForwardSolutions = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBoxForwardSolutions.setObjectName("groupBoxForwardSolutions")
        self.gridLayout_47 = QtWidgets.QGridLayout(self.groupBoxForwardSolutions)
        self.gridLayout_47.setObjectName("gridLayout_47")
        self.listWidgetForwardSolutionsStc = QtWidgets.QListWidget(self.groupBoxForwardSolutions)
        self.listWidgetForwardSolutionsStc.setObjectName("listWidgetForwardSolutionsStc")
        self.gridLayout_47.addWidget(self.listWidgetForwardSolutionsStc, 0, 1, 1, 1)
        self.verticalLayout_11.addWidget(self.groupBoxForwardSolutions)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_11 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_11.setObjectName("groupBox_11")
        self.formLayout_17 = QtWidgets.QFormLayout(self.groupBox_11)
        self.formLayout_17.setObjectName("formLayout_17")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.radioButtonStcRaw = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButtonStcRaw.setChecked(True)
        self.radioButtonStcRaw.setObjectName("radioButtonStcRaw")
        self.verticalLayout_38.addWidget(self.radioButtonStcRaw)
        self.gridLayout_45 = QtWidgets.QGridLayout()
        self.gridLayout_45.setObjectName("gridLayout_45")
        self.radioButtonStcEpochs = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButtonStcEpochs.setObjectName("radioButtonStcEpochs")
        self.gridLayout_45.addWidget(self.radioButtonStcEpochs, 1, 0, 1, 1)
        self.groupBoxStcEpochs = QtWidgets.QGroupBox(self.groupBox_11)
        self.groupBoxStcEpochs.setEnabled(False)
        self.groupBoxStcEpochs.setObjectName("groupBoxStcEpochs")
        self.gridLayout_46 = QtWidgets.QGridLayout(self.groupBoxStcEpochs)
        self.gridLayout_46.setObjectName("gridLayout_46")
        self.listWidgetStcEpochs = QtWidgets.QListWidget(self.groupBoxStcEpochs)
        self.listWidgetStcEpochs.setEnabled(False)
        self.listWidgetStcEpochs.setObjectName("listWidgetStcEpochs")
        self.gridLayout_46.addWidget(self.listWidgetStcEpochs, 0, 0, 1, 1)
        self.gridLayout_45.addWidget(self.groupBoxStcEpochs, 2, 0, 1, 1)
        self.verticalLayout_38.addLayout(self.gridLayout_45)
        self.gridLayout_38 = QtWidgets.QGridLayout()
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.radioButtonStcEvoked = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButtonStcEvoked.setObjectName("radioButtonStcEvoked")
        self.gridLayout_38.addWidget(self.radioButtonStcEvoked, 0, 0, 1, 1)
        self.groupBoxStcEvoked = QtWidgets.QGroupBox(self.groupBox_11)
        self.groupBoxStcEvoked.setEnabled(False)
        self.groupBoxStcEvoked.setObjectName("groupBoxStcEvoked")
        self.gridLayout_39 = QtWidgets.QGridLayout(self.groupBoxStcEvoked)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.listWidgetStcEvoked = QtWidgets.QListWidget(self.groupBoxStcEvoked)
        self.listWidgetStcEvoked.setEnabled(False)
        self.listWidgetStcEvoked.setObjectName("listWidgetStcEvoked")
        self.gridLayout_39.addWidget(self.listWidgetStcEvoked, 0, 0, 1, 1)
        self.gridLayout_38.addWidget(self.groupBoxStcEvoked, 1, 0, 1, 1)
        self.verticalLayout_38.addLayout(self.gridLayout_38)
        self.formLayout_17.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout_38)
        self.verticalLayout_2.addWidget(self.groupBox_11)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_42 = QtWidgets.QVBoxLayout()
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.groupBoxActions = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBoxActions.setObjectName("groupBoxActions")
        self.gridLayout_48 = QtWidgets.QGridLayout(self.groupBoxActions)
        self.gridLayout_48.setObjectName("gridLayout_48")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonLinear = QtWidgets.QPushButton(self.groupBoxActions)
        self.pushButtonLinear.setObjectName("pushButtonLinear")
        self.gridLayout.addWidget(self.pushButtonLinear, 0, 0, 1, 1)
        self.pushButtonLCMV = QtWidgets.QPushButton(self.groupBoxActions)
        self.pushButtonLCMV.setObjectName("pushButtonLCMV")
        self.gridLayout.addWidget(self.pushButtonLCMV, 1, 0, 1, 1)
        self.gridLayout_48.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.verticalLayout_42.addWidget(self.groupBoxActions)
        self.horizontalLayout_4.addLayout(self.verticalLayout_42)
        self.verticalLayout_40 = QtWidgets.QVBoxLayout()
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.groupBox_23 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_23.setObjectName("groupBox_23")
        self.gridLayout_40 = QtWidgets.QGridLayout(self.groupBox_23)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.listWidgetSourceEstimatesStc = QtWidgets.QListWidget(self.groupBox_23)
        self.listWidgetSourceEstimatesStc.setObjectName("listWidgetSourceEstimatesStc")
        self.gridLayout_40.addWidget(self.listWidgetSourceEstimatesStc, 0, 1, 1, 1)
        self.pushButtonStcRemove = QtWidgets.QPushButton(self.groupBox_23)
        self.pushButtonStcRemove.setObjectName("pushButtonStcRemove")
        self.gridLayout_40.addWidget(self.pushButtonStcRemove, 1, 1, 1, 1)
        self.verticalLayout_40.addWidget(self.groupBox_23)
        self.horizontalLayout_4.addLayout(self.verticalLayout_40)
        self.tabWidgetSourceAnalysis.addTab(self.tabSourceEstimate, "")
        self.tabAnalysis = QtWidgets.QWidget()
        self.tabAnalysis.setObjectName("tabAnalysis")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tabAnalysis)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 385, 230))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout()
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.groupBoxSourceEstimatesAna = QtWidgets.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBoxSourceEstimatesAna.setObjectName("groupBoxSourceEstimatesAna")
        self.gridLayout_41 = QtWidgets.QGridLayout(self.groupBoxSourceEstimatesAna)
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.listWidgetSourceEstimatesAna = QtWidgets.QListWidget(self.groupBoxSourceEstimatesAna)
        self.listWidgetSourceEstimatesAna.setObjectName("listWidgetSourceEstimatesAna")
        self.gridLayout_41.addWidget(self.listWidgetSourceEstimatesAna, 0, 1, 1, 1)
        self.verticalLayout_41.addWidget(self.groupBoxSourceEstimatesAna)
        self.horizontalLayout_17.addLayout(self.verticalLayout_41)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBoxActionsAna = QtWidgets.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBoxActionsAna.setObjectName("groupBoxActionsAna")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxActionsAna)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButtonPlotSourceEstimate = QtWidgets.QPushButton(self.groupBoxActionsAna)
        self.pushButtonPlotSourceEstimate.setObjectName("pushButtonPlotSourceEstimate")
        self.gridLayout_3.addWidget(self.pushButtonPlotSourceEstimate, 0, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBoxActionsAna)
        self.horizontalLayout_17.addLayout(self.verticalLayout_7)
        self.tabWidgetSourceAnalysis.addTab(self.tabAnalysis, "")

        self.retranslateUi(mainWindowTabSourceAnalysis)
        self.tabWidgetSourceAnalysis.setCurrentIndex(0)
        self.radioButtonStcRaw.toggled['bool'].connect(self.groupBoxStcEpochs.setDisabled)
        self.radioButtonStcEvoked.toggled['bool'].connect(self.groupBoxStcEpochs.setDisabled)
        self.radioButtonStcRaw.toggled['bool'].connect(self.groupBoxStcEvoked.setDisabled)
        self.radioButtonStcEpochs.toggled['bool'].connect(self.groupBoxStcEvoked.setDisabled)
        self.radioButtonStcEpochs.toggled['bool'].connect(self.listWidgetStcEpochs.setEnabled)
        self.radioButtonStcEvoked.toggled['bool'].connect(self.listWidgetStcEvoked.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(mainWindowTabSourceAnalysis)

    def retranslateUi(self, mainWindowTabSourceAnalysis):
        _translate = QtCore.QCoreApplication.translate
        mainWindowTabSourceAnalysis.setWindowTitle(_translate("mainWindowTabSourceAnalysis", "Form"))
        self.groupBoxReconstruction.setTitle(_translate("mainWindowTabSourceAnalysis", "MRI image reconstruction"))
        self.labelCopyMRI.setText(_translate("mainWindowTabSourceAnalysis", "Select directory to copy the reconstructed MRI image files from:"))
        self.pushButtonBrowseRecon.setText(_translate("mainWindowTabSourceAnalysis", "Browse..."))
        self.labelExamine.setText(_translate("mainWindowTabSourceAnalysis", "Examine the reconstructed MRI image files:"))
        self.pushButtonCheckTalairach.setText(_translate("mainWindowTabSourceAnalysis", "Check Talairach transform"))
        self.pushButtonSkullStrip.setText(_translate("mainWindowTabSourceAnalysis", "Check skull strip"))
        self.pushButtonCheckSurfaces.setText(_translate("mainWindowTabSourceAnalysis", "Check surfaces"))
        self.pushButtonCheckSegmentations.setText(_translate("mainWindowTabSourceAnalysis", "Check segmentation"))
        self.labelCopied.setText(_translate("mainWindowTabSourceAnalysis", "Copy and prepare MRI images under subject folder"))
        self.pushButtonCopyUnderSubject.setText(_translate("mainWindowTabSourceAnalysis", "Copy MRI images"))
        self.labelBem.setText(_translate("mainWindowTabSourceAnalysis", "Create Bem surfaces"))
        self.labelAtlas.setText(_translate("mainWindowTabSourceAnalysis", "Use atlas"))
        self.pushButtonBem.setText(_translate("mainWindowTabSourceAnalysis", "Create Bem surfaces"))
        self.tabWidgetSourceAnalysis.setTabText(self.tabWidgetSourceAnalysis.indexOf(self.tabSourcePreparation), _translate("mainWindowTabSourceAnalysis", "MRI reconstruction"))
        self.groupBoxCoregistration.setTitle(_translate("mainWindowTabSourceAnalysis", "Coregistration of MEG and MRI"))
        self.labelCoregistrationGUI.setText(_translate("mainWindowTabSourceAnalysis", "Use MNE-python Coregistration GUI to create a coordinate transformation file:"))
        self.pushButtonCoregistrationGUI.setText(_translate("mainWindowTabSourceAnalysis", "Open MNE-Python Coregistration..."))
        self.labelCoregistrationBrowse.setText(_translate("mainWindowTabSourceAnalysis", "Locate the created or pre-existing coordinate transformation file:"))
        self.pushButtonCoregistrationBrowse.setText(_translate("mainWindowTabSourceAnalysis", "Browse..."))
        self.labelCoregistrationStatus.setText(_translate("mainWindowTabSourceAnalysis", "Coordinate transformation file selected:"))
        self.labelCoregistrationSelected.setText(_translate("mainWindowTabSourceAnalysis", "Coordinate transformation file selected:"))
        self.tabWidgetSourceAnalysis.setTabText(self.tabWidgetSourceAnalysis.indexOf(self.tabCoregistration), _translate("mainWindowTabSourceAnalysis", "Coregistration"))
        self.groupBox_4.setTitle(_translate("mainWindowTabSourceAnalysis", "Existing forward solutions"))
        self.pushButtonCreateForwardSolution.setText(_translate("mainWindowTabSourceAnalysis", "Create a forward solution..."))
        self.pushButtonRemoveForwardSolution.setText(_translate("mainWindowTabSourceAnalysis", "Remove a forward solution"))
        self.pushButtonImportForwardSolution.setText(_translate("mainWindowTabSourceAnalysis", "Import forward solution..."))
        self.tabWidgetSourceAnalysis.setTabText(self.tabWidgetSourceAnalysis.indexOf(self.tabForwardSolution), _translate("mainWindowTabSourceAnalysis", "Forward solution"))
        self.groupBoxCovarianceComputing.setTitle(_translate("mainWindowTabSourceAnalysis", "Computing covariance matrix"))
        self.labelCovarianceRaw.setText(_translate("mainWindowTabSourceAnalysis", "Compute covariance from Raw:"))
        self.pushButtonCovarianceRaw.setText(_translate("mainWindowTabSourceAnalysis", "Compute covariance from Raw..."))
        self.labelCovarianceEpochs.setText(_translate("mainWindowTabSourceAnalysis", "Compute covariance from Epochs:"))
        self.pushButtonCovarianceEpochs.setText(_translate("mainWindowTabSourceAnalysis", "Compute covariance from Epochs..."))
        self.groupBoxCovarianceList.setTitle(_translate("mainWindowTabSourceAnalysis", "Computed covariances"))
        self.pushButtonCovarianceRemove.setText(_translate("mainWindowTabSourceAnalysis", "Remove covariance matrix"))
        self.pushButtonCovariancePlot.setText(_translate("mainWindowTabSourceAnalysis", "Plot the selected covariance matrix"))
        self.tabWidgetSourceAnalysis.setTabText(self.tabWidgetSourceAnalysis.indexOf(self.tabNoiseCovariance), _translate("mainWindowTabSourceAnalysis", "Covariance matrix"))
        self.groupBoxForwardSolutions.setTitle(_translate("mainWindowTabSourceAnalysis", "Forward solutions:"))
        self.groupBox_11.setTitle(_translate("mainWindowTabSourceAnalysis", "Base source estimate on:"))
        self.radioButtonStcRaw.setText(_translate("mainWindowTabSourceAnalysis", "Raw file"))
        self.radioButtonStcEpochs.setText(_translate("mainWindowTabSourceAnalysis", "Epochs data"))
        self.groupBoxStcEpochs.setTitle(_translate("mainWindowTabSourceAnalysis", "Evoked collections"))
        self.radioButtonStcEvoked.setText(_translate("mainWindowTabSourceAnalysis", "Evoked data"))
        self.groupBoxStcEvoked.setTitle(_translate("mainWindowTabSourceAnalysis", "Evoked collections"))
        self.groupBoxActions.setTitle(_translate("mainWindowTabSourceAnalysis", "Actions:"))
        self.pushButtonLinear.setText(_translate("mainWindowTabSourceAnalysis", "Create linear source estimate"))
        self.pushButtonLCMV.setText(_translate("mainWindowTabSourceAnalysis", "Create LCMV source estimate"))
        self.groupBox_23.setTitle(_translate("mainWindowTabSourceAnalysis", "Source estimates:"))
        self.pushButtonStcRemove.setText(_translate("mainWindowTabSourceAnalysis", "Remove source estimate"))
        self.tabWidgetSourceAnalysis.setTabText(self.tabWidgetSourceAnalysis.indexOf(self.tabSourceEstimate), _translate("mainWindowTabSourceAnalysis", "Source estimate"))
        self.groupBoxSourceEstimatesAna.setTitle(_translate("mainWindowTabSourceAnalysis", "Source estimates:"))
        self.groupBoxActionsAna.setTitle(_translate("mainWindowTabSourceAnalysis", "Actions:"))
        self.pushButtonPlotSourceEstimate.setText(_translate("mainWindowTabSourceAnalysis", "Plot source estimate"))
        self.tabWidgetSourceAnalysis.setTabText(self.tabWidgetSourceAnalysis.indexOf(self.tabAnalysis), _translate("mainWindowTabSourceAnalysis", "Analysis"))

