# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../mainWindowTabSpectrumsUi.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindowTabSpectrums(object):
    def setupUi(self, mainWindowTabSpectrums):
        mainWindowTabSpectrums.setObjectName("mainWindowTabSpectrums")
        mainWindowTabSpectrums.resize(1112, 726)
        self.layoutWidget = QtWidgets.QWidget(mainWindowTabSpectrums)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 941, 591))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.groupBoxComputations = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBoxComputations.setMinimumSize(QtCore.QSize(400, 0))
        self.groupBoxComputations.setObjectName("groupBoxComputations")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxComputations)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonComputeSpectrum = QtWidgets.QPushButton(self.groupBoxComputations)
        self.pushButtonComputeSpectrum.setObjectName("pushButtonComputeSpectrum")
        self.gridLayout_2.addWidget(self.pushButtonComputeSpectrum, 0, 0, 1, 1)
        self.verticalLayout_23.addWidget(self.groupBoxComputations)
        self.gridLayout_15.addLayout(self.verticalLayout_23, 0, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBoxSpectrums = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBoxSpectrums.setMinimumSize(QtCore.QSize(0, 300))
        self.groupBoxSpectrums.setObjectName("groupBoxSpectrums")
        self.formLayout = QtWidgets.QFormLayout(self.groupBoxSpectrums)
        self.formLayout.setObjectName("formLayout")
        self.labelSpectrumInfo = QtWidgets.QLabel(self.groupBoxSpectrums)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelSpectrumInfo.setFont(font)
        self.labelSpectrumInfo.setObjectName("labelSpectrumInfo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelSpectrumInfo)
        self.textBrowserSpectrumInfo = QtWidgets.QTextBrowser(self.groupBoxSpectrums)
        self.textBrowserSpectrumInfo.setObjectName("textBrowserSpectrumInfo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.textBrowserSpectrumInfo)
        self.listWidgetSpectrums = QtWidgets.QListWidget(self.groupBoxSpectrums)
        self.listWidgetSpectrums.setObjectName("listWidgetSpectrums")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.listWidgetSpectrums)
        self.verticalLayout_6.addWidget(self.groupBoxSpectrums)
        self.groupBoxSpectrumActions = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBoxSpectrumActions.setObjectName("groupBoxSpectrumActions")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxSpectrumActions)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBoxSpectrumActions)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonVisualizeSpectrum = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonVisualizeSpectrum.setObjectName("pushButtonVisualizeSpectrum")
        self.horizontalLayout_2.addWidget(self.pushButtonVisualizeSpectrum)
        self.gridLayout_21.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonDeleteSpectrum = QtWidgets.QPushButton(self.groupBoxSpectrumActions)
        self.pushButtonDeleteSpectrum.setObjectName("pushButtonDeleteSpectrum")
        self.gridLayout.addWidget(self.pushButtonDeleteSpectrum, 1, 0, 1, 1)
        self.pushButtonGroupDeleteSpectrum = QtWidgets.QPushButton(self.groupBoxSpectrumActions)
        self.pushButtonGroupDeleteSpectrum.setObjectName("pushButtonGroupDeleteSpectrum")
        self.gridLayout.addWidget(self.pushButtonGroupDeleteSpectrum, 2, 0, 1, 1)
        self.pushButtonGroupAverage = QtWidgets.QPushButton(self.groupBoxSpectrumActions)
        self.pushButtonGroupAverage.setObjectName("pushButtonGroupAverage")
        self.gridLayout.addWidget(self.pushButtonGroupAverage, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBoxSpectrumActions)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonSaveSpectrum = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButtonSaveSpectrum.setObjectName("pushButtonSaveSpectrum")
        self.horizontalLayout_3.addWidget(self.pushButtonSaveSpectrum)
        self.pushButtonGroupSaveSpectrum = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButtonGroupSaveSpectrum.setObjectName("pushButtonGroupSaveSpectrum")
        self.horizontalLayout_3.addWidget(self.pushButtonGroupSaveSpectrum)
        self.gridLayout_20.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBoxSpectrumActions)
        self.gridLayout_15.addLayout(self.verticalLayout_6, 0, 1, 1, 1)

        self.retranslateUi(mainWindowTabSpectrums)
        QtCore.QMetaObject.connectSlotsByName(mainWindowTabSpectrums)

    def retranslateUi(self, mainWindowTabSpectrums):
        _translate = QtCore.QCoreApplication.translate
        mainWindowTabSpectrums.setWindowTitle(_translate("mainWindowTabSpectrums", "Form"))
        self.groupBoxComputations.setTitle(_translate("mainWindowTabSpectrums", "Computations"))
        self.pushButtonComputeSpectrum.setText(_translate("mainWindowTabSpectrums", "Compute spectrum..."))
        self.groupBoxSpectrums.setTitle(_translate("mainWindowTabSpectrums", "Spectrums"))
        self.labelSpectrumInfo.setText(_translate("mainWindowTabSpectrums", "Spectrum info"))
        self.groupBoxSpectrumActions.setTitle(_translate("mainWindowTabSpectrums", "Available actions for spectrums"))
        self.groupBox_2.setTitle(_translate("mainWindowTabSpectrums", "Visualization:"))
        self.pushButtonVisualizeSpectrum.setText(_translate("mainWindowTabSpectrums", "Visualize selected spectrum"))
        self.pushButtonDeleteSpectrum.setText(_translate("mainWindowTabSpectrums", "Delete selected spectrum"))
        self.pushButtonGroupDeleteSpectrum.setText(_translate("mainWindowTabSpectrums", "Group delete selected spectrum"))
        self.pushButtonGroupAverage.setText(_translate("mainWindowTabSpectrums", "Group average for all subjects"))
        self.groupBox_5.setTitle(_translate("mainWindowTabSpectrums", "Saving:"))
        self.pushButtonSaveSpectrum.setText(_translate("mainWindowTabSpectrums", "Save spectrum data"))
        self.pushButtonGroupSaveSpectrum.setText(_translate("mainWindowTabSpectrums", "Group save spectrum data"))

