# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowTabPreprocessingUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindowTabPreprocessing(object):
    def setupUi(self, mainWindowTabPreprocessing):
        mainWindowTabPreprocessing.setObjectName("mainWindowTabPreprocessing")
        mainWindowTabPreprocessing.resize(877, 545)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(mainWindowTabPreprocessing)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 841, 511))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_19.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.groupBoxAvailablePreprocessing = QtWidgets.QGroupBox(self.gridLayoutWidget_3)
        self.groupBoxAvailablePreprocessing.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBoxAvailablePreprocessing.setObjectName("groupBoxAvailablePreprocessing")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBoxAvailablePreprocessing)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.pushButtonEOG = QtWidgets.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonEOG.setObjectName("pushButtonEOG")
        self.gridLayout_14.addWidget(self.pushButtonEOG, 3, 0, 1, 1)
        self.pushButtonApplyEOG = QtWidgets.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonApplyEOG.setEnabled(False)
        self.pushButtonApplyEOG.setObjectName("pushButtonApplyEOG")
        self.gridLayout_14.addWidget(self.pushButtonApplyEOG, 3, 1, 1, 1)
        self.pushButtonApplyECG = QtWidgets.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonApplyECG.setEnabled(False)
        self.pushButtonApplyECG.setObjectName("pushButtonApplyECG")
        self.gridLayout_14.addWidget(self.pushButtonApplyECG, 2, 1, 1, 1)
        self.pushButtonECG = QtWidgets.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonECG.setObjectName("pushButtonECG")
        self.gridLayout_14.addWidget(self.pushButtonECG, 2, 0, 1, 1)
        self.pushButtonFilter = QtWidgets.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonFilter.setObjectName("pushButtonFilter")
        self.gridLayout_14.addWidget(self.pushButtonFilter, 0, 0, 1, 1)
        self.pushButtonICA = QtWidgets.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonICA.setObjectName("pushButtonICA")
        self.gridLayout_14.addWidget(self.pushButtonICA, 0, 1, 1, 1)
        self.pushButtonResampling = QtWidgets.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonResampling.setObjectName("pushButtonResampling")
        self.gridLayout_14.addWidget(self.pushButtonResampling, 1, 1, 1, 1)
        self.pushButtonRereferencing = QtWidgets.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonRereferencing.setObjectName("pushButtonRereferencing")
        self.gridLayout_14.addWidget(self.pushButtonRereferencing, 1, 0, 1, 1)
        self.pushButtonCrop = QtWidgets.QPushButton(self.groupBoxAvailablePreprocessing)
        self.pushButtonCrop.setObjectName("pushButtonCrop")
        self.gridLayout_14.addWidget(self.pushButtonCrop, 4, 0, 1, 1)
        self.horizontalLayout_18.addLayout(self.gridLayout_14)
        self.gridLayout_13.addLayout(self.horizontalLayout_18, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBoxAvailablePreprocessing, 1, 0, 1, 1)
        self.groupBoxPreprocessingCheckBoxes = QtWidgets.QGroupBox(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPreprocessingCheckBoxes.sizePolicy().hasHeightForWidth())
        self.groupBoxPreprocessingCheckBoxes.setSizePolicy(sizePolicy)
        self.groupBoxPreprocessingCheckBoxes.setMinimumSize(QtCore.QSize(60, 0))
        self.groupBoxPreprocessingCheckBoxes.setObjectName("groupBoxPreprocessingCheckBoxes")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBoxPreprocessingCheckBoxes)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.labelRereferenced = QtWidgets.QLabel(self.groupBoxPreprocessingCheckBoxes)
        self.labelRereferenced.setObjectName("labelRereferenced")
        self.gridLayout_6.addWidget(self.labelRereferenced, 2, 0, 1, 1)
        self.labelMaxFilter = QtWidgets.QLabel(self.groupBoxPreprocessingCheckBoxes)
        self.labelMaxFilter.setObjectName("labelMaxFilter")
        self.gridLayout_6.addWidget(self.labelMaxFilter, 0, 0, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem)
        self.checkBoxMaxFilterApplied = QtWidgets.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxMaxFilterApplied.setEnabled(False)
        self.checkBoxMaxFilterApplied.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBoxMaxFilterApplied.setText("")
        self.checkBoxMaxFilterApplied.setObjectName("checkBoxMaxFilterApplied")
        self.horizontalLayout_21.addWidget(self.checkBoxMaxFilterApplied)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem1)
        self.gridLayout_6.addLayout(self.horizontalLayout_21, 0, 1, 1, 1)
        self.labelICAApplied = QtWidgets.QLabel(self.groupBoxPreprocessingCheckBoxes)
        self.labelICAApplied.setObjectName("labelICAApplied")
        self.gridLayout_6.addWidget(self.labelICAApplied, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.checkBoxICAApplied = QtWidgets.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxICAApplied.setEnabled(False)
        self.checkBoxICAApplied.setText("")
        self.checkBoxICAApplied.setObjectName("checkBoxICAApplied")
        self.horizontalLayout_5.addWidget(self.checkBoxICAApplied)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.checkBoxRereferenced = QtWidgets.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxRereferenced.setEnabled(False)
        self.checkBoxRereferenced.setText("")
        self.checkBoxRereferenced.setObjectName("checkBoxRereferenced")
        self.horizontalLayout_6.addWidget(self.checkBoxRereferenced)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.gridLayout_6.addLayout(self.horizontalLayout_6, 2, 1, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBoxPreprocessingCheckBoxes, 0, 0, 1, 1)
        self.groupBoxVisualization = QtWidgets.QGroupBox(self.gridLayoutWidget_3)
        self.groupBoxVisualization.setObjectName("groupBoxVisualization")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxVisualization)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.checkBoxShowEvents = QtWidgets.QCheckBox(self.groupBoxVisualization)
        self.checkBoxShowEvents.setObjectName("checkBoxShowEvents")
        self.gridLayout_16.addWidget(self.checkBoxShowEvents, 0, 1, 1, 1)
        self.pushButtonRawPlot = QtWidgets.QPushButton(self.groupBoxVisualization)
        self.pushButtonRawPlot.setObjectName("pushButtonRawPlot")
        self.gridLayout_16.addWidget(self.pushButtonRawPlot, 0, 0, 1, 1)
        self.pushButtonPlotProjections = QtWidgets.QPushButton(self.groupBoxVisualization)
        self.pushButtonPlotProjections.setObjectName("pushButtonPlotProjections")
        self.gridLayout_16.addWidget(self.pushButtonPlotProjections, 1, 0, 1, 1)
        self.horizontalLayout_32.addLayout(self.gridLayout_16)
        self.gridLayout_3.addLayout(self.horizontalLayout_32, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBoxVisualization, 2, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelBads = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelBads.setObjectName("labelBads")
        self.verticalLayout_5.addWidget(self.labelBads)
        self.listWidgetBads = QtWidgets.QListWidget(self.gridLayoutWidget_3)
        self.listWidgetBads.setEnabled(True)
        self.listWidgetBads.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidgetBads.setObjectName("listWidgetBads")
        self.verticalLayout_5.addWidget(self.listWidgetBads)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonCustomChannels = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButtonCustomChannels.setObjectName("pushButtonCustomChannels")
        self.horizontalLayout.addWidget(self.pushButtonCustomChannels)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.gridLayout_19.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelProjs = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelProjs.setObjectName("labelProjs")
        self.verticalLayout_2.addWidget(self.labelProjs)
        self.listWidgetProjs = QtWidgets.QListWidget(self.gridLayoutWidget_3)
        self.listWidgetProjs.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetProjs.sizePolicy().hasHeightForWidth())
        self.listWidgetProjs.setSizePolicy(sizePolicy)
        self.listWidgetProjs.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidgetProjs.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.listWidgetProjs.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidgetProjs.setObjectName("listWidgetProjs")
        self.verticalLayout_2.addWidget(self.listWidgetProjs)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButtonRemoveProj = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButtonRemoveProj.setObjectName("pushButtonRemoveProj")
        self.horizontalLayout_4.addWidget(self.pushButtonRemoveProj)
        spacerItem8 = QtWidgets.QSpacerItem(78, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_19.addLayout(self.verticalLayout_2, 1, 1, 1, 1)

        self.retranslateUi(mainWindowTabPreprocessing)
        QtCore.QMetaObject.connectSlotsByName(mainWindowTabPreprocessing)

    def retranslateUi(self, mainWindowTabPreprocessing):
        _translate = QtCore.QCoreApplication.translate
        mainWindowTabPreprocessing.setWindowTitle(_translate("mainWindowTabPreprocessing", "Form"))
        self.groupBoxAvailablePreprocessing.setTitle(_translate("mainWindowTabPreprocessing", "Available actions:"))
        self.pushButtonEOG.setText(_translate("mainWindowTabPreprocessing", "Calculate EOG projections..."))
        self.pushButtonApplyEOG.setText(_translate("mainWindowTabPreprocessing", "Apply EOG projections..."))
        self.pushButtonApplyECG.setText(_translate("mainWindowTabPreprocessing", "Apply ECG projections..."))
        self.pushButtonECG.setText(_translate("mainWindowTabPreprocessing", "Calculate ECG projections..."))
        self.pushButtonFilter.setText(_translate("mainWindowTabPreprocessing", "Filter..."))
        self.pushButtonICA.setText(_translate("mainWindowTabPreprocessing", "ICA..."))
        self.pushButtonResampling.setText(_translate("mainWindowTabPreprocessing", "Resample..."))
        self.pushButtonRereferencing.setText(_translate("mainWindowTabPreprocessing", "Rereference..."))
        self.pushButtonCrop.setText(_translate("mainWindowTabPreprocessing", "Crop..."))
        self.groupBoxPreprocessingCheckBoxes.setTitle(_translate("mainWindowTabPreprocessing", "Preprocessing information:"))
        self.labelRereferenced.setText(_translate("mainWindowTabPreprocessing", "Rereferenced:"))
        self.labelMaxFilter.setText(_translate("mainWindowTabPreprocessing", "MaxFilter applied:"))
        self.labelICAApplied.setText(_translate("mainWindowTabPreprocessing", "ICA applied:"))
        self.groupBoxVisualization.setTitle(_translate("mainWindowTabPreprocessing", "Visualization:"))
        self.checkBoxShowEvents.setText(_translate("mainWindowTabPreprocessing", "Show events"))
        self.pushButtonRawPlot.setText(_translate("mainWindowTabPreprocessing", "Raw plot"))
        self.pushButtonPlotProjections.setText(_translate("mainWindowTabPreprocessing", "Plot projections"))
        self.labelBads.setText(_translate("mainWindowTabPreprocessing", "Bad channels"))
        self.listWidgetBads.setSortingEnabled(True)
        self.pushButtonCustomChannels.setText(_translate("mainWindowTabPreprocessing", "Customize channels..."))
        self.labelProjs.setText(_translate("mainWindowTabPreprocessing", "Added projection items"))
        self.listWidgetProjs.setSortingEnabled(False)
        self.pushButtonRemoveProj.setText(_translate("mainWindowTabPreprocessing", "Remove"))

