# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowTabSourceAnalysisUi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindowTabSourceAnalysis(object):
    def setupUi(self, mainWindowTabSourceAnalysis):
        mainWindowTabSourceAnalysis.setObjectName(_fromUtf8("mainWindowTabSourceAnalysis"))
        mainWindowTabSourceAnalysis.resize(1060, 648)
        self.tabWidgetSourceAnalysis = QtGui.QTabWidget(mainWindowTabSourceAnalysis)
        self.tabWidgetSourceAnalysis.setEnabled(True)
        self.tabWidgetSourceAnalysis.setGeometry(QtCore.QRect(0, 10, 991, 571))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidgetSourceAnalysis.sizePolicy().hasHeightForWidth())
        self.tabWidgetSourceAnalysis.setSizePolicy(sizePolicy)
        self.tabWidgetSourceAnalysis.setMinimumSize(QtCore.QSize(200, 400))
        self.tabWidgetSourceAnalysis.setMaximumSize(QtCore.QSize(20000, 16777215))
        self.tabWidgetSourceAnalysis.setObjectName(_fromUtf8("tabWidgetSourceAnalysis"))
        self.tabSourcePreparation = QtGui.QWidget()
        self.tabSourcePreparation.setObjectName(_fromUtf8("tabSourcePreparation"))
        self.formLayout_6 = QtGui.QFormLayout(self.tabSourcePreparation)
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBoxReconstruction = QtGui.QGroupBox(self.tabSourcePreparation)
        self.groupBoxReconstruction.setFlat(False)
        self.groupBoxReconstruction.setCheckable(False)
        self.groupBoxReconstruction.setObjectName(_fromUtf8("groupBoxReconstruction"))
        self.formLayout_5 = QtGui.QFormLayout(self.groupBoxReconstruction)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.frameCopyRecon = QtGui.QFrame(self.groupBoxReconstruction)
        self.frameCopyRecon.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameCopyRecon.setFrameShadow(QtGui.QFrame.Raised)
        self.frameCopyRecon.setObjectName(_fromUtf8("frameCopyRecon"))
        self.gridLayout_29 = QtGui.QGridLayout(self.frameCopyRecon)
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.labelCopyMRI = QtGui.QLabel(self.frameCopyRecon)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelCopyMRI.setFont(font)
        self.labelCopyMRI.setToolTip(_fromUtf8(""))
        self.labelCopyMRI.setWhatsThis(_fromUtf8(""))
        self.labelCopyMRI.setObjectName(_fromUtf8("labelCopyMRI"))
        self.horizontalLayout_6.addWidget(self.labelCopyMRI)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lineEditRecon = QtGui.QLineEdit(self.frameCopyRecon)
        self.lineEditRecon.setEnabled(False)
        self.lineEditRecon.setObjectName(_fromUtf8("lineEditRecon"))
        self.horizontalLayout_5.addWidget(self.lineEditRecon)
        self.pushButtonBrowseRecon = QtGui.QPushButton(self.frameCopyRecon)
        self.pushButtonBrowseRecon.setObjectName(_fromUtf8("pushButtonBrowseRecon"))
        self.horizontalLayout_5.addWidget(self.pushButtonBrowseRecon)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.gridLayout_29.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.frameCopyRecon)
        self.frameExamine = QtGui.QFrame(self.groupBoxReconstruction)
        self.frameExamine.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameExamine.setFrameShadow(QtGui.QFrame.Raised)
        self.frameExamine.setObjectName(_fromUtf8("frameExamine"))
        self.gridLayout_30 = QtGui.QGridLayout(self.frameExamine)
        self.gridLayout_30.setObjectName(_fromUtf8("gridLayout_30"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.labelExamine = QtGui.QLabel(self.frameExamine)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelExamine.setFont(font)
        self.labelExamine.setIndent(-1)
        self.labelExamine.setObjectName(_fromUtf8("labelExamine"))
        self.horizontalLayout_7.addWidget(self.labelExamine)
        self.verticalLayout_13.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_57 = QtGui.QHBoxLayout()
        self.horizontalLayout_57.setObjectName(_fromUtf8("horizontalLayout_57"))
        self.pushButtonCheckTalairach = QtGui.QPushButton(self.frameExamine)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCheckTalairach.sizePolicy().hasHeightForWidth())
        self.pushButtonCheckTalairach.setSizePolicy(sizePolicy)
        self.pushButtonCheckTalairach.setObjectName(_fromUtf8("pushButtonCheckTalairach"))
        self.horizontalLayout_57.addWidget(self.pushButtonCheckTalairach)
        self.pushButtonSkullStrip = QtGui.QPushButton(self.frameExamine)
        self.pushButtonSkullStrip.setObjectName(_fromUtf8("pushButtonSkullStrip"))
        self.horizontalLayout_57.addWidget(self.pushButtonSkullStrip)
        self.pushButtonCheckSurfaces = QtGui.QPushButton(self.frameExamine)
        self.pushButtonCheckSurfaces.setObjectName(_fromUtf8("pushButtonCheckSurfaces"))
        self.horizontalLayout_57.addWidget(self.pushButtonCheckSurfaces)
        self.pushButtonCheckSegmentations = QtGui.QPushButton(self.frameExamine)
        self.pushButtonCheckSegmentations.setObjectName(_fromUtf8("pushButtonCheckSegmentations"))
        self.horizontalLayout_57.addWidget(self.pushButtonCheckSegmentations)
        self.verticalLayout_13.addLayout(self.horizontalLayout_57)
        self.gridLayout_30.addLayout(self.verticalLayout_13, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.frameExamine)
        self.frameCopyUnderSubject = QtGui.QFrame(self.groupBoxReconstruction)
        self.frameCopyUnderSubject.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameCopyUnderSubject.setFrameShadow(QtGui.QFrame.Raised)
        self.frameCopyUnderSubject.setObjectName(_fromUtf8("frameCopyUnderSubject"))
        self.layoutCopyUnderSubject = QtGui.QGridLayout(self.frameCopyUnderSubject)
        self.layoutCopyUnderSubject.setObjectName(_fromUtf8("layoutCopyUnderSubject"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelCopied = QtGui.QLabel(self.frameCopyUnderSubject)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelCopied.setFont(font)
        self.labelCopied.setObjectName(_fromUtf8("labelCopied"))
        self.horizontalLayout.addWidget(self.labelCopied)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButtonCopyUnderSubject = QtGui.QPushButton(self.frameCopyUnderSubject)
        self.pushButtonCopyUnderSubject.setEnabled(True)
        self.pushButtonCopyUnderSubject.setObjectName(_fromUtf8("pushButtonCopyUnderSubject"))
        self.horizontalLayout_2.addWidget(self.pushButtonCopyUnderSubject)
        spacerItem1 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.checkBoxCopyUnderSubject = QtGui.QCheckBox(self.frameCopyUnderSubject)
        self.checkBoxCopyUnderSubject.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxCopyUnderSubject.sizePolicy().hasHeightForWidth())
        self.checkBoxCopyUnderSubject.setSizePolicy(sizePolicy)
        self.checkBoxCopyUnderSubject.setText(_fromUtf8(""))
        self.checkBoxCopyUnderSubject.setCheckable(True)
        self.checkBoxCopyUnderSubject.setObjectName(_fromUtf8("checkBoxCopyUnderSubject"))
        self.horizontalLayout_2.addWidget(self.checkBoxCopyUnderSubject)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layoutCopyUnderSubject.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.frameCopyUnderSubject)
        self.frameBem = QtGui.QFrame(self.groupBoxReconstruction)
        self.frameBem.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameBem.setFrameShadow(QtGui.QFrame.Raised)
        self.frameBem.setObjectName(_fromUtf8("frameBem"))
        self.layoutCopyUnderSubject_2 = QtGui.QGridLayout(self.frameBem)
        self.layoutCopyUnderSubject_2.setObjectName(_fromUtf8("layoutCopyUnderSubject_2"))
        self.verticalLayoutBem = QtGui.QVBoxLayout()
        self.verticalLayoutBem.setContentsMargins(0, 0, -1, -1)
        self.verticalLayoutBem.setObjectName(_fromUtf8("verticalLayoutBem"))
        self.horizontalLayoutBem_1 = QtGui.QHBoxLayout()
        self.horizontalLayoutBem_1.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayoutBem_1.setObjectName(_fromUtf8("horizontalLayoutBem_1"))
        self.labelBem = QtGui.QLabel(self.frameBem)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelBem.setFont(font)
        self.labelBem.setObjectName(_fromUtf8("labelBem"))
        self.horizontalLayoutBem_1.addWidget(self.labelBem)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayoutBem_1.addItem(spacerItem2)
        self.labelAtlas = QtGui.QLabel(self.frameBem)
        self.labelAtlas.setObjectName(_fromUtf8("labelAtlas"))
        self.horizontalLayoutBem_1.addWidget(self.labelAtlas)
        self.checkBoxAtlas = QtGui.QCheckBox(self.frameBem)
        self.checkBoxAtlas.setEnabled(True)
        self.checkBoxAtlas.setText(_fromUtf8(""))
        self.checkBoxAtlas.setChecked(True)
        self.checkBoxAtlas.setObjectName(_fromUtf8("checkBoxAtlas"))
        self.horizontalLayoutBem_1.addWidget(self.checkBoxAtlas)
        self.verticalLayoutBem.addLayout(self.horizontalLayoutBem_1)
        self.horizontalLayoutBem_2 = QtGui.QHBoxLayout()
        self.horizontalLayoutBem_2.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayoutBem_2.setObjectName(_fromUtf8("horizontalLayoutBem_2"))
        self.pushButtonBem = QtGui.QPushButton(self.frameBem)
        self.pushButtonBem.setEnabled(True)
        self.pushButtonBem.setObjectName(_fromUtf8("pushButtonBem"))
        self.horizontalLayoutBem_2.addWidget(self.pushButtonBem)
        spacerItem3 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayoutBem_2.addItem(spacerItem3)
        self.checkBoxBem = QtGui.QCheckBox(self.frameBem)
        self.checkBoxBem.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxBem.sizePolicy().hasHeightForWidth())
        self.checkBoxBem.setSizePolicy(sizePolicy)
        self.checkBoxBem.setText(_fromUtf8(""))
        self.checkBoxBem.setCheckable(True)
        self.checkBoxBem.setObjectName(_fromUtf8("checkBoxBem"))
        self.horizontalLayoutBem_2.addWidget(self.checkBoxBem)
        self.verticalLayoutBem.addLayout(self.horizontalLayoutBem_2)
        self.layoutCopyUnderSubject_2.addLayout(self.verticalLayoutBem, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.frameBem)
        self.formLayout_5.setLayout(0, QtGui.QFormLayout.LabelRole, self.verticalLayout_10)
        self.verticalLayout_8.addWidget(self.groupBoxReconstruction)
        self.formLayout_6.setLayout(0, QtGui.QFormLayout.LabelRole, self.verticalLayout_8)
        self.label_7 = QtGui.QLabel(self.tabSourcePreparation)
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_7)
        self.tabWidgetSourceAnalysis.addTab(self.tabSourcePreparation, _fromUtf8(""))
        self.tabCoregistration = QtGui.QWidget()
        self.tabCoregistration.setObjectName(_fromUtf8("tabCoregistration"))
        self.formLayout_10 = QtGui.QFormLayout(self.tabCoregistration)
        self.formLayout_10.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_10.setObjectName(_fromUtf8("formLayout_10"))
        self.groupBoxCoregistration = QtGui.QGroupBox(self.tabCoregistration)
        self.groupBoxCoregistration.setFlat(False)
        self.groupBoxCoregistration.setCheckable(False)
        self.groupBoxCoregistration.setObjectName(_fromUtf8("groupBoxCoregistration"))
        self.formLayout_7 = QtGui.QFormLayout(self.groupBoxCoregistration)
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.verticalLayoutCoregistration = QtGui.QVBoxLayout()
        self.verticalLayoutCoregistration.setObjectName(_fromUtf8("verticalLayoutCoregistration"))
        self.frameCoregistrationGUI = QtGui.QFrame(self.groupBoxCoregistration)
        self.frameCoregistrationGUI.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameCoregistrationGUI.setFrameShadow(QtGui.QFrame.Raised)
        self.frameCoregistrationGUI.setObjectName(_fromUtf8("frameCoregistrationGUI"))
        self.gridLayout_32 = QtGui.QGridLayout(self.frameCoregistrationGUI)
        self.gridLayout_32.setObjectName(_fromUtf8("gridLayout_32"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.labelCoregistrationGUI = QtGui.QLabel(self.frameCoregistrationGUI)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelCoregistrationGUI.setFont(font)
        self.labelCoregistrationGUI.setToolTip(_fromUtf8(""))
        self.labelCoregistrationGUI.setWhatsThis(_fromUtf8(""))
        self.labelCoregistrationGUI.setObjectName(_fromUtf8("labelCoregistrationGUI"))
        self.horizontalLayout_8.addWidget(self.labelCoregistrationGUI)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.pushButtonCoregistrationGUI = QtGui.QPushButton(self.frameCoregistrationGUI)
        self.pushButtonCoregistrationGUI.setObjectName(_fromUtf8("pushButtonCoregistrationGUI"))
        self.horizontalLayout_9.addWidget(self.pushButtonCoregistrationGUI)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.gridLayout_32.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayoutCoregistration.addWidget(self.frameCoregistrationGUI)
        self.frameCoregistrationBrowse = QtGui.QFrame(self.groupBoxCoregistration)
        self.frameCoregistrationBrowse.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameCoregistrationBrowse.setFrameShadow(QtGui.QFrame.Raised)
        self.frameCoregistrationBrowse.setObjectName(_fromUtf8("frameCoregistrationBrowse"))
        self.gridLayout_42 = QtGui.QGridLayout(self.frameCoregistrationBrowse)
        self.gridLayout_42.setObjectName(_fromUtf8("gridLayout_42"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.labelCoregistrationBrowse = QtGui.QLabel(self.frameCoregistrationBrowse)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelCoregistrationBrowse.setFont(font)
        self.labelCoregistrationBrowse.setIndent(-1)
        self.labelCoregistrationBrowse.setObjectName(_fromUtf8("labelCoregistrationBrowse"))
        self.horizontalLayout_10.addWidget(self.labelCoregistrationBrowse)
        self.verticalLayout_14.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_63 = QtGui.QHBoxLayout()
        self.horizontalLayout_63.setObjectName(_fromUtf8("horizontalLayout_63"))
        self.lineEditCoregistrationBrowse = QtGui.QLineEdit(self.frameCoregistrationBrowse)
        self.lineEditCoregistrationBrowse.setEnabled(False)
        self.lineEditCoregistrationBrowse.setObjectName(_fromUtf8("lineEditCoregistrationBrowse"))
        self.horizontalLayout_63.addWidget(self.lineEditCoregistrationBrowse)
        self.pushButtonCoregistrationBrowse = QtGui.QPushButton(self.frameCoregistrationBrowse)
        self.pushButtonCoregistrationBrowse.setObjectName(_fromUtf8("pushButtonCoregistrationBrowse"))
        self.horizontalLayout_63.addWidget(self.pushButtonCoregistrationBrowse)
        self.verticalLayout_14.addLayout(self.horizontalLayout_63)
        self.gridLayout_42.addLayout(self.verticalLayout_14, 0, 0, 1, 1)
        self.verticalLayoutCoregistration.addWidget(self.frameCoregistrationBrowse)
        self.formLayout_7.setLayout(0, QtGui.QFormLayout.LabelRole, self.verticalLayoutCoregistration)
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.LabelRole, self.groupBoxCoregistration)
        self.tabWidgetSourceAnalysis.addTab(self.tabCoregistration, _fromUtf8(""))
        self.tabForwardSolution = QtGui.QWidget()
        self.tabForwardSolution.setObjectName(_fromUtf8("tabForwardSolution"))
        self.formLayout_11 = QtGui.QFormLayout(self.tabForwardSolution)
        self.formLayout_11.setObjectName(_fromUtf8("formLayout_11"))
        self.horizontalLayout_60 = QtGui.QHBoxLayout()
        self.horizontalLayout_60.setObjectName(_fromUtf8("horizontalLayout_60"))
        self.groupBox_4 = QtGui.QGroupBox(self.tabForwardSolution)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_35 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_35.setObjectName(_fromUtf8("gridLayout_35"))
        self.tableViewFModelsForSolution = QtGui.QTableView(self.groupBox_4)
        self.tableViewFModelsForSolution.setAlternatingRowColors(True)
        self.tableViewFModelsForSolution.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableViewFModelsForSolution.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableViewFModelsForSolution.setSortingEnabled(True)
        self.tableViewFModelsForSolution.setObjectName(_fromUtf8("tableViewFModelsForSolution"))
        self.tableViewFModelsForSolution.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_35.addWidget(self.tableViewFModelsForSolution, 1, 0, 1, 1)
        self.pushButtonCreateForwardSolution = QtGui.QPushButton(self.groupBox_4)
        self.pushButtonCreateForwardSolution.setObjectName(_fromUtf8("pushButtonCreateForwardSolution"))
        self.gridLayout_35.addWidget(self.pushButtonCreateForwardSolution, 2, 0, 1, 1)
        self.pushButtonRemoveForwardSolution = QtGui.QPushButton(self.groupBox_4)
        self.pushButtonRemoveForwardSolution.setObjectName(_fromUtf8("pushButtonRemoveForwardSolution"))
        self.gridLayout_35.addWidget(self.pushButtonRemoveForwardSolution, 4, 0, 1, 1)
        self.pushButtonImportForwardSolution = QtGui.QPushButton(self.groupBox_4)
        self.pushButtonImportForwardSolution.setObjectName(_fromUtf8("pushButtonImportForwardSolution"))
        self.gridLayout_35.addWidget(self.pushButtonImportForwardSolution, 3, 0, 1, 1)
        self.horizontalLayout_60.addWidget(self.groupBox_4)
        self.formLayout_11.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_60)
        self.tabWidgetSourceAnalysis.addTab(self.tabForwardSolution, _fromUtf8(""))
        self.tabNoiseCovariance = QtGui.QWidget()
        self.tabNoiseCovariance.setObjectName(_fromUtf8("tabNoiseCovariance"))
        self.formLayout_16 = QtGui.QFormLayout(self.tabNoiseCovariance)
        self.formLayout_16.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_16.setObjectName(_fromUtf8("formLayout_16"))
        self.horizontalLayout_61 = QtGui.QHBoxLayout()
        self.horizontalLayout_61.setObjectName(_fromUtf8("horizontalLayout_61"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setContentsMargins(-1, 13, -1, -1)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.pushButtonComputeCovarianceRaw = QtGui.QPushButton(self.tabNoiseCovariance)
        self.pushButtonComputeCovarianceRaw.setObjectName(_fromUtf8("pushButtonComputeCovarianceRaw"))
        self.verticalLayout_15.addWidget(self.pushButtonComputeCovarianceRaw)
        self.pushButtonComputeCovarianceEpochs = QtGui.QPushButton(self.tabNoiseCovariance)
        self.pushButtonComputeCovarianceEpochs.setObjectName(_fromUtf8("pushButtonComputeCovarianceEpochs"))
        self.verticalLayout_15.addWidget(self.pushButtonComputeCovarianceEpochs)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem5)
        self.horizontalLayout_61.addLayout(self.verticalLayout_15)
        self.frameCovarianceInfoWidget = QtGui.QFrame(self.tabNoiseCovariance)
        self.frameCovarianceInfoWidget.setMaximumSize(QtCore.QSize(600, 800))
        self.frameCovarianceInfoWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameCovarianceInfoWidget.setFrameShadow(QtGui.QFrame.Raised)
        self.frameCovarianceInfoWidget.setLineWidth(1)
        self.frameCovarianceInfoWidget.setObjectName(_fromUtf8("frameCovarianceInfoWidget"))
        self.horizontalLayout_61.addWidget(self.frameCovarianceInfoWidget)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_61.addItem(spacerItem6)
        self.formLayout_16.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_61)
        self.pushButtonPlotCov = QtGui.QPushButton(self.tabNoiseCovariance)
        self.pushButtonPlotCov.setObjectName(_fromUtf8("pushButtonPlotCov"))
        self.formLayout_16.setWidget(1, QtGui.QFormLayout.LabelRole, self.pushButtonPlotCov)
        self.tabWidgetSourceAnalysis.addTab(self.tabNoiseCovariance, _fromUtf8(""))
        self.tabInverseOperator = QtGui.QWidget()
        self.tabInverseOperator.setObjectName(_fromUtf8("tabInverseOperator"))
        self.layoutWidget_8 = QtGui.QWidget(self.tabInverseOperator)
        self.layoutWidget_8.setGeometry(QtCore.QRect(21, 10, 841, 261))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.horizontalLayout_62 = QtGui.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_62.setObjectName(_fromUtf8("horizontalLayout_62"))
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.groupBox_7 = QtGui.QGroupBox(self.layoutWidget_8)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_36 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_36.setObjectName(_fromUtf8("gridLayout_36"))
        self.listWidgetForwardSolution = QtGui.QListWidget(self.groupBox_7)
        self.listWidgetForwardSolution.setObjectName(_fromUtf8("listWidgetForwardSolution"))
        self.gridLayout_36.addWidget(self.listWidgetForwardSolution, 0, 0, 1, 1)
        self.verticalLayout_19.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(self.layoutWidget_8)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.label_12 = QtGui.QLabel(self.groupBox_8)
        self.label_12.setGeometry(QtCore.QRect(40, 90, 271, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_19.addWidget(self.groupBox_8)
        self.horizontalLayout_62.addLayout(self.verticalLayout_19)
        self.pushButtonComputeInverse = QtGui.QPushButton(self.layoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButtonComputeInverse.sizePolicy().hasHeightForWidth())
        self.pushButtonComputeInverse.setSizePolicy(sizePolicy)
        self.pushButtonComputeInverse.setObjectName(_fromUtf8("pushButtonComputeInverse"))
        self.horizontalLayout_62.addWidget(self.pushButtonComputeInverse)
        self.formLayout_15 = QtGui.QFormLayout()
        self.formLayout_15.setObjectName(_fromUtf8("formLayout_15"))
        self.groupBox_10 = QtGui.QGroupBox(self.layoutWidget_8)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.formLayout_15.setWidget(1, QtGui.QFormLayout.LabelRole, self.groupBox_10)
        self.groupBox_9 = QtGui.QGroupBox(self.layoutWidget_8)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_37 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_37.setObjectName(_fromUtf8("gridLayout_37"))
        self.listWidgetInverseOperator = QtGui.QListWidget(self.groupBox_9)
        self.listWidgetInverseOperator.setObjectName(_fromUtf8("listWidgetInverseOperator"))
        self.gridLayout_37.addWidget(self.listWidgetInverseOperator, 0, 0, 1, 1)
        self.formLayout_15.setWidget(0, QtGui.QFormLayout.SpanningRole, self.groupBox_9)
        self.horizontalLayout_62.addLayout(self.formLayout_15)
        self.tabWidgetSourceAnalysis.addTab(self.tabInverseOperator, _fromUtf8(""))
        self.tabSourceEstimate = QtGui.QWidget()
        self.tabSourceEstimate.setObjectName(_fromUtf8("tabSourceEstimate"))
        self.groupBox_11 = QtGui.QGroupBox(self.tabSourceEstimate)
        self.groupBox_11.setGeometry(QtCore.QRect(30, 20, 430, 511))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.formLayout_17 = QtGui.QFormLayout(self.groupBox_11)
        self.formLayout_17.setObjectName(_fromUtf8("formLayout_17"))
        self.verticalLayout_38 = QtGui.QVBoxLayout()
        self.verticalLayout_38.setObjectName(_fromUtf8("verticalLayout_38"))
        self.radioButtonRaw = QtGui.QRadioButton(self.groupBox_11)
        self.radioButtonRaw.setChecked(True)
        self.radioButtonRaw.setObjectName(_fromUtf8("radioButtonRaw"))
        self.verticalLayout_38.addWidget(self.radioButtonRaw)
        self.verticalLayout_39 = QtGui.QVBoxLayout()
        self.verticalLayout_39.setObjectName(_fromUtf8("verticalLayout_39"))
        self.radioButtonEpoch = QtGui.QRadioButton(self.groupBox_11)
        self.radioButtonEpoch.setObjectName(_fromUtf8("radioButtonEpoch"))
        self.verticalLayout_39.addWidget(self.radioButtonEpoch)
        self.frameInverseEpochs = QtGui.QFrame(self.groupBox_11)
        self.frameInverseEpochs.setEnabled(False)
        self.frameInverseEpochs.setMinimumSize(QtCore.QSize(400, 200))
        self.frameInverseEpochs.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameInverseEpochs.setFrameShadow(QtGui.QFrame.Raised)
        self.frameInverseEpochs.setObjectName(_fromUtf8("frameInverseEpochs"))
        self.verticalLayout_39.addWidget(self.frameInverseEpochs)
        self.verticalLayout_38.addLayout(self.verticalLayout_39)
        self.gridLayout_38 = QtGui.QGridLayout()
        self.gridLayout_38.setObjectName(_fromUtf8("gridLayout_38"))
        self.radioButtonEvoked = QtGui.QRadioButton(self.groupBox_11)
        self.radioButtonEvoked.setObjectName(_fromUtf8("radioButtonEvoked"))
        self.gridLayout_38.addWidget(self.radioButtonEvoked, 0, 0, 1, 1)
        self.groupBoxInverseEvoked = QtGui.QGroupBox(self.groupBox_11)
        self.groupBoxInverseEvoked.setEnabled(False)
        self.groupBoxInverseEvoked.setObjectName(_fromUtf8("groupBoxInverseEvoked"))
        self.gridLayout_39 = QtGui.QGridLayout(self.groupBoxInverseEvoked)
        self.gridLayout_39.setObjectName(_fromUtf8("gridLayout_39"))
        self.listWidgetInverseEvoked = QtGui.QListWidget(self.groupBoxInverseEvoked)
        self.listWidgetInverseEvoked.setEnabled(False)
        self.listWidgetInverseEvoked.setObjectName(_fromUtf8("listWidgetInverseEvoked"))
        self.gridLayout_39.addWidget(self.listWidgetInverseEvoked, 0, 0, 1, 1)
        self.gridLayout_38.addWidget(self.groupBoxInverseEvoked, 1, 0, 1, 1)
        self.verticalLayout_38.addLayout(self.gridLayout_38)
        self.formLayout_17.setLayout(0, QtGui.QFormLayout.SpanningRole, self.verticalLayout_38)
        self.pushButtonMakeSourceEstimate = QtGui.QPushButton(self.tabSourceEstimate)
        self.pushButtonMakeSourceEstimate.setGeometry(QtCore.QRect(480, 40, 121, 491))
        self.pushButtonMakeSourceEstimate.setObjectName(_fromUtf8("pushButtonMakeSourceEstimate"))
        self.label_35 = QtGui.QLabel(self.tabSourceEstimate)
        self.label_35.setGeometry(QtCore.QRect(460, 280, 16, 16))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_36 = QtGui.QLabel(self.tabSourceEstimate)
        self.label_36.setGeometry(QtCore.QRect(600, 280, 21, 16))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.layoutWidget_9 = QtGui.QWidget(self.tabSourceEstimate)
        self.layoutWidget_9.setGeometry(QtCore.QRect(640, 40, 284, 263))
        self.layoutWidget_9.setObjectName(_fromUtf8("layoutWidget_9"))
        self.verticalLayout_40 = QtGui.QVBoxLayout(self.layoutWidget_9)
        self.verticalLayout_40.setObjectName(_fromUtf8("verticalLayout_40"))
        self.groupBox_23 = QtGui.QGroupBox(self.layoutWidget_9)
        self.groupBox_23.setObjectName(_fromUtf8("groupBox_23"))
        self.gridLayout_40 = QtGui.QGridLayout(self.groupBox_23)
        self.gridLayout_40.setObjectName(_fromUtf8("gridLayout_40"))
        self.listWidgetSourceEstimate = QtGui.QListWidget(self.groupBox_23)
        self.listWidgetSourceEstimate.setObjectName(_fromUtf8("listWidgetSourceEstimate"))
        self.gridLayout_40.addWidget(self.listWidgetSourceEstimate, 0, 0, 1, 1)
        self.verticalLayout_40.addWidget(self.groupBox_23)
        self.pushButtonVisStc = QtGui.QPushButton(self.layoutWidget_9)
        self.pushButtonVisStc.setObjectName(_fromUtf8("pushButtonVisStc"))
        self.verticalLayout_40.addWidget(self.pushButtonVisStc)
        self.tabWidgetSourceAnalysis.addTab(self.tabSourceEstimate, _fromUtf8(""))
        self.tabAnalysis = QtGui.QWidget()
        self.tabAnalysis.setObjectName(_fromUtf8("tabAnalysis"))
        self.groupBox_24 = QtGui.QGroupBox(self.tabAnalysis)
        self.groupBox_24.setGeometry(QtCore.QRect(20, 30, 221, 91))
        self.groupBox_24.setObjectName(_fromUtf8("groupBox_24"))
        self.gridLayout_41 = QtGui.QGridLayout(self.groupBox_24)
        self.gridLayout_41.setObjectName(_fromUtf8("gridLayout_41"))
        self.verticalLayout_41 = QtGui.QVBoxLayout()
        self.verticalLayout_41.setObjectName(_fromUtf8("verticalLayout_41"))
        self.pushButtonStcFreq = QtGui.QPushButton(self.groupBox_24)
        self.pushButtonStcFreq.setObjectName(_fromUtf8("pushButtonStcFreq"))
        self.verticalLayout_41.addWidget(self.pushButtonStcFreq)
        self.gridLayout_41.addLayout(self.verticalLayout_41, 0, 0, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.tabAnalysis)
        self.textEdit.setGeometry(QtCore.QRect(460, 60, 211, 171))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.tabWidgetSourceAnalysis.addTab(self.tabAnalysis, _fromUtf8(""))

        self.retranslateUi(mainWindowTabSourceAnalysis)
        self.tabWidgetSourceAnalysis.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindowTabSourceAnalysis)

    def retranslateUi(self, mainWindowTabSourceAnalysis):
        mainWindowTabSourceAnalysis.setWindowTitle(_translate("mainWindowTabSourceAnalysis", "Form", None))
        self.groupBoxReconstruction.setTitle(_translate("mainWindowTabSourceAnalysis", "MRI image reconstruction", None))
        self.frameCopyRecon.setWhatsThis(_translate("mainWindowTabSourceAnalysis", "<html><head/><body><p>MRI-image reconstruction can take a day, therefore Meggie only allows importing the pre-reconstructed image. You can, however, examine the reconstructed image with provided tools - if you have PySurfer installed and its path set properly in Meggie preferences.</p></body></html>", None))
        self.labelCopyMRI.setText(_translate("mainWindowTabSourceAnalysis", "Select directory to copy the reconstructed MRI image files from:", None))
        self.lineEditRecon.setWhatsThis(_translate("mainWindowTabSourceAnalysis", "MRI-image reconstruction can take a day, therefore Meggie only allows importing the pre-reconstructed image. You can, however, examine the reconstructed image with provided tools.", None))
        self.pushButtonBrowseRecon.setWhatsThis(_translate("mainWindowTabSourceAnalysis", "MRI-image reconstruction can take a day, therefore Meggie only allows importing the pre-reconstructed image. You can, however, examine the reconstructed image with provided tools.", None))
        self.pushButtonBrowseRecon.setText(_translate("mainWindowTabSourceAnalysis", "Browse...", None))
        self.labelExamine.setText(_translate("mainWindowTabSourceAnalysis", "Examine the reconstructed MRI image files: (Optional)", None))
        self.pushButtonCheckTalairach.setText(_translate("mainWindowTabSourceAnalysis", "Check Talairach transform", None))
        self.pushButtonSkullStrip.setText(_translate("mainWindowTabSourceAnalysis", "Check skull strip", None))
        self.pushButtonCheckSurfaces.setText(_translate("mainWindowTabSourceAnalysis", "Check surfaces", None))
        self.pushButtonCheckSegmentations.setText(_translate("mainWindowTabSourceAnalysis", "Check segmentation", None))
        self.labelCopied.setText(_translate("mainWindowTabSourceAnalysis", "Copy and prepare MRI images under subject folder", None))
        self.pushButtonCopyUnderSubject.setText(_translate("mainWindowTabSourceAnalysis", "Copy", None))
        self.labelBem.setText(_translate("mainWindowTabSourceAnalysis", "Create Bem surfaces", None))
        self.labelAtlas.setText(_translate("mainWindowTabSourceAnalysis", "Use atlas", None))
        self.pushButtonBem.setText(_translate("mainWindowTabSourceAnalysis", "Create", None))
        self.tabWidgetSourceAnalysis.setTabText(self.tabWidgetSourceAnalysis.indexOf(self.tabSourcePreparation), _translate("mainWindowTabSourceAnalysis", "MRI reconstruction", None))
        self.groupBoxCoregistration.setTitle(_translate("mainWindowTabSourceAnalysis", "Coregistration of MEG and MRI", None))
        self.frameCoregistrationGUI.setWhatsThis(_translate("mainWindowTabSourceAnalysis", "<html><head/><body><p>MRI-image reconstruction can take a day, therefore Meggie only allows importing the pre-reconstructed image. You can, however, examine the reconstructed image with provided tools - if you have PySurfer installed and its path set properly in Meggie preferences.</p></body></html>", None))
        self.labelCoregistrationGUI.setText(_translate("mainWindowTabSourceAnalysis", "Use MNE-python Coregistration GUI to create a coordinate transformation file:", None))
        self.pushButtonCoregistrationGUI.setWhatsThis(_translate("mainWindowTabSourceAnalysis", "MRI-image reconstruction can take a day, therefore Meggie only allows importing the pre-reconstructed image. You can, however, examine the reconstructed image with provided tools.", None))
        self.pushButtonCoregistrationGUI.setText(_translate("mainWindowTabSourceAnalysis", "Open MNE-Python Coregistration...", None))
        self.labelCoregistrationBrowse.setText(_translate("mainWindowTabSourceAnalysis", "Locate the created or pre-existing coordinate transformation file:", None))
        self.lineEditCoregistrationBrowse.setWhatsThis(_translate("mainWindowTabSourceAnalysis", "MRI-image reconstruction can take a day, therefore Meggie only allows importing the pre-reconstructed image. You can, however, examine the reconstructed image with provided tools.", None))
        self.pushButtonCoregistrationBrowse.setText(_translate("mainWindowTabSourceAnalysis", "Browse...", None))
        self.tabWidgetSourceAnalysis.setTabText(self.tabWidgetSourceAnalysis.indexOf(self.tabCoregistration), _translate("mainWindowTabSourceAnalysis", "Coregistration", None))
        self.groupBox_4.setTitle(_translate("mainWindowTabSourceAnalysis", "Existing forward solutions", None))
        self.pushButtonCreateForwardSolution.setText(_translate("mainWindowTabSourceAnalysis", "Create a forward solution...", None))
        self.pushButtonRemoveForwardSolution.setText(_translate("mainWindowTabSourceAnalysis", "Remove a forward solution", None))
        self.pushButtonImportForwardSolution.setText(_translate("mainWindowTabSourceAnalysis", "Import forward solution...", None))
        self.tabWidgetSourceAnalysis.setTabText(self.tabWidgetSourceAnalysis.indexOf(self.tabForwardSolution), _translate("mainWindowTabSourceAnalysis", "Forward solution", None))
        self.pushButtonComputeCovarianceRaw.setText(_translate("mainWindowTabSourceAnalysis", "Compute noise covariance matrix based on raw file...", None))
        self.pushButtonComputeCovarianceEpochs.setText(_translate("mainWindowTabSourceAnalysis", "Compute noise covariance matrix based on epochs...", None))
        self.pushButtonPlotCov.setText(_translate("mainWindowTabSourceAnalysis", "Plot current covariance matrix", None))
        self.tabWidgetSourceAnalysis.setTabText(self.tabWidgetSourceAnalysis.indexOf(self.tabNoiseCovariance), _translate("mainWindowTabSourceAnalysis", "Noise covariance", None))
        self.groupBox_7.setTitle(_translate("mainWindowTabSourceAnalysis", "Forward solutions to base inverse operator on:", None))
        self.groupBox_8.setTitle(_translate("mainWindowTabSourceAnalysis", "Noise covariance matrix info:", None))
        self.label_12.setText(_translate("mainWindowTabSourceAnalysis", "edellisen välilehden tiedot myös tähän ", None))
        self.pushButtonComputeInverse.setText(_translate("mainWindowTabSourceAnalysis", "Compute \n"
" inverse operator...", None))
        self.groupBox_10.setTitle(_translate("mainWindowTabSourceAnalysis", "Information about selected inverse operator:", None))
        self.groupBox_9.setTitle(_translate("mainWindowTabSourceAnalysis", "Inverse operators:", None))
        self.tabWidgetSourceAnalysis.setTabText(self.tabWidgetSourceAnalysis.indexOf(self.tabInverseOperator), _translate("mainWindowTabSourceAnalysis", "Inverse operator", None))
        self.groupBox_11.setTitle(_translate("mainWindowTabSourceAnalysis", "Base source estimate on:", None))
        self.radioButtonRaw.setText(_translate("mainWindowTabSourceAnalysis", "Raw file", None))
        self.radioButtonEpoch.setText(_translate("mainWindowTabSourceAnalysis", "Epoch collection", None))
        self.radioButtonEvoked.setText(_translate("mainWindowTabSourceAnalysis", "Evoked dataset", None))
        self.groupBoxInverseEvoked.setTitle(_translate("mainWindowTabSourceAnalysis", "Evoked collections", None))
        self.pushButtonMakeSourceEstimate.setText(_translate("mainWindowTabSourceAnalysis", "Make \n"
" source estimate", None))
        self.label_35.setText(_translate("mainWindowTabSourceAnalysis", "---", None))
        self.label_36.setText(_translate("mainWindowTabSourceAnalysis", "-->", None))
        self.groupBox_23.setTitle(_translate("mainWindowTabSourceAnalysis", "Source estimates:", None))
        self.pushButtonVisStc.setText(_translate("mainWindowTabSourceAnalysis", "Visualize", None))
        self.tabWidgetSourceAnalysis.setTabText(self.tabWidgetSourceAnalysis.indexOf(self.tabSourceEstimate), _translate("mainWindowTabSourceAnalysis", "Source estimate", None))
        self.groupBox_24.setTitle(_translate("mainWindowTabSourceAnalysis", "Source estimates:", None))
        self.pushButtonStcFreq.setText(_translate("mainWindowTabSourceAnalysis", "Frequency analysis", None))
        self.textEdit.setHtml(_translate("mainWindowTabSourceAnalysis", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">Näille paikkeille sitten visualisointia, export-toimintoja yms.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\"><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\"><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\"><br /></span></p></body></html>", None))
        self.tabWidgetSourceAnalysis.setTabText(self.tabWidgetSourceAnalysis.indexOf(self.tabAnalysis), _translate("mainWindowTabSourceAnalysis", "Analysis", None))

