# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowTabEvokedUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindowTabEvoked(object):
    def setupUi(self, mainWindowTabEvoked):
        mainWindowTabEvoked.setObjectName("mainWindowTabEvoked")
        mainWindowTabEvoked.resize(1054, 773)
        self.layoutWidget_2 = QtWidgets.QWidget(mainWindowTabEvoked)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 994, 734))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.groupBoxEpochs = QtWidgets.QGroupBox(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxEpochs.sizePolicy().hasHeightForWidth())
        self.groupBoxEpochs.setSizePolicy(sizePolicy)
        self.groupBoxEpochs.setMinimumSize(QtCore.QSize(400, 380))
        self.groupBoxEpochs.setTitle("")
        self.groupBoxEpochs.setObjectName("groupBoxEpochs")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBoxEpochs)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.verticalLayout_23.addWidget(self.groupBoxEpochs)
        self.gridLayout_16.addLayout(self.verticalLayout_23, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_4.addItem(spacerItem)
        self.pushButtonCreateEvoked = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCreateEvoked.sizePolicy().hasHeightForWidth())
        self.pushButtonCreateEvoked.setSizePolicy(sizePolicy)
        self.pushButtonCreateEvoked.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.pushButtonCreateEvoked.setObjectName("pushButtonCreateEvoked")
        self.verticalLayout_4.addWidget(self.pushButtonCreateEvoked)
        self.pushButtonCreateEvokedBatch = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButtonCreateEvokedBatch.setObjectName("pushButtonCreateEvokedBatch")
        self.verticalLayout_4.addWidget(self.pushButtonCreateEvokedBatch)
        self.widgetBatchContainer = QtWidgets.QWidget(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetBatchContainer.sizePolicy().hasHeightForWidth())
        self.widgetBatchContainer.setSizePolicy(sizePolicy)
        self.widgetBatchContainer.setObjectName("widgetBatchContainer")
        self.verticalLayout_4.addWidget(self.widgetBatchContainer)
        self.gridLayout_16.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBoxEvokeds2 = QtWidgets.QGroupBox(self.layoutWidget_2)
        self.groupBoxEvokeds2.setMinimumSize(QtCore.QSize(0, 300))
        self.groupBoxEvokeds2.setObjectName("groupBoxEvokeds2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxEvokeds2)
        self.gridLayout.setObjectName("gridLayout")
        self.labelEvokedInfo = QtWidgets.QLabel(self.groupBoxEvokeds2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelEvokedInfo.setFont(font)
        self.labelEvokedInfo.setObjectName("labelEvokedInfo")
        self.gridLayout.addWidget(self.labelEvokedInfo, 1, 0, 1, 1)
        self.listWidgetEvoked = QtWidgets.QListWidget(self.groupBoxEvokeds2)
        self.listWidgetEvoked.setObjectName("listWidgetEvoked")
        self.gridLayout.addWidget(self.listWidgetEvoked, 0, 0, 1, 1)
        self.textBrowserEvokedInfo = QtWidgets.QTextBrowser(self.groupBoxEvokeds2)
        self.textBrowserEvokedInfo.setObjectName("textBrowserEvokedInfo")
        self.gridLayout.addWidget(self.textBrowserEvokedInfo, 2, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBoxEvokeds2)
        self.groupBoxEvokedActions = QtWidgets.QGroupBox(self.layoutWidget_2)
        self.groupBoxEvokedActions.setObjectName("groupBoxEvokedActions")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxEvokedActions)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayoutEvokedActions = QtWidgets.QGridLayout()
        self.gridLayoutEvokedActions.setObjectName("gridLayoutEvokedActions")
        self.pushButtonDeleteEvoked = QtWidgets.QPushButton(self.groupBoxEvokedActions)
        self.pushButtonDeleteEvoked.setObjectName("pushButtonDeleteEvoked")
        self.gridLayoutEvokedActions.addWidget(self.pushButtonDeleteEvoked, 1, 0, 1, 1)
        self.pushButtonGroupDeleteEvoked = QtWidgets.QPushButton(self.groupBoxEvokedActions)
        self.pushButtonGroupDeleteEvoked.setObjectName("pushButtonGroupDeleteEvoked")
        self.gridLayoutEvokedActions.addWidget(self.pushButtonGroupDeleteEvoked, 2, 0, 1, 1)
        self.pushButtonGroupAverageEvoked = QtWidgets.QPushButton(self.groupBoxEvokedActions)
        self.pushButtonGroupAverageEvoked.setObjectName("pushButtonGroupAverageEvoked")
        self.gridLayoutEvokedActions.addWidget(self.pushButtonGroupAverageEvoked, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayoutEvokedActions, 0, 0, 1, 1)
        self.groupBoxVizEvoked = QtWidgets.QGroupBox(self.groupBoxEvokedActions)
        self.groupBoxVizEvoked.setObjectName("groupBoxVizEvoked")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBoxVizEvoked)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonVisualizeEvokedDataset = QtWidgets.QPushButton(self.groupBoxVizEvoked)
        self.pushButtonVisualizeEvokedDataset.setObjectName("pushButtonVisualizeEvokedDataset")
        self.horizontalLayout_2.addWidget(self.pushButtonVisualizeEvokedDataset)
        self.pushButtonEvokedTopomaps = QtWidgets.QPushButton(self.groupBoxVizEvoked)
        self.pushButtonEvokedTopomaps.setObjectName("pushButtonEvokedTopomaps")
        self.horizontalLayout_2.addWidget(self.pushButtonEvokedTopomaps)
        self.gridLayout_21.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxVizEvoked, 1, 0, 1, 1)
        self.groupBoxSaveEvoked = QtWidgets.QGroupBox(self.groupBoxEvokedActions)
        self.groupBoxSaveEvoked.setObjectName("groupBoxSaveEvoked")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBoxSaveEvoked)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonSaveEvoked = QtWidgets.QPushButton(self.groupBoxSaveEvoked)
        self.pushButtonSaveEvoked.setObjectName("pushButtonSaveEvoked")
        self.horizontalLayout_3.addWidget(self.pushButtonSaveEvoked)
        self.pushButtonGroupSaveEvoked = QtWidgets.QPushButton(self.groupBoxSaveEvoked)
        self.pushButtonGroupSaveEvoked.setObjectName("pushButtonGroupSaveEvoked")
        self.horizontalLayout_3.addWidget(self.pushButtonGroupSaveEvoked)
        self.gridLayout_20.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxSaveEvoked, 2, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBoxEvokedActions)
        spacerItem1 = QtWidgets.QSpacerItem(20, 400, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.gridLayout_16.addLayout(self.verticalLayout_6, 0, 2, 1, 1)

        self.retranslateUi(mainWindowTabEvoked)
        QtCore.QMetaObject.connectSlotsByName(mainWindowTabEvoked)

    def retranslateUi(self, mainWindowTabEvoked):
        _translate = QtCore.QCoreApplication.translate
        mainWindowTabEvoked.setWindowTitle(_translate("mainWindowTabEvoked", "Form"))
        self.pushButtonCreateEvoked.setText(_translate("mainWindowTabEvoked", "------ Create evoked dataset ----->"))
        self.pushButtonCreateEvokedBatch.setText(_translate("mainWindowTabEvoked", "----------  Batch evokeds --------->"))
        self.groupBoxEvokeds2.setTitle(_translate("mainWindowTabEvoked", "Evoked datasets (averaged epoch collections):"))
        self.labelEvokedInfo.setText(_translate("mainWindowTabEvoked", "Evoked info"))
        self.groupBoxEvokedActions.setTitle(_translate("mainWindowTabEvoked", "Available actions for evoked datasets:"))
        self.pushButtonDeleteEvoked.setText(_translate("mainWindowTabEvoked", "Delete selected dataset"))
        self.pushButtonGroupDeleteEvoked.setText(_translate("mainWindowTabEvoked", "Group delete selected dataset"))
        self.pushButtonGroupAverageEvoked.setText(_translate("mainWindowTabEvoked", "Group average for all subjects"))
        self.groupBoxVizEvoked.setTitle(_translate("mainWindowTabEvoked", "Visualization:"))
        self.pushButtonVisualizeEvokedDataset.setText(_translate("mainWindowTabEvoked", "Visualize selected dataset"))
        self.pushButtonEvokedTopomaps.setText(_translate("mainWindowTabEvoked", "Plot evoked topomaps"))
        self.groupBoxSaveEvoked.setTitle(_translate("mainWindowTabEvoked", "Saving:"))
        self.pushButtonSaveEvoked.setText(_translate("mainWindowTabEvoked", "Save evoked data"))
        self.pushButtonGroupSaveEvoked.setText(_translate("mainWindowTabEvoked", "Group save evoked data"))

