# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowTabEpochsUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindowTabEpochs(object):
    def setupUi(self, mainWindowTabEpochs):
        mainWindowTabEpochs.setObjectName("mainWindowTabEpochs")
        mainWindowTabEpochs.resize(1011, 732)
        self.layoutWidget = QtWidgets.QWidget(mainWindowTabEpochs)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 806, 628))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.verticalLayoutEpochsInfo = QtWidgets.QVBoxLayout()
        self.verticalLayoutEpochsInfo.setObjectName("verticalLayoutEpochsInfo")
        self.labelParameters = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelParameters.setFont(font)
        self.labelParameters.setAlignment(QtCore.Qt.AlignCenter)
        self.labelParameters.setObjectName("labelParameters")
        self.verticalLayoutEpochsInfo.addWidget(self.labelParameters)
        self.groupBoxEpochTimes = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBoxEpochTimes.setObjectName("groupBoxEpochTimes")
        self.formLayout = QtWidgets.QFormLayout(self.groupBoxEpochTimes)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.labelTmin = QtWidgets.QLabel(self.groupBoxEpochTimes)
        self.labelTmin.setMinimumSize(QtCore.QSize(80, 0))
        self.labelTmin.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelTmin.setObjectName("labelTmin")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelTmin)
        self.textBrowserTmin = QtWidgets.QTextBrowser(self.groupBoxEpochTimes)
        self.textBrowserTmin.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserTmin.sizePolicy().hasHeightForWidth())
        self.textBrowserTmin.setSizePolicy(sizePolicy)
        self.textBrowserTmin.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowserTmin.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textBrowserTmin.setSizeIncrement(QtCore.QSize(0, 31))
        self.textBrowserTmin.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserTmin.setPalette(palette)
        self.textBrowserTmin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowserTmin.setObjectName("textBrowserTmin")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textBrowserTmin)
        self.labelTmax = QtWidgets.QLabel(self.groupBoxEpochTimes)
        self.labelTmax.setMinimumSize(QtCore.QSize(80, 0))
        self.labelTmax.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelTmax.setObjectName("labelTmax")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelTmax)
        self.textBrowserTmax = QtWidgets.QTextBrowser(self.groupBoxEpochTimes)
        self.textBrowserTmax.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserTmax.sizePolicy().hasHeightForWidth())
        self.textBrowserTmax.setSizePolicy(sizePolicy)
        self.textBrowserTmax.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowserTmax.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textBrowserTmax.setSizeIncrement(QtCore.QSize(0, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserTmax.setPalette(palette)
        self.textBrowserTmax.setObjectName("textBrowserTmax")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textBrowserTmax)
        self.verticalLayoutEpochsInfo.addWidget(self.groupBoxEpochTimes)
        self.groupBoxRejections = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBoxRejections.setObjectName("groupBoxRejections")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBoxRejections)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.labelMagReject = QtWidgets.QLabel(self.groupBoxRejections)
        self.labelMagReject.setMinimumSize(QtCore.QSize(80, 0))
        self.labelMagReject.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelMagReject.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelMagReject.setObjectName("labelMagReject")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelMagReject)
        self.textBrowserMag = QtWidgets.QTextBrowser(self.groupBoxRejections)
        self.textBrowserMag.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserMag.sizePolicy().hasHeightForWidth())
        self.textBrowserMag.setSizePolicy(sizePolicy)
        self.textBrowserMag.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowserMag.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textBrowserMag.setSizeIncrement(QtCore.QSize(0, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserMag.setPalette(palette)
        self.textBrowserMag.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowserMag.setObjectName("textBrowserMag")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textBrowserMag)
        self.labelGradReject = QtWidgets.QLabel(self.groupBoxRejections)
        self.labelGradReject.setMinimumSize(QtCore.QSize(75, 0))
        self.labelGradReject.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelGradReject.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelGradReject.setObjectName("labelGradReject")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelGradReject)
        self.textBrowserGrad = QtWidgets.QTextBrowser(self.groupBoxRejections)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserGrad.sizePolicy().hasHeightForWidth())
        self.textBrowserGrad.setSizePolicy(sizePolicy)
        self.textBrowserGrad.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowserGrad.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserGrad.setPalette(palette)
        self.textBrowserGrad.setObjectName("textBrowserGrad")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textBrowserGrad)
        self.labelEegReject = QtWidgets.QLabel(self.groupBoxRejections)
        self.labelEegReject.setMinimumSize(QtCore.QSize(75, 0))
        self.labelEegReject.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelEegReject.setObjectName("labelEegReject")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelEegReject)
        self.textBrowserEEG = QtWidgets.QTextBrowser(self.groupBoxRejections)
        self.textBrowserEEG.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserEEG.setPalette(palette)
        self.textBrowserEEG.setObjectName("textBrowserEEG")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textBrowserEEG)
        self.labelEogReject = QtWidgets.QLabel(self.groupBoxRejections)
        self.labelEogReject.setMinimumSize(QtCore.QSize(75, 0))
        self.labelEogReject.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelEogReject.setObjectName("labelEogReject")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelEogReject)
        self.textBrowserEOG = QtWidgets.QTextBrowser(self.groupBoxRejections)
        self.textBrowserEOG.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserEOG.setPalette(palette)
        self.textBrowserEOG.setObjectName("textBrowserEOG")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.textBrowserEOG)
        self.labelStimReject = QtWidgets.QLabel(self.groupBoxRejections)
        self.labelStimReject.setMinimumSize(QtCore.QSize(75, 0))
        self.labelStimReject.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelStimReject.setObjectName("labelStimReject")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelStimReject)
        self.textBrowserStim = QtWidgets.QTextBrowser(self.groupBoxRejections)
        self.textBrowserStim.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserStim.setPalette(palette)
        self.textBrowserStim.setObjectName("textBrowserStim")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.textBrowserStim)
        self.verticalLayoutEpochsInfo.addWidget(self.groupBoxRejections)
        self.horizontalLayoutSource = QtWidgets.QHBoxLayout()
        self.horizontalLayoutSource.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayoutSource.setObjectName("horizontalLayoutSource")
        self.labelWorkingFile = QtWidgets.QLabel(self.layoutWidget)
        self.labelWorkingFile.setMinimumSize(QtCore.QSize(90, 0))
        self.labelWorkingFile.setMaximumSize(QtCore.QSize(16777215, 6000))
        self.labelWorkingFile.setObjectName("labelWorkingFile")
        self.horizontalLayoutSource.addWidget(self.labelWorkingFile)
        self.textBrowserWorkingFile = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowserWorkingFile.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textBrowserWorkingFile.setPalette(palette)
        self.textBrowserWorkingFile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowserWorkingFile.setObjectName("textBrowserWorkingFile")
        self.horizontalLayoutSource.addWidget(self.textBrowserWorkingFile)
        self.verticalLayoutEpochsInfo.addLayout(self.horizontalLayoutSource)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutEpochsInfo.addItem(spacerItem)
        self.gridLayout_15.addLayout(self.verticalLayoutEpochsInfo, 1, 2, 1, 1)
        self.frameEpochsActions = QtWidgets.QFrame(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameEpochsActions.sizePolicy().hasHeightForWidth())
        self.frameEpochsActions.setSizePolicy(sizePolicy)
        self.frameEpochsActions.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameEpochsActions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameEpochsActions.setObjectName("frameEpochsActions")
        self.formLayout_5 = QtWidgets.QFormLayout(self.frameEpochsActions)
        self.formLayout_5.setObjectName("formLayout_5")
        self.groupBoxEpochCollections = QtWidgets.QGroupBox(self.frameEpochsActions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBoxEpochCollections.sizePolicy().hasHeightForWidth())
        self.groupBoxEpochCollections.setSizePolicy(sizePolicy)
        self.groupBoxEpochCollections.setMinimumSize(QtCore.QSize(400, 300))
        self.groupBoxEpochCollections.setTitle("")
        self.groupBoxEpochCollections.setFlat(False)
        self.groupBoxEpochCollections.setObjectName("groupBoxEpochCollections")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxEpochCollections)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.groupBoxEpochCollections)
        self.groupBoxEpochsManage = QtWidgets.QGroupBox(self.frameEpochsActions)
        self.groupBoxEpochsManage.setObjectName("groupBoxEpochsManage")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.groupBoxEpochsManage)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.pushButtonCreateEpochs = QtWidgets.QPushButton(self.groupBoxEpochsManage)
        self.pushButtonCreateEpochs.setObjectName("pushButtonCreateEpochs")
        self.gridLayout_27.addWidget(self.pushButtonCreateEpochs, 0, 0, 1, 1)
        self.pushButtonDeleteEpochs = QtWidgets.QPushButton(self.groupBoxEpochsManage)
        self.pushButtonDeleteEpochs.setObjectName("pushButtonDeleteEpochs")
        self.gridLayout_27.addWidget(self.pushButtonDeleteEpochs, 1, 0, 1, 1)
        self.pushButtonGroupDeleteEpochs = QtWidgets.QPushButton(self.groupBoxEpochsManage)
        self.pushButtonGroupDeleteEpochs.setObjectName("pushButtonGroupDeleteEpochs")
        self.gridLayout_27.addWidget(self.pushButtonGroupDeleteEpochs, 2, 0, 1, 1)
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.groupBoxEpochsManage)
        self.groupBoxEpochsAnalysis = QtWidgets.QGroupBox(self.frameEpochsActions)
        self.groupBoxEpochsAnalysis.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBoxEpochsAnalysis.setMaximumSize(QtCore.QSize(500, 240))
        self.groupBoxEpochsAnalysis.setObjectName("groupBoxEpochsAnalysis")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.groupBoxEpochsAnalysis)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButtonVisualizeEpochChannels = QtWidgets.QPushButton(self.groupBoxEpochsAnalysis)
        self.pushButtonVisualizeEpochChannels.setObjectName("pushButtonVisualizeEpochChannels")
        self.horizontalLayout_17.addWidget(self.pushButtonVisualizeEpochChannels)
        self.pushButtonEpochsPlot = QtWidgets.QPushButton(self.groupBoxEpochsAnalysis)
        self.pushButtonEpochsPlot.setObjectName("pushButtonEpochsPlot")
        self.horizontalLayout_17.addWidget(self.pushButtonEpochsPlot)
        self.gridLayout_28.addLayout(self.horizontalLayout_17, 0, 0, 1, 1)
        self.groupBoxChannelAverages = QtWidgets.QGroupBox(self.groupBoxEpochsAnalysis)
        self.groupBoxChannelAverages.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBoxChannelAverages.setObjectName("groupBoxChannelAverages")
        self.formLayout_22 = QtWidgets.QFormLayout(self.groupBoxChannelAverages)
        self.formLayout_22.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_22.setObjectName("formLayout_22")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.labelLobes = QtWidgets.QLabel(self.groupBoxChannelAverages)
        self.labelLobes.setObjectName("labelLobes")
        self.horizontalLayout_43.addWidget(self.labelLobes)
        self.comboBoxLobes = QtWidgets.QComboBox(self.groupBoxChannelAverages)
        self.comboBoxLobes.setObjectName("comboBoxLobes")
        self.horizontalLayout_43.addWidget(self.comboBoxLobes)
        self.verticalLayout_35.addLayout(self.horizontalLayout_43)
        self.pushButtonChannelAverages = QtWidgets.QPushButton(self.groupBoxChannelAverages)
        self.pushButtonChannelAverages.setObjectName("pushButtonChannelAverages")
        self.verticalLayout_35.addWidget(self.pushButtonChannelAverages)
        self.formLayout_22.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_35)
        self.gridLayout_28.addWidget(self.groupBoxChannelAverages, 1, 0, 1, 1)
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.groupBoxEpochsAnalysis)
        self.gridLayout_15.addWidget(self.frameEpochsActions, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem1, 1, 1, 1, 1)

        self.retranslateUi(mainWindowTabEpochs)
        QtCore.QMetaObject.connectSlotsByName(mainWindowTabEpochs)

    def retranslateUi(self, mainWindowTabEpochs):
        _translate = QtCore.QCoreApplication.translate
        mainWindowTabEpochs.setWindowTitle(_translate("mainWindowTabEpochs", "Form"))
        self.labelParameters.setText(_translate("mainWindowTabEpochs", "Parameters of the selected epoch collection:"))
        self.groupBoxEpochTimes.setTitle(_translate("mainWindowTabEpochs", "Time limits:"))
        self.labelTmin.setText(_translate("mainWindowTabEpochs", "Start time:"))
        self.labelTmax.setText(_translate("mainWindowTabEpochs", "End time:"))
        self.groupBoxRejections.setTitle(_translate("mainWindowTabEpochs", "Rejection parameters:"))
        self.labelMagReject.setText(_translate("mainWindowTabEpochs", "Mag:"))
        self.labelGradReject.setText(_translate("mainWindowTabEpochs", "Grad:"))
        self.labelEegReject.setText(_translate("mainWindowTabEpochs", "EEG:"))
        self.labelEogReject.setText(_translate("mainWindowTabEpochs", "EOG:"))
        self.labelStimReject.setText(_translate("mainWindowTabEpochs", "Stim:"))
        self.labelWorkingFile.setText(_translate("mainWindowTabEpochs", "Source file:"))
        self.groupBoxEpochsManage.setTitle(_translate("mainWindowTabEpochs", "Available actions for epoch collections:"))
        self.pushButtonCreateEpochs.setText(_translate("mainWindowTabEpochs", "Create new collection..."))
        self.pushButtonDeleteEpochs.setText(_translate("mainWindowTabEpochs", "Delete selected collection"))
        self.pushButtonGroupDeleteEpochs.setText(_translate("mainWindowTabEpochs", "Group delete selected collection"))
        self.groupBoxEpochsAnalysis.setTitle(_translate("mainWindowTabEpochs", "Visualization for epoch collections:"))
        self.pushButtonVisualizeEpochChannels.setText(_translate("mainWindowTabEpochs", "Visualize epochs in selected channels..."))
        self.pushButtonEpochsPlot.setText(_translate("mainWindowTabEpochs", "Epochs plot"))
        self.groupBoxChannelAverages.setTitle(_translate("mainWindowTabEpochs", "Channel Averages"))
        self.labelLobes.setText(_translate("mainWindowTabEpochs", "Lobe:"))
        self.pushButtonChannelAverages.setText(_translate("mainWindowTabEpochs", "Show channel averages"))

