# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../powerSpectrumDialogUi.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PowerSpectrumDialog(object):
    def setupUi(self, PowerSpectrumDialog):
        PowerSpectrumDialog.setObjectName("PowerSpectrumDialog")
        PowerSpectrumDialog.resize(724, 665)
        self.gridLayout = QtWidgets.QGridLayout(PowerSpectrumDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(PowerSpectrumDialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 702, 603))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(700, 540))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.groupBoxConditions = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxConditions.setGeometry(QtCore.QRect(10, 70, 681, 191))
        self.groupBoxConditions.setObjectName("groupBoxConditions")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxConditions)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.labelFmin = QtWidgets.QLabel(self.groupBoxConditions)
        self.labelFmin.setObjectName("labelFmin")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelFmin)
        self.spinBoxFmin = QtWidgets.QSpinBox(self.groupBoxConditions)
        self.spinBoxFmin.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBoxFmin.setMaximum(1000)
        self.spinBoxFmin.setProperty("value", 1)
        self.spinBoxFmin.setObjectName("spinBoxFmin")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBoxFmin)
        self.labelFmax = QtWidgets.QLabel(self.groupBoxConditions)
        self.labelFmax.setObjectName("labelFmax")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelFmax)
        self.spinBoxFmax = QtWidgets.QSpinBox(self.groupBoxConditions)
        self.spinBoxFmax.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBoxFmax.setMaximum(1000)
        self.spinBoxFmax.setProperty("value", 40)
        self.spinBoxFmax.setObjectName("spinBoxFmax")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBoxFmax)
        self.horizontalLayout_5.addLayout(self.formLayout_2)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName("formLayout_6")
        self.labelNfft = QtWidgets.QLabel(self.groupBoxConditions)
        self.labelNfft.setObjectName("labelNfft")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelNfft)
        self.spinBoxNfft = QtWidgets.QSpinBox(self.groupBoxConditions)
        self.spinBoxNfft.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBoxNfft.setMaximum(10000)
        self.spinBoxNfft.setProperty("value", 512)
        self.spinBoxNfft.setObjectName("spinBoxNfft")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBoxNfft)
        self.labelOverlap = QtWidgets.QLabel(self.groupBoxConditions)
        self.labelOverlap.setObjectName("labelOverlap")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelOverlap)
        self.spinBoxOverlap = QtWidgets.QSpinBox(self.groupBoxConditions)
        self.spinBoxOverlap.setMaximum(10000)
        self.spinBoxOverlap.setProperty("value", 256)
        self.spinBoxOverlap.setObjectName("spinBoxOverlap")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBoxOverlap)
        self.checkBoxLogarithm = QtWidgets.QCheckBox(self.groupBoxConditions)
        self.checkBoxLogarithm.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxLogarithm.setAutoFillBackground(False)
        self.checkBoxLogarithm.setChecked(True)
        self.checkBoxLogarithm.setObjectName("checkBoxLogarithm")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBoxLogarithm)
        self.horizontalLayout_5.addLayout(self.formLayout_6)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 270, 671, 321))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBoxIntervals = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxIntervals.sizePolicy().hasHeightForWidth())
        self.groupBoxIntervals.setSizePolicy(sizePolicy)
        self.groupBoxIntervals.setMaximumSize(QtCore.QSize(260, 16777215))
        self.groupBoxIntervals.setObjectName("groupBoxIntervals")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBoxIntervals)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 235, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelGroup = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelGroup.setObjectName("labelGroup")
        self.horizontalLayout.addWidget(self.labelGroup)
        self.comboBoxAvgGroup = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBoxAvgGroup.setObjectName("comboBoxAvgGroup")
        self.comboBoxAvgGroup.addItem("")
        self.comboBoxAvgGroup.addItem("")
        self.comboBoxAvgGroup.addItem("")
        self.comboBoxAvgGroup.addItem("")
        self.comboBoxAvgGroup.addItem("")
        self.comboBoxAvgGroup.addItem("")
        self.comboBoxAvgGroup.addItem("")
        self.comboBoxAvgGroup.addItem("")
        self.horizontalLayout.addWidget(self.comboBoxAvgGroup)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelTmin = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelTmin.setObjectName("labelTmin")
        self.horizontalLayout_4.addWidget(self.labelTmin)
        self.doubleSpinBoxTmin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.doubleSpinBoxTmin.setMaximum(1000000000.0)
        self.doubleSpinBoxTmin.setObjectName("doubleSpinBoxTmin")
        self.horizontalLayout_4.addWidget(self.doubleSpinBoxTmin)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelTmax = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelTmax.setObjectName("labelTmax")
        self.horizontalLayout_6.addWidget(self.labelTmax)
        self.doubleSpinBoxTmax = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.doubleSpinBoxTmax.setMaximum(1000000000.0)
        self.doubleSpinBoxTmax.setObjectName("doubleSpinBoxTmax")
        self.horizontalLayout_6.addWidget(self.doubleSpinBoxTmax)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.pushButtonAdd = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.verticalLayout.addWidget(self.pushButtonAdd)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.pushButtonAddEvents = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButtonAddEvents.setObjectName("pushButtonAddEvents")
        self.verticalLayout.addWidget(self.pushButtonAddEvents)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.pushButtonClearRow = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButtonClearRow.setObjectName("pushButtonClearRow")
        self.verticalLayout.addWidget(self.pushButtonClearRow)
        self.pushButtonClear = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.verticalLayout.addWidget(self.pushButtonClear)
        self.horizontalLayout_3.addWidget(self.groupBoxIntervals)
        self.listWidgetIntervals = QtWidgets.QListWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetIntervals.sizePolicy().hasHeightForWidth())
        self.listWidgetIntervals.setSizePolicy(sizePolicy)
        self.listWidgetIntervals.setObjectName("listWidgetIntervals")
        self.horizontalLayout_3.addWidget(self.listWidgetIntervals)
        self.groupBoxGeneral = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxGeneral.setGeometry(QtCore.QRect(10, 0, 681, 52))
        self.groupBoxGeneral.setObjectName("groupBoxGeneral")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxGeneral)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelName = QtWidgets.QLabel(self.groupBoxGeneral)
        self.labelName.setObjectName("labelName")
        self.gridLayout_3.addWidget(self.labelName, 0, 0, 1, 1)
        self.lineEditName = QtWidgets.QLineEdit(self.groupBoxGeneral)
        self.lineEditName.setObjectName("lineEditName")
        self.gridLayout_3.addWidget(self.lineEditName, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(PowerSpectrumDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.NoButton)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButtonReject = QtWidgets.QPushButton(PowerSpectrumDialog)
        self.pushButtonReject.setObjectName("pushButtonReject")
        self.horizontalLayout_2.addWidget(self.pushButtonReject)
        self.pushButtonAccept = QtWidgets.QPushButton(PowerSpectrumDialog)
        self.pushButtonAccept.setObjectName("pushButtonAccept")
        self.horizontalLayout_2.addWidget(self.pushButtonAccept)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)

        self.retranslateUi(PowerSpectrumDialog)
        self.pushButtonAccept.clicked.connect(PowerSpectrumDialog.accept)
        self.pushButtonReject.clicked.connect(PowerSpectrumDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PowerSpectrumDialog)

    def retranslateUi(self, PowerSpectrumDialog):
        _translate = QtCore.QCoreApplication.translate
        PowerSpectrumDialog.setWindowTitle(_translate("PowerSpectrumDialog", "Power spectrum"))
        self.groupBoxConditions.setTitle(_translate("PowerSpectrumDialog", "Conditions"))
        self.labelFmin.setToolTip(_translate("PowerSpectrumDialog", "Set the lower limit for the frequencies."))
        self.labelFmin.setText(_translate("PowerSpectrumDialog", "Min frequency of interest:"))
        self.spinBoxFmin.setToolTip(_translate("PowerSpectrumDialog", "Set the lower limit for the frequencies."))
        self.spinBoxFmin.setSuffix(_translate("PowerSpectrumDialog", "Hz"))
        self.labelFmax.setToolTip(_translate("PowerSpectrumDialog", "Set the upper limit for the frequencies."))
        self.labelFmax.setText(_translate("PowerSpectrumDialog", "Max frequency of interest:"))
        self.spinBoxFmax.setToolTip(_translate("PowerSpectrumDialog", "Set the upper limit for the frequencies."))
        self.spinBoxFmax.setSuffix(_translate("PowerSpectrumDialog", "Hz"))
        self.labelNfft.setToolTip(_translate("PowerSpectrumDialog", "<html><head/><body><p>The length of the tapers ie. the windows (hanning). The smaller it is the smoother are the PSDs.</p></body></html>"))
        self.labelNfft.setText(_translate("PowerSpectrumDialog", "Length of the tapers (ie. the windows):"))
        self.spinBoxNfft.setToolTip(_translate("PowerSpectrumDialog", "<html><head/><body><p>The length of the tapers ie. the windows (hanning). The smaller it is the smoother are the PSDs.</p></body></html>"))
        self.labelOverlap.setToolTip(_translate("PowerSpectrumDialog", "<html><head/><body><p>Number of overlapping points between the blocks.</p></body></html>"))
        self.labelOverlap.setText(_translate("PowerSpectrumDialog", "Overlap"))
        self.spinBoxOverlap.setToolTip(_translate("PowerSpectrumDialog", "<html><head/><body><p>Number of overlapping points between the blocks.</p></body></html>"))
        self.checkBoxLogarithm.setToolTip(_translate("PowerSpectrumDialog", "Use logarithmic scale."))
        self.checkBoxLogarithm.setText(_translate("PowerSpectrumDialog", "Use logarithmic scale"))
        self.groupBoxIntervals.setTitle(_translate("PowerSpectrumDialog", "Select time intervals"))
        self.labelGroup.setText(_translate("PowerSpectrumDialog", "Average group:"))
        self.comboBoxAvgGroup.setItemText(0, _translate("PowerSpectrumDialog", "1"))
        self.comboBoxAvgGroup.setItemText(1, _translate("PowerSpectrumDialog", "2"))
        self.comboBoxAvgGroup.setItemText(2, _translate("PowerSpectrumDialog", "3"))
        self.comboBoxAvgGroup.setItemText(3, _translate("PowerSpectrumDialog", "4"))
        self.comboBoxAvgGroup.setItemText(4, _translate("PowerSpectrumDialog", "5"))
        self.comboBoxAvgGroup.setItemText(5, _translate("PowerSpectrumDialog", "6"))
        self.comboBoxAvgGroup.setItemText(6, _translate("PowerSpectrumDialog", "7"))
        self.comboBoxAvgGroup.setItemText(7, _translate("PowerSpectrumDialog", "8"))
        self.labelTmin.setText(_translate("PowerSpectrumDialog", "Start time:"))
        self.doubleSpinBoxTmin.setSuffix(_translate("PowerSpectrumDialog", " s"))
        self.labelTmax.setText(_translate("PowerSpectrumDialog", "End time:"))
        self.doubleSpinBoxTmax.setSuffix(_translate("PowerSpectrumDialog", " s"))
        self.pushButtonAdd.setText(_translate("PowerSpectrumDialog", "Add to list >>"))
        self.pushButtonAddEvents.setText(_translate("PowerSpectrumDialog", "Add from events... >>"))
        self.pushButtonClearRow.setText(_translate("PowerSpectrumDialog", "Clear row <<"))
        self.pushButtonClear.setText(_translate("PowerSpectrumDialog", "Clear list <<"))
        self.groupBoxGeneral.setTitle(_translate("PowerSpectrumDialog", "General"))
        self.labelName.setText(_translate("PowerSpectrumDialog", "Spectrum name:"))
        self.pushButtonReject.setText(_translate("PowerSpectrumDialog", "Cancel"))
        self.pushButtonAccept.setText(_translate("PowerSpectrumDialog", "Start"))

