# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TFRDialogUi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TFRDialog(object):
    def setupUi(self, TFRDialog):
        TFRDialog.setObjectName(_fromUtf8("TFRDialog"))
        TFRDialog.resize(576, 482)
        self.gridLayout_2 = QtGui.QGridLayout(TFRDialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(TFRDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(TFRDialog)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 558, 423))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_4 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBoxMisc = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxMisc.setObjectName(_fromUtf8("groupBoxMisc"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBoxMisc)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.spinBoxDecim = QtGui.QSpinBox(self.groupBoxMisc)
        self.spinBoxDecim.setProperty("value", 2)
        self.spinBoxDecim.setObjectName(_fromUtf8("spinBoxDecim"))
        self.gridLayout_10.addWidget(self.spinBoxDecim, 0, 1, 1, 1)
        self.labelDecim = QtGui.QLabel(self.groupBoxMisc)
        self.labelDecim.setObjectName(_fromUtf8("labelDecim"))
        self.gridLayout_10.addWidget(self.labelDecim, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_10, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelSubtractEvoked = QtGui.QLabel(self.groupBoxMisc)
        self.labelSubtractEvoked.setObjectName(_fromUtf8("labelSubtractEvoked"))
        self.horizontalLayout.addWidget(self.labelSubtractEvoked)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.checkBoxSubtractEvoked = QtGui.QCheckBox(self.groupBoxMisc)
        self.checkBoxSubtractEvoked.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBoxSubtractEvoked.setText(_fromUtf8(""))
        self.checkBoxSubtractEvoked.setObjectName(_fromUtf8("checkBoxSubtractEvoked"))
        self.horizontalLayout.addWidget(self.checkBoxSubtractEvoked)
        self.gridLayout_9.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxMisc, 4, 0, 1, 1)
        self.groupBoxFrequencies = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBoxFrequencies.sizePolicy().hasHeightForWidth())
        self.groupBoxFrequencies.setSizePolicy(sizePolicy)
        self.groupBoxFrequencies.setObjectName(_fromUtf8("groupBoxFrequencies"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBoxFrequencies)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelMinFreq = QtGui.QLabel(self.groupBoxFrequencies)
        self.labelMinFreq.setObjectName(_fromUtf8("labelMinFreq"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelMinFreq)
        self.doubleSpinBoxMinFreq = QtGui.QDoubleSpinBox(self.groupBoxFrequencies)
        self.doubleSpinBoxMinFreq.setMinimum(0.0)
        self.doubleSpinBoxMinFreq.setMaximum(1000.0)
        self.doubleSpinBoxMinFreq.setProperty("value", 4.0)
        self.doubleSpinBoxMinFreq.setObjectName(_fromUtf8("doubleSpinBoxMinFreq"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxMinFreq)
        self.labelMaxFreq = QtGui.QLabel(self.groupBoxFrequencies)
        self.labelMaxFreq.setObjectName(_fromUtf8("labelMaxFreq"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelMaxFreq)
        self.doubleSpinBoxMaxFreq = QtGui.QDoubleSpinBox(self.groupBoxFrequencies)
        self.doubleSpinBoxMaxFreq.setMinimum(0.0)
        self.doubleSpinBoxMaxFreq.setMaximum(1000.0)
        self.doubleSpinBoxMaxFreq.setProperty("value", 40.0)
        self.doubleSpinBoxMaxFreq.setObjectName(_fromUtf8("doubleSpinBoxMaxFreq"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxMaxFreq)
        self.labelFrequencyInterval = QtGui.QLabel(self.groupBoxFrequencies)
        self.labelFrequencyInterval.setObjectName(_fromUtf8("labelFrequencyInterval"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelFrequencyInterval)
        self.doubleSpinBoxFreqInterval = QtGui.QDoubleSpinBox(self.groupBoxFrequencies)
        self.doubleSpinBoxFreqInterval.setMinimum(0.1)
        self.doubleSpinBoxFreqInterval.setMaximum(99.99)
        self.doubleSpinBoxFreqInterval.setProperty("value", 2.0)
        self.doubleSpinBoxFreqInterval.setObjectName(_fromUtf8("doubleSpinBoxFreqInterval"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxFreqInterval)
        self.label_7 = QtGui.QLabel(self.groupBoxFrequencies)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.radioButtonFixed = QtGui.QRadioButton(self.groupBoxFrequencies)
        self.radioButtonFixed.setChecked(True)
        self.radioButtonFixed.setObjectName(_fromUtf8("radioButtonFixed"))
        self.horizontalLayout_18.addWidget(self.radioButtonFixed)
        self.formLayout.setLayout(4, QtGui.QFormLayout.LabelRole, self.horizontalLayout_18)
        self.doubleSpinBoxNcycles = QtGui.QDoubleSpinBox(self.groupBoxFrequencies)
        self.doubleSpinBoxNcycles.setEnabled(True)
        self.doubleSpinBoxNcycles.setMinimum(1.0)
        self.doubleSpinBoxNcycles.setMaximum(100.0)
        self.doubleSpinBoxNcycles.setProperty("value", 5.0)
        self.doubleSpinBoxNcycles.setObjectName(_fromUtf8("doubleSpinBoxNcycles"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxNcycles)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.radioButtonAdapted = QtGui.QRadioButton(self.groupBoxFrequencies)
        self.radioButtonAdapted.setToolTip(_fromUtf8(""))
        self.radioButtonAdapted.setChecked(False)
        self.radioButtonAdapted.setObjectName(_fromUtf8("radioButtonAdapted"))
        self.horizontalLayout_19.addWidget(self.radioButtonAdapted)
        self.formLayout.setLayout(5, QtGui.QFormLayout.LabelRole, self.horizontalLayout_19)
        self.doubleSpinBoxCycleFactor = QtGui.QDoubleSpinBox(self.groupBoxFrequencies)
        self.doubleSpinBoxCycleFactor.setEnabled(False)
        self.doubleSpinBoxCycleFactor.setToolTip(_fromUtf8(""))
        self.doubleSpinBoxCycleFactor.setMinimum(1.0)
        self.doubleSpinBoxCycleFactor.setMaximum(10.0)
        self.doubleSpinBoxCycleFactor.setSingleStep(1.0)
        self.doubleSpinBoxCycleFactor.setProperty("value", 2.0)
        self.doubleSpinBoxCycleFactor.setObjectName(_fromUtf8("doubleSpinBoxCycleFactor"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxCycleFactor)
        self.gridLayout_5.addLayout(self.formLayout, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxFrequencies, 3, 0, 1, 2)
        self.groupBoxGeneral = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxGeneral.setObjectName(_fromUtf8("groupBoxGeneral"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBoxGeneral)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.labelEpochName = QtGui.QLabel(self.groupBoxGeneral)
        self.labelEpochName.setObjectName(_fromUtf8("labelEpochName"))
        self.gridLayout_6.addWidget(self.labelEpochName, 1, 0, 1, 1)
        self.lineEditEpochName = QtGui.QLineEdit(self.groupBoxGeneral)
        self.lineEditEpochName.setEnabled(False)
        self.lineEditEpochName.setObjectName(_fromUtf8("lineEditEpochName"))
        self.gridLayout_6.addWidget(self.lineEditEpochName, 1, 1, 1, 1)
        self.labelTFRName = QtGui.QLabel(self.groupBoxGeneral)
        self.labelTFRName.setObjectName(_fromUtf8("labelTFRName"))
        self.gridLayout_6.addWidget(self.labelTFRName, 2, 0, 1, 1)
        self.lineEditTFRName = QtGui.QLineEdit(self.groupBoxGeneral)
        self.lineEditTFRName.setObjectName(_fromUtf8("lineEditTFRName"))
        self.gridLayout_6.addWidget(self.lineEditTFRName, 2, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxGeneral, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(TFRDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), TFRDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), TFRDialog.reject)
        QtCore.QObject.connect(self.radioButtonAdapted, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBoxCycleFactor.setEnabled)
        QtCore.QObject.connect(self.radioButtonFixed, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBoxNcycles.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(TFRDialog)
        TFRDialog.setTabOrder(self.scrollArea, self.radioButtonFixed)
        TFRDialog.setTabOrder(self.radioButtonFixed, self.radioButtonAdapted)
        TFRDialog.setTabOrder(self.radioButtonAdapted, self.buttonBox)

    def retranslateUi(self, TFRDialog):
        TFRDialog.setWindowTitle(_translate("TFRDialog", "Meggie - Compute TFR", None))
        self.groupBoxMisc.setTitle(_translate("TFRDialog", "Miscellaneous", None))
        self.labelDecim.setText(_translate("TFRDialog", "Decimation factor:", None))
        self.labelSubtractEvoked.setText(_translate("TFRDialog", "Subtract evoked:", None))
        self.groupBoxFrequencies.setTitle(_translate("TFRDialog", "Frequency window", None))
        self.labelMinFreq.setText(_translate("TFRDialog", "Min frequency:", None))
        self.doubleSpinBoxMinFreq.setSuffix(_translate("TFRDialog", "Hz", None))
        self.labelMaxFreq.setText(_translate("TFRDialog", "Max frequency:", None))
        self.doubleSpinBoxMaxFreq.setSuffix(_translate("TFRDialog", "Hz", None))
        self.labelFrequencyInterval.setText(_translate("TFRDialog", "Frequency interval:", None))
        self.doubleSpinBoxFreqInterval.setSuffix(_translate("TFRDialog", "Hz", None))
        self.label_7.setText(_translate("TFRDialog", "Number of cycles", None))
        self.radioButtonFixed.setText(_translate("TFRDialog", "Fixed", None))
        self.radioButtonAdapted.setText(_translate("TFRDialog", "Freqs divided by", None))
        self.groupBoxGeneral.setTitle(_translate("TFRDialog", "General:", None))
        self.labelEpochName.setText(_translate("TFRDialog", "Epoch name: ", None))
        self.labelTFRName.setText(_translate("TFRDialog", "TFR name:", None))

