# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TFRDialogUi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TFRDialog(object):
    def setupUi(self, TFRDialog):
        TFRDialog.setObjectName(_fromUtf8("TFRDialog"))
        TFRDialog.resize(611, 601)
        self.gridLayout_2 = QtGui.QGridLayout(TFRDialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(TFRDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(TFRDialog)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 593, 542))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_4 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBoxBaseline = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxBaseline.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBoxBaseline.sizePolicy().hasHeightForWidth())
        self.groupBoxBaseline.setSizePolicy(sizePolicy)
        self.groupBoxBaseline.setCheckable(True)
        self.groupBoxBaseline.setChecked(True)
        self.groupBoxBaseline.setObjectName(_fromUtf8("groupBoxBaseline"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxBaseline)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.labelRescaling = QtGui.QLabel(self.groupBoxBaseline)
        self.labelRescaling.setObjectName(_fromUtf8("labelRescaling"))
        self.gridLayout_7.addWidget(self.labelRescaling, 0, 0, 1, 1)
        self.labelBaselineStart = QtGui.QLabel(self.groupBoxBaseline)
        self.labelBaselineStart.setEnabled(True)
        self.labelBaselineStart.setObjectName(_fromUtf8("labelBaselineStart"))
        self.gridLayout_7.addWidget(self.labelBaselineStart, 1, 0, 1, 1)
        self.comboBoxMode = QtGui.QComboBox(self.groupBoxBaseline)
        self.comboBoxMode.setObjectName(_fromUtf8("comboBoxMode"))
        self.comboBoxMode.addItem(_fromUtf8(""))
        self.comboBoxMode.addItem(_fromUtf8(""))
        self.comboBoxMode.addItem(_fromUtf8(""))
        self.comboBoxMode.addItem(_fromUtf8(""))
        self.comboBoxMode.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.comboBoxMode, 0, 1, 1, 1)
        self.doubleSpinBoxBaselineStart = QtGui.QDoubleSpinBox(self.groupBoxBaseline)
        self.doubleSpinBoxBaselineStart.setEnabled(True)
        self.doubleSpinBoxBaselineStart.setDecimals(3)
        self.doubleSpinBoxBaselineStart.setSingleStep(0.05)
        self.doubleSpinBoxBaselineStart.setObjectName(_fromUtf8("doubleSpinBoxBaselineStart"))
        self.gridLayout_7.addWidget(self.doubleSpinBoxBaselineStart, 1, 1, 1, 1)
        self.labelBaselineEnd = QtGui.QLabel(self.groupBoxBaseline)
        self.labelBaselineEnd.setEnabled(True)
        self.labelBaselineEnd.setObjectName(_fromUtf8("labelBaselineEnd"))
        self.gridLayout_7.addWidget(self.labelBaselineEnd, 2, 0, 1, 1)
        self.doubleSpinBoxBaselineEnd = QtGui.QDoubleSpinBox(self.groupBoxBaseline)
        self.doubleSpinBoxBaselineEnd.setEnabled(True)
        self.doubleSpinBoxBaselineEnd.setDecimals(3)
        self.doubleSpinBoxBaselineEnd.setSingleStep(0.05)
        self.doubleSpinBoxBaselineEnd.setObjectName(_fromUtf8("doubleSpinBoxBaselineEnd"))
        self.gridLayout_7.addWidget(self.doubleSpinBoxBaselineEnd, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_7, 0, 0, 1, 2)
        self.gridLayout_4.addWidget(self.groupBoxBaseline, 4, 0, 1, 2)
        self.groupBoxMisc = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxMisc.setObjectName(_fromUtf8("groupBoxMisc"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBoxMisc)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.spinBoxDecim = QtGui.QSpinBox(self.groupBoxMisc)
        self.spinBoxDecim.setProperty("value", 2)
        self.spinBoxDecim.setObjectName(_fromUtf8("spinBoxDecim"))
        self.gridLayout_10.addWidget(self.spinBoxDecim, 0, 1, 1, 1)
        self.labelDecim = QtGui.QLabel(self.groupBoxMisc)
        self.labelDecim.setObjectName(_fromUtf8("labelDecim"))
        self.gridLayout_10.addWidget(self.labelDecim, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_10, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxMisc, 5, 0, 1, 1)
        self.groupBoxFrequencies = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBoxFrequencies.sizePolicy().hasHeightForWidth())
        self.groupBoxFrequencies.setSizePolicy(sizePolicy)
        self.groupBoxFrequencies.setObjectName(_fromUtf8("groupBoxFrequencies"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBoxFrequencies)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.doubleSpinBoxNcycles = QtGui.QDoubleSpinBox(self.groupBoxFrequencies)
        self.doubleSpinBoxNcycles.setEnabled(True)
        self.doubleSpinBoxNcycles.setMinimum(1.0)
        self.doubleSpinBoxNcycles.setMaximum(100.0)
        self.doubleSpinBoxNcycles.setProperty("value", 5.0)
        self.doubleSpinBoxNcycles.setObjectName(_fromUtf8("doubleSpinBoxNcycles"))
        self.gridLayout_8.addWidget(self.doubleSpinBoxNcycles, 6, 1, 1, 1)
        self.doubleSpinBoxCycleFactor = QtGui.QDoubleSpinBox(self.groupBoxFrequencies)
        self.doubleSpinBoxCycleFactor.setEnabled(False)
        self.doubleSpinBoxCycleFactor.setToolTip(_fromUtf8(""))
        self.doubleSpinBoxCycleFactor.setMinimum(1.0)
        self.doubleSpinBoxCycleFactor.setMaximum(10.0)
        self.doubleSpinBoxCycleFactor.setSingleStep(1.0)
        self.doubleSpinBoxCycleFactor.setProperty("value", 2.0)
        self.doubleSpinBoxCycleFactor.setObjectName(_fromUtf8("doubleSpinBoxCycleFactor"))
        self.gridLayout_8.addWidget(self.doubleSpinBoxCycleFactor, 7, 1, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.radioButtonAdapted = QtGui.QRadioButton(self.groupBoxFrequencies)
        self.radioButtonAdapted.setToolTip(_fromUtf8(""))
        self.radioButtonAdapted.setChecked(False)
        self.radioButtonAdapted.setObjectName(_fromUtf8("radioButtonAdapted"))
        self.horizontalLayout_19.addWidget(self.radioButtonAdapted)
        self.gridLayout_8.addLayout(self.horizontalLayout_19, 7, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBoxFrequencies)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_8.addWidget(self.label_7, 5, 0, 1, 1)
        self.doubleSpinBoxMaxFreq = QtGui.QDoubleSpinBox(self.groupBoxFrequencies)
        self.doubleSpinBoxMaxFreq.setMinimum(0.0)
        self.doubleSpinBoxMaxFreq.setMaximum(1000.0)
        self.doubleSpinBoxMaxFreq.setProperty("value", 40.0)
        self.doubleSpinBoxMaxFreq.setObjectName(_fromUtf8("doubleSpinBoxMaxFreq"))
        self.gridLayout_8.addWidget(self.doubleSpinBoxMaxFreq, 2, 1, 1, 1)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.radioButtonFixed = QtGui.QRadioButton(self.groupBoxFrequencies)
        self.radioButtonFixed.setChecked(True)
        self.radioButtonFixed.setObjectName(_fromUtf8("radioButtonFixed"))
        self.horizontalLayout_18.addWidget(self.radioButtonFixed)
        self.gridLayout_8.addLayout(self.horizontalLayout_18, 6, 0, 1, 1)
        self.doubleSpinBoxFreqInterval = QtGui.QDoubleSpinBox(self.groupBoxFrequencies)
        self.doubleSpinBoxFreqInterval.setMinimum(0.1)
        self.doubleSpinBoxFreqInterval.setMaximum(99.99)
        self.doubleSpinBoxFreqInterval.setProperty("value", 2.0)
        self.doubleSpinBoxFreqInterval.setObjectName(_fromUtf8("doubleSpinBoxFreqInterval"))
        self.gridLayout_8.addWidget(self.doubleSpinBoxFreqInterval, 3, 1, 1, 1)
        self.labelMinFreq = QtGui.QLabel(self.groupBoxFrequencies)
        self.labelMinFreq.setObjectName(_fromUtf8("labelMinFreq"))
        self.gridLayout_8.addWidget(self.labelMinFreq, 1, 0, 1, 1)
        self.labelMaxFreq = QtGui.QLabel(self.groupBoxFrequencies)
        self.labelMaxFreq.setObjectName(_fromUtf8("labelMaxFreq"))
        self.gridLayout_8.addWidget(self.labelMaxFreq, 2, 0, 1, 1)
        self.labelFrequencyInterval = QtGui.QLabel(self.groupBoxFrequencies)
        self.labelFrequencyInterval.setObjectName(_fromUtf8("labelFrequencyInterval"))
        self.gridLayout_8.addWidget(self.labelFrequencyInterval, 3, 0, 1, 1)
        self.doubleSpinBoxMinFreq = QtGui.QDoubleSpinBox(self.groupBoxFrequencies)
        self.doubleSpinBoxMinFreq.setMinimum(0.0)
        self.doubleSpinBoxMinFreq.setMaximum(1000.0)
        self.doubleSpinBoxMinFreq.setProperty("value", 4.0)
        self.doubleSpinBoxMinFreq.setObjectName(_fromUtf8("doubleSpinBoxMinFreq"))
        self.gridLayout_8.addWidget(self.doubleSpinBoxMinFreq, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem, 4, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_8, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxFrequencies, 3, 0, 1, 2)
        self.groupBoxGeneral = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxGeneral.setObjectName(_fromUtf8("groupBoxGeneral"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBoxGeneral)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.labelEpochName = QtGui.QLabel(self.groupBoxGeneral)
        self.labelEpochName.setObjectName(_fromUtf8("labelEpochName"))
        self.gridLayout_6.addWidget(self.labelEpochName, 1, 0, 1, 1)
        self.lineEditEpochName = QtGui.QLineEdit(self.groupBoxGeneral)
        self.lineEditEpochName.setEnabled(False)
        self.lineEditEpochName.setObjectName(_fromUtf8("lineEditEpochName"))
        self.gridLayout_6.addWidget(self.lineEditEpochName, 1, 1, 1, 1)
        self.labelTFRName = QtGui.QLabel(self.groupBoxGeneral)
        self.labelTFRName.setObjectName(_fromUtf8("labelTFRName"))
        self.gridLayout_6.addWidget(self.labelTFRName, 2, 0, 1, 1)
        self.lineEditTFRName = QtGui.QLineEdit(self.groupBoxGeneral)
        self.lineEditTFRName.setObjectName(_fromUtf8("lineEditTFRName"))
        self.gridLayout_6.addWidget(self.lineEditTFRName, 2, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxGeneral, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(TFRDialog)
        self.comboBoxMode.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), TFRDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), TFRDialog.reject)
        QtCore.QObject.connect(self.radioButtonAdapted, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBoxCycleFactor.setEnabled)
        QtCore.QObject.connect(self.radioButtonFixed, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBoxNcycles.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(TFRDialog)
        TFRDialog.setTabOrder(self.scrollArea, self.radioButtonFixed)
        TFRDialog.setTabOrder(self.radioButtonFixed, self.radioButtonAdapted)
        TFRDialog.setTabOrder(self.radioButtonAdapted, self.groupBoxBaseline)
        TFRDialog.setTabOrder(self.groupBoxBaseline, self.buttonBox)

    def retranslateUi(self, TFRDialog):
        TFRDialog.setWindowTitle(_translate("TFRDialog", "Meggie - Compute TFR", None))
        self.groupBoxBaseline.setTitle(_translate("TFRDialog", "Baseline rescaling and correction", None))
        self.labelRescaling.setText(_translate("TFRDialog", "Rescaling mode:", None))
        self.labelBaselineStart.setText(_translate("TFRDialog", "Baseline start:", None))
        self.comboBoxMode.setItemText(0, _translate("TFRDialog", "logratio", None))
        self.comboBoxMode.setItemText(1, _translate("TFRDialog", "ratio", None))
        self.comboBoxMode.setItemText(2, _translate("TFRDialog", "mean", None))
        self.comboBoxMode.setItemText(3, _translate("TFRDialog", "zscore", None))
        self.comboBoxMode.setItemText(4, _translate("TFRDialog", "percent", None))
        self.doubleSpinBoxBaselineStart.setSuffix(_translate("TFRDialog", "s", None))
        self.labelBaselineEnd.setText(_translate("TFRDialog", "Baseline end:", None))
        self.doubleSpinBoxBaselineEnd.setSuffix(_translate("TFRDialog", "s", None))
        self.groupBoxMisc.setTitle(_translate("TFRDialog", "Miscellaneous", None))
        self.labelDecim.setText(_translate("TFRDialog", "Decimation factor:", None))
        self.groupBoxFrequencies.setTitle(_translate("TFRDialog", "Frequency window", None))
        self.radioButtonAdapted.setText(_translate("TFRDialog", "Freqs divided by", None))
        self.label_7.setText(_translate("TFRDialog", "Number of cycles", None))
        self.doubleSpinBoxMaxFreq.setSuffix(_translate("TFRDialog", "Hz", None))
        self.radioButtonFixed.setText(_translate("TFRDialog", "Fixed", None))
        self.doubleSpinBoxFreqInterval.setSuffix(_translate("TFRDialog", "Hz", None))
        self.labelMinFreq.setText(_translate("TFRDialog", "Min frequency:", None))
        self.labelMaxFreq.setText(_translate("TFRDialog", "Max frequency:", None))
        self.labelFrequencyInterval.setText(_translate("TFRDialog", "Frequency interval:", None))
        self.doubleSpinBoxMinFreq.setSuffix(_translate("TFRDialog", "Hz", None))
        self.groupBoxGeneral.setTitle(_translate("TFRDialog", "General:", None))
        self.labelEpochName.setText(_translate("TFRDialog", "Epoch name: ", None))
        self.labelTFRName.setText(_translate("TFRDialog", "TFR name:", None))

