# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TFRfromRawDialogUi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogRawTFR(object):
    def setupUi(self, DialogRawTFR):
        DialogRawTFR.setObjectName(_fromUtf8("DialogRawTFR"))
        DialogRawTFR.resize(495, 503)
        self.gridLayout = QtGui.QGridLayout(DialogRawTFR)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(DialogRawTFR)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(DialogRawTFR)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.comboBoxChannel = QtGui.QComboBox(DialogRawTFR)
        self.comboBoxChannel.setObjectName(_fromUtf8("comboBoxChannel"))
        self.horizontalLayout_5.addWidget(self.comboBoxChannel)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.line_3 = QtGui.QFrame(DialogRawTFR)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(DialogRawTFR)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.spinBoxWsize = QtGui.QSpinBox(DialogRawTFR)
        self.spinBoxWsize.setMaximum(1000000000)
        self.spinBoxWsize.setSingleStep(1)
        self.spinBoxWsize.setProperty("value", 1024)
        self.spinBoxWsize.setObjectName(_fromUtf8("spinBoxWsize"))
        self.horizontalLayout.addWidget(self.spinBoxWsize)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(DialogRawTFR)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.checkBoxTstep = QtGui.QCheckBox(DialogRawTFR)
        self.checkBoxTstep.setChecked(True)
        self.checkBoxTstep.setObjectName(_fromUtf8("checkBoxTstep"))
        self.verticalLayout.addWidget(self.checkBoxTstep)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(DialogRawTFR)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.spinBoxTstep = QtGui.QSpinBox(DialogRawTFR)
        self.spinBoxTstep.setEnabled(False)
        self.spinBoxTstep.setMaximum(1000000000)
        self.spinBoxTstep.setSingleStep(1)
        self.spinBoxTstep.setProperty("value", 512)
        self.spinBoxTstep.setObjectName(_fromUtf8("spinBoxTstep"))
        self.horizontalLayout_2.addWidget(self.spinBoxTstep)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtGui.QFrame(DialogRawTFR)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(DialogRawTFR)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBoxFmin = QtGui.QSpinBox(DialogRawTFR)
        self.spinBoxFmin.setEnabled(True)
        self.spinBoxFmin.setMinimum(0)
        self.spinBoxFmin.setMaximum(1000)
        self.spinBoxFmin.setProperty("value", 1)
        self.spinBoxFmin.setObjectName(_fromUtf8("spinBoxFmin"))
        self.horizontalLayout_3.addWidget(self.spinBoxFmin)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(DialogRawTFR)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.spinBoxFmax = QtGui.QSpinBox(DialogRawTFR)
        self.spinBoxFmax.setEnabled(True)
        self.spinBoxFmax.setMinimum(0)
        self.spinBoxFmax.setMaximum(1000)
        self.spinBoxFmax.setProperty("value", 40)
        self.spinBoxFmax.setObjectName(_fromUtf8("spinBoxFmax"))
        self.horizontalLayout_4.addWidget(self.spinBoxFmax)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line_4 = QtGui.QFrame(DialogRawTFR)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout.addWidget(self.line_4)
        self.groupBoxBaseline = QtGui.QGroupBox(DialogRawTFR)
        self.groupBoxBaseline.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBoxBaseline.sizePolicy().hasHeightForWidth())
        self.groupBoxBaseline.setSizePolicy(sizePolicy)
        self.groupBoxBaseline.setCheckable(True)
        self.groupBoxBaseline.setChecked(True)
        self.groupBoxBaseline.setObjectName(_fromUtf8("groupBoxBaseline"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxBaseline)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.labelRescaling = QtGui.QLabel(self.groupBoxBaseline)
        self.labelRescaling.setObjectName(_fromUtf8("labelRescaling"))
        self.gridLayout_7.addWidget(self.labelRescaling, 0, 0, 1, 1)
        self.labelBaselineStart = QtGui.QLabel(self.groupBoxBaseline)
        self.labelBaselineStart.setEnabled(True)
        self.labelBaselineStart.setObjectName(_fromUtf8("labelBaselineStart"))
        self.gridLayout_7.addWidget(self.labelBaselineStart, 1, 0, 1, 1)
        self.comboBoxMode = QtGui.QComboBox(self.groupBoxBaseline)
        self.comboBoxMode.setObjectName(_fromUtf8("comboBoxMode"))
        self.comboBoxMode.addItem(_fromUtf8(""))
        self.comboBoxMode.addItem(_fromUtf8(""))
        self.comboBoxMode.addItem(_fromUtf8(""))
        self.comboBoxMode.addItem(_fromUtf8(""))
        self.comboBoxMode.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.comboBoxMode, 0, 1, 1, 1)
        self.doubleSpinBoxBaselineStart = QtGui.QDoubleSpinBox(self.groupBoxBaseline)
        self.doubleSpinBoxBaselineStart.setEnabled(True)
        self.doubleSpinBoxBaselineStart.setDecimals(3)
        self.doubleSpinBoxBaselineStart.setSingleStep(0.05)
        self.doubleSpinBoxBaselineStart.setObjectName(_fromUtf8("doubleSpinBoxBaselineStart"))
        self.gridLayout_7.addWidget(self.doubleSpinBoxBaselineStart, 1, 1, 1, 1)
        self.labelBaselineEnd = QtGui.QLabel(self.groupBoxBaseline)
        self.labelBaselineEnd.setEnabled(True)
        self.labelBaselineEnd.setObjectName(_fromUtf8("labelBaselineEnd"))
        self.gridLayout_7.addWidget(self.labelBaselineEnd, 2, 0, 1, 1)
        self.doubleSpinBoxBaselineEnd = QtGui.QDoubleSpinBox(self.groupBoxBaseline)
        self.doubleSpinBoxBaselineEnd.setEnabled(True)
        self.doubleSpinBoxBaselineEnd.setDecimals(3)
        self.doubleSpinBoxBaselineEnd.setSingleStep(0.05)
        self.doubleSpinBoxBaselineEnd.setObjectName(_fromUtf8("doubleSpinBoxBaselineEnd"))
        self.gridLayout_7.addWidget(self.doubleSpinBoxBaselineEnd, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_7, 0, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBoxBaseline)
        self.line_5 = QtGui.QFrame(DialogRawTFR)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout.addWidget(self.line_5)
        self.checkBoxSaveData = QtGui.QCheckBox(DialogRawTFR)
        self.checkBoxSaveData.setObjectName(_fromUtf8("checkBoxSaveData"))
        self.verticalLayout.addWidget(self.checkBoxSaveData)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(DialogRawTFR)
        self.comboBoxMode.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DialogRawTFR.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DialogRawTFR.reject)
        QtCore.QObject.connect(self.checkBoxTstep, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spinBoxTstep.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(DialogRawTFR)

    def retranslateUi(self, DialogRawTFR):
        DialogRawTFR.setWindowTitle(_translate("DialogRawTFR", "Meggie - TFR from raw", None))
        self.label_5.setText(_translate("DialogRawTFR", "Select channel:", None))
        self.label.setText(_translate("DialogRawTFR", "Length of the STFT window in samples:", None))
        self.checkBoxTstep.setText(_translate("DialogRawTFR", "Use default step (=window length / 2)", None))
        self.label_2.setText(_translate("DialogRawTFR", "Step between successive windows in samples:", None))
        self.label_3.setText(_translate("DialogRawTFR", "Min frequency:", None))
        self.label_4.setText(_translate("DialogRawTFR", "Max frequency:", None))
        self.groupBoxBaseline.setTitle(_translate("DialogRawTFR", "Baseline rescaling and correction", None))
        self.labelRescaling.setText(_translate("DialogRawTFR", "Rescaling mode:", None))
        self.labelBaselineStart.setText(_translate("DialogRawTFR", "Baseline start:", None))
        self.comboBoxMode.setItemText(0, _translate("DialogRawTFR", "ratio", None))
        self.comboBoxMode.setItemText(1, _translate("DialogRawTFR", "logratio", None))
        self.comboBoxMode.setItemText(2, _translate("DialogRawTFR", "mean", None))
        self.comboBoxMode.setItemText(3, _translate("DialogRawTFR", "zscore", None))
        self.comboBoxMode.setItemText(4, _translate("DialogRawTFR", "percent", None))
        self.doubleSpinBoxBaselineStart.setSuffix(_translate("DialogRawTFR", "s", None))
        self.labelBaselineEnd.setText(_translate("DialogRawTFR", "Baseline end:", None))
        self.doubleSpinBoxBaselineEnd.setSuffix(_translate("DialogRawTFR", "s", None))
        self.checkBoxSaveData.setText(_translate("DialogRawTFR", "Save data", None))

