# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TFRPlotTopologyDialogUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TFRPlotTopologyDialog(object):
    def setupUi(self, TFRPlotTopologyDialog):
        TFRPlotTopologyDialog.setObjectName("TFRPlotTopologyDialog")
        TFRPlotTopologyDialog.resize(556, 300)
        self.gridLayout_2 = QtWidgets.QGridLayout(TFRPlotTopologyDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(TFRPlotTopologyDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(TFRPlotTopologyDialog)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 524, 273))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBoxPreferences = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxPreferences.setObjectName("groupBoxPreferences")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBoxPreferences)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelBaselineMode = QtWidgets.QLabel(self.groupBoxPreferences)
        self.labelBaselineMode.setObjectName("labelBaselineMode")
        self.horizontalLayout_2.addWidget(self.labelBaselineMode)
        self.comboBoxBaselineMode = QtWidgets.QComboBox(self.groupBoxPreferences)
        self.comboBoxBaselineMode.setObjectName("comboBoxBaselineMode")
        self.comboBoxBaselineMode.addItem("")
        self.comboBoxBaselineMode.addItem("")
        self.comboBoxBaselineMode.addItem("")
        self.comboBoxBaselineMode.addItem("")
        self.comboBoxBaselineMode.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxBaselineMode)
        self.gridLayout_9.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelBaselineCorrection = QtWidgets.QLabel(self.groupBoxPreferences)
        self.labelBaselineCorrection.setObjectName("labelBaselineCorrection")
        self.horizontalLayout.addWidget(self.labelBaselineCorrection)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.checkBoxBaselineCorrection = QtWidgets.QCheckBox(self.groupBoxPreferences)
        self.checkBoxBaselineCorrection.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBoxBaselineCorrection.setText("")
        self.checkBoxBaselineCorrection.setChecked(True)
        self.checkBoxBaselineCorrection.setObjectName("checkBoxBaselineCorrection")
        self.horizontalLayout.addWidget(self.checkBoxBaselineCorrection)
        self.gridLayout_9.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelBaselineStart = QtWidgets.QLabel(self.groupBoxPreferences)
        self.labelBaselineStart.setObjectName("labelBaselineStart")
        self.horizontalLayout_3.addWidget(self.labelBaselineStart)
        self.doubleSpinBoxBaselineStart = QtWidgets.QDoubleSpinBox(self.groupBoxPreferences)
        self.doubleSpinBoxBaselineStart.setObjectName("doubleSpinBoxBaselineStart")
        self.horizontalLayout_3.addWidget(self.doubleSpinBoxBaselineStart)
        self.gridLayout_9.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelBaselineEnd = QtWidgets.QLabel(self.groupBoxPreferences)
        self.labelBaselineEnd.setObjectName("labelBaselineEnd")
        self.horizontalLayout_4.addWidget(self.labelBaselineEnd)
        self.doubleSpinBoxBaselineEnd = QtWidgets.QDoubleSpinBox(self.groupBoxPreferences)
        self.doubleSpinBoxBaselineEnd.setObjectName("doubleSpinBoxBaselineEnd")
        self.horizontalLayout_4.addWidget(self.doubleSpinBoxBaselineEnd)
        self.gridLayout_9.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxPreferences, 2, 0, 1, 1)
        self.groupBoxOutputOptions = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxOutputOptions.setObjectName("groupBoxOutputOptions")
        self.formLayout = QtWidgets.QFormLayout(self.groupBoxOutputOptions)
        self.formLayout.setObjectName("formLayout")
        self.radioButtonAllChannels = QtWidgets.QRadioButton(self.groupBoxOutputOptions)
        self.radioButtonAllChannels.setChecked(True)
        self.radioButtonAllChannels.setObjectName("radioButtonAllChannels")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radioButtonAllChannels)
        self.radioButtonChannelAverages = QtWidgets.QRadioButton(self.groupBoxOutputOptions)
        self.radioButtonChannelAverages.setObjectName("radioButtonChannelAverages")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.radioButtonChannelAverages)
        self.gridLayout_4.addWidget(self.groupBoxOutputOptions, 3, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(TFRPlotTopologyDialog)
        self.buttonBox.accepted.connect(TFRPlotTopologyDialog.accept)
        self.buttonBox.rejected.connect(TFRPlotTopologyDialog.reject)
        self.checkBoxBaselineCorrection.toggled['bool'].connect(self.comboBoxBaselineMode.setEnabled)
        self.checkBoxBaselineCorrection.toggled['bool'].connect(self.doubleSpinBoxBaselineStart.setEnabled)
        self.checkBoxBaselineCorrection.toggled['bool'].connect(self.doubleSpinBoxBaselineEnd.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(TFRPlotTopologyDialog)
        TFRPlotTopologyDialog.setTabOrder(self.scrollArea, self.buttonBox)

    def retranslateUi(self, TFRPlotTopologyDialog):
        _translate = QtCore.QCoreApplication.translate
        TFRPlotTopologyDialog.setWindowTitle(_translate("TFRPlotTopologyDialog", "Meggie - Plot TFR"))
        self.groupBoxPreferences.setTitle(_translate("TFRPlotTopologyDialog", "Preferences"))
        self.labelBaselineMode.setText(_translate("TFRPlotTopologyDialog", "Baseline mode:"))
        self.comboBoxBaselineMode.setItemText(0, _translate("TFRPlotTopologyDialog", "mean"))
        self.comboBoxBaselineMode.setItemText(1, _translate("TFRPlotTopologyDialog", "ratio"))
        self.comboBoxBaselineMode.setItemText(2, _translate("TFRPlotTopologyDialog", "logratio"))
        self.comboBoxBaselineMode.setItemText(3, _translate("TFRPlotTopologyDialog", "percent"))
        self.comboBoxBaselineMode.setItemText(4, _translate("TFRPlotTopologyDialog", "zscore"))
        self.labelBaselineCorrection.setText(_translate("TFRPlotTopologyDialog", "Baseline correction:"))
        self.labelBaselineStart.setText(_translate("TFRPlotTopologyDialog", "Start:"))
        self.labelBaselineEnd.setText(_translate("TFRPlotTopologyDialog", "End:"))
        self.groupBoxOutputOptions.setTitle(_translate("TFRPlotTopologyDialog", "Output options"))
        self.radioButtonAllChannels.setText(_translate("TFRPlotTopologyDialog", "All channels"))
        self.radioButtonChannelAverages.setText(_translate("TFRPlotTopologyDialog", "Channel averages"))

