# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer_ui_files/TSEPlotDialogUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TSEPlotDialog(object):
    def setupUi(self, TSEPlotDialog):
        TSEPlotDialog.setObjectName("TSEPlotDialog")
        TSEPlotDialog.resize(463, 280)
        self.gridLayout_2 = QtWidgets.QGridLayout(TSEPlotDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(TSEPlotDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(TSEPlotDialog)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 445, 230))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBoxPreferences = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxPreferences.setObjectName("groupBoxPreferences")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBoxPreferences)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelMinFreq = QtWidgets.QLabel(self.groupBoxPreferences)
        self.labelMinFreq.setObjectName("labelMinFreq")
        self.horizontalLayout_3.addWidget(self.labelMinFreq)
        self.doubleSpinBoxMinFreq = QtWidgets.QDoubleSpinBox(self.groupBoxPreferences)
        self.doubleSpinBoxMinFreq.setMaximum(999.99)
        self.doubleSpinBoxMinFreq.setObjectName("doubleSpinBoxMinFreq")
        self.horizontalLayout_3.addWidget(self.doubleSpinBoxMinFreq)
        self.gridLayout_9.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelMaxFreq = QtWidgets.QLabel(self.groupBoxPreferences)
        self.labelMaxFreq.setObjectName("labelMaxFreq")
        self.horizontalLayout_4.addWidget(self.labelMaxFreq)
        self.doubleSpinBoxMaxFreq = QtWidgets.QDoubleSpinBox(self.groupBoxPreferences)
        self.doubleSpinBoxMaxFreq.setMaximum(999.99)
        self.doubleSpinBoxMaxFreq.setObjectName("doubleSpinBoxMaxFreq")
        self.horizontalLayout_4.addWidget(self.doubleSpinBoxMaxFreq)
        self.gridLayout_9.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxPreferences, 2, 0, 1, 1)
        self.groupBoxOutputOptions = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxOutputOptions.setObjectName("groupBoxOutputOptions")
        self.formLayout = QtWidgets.QFormLayout(self.groupBoxOutputOptions)
        self.formLayout.setObjectName("formLayout")
        self.labelChannels = QtWidgets.QLabel(self.groupBoxOutputOptions)
        self.labelChannels.setObjectName("labelChannels")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelChannels)
        self.radioButtonAllChannels = QtWidgets.QRadioButton(self.groupBoxOutputOptions)
        self.radioButtonAllChannels.setChecked(True)
        self.radioButtonAllChannels.setObjectName("radioButtonAllChannels")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.radioButtonAllChannels)
        self.radioButtonChannelAverages = QtWidgets.QRadioButton(self.groupBoxOutputOptions)
        self.radioButtonChannelAverages.setObjectName("radioButtonChannelAverages")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.radioButtonChannelAverages)
        self.gridLayout_4.addWidget(self.groupBoxOutputOptions, 3, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(TSEPlotDialog)
        self.buttonBox.accepted.connect(TSEPlotDialog.accept)
        self.buttonBox.rejected.connect(TSEPlotDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(TSEPlotDialog)
        TSEPlotDialog.setTabOrder(self.scrollArea, self.buttonBox)

    def retranslateUi(self, TSEPlotDialog):
        _translate = QtCore.QCoreApplication.translate
        TSEPlotDialog.setWindowTitle(_translate("TSEPlotDialog", "Meggie - Plot TFR"))
        self.groupBoxPreferences.setTitle(_translate("TSEPlotDialog", "Preferences"))
        self.labelMinFreq.setText(_translate("TSEPlotDialog", "Minimum frequency:"))
        self.labelMaxFreq.setText(_translate("TSEPlotDialog", "Maximum frequency:"))
        self.groupBoxOutputOptions.setTitle(_translate("TSEPlotDialog", "Output options"))
        self.labelChannels.setText(_translate("TSEPlotDialog", "Type:"))
        self.radioButtonAllChannels.setText(_translate("TSEPlotDialog", "All channels"))
        self.radioButtonChannelAverages.setText(_translate("TSEPlotDialog", "Channel averages"))

