# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIehdotus11.ui'
#
# Created: Tue Apr 30 14:50:28 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(935, 717)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 937, 638))
        self.scrollAreaWidgetContents_3.setMinimumSize(QtCore.QSize(937, 638))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.layoutWidget = QtGui.QWidget(self.scrollAreaWidgetContents_3)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 5, 921, 631))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.layoutWidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabRaw = QtGui.QWidget()
        self.tabRaw.setObjectName(_fromUtf8("tabRaw"))
        self.gridLayout = QtGui.QGridLayout(self.tabRaw)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.metaBox = QtGui.QGroupBox(self.tabRaw)
        self.metaBox.setObjectName(_fromUtf8("metaBox"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.metaBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(30, 30, 291, 81))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelExperiment = QtGui.QLabel(self.formLayoutWidget_2)
        self.labelExperiment.setObjectName(_fromUtf8("labelExperiment"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelExperiment)
        self.labelExperimentName = QtGui.QLabel(self.formLayoutWidget_2)
        self.labelExperimentName.setObjectName(_fromUtf8("labelExperimentName"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.labelExperimentName)
        self.labelDate = QtGui.QLabel(self.formLayoutWidget_2)
        self.labelDate.setObjectName(_fromUtf8("labelDate"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelDate)
        self.labelDateValue = QtGui.QLabel(self.formLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDateValue.sizePolicy().hasHeightForWidth())
        self.labelDateValue.setSizePolicy(sizePolicy)
        self.labelDateValue.setObjectName(_fromUtf8("labelDateValue"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.labelDateValue)
        self.labelSubject = QtGui.QLabel(self.formLayoutWidget_2)
        self.labelSubject.setObjectName(_fromUtf8("labelSubject"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelSubject)
        self.labelSubjectValue = QtGui.QLabel(self.formLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSubjectValue.sizePolicy().hasHeightForWidth())
        self.labelSubjectValue.setSizePolicy(sizePolicy)
        self.labelSubjectValue.setObjectName(_fromUtf8("labelSubjectValue"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.labelSubjectValue)
        self.horizontalLayout_3.addWidget(self.metaBox)
        self.channelsBox = QtGui.QGroupBox(self.tabRaw)
        self.channelsBox.setObjectName(_fromUtf8("channelsBox"))
        self.layoutWidget_7 = QtGui.QWidget(self.channelsBox)
        self.layoutWidget_7.setGeometry(QtCore.QRect(30, 30, 251, 112))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.labelEEG = QtGui.QLabel(self.layoutWidget_7)
        self.labelEEG.setObjectName(_fromUtf8("labelEEG"))
        self.horizontalLayout_6.addWidget(self.labelEEG)
        self.labelEEGValue = QtGui.QLabel(self.layoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelEEGValue.sizePolicy().hasHeightForWidth())
        self.labelEEGValue.setSizePolicy(sizePolicy)
        self.labelEEGValue.setObjectName(_fromUtf8("labelEEGValue"))
        self.horizontalLayout_6.addWidget(self.labelEEGValue)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.labelGradMEG = QtGui.QLabel(self.layoutWidget_7)
        self.labelGradMEG.setObjectName(_fromUtf8("labelGradMEG"))
        self.horizontalLayout_7.addWidget(self.labelGradMEG)
        self.labelGradMEGValue = QtGui.QLabel(self.layoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelGradMEGValue.sizePolicy().hasHeightForWidth())
        self.labelGradMEGValue.setSizePolicy(sizePolicy)
        self.labelGradMEGValue.setObjectName(_fromUtf8("labelGradMEGValue"))
        self.horizontalLayout_7.addWidget(self.labelGradMEGValue)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.labelMagMEG = QtGui.QLabel(self.layoutWidget_7)
        self.labelMagMEG.setObjectName(_fromUtf8("labelMagMEG"))
        self.horizontalLayout_8.addWidget(self.labelMagMEG)
        self.labelMagMEGValue = QtGui.QLabel(self.layoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMagMEGValue.sizePolicy().hasHeightForWidth())
        self.labelMagMEGValue.setSizePolicy(sizePolicy)
        self.labelMagMEGValue.setObjectName(_fromUtf8("labelMagMEGValue"))
        self.horizontalLayout_8.addWidget(self.labelMagMEGValue)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.labelSamples = QtGui.QLabel(self.layoutWidget_7)
        self.labelSamples.setObjectName(_fromUtf8("labelSamples"))
        self.horizontalLayout_9.addWidget(self.labelSamples)
        self.labelSamplesValue = QtGui.QLabel(self.layoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSamplesValue.sizePolicy().hasHeightForWidth())
        self.labelSamplesValue.setSizePolicy(sizePolicy)
        self.labelSamplesValue.setObjectName(_fromUtf8("labelSamplesValue"))
        self.horizontalLayout_9.addWidget(self.labelSamplesValue)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_3.addWidget(self.channelsBox)
        self.filtersBox = QtGui.QGroupBox(self.tabRaw)
        self.filtersBox.setObjectName(_fromUtf8("filtersBox"))
        self.layoutWidget_6 = QtGui.QWidget(self.filtersBox)
        self.layoutWidget_6.setGeometry(QtCore.QRect(24, 32, 221, 65))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.labelLow = QtGui.QLabel(self.layoutWidget_6)
        self.labelLow.setLineWidth(1)
        self.labelLow.setScaledContents(True)
        self.labelLow.setObjectName(_fromUtf8("labelLow"))
        self.horizontalLayout_4.addWidget(self.labelLow)
        self.labelLowValue = QtGui.QLabel(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLowValue.sizePolicy().hasHeightForWidth())
        self.labelLowValue.setSizePolicy(sizePolicy)
        self.labelLowValue.setObjectName(_fromUtf8("labelLowValue"))
        self.horizontalLayout_4.addWidget(self.labelLowValue)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.labelHigh = QtGui.QLabel(self.layoutWidget_6)
        self.labelHigh.setObjectName(_fromUtf8("labelHigh"))
        self.horizontalLayout_5.addWidget(self.labelHigh)
        self.labelHighValue = QtGui.QLabel(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHighValue.sizePolicy().hasHeightForWidth())
        self.labelHighValue.setSizePolicy(sizePolicy)
        self.labelHighValue.setObjectName(_fromUtf8("labelHighValue"))
        self.horizontalLayout_5.addWidget(self.labelHighValue)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3.addWidget(self.filtersBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.triggersBox = QtGui.QGroupBox(self.tabRaw)
        self.triggersBox.setObjectName(_fromUtf8("triggersBox"))
        self.listWidget = QtGui.QListWidget(self.triggersBox)
        self.listWidget.setGeometry(QtCore.QRect(10, 30, 241, 141))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.labelWorkingFile = QtGui.QLabel(self.triggersBox)
        self.labelWorkingFile.setGeometry(QtCore.QRect(370, 30, 66, 21))
        self.labelWorkingFile.setObjectName(_fromUtf8("labelWorkingFile"))
        self.verticalLayout_4.addWidget(self.triggersBox)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButtonMNE_Browse_Raw = QtGui.QPushButton(self.tabRaw)
        self.pushButtonMNE_Browse_Raw.setObjectName(_fromUtf8("pushButtonMNE_Browse_Raw"))
        self.verticalLayout.addWidget(self.pushButtonMNE_Browse_Raw)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabRaw, _fromUtf8(""))
        self.tabPreprocessing = QtGui.QWidget()
        self.tabPreprocessing.setObjectName(_fromUtf8("tabPreprocessing"))
        self.groupBoxPreprocessingCheckBoxes = QtGui.QGroupBox(self.tabPreprocessing)
        self.groupBoxPreprocessingCheckBoxes.setGeometry(QtCore.QRect(10, 20, 270, 130))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPreprocessingCheckBoxes.sizePolicy().hasHeightForWidth())
        self.groupBoxPreprocessingCheckBoxes.setSizePolicy(sizePolicy)
        self.groupBoxPreprocessingCheckBoxes.setMinimumSize(QtCore.QSize(60, 0))
        self.groupBoxPreprocessingCheckBoxes.setObjectName(_fromUtf8("groupBoxPreprocessingCheckBoxes"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBoxPreprocessingCheckBoxes)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.checkBoxMaxFilter = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxMaxFilter.setCheckable(True)
        self.checkBoxMaxFilter.setObjectName(_fromUtf8("checkBoxMaxFilter"))
        self.verticalLayout_9.addWidget(self.checkBoxMaxFilter)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.checkBoxECG = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxECG.setCheckable(True)
        self.checkBoxECG.setObjectName(_fromUtf8("checkBoxECG"))
        self.horizontalLayout_2.addWidget(self.checkBoxECG)
        self.checkBoxECGApplied = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxECGApplied.setObjectName(_fromUtf8("checkBoxECGApplied"))
        self.horizontalLayout_2.addWidget(self.checkBoxECGApplied)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.checkBoxEOG = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxEOG.setCheckable(True)
        self.checkBoxEOG.setObjectName(_fromUtf8("checkBoxEOG"))
        self.horizontalLayout_10.addWidget(self.checkBoxEOG)
        self.checkBoxEOGApplied = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes)
        self.checkBoxEOGApplied.setObjectName(_fromUtf8("checkBoxEOGApplied"))
        self.horizontalLayout_10.addWidget(self.checkBoxEOGApplied)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.groupBoxAvailablePreprocessingSteps = QtGui.QGroupBox(self.tabPreprocessing)
        self.groupBoxAvailablePreprocessingSteps.setGeometry(QtCore.QRect(10, 250, 441, 211))
        self.groupBoxAvailablePreprocessingSteps.setObjectName(_fromUtf8("groupBoxAvailablePreprocessingSteps"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxAvailablePreprocessingSteps)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.pushButtonMaxFilter = QtGui.QPushButton(self.groupBoxAvailablePreprocessingSteps)
        self.pushButtonMaxFilter.setObjectName(_fromUtf8("pushButtonMaxFilter"))
        self.verticalLayout_5.addWidget(self.pushButtonMaxFilter)
        self.pushButtonECG = QtGui.QPushButton(self.groupBoxAvailablePreprocessingSteps)
        self.pushButtonECG.setObjectName(_fromUtf8("pushButtonECG"))
        self.verticalLayout_5.addWidget(self.pushButtonECG)
        self.pushButtonEOG = QtGui.QPushButton(self.groupBoxAvailablePreprocessingSteps)
        self.pushButtonEOG.setObjectName(_fromUtf8("pushButtonEOG"))
        self.verticalLayout_5.addWidget(self.pushButtonEOG)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.pushButtonApplyECG = QtGui.QPushButton(self.groupBoxAvailablePreprocessingSteps)
        self.pushButtonApplyECG.setEnabled(False)
        self.pushButtonApplyECG.setObjectName(_fromUtf8("pushButtonApplyECG"))
        self.verticalLayout_2.addWidget(self.pushButtonApplyECG)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.pushButtonApplyEOG = QtGui.QPushButton(self.groupBoxAvailablePreprocessingSteps)
        self.pushButtonApplyEOG.setEnabled(False)
        self.pushButtonApplyEOG.setObjectName(_fromUtf8("pushButtonApplyEOG"))
        self.verticalLayout_2.addWidget(self.pushButtonApplyEOG)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tabPreprocessing)
        self.groupBox_2.setGeometry(QtCore.QRect(430, 30, 381, 231))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.listWidgetEventsPre = QtGui.QListWidget(self.groupBox_2)
        self.listWidgetEventsPre.setGeometry(QtCore.QRect(10, 20, 331, 191))
        self.listWidgetEventsPre.setObjectName(_fromUtf8("listWidgetEventsPre"))
        self.tabWidget.addTab(self.tabPreprocessing, _fromUtf8(""))
        self.tabAnalysis = QtGui.QWidget()
        self.tabAnalysis.setObjectName(_fromUtf8("tabAnalysis"))
        self.groupBoxPreprocessingCheckBoxes_2 = QtGui.QGroupBox(self.tabAnalysis)
        self.groupBoxPreprocessingCheckBoxes_2.setGeometry(QtCore.QRect(20, 30, 241, 126))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPreprocessingCheckBoxes_2.sizePolicy().hasHeightForWidth())
        self.groupBoxPreprocessingCheckBoxes_2.setSizePolicy(sizePolicy)
        self.groupBoxPreprocessingCheckBoxes_2.setMinimumSize(QtCore.QSize(60, 0))
        self.groupBoxPreprocessingCheckBoxes_2.setObjectName(_fromUtf8("groupBoxPreprocessingCheckBoxes_2"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBoxPreprocessingCheckBoxes_2)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.checkBox = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes_2)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout_10.addWidget(self.checkBox)
        self.checkBoxEpochs = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes_2)
        self.checkBoxEpochs.setCheckable(True)
        self.checkBoxEpochs.setObjectName(_fromUtf8("checkBoxEpochs"))
        self.verticalLayout_10.addWidget(self.checkBoxEpochs)
        self.checkBoxEOG_2 = QtGui.QCheckBox(self.groupBoxPreprocessingCheckBoxes_2)
        self.checkBoxEOG_2.setCheckable(True)
        self.checkBoxEOG_2.setObjectName(_fromUtf8("checkBoxEOG_2"))
        self.verticalLayout_10.addWidget(self.checkBoxEOG_2)
        self.groupBoxAvailablePreprocessingSteps_2 = QtGui.QGroupBox(self.tabAnalysis)
        self.groupBoxAvailablePreprocessingSteps_2.setGeometry(QtCore.QRect(20, 260, 218, 143))
        self.groupBoxAvailablePreprocessingSteps_2.setObjectName(_fromUtf8("groupBoxAvailablePreprocessingSteps_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBoxAvailablePreprocessingSteps_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.pushButtonEventlist = QtGui.QPushButton(self.groupBoxAvailablePreprocessingSteps_2)
        self.pushButtonEventlist.setObjectName(_fromUtf8("pushButtonEventlist"))
        self.verticalLayout_11.addWidget(self.pushButtonEventlist)
        self.pushButtonEpochs = QtGui.QPushButton(self.groupBoxAvailablePreprocessingSteps_2)
        self.pushButtonEpochs.setObjectName(_fromUtf8("pushButtonEpochs"))
        self.verticalLayout_11.addWidget(self.pushButtonEpochs)
        self.pushButtonAverage = QtGui.QPushButton(self.groupBoxAvailablePreprocessingSteps_2)
        self.pushButtonAverage.setObjectName(_fromUtf8("pushButtonAverage"))
        self.verticalLayout_11.addWidget(self.pushButtonAverage)
        self.gridLayout_4.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tabAnalysis)
        self.groupBox.setGeometry(QtCore.QRect(430, 30, 381, 231))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.listWidgetEvents = QtGui.QListWidget(self.groupBox)
        self.listWidgetEvents.setGeometry(QtCore.QRect(10, 20, 331, 191))
        self.listWidgetEvents.setObjectName(_fromUtf8("listWidgetEvents"))
        self.pushButtonTFR = QtGui.QPushButton(self.tabAnalysis)
        self.pushButtonTFR.setGeometry(QtCore.QRect(700, 280, 75, 23))
        self.pushButtonTFR.setObjectName(_fromUtf8("pushButtonTFR"))
        self.tabWidget.addTab(self.tabAnalysis, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 935, 29))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionCreate_experiment = QtGui.QAction(MainWindow)
        self.actionCreate_experiment.setObjectName(_fromUtf8("actionCreate_experiment"))
        self.actionOpen_experiment = QtGui.QAction(MainWindow)
        self.actionOpen_experiment.setObjectName(_fromUtf8("actionOpen_experiment"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionSet_workspace = QtGui.QAction(MainWindow)
        self.actionSet_workspace.setObjectName(_fromUtf8("actionSet_workspace"))
        self.menuFile.addAction(self.actionCreate_experiment)
        self.menuFile.addAction(self.actionOpen_experiment)
        self.menuFile.addAction(self.actionSet_workspace)
        self.menuTools.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.toolBar.addAction(self.actionCreate_experiment)
        self.toolBar.addAction(self.actionOpen_experiment)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.metaBox.setTitle(_translate("MainWindow", "Background", None))
        self.labelExperiment.setText(_translate("MainWindow", "Experiment:", None))
        self.labelExperimentName.setText(_translate("MainWindow", "TextLabel", None))
        self.labelDate.setText(_translate("MainWindow", "Date:", None))
        self.labelDateValue.setText(_translate("MainWindow", "DateValue", None))
        self.labelSubject.setText(_translate("MainWindow", "Subject:", None))
        self.labelSubjectValue.setText(_translate("MainWindow", "TextLabel", None))
        self.channelsBox.setTitle(_translate("MainWindow", "Channels", None))
        self.labelEEG.setText(_translate("MainWindow", "EEG channels:", None))
        self.labelEEGValue.setText(_translate("MainWindow", "EEG value", None))
        self.labelGradMEG.setText(_translate("MainWindow", "Gradiometers:", None))
        self.labelGradMEGValue.setText(_translate("MainWindow", "Grad. MEG value", None))
        self.labelMagMEG.setText(_translate("MainWindow", "Magnetometers:", None))
        self.labelMagMEGValue.setText(_translate("MainWindow", "Mag. MEG value", None))
        self.labelSamples.setText(_translate("MainWindow", "Sampling frequency:", None))
        self.labelSamplesValue.setText(_translate("MainWindow", "SamplesValue", None))
        self.filtersBox.setTitle(_translate("MainWindow", "Filters", None))
        self.labelLow.setText(_translate("MainWindow", "Low-pass:", None))
        self.labelLowValue.setText(_translate("MainWindow", "Low-pass value", None))
        self.labelHigh.setText(_translate("MainWindow", "High-pass:", None))
        self.labelHighValue.setText(_translate("MainWindow", "High-pass value", None))
        self.triggersBox.setTitle(_translate("MainWindow", "Triggers", None))
        self.labelWorkingFile.setText(_translate("MainWindow", "TextLabel", None))
        self.pushButtonMNE_Browse_Raw.setText(_translate("MainWindow", "View with MNE_Browse_Raw", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRaw), _translate("MainWindow", "Raw", None))
        self.groupBoxPreprocessingCheckBoxes.setTitle(_translate("MainWindow", "Preprocessing steps completed:", None))
        self.checkBoxMaxFilter.setText(_translate("MainWindow", "Maxfilter", None))
        self.checkBoxECG.setText(_translate("MainWindow", "ECG computed", None))
        self.checkBoxECGApplied.setText(_translate("MainWindow", "ECG applied", None))
        self.checkBoxEOG.setText(_translate("MainWindow", "EOG computed", None))
        self.checkBoxEOGApplied.setText(_translate("MainWindow", "EOG applied", None))
        self.groupBoxAvailablePreprocessingSteps.setTitle(_translate("MainWindow", "Available actions:", None))
        self.pushButtonMaxFilter.setText(_translate("MainWindow", "MaxFilter", None))
        self.pushButtonECG.setText(_translate("MainWindow", "Calculate ECG projections", None))
        self.pushButtonEOG.setText(_translate("MainWindow", "Calculate EOG projections", None))
        self.pushButtonApplyECG.setText(_translate("MainWindow", "Apply ECG projections", None))
        self.pushButtonApplyEOG.setText(_translate("MainWindow", "Apply EOG projections", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Events:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPreprocessing), _translate("MainWindow", "Preprocessing", None))
        self.groupBoxPreprocessingCheckBoxes_2.setTitle(_translate("MainWindow", "Steps completed:", None))
        self.checkBox.setText(_translate("MainWindow", "Eventlist", None))
        self.checkBoxEpochs.setText(_translate("MainWindow", "Epochs", None))
        self.checkBoxEOG_2.setText(_translate("MainWindow", "Average", None))
        self.groupBoxAvailablePreprocessingSteps_2.setTitle(_translate("MainWindow", "Available actions:", None))
        self.pushButtonEventlist.setText(_translate("MainWindow", "Eventlist", None))
        self.pushButtonEpochs.setText(_translate("MainWindow", "Epochs", None))
        self.pushButtonAverage.setText(_translate("MainWindow", "Average", None))
        self.groupBox.setTitle(_translate("MainWindow", "Events:", None))
        self.pushButtonTFR.setText(_translate("MainWindow", "TFR", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAnalysis), _translate("MainWindow", "Analysis", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionCreate_experiment.setText(_translate("MainWindow", "Create new experiment...", None))
        self.actionOpen_experiment.setText(_translate("MainWindow", "Open experiment...", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionSet_workspace.setText(_translate("MainWindow", "Set workspace...", None))

