# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../filterDialogUi.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogFilter(object):
    def setupUi(self, DialogFilter):
        DialogFilter.setObjectName("DialogFilter")
        DialogFilter.resize(622, 979)
        self.gridLayout = QtWidgets.QGridLayout(DialogFilter)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonCancel = QtWidgets.QPushButton(DialogFilter)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.pushButtonComputeBatch = QtWidgets.QPushButton(DialogFilter)
        self.pushButtonComputeBatch.setObjectName("pushButtonComputeBatch")
        self.horizontalLayout.addWidget(self.pushButtonComputeBatch)
        self.pushButtonCompute = QtWidgets.QPushButton(DialogFilter)
        self.pushButtonCompute.setObjectName("pushButtonCompute")
        self.horizontalLayout.addWidget(self.pushButtonCompute)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(DialogFilter)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 604, 922))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(604, 922))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frameFilterSelection = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frameFilterSelection.setGeometry(QtCore.QRect(0, 10, 596, 491))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameFilterSelection.sizePolicy().hasHeightForWidth())
        self.frameFilterSelection.setSizePolicy(sizePolicy)
        self.frameFilterSelection.setMinimumSize(QtCore.QSize(350, 0))
        self.frameFilterSelection.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFilterSelection.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFilterSelection.setLineWidth(0)
        self.frameFilterSelection.setObjectName("frameFilterSelection")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frameFilterSelection)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frameBandPass = QtWidgets.QFrame(self.frameFilterSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameBandPass.sizePolicy().hasHeightForWidth())
        self.frameBandPass.setSizePolicy(sizePolicy)
        self.frameBandPass.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBandPass.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBandPass.setObjectName("frameBandPass")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frameBandPass)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_3 = QtWidgets.QFrame(self.frameBandPass)
        self.frame_3.setEnabled(True)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.doubleSpinBoxBandstopFreq = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBoxBandstopFreq.setEnabled(False)
        self.doubleSpinBoxBandstopFreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandstopFreq.setDecimals(3)
        self.doubleSpinBoxBandstopFreq.setMaximum(10000.0)
        self.doubleSpinBoxBandstopFreq.setSingleStep(1.0)
        self.doubleSpinBoxBandstopFreq.setProperty("value", 50.0)
        self.doubleSpinBoxBandstopFreq.setObjectName("doubleSpinBoxBandstopFreq")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxBandstopFreq)
        self.gridLayout_5.addWidget(self.frame_3, 1, 0, 1, 1)
        self.checkBoxBandstop = QtWidgets.QCheckBox(self.frameBandPass)
        self.checkBoxBandstop.setChecked(False)
        self.checkBoxBandstop.setObjectName("checkBoxBandstop")
        self.gridLayout_5.addWidget(self.checkBoxBandstop, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frameBandPass, 2, 0, 1, 1)
        self.frameBandStop_3 = QtWidgets.QFrame(self.frameFilterSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameBandStop_3.sizePolicy().hasHeightForWidth())
        self.frameBandStop_3.setSizePolicy(sizePolicy)
        self.frameBandStop_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBandStop_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBandStop_3.setObjectName("frameBandStop_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frameBandStop_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_4 = QtWidgets.QFrame(self.frameBandStop_3)
        self.frame_4.setEnabled(False)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.frame_4)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.doubleSpinBoxBandstopFreq2 = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.doubleSpinBoxBandstopFreq2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandstopFreq2.setDecimals(3)
        self.doubleSpinBoxBandstopFreq2.setMaximum(10000.0)
        self.doubleSpinBoxBandstopFreq2.setSingleStep(1.0)
        self.doubleSpinBoxBandstopFreq2.setProperty("value", 100.0)
        self.doubleSpinBoxBandstopFreq2.setObjectName("doubleSpinBoxBandstopFreq2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxBandstopFreq2)
        self.gridLayout_7.addWidget(self.frame_4, 1, 0, 1, 1)
        self.checkBoxBandstop2 = QtWidgets.QCheckBox(self.frameBandStop_3)
        self.checkBoxBandstop2.setObjectName("checkBoxBandstop2")
        self.gridLayout_7.addWidget(self.checkBoxBandstop2, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frameBandStop_3, 2, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButtonPreview = QtWidgets.QPushButton(self.frameFilterSelection)
        self.pushButtonPreview.setEnabled(True)
        self.pushButtonPreview.setObjectName("pushButtonPreview")
        self.horizontalLayout_8.addWidget(self.pushButtonPreview)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 6, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.frameFilterSelection)
        self.line.setLineWidth(2)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelBandStopNotchWidth = QtWidgets.QLabel(self.frameFilterSelection)
        self.labelBandStopNotchWidth.setObjectName("labelBandStopNotchWidth")
        self.horizontalLayout_5.addWidget(self.labelBandStopNotchWidth)
        self.doubleSpinBoxBandstopWidth = QtWidgets.QDoubleSpinBox(self.frameFilterSelection)
        self.doubleSpinBoxBandstopWidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandstopWidth.setDecimals(3)
        self.doubleSpinBoxBandstopWidth.setMaximum(10000.0)
        self.doubleSpinBoxBandstopWidth.setSingleStep(1.0)
        self.doubleSpinBoxBandstopWidth.setProperty("value", 1.0)
        self.doubleSpinBoxBandstopWidth.setObjectName("doubleSpinBoxBandstopWidth")
        self.horizontalLayout_5.addWidget(self.doubleSpinBoxBandstopWidth)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 3, 0, 1, 2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelTransBw = QtWidgets.QLabel(self.frameFilterSelection)
        self.labelTransBw.setObjectName("labelTransBw")
        self.horizontalLayout_7.addWidget(self.labelTransBw)
        self.doubleSpinBoxNotchTransBw = QtWidgets.QDoubleSpinBox(self.frameFilterSelection)
        self.doubleSpinBoxNotchTransBw.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxNotchTransBw.setDecimals(3)
        self.doubleSpinBoxNotchTransBw.setMinimum(0.1)
        self.doubleSpinBoxNotchTransBw.setSingleStep(0.1)
        self.doubleSpinBoxNotchTransBw.setProperty("value", 0.5)
        self.doubleSpinBoxNotchTransBw.setObjectName("doubleSpinBoxNotchTransBw")
        self.horizontalLayout_7.addWidget(self.doubleSpinBoxNotchTransBw)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 4, 0, 1, 2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelBandstopFilterLength = QtWidgets.QLabel(self.frameFilterSelection)
        self.labelBandstopFilterLength.setObjectName("labelBandstopFilterLength")
        self.horizontalLayout_6.addWidget(self.labelBandstopFilterLength)
        self.doubleSpinBoxBandStopLength = QtWidgets.QDoubleSpinBox(self.frameFilterSelection)
        self.doubleSpinBoxBandStopLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandStopLength.setSingleStep(0.1)
        self.doubleSpinBoxBandStopLength.setProperty("value", 10.0)
        self.doubleSpinBoxBandStopLength.setObjectName("doubleSpinBoxBandStopLength")
        self.horizontalLayout_6.addWidget(self.doubleSpinBoxBandStopLength)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 5, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frameHighpass = QtWidgets.QFrame(self.frameFilterSelection)
        self.frameHighpass.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameHighpass.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameHighpass.setObjectName("frameHighpass")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frameHighpass)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.frameHighpass)
        self.frame_2.setEnabled(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.doubleSpinBoxHighpassCutoff = QtWidgets.QDoubleSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxHighpassCutoff.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxHighpassCutoff.setSizePolicy(sizePolicy)
        self.doubleSpinBoxHighpassCutoff.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxHighpassCutoff.setDecimals(3)
        self.doubleSpinBoxHighpassCutoff.setMaximum(1000000000.0)
        self.doubleSpinBoxHighpassCutoff.setSingleStep(1.0)
        self.doubleSpinBoxHighpassCutoff.setProperty("value", 1.0)
        self.doubleSpinBoxHighpassCutoff.setObjectName("doubleSpinBoxHighpassCutoff")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxHighpassCutoff)
        self.gridLayout_4.addWidget(self.frame_2, 1, 0, 1, 1)
        self.checkBoxHighpass = QtWidgets.QCheckBox(self.frameHighpass)
        self.checkBoxHighpass.setChecked(True)
        self.checkBoxHighpass.setObjectName("checkBoxHighpass")
        self.gridLayout_4.addWidget(self.checkBoxHighpass, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frameHighpass)
        self.frameLowpass = QtWidgets.QFrame(self.frameFilterSelection)
        self.frameLowpass.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLowpass.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLowpass.setObjectName("frameLowpass")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frameLowpass)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.frameLowpass)
        self.frame.setEnabled(True)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.doubleSpinBoxLowpassCutoff = QtWidgets.QDoubleSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxLowpassCutoff.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxLowpassCutoff.setSizePolicy(sizePolicy)
        self.doubleSpinBoxLowpassCutoff.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxLowpassCutoff.setDecimals(3)
        self.doubleSpinBoxLowpassCutoff.setMaximum(10000.0)
        self.doubleSpinBoxLowpassCutoff.setSingleStep(1.0)
        self.doubleSpinBoxLowpassCutoff.setProperty("value", 40.0)
        self.doubleSpinBoxLowpassCutoff.setObjectName("doubleSpinBoxLowpassCutoff")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxLowpassCutoff)
        self.gridLayout_3.addWidget(self.frame, 1, 0, 1, 1)
        self.checkBoxLowpass = QtWidgets.QCheckBox(self.frameLowpass)
        self.checkBoxLowpass.setChecked(True)
        self.checkBoxLowpass.setObjectName("checkBoxLowpass")
        self.gridLayout_3.addWidget(self.checkBoxLowpass, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frameLowpass)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelTransitionWidth = QtWidgets.QLabel(self.frameFilterSelection)
        self.labelTransitionWidth.setObjectName("labelTransitionWidth")
        self.horizontalLayout_4.addWidget(self.labelTransitionWidth)
        self.doubleSpinBoxTransBandwidth = QtWidgets.QDoubleSpinBox(self.frameFilterSelection)
        self.doubleSpinBoxTransBandwidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxTransBandwidth.setDecimals(3)
        self.doubleSpinBoxTransBandwidth.setMaximum(10000.0)
        self.doubleSpinBoxTransBandwidth.setSingleStep(0.1)
        self.doubleSpinBoxTransBandwidth.setProperty("value", 0.5)
        self.doubleSpinBoxTransBandwidth.setObjectName("doubleSpinBoxTransBandwidth")
        self.horizontalLayout_4.addWidget(self.doubleSpinBoxTransBandwidth)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelFilterLength = QtWidgets.QLabel(self.frameFilterSelection)
        self.labelFilterLength.setObjectName("labelFilterLength")
        self.horizontalLayout_3.addWidget(self.labelFilterLength)
        self.doubleSpinBoxLength = QtWidgets.QDoubleSpinBox(self.frameFilterSelection)
        self.doubleSpinBoxLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxLength.setSingleStep(0.1)
        self.doubleSpinBoxLength.setProperty("value", 10.0)
        self.doubleSpinBoxLength.setObjectName("doubleSpinBoxLength")
        self.horizontalLayout_3.addWidget(self.doubleSpinBoxLength)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 2)
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(9, 510, 301, 371))
        self.widget.setObjectName("widget")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(DialogFilter)
        self.checkBoxBandstop2.toggled['bool'].connect(self.frame_4.setEnabled)
        self.checkBoxHighpass.toggled['bool'].connect(self.frame_2.setEnabled)
        self.checkBoxLowpass.toggled['bool'].connect(self.frame.setEnabled)
        self.pushButtonCompute.clicked.connect(DialogFilter.accept)
        self.pushButtonCancel.clicked.connect(DialogFilter.reject)
        self.pushButtonComputeBatch.clicked.connect(DialogFilter.acceptBatch)
        self.checkBoxBandstop.toggled['bool'].connect(self.doubleSpinBoxBandstopFreq.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(DialogFilter)
        DialogFilter.setTabOrder(self.checkBoxLowpass, self.doubleSpinBoxLowpassCutoff)
        DialogFilter.setTabOrder(self.doubleSpinBoxLowpassCutoff, self.checkBoxHighpass)
        DialogFilter.setTabOrder(self.checkBoxHighpass, self.doubleSpinBoxHighpassCutoff)
        DialogFilter.setTabOrder(self.doubleSpinBoxHighpassCutoff, self.checkBoxBandstop)
        DialogFilter.setTabOrder(self.checkBoxBandstop, self.doubleSpinBoxBandstopFreq)
        DialogFilter.setTabOrder(self.doubleSpinBoxBandstopFreq, self.checkBoxBandstop2)
        DialogFilter.setTabOrder(self.checkBoxBandstop2, self.doubleSpinBoxBandstopFreq2)

    def retranslateUi(self, DialogFilter):
        _translate = QtCore.QCoreApplication.translate
        DialogFilter.setWindowTitle(_translate("DialogFilter", "Filtering"))
        self.pushButtonCancel.setText(_translate("DialogFilter", "Cancel"))
        self.pushButtonComputeBatch.setText(_translate("DialogFilter", "Compute Batch"))
        self.pushButtonCompute.setText(_translate("DialogFilter", "Compute"))
        self.doubleSpinBoxBandstopFreq.setSuffix(_translate("DialogFilter", " Hz"))
        self.checkBoxBandstop.setText(_translate("DialogFilter", "BandStop filter (notch)"))
        self.doubleSpinBoxBandstopFreq2.setSuffix(_translate("DialogFilter", " Hz"))
        self.checkBoxBandstop2.setText(_translate("DialogFilter", "BandStop filter (notch)"))
        self.pushButtonPreview.setText(_translate("DialogFilter", "Preview with given filters"))
        self.labelBandStopNotchWidth.setText(_translate("DialogFilter", "Notch band width:"))
        self.doubleSpinBoxBandstopWidth.setSuffix(_translate("DialogFilter", " Hz"))
        self.labelTransBw.setText(_translate("DialogFilter", "Transition band width:"))
        self.doubleSpinBoxNotchTransBw.setSuffix(_translate("DialogFilter", " Hz"))
        self.labelBandstopFilterLength.setText(_translate("DialogFilter", "Filter length:"))
        self.doubleSpinBoxBandStopLength.setSuffix(_translate("DialogFilter", "s"))
        self.doubleSpinBoxHighpassCutoff.setSuffix(_translate("DialogFilter", " Hz"))
        self.checkBoxHighpass.setText(_translate("DialogFilter", "Highpass filter"))
        self.doubleSpinBoxLowpassCutoff.setSuffix(_translate("DialogFilter", " Hz"))
        self.checkBoxLowpass.setText(_translate("DialogFilter", "Lowpass filter"))
        self.labelTransitionWidth.setText(_translate("DialogFilter", "Transition band width:"))
        self.doubleSpinBoxTransBandwidth.setSuffix(_translate("DialogFilter", " Hz"))
        self.labelFilterLength.setText(_translate("DialogFilter", "Filter length:"))
        self.doubleSpinBoxLength.setSuffix(_translate("DialogFilter", "s"))

