# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kari/Opinnot/gradu/lahdekoodit/lahdekoodit/meggie_batch/ui/qt4Designer_ui_files/filterDialog.ui'
#
# Created: Wed Feb 18 22:08:26 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogFilter(object):
    def setupUi(self, DialogFilter):
        DialogFilter.setObjectName(_fromUtf8("DialogFilter"))
        DialogFilter.resize(686, 404)
        self.gridLayout = QtGui.QGridLayout(DialogFilter)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frameFilterSelection = QtGui.QFrame(DialogFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameFilterSelection.sizePolicy().hasHeightForWidth())
        self.frameFilterSelection.setSizePolicy(sizePolicy)
        self.frameFilterSelection.setMinimumSize(QtCore.QSize(350, 0))
        self.frameFilterSelection.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameFilterSelection.setFrameShadow(QtGui.QFrame.Raised)
        self.frameFilterSelection.setLineWidth(0)
        self.frameFilterSelection.setObjectName(_fromUtf8("frameFilterSelection"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frameFilterSelection)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frameHighpass = QtGui.QFrame(self.frameFilterSelection)
        self.frameHighpass.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameHighpass.setFrameShadow(QtGui.QFrame.Raised)
        self.frameHighpass.setObjectName(_fromUtf8("frameHighpass"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frameHighpass)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.frame_2 = QtGui.QFrame(self.frameHighpass)
        self.frame_2.setEnabled(False)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.frame_2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelHighpassCutoff = QtGui.QLabel(self.frame_2)
        self.labelHighpassCutoff.setObjectName(_fromUtf8("labelHighpassCutoff"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelHighpassCutoff)
        self.doubleSpinBoxHighpassCutoff = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBoxHighpassCutoff.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxHighpassCutoff.setDecimals(3)
        self.doubleSpinBoxHighpassCutoff.setMaximum(1000000000.0)
        self.doubleSpinBoxHighpassCutoff.setSingleStep(10.0)
        self.doubleSpinBoxHighpassCutoff.setProperty("value", 0.5)
        self.doubleSpinBoxHighpassCutoff.setObjectName(_fromUtf8("doubleSpinBoxHighpassCutoff"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxHighpassCutoff)
        self.labelHighpassTransitionWidth = QtGui.QLabel(self.frame_2)
        self.labelHighpassTransitionWidth.setObjectName(_fromUtf8("labelHighpassTransitionWidth"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelHighpassTransitionWidth)
        self.doubleSpinBoxHighpassTransBandwidth = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBoxHighpassTransBandwidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxHighpassTransBandwidth.setDecimals(3)
        self.doubleSpinBoxHighpassTransBandwidth.setMaximum(10000.0)
        self.doubleSpinBoxHighpassTransBandwidth.setSingleStep(10.0)
        self.doubleSpinBoxHighpassTransBandwidth.setProperty("value", 0.5)
        self.doubleSpinBoxHighpassTransBandwidth.setObjectName(_fromUtf8("doubleSpinBoxHighpassTransBandwidth"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxHighpassTransBandwidth)
        self.labelHighpassFilterLength = QtGui.QLabel(self.frame_2)
        self.labelHighpassFilterLength.setObjectName(_fromUtf8("labelHighpassFilterLength"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelHighpassFilterLength)
        self.lineEditHighpassLength = QtGui.QLineEdit(self.frame_2)
        self.lineEditHighpassLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditHighpassLength.setObjectName(_fromUtf8("lineEditHighpassLength"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditHighpassLength)
        self.gridLayout_4.addWidget(self.frame_2, 1, 0, 1, 1)
        self.checkBoxHighpass = QtGui.QCheckBox(self.frameHighpass)
        self.checkBoxHighpass.setObjectName(_fromUtf8("checkBoxHighpass"))
        self.gridLayout_4.addWidget(self.checkBoxHighpass, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frameHighpass, 0, 0, 1, 1)
        self.frameLowpass = QtGui.QFrame(self.frameFilterSelection)
        self.frameLowpass.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameLowpass.setFrameShadow(QtGui.QFrame.Raised)
        self.frameLowpass.setObjectName(_fromUtf8("frameLowpass"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frameLowpass)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.frame = QtGui.QFrame(self.frameLowpass)
        self.frame.setEnabled(False)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayout = QtGui.QFormLayout(self.frame)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelLowpassCutoff = QtGui.QLabel(self.frame)
        self.labelLowpassCutoff.setObjectName(_fromUtf8("labelLowpassCutoff"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelLowpassCutoff)
        self.doubleSpinBoxLowpassCutoff = QtGui.QDoubleSpinBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxLowpassCutoff.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxLowpassCutoff.setSizePolicy(sizePolicy)
        self.doubleSpinBoxLowpassCutoff.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxLowpassCutoff.setDecimals(3)
        self.doubleSpinBoxLowpassCutoff.setMaximum(10000.0)
        self.doubleSpinBoxLowpassCutoff.setSingleStep(10.0)
        self.doubleSpinBoxLowpassCutoff.setProperty("value", 40.0)
        self.doubleSpinBoxLowpassCutoff.setObjectName(_fromUtf8("doubleSpinBoxLowpassCutoff"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxLowpassCutoff)
        self.labelLowpassTransitionWidth = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLowpassTransitionWidth.sizePolicy().hasHeightForWidth())
        self.labelLowpassTransitionWidth.setSizePolicy(sizePolicy)
        self.labelLowpassTransitionWidth.setObjectName(_fromUtf8("labelLowpassTransitionWidth"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelLowpassTransitionWidth)
        self.doubleSpinBoxLowpassTransBandwidth = QtGui.QDoubleSpinBox(self.frame)
        self.doubleSpinBoxLowpassTransBandwidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxLowpassTransBandwidth.setDecimals(3)
        self.doubleSpinBoxLowpassTransBandwidth.setMaximum(10000.0)
        self.doubleSpinBoxLowpassTransBandwidth.setSingleStep(10.0)
        self.doubleSpinBoxLowpassTransBandwidth.setProperty("value", 5.0)
        self.doubleSpinBoxLowpassTransBandwidth.setObjectName(_fromUtf8("doubleSpinBoxLowpassTransBandwidth"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxLowpassTransBandwidth)
        self.labelLowpassFilterLength = QtGui.QLabel(self.frame)
        self.labelLowpassFilterLength.setObjectName(_fromUtf8("labelLowpassFilterLength"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelLowpassFilterLength)
        self.lineEditLowpassLength = QtGui.QLineEdit(self.frame)
        self.lineEditLowpassLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditLowpassLength.setObjectName(_fromUtf8("lineEditLowpassLength"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditLowpassLength)
        self.gridLayout_3.addWidget(self.frame, 1, 0, 1, 1)
        self.checkBoxLowpass = QtGui.QCheckBox(self.frameLowpass)
        self.checkBoxLowpass.setChecked(False)
        self.checkBoxLowpass.setObjectName(_fromUtf8("checkBoxLowpass"))
        self.gridLayout_3.addWidget(self.checkBoxLowpass, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frameLowpass, 0, 1, 1, 1)
        self.frameBandPass = QtGui.QFrame(self.frameFilterSelection)
        self.frameBandPass.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameBandPass.setFrameShadow(QtGui.QFrame.Raised)
        self.frameBandPass.setObjectName(_fromUtf8("frameBandPass"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frameBandPass)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frame_3 = QtGui.QFrame(self.frameBandPass)
        self.frame_3.setEnabled(False)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.frame_3)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.labelBandStopFreq = QtGui.QLabel(self.frame_3)
        self.labelBandStopFreq.setObjectName(_fromUtf8("labelBandStopFreq"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelBandStopFreq)
        self.doubleSpinBoxBandstopFreq = QtGui.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBoxBandstopFreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandstopFreq.setDecimals(3)
        self.doubleSpinBoxBandstopFreq.setMaximum(10000.0)
        self.doubleSpinBoxBandstopFreq.setSingleStep(10.0)
        self.doubleSpinBoxBandstopFreq.setProperty("value", 50.0)
        self.doubleSpinBoxBandstopFreq.setObjectName(_fromUtf8("doubleSpinBoxBandstopFreq"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxBandstopFreq)
        self.labelBandStopNotchWidth = QtGui.QLabel(self.frame_3)
        self.labelBandStopNotchWidth.setObjectName(_fromUtf8("labelBandStopNotchWidth"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelBandStopNotchWidth)
        self.doubleSpinBoxBandstopWidth = QtGui.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBoxBandstopWidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandstopWidth.setDecimals(3)
        self.doubleSpinBoxBandstopWidth.setMaximum(10000.0)
        self.doubleSpinBoxBandstopWidth.setSingleStep(1.0)
        self.doubleSpinBoxBandstopWidth.setProperty("value", 1.0)
        self.doubleSpinBoxBandstopWidth.setObjectName(_fromUtf8("doubleSpinBoxBandstopWidth"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxBandstopWidth)
        self.labelBandstopFilterLength = QtGui.QLabel(self.frame_3)
        self.labelBandstopFilterLength.setObjectName(_fromUtf8("labelBandstopFilterLength"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelBandstopFilterLength)
        self.lineEditBandstopLength = QtGui.QLineEdit(self.frame_3)
        self.lineEditBandstopLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditBandstopLength.setObjectName(_fromUtf8("lineEditBandstopLength"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditBandstopLength)
        self.gridLayout_5.addWidget(self.frame_3, 1, 0, 1, 1)
        self.checkBoxBandstop = QtGui.QCheckBox(self.frameBandPass)
        self.checkBoxBandstop.setObjectName(_fromUtf8("checkBoxBandstop"))
        self.gridLayout_5.addWidget(self.checkBoxBandstop, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frameBandPass, 1, 0, 1, 1)
        self.frameBandStop_3 = QtGui.QFrame(self.frameFilterSelection)
        self.frameBandStop_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameBandStop_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frameBandStop_3.setObjectName(_fromUtf8("frameBandStop_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frameBandStop_3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.frame_4 = QtGui.QFrame(self.frameBandStop_3)
        self.frame_4.setEnabled(False)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.frame_4)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.labelBandStopFreq2 = QtGui.QLabel(self.frame_4)
        self.labelBandStopFreq2.setObjectName(_fromUtf8("labelBandStopFreq2"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelBandStopFreq2)
        self.doubleSpinBoxBandstopFreq2 = QtGui.QDoubleSpinBox(self.frame_4)
        self.doubleSpinBoxBandstopFreq2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandstopFreq2.setDecimals(3)
        self.doubleSpinBoxBandstopFreq2.setMaximum(10000.0)
        self.doubleSpinBoxBandstopFreq2.setSingleStep(10.0)
        self.doubleSpinBoxBandstopFreq2.setProperty("value", 100.0)
        self.doubleSpinBoxBandstopFreq2.setObjectName(_fromUtf8("doubleSpinBoxBandstopFreq2"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxBandstopFreq2)
        self.labelBandStopNotchWidth2 = QtGui.QLabel(self.frame_4)
        self.labelBandStopNotchWidth2.setObjectName(_fromUtf8("labelBandStopNotchWidth2"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelBandStopNotchWidth2)
        self.doubleSpinBoxBandstopWidth2 = QtGui.QDoubleSpinBox(self.frame_4)
        self.doubleSpinBoxBandstopWidth2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandstopWidth2.setDecimals(3)
        self.doubleSpinBoxBandstopWidth2.setMaximum(10000.0)
        self.doubleSpinBoxBandstopWidth2.setSingleStep(1.0)
        self.doubleSpinBoxBandstopWidth2.setProperty("value", 1.0)
        self.doubleSpinBoxBandstopWidth2.setObjectName(_fromUtf8("doubleSpinBoxBandstopWidth2"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxBandstopWidth2)
        self.labelBandstopFilterLength2 = QtGui.QLabel(self.frame_4)
        self.labelBandstopFilterLength2.setObjectName(_fromUtf8("labelBandstopFilterLength2"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelBandstopFilterLength2)
        self.lineEditBandstopLength2 = QtGui.QLineEdit(self.frame_4)
        self.lineEditBandstopLength2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditBandstopLength2.setObjectName(_fromUtf8("lineEditBandstopLength2"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditBandstopLength2)
        self.gridLayout_7.addWidget(self.frame_4, 1, 0, 1, 1)
        self.checkBoxBandstop2 = QtGui.QCheckBox(self.frameBandStop_3)
        self.checkBoxBandstop2.setObjectName(_fromUtf8("checkBoxBandstop2"))
        self.gridLayout_7.addWidget(self.checkBoxBandstop2, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frameBandStop_3, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.frameFilterSelection, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonPreview = QtGui.QPushButton(DialogFilter)
        self.pushButtonPreview.setEnabled(True)
        self.pushButtonPreview.setObjectName(_fromUtf8("pushButtonPreview"))
        self.horizontalLayout.addWidget(self.pushButtonPreview)
        self.buttonBox = QtGui.QDialogButtonBox(DialogFilter)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(DialogFilter)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DialogFilter.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DialogFilter.reject)
        QtCore.QObject.connect(self.checkBoxLowpass, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame.setEnabled)
        QtCore.QObject.connect(self.checkBoxHighpass, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame_2.setEnabled)
        QtCore.QObject.connect(self.checkBoxBandstop, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame_3.setEnabled)
        QtCore.QObject.connect(self.checkBoxBandstop2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame_4.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(DialogFilter)
        DialogFilter.setTabOrder(self.checkBoxLowpass, self.doubleSpinBoxLowpassCutoff)
        DialogFilter.setTabOrder(self.doubleSpinBoxLowpassCutoff, self.doubleSpinBoxLowpassTransBandwidth)
        DialogFilter.setTabOrder(self.doubleSpinBoxLowpassTransBandwidth, self.lineEditLowpassLength)
        DialogFilter.setTabOrder(self.lineEditLowpassLength, self.checkBoxHighpass)
        DialogFilter.setTabOrder(self.checkBoxHighpass, self.doubleSpinBoxHighpassCutoff)
        DialogFilter.setTabOrder(self.doubleSpinBoxHighpassCutoff, self.doubleSpinBoxHighpassTransBandwidth)
        DialogFilter.setTabOrder(self.doubleSpinBoxHighpassTransBandwidth, self.lineEditHighpassLength)
        DialogFilter.setTabOrder(self.lineEditHighpassLength, self.checkBoxBandstop)
        DialogFilter.setTabOrder(self.checkBoxBandstop, self.doubleSpinBoxBandstopFreq)
        DialogFilter.setTabOrder(self.doubleSpinBoxBandstopFreq, self.doubleSpinBoxBandstopWidth)
        DialogFilter.setTabOrder(self.doubleSpinBoxBandstopWidth, self.lineEditBandstopLength)
        DialogFilter.setTabOrder(self.lineEditBandstopLength, self.checkBoxBandstop2)
        DialogFilter.setTabOrder(self.checkBoxBandstop2, self.doubleSpinBoxBandstopFreq2)
        DialogFilter.setTabOrder(self.doubleSpinBoxBandstopFreq2, self.doubleSpinBoxBandstopWidth2)
        DialogFilter.setTabOrder(self.doubleSpinBoxBandstopWidth2, self.lineEditBandstopLength2)
        DialogFilter.setTabOrder(self.lineEditBandstopLength2, self.pushButtonPreview)

    def retranslateUi(self, DialogFilter):
        DialogFilter.setWindowTitle(_translate("DialogFilter", "Filtering", None))
        self.labelHighpassCutoff.setText(_translate("DialogFilter", "Cutoff frequency:", None))
        self.doubleSpinBoxHighpassCutoff.setSuffix(_translate("DialogFilter", " Hz", None))
        self.labelHighpassTransitionWidth.setText(_translate("DialogFilter", "Transition band width:", None))
        self.doubleSpinBoxHighpassTransBandwidth.setSuffix(_translate("DialogFilter", " Hz", None))
        self.labelHighpassFilterLength.setText(_translate("DialogFilter", "Filter length:", None))
        self.lineEditHighpassLength.setPlaceholderText(_translate("DialogFilter", "e.g. 10s, 500ms", None))
        self.checkBoxHighpass.setText(_translate("DialogFilter", "Highpass filter", None))
        self.labelLowpassCutoff.setText(_translate("DialogFilter", "Cutoff frequency:", None))
        self.doubleSpinBoxLowpassCutoff.setSuffix(_translate("DialogFilter", " Hz", None))
        self.labelLowpassTransitionWidth.setText(_translate("DialogFilter", "Transition band width:", None))
        self.doubleSpinBoxLowpassTransBandwidth.setSuffix(_translate("DialogFilter", " Hz", None))
        self.labelLowpassFilterLength.setText(_translate("DialogFilter", "Filter length:", None))
        self.lineEditLowpassLength.setPlaceholderText(_translate("DialogFilter", "e.g. 10s, 500ms", None))
        self.checkBoxLowpass.setText(_translate("DialogFilter", "Lowpass filter", None))
        self.labelBandStopFreq.setText(_translate("DialogFilter", "Notch frequency:", None))
        self.doubleSpinBoxBandstopFreq.setSuffix(_translate("DialogFilter", " Hz", None))
        self.labelBandStopNotchWidth.setText(_translate("DialogFilter", "Band width:", None))
        self.doubleSpinBoxBandstopWidth.setSuffix(_translate("DialogFilter", " Hz", None))
        self.labelBandstopFilterLength.setText(_translate("DialogFilter", "Filter length:", None))
        self.lineEditBandstopLength.setPlaceholderText(_translate("DialogFilter", "e.g. 10s, 500ms", None))
        self.checkBoxBandstop.setText(_translate("DialogFilter", "BandStop filter (notch)", None))
        self.labelBandStopFreq2.setText(_translate("DialogFilter", "Notch frequency:", None))
        self.doubleSpinBoxBandstopFreq2.setSuffix(_translate("DialogFilter", " Hz", None))
        self.labelBandStopNotchWidth2.setText(_translate("DialogFilter", "Band width:", None))
        self.doubleSpinBoxBandstopWidth2.setSuffix(_translate("DialogFilter", " Hz", None))
        self.labelBandstopFilterLength2.setText(_translate("DialogFilter", "Filter length:", None))
        self.lineEditBandstopLength2.setPlaceholderText(_translate("DialogFilter", "e.g. 10s, 500ms", None))
        self.checkBoxBandstop2.setText(_translate("DialogFilter", "BandStop filter (notch)", None))
        self.pushButtonPreview.setText(_translate("DialogFilter", "Preview with given filters", None))

