# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer_ui_files/mainWindowTabInducedUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindowTabInduced(object):
    def setupUi(self, mainWindowTabInduced):
        mainWindowTabInduced.setObjectName("mainWindowTabInduced")
        mainWindowTabInduced.resize(997, 601)
        self.layoutWidget = QtWidgets.QWidget(mainWindowTabInduced)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 981, 581))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.groupBoxEpochs = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBoxEpochs.setTitle("")
        self.groupBoxEpochs.setObjectName("groupBoxEpochs")
        self.verticalLayout_23.addWidget(self.groupBoxEpochs)
        self.groupBoxComputations = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBoxComputations.setMinimumSize(QtCore.QSize(400, 0))
        self.groupBoxComputations.setObjectName("groupBoxComputations")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxComputations)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonComputeTFR = QtWidgets.QPushButton(self.groupBoxComputations)
        self.pushButtonComputeTFR.setObjectName("pushButtonComputeTFR")
        self.gridLayout_2.addWidget(self.pushButtonComputeTFR, 0, 0, 1, 1)
        self.verticalLayout_23.addWidget(self.groupBoxComputations)
        self.gridLayout_15.addLayout(self.verticalLayout_23, 0, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBoxTFR = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBoxTFR.setMinimumSize(QtCore.QSize(0, 300))
        self.groupBoxTFR.setObjectName("groupBoxTFR")
        self.formLayout = QtWidgets.QFormLayout(self.groupBoxTFR)
        self.formLayout.setObjectName("formLayout")
        self.labelTFRInfo = QtWidgets.QLabel(self.groupBoxTFR)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelTFRInfo.setFont(font)
        self.labelTFRInfo.setObjectName("labelTFRInfo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelTFRInfo)
        self.listWidgetTFR = QtWidgets.QListWidget(self.groupBoxTFR)
        self.listWidgetTFR.setObjectName("listWidgetTFR")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.listWidgetTFR)
        self.textBrowserTFRInfo = QtWidgets.QTextBrowser(self.groupBoxTFR)
        self.textBrowserTFRInfo.setObjectName("textBrowserTFRInfo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.textBrowserTFRInfo)
        self.verticalLayout_6.addWidget(self.groupBoxTFR)
        self.groupBoxTFRActions = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBoxTFRActions.setObjectName("groupBoxTFRActions")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxTFRActions)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBoxTFRActions)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonPlotTFR = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonPlotTFR.setObjectName("pushButtonPlotTFR")
        self.horizontalLayout_2.addWidget(self.pushButtonPlotTFR)
        self.pushButtonPlotTSE = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonPlotTSE.setObjectName("pushButtonPlotTSE")
        self.horizontalLayout_2.addWidget(self.pushButtonPlotTSE)
        self.gridLayout_21.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonDeleteTFR = QtWidgets.QPushButton(self.groupBoxTFRActions)
        self.pushButtonDeleteTFR.setObjectName("pushButtonDeleteTFR")
        self.gridLayout.addWidget(self.pushButtonDeleteTFR, 1, 0, 1, 1)
        self.pushButtonGroupAverage = QtWidgets.QPushButton(self.groupBoxTFRActions)
        self.pushButtonGroupAverage.setObjectName("pushButtonGroupAverage")
        self.gridLayout.addWidget(self.pushButtonGroupAverage, 0, 0, 1, 1)
        self.pushButtonGroupDeleteTFR = QtWidgets.QPushButton(self.groupBoxTFRActions)
        self.pushButtonGroupDeleteTFR.setObjectName("pushButtonGroupDeleteTFR")
        self.gridLayout.addWidget(self.pushButtonGroupDeleteTFR, 2, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBoxTFRActions)
        self.gridLayout_15.addLayout(self.verticalLayout_6, 0, 1, 1, 1)

        self.retranslateUi(mainWindowTabInduced)
        QtCore.QMetaObject.connectSlotsByName(mainWindowTabInduced)

    def retranslateUi(self, mainWindowTabInduced):
        _translate = QtCore.QCoreApplication.translate
        mainWindowTabInduced.setWindowTitle(_translate("mainWindowTabInduced", "Form"))
        self.groupBoxComputations.setTitle(_translate("mainWindowTabInduced", "Computations:"))
        self.pushButtonComputeTFR.setText(_translate("mainWindowTabInduced", "Compute TFR..."))
        self.groupBoxTFR.setTitle(_translate("mainWindowTabInduced", "TFR\'s"))
        self.labelTFRInfo.setText(_translate("mainWindowTabInduced", "TFR info"))
        self.groupBoxTFRActions.setTitle(_translate("mainWindowTabInduced", "Available actions for TFR\'s:"))
        self.groupBox_2.setTitle(_translate("mainWindowTabInduced", "Visualization:"))
        self.pushButtonPlotTFR.setText(_translate("mainWindowTabInduced", "Plot TFR..."))
        self.pushButtonPlotTSE.setText(_translate("mainWindowTabInduced", "Plot TSE..."))
        self.pushButtonDeleteTFR.setText(_translate("mainWindowTabInduced", "Delete selected TFR"))
        self.pushButtonGroupAverage.setText(_translate("mainWindowTabInduced", "Group average for all subjects"))
        self.pushButtonGroupDeleteTFR.setText(_translate("mainWindowTabInduced", "Group delete selected TFR"))

