# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maxFilterDialog.ui'
#
# Created: Thu Mar 28 12:34:36 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setEnabled(True)
        Dialog.resize(462, 723)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(100, 660, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 380, 409, 131))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.checkBoxtSSS = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxtSSS.setEnabled(True)
        self.checkBoxtSSS.setChecked(True)
        self.checkBoxtSSS.setObjectName(_fromUtf8("checkBoxtSSS"))
        self.verticalLayout_2.addWidget(self.checkBoxtSSS)
        self.frame = QtGui.QFrame(self.layoutWidget)
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayoutWidget = QtGui.QWidget(self.frame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 10, 401, 81))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelDataBufferLength = QtGui.QLabel(self.formLayoutWidget)
        self.labelDataBufferLength.setObjectName(_fromUtf8("labelDataBufferLength"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelDataBufferLength)
        self.lineEditDataBufferLength = QtGui.QLineEdit(self.formLayoutWidget)
        self.lineEditDataBufferLength.setObjectName(_fromUtf8("lineEditDataBufferLength"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditDataBufferLength)
        self.labelSubspaceCorrelationLimit = QtGui.QLabel(self.formLayoutWidget)
        self.labelSubspaceCorrelationLimit.setObjectName(_fromUtf8("labelSubspaceCorrelationLimit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelSubspaceCorrelationLimit)
        self.lineEditSubspaceCorrelationLimit = QtGui.QLineEdit(self.formLayoutWidget)
        self.lineEditSubspaceCorrelationLimit.setObjectName(_fromUtf8("lineEditSubspaceCorrelationLimit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditSubspaceCorrelationLimit)
        self.verticalLayout_2.addWidget(self.frame)
        self.layoutWidget_4 = QtGui.QWidget(Dialog)
        self.layoutWidget_4.setGeometry(QtCore.QRect(30, 520, 409, 131))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.checkBoxMaxMove = QtGui.QCheckBox(self.layoutWidget_4)
        self.checkBoxMaxMove.setEnabled(True)
        self.checkBoxMaxMove.setChecked(True)
        self.checkBoxMaxMove.setObjectName(_fromUtf8("checkBoxMaxMove"))
        self.verticalLayout_4.addWidget(self.checkBoxMaxMove)
        self.frame_2 = QtGui.QFrame(self.layoutWidget_4)
        self.frame_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.formLayoutWidget_3 = QtGui.QWidget(self.frame_2)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(9, 10, 391, 80))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.formLayout_3.setLayout(2, QtGui.QFormLayout.LabelRole, self.formLayout_4)
        self.labelHPI = QtGui.QLabel(self.formLayoutWidget_3)
        self.labelHPI.setObjectName(_fromUtf8("labelHPI"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelHPI)
        self.lineEditHPI = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.lineEditHPI.setObjectName(_fromUtf8("lineEditHPI"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditHPI)
        self.labelHPIStep = QtGui.QLabel(self.formLayoutWidget_3)
        self.labelHPIStep.setObjectName(_fromUtf8("labelHPIStep"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelHPIStep)
        self.lineEditHPIStep = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.lineEditHPIStep.setObjectName(_fromUtf8("lineEditHPIStep"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditHPIStep)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.layoutWidget1 = QtGui.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 30, 409, 341))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelOrigin = QtGui.QLabel(self.layoutWidget1)
        self.labelOrigin.setObjectName(_fromUtf8("labelOrigin"))
        self.horizontalLayout_3.addWidget(self.labelOrigin)
        self.labelX0 = QtGui.QLabel(self.layoutWidget1)
        self.labelX0.setObjectName(_fromUtf8("labelX0"))
        self.horizontalLayout_3.addWidget(self.labelX0)
        self.lineEditX0 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEditX0.setObjectName(_fromUtf8("lineEditX0"))
        self.horizontalLayout_3.addWidget(self.lineEditX0)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.labelY0 = QtGui.QLabel(self.layoutWidget1)
        self.labelY0.setObjectName(_fromUtf8("labelY0"))
        self.horizontalLayout_4.addWidget(self.labelY0)
        self.lineEditY0 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEditY0.setObjectName(_fromUtf8("lineEditY0"))
        self.horizontalLayout_4.addWidget(self.lineEditY0)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.labelZ0 = QtGui.QLabel(self.layoutWidget1)
        self.labelZ0.setObjectName(_fromUtf8("labelZ0"))
        self.horizontalLayout_5.addWidget(self.labelZ0)
        self.lineEditZ0 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEditZ0.setObjectName(_fromUtf8("lineEditZ0"))
        self.horizontalLayout_5.addWidget(self.lineEditZ0)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.checkBoxFit = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBoxFit.setObjectName(_fromUtf8("checkBoxFit"))
        self.horizontalLayout_7.addWidget(self.checkBoxFit)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.labelOrderIn = QtGui.QLabel(self.layoutWidget1)
        self.labelOrderIn.setObjectName(_fromUtf8("labelOrderIn"))
        self.horizontalLayout_8.addWidget(self.labelOrderIn)
        self.lineEditOrderIn = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEditOrderIn.setObjectName(_fromUtf8("lineEditOrderIn"))
        self.horizontalLayout_8.addWidget(self.lineEditOrderIn)
        self.labelOrderOut = QtGui.QLabel(self.layoutWidget1)
        self.labelOrderOut.setObjectName(_fromUtf8("labelOrderOut"))
        self.horizontalLayout_8.addWidget(self.labelOrderOut)
        self.lineEditOrderOut = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEditOrderOut.setObjectName(_fromUtf8("lineEditOrderOut"))
        self.horizontalLayout_8.addWidget(self.lineEditOrderOut)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelBadLimit = QtGui.QLabel(self.layoutWidget1)
        self.labelBadLimit.setObjectName(_fromUtf8("labelBadLimit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelBadLimit)
        self.lineEditBadLimit = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEditBadLimit.setObjectName(_fromUtf8("lineEditBadLimit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditBadLimit)
        self.labelBad = QtGui.QLabel(self.layoutWidget1)
        self.labelBad.setObjectName(_fromUtf8("labelBad"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelBad)
        self.lineEditBad = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEditBad.setObjectName(_fromUtf8("lineEditBad"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditBad)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_5.addWidget(self.label_3)
        self.radioButtonFloat = QtGui.QRadioButton(self.layoutWidget1)
        self.radioButtonFloat.setChecked(True)
        self.radioButtonFloat.setObjectName(_fromUtf8("radioButtonFloat"))
        self.buttonGroup = QtGui.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButtonFloat)
        self.verticalLayout_5.addWidget(self.radioButtonFloat)
        self.radioButtonLong = QtGui.QRadioButton(self.layoutWidget1)
        self.radioButtonLong.setObjectName(_fromUtf8("radioButtonLong"))
        self.buttonGroup.addButton(self.radioButtonLong)
        self.verticalLayout_5.addWidget(self.radioButtonLong)
        self.radioButtonShort = QtGui.QRadioButton(self.layoutWidget1)
        self.radioButtonShort.setObjectName(_fromUtf8("radioButtonShort"))
        self.buttonGroup.addButton(self.radioButtonShort)
        self.verticalLayout_5.addWidget(self.radioButtonShort)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.formLayout_2.setLayout(3, QtGui.QFormLayout.LabelRole, self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_6.addWidget(self.label_4)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEditSkipEnd_1 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEditSkipEnd_1.setEnabled(False)
        self.lineEditSkipEnd_1.setObjectName(_fromUtf8("lineEditSkipEnd_1"))
        self.gridLayout.addWidget(self.lineEditSkipEnd_1, 1, 3, 1, 1)
        self.lineEditSkipStart_3 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEditSkipStart_3.setEnabled(False)
        self.lineEditSkipStart_3.setObjectName(_fromUtf8("lineEditSkipStart_3"))
        self.gridLayout.addWidget(self.lineEditSkipStart_3, 3, 1, 1, 2)
        self.lineEditSkipEnd_2 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEditSkipEnd_2.setEnabled(False)
        self.lineEditSkipEnd_2.setObjectName(_fromUtf8("lineEditSkipEnd_2"))
        self.gridLayout.addWidget(self.lineEditSkipEnd_2, 2, 3, 1, 1)
        self.lineEditSkipEnd_3 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEditSkipEnd_3.setEnabled(False)
        self.lineEditSkipEnd_3.setObjectName(_fromUtf8("lineEditSkipEnd_3"))
        self.gridLayout.addWidget(self.lineEditSkipEnd_3, 3, 3, 1, 1)
        self.checkBoxSkip_1 = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBoxSkip_1.setObjectName(_fromUtf8("checkBoxSkip_1"))
        self.gridLayout.addWidget(self.checkBoxSkip_1, 1, 0, 1, 1)
        self.checkBoxSkip_2 = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBoxSkip_2.setEnabled(False)
        self.checkBoxSkip_2.setObjectName(_fromUtf8("checkBoxSkip_2"))
        self.gridLayout.addWidget(self.checkBoxSkip_2, 2, 0, 1, 1)
        self.lineEditSkipStart_1 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEditSkipStart_1.setEnabled(False)
        self.lineEditSkipStart_1.setObjectName(_fromUtf8("lineEditSkipStart_1"))
        self.gridLayout.addWidget(self.lineEditSkipStart_1, 1, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.checkBoxSkip_3 = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBoxSkip_3.setEnabled(False)
        self.checkBoxSkip_3.setObjectName(_fromUtf8("checkBoxSkip_3"))
        self.gridLayout.addWidget(self.checkBoxSkip_3, 3, 0, 1, 1)
        self.lineEditSkipStart_2 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEditSkipStart_2.setEnabled(False)
        self.lineEditSkipStart_2.setObjectName(_fromUtf8("lineEditSkipStart_2"))
        self.gridLayout.addWidget(self.lineEditSkipStart_2, 2, 1, 1, 2)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.formLayout_2.setLayout(3, QtGui.QFormLayout.FieldRole, self.verticalLayout_6)
        self.verticalLayout.addLayout(self.formLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.checkBoxtSSS, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame.setVisible)
        QtCore.QObject.connect(self.checkBoxSkip_1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEditSkipStart_1.setEnabled)
        QtCore.QObject.connect(self.checkBoxSkip_1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEditSkipEnd_1.setEnabled)
        QtCore.QObject.connect(self.checkBoxSkip_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEditSkipStart_2.setEnabled)
        QtCore.QObject.connect(self.checkBoxSkip_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEditSkipEnd_2.setEnabled)
        QtCore.QObject.connect(self.checkBoxSkip_3, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEditSkipStart_3.setEnabled)
        QtCore.QObject.connect(self.checkBoxSkip_3, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEditSkipEnd_3.setEnabled)
        QtCore.QObject.connect(self.checkBoxSkip_1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBoxSkip_2.setEnabled)
        QtCore.QObject.connect(self.checkBoxSkip_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBoxSkip_3.setEnabled)
        QtCore.QObject.connect(self.checkBoxMaxMove, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame_2.setVisible)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.checkBoxtSSS.setText(_translate("Dialog", "tSSS", None))
        self.labelDataBufferLength.setText(_translate("Dialog", "Data buffer length (s):", None))
        self.lineEditDataBufferLength.setText(_translate("Dialog", "10", None))
        self.labelSubspaceCorrelationLimit.setText(_translate("Dialog", "Subspace correlation limit:", None))
        self.lineEditSubspaceCorrelationLimit.setText(_translate("Dialog", "0.98", None))
        self.checkBoxMaxMove.setText(_translate("Dialog", "MaxMove", None))
        self.labelHPI.setText(_translate("Dialog", "HPI signal amp extraction window (ms):", None))
        self.lineEditHPI.setText(_translate("Dialog", "200", None))
        self.labelHPIStep.setText(_translate("Dialog", "Step to move HPI window (ms):", None))
        self.lineEditHPIStep.setText(_translate("Dialog", "10", None))
        self.labelOrigin.setText(_translate("Dialog", "Origin:", None))
        self.labelX0.setText(_translate("Dialog", "x0", None))
        self.labelY0.setText(_translate("Dialog", "y0", None))
        self.labelZ0.setText(_translate("Dialog", "z0", None))
        self.checkBoxFit.setText(_translate("Dialog", "Fit to isotrak points", None))
        self.labelOrderIn.setText(_translate("Dialog", "Order in:", None))
        self.labelOrderOut.setText(_translate("Dialog", "Order out:", None))
        self.labelBadLimit.setText(_translate("Dialog", "Threshold for bads:", None))
        self.labelBad.setText(_translate("Dialog", "Bad channels:", None))
        self.label_3.setText(_translate("Dialog", "Output format:", None))
        self.radioButtonFloat.setText(_translate("Dialog", "Float (32 bits)", None))
        self.radioButtonLong.setText(_translate("Dialog", "Long (32 bits)", None))
        self.radioButtonShort.setText(_translate("Dialog", "Short (16 bits)", None))
        self.label_4.setText(_translate("Dialog", "Data skips:", None))
        self.checkBoxSkip_1.setText(_translate("Dialog", "S1", None))
        self.checkBoxSkip_2.setText(_translate("Dialog", "S2", None))
        self.label_5.setText(_translate("Dialog", "Start (sec)", None))
        self.label_6.setText(_translate("Dialog", "End (sec)", None))
        self.checkBoxSkip_3.setText(_translate("Dialog", "S3", None))

