# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'infoDialog.ui'
#
# Created: Thu Mar 14 10:26:43 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_infoDialog(object):
    def setupUi(self, infoDialog):
        infoDialog.setObjectName(_fromUtf8("infoDialog"))
        infoDialog.resize(455, 425)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(infoDialog.sizePolicy().hasHeightForWidth())
        infoDialog.setSizePolicy(sizePolicy)
        self.ButtonClose = QtGui.QPushButton(infoDialog)
        self.ButtonClose.setGeometry(QtCore.QRect(340, 390, 75, 23))
        self.ButtonClose.setObjectName(_fromUtf8("ButtonClose"))
        self.layoutWidget = QtGui.QWidget(infoDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(22, 22, 301, 391))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.metaBox = QtGui.QGroupBox(self.layoutWidget)
        self.metaBox.setObjectName(_fromUtf8("metaBox"))
        self.layoutWidget1 = QtGui.QWidget(self.metaBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(26, 35, 113, 23))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.labelDate = QtGui.QLabel(self.layoutWidget1)
        self.labelDate.setObjectName(_fromUtf8("labelDate"))
        self.gridLayout_3.addWidget(self.labelDate, 0, 0, 1, 1)
        self.labelDateValue = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDateValue.sizePolicy().hasHeightForWidth())
        self.labelDateValue.setSizePolicy(sizePolicy)
        self.labelDateValue.setObjectName(_fromUtf8("labelDateValue"))
        self.gridLayout_3.addWidget(self.labelDateValue, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.metaBox)
        self.filtersBox = QtGui.QGroupBox(self.layoutWidget)
        self.filtersBox.setObjectName(_fromUtf8("filtersBox"))
        self.layoutWidget2 = QtGui.QWidget(self.filtersBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(23, 31, 181, 77))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelLow = QtGui.QLabel(self.layoutWidget2)
        self.labelLow.setLineWidth(1)
        self.labelLow.setScaledContents(True)
        self.labelLow.setObjectName(_fromUtf8("labelLow"))
        self.gridLayout_2.addWidget(self.labelLow, 0, 0, 1, 1)
        self.labelLowValue = QtGui.QLabel(self.layoutWidget2)
        self.labelLowValue.setObjectName(_fromUtf8("labelLowValue"))
        self.gridLayout_2.addWidget(self.labelLowValue, 0, 1, 1, 1)
        self.labelHigh = QtGui.QLabel(self.layoutWidget2)
        self.labelHigh.setObjectName(_fromUtf8("labelHigh"))
        self.gridLayout_2.addWidget(self.labelHigh, 1, 0, 1, 1)
        self.labelHighValue = QtGui.QLabel(self.layoutWidget2)
        self.labelHighValue.setObjectName(_fromUtf8("labelHighValue"))
        self.gridLayout_2.addWidget(self.labelHighValue, 1, 1, 1, 1)
        self.labelSfreq = QtGui.QLabel(self.layoutWidget2)
        self.labelSfreq.setObjectName(_fromUtf8("labelSfreq"))
        self.gridLayout_2.addWidget(self.labelSfreq, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.filtersBox)
        self.channelsBox = QtGui.QGroupBox(self.layoutWidget)
        self.channelsBox.setObjectName(_fromUtf8("channelsBox"))
        self.layoutWidget3 = QtGui.QWidget(self.channelsBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 23, 249, 104))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelEEG = QtGui.QLabel(self.layoutWidget3)
        self.labelEEG.setObjectName(_fromUtf8("labelEEG"))
        self.gridLayout.addWidget(self.labelEEG, 0, 0, 1, 1)
        self.labelEEGValue = QtGui.QLabel(self.layoutWidget3)
        self.labelEEGValue.setObjectName(_fromUtf8("labelEEGValue"))
        self.gridLayout.addWidget(self.labelEEGValue, 0, 1, 1, 1)
        self.labelGradMEG = QtGui.QLabel(self.layoutWidget3)
        self.labelGradMEG.setObjectName(_fromUtf8("labelGradMEG"))
        self.gridLayout.addWidget(self.labelGradMEG, 1, 0, 1, 1)
        self.labelGradMEGValue = QtGui.QLabel(self.layoutWidget3)
        self.labelGradMEGValue.setObjectName(_fromUtf8("labelGradMEGValue"))
        self.gridLayout.addWidget(self.labelGradMEGValue, 1, 1, 1, 1)
        self.labelMagMEG = QtGui.QLabel(self.layoutWidget3)
        self.labelMagMEG.setObjectName(_fromUtf8("labelMagMEG"))
        self.gridLayout.addWidget(self.labelMagMEG, 2, 0, 1, 1)
        self.labelMagMEGValue = QtGui.QLabel(self.layoutWidget3)
        self.labelMagMEGValue.setObjectName(_fromUtf8("labelMagMEGValue"))
        self.gridLayout.addWidget(self.labelMagMEGValue, 2, 1, 1, 1)
        self.labelSamples = QtGui.QLabel(self.layoutWidget3)
        self.labelSamples.setObjectName(_fromUtf8("labelSamples"))
        self.gridLayout.addWidget(self.labelSamples, 3, 0, 1, 1)
        self.labelSamplesValue = QtGui.QLabel(self.layoutWidget3)
        self.labelSamplesValue.setObjectName(_fromUtf8("labelSamplesValue"))
        self.gridLayout.addWidget(self.labelSamplesValue, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.channelsBox)

        self.retranslateUi(infoDialog)
        QtCore.QMetaObject.connectSlotsByName(infoDialog)

    def retranslateUi(self, infoDialog):
        infoDialog.setWindowTitle(_translate("infoDialog", "Measurement info", None))
        self.ButtonClose.setText(_translate("infoDialog", "Close", None))
        self.metaBox.setTitle(_translate("infoDialog", "Background", None))
        self.labelDate.setText(_translate("infoDialog", "Date:", None))
        self.labelDateValue.setText(_translate("infoDialog", "DateValue", None))
        self.filtersBox.setTitle(_translate("infoDialog", "Filters", None))
        self.labelLow.setText(_translate("infoDialog", "Low-pass:", None))
        self.labelLowValue.setText(_translate("infoDialog", "Low-pass value", None))
        self.labelHigh.setText(_translate("infoDialog", "High-pass:", None))
        self.labelHighValue.setText(_translate("infoDialog", "High-pass value", None))
        self.labelSfreq.setText(_translate("infoDialog", "TextLabel:", None))
        self.label_5.setText(_translate("infoDialog", "TextLabel", None))
        self.channelsBox.setTitle(_translate("infoDialog", "Channels", None))
        self.labelEEG.setText(_translate("infoDialog", "EEG:", None))
        self.labelEEGValue.setText(_translate("infoDialog", "EEG value", None))
        self.labelGradMEG.setText(_translate("infoDialog", "Grad. MEG:", None))
        self.labelGradMEGValue.setText(_translate("infoDialog", "Grad. MEG value", None))
        self.labelMagMEG.setText(_translate("infoDialog", "Mag. MEG:", None))
        self.labelMagMEGValue.setText(_translate("infoDialog", "Mag. MEG value", None))
        self.labelSamples.setText(_translate("infoDialog", "Sampling frequency:", None))
        self.labelSamplesValue.setText(_translate("infoDialog", "SamplesValue", None))
